### ISSUE TITLE
Ballista client fails to build with --features=standalone

### ISSUE THREAD

**Issue by Igosuki** [apache/arrow-datafusion#1000]
**Describe the bug**
```cargo check --features=standalone``` fails

**To Reproduce**
see above

**Expected behavior**
It builds

**Additional context**
Came across this while doing my default ```cargo check --all-features```

**Comment by Igosuki** [comment]
Turns out the test is also broken

**Comment by Igosuki** [comment]
I fixed it in a branch, but I have a problem with passing the test, the thing is that the spawned ArrowFlight tonic server spawned in the standalone mode gets scrapped before the new dataframe API can collect the partition through the ballista FlightClient

**Comment by houqp** [comment]
@Igosuki perhaps you can push your branch to a PR so others can help with the test issue?

**Comment by Igosuki** [comment]
https://github.com/apache/arrow-datafusion/pull/1008
