### ISSUE TITLE
[Python]: Inconsistencies with Python package name 

### ISSUE THREAD

**Issue by mmuru** [apache/arrow-datafusion#1011]
In python/Cargo.toml file, the package name is name = "datafusion-python" where as pyproject.toml the project name is datafusion. Before this change merge, the python package installed as datafusion-python but now datafusion.  

@houqp: As you mentioned, it should be called datafusion-python. Please, can you clarify this package naming? Thanks.

**Comment by houqp** [comment]
Hi @mmuru , this is intentional because the python binding is published to pypi as datafusion, not datafusion-python: https://pypi.org/project/datafusion/.

**Comment by mmuru** [comment]
@houqp: Thanks for the clarification. I closed it.
