### ISSUE TITLE
Make the conversion from logical to physical plan async

### ISSUE THREAD

**Issue by rdettai** [apache/arrow-datafusion#1012]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
As discussed in #1010, it would add a lot of flexibility to the planning to make it possible to use async methods. Thanks to #962, the statistics resolution can be delayed to the creation of the physical plan. Adding async to `TableProvider.scan()`, the method that converts the logical plan to the physical plan, will make it possible to have async statistics resolution. 

**Describe the solution you'd like**
Make the trait method `TableProvider.scan()` async and propagate that change to the outer APIs (mostly `ExecutionContext.create_physical_plan(&LogicalPlan)`)

**Describe alternatives you've considered**
- also add statistics to optimizers: that could be a next step but it is not required for now
- leave the planning sync and force `TableProvider` implementers to make their async methods sync: syncifying in Rust is pretty hard ([cloud-reader-rs](https://github.com/cloudfuse-io/cloud-readers-rs) is an example of this) and it is a huge constraint for implementers 

**Additional context**
This will also help the useage of the `ObjectStore` abstraction added in #811.

**Comment by rdettai** [comment]
This also pops a question. The state of execution context is protected by a Mutex:
```Rust
pub struct ExecutionContext {
    /// Internal state for the context
    pub state: Arc<Mutex<ExecutionContextState>>,
}
```

Why do some of its methods take `&mut self` ???

**Comment by houqp** [comment]
> Why do some of its methods take &mut self ???

Probably for no good reason, maybe it used to not be protected by mutex.
