### ISSUE TITLE
Add baseline metrics for remaining execution plan nodes

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#1019]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

We want basic understanding of where a plan's time is spent and in what operators. See https://github.com/apache/arrow-datafusion/issues/866 for more details

This information has been added (#866) for intermediate operators but not for low level readers for parquet, json, csv, and avro.

**Describe the solution you'd like**
Add "baseline" metrics (start time, stop time, output rows, and elapsed_compute) for the data source `ExecutionPlans`:
1. `ParquetExec`
2. `NdJsonExec`
3. `NdJsonExec`
4. `AvroExec`
5. `CsvExec`
6. `CrossJoinExec`
7.  `EmptyExec`
8. `MemoryExec`

**Describe alternatives you've considered**
None

**Additional context**
It should be straightforward to follow the model for adding statistics on the following PRs:
* https://github.com/apache/arrow-datafusion/pull/1004
* https://github.com/apache/arrow-datafusion/pull/960

**Comment by Dandandan** [comment]
What about `CsvExec` ?

**Comment by alamb** [comment]
Good eyes @Dandandan  -- including them in the description

**Comment by alamb** [comment]
I don't plan any more work on this ticket -- we can add metrics to other operators if there is a specific need
