### ISSUE TITLE
Ballista context::tests::test_standalone_mode test fails

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#1020]
**Describe the bug**

**To Reproduce**

```shell
cargo test -p ballista --features=standalone -- standalone
```

Fails with the following error:

```
running 1 test
test context::tests::test_standalone_mode ... FAILED

failures:

---- context::tests::test_standalone_mode stdout ----
=== [9vMWKNg/1/0] Physical plan with metrics ===
ShuffleWriterExec: None, metrics=[output_rows=0, input_rows=0, write_time=1.046337ms]
  ProjectionExec: expr=[1 as Int64(1)], metrics=[output_rows=0, elapsed_compute=NOT RECORDED]
    EmptyExec: produce_one_row=false, metrics=[]


thread 'context::tests::test_standalone_mode' panicked at 'called `Result::unwrap()` on an `Err` value: Execution("General(\"Error connecting to Ballista scheduler or executor at http://127.0.0.1:62230: tonic::transport::Error(Transport, hyper::Error(Connect, ConnectError(\\\"tcp connect error\\\", Os { code: 61, kind: ConnectionRefused, message: \\\"Connection refused\\\" })))\")")', ballista/rust/client/src/context.rs:306:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    context::tests::test_standalone_mode

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.48s

error: test failed, to rerun pass '-p ballista --lib'
```

**Expected behavior**
1. Test should pass
2. CI should include this mode so that it does not break again

**Additional context**
Reported by @Igosuki  on lucky https://github.com/apache/arrow-datafusion/issues/1000 / https://github.com/apache/arrow-datafusion/pull/1008 (see more details on https://github.com/apache/arrow-datafusion/pull/1008#issuecomment-922278692 )

**Comment by alamb** [comment]
Looks like @edrevo may have authored / last worked on this code in https://github.com/ballista-compute/ballista/pull/445 and moved them in https://github.com/apache/arrow-datafusion/pull/589. Perhaps he or @andygrove  or @houqp  have some thoughts on this ticket

**Comment by Igosuki** [comment]
Server spawned here https://github.com/apache/arrow-datafusion/blob/master/ballista/rust/executor/src/standalone.rs#L55
Executing the plan fetches the remote partition but the server isn't there at the addr provided in the partition.

**Comment by houqp** [comment]
Interesting, this test passes for me:

```
22:00:43 ❯ cargo test -p ballista --features=standalone -- standalone
    Finished test [unoptimized + debuginfo] target(s) in 0.11s
     Running unittests (target/debug/deps/ballista-250bed8f4d7a7d71)

running 1 test
test context::tests::test_standalone_mode ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.49s

   Doc-tests ballista

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.00s
```

With Linux 5.4 & rust 1.55. @alamb @Igosuki did you all run the test under Linux too?

**Comment by Igosuki** [comment]
Yeah I'm on linux like you (and rust 1.57). The command that fails is : ```cargo test --package ballista --lib context::tests::test_standalone_mode --features=standalone -- --exact --nocapture```

**Comment by alamb** [comment]
I am running on a mac and it fails as shown above for me

**Comment by thinkharderdev** [comment]
I get the same error on a mac. It seems like the executor is listening on the IPv6 loopback address but the client is trying to fetch the partition from the IPv4 loopback address:

```
INFO [ballista_executor::standalone] Ballista v0.6.0 Rust Executor listening on [::1]:62689

Error: Execution("General(\"Error connecting to Ballista scheduler or executor at http://127.0.0.1:62689: tonic::transport::Error(Transport, hyper::Error(Connect, ConnectError(\\\"tcp connect error\\\", Os { code: 61, kind: ConnectionRefused, message: \\\"Connection refused\\\" })))\")")
```
