### ISSUE TITLE
README.md link to cli.md is broken

### ISSUE THREAD

**Issue by storopoli** [apache/arrow-datafusion#1021]
If you go to the the header h2 in the `README.md`:

```markdown
## Using DataFusion as a binary

DataFusion also includes a simple command-line interactive SQL utility. See the [CLI reference](datafusion/docs/cli.md) for more information.
```

The link that points to is: https://github.com/apache/arrow-datafusion/blob/master/datafusion/docs/cli.md which is broken (deleted file)

**Comment by houqp** [comment]
Good catch @storopoli , the doc has been moved to https://github.com/apache/arrow-datafusion/blob/master/docs/source/cli/index.rst. Do you mind sending a PR to get it updated?

**Comment by storopoli** [comment]
Sure!
