### ISSUE TITLE
Test execution_plans::shuffle_writer::tests::test Fail

### ISSUE THREAD

**Issue by Ted-Jiang** [apache/arrow-datafusion#1040]
**Describe the bug**

run cargo test --no-default-features --features sled

![image](https://user-images.githubusercontent.com/37145547/134296326-ff4cb527-555e-4e0a-af7c-3aa4f3be67d1.png)

**To Reproduce**

**Expected behavior**
All test pass

**Additional context**

**Comment by Ted-Jiang** [comment]
I debug the code, find `create_hashes` func go into #[cfg(feature = "force_hash_collisions")]
I set #[cfg(not(feature = "force_hash_collisions"))] at the head of the test func still not work

**Comment by Ted-Jiang** [comment]
@alamb  Sorry for bother you, could you have a look?

**Comment by alamb** [comment]
Ho @Ted-Jiang  -- I am not familiar with ballista. Do the tests pass for you if you remove the `--features sled` option?

It seems like @edrevo  or @andygrove  may be more familiar with this code

**Comment by alamb** [comment]
FWIW when I run `cargo test --no-default-features --features sled` locally (mac, Rust 1.55) I do not see any failures

**Comment by Ted-Jiang** [comment]
@alamb  Thanks. It works for me to update `rustc` version from` 1.54 to 1.55`

I think its good to notify what version should use in Readme (or i not found it).

**Comment by alamb** [comment]
Yeah, we should definitely make it clear that we only test on the latest rust (whatever that happens to be). At this point we just don't have the maintenance bandwidth to maintain compatibility with older rust versions

**Comment by alamb** [comment]
Filed https://github.com/apache/arrow-datafusion/issues/1043 to track the doc improvement. Thanks for the report @Ted-Jiang . Closing this one for now

**Comment by Ted-Jiang** [comment]
Feel glad to help the community become better.
