### ISSUE TITLE
Update docs to make it clear that we support only the latest stable version of rust

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#1043]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
DataFusion / Ballista can (and sometimes do) fail to compile or successfully execute all tests when run with a version of Rust other than the latest stable version. 

This can cause confusion, most recently on #1040 -- https://github.com/apache/arrow-datafusion/issues/1040#issuecomment-925545971

The docs do not appear to say anything about this policy
https://github.com/apache/arrow-datafusion/search?l=YAML&q=stable

**Describe the solution you'd like**
Add a note to the docs that says DataFusion / Ballista are only tested with the latest stable version of rust

**Additional context**
I added a similar note to arrow-rs not too long ago, that we might be able to crib from: https://github.com/apache/arrow-rs/pull/726

**Comment by 1nF0rmed** [comment]
@alamb if I'm not wrong, we would want to update the [Datafusion Readme](https://github.com/apache/arrow-datafusion/blob/master/README.md) and the [Ballista Readme](https://github.com/apache/arrow-datafusion/blob/master/ballista/README.md) with a note that says we only support the latest stable version of Rust.

Also, can I base the note on the PR you mentioned in `Additional context`?

**Comment by alamb** [comment]
Thanks @1nF0rmed  !

> @alamb if I'm not wrong, we would want to update the Datafusion Readme and the Ballista Readme with a note that says we only support the latest stable version of Rust.

Yes I think that is correct

> Also, can I base the note on the PR you mentioned in Additional context?

Absolutely

**Comment by 1nF0rmed** [comment]
@alamb If it's alright, I'd like to make a PR for this

**Comment by alamb** [comment]
Please do -- that would be great

**Comment by 1nF0rmed** [comment]
Thank you for being soo responsive! 
I have raised a PR for the same. 

Would it be possible to add the `hacktoberfest` label to this?

**Comment by alamb** [comment]
> Would it be possible to add the hacktoberfest label to this issue?

Sure -- this project doesn't have a `hactoberfest` label -- do I just create one like 

![Screen Shot 2021-10-10 at 7 00 59 AM](https://user-images.githubusercontent.com/490673/136692810-48af1488-7488-4222-8068-9dac4f497968.png)

https://hacktoberfest.digitalocean.com/

**Comment by 1nF0rmed** [comment]
Yes, you can add a `hacktoberfest` label to this issue. It will get tracked then

**Comment by alamb** [comment]
Done

**Comment by 1nF0rmed** [comment]
@alamb My bad, the topic has to be added to the repo I guess. (My previous PR got tracked because they added the `hacktoberfest` topic later)

**Comment by 1nF0rmed** [comment]
Unless you have access as mentioned [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics#adding-topics-to-your-repository), 
we would have to ask IT to do it.
