### ISSUE TITLE
ARROW2: Investigate csv_query_window_with_partition_by test failure

### ISSUE THREAD

**Issue by houqp** [apache/arrow-datafusion#1057]
**Describe the bug**

Test defined at https://github.com/apache/arrow-datafusion/blob/91a450fcc3a08a65a521b555707a3a2893a85697/datafusion/tests/sql.rs#L1019-L1031

This test is passing in master, but failing in arrow2 branch. The expected result asserted in the test is:

```
"+-----------+---------+------------+------+---------+---------+---------+---------+------------------------ ---+",
"| c9        | SUM(CAS | AVG(CAST(a | COUN | MAX(CAS | MIN(CAS | FIRST_V | LAST_VA | NTH_VALUE(.c4 AS Int32) 2) |",
"+-----------+---------+------------+------+---------+---------+---------+---------+------------------------ ---+",
"| 28774375  | -16110  | -16110     | 1    | -16110  | -16110  | -16110  | -16110  |                            |",
"| 63044568  | 3917    | 3917       | 1    | 3917    | 3917    | 3917    | 3917    |                            |",
"| 141047417 | -38455  | -19227.5   | 2    | -16974  | -21481  | -16974  | -21481  |                            |",
"| 141680161 | -1114   | -1114      | 1    | -1114   | -1114   | -1114   | -1114   |                            |",
"| 145294611 | 15673   | 15673      | 1    | 15673   | 15673   | 15673   | 15673   |                            |",
"+-----------+---------+------------+------+---------+---------+---------+---------+------------------------ ---+",
```

Result from postgres:

```
c9      	sum	avg	count	max	min	first	last	nth
28774375	-16110	-16110	1	-16110	-16110	-16110	-16110	NULL
63044568	3917	3917	1	3917	3917	3917	3917	NULL
141047417	-38455	-19227.5 2	-16974	-21481	-21481	-16974	-16974
141680161	-1114	-1114	1	-1114	-1114	-1114	-1114	NULL
145294611	15673	15673	1	15673	15673	15673	15673	NULL
```

Row in question is `c9=141047417`. Notice nth value column is not null from postgres. The c3 partition (c3=36) this row belongs to has two values, so we think the asserted test result is likely wrong and we have a bug in both the master and arrow2 branches.

In arrow2 branch, the nth value yields the correct value when we sort partition by `c4` column `asc`: `over (partition by c3 order by c4 asc)`. But it also returns null when we sort partition by `c4` column `desc`: `over (partition by c3 order by c4 desc)`. When partition is not sorted, it returns null half of the time due to unstable sort. So for unknown reason, the partition size is flipping from 1 to 2 depending on the sort order :(

**Comment by houqp** [comment]
test is currently commented out, we should uncomment it once we catch up to https://github.com/apache/arrow-datafusion/pull/1059

**Comment by Jimexist** [comment]
maybe fixed by https://github.com/apache/arrow-datafusion/pull/1059

**Comment by houqp** [comment]
this test has already been reenabled in arrow2 branch.
