### ISSUE TITLE
Use `parquet2` async reader in `physical_plan/parquet`

### ISSUE THREAD

**Issue by yjshen** [apache/arrow-datafusion#1058]
This issue relies on https://github.com/apache/arrow-datafusion/pull/1010 as well as https://github.com/rdettai/arrow-datafusion/pull/1.

Please revisit `physical_plan/parquet` of all dead codes and unused variables for a throughout consideration.

**Comment by alamb** [comment]
see also https://github.com/apache/arrow-datafusion/issues/1532

**Comment by tustvold** [comment]
Closing as duplicate of #1532
