### ISSUE TITLE
Implement the rest of Set Operators: INTERSECT, EXCEPT, etc

### ISSUE THREAD

**Issue by xudong963** [apache/arrow-datafusion#1082]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

- [x] INTERSECT
- [x] INTERSECT ALL
- [x] EXCEPT 
- [x] EXCEPT ALL

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by xudong963** [comment]
Please assign me, thanks! @houqp

**Comment by xudong963** [comment]
First of all, I'll implement `INTERSECT`
My direct idea is to rewrite it to `left-semi Join`

such as
```sql
SELECT a1 FROM t1 INTERSECT SELECT a2 FROM t2;

to

SELECT DISTINCT a1 FROM t1 LEFT SEMI JOIN t2 ON a1 is distinct from a2
```
How do you think about it? @houqp @alamb @Dandandan 

If it's ok, I think I should implement `is distinct from` firstly.  https://www.postgresql.org/docs/14/functions-comparison.html

**Comment by alamb** [comment]
Creating / using `is distinct from` makes sense to me 👍  ). Good thinking @xudong963

**Comment by Dandandan** [comment]
It looks like PostgreSQL has some explicit operator (`HashSetOp`) for these kind of things:


```sql
> explain select * from demo intersect select * from demo;

HashSetOp Intersect  (cost=0.00..30.40 rows=160 width=458)
  ->  Append  (cost=0.00..28.00 rows=320 width=458)
        ->  Subquery Scan on "*SELECT* 1"  (cost=0.00..13.20 rows=160 width=458)
              ->  Seq Scan on demo  (cost=0.00..11.60 rows=160 width=454)
        ->  Subquery Scan on "*SELECT* 2"  (cost=0.00..13.20 rows=160 width=458)
              ->  Seq Scan on demo demo_1  (cost=0.00..11.60 rows=160 width=454)
```

**Comment by alamb** [comment]
I can see the potential benefit of implementing some special physical operator to implement INTERSECT / EXCEPT -- it might be potentially faster than the general purpose join operator

However, that being said, using a general purpose SEMI join as you have suggested @xudong963  would definitely be my preference to keep the DF code base simpler, unless there is some compelling performance measurement / need for a faster implementation

**Comment by alamb** [comment]
@Dandandan  has made https://github.com/apache/arrow-datafusion/pull/1117 to add `is distinct from`

**Comment by xudong963** [comment]
After https://github.com/apache/arrow-datafusion/pull/1135 merged, I believe the issue will be closed quickly, because on the basis of https://github.com/apache/arrow-datafusion/pull/1135, `EXCEPT` can be implemented by `ANTI JOIN` with `null_equal_null`.

**Comment by xudong963** [comment]
The issue needs to reopen, there are other things to do, such as `Expect` support. @alamb

**Comment by alamb** [comment]
Reopening as github API got a little too excited

**Comment by xudong963** [comment]
All related PRs have finished, after merging, the issue can be closed. Thanks for your help! @alamb @Dandandan @houqp
