### ISSUE TITLE
Add roadmap for datafusion

### ISSUE THREAD

**Issue by xudong963** [apache/arrow-datafusion#1102]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
The issue just is a proposal. 
As todos in the README file become less and less, I think it's better to have a clear roadmap for datafusion, like https://github.com/ClickHouse/ClickHouse/issues/17623.

**Describe the solution you'd like**
As a newer to datafusion, I don't have enough ability to complete the issue. But I'm very happy to participant in the development of roadmap！

**Describe alternatives you've considered**
There are two advantages to have a roadmap
1. Newcomers can clearly choose the tasks they can do, and then quickly participate in datafusion
2. Goals drive development and make datafusion stronger and stronger. 

**Additional context**

**Comment by alamb** [comment]
Also related: https://news.ycombinator.com/item?id=28290616
