### ISSUE TITLE
add a Java wrapper for datafusion

### ISSUE THREAD

**Issue by Jimexist** [apache/arrow-datafusion#1108]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

A challenge to add a Java wrapper for datafusion, so that we can leverage Rust's speed and memory management and also Java's eco-system.

**Describe the solution you'd like**

Unlike Python where we have `maturin` - an easy to use binding to Rust, I'm trying to use JNI in this case but that requires handling memory on/off heap. One way to achieve this is to leverage Arrow's IPC between Java and Rust.

**Describe alternatives you've considered**

**Additional context**

**Comment by Dandandan** [comment]
I agree this could be done better in a separate repo.
If it's mature enough to be considered in the repository, we can decide to do so.

**Comment by houqp** [comment]
it looks like everyone is having mono repo PTSD here :D

**Comment by Jimexist** [comment]
for the moment let me put this [here][1], once ready i can transfer it under apache org

[1]: https://github.com/Jimexist/datafusion-java
