### ISSUE TITLE
Export C API

### ISSUE THREAD

**Issue by j-a-m-l** [apache/arrow-datafusion#1113]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
We (me and @kou ) would like to export the C API to allow other language bindings (#1108, #1114).

**Describe the solution you'd like**
We will use the FFI that allow exposing a C API (https://doc.rust-lang.org/nomicon/ffi.html#calling-rust-code-from-c).

**Describe alternatives you've considered**
None, since not all languages have direct bindings/FFI to Rust

**Comment by Jimexist** [comment]
I'm not sure tokio and async functions can be easily modeled.

**Comment by houqp** [comment]
i think we would need to do pull the same trick we have with our python binding.

**Comment by dsisnero** [comment]
there are several libraries made in ruby similar to py03 in python
https://github.com/danielpclark/rutie
https://github.com/matsadler/magnus

**Comment by kou** [comment]
I close this because we work on this at https://github.com/datafusion-contrib/datafusion-c .
