### ISSUE TITLE
Improve testing of optimizers using EXPLAIN

### ISSUE THREAD

**Issue by matthewmturner** [apache/arrow-datafusion#1118]
It would be very reassuring if these optimizations came with a more systematic testing routine. I agree that unit tests in this precise scenario are not very powerful. Currently we have a test here: https://github.com/apache/arrow-datafusion/blob/558d8ecfe2d1b0737de1e2548c5fbedc0ea17ada/datafusion/tests/sql.rs#L3020

that ensures that the count optimizer rule kicks in properly with `EXPLAIN [ANALYZE]`. What do you think about creating a separate integration test file called `optimizers.rs` that runs SQL queries and checks if they were optimized as expected?

_Originally posted by @rdettai in https://github.com/apache/arrow-datafusion/issues/1063#issuecomment-931390885_

**Comment by alamb** [comment]
Sounds great -- thank you @matthewmturner !

Here is another idea with additional thoughts on test cleanup if you are feeling ambitious and want to move code around: https://github.com/apache/arrow-datafusion/issues/743

In general, I think the idea of consolidating SQL optimizer "end to end" tests that use explain into `datafusion/tests/optimizers.rs` sounds like a great idea. 

If you are inspired to do this, I suggest looking through the codebase first and consolidating existing tests into optimizers.rs.

For example, there are a bunch of "explain" tests here:

https://github.com/apache/arrow-datafusion/blob/d331fa2b87b0723eca486b1951a3f734ef6276a3/datafusion/src/optimizer/filter_push_down.rs#L699-L725

I bet you could rewrite them to actually use `EXPLAIN` and `assert_batches_eq!` and they would look a lot better.

**Comment by alamb** [comment]
I believe this is now in place via https://github.com/apache/arrow-datafusion/blob/master/datafusion/optimizer/tests/integration-test.rs
