### ISSUE TITLE
  Implement "coalesce partitions" operator

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#112]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-10583

The coalesce partitions operator simply reduces the number of partitions to the specified amount.

The target partition count must be >=1

If the target partition count is >= the number of input partitions then this is a no-op and can be optimized out of the plan.

The simplest implementation would be to assign one or more input partitions to each output partition. This works well where the number of input partitions is divisible by the number of output partitions e.g. going from 64 input partitions to 8 output partitions. In other cases, the resulting partitions may have data skew e.g. going from 3 partitions to 2. It would be possible to do the partitioning at the row level but that would add a lot of overhead and the "repartition" operator should be used for that case.

**Comment by houqp** [comment]
We already have `CoalesceBatchesExec` physical plan implemented, just need to hook it up with a new logical plan node and make it accessible to our dataframe API.

**Comment by xudong963** [comment]
> However, currently it is restricted to only produce one partition

Yep, I found it. So I thought maybe the title means `coalesce batches`😁.  



> so there is more work than just connecting it to a logical plan node :( Will need to make that partition count configurable first.

No problem!

**Comment by alamb** [comment]
I think we have implemented this operator a long time ago and it seems to be working well
