### ISSUE TITLE
Ensure column names are equivalent with or without optimization

### ISSUE THREAD

**Issue by matthewmturner** [apache/arrow-datafusion#1123]
In the context of adding a new physical optimizer (#1063) the topic of column names came up.  From this, we would like to ensure that regardless of whether an optimization was performed that the output column name is the same.

I believe we will want to add tests for this that simply check output schemas of a plan that wasnt optimized and an optimized plan.  

These tests could likely belong in `datafusion/tests/optimizer.rs` which we expect to make as part of #1118 

_Originally posted by @rdettai in https://github.com/apache/arrow-datafusion/pull/1063#issuecomment-944285349_

**Comment by alamb** [comment]
I think @jackwener fixed this one in https://github.com/apache/arrow-datafusion/pull/4233
