### ISSUE TITLE
  ColumnarValue::into_array should not require batch

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#113]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-10687

ColumnarValue::into_array requires a batch argument, which is used to get the number of rows from the batch.

It would be better to just pass in the number of rows instead so that we can use this function in cases where we do not have a batch available.

**Comment by isidentical** [comment]
`into_array` now (actually since this PR by Andy, which seems quite old 😄  https://github.com/apache/arrow/pull/8740) takes the length instead of the batch itself, so I guess we can mark it as done.

**Comment by alamb** [comment]
Good idea @isidentical  -- thanks!
