### ISSUE TITLE
allow `lit` python function to support `boolean` and other types

### ISSUE THREAD

**Issue by Jimexist** [apache/arrow-datafusion#1136]
looks good to me too -- bool is a good suggestion from @houqp 

Another good set might be timestamps (`datetime.date`, etc) but perhaps we can add those as a separate PR

(nice tests, btw)

_Originally posted by @alamb in https://github.com/apache/arrow-datafusion/pull/1130#pullrequestreview-781435561_

**Comment by sunisdown** [comment]
@Jimexist seems that this issue can be closed since the python binding is moved to [datafusion-python](https://github.com/datafusion-contrib/datafusion-python)

**Comment by yjshen** [comment]
Thanks, @sunisdown. I'm closing this.

**Comment by yjshen** [comment]
Moved to https://github.com/datafusion-contrib/datafusion-python/issues/49
