### ISSUE TITLE
  Split logical expressions out into separate source files

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#114]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-10713

We should split the logical expressions out into separate source files to make the code based easier to work with.

**Comment by xudong963** [comment]
The issue seems stale.

**Comment by alamb** [comment]
I agree --  I think it is covered by https://github.com/apache/arrow-datafusion/issues/1750
