### ISSUE TITLE
  Split the logical operators out into separate source files

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#115]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-10714

We should split the logical operators out into separate source files to make the code base easier to work with.

**Comment by HaoYang670** [comment]
Could you please give more detail?

**Comment by alamb** [comment]
I am not sure -- @andygrove  filed the original ticket here https://issues.apache.org/jira/browse/ARROW-10714 

This one may not be relevant any more? I am not sure.

**Comment by liukun4515** [comment]
> Could you please give more detail?

Maybe this is an out-of-data issue migrated from jira.

**Comment by alamb** [comment]
I agree with @liukun4515  -- closing this ticket for now, and we can reopen it if we get some more information to make it actionable
