### ISSUE TITLE
apply constant folding to LogicalPlan::Values

### ISSUE THREAD

**Issue by Jimexist** [apache/arrow-datafusion#1170]
I suspect it is not likely to matter, but constant folding could be applied to the `Expr`s in `values`. As written this code will not apply constant folding to those expressions

_Originally posted by @alamb in https://github.com/apache/arrow-datafusion/pull/1165#discussion_r734958657_

**Comment by viirya** [comment]
Hmm, I actually saw `LogicalPlan::Values` in constant folding optimizer rule now. Is this already resolved?

**Comment by viirya** [comment]
Ran a test:

```rust
    #[test]
    fn optimize_plan_support_values() -> Result<()> {
        let expr1 = Expr::BinaryExpr {
            left: Box::new(lit(1)),
            op: Operator::Plus,
            right: Box::new(lit(2)),
        };
        let expr2 = Expr::BinaryExpr {
            left: Box::new(lit(2)),
            op: Operator::Minus,
            right: Box::new(lit(1)),
        };
        let values = vec![vec![expr1, expr2]];
        let plan = LogicalPlanBuilder::values(values)?.build()?;

        let expected = "\
        Values: (Int32(3), Int32(1))";

        assert_optimized_plan_eq(&plan, expected);
        Ok(())
    }
```


Looks it already did constant folding?

Maybe we just need to add the test?

**Comment by alamb** [comment]
Thanks @viirya  -- yes I think the general purpose constant folding implementation we have now should handle the Values. Thanks for the test !
