### ISSUE TITLE
  Add SQL support for IN expression

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#118]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-10731

We should add support for the SQL "IN" expression.

See TPC-H query 12 for a good example:
{code:java}
WHERE l_shipmode IN ('MAIL', 'SHIP') {code}

**Comment by Ted-Jiang** [comment]
i will have a try.  i think its a good chance to familiar datafusion code.😁

**Comment by Ted-Jiang** [comment]
it seems already support in `where col1 in (1,2) `  in  in_list.rs @alamb

**Comment by Ted-Jiang** [comment]
but in  for a sub_query is not support, should i implement this?

**Comment by alamb** [comment]
Thanks @Ted-Jiang  you are right! @seddonm1  added support in https://github.com/apache/arrow-datafusion/commit/93c6c8879c22f96481b5ce7b6057466986f8d340

I think @xudong963  has been working on some subqueries (e.g. https://github.com/apache/arrow-datafusion/issues/1209 and https://github.com/apache/arrow-datafusion/pull/1373 / https://github.com/apache/arrow-datafusion/pull/1492)  so it might be good to catch up on those efforts.

**Comment by alamb** [comment]
There were some attempts to improve the performance of INLIST here:  https://github.com/apache/arrow-datafusion/pull/806 https://github.com/apache/arrow-datafusion/pull/278 from @Dandandan  and @pjmore

**Comment by xudong963** [comment]
> I think @xudong963 has been working on some subqueries (e.g. #1209 and #1373 / #1492) so it might be good to catch up on those efforts.

Yes, I'm sure I'll continue with this weekend. BTW, I'll split some small tasks, @Ted-Jiang you can help me. There is a paper that you can read in advance. "Execution Strategies for SQL Subqueries"
