### ISSUE TITLE
Null constants can not be used in most expressions

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#1184]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

I want to be able to use null constants in my datafusion queries (e.g. `NULL < 5`). While at first this seems a silly usecase, we end up with such predicates during automated rewrites in IOx (where sometimes we replace column references with null constants --  See more details on  https://github.com/influxdata/influxdb_iox/issues/883)

While they are allowed in the SQL or expr language (e.g. `Expr::Literal(ScalarValue::Utf8(None)))` they typically generate some runtime error before execution

**Describe the solution you'd like**
I want to be able to write expressions like `NULL < 5` in all cases where I could write `col < 5` and have DataFusion evaluate to the correct thing. 

The proper fix for this ticket is likely first class support for `DataType::Null` and then proper coercion logic in the codebase as required. See the discussion by @Dandandan  and @Jimexist on #1179  at https://github.com/apache/arrow-datafusion/issues/1179#issuecomment-952997737

**Task List**
- [x] https://github.com/apache/arrow-rs/issues/876
- [x] https://github.com/apache/arrow-datafusion/issues/1179
- [x] #1188
- [x] #1189
- [x] #1191
- [x] #1192
- [x] #1193
- [x] #1194
- [x] #1195

**Additional context**
This is a tracking ticket for a variety of null incorrectness issues I found while working on https://github.com/apache/arrow-datafusion/issues/1179

**Comment by WinkerDu** [comment]
Maybe I can pick up some tickets as appropriate.

**Comment by alamb** [comment]
Thanks @WinkerDu  

I can't remember how far I got with this one. If I were doing this project what I would do is try and change the code so that a `Null` constant (aka `ScalarValue` with an embedded `None`) as `DataType::Null` and then implement coercion rules for DataType::Null <--> All other types.

I tried this at some point and I think I hit issues in `arrow-rs` 's `cast` kernel not knowing how to cast from `Null` to other types, which has since been fixed I think

**Comment by WinkerDu** [comment]
> I can't remember how far I got with this one. If I were doing this project what I would do is try and change the code so that a `Null` constant (aka `ScalarValue` with an embedded `None`) as `DataType::Null` and then implement coercion rules for DataType::Null <--> All other types.

@alamb
I commit a pr [apache/arrow-rs#1572](https://github.com/apache/arrow-rs/pull/1572) to implement coercion rules for `DataType::Null` cast from and to all other types in `arrow-rs`. I think we can solve most of the `NULL` coercion issues  in df based on it.
Please have a review, thank you.

**Comment by alamb** [comment]
Thank you @WinkerDu  -- https://github.com/apache/arrow-rs/pull/1572 won't be included in an arrow release for 2 weeks -- but in the interim we can make a branch in DataFusion that temporarily uses the new version (use `cargo.patch` and use the code directly from github). Let me know if I can help

**Comment by WinkerDu** [comment]
It wound be nice if we can make a temporary branch to solve `NULL` issues in DF, I'm glad to introduce `ScalarValue::Null` to DF and  work on these issues in the interim.
Can you help making this branch @alamb? Thanks

**Comment by alamb** [comment]
> Can you help making this branch @alamb? Thanks

Yes -- check out

**Comment by WinkerDu** [comment]
thank you @alamb  for making this branch,
I haven't committed pr to a private repo before, I will try this branch later in my spare time

**Comment by WinkerDu** [comment]
@alamb 
My bad, I didn't put it right, I didn't mean I need a `arrow-rs` branch, maybe I need a `DataFusion` branch instead. My question is if we have no `DataFusion` branch for `NULL` issues, how can I commit pr and involve other committers reviewing? 
Hope to have some advices, thank you!

**Comment by alamb** [comment]
> My bad, I didn't put it right, I didn't mean I need a arrow-rs branch, maybe I need a DataFusion branch instead. My question is if we have no DataFusion branch for NULL issues, how can I commit pr and involve other committers reviewing?
Hope to have some advices, thank you!

Hi @WinkerDu  - I think you need a datafusion branch to work on with other committers. I suggest you make a branch based on https://github.com/alamb/arrow-datafusion/tree/alamb/preview_null_cast and then put a draft PR to datafusion/master to get review comments on.

I needed to make an arrow-rs branch because there are changes on the master branch that are not yet integrated into DataFusion yet.

However, once https://github.com/apache/arrow-datafusion/pull/2253 is merged I think you can make your datafusion branch point directly at a revision on apache/arrow-rs  rather than my arrow-s branch

😓  sorry that is so complicated

**Comment by WinkerDu** [comment]
Thank you! @alamb 

Seems #2253 is merged, I'll try this suggestion :heart:

> However, once #2253 is merged I think you can make your datafusion branch point directly at a revision on apache/arrow-rs rather than my arrow-s branch

**Comment by alamb** [comment]
I believe we have completed all items in this ticket so closing it down
