### ISSUE TITLE
Function calls with NULL literals do not work

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#1188]
Reproducer:

```sql
> select sqrt(null);
Plan("Coercion from [Utf8] to the signature Uniform(1, [Float64, Float32]) failed.")
```

The correct output is `null`

I think the solution will likely be to teach the function type coercion code about the null type (and that it can be cast to any other type). See https://github.com/apache/arrow-datafusion/issues/1184 for more details

**Comment by WinkerDu** [comment]
@alamb plz assign this issue to me, thank you.
I'll try to introduce `ScalarValue::Null` to solve this issue

**Comment by WinkerDu** [comment]
@alamb 
I try to introduce `ScalarValue::Null`, which `pub fn get_datatype(&self) -> DataType {..}` method will return `DataType::Null`.
But for `DataType::Utf8` type, it seems arrow-rs does not supported `DataType::Null` cast to `DataType::Utf8` yet,
So I got panic error in some cases like `Select ascii(NULL)`.

Or I just allow `Utf8` coercion check pass for function `NULL` support?

What do you think about it ?

**Comment by alamb** [comment]
> But for DataType::Utf8 type, it seems arrow-rs does not supported DataType::Null cast to DataType::Utf8 yet,

Aaah -- I remember hitting that (or something similiar) when I started messing around with null constants. We should probably start by fixing the cast kernel in arrow-rs to cast back/forth between null and any type. Is that something you would like to try or shall I try and find some time?

It actually seems as if @bjchambers suggested this last year https://github.com/apache/arrow-rs/issues/684

**Comment by alamb** [comment]
Thanks @WinkerDu
