### ISSUE TITLE
  Add SQL support for referencing fields in structs

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#119]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-10761

I would like to be able to use SQL to query data sources such as Parquet and JSON that support nested types.

Example:
{code:java}
SELECT id, first_name, address.zip AS zip_code FROM customer{code}

**Comment by houqp** [comment]
I think we are almost there with this feature, see my comment in https://github.com/apache/arrow-datafusion/pull/1006#issuecomment-941938893.

**Comment by Igosuki** [comment]
#1204
