### ISSUE TITLE
`-` (negation) with NULL literals does not work: can't be evaluated because the expression's type is Utf8, not signed 

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#1192]
Reproducer:

```sql
> select -null;
Internal("(- 'Literal { value: Utf8(NULL) }') can't be evaluated because the expression's type is Utf8, not signed numeric")
```

The correct output is `null`

I think the solution will likely be to teach `Expr::Negative` about type coercion (as is done in `BinaryExpr` and function calls) once coercion knows about the null type (and that it can be cast to any other type). See https://github.com/apache/arrow-datafusion/issues/1184 for more details

**Comment by WinkerDu** [comment]
@alamb plz assign to me, thank you.

**Comment by xudong963** [comment]
I tested `select -null;` in mysql and postgres: mysql returned null but
```sql
postgres=# select -null;
ERROR:  operator is not unique: - unknown
LINE 1: select -null;
               ^
HINT:  Could not choose a best candidate operator. You might need to add explicit type casts.
```
Do you need this syntax in iox? @alamb

**Comment by WinkerDu** [comment]
> I tested `select -null;` in mysql and postgres: mysql returned null but
> 
> ```sql
> postgres=# select -null;
> ERROR:  operator is not unique: - unknown
> LINE 1: select -null;
>                ^
> HINT:  Could not choose a best candidate operator. You might need to add explicit type casts.
> ```
> 
> Do you need this syntax in iox? @alamb

@xudong963 Thanks for the test! I agree we can discuss more on it.

**Comment by alamb** [comment]
> Do you need this syntax in iox? @alamb

We do not need this syntax in IOx

**Comment by WinkerDu** [comment]
@alamb @xudong963 Maybe we can introduce this syntax, and keep the contract that operators comes out result `NULL` when accepts `NULL`.

**Comment by liukun4515** [comment]
> @alamb @xudong963 Maybe we can introduce this syntax, and keep the contract that operators comes out result `NULL` when accepts `NULL`.

I think It's better to make it consistent with PG in SQL dialect.

**Comment by WinkerDu** [comment]
I feel free to close the pr #2249 since more conservative opinions of introducing `-NULL` SQL dialect
Thank you @liukun4515 @xudong963

**Comment by liukun4515** [comment]
I think this issue can be closed.
@alamb

**Comment by alamb** [comment]
🤔  I just tried the query again, and it now gives a different error:

```sql
❯ select -null;
Internal("(- 'Literal { value: NULL }') can't be evaluated because the expression's type is Null, not signed numeric")
```

I think we are getting closer...

**Comment by alamb** [comment]
I bet this is a fairly straightforward matter of adding a case in the evaluation kernels

**Comment by drrtuy** [comment]
It is indeed an additional condition in epressions/negative.rs. Here is the PR #3771.
