### ISSUE TITLE
support more subqueries

### ISSUE THREAD

**Issue by xudong963** [apache/arrow-datafusion#1209]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
support more subqueries and pass the TPCH associated with the subquery: https://github.com/apache/arrow-datafusion/issues?q=is%3Aopen+is%3Aissue+milestone%3ATPC-H

**Describe the solution you'd like**

- [ ] `WHERE EXISTS (SELECT ...)`
- [ ] `SELECT (subquery) AS x` or `WHERE (subquery) = x`
- [ ] `[ NOT ] IN (SELECT ...)`  https://github.com/apache/arrow-datafusion/issues/1835
- [ ] `<expr> <op> ANY/SOME (<query>)`
- [ ] `<expr> <op> ALL (<query>)`
- [ ] Single-Row Comparison

**Describe alternatives you've considered**
Correlated subqueries will be implemented by nested loop initially. After the realization of basic functions, we can do some optimization, such as decorrelation and so on.

**Additional context**

**Comment by xudong963** [comment]
@houqp Please assign it to me, thanks!

**Comment by Igosuki** [comment]
Does that require to patch sqlparser or it's only on the engine side ?

**Comment by xudong963** [comment]
@Igosuki As far as know, sqlparser has supported subqueries that I listed, so it's only on the engine side.

**Comment by yahoNanJing** [comment]
Hi @xudong963, could you add #1835 to your list?

**Comment by xudong963** [comment]
> Hi @xudong963, could you add #1835 to your list?

I think it has already had. 
![image](https://user-images.githubusercontent.com/41979257/153994402-116bd298-102c-4140-a12f-b6b290d702b3.png)

After https://github.com/apache/arrow-datafusion/pull/1649 is finished, the `IN` subquery can be easy to add.
