### ISSUE TITLE
execution::context::sql should support creating partitioned dataset

### ISSUE THREAD

**Issue by Jimexist** [apache/arrow-datafusion#1220]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

A challenge to allow `execution::context::sql` supporting creation of partitioned dataset.

For now:
https://github.com/apache/arrow-datafusion/blob/75b8112ee33af81d6085be4a83a096bf965dbc89/datafusion/src/execution/context.rs#L187-L225

the line for `table_partition_cols` is empty

**Describe the solution you'd like**

Ideally we should allow the same syntax, but allow auto detection of partitioned dataset based on either the `location` is a file or a directory

**Describe alternatives you've considered**

**Additional context**

**Comment by Jimexist** [comment]
related #1139

**Comment by Jimexist** [comment]
cc @rdettai and @alamb

**Comment by alamb** [comment]
Auto detecting common partitioning schemes seems like a good idea to me @Jimexist 

Something else I have been wondering is "how general do we want our partitioning to be" -- what @rdettai  has implemented is the classic hive partitioning when partitioning by date looks like `/foo/date=2021-10-01` 

But there are other ways to partition data (e.g. IOx has its own way to partition data into individual files but the partition metadata is stored in some in-memory catalog) -- it would be pretty cool to re-use all the partitioning infrastructure (as well as, for example, add more sophisticated partition pruning)

**Comment by rdettai** [comment]
#1185 is also a follow up to #1135 that is closely related to this. Maybe we can merge the two issues and create subtasks?

**Comment by Jimexist** [comment]
Duplicate of #1185
