### ISSUE TITLE
datafusion cli to support listing functions

### ISSUE THREAD

**Issue by Jimexist** [apache/arrow-datafusion#1227]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

A challenge to add function searching and listing in datafusion cli

**Describe the solution you'd like**

Following https://github.com/apache/arrow-datafusion/pull/1224 where command is added, we can now add `\h` or similar thing to datafusion cli like `psql` to support listing and searching for functions

**Describe alternatives you've considered**

**Additional context**

**Comment by matthewmturner** [comment]
@Jimexist i can give this a shot
