### ISSUE TITLE
Extract logical plans in  LogicalPlan as independent struct

### ISSUE THREAD

**Issue by xudong963** [apache/arrow-datafusion#1228]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
During I try to implement `Select (subquery)` , I add ` Select(Box<LogicalPlan>)` in `Expr`. Because `Expr` derives `PartialEq, PartialOrd`, but `LogicalPlan` not, I try to derive `PartialEq, PartialOrd` for `LogicalPlan`. Unfortunately, I got an error, because some logical plan contains traits, such as `TableScan`, which contains the `TableProvider` trait. 

more thoughts: https://github.com/apache/arrow-datafusion/issues/1228#issuecomment-969443381

**Describe the solution you'd like**
In order to achieve better scalability, I think we can extract logical plans in LogicalPlan as independent structs. For example
```rust
pub enum LogicalPlan {
   ...
    TableScan {
        /// The name of the table
        table_name: String,
        /// The source of the table
        source: Arc<dyn TableProvider>,
        /// Optional column indices to use as a projection
        projection: Option<Vec<usize>>,
        /// The schema description of the output
        projected_schema: DFSchemaRef,
        /// Optional expressions to be used as filters by the table provider
        filters: Vec<Expr>,
        /// Optional limit to skip reading
        limit: Option<usize>,
    },
   ...
}
```
```rust
pub struct TableScanPlan {
    /// The name of the table
    table_name: String,
    /// The source of the table
    source: Arc<dyn TableProvider>,
    /// Optional column indices to use as a projection
    projection: Option<Vec<usize>>,
    /// The schema description of the output
    projected_schema: DFSchemaRef,
    /// Optional expressions to be used as filters by the table provider
    filters: Vec<Expr>,
    /// Optional limit to skip reading
    limit: Option<usize>,
}

pub enum LogicalPlan {
  ...
  TableScan(TableScanPlan),
  ...
}

```
**Describe alternatives you've considered**

**What changes are planned in further issues/PRs?**
- #1302 
- #1303 
- #1304 
- #1305 
- #1306 
- #1307

**Comment by xudong963** [comment]
Let me know your thoughts ❤️ @houqp @alamb @Jimexist @Dandandan

**Comment by houqp** [comment]
@alamb if I recall correctly, the partialOrd for Expr as added to help with unit testing right?

**Comment by alamb** [comment]
> @alamb if I recall correctly, the partialOrd for Expr as added to help with unit testing right?

Yes, it was added in https://github.com/apache/arrow-datafusion/pull/1015 

The test ordering I was the main usecase but I think there are some other ideas of being able to have Exprs in `BTreeSets` and other ordering based containers.

I think extracting `LogicalPlan` into structs would be fine, though it will be a very non trivial change (both for DataFusion and all users)

Something that is more of a hack but might be quicker to do would be to use a `NewType` kind of thing:

```rust
struct Subquery {
  relation_name: String,
  plan: Box<LogicalPlan>
}
```

And then implement `PartialOrd` directly on this structure (perhaps by using the point value of the Box directly).

**Comment by houqp** [comment]
On that topic, what about pushing the `PartialOrd` and `PartialEq` trait to the trait objects? i.e. `LogicalPlan::Extension.node` and `LogicalPlan::TableScan.source`.

**Comment by xudong963** [comment]
> Something that is more of a hack but might be quicker to do would be to use a `NewType` kind of thing

Good idea!



> I think extracting `LogicalPlan` into structs would be fine, though it will be a very non trivial change (both for DataFusion and all users)

Long-term thinking, maybe we can profit from extracting `LogicalPlan` into structs. So if all of you agree, I can do it before doing subquery features. cc @houqp

**Comment by alamb** [comment]
I like @houqp's idea of marking adding`PartialOrd` and `PartialEq` to traits to allow `LogicalPlan` to derive them as well

Perhaps something like

```rust
trait ExtensionNode: PartialOrd, PartialEq {
..
}
```
(and similarly for any other trait objects in `LogicalPlan`)

```rust
#[derive(PartialOrd, PartialEq)]
enum LogicalPlan {
...
}
```

**Comment by xudong963** [comment]
Because `PartialEq` and `PartialOrd`  traits are not "object safe", so pushing the PartialOrd and PartialEq trait to the trait such as `TableProvider` will make `TableProvider` "object unsafe".

**Comment by houqp** [comment]
Good point @xudong963 , totally forgot about object safety :(

I don't have a strong opinion on this and I am cool with us going either way. I do agree with you that adding the `TableScanPlan` struct makes things more flexible in the long run.

**Comment by xudong963** [comment]
> I do agree with you that adding the `TableScanPlan` struct makes things more flexible in the long run.

@alamb @Dandandan @Jimexist How about your thoughts? If you also agree, I want to try on this weekend and after finishing this, I'll continue to deep into subqueries.

**Comment by alamb** [comment]
I think it is a reasonable thing to try. I suspect we'll have to see what the final code looks like to really know 🤷

**Comment by xudong963** [comment]
> I think it is a reasonable thing to try. I suspect we'll have to see what the final code looks like to really know 🤷

OK. I'll firstly extract `TableScan`, then you can what the code looks like, lol 😄

**Comment by liukun4515** [comment]
hi @xudong963 , please at me, if you finish this task and want someone to review it.
Maybe i can begin this [task](https://github.com/apache/arrow-datafusion/issues/1281), after your refactoring work.

**Comment by xudong963** [comment]
I split six sub-issues, newcomers can join us by participating in these issues.

**Comment by rdettai** [comment]
Thanks for your work @xudong963 ! Sorry for getting into the conversation so late but I was in vacations these past two weeks 😉 

A few remarks and questions:
- why do we need to do all these changes to implement `PartialEq` (and `PartialOrd`) here? Why don't we just add an `fn eq(&self, other: & dyn TableProvider) -> bool` method on `TableProvider` and a then implement manually the `PartialEq` trait on the logical plan with a `match` statement? The method will surely be a bit verbose, but it would avoid refactoring the entire codebase.
- even if we go for the solution where we want to implement `PartialEq` using `#[derive()]`, why do we need to extract all variants of `LogicalPlan` into structs? isn't it enough to do it for the variants with trait object fields?
- finally if we really believe that it is worth extracting all the variants into structs and we do it in multiple issues, can we please have an umbrella issue with subtasks that link to all these steps? 


I might have missed some parts of the discussion, so please excuse me if my questions are a bit off 😄

**Comment by xudong963** [comment]
Hi @rdettai, long time no see. Thanks for your feedback.

Now, this is not just a question of subqueries, but a question of which design is better.

During my implementation of subqueries, I encountered some obstacles due to the current pattern.

```rust
pub enum LogicalPlan {
   ...
    TableScan {
        /// The name of the table
        table_name: String,
        /// The source of the table
        source: Arc<dyn TableProvider>,
        /// Optional column indices to use as a projection
        projection: Option<Vec<usize>>,
        /// The schema description of the output
        projected_schema: DFSchemaRef,
        /// Optional expressions to be used as filters by the table provider
        filters: Vec<Expr>,
        /// Optional limit to skip reading
        limit: Option<usize>,
    },
   ...
}
```
So I started to think about the disadvantages of this pattern.

First of all, I think the following pattern is more common in Rust, such as https://github.com/rust-lang/rust/blob/ad808d95c4839caedc2be76d0ed059dc920ab4b6/src/librustc/hir/mod.rs#L2752
```rust
pub struct TableScanPlan {
    /// The name of the table
    table_name: String,
    /// The source of the table
    source: Arc<dyn TableProvider>,
    /// Optional column indices to use as a projection
    projection: Option<Vec<usize>>,
    /// The schema description of the output
    projected_schema: DFSchemaRef,
    /// Optional expressions to be used as filters by the table provider
    filters: Vec<Expr>,
    /// Optional limit to skip reading
    limit: Option<usize>,
}

pub enum LogicalPlan {
  ...
  TableScan(TableScanPlan),
  ...
}
```

In addition to the above, it has some other benefits:

1. It's more clearer and flexiable, long-term thinking, maybe we can profit from extracting LogicalPlan into structs.
2. Enum variants are not types, so `LogicalPlan::TableScan` can't be a function parameter or stored, you need to pass `Logical Plan`. But if each enum variant has its own type, `TableScan` can be passed and stored.
3. When a match occurs, the following are the match styles corresponding to the above two writing methods
   ```rust
   match LogicalPlan {
       TableScan {table_name, source, projection, projected_schema, filters, ...} => /* some actions */
   }
   ```

   ```rust
   match LogicalPlan {
       TableScan(ts) => /* ts.table_name, ts.source, ... */
   }
   ```

4. If multiple enums have the same variants, we need to repeat to write the variant with all its fields when using the first pattern.

Sorry, I don't link all the subtasks to an umbrella issue, I'll do it now.

cc @alamb @houqp  and welcome everyone to discuss!

**Comment by houqp** [comment]
Thanks @xudong963 for the detailed write up.

> Enum variants are not types, so LogicalPlan::TableScan can't be a function parameter or stored, you need to pass Logical Plan. But if each enum variant has its own type, TableScan can be passed and stored.

This to me is my favorite benefit :+1: This effectively means if a series of function calls needs access to a particular plan node, we only need to match on LogicalPlan once, resulting in more readable and performant code.

**Comment by rdettai** [comment]
Thanks for taking the time to answer my set of questions! Makes sense to me now 🙂.

**Comment by alamb** [comment]
> above all, I think this is a meaningful and valuable refactoring, despite major changes to the codebase.

Yes, I think this is the primary benefit of pulling LogicalPlan nodes into their own structs  (not that it is required for subqueries -- I think we could probably make that work somehow -- but that this will make the codebase cleaner in the longer term
