### ISSUE TITLE
  Benchmark crate does not have a SIMD feature

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#124]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-10884

The benchmarks run without SIMD by default. We need to add a feature to the Cargo.toml to enable SIMD.

**Comment by Jefffrey** [comment]
This looks to already be completed by this commit https://github.com/apache/arrow-datafusion/commit/82773fafcb4886b6e7338e85a6a9800bc156e53a

Should be able to close this issue?

**Comment by xudong963** [comment]
Yes, thanks for your check! @Jefffrey
