### ISSUE TITLE
Should not fold a non-constant expression when it is not clear to do so

### ISSUE THREAD

**Issue by NGA-TRAN** [apache/arrow-datafusion#1244]
**Describe the bug**
This expression `col < 10 and boolean(NULL)` can either be NULL or false depending on the result of `col < 10`. Hence it should not be rewritten to a constant but it is current can.

**To Reproduce**
Add the following test in [optimize_expr_bool_and](https://github.com/apache/arrow-datafusion/blob/8f1d533f16e50c309163d2ef7121e2201c80176c/datafusion/src/optimizer/constant_folding.rs#L968), you will see it was rewritten to `c1 BETWEEN Int32(0) AND Int32(10)` which is wrong.

 ```
       // c1 BETWEEN Int32(0) AND Int32(10) AND Boolean(NULL)
       // it can be either NULL or false depending on the value of `c1 BETWEEN Int32(0) AND Int32(10`
        let expr = Expr::Between{ expr: Box::new(col("c1")), negated: false, low: Box::new(lit(0)), high: Box::new(lit(10))};
        let expr = expr.and(Expr::Literal(ScalarValue::Boolean(None)));
        let result = expr.clone().rewrite(&mut rewriter)?;
        println!("expr: {:#?} \n result: {:#?}", expr, result);
        assert_eq!(expr, result);
```

**Expected behavior**
Do not rewritten expression that does not have deterministic result yet

**Comment by NGA-TRAN** [comment]
I am working on a fix for this

**Comment by alamb** [comment]
thank you @NGA-TRAN  -- FYI @matthewmturner  I lead you astray in https://github.com/apache/arrow-datafusion/pull/1208 🤦  about nulls. NULLs!!!!

**Comment by matthewmturner** [comment]
@alamb got it - thanks for keeping me posted!

**Comment by alamb** [comment]
👍  FWIW I think handling `NULL`s correctly is the single hardest thing in databases (at least the thing that is the most fraught with strange corner cases). The fact we are dealing with them in DataFusion now I think is a sign of its maturity
