### ISSUE TITLE
  Optimizer rules should work with qualified column names

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#125]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-10894

We have a number of optimization rules that deal with column names represented by strings.

In order to support qualified field names in queries we need to update these rules to work with a data structure representing optionally qualified column names instead.

Suggested data structure:
{code:java}
struct ColumnName {
  qualifier: Option<String>,
  name: String
} {code}

**Comment by houqp** [comment]
this can be assigned to me since it is covered by #55
