### ISSUE TITLE
test `create_external_table_with_timestamps` failed locally

### ISSUE THREAD

**Issue by xudong963** [apache/arrow-datafusion#1262]
**Describe the bug**
`create_external_table_with_timestamps` failed locally, but CI seems normal.

**To Reproduce**

**Expected behavior**
```
expected:

[
    "+--------+-------------------------+",
    "| name   | ts                      |",
    "+--------+-------------------------+",
    "| Andrew | 2018-11-13 17:11:10.011 |",
    "| Jorge  | 2018-12-13 12:12:10.011 |",
    "+--------+-------------------------+",
]
actual:

[
    "+--------+-------------------------+",
    "| name   | ts                      |",
    "+--------+-------------------------+",
    "| Andrew | 2018-11-13 09:11:10.011 |",
    "| Jorge  | 2018-12-13 04:12:10.011 |",
    "+--------+-------------------------+",
]
```

**Additional context**
It seems a zone question, I'm in east 8th.

**Comment by xudong963** [comment]
FYI, yesterday, the test was normal locally. Today, I rebased master and it failed, there are two new commits, https://github.com/apache/arrow-datafusion/pull/1243, https://github.com/apache/arrow-datafusion/pull/1255. I guess maybe arrow-rs 6.1.0 caused it. I had a quick look at arrow-rs 6.1.0 and found a Suspicious PR about zone: https://github.com/apache/arrow-rs/commit/d4bf0b64f4f8d072094f2f89256fced471c43ad8

**Comment by alamb** [comment]
I think it may be related to https://github.com/apache/arrow-rs/pull/832
