### ISSUE TITLE
why snmalloc?

### ISSUE THREAD

**Issue by stevenbarragan** [apache/arrow-datafusion#1264]
not a bug! just a question.

Why is `smalloc-rs` suggested for an optimized configuration [arrow.apache.org/datafusion/user-guide/library.html](https://arrow.apache.org/datafusion/user-guide/library.html#optimized-configuration) ?
in what way is better than `jemalloc`?

**Comment by Dandandan** [comment]
In my benchmarks, `snmalloc` and `mimalloc` performed better than `jemalloc`.

For jemalloc, I believe this is the most recent / optimized version https://crates.io/crates/tikv-jemallocator .
Feel free to run some benchmarks yourself and report back!

**Comment by alamb** [comment]
I think this question has been answered so closing it down
