### ISSUE TITLE
allow datafusion-cli to toggle quiet flag within CLI

### ISSUE THREAD

**Issue by Jimexist** [apache/arrow-datafusion#1268]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

allow datafusion-cli to toggle quite flag within CLI

**Describe the solution you'd like**

Similar to `psql`, and as an complement to the `-q` flag

**Describe alternatives you've considered**

**Additional context**

**Comment by jgoday** [comment]
Hi @Jimexist, I have made a PR  for this issue #1330.
It adds a new command (QuietMode) for the datafusion-cli.
