### ISSUE TITLE
 Implement Value(Null)

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#130]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-10970

We need to add support for the NULL value. 

For example:

```sql
SELECT char_length(NULL) AS char_length_null
```

**Comment by alamb** [comment]
Comment from Mike Seddon(MikeSeddonAU) @ 2020-12-20T01:10:56.266+0000:
<pre>Added as part of https://github.com/apache/arrow/pull/8966

For future reference:

I have now added the NULL value to both the test cases and the planner.

This is where things get interesting. For this statement:

SELECT NULL

Spark implements a special NullType for this return type but that creates a lot of side effects for things like the Parquet writer and JDBC drivers do not support this type.

I tested Postgres:

CREATE TABLE test AS
SELECT NULL;

The DDL for this table shows that column as a text type so that is why I have applied the default utf8 type to Value(Null).</pre>

**Comment by qrilka** [comment]
@alamb wasn't it implemented already? E.g. in datafusion-cli I see:
```
❯ select char_length(null),a from test;
+------------------------+---+
| character_length(NULL) | a |
+------------------------+---+
|                        | 1 |
|                        | 2 |
+------------------------+---+
2 rows in set. Query took 0.001 seconds.

❯ select null;
+------+
| NULL |
+------+
|      |
+------+
1 row in set. Query took 0.002 seconds.
❯ CREATE TABLE test1 AS
SELECT NULL;
0 rows in set. Query took 0.010 seconds.

❯ select * from test1;
+------+
| NULL |
+------+
|      |
+------+
1 row in set. Query took 0.002 seconds.
```

So it seems to me that the described use cases are already supported

**Comment by alamb** [comment]
I agree -- thanks for pointing this out @qrilka
