### ISSUE TITLE
Extract `Projection`, `Filter`, `Window` in LogicalPlan as independent struct

### ISSUE THREAD

**Issue by xudong963** [apache/arrow-datafusion#1302]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
There are some discussions in https://github.com/apache/arrow-datafusion/issues/1228

**Describe the solution you'd like**
like https://github.com/apache/arrow-datafusion/pull/1290

**Describe alternatives you've considered**
The task is mechanical, however, it is ideal for newcomers to familiarize themselves with datafusion's build, test, and PR processes. 
**Additional context**
If you want to do it, please ping me and assign the task to you, avoiding collisions with other people.

**Comment by xudong963** [comment]
@houqp Please add the `good first issue` label.

**Comment by ic4y** [comment]
can you assign me to this issue ?

**Comment by Dandandan** [comment]
@ic4y done!
