### ISSUE TITLE
Extract `Aggregate`, `Sort`, `Join` in LogicalPlan as independent struct

### ISSUE THREAD

**Issue by xudong963** [apache/arrow-datafusion#1303]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
There are some discussions in #1228

**Describe the solution you'd like**
like #1290

**Describe alternatives you've considered**
The task is mechanical, however, it is ideal for newcomers to familiarize themselves with datafusion's build, test, and PR processes.

**Additional context**
If you want to do it, please ping me and assign the task to you, avoiding collisions with other people.

**Comment by matthewmturner** [comment]
ill give this a shot

**Comment by xudong963** [comment]
> ill give this a shot

Thanks! @matthewmturner
