### ISSUE TITLE
  Implement hash partitioning

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#131]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-11011

Once https://issues.apache.org/jira/browse/ARROW-10582 is implemented, we should add support for hash partitioning. The logical physical plans already support create a plan with hash partitioning but the execution needs implementing in repartition.rs

 

As part of this issue, we should remove the following comment from the logical and physical Partitioning enum:

 
{code:java}
/// This partitioning scheme is not yet fully supported. See https://issues.apache.org/jira/browse/ARROW-11011 {code}

**Comment by Dandandan** [comment]
hash partitioning is supported in DataFusion

https://github.com/apache/arrow-datafusion/blob/master/datafusion/src/physical_plan/repartition.rs#L186
