### ISSUE TITLE
implement `set_agg` aggregation function

### ISSUE THREAD

**Issue by Jimexist** [apache/arrow-datafusion#1323]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

now that we have #1085 we can have `set_agg` as well. we can follow [presto][2]'s convention

**Describe the solution you'd like**

to have an aggregate function to set aggregate a group

**Describe alternatives you've considered**

alternative is to have array_distinct as in [trino][1]

**Additional context**

[1]: https://trino.io/docs/current/functions/array.html
[2]: https://prestodb.io/docs/current/functions/aggregate.html

**Comment by liukun4515** [comment]
Maybe i can try this issue.

**Comment by liukun4515** [comment]
@Jimexist do we have a plan for implement the function or agg?
Another question is which SQL protocal we use? Is pg or mysql?

**Comment by xudong963** [comment]
> @Jimexist do we have a plan for implement the function or agg? Another question is which SQL protocal we use? Is pg or mysql?

DataFusion strives to implement a subset of the PostgreSQL SQL dialect where possible

**Comment by liukun4515** [comment]
> > @Jimexist do we have a plan for implement the function or agg? Another question is which SQL protocal we use? Is pg or mysql?
> 
> DataFusion strives to implement a subset of the PostgreSQL SQL dialect where possible

But i can't find the `set_agg` in the pg document, just find it in the presto doc.

**Comment by Jimexist** [comment]
no it's not. i guess you can choose either:
1. `set-agg`
2. `array-distinct` operator wrapping `array-agg`

i believe 1 is more efficient

**Comment by liukun4515** [comment]
I think we should better add a document to list function or operation we support.

**Comment by james727** [comment]
@Jimexist @liukun4515 is this still wanted? I was looking at this as a potential issue to start learning the codebase, it's unclear if someone's already working on it though or if it makes sense to implement. This seems generally useful, but it is a divergence from Postgres.

**Comment by liukun4515** [comment]
> 

I will not start this issue recently, I am busy with the DECIMAL data type.
If you are interested in it, go-ahead.
@james727

**Comment by james727** [comment]
Great, I'll try and put something together

**Comment by james727** [comment]
@Jimexist  I realized after working on this for a bit that `array_agg(distinct <expr>)` should work for this case - is there a use case where `set_agg` would work but `array_agg` with distinct would not? Datafusion supports this syntax right now, though there appear to be some issues with non-column expression and distinct.
