### ISSUE TITLE
move datafusion-python to the contrib org?

### ISSUE THREAD

**Issue by Jimexist** [apache/arrow-datafusion#1324]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

a question on whether we should move the Datafusion-python crate into the datafusion-contrib org - to make the core development of Datafusion more efficient and loosen up coupling.

not sure if this is doable under the current apache repo setup.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Jimexist** [comment]
cc @alamb @jorgecarleitao @Dandandan @houqp or anyone else who might be concerned

**Comment by houqp** [comment]
I believe this is doable, just like how the java binding is maintained. It will certainly make releases easier for both the python binding and datafusion core. I don't have a strong opinion either way :)

**Comment by alamb** [comment]
I think moving the python  bindings out of the core repo is a good idea and I would be happy to help. The downside is that it will take some concerted effort by the people maintaining the python bindings to keep up with DataFusion

I do want to be honest that I personally and professionally am not likely to spend much / any time on the python bindings once it leaves the arrow-datafusion crate

**Comment by alamb** [comment]
(I think moving the code out of Apache is totally fine -- bringing it back in requires a bit more -- like an Intellectual Property clearance process)

**Comment by Jimexist** [comment]
> I think moving the python bindings out of the core repo is a good idea and I would be happy to help. The downside is that it will take some concerted effort by the people maintaining the python bindings to keep up with DataFusion
> 
> I do want to be honest that I personally and professionally am not likely to spend much / any time on the python bindings once it leaves the arrow-datafusion crate

I think it's okay (and even preferred) for people to focus more. if you are not going to spend too much time on the python binding because it is not at the moment useful to you or your work then it possibly also means that keeping the crate under this repo brings more unwanted overhead for maintenance - in that case moving out sounds like a better idea. if this applies to a lot more people then i guess it shall be moved out.

**Comment by Jimexist** [comment]
[discussion thread in mail][1]
[migrated code][2]

[1]: https://lists.apache.org/thread/4fdn3sx82wdb2c5wk9twkn9fy0do0ohl
[2]: https://github.com/datafusion-contrib/datafusion-python

**Comment by alamb** [comment]
Thank you @Jimexist ! shall we remove the python code from https://github.com/apache/arrow-datafusion/tree/master/python as well?

**Comment by alamb** [comment]
🎉
