### ISSUE TITLE
implement grouping sets, cubes, and rollups

### ISSUE THREAD

**Issue by Jimexist** [apache/arrow-datafusion#1327]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

a challenge to design and implement `grouping set`s, `cube`s, and `rollup`s.

**Describe the solution you'd like**

similar to https://www.postgresql.org/docs/current/queries-table-expressions.html#QUERIES-GROUPING-SETS

**Describe alternatives you've considered**

**Additional context**

this would be a rather large piece of work so ideally can be split up into three subsets:

- [ ] update sqlparser https://github.com/sqlparser-rs/sqlparser-rs/pull/366
- [ ] grouping sets
- [ ] cubes
- [ ] rollups

**Comment by Jimexist** [comment]
I guess a modification to sqlparser is also needed?

**Comment by alamb** [comment]
FYI @thinkharderdev  bashed this out in https://github.com/apache/arrow-datafusion/pull/2716 🥇
