### ISSUE TITLE
`function` module in python binding is broken in 6.0

### ISSUE THREAD

**Issue by Jimexist** [apache/arrow-datafusion#1328]
**Describe the bug**

the `function` module in python binding is broken in 6.0

**To Reproduce**

```ipython
In [1]: import datafusion
f
In [2]: from datafusion import functions

In [3]: dir(functions)
Out[3]:
['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'functions']
```

**Expected behavior**

expect the `function` module to be only one level below `Datafusion`.

**Additional context**

related 
1. #856 
2. #873

**Comment by houqp** [comment]
@Jimexist this was intentional, see https://github.com/apache/arrow-datafusion/pull/1287#discussion_r748150353.

**Comment by houqp** [comment]
I don't have a strong opinion on this though, if you think there is a valid use-case for having the functions module, we can add it back.

**Comment by houqp** [comment]
https://github.com/apache/arrow-datafusion/pull/1287#discussion_r748150353 is the comment that made me change my mind on my original PR :)

**Comment by Jimexist** [comment]
> I don't have a strong opinion on this though, if you think there is a valid use-case for having the functions module, we can add it back.

so you are saying that we should use:

```python
 from datafusion.functions import functions as f
```

instead of 
```python
 from datafusion import functions as f
```

**Comment by Jimexist** [comment]
ah I see now that I can do

```python
from datafusion.functions import md5
```

**Comment by houqp** [comment]
`from datafusion import functions as f` should still work, it's just that `datafusion.functions` won't work anymore.

**Comment by houqp** [comment]
oh, i see what confused you. yeah, it would be better if `dir` works with `functions` module :(
