### ISSUE TITLE
DuckDB Comparison - Questions + Bug

### ISSUE THREAD

**Issue by pdet** [apache/arrow-datafusion#1329]
**Describe the bug**
Hi all, 
I'm currently writing up a blog post on our recent DuckDB/Arrow integration. I was recommended  to check your project since 
(I think) DuckDB and Datafusion are the only systems out there consuming and producing memory Arrow Objects  :-)

I just have a couple of questions and a small bug report.

1. It seems to me that Datafusion is not consuming streaming arrow objects (i.e., not fully materialized objects), is that correct? 
2. Is datafusion already running in parallel?
3. Is there a specific batch size that is more attractive to the datafusion engine?

I've managed to install v 0.4  of datafusion/python, from the sources and run the TPC-H Q6. I wanted to check with you, if the numbers I'm getting are expected, or if I did something wrong when experimenting with it (The code I used is under the reproduce)

DataFusion: 0.20
DuckDB: 0.046753292

**The bug:** One last thing, when trying to generate RecordBatches with different sizes 
e.g.:
``` python
pq.read_table('lineitemsf1.snappy.parquet').to_batches(1024)
```
I hit the following exception:
``` thread 'thread 'tokio-runtime-workertokio-runtime-worker' panicked at '' panicked at 'the offset of the new Buffer cannot exceed the existing lengththe offset of the new Buffer cannot exceed the existing length', ', thread '/Users/holanda/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow-6.2.0/src/buffer/immutable.rs/Users/holanda/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow-6.2.0/src/buffer/immutable.rs::tokio-runtime-worker142142' panicked at '::assertion failed: ceil(offset + len, 8) <= buffer.len() * 899', 

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
/Users/holanda/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow-6.2.0/src/util/bit_chunk_iterator.rs:33:9
thread 'tokio-runtime-worker' panicked at 'the offset of the new Buffer cannot exceed the existing length', /Users/holanda/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow-6.2.0/src/buffer/immutable.rs:142:9
thread 'tokio-runtime-worker' panicked at 'the offset of the new Buffer cannot exceed the existing length', /Users/holanda/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow-6.2.0/src/buffer/immutable.rs:142:9
thread 'tokio-runtime-worker' panicked at 'the offset of the new Buffer cannot exceed the existing length', /Users/holanda/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow-6.2.0/src/buffer/immutable.rs:142:9
thread 'tokio-runtime-worker' panicked at 'the offset of the new Buffer cannot exceed the existing length', /Users/holanda/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow-6.2.0/src/buffer/immutable.rs:142:9
Traceback (most recent call last):
  File "/Users/holanda/Documents/Projects/tryit.py", line 31, in <module>
    result_df = ctx.sql(query).collect()
Exception: Arrow error: External error: oneshot canceled
```

Thanks for your time! Always great to learn a bit about the other db engines out there :-)

**To Reproduce**
```python
from datafusion import ExecutionContext
import pyarrow.parquet as pq
import pyarrow as pa
import time
import duckdb


# wget -q https://github.com/cwida/duckdb-data/releases/download/v1.0/lineitemsf1.snappy.parquet
ctx = ExecutionContext()
conn = duckdb.connect()

query = """SELECT sum(l_extendedprice * l_discount) AS revenue
            FROM
                lineitem
            WHERE
                l_shipdate >= CAST('1994-01-01' AS date)
                AND l_shipdate < CAST('1995-01-01' AS date)
                AND l_discount BETWEEN 0.05
                AND 0.07
                AND l_quantity < 24; """

# for i in range (10,20):
#     batch_size = pow (2,i)
batch_size = '-'
lineitem_fusion = pq.read_table('lineitemsf1.snappy.parquet').to_batches()
lineitem = pa.Table.from_batches(lineitem_fusion)

start_time = time.monotonic()
ctx.register_record_batches("lineitem", [lineitem_fusion])
result_df = ctx.sql(query).collect()
print("DataFusion ("+str(batch_size)+"): "+ str(time.monotonic()-start_time))


start_time = time.monotonic()
result_duck =  conn.execute(query).fetchall()
print("DuckDB ("+str(batch_size)+"): "+ str(time.monotonic()-start_time))

print (result_df[0].column(0))
print (result_duck)
```

**Comment by jorgecarleitao** [comment]
Dandandan summarized it well. Note that there are other systems using Arrow beneath them. E.g.

* [signavio](https://www.signavio.com/)
* [IOx](https://github.com/influxdata/influxdb_iox)
* [dremio](https://www.dremio.com/)
* [polars](https://www.pola.rs/)
* [databend](https://github.com/datafuselabs/databend)
* ask the Arrow dev mailing list for more?

There is also this popular comparison between some of them, https://h2oai.github.io/db-benchmark/ (which is _not_ TPC-H); DuckDB is there :)

**Comment by alamb** [comment]
There is also a substantial list of "powered by" Arrow systems at https://arrow.apache.org/powered_by/

Something else which may be obvious, but I wanted to make explicit, is that that DataFusion doesn't have its own "native" storage format in the way that DuckDB or other DBMS systems do -- DataFusion is a  query engine that can be used if you have your data in Arrow record batches (or want to load them into memory using `register_record_batches`).

If you are comparing DuckDB and DataFusion, another comparison might be to start with data in parquet files and compare the timings of:

1. Time to load the parquet into DuckDB + time to run the query (or time to run the queries in DuckDB if it supports external tables)
2. The time needed to run the query in DataFusion directly against parquet

**Comment by pdet** [comment]
Hey guys,  thanks for the quick answers and suggestions :-)
Also, one thing that I really enjoyed about your project is the easy usability, it literally took me a couple of minutes to get a tpc-h query running, coming from database-server-land this always amazes me!

@Dandandan 
> Hey @pdet
> 
> Thanks for opening this issue! I am personally very interested if there are components within the ecosystem that could be shared between engines such as DuckDB and DataFusion and the pyarrow library. I am thinking about query optimization, re-using UDFs, executing certain parts in one engine or the other, etc.

For sure, I think this is one of the most interesting aspects of being able to zero-copy an in-memory data storage format (Exiting Stuff :-)). I'm still considering showcasing an "executing certain parts in one engine or the other", in the blog post, just have to craft a realistic example for that! 

> For the timings - let me play a bit with your example - I'll come back to it. At first glance, those two things come to mind when looking at the code:
> 
> * It looks like DuckDB doesn't need to load all columns in memory whereas `register_record_batches` pre-loads the data (all columns) in memory.
> * DataFusion can benefit from more parallelism for Parquet reading (See notes on question 2.) by splitting your data into _n_ equal partitions / files.

So, as far as I understand, Arrow has two main types of objects, materialized (e.g., Arrow Tables, RecordBatches ) and streamed ones. (e.g., Record Batch Reader), DuckDB can consume/produce both of these, and quite similar to DataFusion, it automatically parallelizes on the number of batches (If I got that right). In the code-snippet I sent, we are consuming Arrow Tables, exactly to start off from a point where everything is already materialized in memory. From a streaming perspective, yes we wouldn't need to load unnecessary columns/row groups.

> Looking forward to the blog post!
> 
> > 1. It seems to me that DataFusion is not consuming streaming arrow objects (i.e., not fully materialized objects), is that correct?
> 
> I am not 100% certain what you mean here. `register_record_batches` (see PR #981) currently uses `MemTable` which keeps the data as batches in memory (in a fully materialized list). We don't have a streaming table provider as of now which consumes a stream / iterator of Arrow batches. Also would be interesting to see if we can integrate somehow with an Arrow `Table` instead.
Yes, my question was again related to record batch readers. You answered it perfectly!



@jorgecarleitao 
Thanks for the suggestions, the main point of my post is to use DuckDB as an execution engine for Arrow, so basically I want to compare with other libraries that have bindings to Python/R and can run SQL, while integrating with Arrow Tables/Record Batches/ Record Batch Readers. I'll check if any of those fit these criteria as well! :-)
I'm also familiar with the H2OAI benchmark, I was focusing on TPC-H mainly because of the current blogpost examples, but maybe I should have another look at using H2OAI using as well.


@alamb 
Thanks for the list! Will surely have a look.

Just as a clarification, I'm not planning on doing a benchmark comparison with datafusion as engines, but I just want to describe a bit what other options out there can query arrow objects, and a bit of how mature/fast/easy-to-use they are.

Thanks again for all of your answers!
