### ISSUE TITLE
The returned type of abs is error.

### ISSUE THREAD

**Issue by liukun4515** [apache/arrow-datafusion#1335]
**Describe the bug**

In the pg database, the abs support varchar data type

But the result in the datafusion is 
```
❯ select abs('123');
Plan("Coercion from [Utf8] to the signature Uniform(1, [Float64, Float32]) failed.")
❯
```

In other size, the returned type of abs is the input type.

If the input type is int, the returned type must be the int.

If the result data is out of range, PG will throw error message.

```
postgres=# SELECT abs(-2147483648);
ERROR:  integer out of range
postgres=#
```

but in the datafusion, it convert the `-2147483648` to INT64

```
❯ SELECT abs(-2147483648);
+-------------------------+
| abs(Int64(-2147483648)) |
+-------------------------+
| 2147483648              |
+-------------------------+
```

**To Reproduce**
execute the sql
```
❯ select abs('123');
Plan("Coercion from [Utf8] to the signature Uniform(1, [Float64, Float32]) failed.")
❯
```

**Expected behavior**

```
postgres=# select abs('123');
 abs
-----
 123
(1 row)
```

the result of type is always double

**Additional context**

**Comment by liukun4515** [comment]
Please assign this issue to me.

**Comment by liukun4515** [comment]
After survey, in the PG, we can use the function ob ABS to INT,BIGINT,FLOAT,DOUBLE,VARCHAR,DECIMAL and other datatype. The result type is complex, Maybe other mathematical functions also have the same issue.
I will give a general solution to resolve it.

**Comment by alamb** [comment]
https://github.com/apache/arrow-datafusion/pull/5086/files#r1089553803 -- @melgenek  noticed that `abs(decimal)` appears to be resolved as a float rather than decimal

**Comment by alamb** [comment]
I am going to close this one as I can't figure out what this ticket is tracking

I think the current error message is pretty straightforward:

```sql
❯ select abs('123');
Error during planning: No function matches the given name and argument types 'abs(Utf8)'. You might need to add explicit type casts.
	Candidate functions:
	abs(Float64/Float32)
```

I am not sure what this issue is tracking any more. Is the requested feature to support automatically cocercing strings to some type?

If so I'll open a new specific ticket for that
