### ISSUE TITLE
Improve the Ballista crates.io / docs.rs documentation for the example code

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#1340]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
I just tried out the official Ballista 0.6.0 release by following the instructions shown [here](https://crates.io/crates/ballista) and [here](https://docs.rs/ballista/0.6.0/ballista/).

Overall, this was really great and this is the first Ballista release that is easy to try out via `cargo install` but I did have to spend some time finding the correct dependencies to add to my Cargo.toml and this could be a burden for someone that is not already familiar with the project.

**Describe the solution you'd like**
I think we can either just document that it is necessary to add the following dependencies, or we could link to a working example in the repo.

```toml
[dependencies]
ballista = "0.6"
datafusion = "6.0"
tokio = "1.0"
```

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by jgoday** [comment]
Hi, I have created this PR #1346 for this issue.
