### ISSUE TITLE
Benchmark `constellation-rs/amadeus`'s parquet implementation

### ISSUE THREAD

**Issue by jon-chuang** [apache/arrow-datafusion#1341]
We might want to use `constellation-rs/amadeus`'s parquet, which claims a 1.5-17x speedup, or maybe even attempt to merge it upstream.
One should also consider just how big of an overhead we are talking about when it comes to reading parquet files and how this relates to Ballista's persistence story.

**Comment by houqp** [comment]
What they have seems just like a fork of what's in arrow-rs, I doubt it will be faster than @jorgecarleitao 's parquet2/arrow2 implementation ;)

**Comment by jon-chuang** [comment]
Ah, I see, ok, I'll take a look at that :)

**Comment by houqp** [comment]
for parquet2, you can play around with it with the code in https://github.com/apache/arrow-datafusion/pull/68. I am also curious how amadeus' implementation performs.

**Comment by tustvold** [comment]
https://github.com/constellation-rs/amadeus appears to be abandoned so closing.

_FWIW there was work in February of this year to port across many of the ideas from parquet2, which brought the two into roughly the same ballpark. Depending on benchmark selection you could make either perform better  Now that parquet supports predicate pushdown the story is significantly less nuanced._
