### ISSUE TITLE
Support Filter on unprojected columns

### ISSUE THREAD

**Issue by houqp** [apache/arrow-datafusion#1351]
**Describe the bug**

`SELECT a FROM table WHERE b > 0` will throw an error in datafusion because `b` is not a projected column.

**To Reproduce**

Try to filter on unprojected column

**Expected behavior**

`SELECT a FROM table WHERE b > 0` should work without error.

**Additional context**

https://github.com/roapi/roapi/issues/110

**Comment by viirya** [comment]
Is there any other condition? I tried to run a query like `"SELECT id FROM alltypes_plain WHERE int_col > 0"`, but seems it works.

**Comment by viirya** [comment]
Also ran with csv, and mem table, still cannot reproduce it.

**Comment by houqp** [comment]
Thanks @viirya for looking into this, turns out I filed the wrong the ticket :man_facepalming:  I filed https://github.com/apache/arrow-datafusion/issues/1372 to replace this one.
