### ISSUE TITLE
The framework about expression type coercion

### ISSUE THREAD

**Issue by liukun4515** [apache/arrow-datafusion#1356]
**Describe the bug**
In the [Implement DECIMAL type](https://github.com/apache/arrow-datafusion/issues/122), I want to implement the decimal data type in datafusion.

In the survey period, I take a look the type coercion in the current datafusion, and find some confused points.

For example:
- `AggFunction`

```
logical expr：
agg(input_exprs)
```

In the expression evaluation, we need to coercion the expr and calc the result type of `AggFunction` expr.

In the current code, the logical result type use this API [return_type](https://github.com/apache/arrow-datafusion/blob/645a7f484435d7182d88a541ac8cdf8b079b7714/datafusion/src/physical_plan/aggregates.rs#L97), but get the physical expr result type use this API [create_agg_expr](https://github.com/apache/arrow-datafusion/blob/645a7f484435d7182d88a541ac8cdf8b079b7714/datafusion/src/physical_plan/aggregates.rs#L121).

These two API have a gap, which is `coerce`. In the `coerce`, the input expr may be added `try_cast` and change the data type. The result data type of inferred physical expr may be diff with the logical result data type.

**To Reproduce**

**Expected behavior**

**Additional context**

**plan**

- [x] rule for AggregateFunction https://github.com/apache/arrow-datafusion/pull/1387
- [ ] rule for binary operator: comparison operation
- [ ] rule for ScalarFunction
- [ ] rule for ScalarUDF
- [ ] rule for WindowFunction
- [ ] rule for AggregateUDF
- [ ] other

**Comment by liukun4515** [comment]
By the way, I think there is a [bug](https://github.com/apache/arrow-datafusion/blob/645a7f484435d7182d88a541ac8cdf8b079b7714/datafusion/src/physical_plan/aggregates.rs#L138).

```
    let name = name.into();
    let arg = coerce(args, input_schema, &signature(fun))?;
    if arg.is_empty() {
        return Err(DataFusionError::Plan(format!(
            "Invalid or wrong number of arguments passed to aggregate: '{}'",
            name,
        )));
    }
    let arg = arg[0].clone();

    let arg_types = args
        .iter()
        .map(|e| e.data_type(input_schema))
        .collect::<Result<Vec<_>>>()?;

    let return_type = return_type(fun, &arg_types)?;
```

The `args` is the original physical exprs, and the `arg` is the coerced physical exprs.
In order to get the result type, we need replace

```
    let arg_types = args
        .iter()
        .map(|e| e.data_type(input_schema))
        .collect::<Result<Vec<_>>>()?;
```
with

```
    let arg_types = arg
        .iter()
        .map(|e| e.data_type(input_schema))
        .collect::<Result<Vec<_>>>()?;
```

In the [functions.rs](https://github.com/apache/arrow-datafusion/blob/645a7f484435d7182d88a541ac8cdf8b079b7714/datafusion/src/physical_plan/functions.rs#L1139), I think the usage is right.

**Comment by alamb** [comment]
I agree that the `coercion` framework is a bit messy at the moment. It might help to start refactoring by collecting the coercion logic into a single module with some clearly defined entrypoint.

Perhaps something like 
```rust
pub fn coerce_to(expr: Expr, to_type: &DataType) -> Option<Expr> {
...
}
```
With appropriate comments and tests

**Comment by alamb** [comment]
BTW I would love to help centralize the coercion logic -- I have ideas / plans to make it support coercing to/from NULL which is currently a gap.

**Comment by liukun4515** [comment]
Now, the `coercision` is in the physical plan or physical expr generation period, but in the spark and other SQL system this action is in the logical period. @alamb

**Comment by liukun4515** [comment]
> BTW I would love to help centralize the coercion logic -- I have ideas / plans to make it support coercing to/from NULL which is currently a gap.

Can you explain or give more details?

**Comment by liukun4515** [comment]
> I agree that the `coercion` framework is a bit messy at the moment. It might help to start refactoring by collecting the coercion logic into a single module with some clearly defined entrypoint.
> 
> Perhaps something like
> 
> ```rust
> pub fn coerce_to(expr: Expr, to_type: &DataType) -> Option<Expr> {
> ...
> }
> ```
> 
> With appropriate comments and tests

Now all the coercion logic are in one the rule file, and it can't fit many case. For example
```
select abs('123');
select '123'+10;
select 12.3+'1.23';
....
```
Now all the coercion logic are in one the rule file, and it can't fit many case. For example
I think we can create a new mod for coercion and type inferring.
The new mod should be `pub crate` and should not public to out of the `datafusion` crate.

I think we should create diff coercion rule for diff expr type, and we can summary the common logic to the same file.

In the AggFunction, ScalarFuntion, ScalarUDF, we can define diff coercion to fit each expr and operation.

**Comment by liukun4515** [comment]
In the binary expr, the input has the `op type` and `left,right expr`, we need these three component to get the `result type` and `coercion`;

In the build-in function expr, the input has the `function type` and `exprs`, we need these three component to get the `result type` and `coercion`.

The `AggregateFunction` is the same as above.

**Comment by liukun4515** [comment]
@andygrove @Jimexist @Dandandan  @houqp PTAL

**Comment by liukun4515** [comment]
@jorgecarleitao Do you have time to take look it?

**Comment by alamb** [comment]
> Now, the coercision is in the physical plan or physical expr generation period, but in the spark and other SQL system this action is in the logical period. @alamb

Yes, this is something @jorgecarleitao  wrote -- I think it originally came in as part of https://github.com/apache/arrow/pull/8024, which has much more of the rationale. Other systems I have worked on do the coercion at the `LogicalPlan` / `Expr` level, but I think doing coercion at the `ExeuctioPlan` / `PhysicalExpr` level makes sense too. Unless we discover some compelling reason to move coercion to `LogicalPlan` I suggest we do not revisit this decision. 


> I think we can create a new mod for coercion and type inferring.
> The new mod should be pub crate and should not public to out of the datafusion crate.

This makes sense to me

> I think we should create diff coercion rule for diff expr type, and we can summary the common logic to the same file.

Yes I agree

> In the AggFunction, ScalarFuntion, ScalarUDF, we can define diff coercion to fit each expr and operation.

I think it might make sense to keep all the coercion logic in the same place (e.g. in the `coercion.rs` module rather than splitting it across `AggFunction`, `ScalarFunction`, etc) but I do not feel super strongly about this

**Comment by liukun4515** [comment]
> > Now, the coercision is in the physical plan or physical expr generation period, but in the spark and other SQL system this action is in the logical period. @alamb
> 
> Yes, this is something @jorgecarleitao wrote -- I think it originally came in as part of [apache/arrow#8024](https://github.com/apache/arrow/pull/8024), which has much more of the rationale. Other systems I have worked on do the coercion at the `LogicalPlan` / `Expr` level, but I think doing coercion at the `ExeuctioPlan` / `PhysicalExpr` level makes sense too. Unless we discover some compelling reason to move coercion to `LogicalPlan` I suggest we do not revisit this decision.
> 

Yes, now we have not meet some issues which should change the coercion to logical period. if we meet them, we can discuss this again.

> > I think we can create a new mod for coercion and type inferring.
> > The new mod should be pub crate and should not public to out of the datafusion crate.
> 
> This makes sense to me
> 
> > I think we should create diff coercion rule for diff expr type, and we can summary the common logic to the same file.
> 
> Yes I agree
> 
> > In the AggFunction, ScalarFuntion, ScalarUDF, we can define diff coercion to fit each expr and operation.
> 
> I think it might make sense to keep all the coercion logic in the same place (e.g. in the `coercion.rs` module rather than splitting it across `AggFunction`, `ScalarFunction`, etc) but I do not feel super strongly about this

I think we have aligned that we can split coercion logic into a independent mod (one sub directory in the `physical_plan` directory).
I will try to implement the Agg function to as a sample.

**Comment by alamb** [comment]
I think this issue is now closed and we are on our way to uniform type coercion logic ❤️

**Comment by liukun4515** [comment]
> I think this issue is now closed and we are on our way to uniform type coercion logic ❤️

thank you for your reminder. 
I will focus on the coercion logic when we meet some issues.

**Comment by liukun4515** [comment]
InList coercion rule: https://github.com/apache/arrow-datafusion/pull/2794/
