### ISSUE TITLE
Why use the expr types before coercion to get the result type?

### ISSUE THREAD

**Issue by liukun4515** [apache/arrow-datafusion#1358]
https://github.com/apache/arrow-datafusion/blob/15db29153aefc9b759ec03e6eeab8cb9ebf87781/datafusion/src/physical_plan/functions.rs#L1144

In order to get agg phy expr,  we need to coerce the input exprs(may need to add try_cast to wrap the expr), so the types of 
coerced exprs is diff with the types of input exprs.

In the below code, we also need to use the coerced exprs and coerced types to generate the agg expr.

**Comment by liukun4515** [comment]
cc @jorgecarleitao

**Comment by alamb** [comment]
if the question is "should we use the argument types after coercion" that seems to make sense to me, but I haven't thought about it all that much

**Comment by liukun4515** [comment]
This an invalid issue, [this line](https://github.com/apache/arrow-datafusion/blob/15db29153aefc9b759ec03e6eeab8cb9ebf87781/datafusion/src/physical_plan/functions.rs#L1144) is my intention.
The return data type should get from the input expr types and not from coerced expr types

**Comment by alamb** [comment]
> This an invalid issue, this line is my intention.


@liukun4515  are you suggesting we close this issue?

**Comment by liukun4515** [comment]
> > This an invalid issue, this line is my intention.
> 
> @liukun4515 are you suggesting we close this issue?

Yes, i will close it.
