### ISSUE TITLE
  ParquetTable should avoid scanning all files twice

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#136]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-11047

ParquetTable currently reads the metadata for all files once in the constructor in order to get the schema, and does it again each time scan() is called.

We could read the metadata once and cache it instead.

**Comment by houqp** [comment]
@alamb I think this can be closed now, @rdettai 's file format implementation only scans a single file now for schema inference.
