### ISSUE TITLE
An invalid piece of code in hash_aggregate

### ISSUE THREAD

**Issue by ic4y** [apache/arrow-datafusion#1362]
**Describe the bug**
An invalid piece of code in hash_aggregate.
I didn't find any use of `group_by_values`
https://github.com/apache/arrow-datafusion/blob/414c826bf06fd22e0bb52edbb497791b5fe558e0/datafusion/src/physical_plan/hash_aggregate.rs#L364-L370

**To Reproduce**

**Expected behavior**
If this is indeed invalid, I will delete it

**Additional context**
__

**Comment by Dandandan** [comment]
Looks to me like it is unused, old code indeed. Good find :+1:
