### ISSUE TITLE
Documentation for using scalar functions with the the DataFrame API

### ISSUE THREAD

**Issue by tobyhede** [apache/arrow-datafusion#1364]
I've framed this as a documentation feature request, but it is also a request for assistance. I''ve been attempting to get the `starts_with` function working with the Dataframe API and after banging my head for a couple of hours I am a bit stumped as to how to make it actually work. 

**Describe the solution you'd like**
More documentation and extended examples for the Dataframe API that include usage of some of the other availablefunctions. 
Current docs demonstrate comparison (lt_eq) and aggrgeation. 

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by xudong963** [comment]
Hi @tobyhede, thanks for your interest in Datafusion. 
I think you can find all DF API usages in https://github.com/apache/arrow-datafusion/blob/master/datafusion/src/dataframe.rs which has rich notes.

**Comment by tobyhede** [comment]
Thanks @xudong963. The core docs are very good, but don't seem to include any examples of using the scalar functions  `lower, upper, starts_with, etc` . I've been trying permutations with no luck.

eg My assumption (based on the equality operators) was that something like this should work:
```
  .filter(col("some_col").starts_with(lit("alpha")))
```

In the above, `starts_with` isn't found in the scope.

**Comment by tobyhede** [comment]
Digging further, it looks like the root cause here is a bug in the functions - many are being constructed without the correct arity.
