### ISSUE TITLE
  Allow ParquetExec to parallelize work based on row groups

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#137]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-11056

ParquetExec currently parallelizes work by passinging individual files to threads. It would be nice to be able to do this in a finer-grained way by assigning row groups and/or column chunks instead. This will be especially important in distributed systems built on DataFusion.

**Comment by Ted-Jiang** [comment]
@houqp plz assign this to me
