### ISSUE TITLE
Add tests for TPCH explain plans to avoid regressions

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#1377]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
We have had performance regressions in the TPCH plans due to plan changes (e.g. https://github.com/apache/arrow-datafusion/issues/1367)

In order to avoid this situation in the future, we would like to have the explain plans committed as tests (so we can evaluate any changes to those plans as part of normal PR review)

**Describe the solution you'd like**
Add tests that `EXPLAIN ...` the TPCQ queries,  following the model of the test added by @viirya in  https://github.com/apache/arrow-datafusion/pull/1368 

Ideally this would be in the `tpch` crate, as suggested in @Dandandan  https://github.com/apache/arrow-datafusion/pull/1368/files#r757892477

**Describe alternatives you've considered**

**Comment by viirya** [comment]
BTW, does the tpch crate mean the benchmarks? Otherwise I don't find a tpch crate here.

**Comment by alamb** [comment]
> BTW, does the tpch crate mean the benchmarks? Otherwise I don't find a tpch crate here.

Yes, I think that is right.

So perhaps we could add some sort of test in  https://github.com/apache/arrow-datafusion/blob/master/benchmarks/src such as `benchmarks/tests/plans.rs` that used the queries in https://github.com/apache/arrow-datafusion/tree/master/benchmarks/queries. 

We could probably adapt lots of https://github.com/apache/arrow-datafusion/blob/master/benchmarks/src/bin/tpch.rs

**Comment by jiangyinzuo** [comment]
I am willing to handle this issue.:smile:
