### ISSUE TITLE
real data type is float32 in PG database, but in the datafusion it is as float64

### ISSUE THREAD

**Issue by liukun4515** [apache/arrow-datafusion#1380]
**Describe the bug**
In the PG database, the `real` datatype is as the float32, but it is as float64 in the datafusion.

Do we need to be consistent with PG database in the point?

1. https://github.com/apache/arrow-datafusion/blob/3bf5811b9a275b7ce6792867a5c1fa230a880742/datafusion/src/catalog/information_schema.rs#L416
2. https://github.com/apache/arrow-datafusion/blob/414c826bf06fd22e0bb52edbb497791b5fe558e0/datafusion/src/sql/planner.rs#L377

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by liukun4515** [comment]
@alamb @houqp  do you think we should make consistent with the PG [datatype](https://www.postgresql.org/docs/current/datatype-numeric.html) ?

**Comment by houqp** [comment]
I think so considering we aim to be compatible with postgres
