### ISSUE TITLE
Support `register_parquet` from a list of files

### ISSUE THREAD

**Issue by sergiimk** [apache/arrow-datafusion#1384]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Current API (`register_parquet`) allows only to specify a single parquet file, or an entire directory (prefix).

There are cases where application has **extra knowledge** that can help narrow down the list of files needed to execute a query to a much smaller subset - e.g. reduce the number of files scanned from thousands to just a few.

**Describe the solution you'd like**
It would be very useful to have an API that creates a table from a **list of specific parquet files**.

**Describe alternatives you've considered**
In datafusion `v5` I had a custom implementation of `ParquetTable` (`TableProvider`) that accepted a `Vec<Path>`.

In `v6` the logic of which files are read is now spread between `ListingOptions`, `ObjectStore`, and `ListingTable` and I don't see an easy way to customize it. 

I tried to implement a wrapper on top of `LocalFileSystem` (`ObjectStore`) ... but, oh my, working with async streams is a pain.

**Additional context**
I'm working on a stream processing tool that persists stream data in a series of parquet files like so:

```
/my-data-stream/
|-- 2c4e3cee4
|-- 37bf92a55
|-- 3c31ccace
| ...
```

There can be many thousands of files in a stream and the tool often queries just a few most recent event batches (e.g. `tail -n 100` - show last 100 events in the stream). I'd like to avoid the overhead of scanning the entire directory and ordering records by time.

**Comment by liukun4515** [comment]
Does your files is end with `.parquet`？
Now the list options just can accept parquet fileformat file with `.parquet` extension.

**Comment by sergiimk** [comment]
No, my files don't have an extension. 
Hard-coded `.parquet` extension is a different (smaller) problem that I managed to work around.

**Comment by houqp** [comment]
@sergiimk with the new API, we are supposed to perform the file listing pruning inside TableProvider's scan method like this https://github.com/delta-io/delta-rs/blob/44fff8f50563c7d3d89866e2b93025541765a08e/rust/src/delta_datafusion.rs#L240. You shouldn't need to touch objectstore since this abstraction is supposed to agnostic to table layouts and file formats.

**Comment by sergiimk** [comment]
Thanks @houqp, I ended up trying both ways and agree custom `TableProvider` is a better option. 

I implemented my own version of `ListingTable` - `PreListedTable`, that takes a Vec of paths. The problem is the amount of code duplication.

`ListingTable` does many more things in addition to scanning files:
- splitting them up into partitions
- collecting file statistics
- building physical plan

All this has to be duplicated amounting to >200 LOC, including inlining some helper functions that were inaccessible due to being in private modules (e.g. `split_files`). This will be a pain to maintain.

I'm curious if you think my use-case makes sense overall - it it something datafusion would like to support out-of-the-box? 

If yes - we can discuss the API and I'd be happy to work on adding it.

**Comment by houqp** [comment]
Yes, I think there is value in exporting those resusable code through public interfaces so we can maintain and optimize them together. Curious what @rdettai @alamb @Dandandan @jorgecarleitao @Jimexist @andygrove think about this.

**Comment by alamb** [comment]
> Yes, I think there is value in exporting those resusable code through public interfaces so we can maintain and optimize them together. Curious what @rdettai @alamb @Dandandan @jorgecarleitao @Jimexist @andygrove think about this.

Yes I agree there is value to an API like 'just scan this list of parquet files' . In our IOx project we have a similar situation (we have a list of parquet files we want to scan that we determine using our own in memory metadata / catalog structures). In my opinion the more of such code can be shared in DataFusion the better (so we don't all end up implementing the same thing)

cc @tustvold

**Comment by capkurmagati** [comment]
I had the same problem when I played with Apache Iceberg and datafusion. Iceberg tracks files for each snapshot so the current `list files with this filter` feature is almost never used.

**Comment by dispanser** [comment]
I have a project with similar requirements, where files / partitions are determined by looking up a catalog with additional indexing capabilities to determine the files to read prior to passing them to datafusion.

In our case, we don't actually want to register a table (as the selection of files changes with every query), but need something like `read_parquet(Vec<Path>)`.
I'm not sure if that makes it sufficiently different to what's discussed here to make it a separate issue, but it sounds to require very similar functionality under the hood.

I'm happy to help, but not well-versed in the datafusion codebase to drive the design decisions.

**Comment by alamb** [comment]
I think https://github.com/apache/arrow-datafusion/pull/1863 from @matthewmturner  may start to lay some of the foundations for doing something similar (e.g. a ObjectStore backed schema provider that could ease the integration challenge)

**Comment by rdettai** [comment]
sorry for the late response, I missed this thread! Obviously, if we make `ListingTable` usable without using the listing capability, that would be a clear violation of its name! 😄 

The capability to query a provided list of files (possibly with provided statistics) is very useful. I have the feeling that it calls for the addition of a lower level `TableProvider` that would take as input the configs of the physical plan itself (`PhysicalPlanConfig`) and just pass them through. We can refactor the small bits of code that could be useful to build the input of that table provider to make them public utility functions:
- they are mostly already factorized into the `helpers` mod, just need to expose them one step further
- they are actually not that smart: `split_files()` is pretty much a one liner and `get_statistics_with_limit()` should actually be improved as its behavior is not always properly defined
- the only bit that should be exctracted from the listing table is the one that iterates over the list of file names and calls `infer_stats` on them, but again, it is really just a basic stream iteration

**Comment by djouallah** [comment]
had the same issue, would love to be able to read a list of files

**Comment by sergiimk** [comment]
There was a [recent change](https://github.com/apache/arrow-datafusion/pull/4908) that allowed passing multiple files to `SessionContext::read_parquet()` API. This allowed us to finally get rid of our custom table implementation and just do:

```rust
let file_urls: Vec<String> = ...;

let df = session_context
    .read_parquet(
        file_urls,
        ParquetReadOptions {
            file_extension: "",
            ..Default::default()
        },
    )
    .await
```
This solved the original issue I reported, so I will close this ticket. @djouallah if the API still doesn't meet some of your requirements - you can reopen or submit a new issue.

**Comment by alamb** [comment]
Thanks @sergiimk

**Comment by djouallah** [comment]
@alamb I use Python datafusion and I don't know how to use it ?

**Comment by alamb** [comment]
I am not sure if it has been exposed yet in the python bindings -- maybe @andygrove  or @jdye64  know 🤔 

If not, perhaps it is worth a report in https://github.com/apache/arrow-datafusion-python/issues
