### ISSUE TITLE
Duplicated content in Readme and User Guide -- should we consolidate

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#1400]
**Describe the bug**
There appears to be duplicated content / overlap between 

https://github.com/apache/arrow-datafusion/blob/master/docs/source/user-guide/ (which is eventually published to https://arrow.apache.org/datafusion/ ) 

and https://github.com/apache/arrow-datafusion/blob/master/README.md 

I worry that the content is diverging (e.g. with the list of supported SQL)

**Expected behavior**
I wonder if it would ok to move all content from and https://github.com/apache/arrow-datafusion/blob/master/README.md into the users guide and change README.md to have a link to the user guide?

**Comment by alamb** [comment]
Any thoughts @houqp  / @Jimexist ?

**Comment by xudong963** [comment]
I think it's enough to keep `Datafusion`, `Use Cases`, `Why DataFusion?`, `Known Uses`, `Example Usage`, `Using DataFusion as a library`, `Using DataFusion as a binary`, `Roadmap`, `Architecture Overview`, `Developer's guide` in README (maybe fewer parts), others will be better to move into user guide. Then README will be concise and highlight the key points.

**Comment by alamb** [comment]
> I think it's enough to keep Datafusion, Use Cases, Why DataFusion?, Known Uses, Example Usage, Using DataFusion as a library, Using DataFusion as a binary, Roadmap, Architecture Overview, Developer's guide in README (maybe fewer parts), others will be better to move into user guide. Then README will be concise and highlight the key points.

I agree -- good point to keep the README highlighting key points, especially as the README.md text turns into the documentation on the crates.io homepage: https://crates.io/crates/datafusion

**Comment by houqp** [comment]
+1 from me for moving big chunk of content to our website and keep only the key highlights in readme. We can convert some of the key highlights into different datafusion website links in readme as well to further reduce duplication.

**Comment by xudong963** [comment]
How's this going? Maybe we can add a `good first issue` tag.

**Comment by alamb** [comment]
added tag
