### ISSUE TITLE
Group by uses unselect column is invalid

### ISSUE THREAD

**Issue by xudong963** [apache/arrow-datafusion#1403]
**Describe the bug**
Group by uses unselect column is invalid.
such as `SELECT a FROM t ORDER BY b;` 

**To Reproduce**
Postgres:
```sql
postgres=# create table foo (
    a int,
    b int
);
CREATE TABLE
postgres=# insert into foo (a, b) values (1, 2);
insert into foo (a, b) values (null, 3);
INSERT 0 1
INSERT 0 1
postgres=# select a from foo order by b;
 a
---
 1

(2 rows)
```

Datafusion
```sql
❯ create table foo as SELECT * FROM (VALUES (1,2), (2,3)) as t;
0 rows in set. Query took 0.061 seconds.
❯ select * from foo;
+---------+---------+
| column1 | column2 |
+---------+---------+
| 1       | 2       |
| 2       | 3       |
+---------+---------+
2 rows in set. Query took 0.006 seconds.
❯ select column1 from foo order by column2;
Plan("No field named 'foo.column2'. Valid fields are 'foo.column1'.")
```

**Expected behavior**

**Additional context**

**Comment by houqp** [comment]
this seems like a duplicate of https://github.com/apache/arrow-datafusion/issues/1372? I also commented a potential quick fix in there as well ;)

**Comment by xudong963** [comment]
> this seems like a duplicate of #1372? I also commented a potential quick fix in there as well ;)

Yes, sorry for not checking the existed issue.
