### ISSUE TITLE
Do not send empty batches for Hash partitioning

### ISSUE THREAD

**Issue by Dandandan** [apache/arrow-datafusion#1405]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
In https://github.com/apache/arrow-datafusion/issues/1404 an example is shown where we have batches with 0 values.
This seems easy to avoid.

**Describe the solution you'd like**
In `RepartitionExec` we can have an early check on empty batches and not issue them.

**Describe alternatives you've considered**
Keep it as is.

**Additional context**

**Comment by Ted-Jiang** [comment]
@houqp Please assign this issue to me.

**Comment by Ted-Jiang** [comment]
@Dandandan Sorry for forgot add close tag in pr, please close this issue.
