### ISSUE TITLE
`order by` supports index in select list

### ISSUE THREAD

**Issue by xudong963** [apache/arrow-datafusion#1414]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
`order by` supports index, such as `select a from foo order by 1;`

**Describe the solution you'd like**
Add special process in https://github.com/apache/arrow-datafusion/blob/b9866e62800700dd322e755cfbbbff6b0df48fa2/datafusion/src/sql/planner.rs#L1011. Transfer `index` to `column` which is in select list. 

**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by xudong963** [comment]
FYI

**postgres**
```sql
postgres=# create table foo (
    a int,
    b int
);
CREATE TABLE
postgres=# insert into foo (a, b) values (1, 2);
insert into foo (a, b) values (null, 3);
INSERT 0 1
INSERT 0 1

postgres=# select a from foo order by 1;
 a
---
 1

(2 rows)
```

**Datafusion**
```sql
❯ select column1 from foo order by 1;
ArrowError(ExternalError(Plan("Sort operation is not applicable to scalar value 1")))
```

**Comment by xudong963** [comment]
Maybe the issue is suitable for newcomers, please add the `good first issue` label.

**Comment by hntd187** [comment]
I'll give this a whirl, PR shortly

**Comment by hntd187** [comment]
Just verifying, this counts starting from 1 correct @xudong963 not 0?

**Comment by xudong963** [comment]
> Just verifying, this counts starting from 1 correct @xudong963 not 0?

yes
