### ISSUE TITLE
Talk about the result type for coerced type

### ISSUE THREAD

**Issue by liukun4515** [apache/arrow-datafusion#1418]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
In the #122  and #1356, I add new datatype(decimal) and propose a more clear coercion rule for expr system.
When I add decimal to the SUM and AVG function https://github.com/apache/arrow-datafusion/pull/1408 , I meet some problem.
It's about the returned data type.

For example:
https://github.com/apache/arrow-datafusion/blob/415c5e124af18a05500514f78604366d860dcf5a/datafusion/src/physical_plan/expressions/sum.rs#L49 for floating-point datatype, the [pg](https://www.postgresql.org/docs/8.2/functions-aggregate.html) use the double-precision(double/float64) as the returned data type, but the datafusion is different.

There may be other different rules in [spark](https://spark.apache.org/docs/3.2.0/sql-ref-ansi-compliance.html#type-coercion)

Which rule should we follow? For example sum and avg?
@alamb @houqp 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
@liukun4515  -- I think the rationale for using `float64` for the result of `sum(float32)` and `avg(float32)` is done to minimize error due to floating point rounding

I think using `float64` for the result type makes sense

**Comment by liukun4515** [comment]
> I think using `float64` for the result type makes sense

Do you mean to change this line https://github.com/apache/arrow-datafusion/blob/415c5e124af18a05500514f78604366d860dcf5a/datafusion/src/physical_plan/expressions/sum.rs#L57 and return FLOAT64 for sum(float32)?
