### ISSUE TITLE
ExecutionContext support init ExecutionContextState with `new(state: Arc<Mutex<ExecutionContextState>>)` method

### ISSUE THREAD

**Issue by gaojun2048** [apache/arrow-datafusion#1439]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Now, we can only create a datafusion execution context with default table information in ballista, we can't just create a new context because we need a context that has tables registered from previous SQL statements that have been executed.
![image](https://user-images.githubusercontent.com/32193458/145745802-45304fa6-c6ab-4f78-b167-e73476373343.png)

**Describe the solution you'd like**
If ExecutionContext support init ExecutionContextState with `new(state: Arc<Mutex<ExecutionContextState>>)` method, then we can manage this information in the ballista scheduler, and send this information to the ballista executor, where every datafusion ExecutionContext created in the ballista executor can be Have the same ExecutionContextState content.

**Comment by ic4y** [comment]
🚀
