### ISSUE TITLE
 Implement optional second argument to ltrim and rtrim functions

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#144]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-11164

https://github.com/apache/arrow/pull/9108 adds the ltrim and rtrim functions to datafusion, following postgres. However, postgres offers a second optional argument (the character to trim) that is not yet implemented, as described on https://www.postgresql.org/docs/9.1/functions-string.html

For example:
 !103891510-f84d8800-50b7-11eb-929e-94f56c2364cd.png! 

This ticket tracks the work to add support for the second optional arguments (what character to trim) - it would probably be a good introductory item for new contributors.

There is more context here:
https://github.com/apache/arrow/pull/9108#pullrequestreview-563440252

**Comment by Jefffrey** [comment]
Implemented by https://github.com/apache/arrow-datafusion/commit/bc1e590edbf77f5fe112a89fe7f3272b5de06ea2

Issue can be closed

**Comment by Dandandan** [comment]
Thanks @Jefffrey
