### ISSUE TITLE
try to read data from apache kudu

### ISSUE THREAD

**Issue by jiangzhx** [apache/arrow-datafusion#1440]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

datafuison now support csv,parquet datasource.
our team want to  add more datasource like apache kudu;
is there docs or advise to help us do the right way.

**Comment by houqp** [comment]
There is no docs on this as far as I know. I think it's best to add support for kudu through a table provider. The existing memory table provider is a pretty minimal example on provider implementation: https://github.com/apache/arrow-datafusion/blob/master/datafusion/src/datasource/memory.rs. You can also take a look at the listing table provider for a more advanced implementation.
