### ISSUE TITLE
[Question] I'm doing some benchmark test(TPCH) on DataFusion, is there a way to run the benchmark in a single thread?

### ISSUE THREAD

**Issue by mingmwang** [apache/arrow-datafusion#1452]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
Hi @mingmwang  -- I think setting `partitions` to `1` is the closest we have at the moment

So something like
```shell
./target/debug/tpch benchmark datafusion -n 1 ...
```

**Comment by alamb** [comment]
If you want to ensure only a single thread is used, you can set the tokio runtime to use a single thread

Something like modify https://github.com/apache/arrow-datafusion/blob/7996fa86720fd96628bc07b7ee3f226107b7f969/benchmarks/src/bin/tpch.rs#L187-L189

And change 

```rust
#[tokio::main]
```

to 
```rust
#[tokio::main(core_threads = 1, max_threads = 1)]
```

**Comment by alamb** [comment]
I think this question has been answered, so closing
