### ISSUE TITLE
fix calculate total_rows in many_to_many_hash_partition

### ISSUE THREAD

**Issue by Ted-Jiang** [apache/arrow-datafusion#1462]
**Describe the bug**

`        let total_rows: usize = output_partitions.iter().map(|x| x.len()).sum();
`
is sum the total RecordBatch number.

For now empty RecordBatch will send to next plan so the total_RecordBatch equals total_rows
**To Reproduce**
https://github.com/apache/arrow-datafusion/pull/1459
**Expected behavior**
`let total_rows: usize = output_partitions
            .iter()
            .map(|x| x.into_iter().map(|x| x.num_rows()).sum::<usize>())
            .sum();`
is sum the total row number

**Comment by Dandandan** [comment]
Closed by #1463
