### ISSUE TITLE
Keep all datafusion's packages up to date with Dependabot

### ISSUE THREAD

**Issue by xudong963** [apache/arrow-datafusion#1472]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
As the title.

**Describe the solution you'd like**
Add a `dependabot.yml` into `.github`. 

https://github.com/marketplace/actions/dependencies-autoupdate
https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/

**Describe alternatives you've considered**
No

**Additional context**
Suitable for newcomers.

**Comment by alamb** [comment]
YES! This would be super super helpful -- great idea @xudong963
