### ISSUE TITLE
Internal error: Unsupported data type in hasher: FixedSizeBinary(16)

### ISSUE THREAD

**Issue by FauxFaux** [apache/arrow-datafusion#1516]
**Describe the bug**
An aggregation query against a `FixedSizeBinary` column returns an internal error:

`Error: Arrow error: External error: Execution error: Arrow error: External error: Internal error: Unsupported data type in hasher: FixedSizeBinary(16).`

**To Reproduce**

`ctx.sql("select fsb, count(*) from tbl group by fsb")` for some `fsb FixedSizedBinary` column.

**Expected behavior**

I expect this column to be treated as if it was a `Binary`: equality based on length and byte equality.

**Additional context**
I realise there's very little support for `FixedSizeBinary` columns anywhere else; I have built my own equality as a UDF. Not sure if there's a wider plan here, like "always treat them as `Binary`".

I'm pulling these from Parquet; they are legitimately binary opaque keys, exactly like a (v4) UUID, and I believe a FixedSizeBinary is the right type for them here. They have duplicates in a way that Parquet's compression handles well.

**Comment by liukun4515** [comment]
The DF doesn't support hash for the  `FixedSizedBinary` type.

**Comment by lquerel** [comment]
Also doesn't work on Arrow List and some other complex Arrow types. This makes the `SELECT DISTINCT * FROM table` syntax almost useless in general as any unsupported column type will result in an error.
