### ISSUE TITLE
Add version field to ExecutionContext

### ISSUE THREAD

**Issue by tfeda** [apache/arrow-datafusion#1517]
Is your feature request related to a problem or challenge? Please describe what you are trying to do.

#1514 points out a secondary goal for the python library to expose the datafusion and arrow-rust versions.
I think Spark has a good implementation of this by binding the spark version to SparkContext in the jvm code, then exposing it to the pyspark API. pyspark's version itself is hard-coded. 

Describe the solution you'd like

Add a version field to the ```ExecutionContext``` struct, and expose it to the datafusion-python library. The version could then be retrieved by users by calling ```ExecutionContext.version```

Describe alternatives you've considered

Leaving it out of the rust implementation and just putting it in the python version.

Additional context
I'm not sure how arrow-rust's version would be added, but a similar approach could be taken.

**Comment by tfeda** [comment]
I'm new to the project (and open source in general), so I think this would be a good exercise for me. Because it's an API addition, I could use some stylistic input on the solution I proposed above.

**Comment by alamb** [comment]
What version would you like to appear? Do you have in mind the `version` of the rust crate https://github.com/apache/arrow-rs/blob/master/arrow/Cargo.toml#L20 ? If so you can probably follow the same model as parquet

Here is how the version is embedded in parquet files 'created by' fields: https://sourcegraph.com/github.com/apache/arrow-rs/-/blob/parquet/build.rs?L20:25&subtree=true

https://stackoverflow.com/questions/27840394/how-can-a-rust-program-access-metadata-from-its-cargo-package
