### ISSUE TITLE
Add load test in tpch.rs

### ISSUE THREAD

**Issue by Ted-Jiang** [apache/arrow-datafusion#1521]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
I want to find out how ballista scheduler how many concurrency can be supported.

**Describe the solution you'd like**
Add loadTest Option in tpch.rs,  
  we could set:
    1. request amount
    2. Concurrency clients number
    3. ....
    4. 
then random pick tpch-query run in cluster,  finally collect some metrics.

**Describe alternatives you've considered**

**Additional context**
I am glad to do this test and share data with community.

**Comment by liukun4515** [comment]
The issue will be closed automatically, with `Close #1521` in the pull request. Just like Close #1521.
@Ted-Jiang
