### ISSUE TITLE
Add Decimal support for statistical functions `var` and `stddev`

### ISSUE THREAD

**Issue by realno** [apache/arrow-datafusion#1529]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

A PR is open for adding variance and standard deviation functions to DataFusion (https://github.com/apache/arrow-datafusion/pull/1525). Decimal type is not supported as Postgres spec (https://www.postgresql.org/docs/9.1/functions-aggregate.html). This issue is to capture the work.

**Describe the solution you'd like**
`var`, `var_samp`, `var_pop`, `stddev`, `stddev_samp`, `stddev_pop` should support decimal type.

**Describe alternatives you've considered**

**Additional context**
The work can be added to (#122) or create a new PR once it's merged.

**Comment by Dandandan** [comment]
This is supported now
