### ISSUE TITLE
Ballista scheduler dead loop in loadtest 

### ISSUE THREAD

**Issue by Ted-Jiang** [apache/arrow-datafusion#1531]
**Describe the bug**
1. start scheduler `RUST_LOG=INFO cargo run   --bin ballista-scheduler` 
2. start one executor  'RUST_LOG=INFO cargo run --release  --bin ballista-executor '
3. run load test in #1521  with `RUST_LOG=INFO cargo run --bin tpch -- loadtest  ballista-load --query-list 1,3,5,6,7,10,12,13  --data-path ***/tpch-1g-oneFile/ --format parquet --host localhost --port 50050 --sql-path **` -> this run 100 sqls with 5 clients concurrency.

the scheduler will hang forever after  run cmd at most twice times.

**Additional context**
i use process sample to take the stack trace 

https://docs.google.com/document/d/13rTSlbE0NwCeZvw33dfJrhuVuPoc1RTWQSP42vlzoK8/edit?usp=sharing

it seems all tokio-runtime-worker are at `_pthread_cond_wait`

**Comment by Ted-Jiang** [comment]
All 16 tokio-runtime-worker are lock at sled::subscriber::Subscribers `register` or `reserve`

`register` : create a Subscribe  on some key in sled
`reserve`:  create a Broadcast  on some key in sled
above two operations will all acquire a same write lock 

in the stack trace only `Thread_396250` get the lock, but stuck in the `std::sync::mpsc::SyncSender` for some reason.

**Comment by Ted-Jiang** [comment]
I found `ballista_scheduler::SchedulerServer::new` 11 times in process 

https://github.com/apache/arrow-datafusion/blob/847e78a675703c24933af5d6a429c2576bc14e9d/ballista/rust/scheduler/src/main.rs#L68

it seems each  will new a SchedulerServer
each new() will create a synchronize_job_status_loop

https://github.com/apache/arrow-datafusion/blob/847e78a675703c24933af5d6a429c2576bc14e9d/ballista/rust/scheduler/src/lib.rs#L112

synchronize_job_status_loop() will  `register `  all the key-value change in sled.

**Comment by Ted-Jiang** [comment]
I think it should create only one synchronize_job_status_loop in one ballista_scheduler process. 

@andygrove  @Dandandan  @alamb   FYI

**Comment by alamb** [comment]
hi @Ted-Jiang  -- thanks for the report. I am not super familiar with the ballista internals but it definitely sounds like a bug to me. We would welcome a pull request with a fix

**Comment by houqp** [comment]
Thanks @Ted-Jiang for the deepdive, if you look at the comment above the tokio spawn line you linked, it also mentioned we should only run a single loop. Perhaps we should first look into whether it is expected to have 11 scheduler server created in the first place in the same process.

**Comment by Ted-Jiang** [comment]
> Thanks @Ted-Jiang for the deepdive, if you look at the comment above the tokio spawn line you linked, it also mentioned we should only run a single loop. Perhaps we should first look into whether it is expected to have 11 scheduler servers created in the first place in the same process.

Thanks @houqp  for your reply, in my opinion:
https://github.com/apache/arrow-datafusion/blob/d6d90e93117293adfa7aa6f4a93bd796665c28a3/ballista/rust/scheduler/src/main.rs#L67
send  a closure to `make_service_fn`, each request will call `SchedulerServer::new` then start a synchronize_job_status_loop

i think it should extract  `SchedulerServer::new` before start server
https://github.com/apache/arrow-datafusion/blob/d6d90e93117293adfa7aa6f4a93bd796665c28a3/ballista/rust/scheduler/src/main.rs#L66
send copy to each request, is this ok ?
