### ISSUE TITLE
Not able to get the table from register_listing_table

### ISSUE THREAD

**Issue by selvavm** [apache/arrow-datafusion#1536]
**Describe the bug**
When I want to generate a dataframe over 

**To Reproduce**

            let file_format = ParquetFormat::default().with_enable_pruning(true);
            let listing_options = ListingOptions {
                file_extension: ".parquet".to_owned(),
                format: Arc::new(file_format),
                table_partition_cols: vec!["country".to_string()],
                collect_stat: true,
                target_partitions: parquet_file_count,
            };
           ctx.register_listing_table(
                "my_table",
                &r#"C:\builds\testdata"#.to_string(),
                listing_options,
                None,
            )
            .await;
            ctx.table("my_table")

My testdata folder,

         testdata
         |_ country=france
            |_ file1.parquet
         |_ country=china
            |_ file1.parquet

**Expected behavior**
`ctx.table` should return a dataframe

**Actual behavior**
`thread 'main' panicked at 'called Result::unwrap() on an Err value: Plan("No table named 'my_table'")'`

**Additional context**

**Comment by houqp** [comment]
Did `register_listing_table` return an error for you?

**Comment by selvavm** [comment]
@houqp No. `ctx.table` returns an error. My knowledge on Parquet is limited. Sorry for that. 

Below are the things I tried,

- Changed the `uri` field in register_listing_table as `&format!("file://{}","C:\\builds\\testdata")` - Still same
- Changed the code like below which now doesn't throw error but returns empty table

        Runtime::new().unwrap().block_on(async {
            ctx.register_listing_table(
                "my_table",
                &format!("file://{}","C:\\builds\\testdata")
                listing_options,
                None,
            )
            .await
            .unwrap()
            });
        Runtime::new().unwrap().block_on(async {
            let a: Vec<RecordBatch> = df
               .select(vec![col("state")])
               .unwrap()
               .collect()
               .await
               .unwrap();
               pretty::print_batches(&a);
        });

- Changed the `table_partition_cols: vec!["country".to_string()],` to `table_partition_cols: vec![],`. With this, I am getting below error, 
`ParquetError(General("Repetition level must be defined for a primitive type"))'`

I tried viewing my parquet using a viewer tool and the metadata is as follows,

    {
      "Version": 1,
      "Num_rows": 50,
      "Created_by": "parquet-rs version 6.5.0",
      "Schema": [
        {
          "Field_id": 0,
          "Name": "state",
          "Type": "BYTE_ARRAY",
          "Type_length": 0,
          "LogicalType": null,
          "Scale": 0,
          "Precision": 0,
          "Repetition_type": "REQUIRED",
          "Converted_type": "UTF8"
        },
        {
          "Field_id": 0,
          "Name": "population",
          "Type": "FLOAT",
          "Type_length": 0,
          "LogicalType": null,
          "Scale": 0,
          "Precision": 0,
          "Repetition_type": "REQUIRED",
          "Converted_type": "UTF8"
        },
    }

**Comment by houqp** [comment]
> ParquetError(General("Repetition level must be defined for a primitive type"))'

This error usually comes from parquet parsing, so I am surprised individual file works without error for you. Do you get this error with just a single partition? If so, it would be helpful if you can upload that single file here for others to reproduce.

**Comment by selvavm** [comment]
Hi @houqp. Sure I will try to reproduce the example and share. My understanding is - `Datafusion (or Arrow)` is able to understand the folder structure as Hive format and tries to create a new field (`country`). It is failing because nowhere I have an option to tell the `"Repetition_type": "REQUIRED"` for this new field.

**Comment by selvavm** [comment]
Hi @houqp. Sorry for delay in response.

I have created a minimum example which reproduce the problem. It is [here](https://github.com/apache/arrow-datafusion/files/7874537/sample_share.zip)

**Expected Result**
|id|
| -------------|
|1|
|2|

**Actual Result**
++
++
