### ISSUE TITLE
Replace DataFusionError/Result with impl Error for ObjectStore and Reader 

### ISSUE THREAD

**Issue by matthewmturner** [apache/arrow-datafusion#1540]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)
In the context of adding S3 support (https://github.com/datafusion-contrib/datafusion-objectstore-s3/pull/12) I propose changing the signature for the `ObjectStore` and `ObjectReader` trait methods so that they return a generic error instead of datafusion error.  This way extensions, such as s3, can implement their own error types and we can have clearer view of what is causing error.

**Describe the solution you'd like**
The `ObjectStore` and `ObjectReader` trait methods that return a datafusion `Result` or `Error` should be changed to something like `impl Error` (i.e. an error that isnt specific to Datafusion)

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
@matthewmturner 

It is possible today to return a `Box<dyn Error>` as a `DatafusionError`which is pretty nasty but works in (that we use in IOx)  which is to return a `DataFusionError::ArrowArrowError::External(Box::new(boxed_error))`. Here is an example: https://github.com/influxdata/influxdb_iox/blob/e8ddc4e0db4c59f039a34f0e3297c9eb495c1d5a/query/src/exec/non_null_checker.rs#L271

Given how nasty that is, one alternative might be to add a `DataFusion::External` and follow  the model of `ArrowError::External` in https://github.com/apache/arrow-rs/blob/master/arrow/src/error.rs#L29

Or maybe we can simply add a `From<Box dyn Error> for DataFusionError` to make the conversion nicer

**Comment by houqp** [comment]
> Or maybe we can add a From<Box dyn Error> for DataFusionError to make the conversion nicer

I like the idea of doing this combined with the new `Datafusion::External` enum.

**Comment by matthewmturner** [comment]
I was playing with `From<Box<dyn Error>> for DataFusionError` before but having issues with it.  I think if i'm understanding correctly the approach we could do, as @houqp mentioned, would be something like the following:

```
pub enum DataFusionError {
    /// Error returned by arrow.
    ArrowError(ArrowError),
    ...
    /// Errors originating from outside DataFusion's core codebase.
    /// For example, a custom S3Error from the crate datafusion-objectstore-s3
    ExternalError(Box<dyn Error + Send + Sync>),
} 

impl From<Box<dyn Error>> for DataFusionError {
    fn from(err: Box<dyn Error>) -> Self {
        DataFusionError::External(err)
    }
```

Is this what you guys had in mind?
