### ISSUE TITLE
Add covar operators to DataFusion

### ISSUE THREAD

**Issue by realno** [apache/arrow-datafusion#1548]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Add covar operators to data fustion.

**Describe the solution you'd like**

Add three operators: `covar`, `covar_samp` and `covar_pop`.

**Describe alternatives you've considered**

**Additional context**

**Comment by realno** [comment]
I will be working on this issue.

**Comment by alamb** [comment]
Thanks @realno
