### ISSUE TITLE
ARROW2: fix csv schema inference records to read calculation

### ISSUE THREAD

**Issue by houqp** [apache/arrow-datafusion#1563]
**Describe the bug**

Now that we have upstream support in https://github.com/jorgecarleitao/arrow2/pull/765, we should address the FIXME in datasource/file_format/csv.rs.

**Additional context**

This is a left over item for the arrow2 branch.

**Comment by jorgecarleitao** [comment]
PR: https://github.com/jorgecarleitao/arrow2/pull/765

**Comment by houqp** [comment]
fixed by @Igosuki :rocket:
