### ISSUE TITLE
Memory Limited Sort (Externalized / Spill)

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#1568]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Support Sorting "arbitrarily" large inputs (that don't fit in RAM or within some user defined budget)

This ticket concerns the memory potentially used the Sort operator -- it doesn't cover other potential targets (e.g. sort based aggregation, for example). That will be covered by other tasks tracked by #587 

**Describe the solution you'd like**
1. Allow DataFusion users to specify a RAM budget (aka via the config introduced in #1526) and have their queries complete running without the sort exceeding that budget.
2. Make sure there is a single production ready implementation of `N-way Merge of Sorted Streams` to build on top of

For the Sort operator, I think the best behavior would be:
1. Sort all the input in RAM (as is done today in [`SortExec`](https://github.com/apache/arrow-datafusion/blob/master/datafusion/src/physical_plan/sorts/sort.rs) ), if the memory budget allows
2. If all the input does not fit in the RAM budget, the in memory portion is sorted and written to temporary disk files
3. Temporary disk files are read / merged to produce the final results

@yjshen 's PR https://github.com/apache/arrow-datafusion/pull/1526 has most of the individual pieces of this logic, but they aren't hooked up yet (that is if you run `SELECT .. FROM foo ORDER BY x`) it will still exhaust memory. 

Some ideas of how to break this task down

- [x] #1571
- [x] #1573
- [x] #1572
- [x] https://github.com/apache/arrow-datafusion/issues/1611
- [ ] #2148
- [x] #2149
- [ ] #2150
- [ ] #2151

**Describe alternatives you've considered**
Use two implementations of Sort (one in memory and one that can spill). This would ensure no performance regressions for the non-spilling case but would require users to decide which one to use. 

**Context**
This is follow on work from the great PR from @yjshen in https://github.com/apache/arrow-datafusion/pull/1526 and part of the story of limiting memory used by DataFusion https://github.com/apache/arrow-datafusion/issues/587

**Comment by alamb** [comment]
cc @yjshen here are some thoughts on the next steps for sorting -- what do you think? Are you planning to do any/all of this? Is there something in particular I could help the most with?

**Comment by yjshen** [comment]
Thanks @alamb . Let me start from #1572 first. Anyone interested in could drop in then.

**Comment by yjshen** [comment]
Add https://github.com/apache/arrow-datafusion/issues/1611 to tracking spills in sort metrics.

**Comment by alamb** [comment]
I think this issue is mostly done. We can track additional work items as follow on epics, etc
