### ISSUE TITLE
Track memory usage in Non Limited Operators

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#1569]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Ensure that physical `ExecutionPlan` nodes properly report their memory usage so DataFusion's can properly stay under its memory budget

**Describe the solution you'd like**
1. Figure out a pattern to make ExecutionPlans be `Tracking` memory consumers (api in https://github.com/apache/arrow-datafusion/pull/1526)
2. Apply that pattern to all operators built into DataFusion

**Describe alternatives you've considered**
N/A

**Context**
This is follow on work from the great PR from @yjshen in https://github.com/apache/arrow-datafusion/pull/1526 and part of the story of limiting memory used by DataFusion https://github.com/apache/arrow-datafusion/issues/587

**Comment by yjshen** [comment]
I want to propose adding a new kind of Metric: `Gauge`, which is much like the current `Count` but provide two extra methods `sub` and `set`:

```rust
#[derive(Debug, Clone)]
pub struct Gauge {
    /// value of the metric gauge
    value: std::sync::Arc<AtomicUsize>,
}

impl Gauge {
    /// create a new gauge
    pub fn new() -> Self {
        Self {
            value: Arc::new(AtomicUsize::new(0)),
        }
    }

    /// Add `n` to the metric's value
    pub fn add(&self, n: usize) {
        // relaxed ordering for operations on `value` poses no issues
        // we're purely using atomic ops with no associated memory ops
        self.value.fetch_add(n, Ordering::Relaxed);
    }

    /// Substract `n` from the metric's value
    pub fn sub(&self, n: usize) {
    }

    /// set the metric's value to `n`
    pub fn set(&self, n: usize) {
    }

    /// Get the current value
    pub fn value(&self) -> usize {
        self.value.load(Ordering::Relaxed)
    }
}
```

And by adding `CurrentMemoryUsage(Gauge)` to `BaselineMetrics`, we could achieve the goal of memory tracking more easily. 

Besides, a `MaxMemoryUsage(Gauge)` could be used, providing more configuration optimization info to users.

cc @alamb @houqp for more thoughts.

**Comment by houqp** [comment]
Yeah makes sense to me, i am actually surprised we don't have gauge type already. Do we really need the `add` and `sub` method? I was under the impression that you almost always call `set` on guage type metrics directly.

**Comment by yjshen** [comment]
`add` will be helpful for `ConsumerType::Requesting` since we are growing memory usage each time we acquire. I haven't thought of a use case for `sub` yet. Maybe leave that until we see the need.

**Comment by alamb** [comment]
I agree getting a Gauge sounds like a good idea. thanks for the writeup @yjshen
