### ISSUE TITLE
ARROW2: remove clock feature for chrono dependency

### ISSUE THREAD

**Issue by houqp** [apache/arrow-datafusion#1584]
**Describe the bug**

From @jorgecarleitao 

> Note that this feature has a known vulnerability. arrow-rs depends on it, arrow2 does not (casting from utf8 to datetime is consistent with the arrow spec's definitions of timezone-aware timezones).

We should look into whether we can remove this feature in datafusion. From what I have seen so far, we are only using this feature to get the current system time.

**Additional context**
[Add any other context about the problem here.](https://github.com/apache/arrow-datafusion/pull/1556#discussion_r784523384.)

**Comment by Dandandan** [comment]
I think we can close it as arrow2 and arrow will be merged in the future.
