### ISSUE TITLE
datafusion doesn't process predicate pushdown correctly when there is outer join

### ISSUE THREAD

**Issue by xudong963** [apache/arrow-datafusion#1586]
**Describe the bug**

Now datafusion doesn't process predicate pushdown correctly when there is `outer join`. I have discussed much in #1339 with @alamb. I think we ended up with a consensus.

Notes that filtering conditions fall into two categories: `join condition` and `where condition`, I'll explain them separately in the following:
1. **join condition**: if the filter condition contains the **non-nullable-side** table, it can't be pushed down.
2. **where condition**: if the filter condition contains the **nullable-side** table, it can't be pushed down. But it's can be optimized, I describe how to process the case in #1585.

**Additional context**
related issues and pr: #1321 , #1585,  #1339

**Comment by xudong963** [comment]
cc @alamb

**Comment by james727** [comment]
I can try this one if no one is working on it yet.

**Comment by xudong963** [comment]
> I can try this one if no one is working on it yet.

I believe no one is working on it, please do it! Thanks, @james727
