### ISSUE TITLE
Follow up on the removal of `update` and `merge` in `Accumulator`

### ISSUE THREAD

**Issue by Jimexist** [apache/arrow-datafusion#1598]
I think it would be a good idea as a follow on PR to update these implementations to avoid the use of ScalarValue. 

I'll try find some time this week to do it (I need some coding time :) -- lots of reviewing so far)

_Originally posted by @alamb in https://github.com/apache/arrow-datafusion/pull/1582#discussion_r786044972_

**Comment by alamb** [comment]
Basically the idea here would be to rewrite the implementations that use `ScalarValue` to directly use the appriate arrow compute kernels: https://docs.rs/arrow/7.0.0/arrow/compute/index.html

**Comment by Weijun-H** [comment]
This issue can be closed, because all parts are refactored.

**Comment by alamb** [comment]
Thank you @Weijun-H
