### ISSUE TITLE
Remove redundant`is_numeric` and other checks for DataType

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#1613]
`arrow-rs` has some functions to check data type, and the logic is also in datafusion, for example, https://docs.rs/arrow/7.0.0/arrow/datatypes/enum.DataType.html#method.is_numeric

We should reduce the redundancy in DataFusion to make the codebase clear.

_Originally posted by @liukun4515 in https://github.com/apache/arrow-datafusion/pull/1606#discussion_r787306626_

**Comment by alamb** [comment]
This is a good one -- just delete some code from DataFusion 👍

**Comment by HaoYang670** [comment]
`is_numeric` in `arrow-rs` seems not to be same as in `arrow-datafusion` because `DataType::Decimal` is not included.

**Comment by liukun4515** [comment]
> `is_numeric` in `arrow-rs` seems not to be same as in `arrow-datafusion` because `DataType::Decimal` is not included.

@HaoYang670 

In the PG or Spark, the decimal is included in the `numeric`.
Because the decimal is in development, some codes may be not consistent.

**Comment by liukun4515** [comment]
Now we can focus on other issues, and deal with them after other stabilization.

**Comment by HaoYang670** [comment]
At least, should rename this function, so that developers would not misuse this and `DataType::is_numeric`.
