### ISSUE TITLE
Include join type in display implementation for logical plan

### ISSUE THREAD

**Issue by james727** [apache/arrow-datafusion#1620]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Right now when printing a logical plan with a join there is no indication of the type of join involved. For example, the following can represent any one of a left/right/inner/full join:
```
Join: Using #test.a = #test2.a
```

**Describe the solution you'd like**
Update `display` to include the `JoinType`.

**Additional context**
This would be useful for testing https://github.com/apache/arrow-datafusion/issues/1585

**Comment by houqp** [comment]
Good idea :+1:

**Comment by xudong963** [comment]
A very useful feature, I'll implement it and use it. Thanks for your idea @james727
