### ISSUE TITLE
Provide RuntimeEnv to ExecutionContext

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-datafusion#1636]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

https://github.com/apache/arrow-datafusion/pull/1526 added a MemoryManager along with the concept of a RuntimeEnv, this is awesome. Unfortunately `ExecutionContext::new()` and `ExecutionContext::with_config` call `RuntimeEnv::new()`, which in turn creates a new `MemoryManager` and `DiskManager`, which create a temporary directory and print logs, which is decidedly less awesome.

At least within IOx we construct an `ExecutionContext` for each query, as various settings may change, most notably the catalog. Therefore these logs and especially the directory creation and associated IO (#1637) are problematic.

**Describe the solution you'd like**

I think it should be possible to pass an extant `Arc<RuntimeEnv>` to an `ExecutionContext`, so that multiple different `ExecutionContext` can share the same resource pool.

**Describe alternatives you've considered**

We could maintain separate `ExecutionContext` for each type of query IOx executes, but this is just punting the problem imo. We want to be able to have queries running in different contexts, but on the same pool of resources managed by a `RuntimeEnv`.

FYI @yjshen

**Comment by alamb** [comment]
Being able to do something like

```rust
let context = context.with_runtime(existing_runtime);
```

makes a lot of sense to me

**Comment by yjshen** [comment]
Thanks for the detailed explanation of the use case in Influx, haven't thought of it before. I think it would be great to have this.

**Comment by alamb** [comment]
I plan to work on this issue, with respect to https://github.com/influxdata/influxdb_iox/issues/3507

**Comment by alamb** [comment]
In general I am planning a cleanup to the `MemoryManager` and `DiskManager` configuration. I expect to have a PR for review shortly

**Comment by alamb** [comment]
PR with proposed improvements: https://github.com/apache/arrow-datafusion/pull/1668#
