### ISSUE TITLE
thread 'tokio-runtime-worker' panicked at 'not implemented: Take not supported for data type Decimal(18, 4)

### ISSUE THREAD

**Issue by hengaini2055** [apache/arrow-datafusion#1661]
**Describe the bug**
I use datafusion-cli using sql. When I select sum(amount) as amount from my_table; , then everything is OK. When I use sql "select dept, sum(amount) as amount from my_table group by dept;', I get the error:

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by hengaini2055** [comment]
My parquet file has a decimal(18,4) column named amount.  The exact error is 
```
thread 'tokio-runtime-worker' panicked at 'not implemented: Take not supported for data type Decimal(18, 4)', C:\Users\hengaini2055\.cargo\registry\src\mirrors.ustc.edu.cn-12df342d903acd47\arrow-7.0.0\src\compute\kernels\take.rs:297:14
```

**Comment by hengaini2055** [comment]
The parquet file is exported using odbc2parquet tool from SQLServer Database.
```
odbc2parquet query --dsn wd_bi_test --password "888888" --user "88" e:\temp\bi_test_jd2.parquet "select Period, dept cast(amount as decimal(18,4)) as amount, yw1_name, yw2_name, yw3_name from my_table"
```

**Comment by alamb** [comment]
This will likely be fixed as soon as we can upgrade to arrow 8.0.0 (due to be released today): https://github.com/apache/arrow-rs/pull/1172 

Sorry for the delay

cc @liukun4515

**Comment by liukun4515** [comment]
> amount

This https://github.com/apache/arrow-rs/pull/1172 has been merged, and the [group by supported](https://github.com/apache/arrow-datafusion/pull/1640) merged.
But we need to wait for the arrow-rs to upgrade which is doing by @alamb.
I think this feature will support soon after the arrow-rs 8.0.0 is released.

**Comment by alamb** [comment]
I am waiting on the final approval needed to release 8.0.0. I hope I can get this today

**Comment by alamb** [comment]
Released https://lists.apache.org/thread/b803mt0g8czbz3l31230053o2q728mqw 🎉 

I will get a PR up to upgrade datafusion

**Comment by liukun4515** [comment]
thanks @alamb 
Maybe we can close this ticket
