### ISSUE TITLE
Update `clap` version to 3.0.12

### ISSUE THREAD

**Issue by xudong963** [apache/arrow-datafusion#1666]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
see https://github.com/apache/arrow-datafusion/pull/1632

**Describe the solution you'd like**

**Describe alternatives you've considered**
Changes related to the Ballista configuration are involved, so you may need to know about Ballista.

**Additional context**

**Comment by alamb** [comment]
Fixed in https://github.com/apache/arrow-datafusion/pull/1672
