### ISSUE TITLE
Support reading from CSV, Avro and Json files that have mergeable/compatible,  but not identical schemas

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#1669]
@thinkharderdev implemented schema merging functionality for Parquet files in #1622. However, this logic only applies to Parquet, and @tustvold noted that it would likely also be useful to apply to CSV, Avro and Json files so that DataFusion could read from files in those formats that had compatible but not identical schemas

Specifically,  the logic in read_partition might be extracted into some of `SchemaAdapter`, akin to `PartitionColumnProjector`. This would allow the logic to be reused with other file formats, e.g. JSON or CSV, whilst also allowing testing it in isolation.

_Originally posted by @tustvold in https://github.com/apache/arrow-datafusion/pull/1622#discussion_r789900481_

**Comment by thinkharderdev** [comment]
Since I made this mess I feel duty-bound to clean it up :) I can take this one.

**Comment by alamb** [comment]
> Since I made this mess I feel duty-bound to clean it up :) I can take this one.


I wouldn't describe this as a mess ! The ability to merge multiple parquet files without the exact same schema is a great addition -- this will just be the icing on the cake, as it were
