### ISSUE TITLE
 Support DataType::Decimal(15, 2) in TPC-H benchmark

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#174]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-11536

Currently converting the Float64 to Decimal(15, 2) fails with:

Error: Plan("\'Int64 - Decimal(15, 2)\' can\'t be evaluated because there isn\'t a common type to coerce the types to")

FYI [~MikeSeddonAU]

**Comment by liukun4515** [comment]
@alamb  this issue can be closed.
The cast/try_cast has been implemented.
We can cast float to decimal or decimal to float.

**Comment by liukun4515** [comment]
```
❯ select cast(12.33 as decimal(10,2));
+----------------------------------------+
| CAST(Float64(12.33) AS Decimal(10, 2)) |
+----------------------------------------+
| 12.33                                  |
+----------------------------------------+
1 row in set. Query took 0.006 seconds.
```

**Comment by houqp** [comment]
:tada:
