### ISSUE TITLE
Support CREATE/DROP/ALTER VIEW (and associated DataFrame functions)

### ISSUE THREAD

**Issue by Igosuki** [apache/arrow-datafusion#1740]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Currently we can create external and in memory listing tables, I want to go further and allow creating views from SQL queries.
Registering a dataframe as a table requires the following : 
``` 
    let table = ctx.clone().sql(&sql_query).await?;
    let df_impl = Arc::new(DataFrameImpl::new(ctx.state.clone(), &table.to_logical_plan()));
    ctx.register_table(table_name.as_str(), df_impl.clone())?;
```

**Describe the solution you'd like**
Since DataframeImpl is already a TableType::View, registering/droping/altering a view could be done from SQL, or directly with ```ctx.create_view(df: Arc<dyn DataFrame>) or df.register_as_view(name: impl Into<TableReference>)```
and 
```
ctx.sql("CREATE VIEW records AS select * from other_records where ...")
```

**Describe alternatives you've considered**
Leaving things as is

**Additional context**
Make it easier to use arrow-datafusion without knowing its internals.

**Comment by alamb** [comment]
🤔  since `SchemaProvider` already allows registering a new table provider, we might be able to implement this without any new traits

https://github.com/apache/arrow-datafusion/blob/6ec18bb4a53f684efd8d97443c55035eb37bda14/datafusion/src/catalog/schema.rs#L40-L51

**Comment by matthewmturner** [comment]
Im very interested in this as well, in particular just getting started with enabling `CREATE VIEW`.

@Igosuki did you have plans to work on this?

**Comment by Igosuki** [comment]
I would love to but I am quite busy with other things these days (recently got knee surgery). So feel free to take ownership !

**Comment by matthewmturner** [comment]
Sorry to hear - wishing you a speedy recovery!

I hope to look into it soon.  Will keep you posted.

**Comment by alamb** [comment]
Create VIEW would be cool indeed -- I suggest adding it to the Catalog/Schema provider traits (as the view definitions logically belong there I think)

**Comment by matthewmturner** [comment]
@alamb noted - i will look into that.

**Comment by matthewmturner** [comment]
I have started work on `CREATE VIEW`
