### ISSUE TITLE
Break datafusion crate into smaller crates

### ISSUE THREAD

**Issue by Jimexist** [apache/arrow-datafusion#1750]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

a new feature: to break `datafusion` crate into separate smaller crates.

It helps with code management and dependency reasoning

**Describe the solution you'd like**

- [x] #1752
  - [x] #1751 
  - [x] #1758 
  - [x] #1760 
- [x] #1753 
  - [x] #1759 
  - [x] #1761 
  - [x] #1763 
  - [x] #1764 
  - [x] #1765 
  - [x] #1762
  - [x] #1774 
  - [x] #1784 
  - [x] #1762 
  - [x] #1794 

---

- [x] #1844
  - [x] #1843 
  - [x] #1865
  - [x] https://github.com/apache/arrow-datafusion/pull/1889 
  - [x] https://github.com/apache/arrow-datafusion/pull/1892
- [x] #1772
  - [ ] file format
  - [ ] listing and object store
- [ ] #1755 
  - [ ] move logical plan builder
  - [ ] move logical plan structs
  - [ ] move move optimizers
- [ ] #1754 
  - [ ] move physical planner
  - [ ] move execution exprs
  - [ ] move physical plan optimizer
- [ ] split datafusion-execution sub-module
  - [ ] move memory and disk manager
  - [ ] move stats collection

**Describe alternatives you've considered**

**Additional context**

**Comment by Jimexist** [comment]
cc @alamb @houqp @Dandandan what do you think?

**Comment by alamb** [comment]
I like this idea @Jimexist  👍  There is some related commentary / information here: https://github.com/apache/arrow-datafusion/issues/348 as well

Some other crates that might be useful to consider;

* `datafusion_core` (`DataFusionError`, `DFSchema`, etc)
* `datafusion_datasource` (the built in parquet, avro, csv and json readers and supporting logic)

**Comment by andygrove** [comment]
This will be helpful for use cases where users are looking to use DataFusion in a similar fashion to Calcite, for query parsing and planning, but not for execution. I like this idea.

**Comment by houqp** [comment]
Thank you @Jimexist for taking on this! I think this is the right path forward.

cc @jorgecarleitao and @yjshen since they have proposed the similar ideas before.

**Comment by yahoNanJing** [comment]
Hi @Jimexist, is it possible to make a exclusive crate for the data source so that it will be easy for the integration of the different kinds of remote object store?

**Comment by yahoNanJing** [comment]
Thanks @Jimexist

**Comment by Jimexist** [comment]
my current plan is to finish items for:
- `datafusion-common`
- `datafusion-expr`

before release 7:
- #1587 

and finish the rest after the release, to cap the amount of changes in a release

**Comment by Igosuki** [comment]
@Jimexist could this lead to a smaller ballista client crate as well ? Potentially, this could greatly speed up compilation of programs who just want to be datafusion clients and not run the entire stack.

**Comment by Jimexist** [comment]
> Contributor

i'm not sure as of now - but probably if we split up logical/physical planning further - but that won't happen soon

**Comment by alamb** [comment]
Related comment: https://github.com/apache/arrow-datafusion/pull/1762#discussion_r802563462

**Comment by Jimexist** [comment]
i wanted to continue iterating on this split but obviously i didn't have time to keep up. a lot has happened in the last few months. i wonder if this is still relevant or it shall be closed now. @alamb and @andygrove any suggestions?

**Comment by alamb** [comment]
@Jimexist welcome back!

I would say that the main "break datafusion into smaller crates" has been completed. There are still some items in the description of this ticket that might not be done - I would personally recommend filing a new issue with any items that you think would still be good to work on and then closing this one.

**Comment by alamb** [comment]
Closing this ticket and we can track further splitting in follow on issues. Again 👏

**Comment by alamb** [comment]
I am thinking of trying to push us to the next level here https://github.com/apache/arrow-datafusion/issues/4181
