### ISSUE TITLE
split datafusion-physical-plan sub-module

### ISSUE THREAD

**Issue by Jimexist** [apache/arrow-datafusion#1754]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
My eventual plan is to have a dependency hierarchy like:

```
core --> (physical_plan) --> (datasource) --> (execution)    
```

I am trying to extract execution first, then I will extract datasource, and then physical plan

**Comment by alamb** [comment]
🤔  it seems like datasource may be the crate to extract next (and perhaps RuntimeEnv belongs there)

Specific items to do:
- [ ] move TaskContext into datafusion_execution
- [ ] remove SessionState references from physical_plan(most of them just need TaskContext)
- [ ] move object registries and table_factories off RuntimeEnv and into SessionState directly

**Comment by alamb** [comment]
Update 2023-03-27: 

I have moved `TaskContext` into `datafusion-execution` 🎉  and updated the list in https://github.com/apache/arrow-datafusion/issues/1754#issuecomment-1452438453

To move datasource into its own crate I need to do the following two non trivial API changes (added to the list above)
- [ ] remove SessionState reference from file_format (replace with TaskContext)
- [ ] remove SessionState reference from `TableProvider` (replace with `TaskContext`)

Here are the file_format uses (I don't think this will be major)

```
    async fn infer_stats(
        &self,
        _state: &SessionState,
        _store: &Arc<dyn ObjectStore>,
        _table_schema: SchemaRef,
        _object: &ObjectMeta,
    ) -> Result<Statistics> {
        Ok(Statistics::default())
    }
```


The `TableProvider` will be major I think:

```rust
    /// Create an ExecutionPlan that will scan the table.
    /// The table provider will be usually responsible of grouping
    /// the source data into partitions that can be efficiently
    /// parallelized or distributed.
    async fn scan(
        &self,
        state: &SessionState,
        projection: Option<&Vec<usize>>,
        filters: &[Expr],
        // limit can be used to reduce the amount scanned
        // from the datasource as a performance optimization.
        // If set, it contains the amount of rows needed by the `LogicalPlan`,
        // The datasource should return *at least* this number of rows if available.
        limit: Option<usize>,
    ) -> Result<Arc<dyn ExecutionPlan>>;
```

**Comment by alamb** [comment]
I am actively working on this  -- after a few tries my current plan is to to end up with this dependency diagram (aka datasource and listing table need to depend on physical_plan I think)

More PR to come

```
(core) --> (datasource) --> (physical_plan)
    \---------(physical_optimizer) --/
```

**Comment by alamb** [comment]
I tried extracting physical_plan again after https://github.com/apache/arrow-datafusion/pull/6516 and here is the list of things I needed to do (which can be done as smaller PRs):

- [ ] Move physical planner out of physical_plan and into datafusion/core/src/physical_planner
- [ ] Move`StringifiedPlan, ToStringifiedPlan, PlanType` out of logical_plan and into datafusion_common and update uses from `crate::logical_expr::JoinType`
- [ ] Move JoinType out of logical_plan and into `datafusion_common` (break dependence on logical plan)
- [ ] Update uses of `crate::error` to  `datafusion_common` (e.g. `use crate::error::{DataFusionError, Result};` to `use datafusion_common::{DataFusionError, Result};`) 
- [ ] Move `StreamingTableExec` into datasource as well (get datasource out of physical plan)
- [ ] Update `use crate::scalar::ScalarValue` --> `datafusion_common::ScalarValue`


Also I need to figure out how to remove all uses of  `SessionContext` in tests  (maybe by moving tests to sql integration), but that in theory could come as a follow on PR
