### ISSUE TITLE
split datafusion-logical-plan sub-module

### ISSUE THREAD

**Issue by Jimexist** [apache/arrow-datafusion#1755]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
I believe this is done https://github.com/apache/arrow-datafusion/tree/master/datafusion/expr/src/logical_plan -- though maybe the intent was to move all of logical_plan into its own crate? 

I am thinking extracting the physical plan from core will be the biggest bang for the buck
