### ISSUE TITLE
Benchmarks should optionally write timings and environment details to a JSON file

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#1757]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
I am working on some benchmark automation. I would like to have the benchmarks optionally produce a JSON file containing:

- Current date and time
- DatraFusion version
- The parameters passed to the benchmark
- Timings for each run of the query or queries
- Summary of results (row counts, hashes?)

Stretch goals would be to include the following, but this could be handled in separate issues later.

- Git branch name and hash of latest commit, and whether any local files have been modified
- Information about the host (operating system version, number of cores, mem etc)
- Rust version

**Describe the solution you'd like**
As described above.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by houqp** [comment]
Perhaps also hardware info?

**Comment by Dandandan** [comment]
Also compile time features in use would be interesting (LTO, SIMD,  memory allocator, etc.)

**Comment by andygrove** [comment]
> Perhaps also hardware info?

I added the number of CPU cores but it would be good to add operating system and architecture info. Do you happen to know of any good crates that provide this? I have not researched this yet.
