### ISSUE TITLE
Parquet reader thread errors do not make query fail

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#1767]
**Describe the bug**
The Parquet reader thread can terminate due to errors but it does not make the query fail. It just uses `println!` to print the error.

```
Parquet reader thread terminated due to error: Execution("Failed to map column projection for field l_orderkey. Incompatible data types Int32 and Int64") for files: [PartitionedFile { file_meta: FileMeta { sized_file: SizedFile { path: "/mnt/data/tpch/sf100-parquet//lineitem/part-13.parquet", size: 1165760107 }, last_modified: Some(2022-02-05T18:23:00.416225870Z) }, partition_values: [] }]
Query 3 iteration 1 took 5452.6 ms and returned 0 rows
```

**To Reproduce**
Run one of the unsupported tpch queries or run against invalid parquet files.

**Expected behavior**
Query should fail.

**Additional context**
None

**Comment by alamb** [comment]
I think this comes from https://github.com/apache/arrow-datafusion/blob/master/datafusion/src/physical_plan/file_format/parquet.rs#L230

We can probably adapt a similar approach as taken in `RepartitionExec` https://github.com/apache/arrow-datafusion/blob/master/datafusion/src/physical_plan/repartition.rs#L412-L449 with an extra task that handles a panic (join handle returning null) and sends a `Error` as @andygrove  suggests

**Comment by alamb** [comment]
I'll take a stab at this 

Also, as noted by @Dandandan  / @andygrove  in the slack channel, the #1617  may make this redundant anyways
