### ISSUE TITLE
split datafusion-datasource module

### ISSUE THREAD

**Issue by Jimexist** [apache/arrow-datafusion#1772]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yahoNanJing** [comment]
Hi @Jimexist, any progress on this? If you have started, maybe I can handle this.

**Comment by Jimexist** [comment]
> Hi @Jimexist, any progress on this? If you have started, maybe I can handle this.

Please go ahead - been busy recently
