### ISSUE TITLE
Consider using GitHub pages for DataFusion/Ballista documentation

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#18]
ASF supports enabling GitHub pages via asf.yaml [1] and we could consider using this to publish end user documentation for DataFusion and Ballista.

Ballista already has a minimal user guide in mdbook format that is part of this repo [2] and is currently published to https://ballistacompute.org/docs/ but it would be better to publish it here as part of the DataFusion user guide?

[1] https://cwiki.apache.org/confluence/display/INFRA/git+-+.asf.yaml+features
[2] https://github.com/apache/arrow-datafusion/tree/master/ballista/docs/user-guide

**Comment by returnString** [comment]
I was toying with the idea of an mdbook-style user guide for DataFusion recently - a unified setup for DF and Ballista would be excellent :)

**Comment by andygrove** [comment]
I created a new issue [1] and corresponding PR to create a unified mdbook setup for the user guide for DataFusion and Ballista.

I did this as a separate issue because writing the user guide is a separate concern from how and where we will publish it at release time.

[1] https://github.com/apache/arrow-datafusion/issues/19

**Comment by andygrove** [comment]
We should also have the ability to publish release notes and general blog posts on GitHub pages.

**Comment by andygrove** [comment]
I started looking into this. I propose that we create a `gh-pages` branch that will host the website (jekyll-based site with blog). As part of the release process, we can publish the mdbook content here.

**Comment by andygrove** [comment]
I've written up a proposal: https://docs.google.com/document/d/1oIb4QJMzFmA0bqaP42YQWgmnPiHqOTYzwmukANV5O-U/edit?usp=sharing

**Comment by andygrove** [comment]
I am closing this based on the feedback in the discussion at https://lists.apache.org/thread.html/r0ed76cc60cdf651e8cf5c82a21cc64114c1f6d174dc5487434bd32ef%40%3Cdev.arrow.apache.org%3E

**Comment by houqp** [comment]
@andygrove so the new plan is to host the datafusion website under `arrow.apache.org/datafusion` right? Are you actively working on this?

**Comment by andygrove** [comment]
Yes, I believe that is the plan now. I am not actively working on it.
