### ISSUE TITLE
Cannot install ballista-scheduler

### ISSUE THREAD

**Issue by selvavm** [apache/arrow-datafusion#1809]
**Describe the bug**
Getting error when installing `ballista-scheduler`

**To Reproduce**
Run `cargo install ballista-scheduler`

**Expected behavior**
Install successfully

**Additional context**
```
error[E0599]: no function or associated item named `from_str_unchecked` found for struct `proc_macro2::Literal` in the current scope
   --> C:\Users\selva\.cargo\registry\src\github.com-1ecc6299db9ec823\quote-1.0.11\src\runtime.rs:301:41
    |
301 |         let literal = unsafe { Literal::from_str_unchecked(repr) };
    |                                         ^^^^^^^^^^^^^^^^^^ function or associated item not found in `proc_macro2::Literal`

error[E0599]: no function or associated item named `from_str_unchecked` found for struct `proc_macro2::Literal` in the current scope
   --> C:\Users\selva\.cargo\registry\src\github.com-1ecc6299db9ec823\quote-1.0.11\src\runtime.rs:310:45
    |
310 |         let mut literal = unsafe { Literal::from_str_unchecked(repr) };
    |                                             ^^^^^^^^^^^^^^^^^^ function or associated item not found in `proc_macro2::Literal`

   Compiling twoway v0.1.8
For more information about this error, try `rustc --explain E0599`.

**Comment by alamb** [comment]
Thanks for the bug @selvavm 

This looks very similar to https://github.com/dtolnay/quote/issues/204 (there is a workaround listed on that ticket)

**Comment by selvavm** [comment]
@alamb thanks for the response. From the issue you mentioned, it looks like I will have to hardcode the quote version in `ballista/rust/core/cargo.toml`. Is this the workaround you meant?

if yes, I am not sure how I can do a `cargo install`

**Comment by houqp** [comment]
If we check in a lock file for ballista scheduler and other binary crates, then we can use `cargo install --locked` to install with all dependencies pinned to a specific version.
