### ISSUE TITLE
 Crash on parsing sql query with Cyrillic letters

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#184]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-11731

Hello,

I'm using DataFusion to query data from my csv file. The file contains columns with Cyrillic letters and when I write query like this one, I get a crash.

Code sample:
{code}
let mut ctx = ExecutionContext::new();
let csv_file = CsvFile::try_new(args.input.as_path().to_str().unwrap(), CsvReadOptions::new())?;
ctx.register_table("transactions", Arc::new(csv_file));
let df = ctx.sql("SELECT \"ДАТА\" FROM transactions")?;
let results = df.collect().await?;
log::info!("result: {:?}", results);
{code}

Stack trace: [^StackTrace.txt]

**Comment by Jefffrey** [comment]
Fixed by https://github.com/apache/arrow-datafusion/commit/5c5a0bb0af8130069071c193ca8c214022666a4e

**Comment by Dandandan** [comment]
Thanks @Jefffrey
