### ISSUE TITLE
Add a DataFusion example capable of retrieving data from a custom datasource

### ISSUE THREAD

**Issue by PierreZ** [apache/arrow-datafusion#1864]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

I'm currently playing with DataFusion to see if we can use it as a query execution runtime over a custom datasource. I could not find some documentation and/or examples on which traits should I be implemented in order to query data from a custom datasource.

**Describe the solution you'd like**

An example of a structure implementing the right Traits to fetch data over a custom datasource.

**Describe alternatives you've considered**

I really like the DataFrame Trait in the [dataframe.rs example](https://github.com/apache/arrow-datafusion/blob/master/datafusion-examples/examples/dataframe.rs), but I was wondering if I can implement "lower" Traits.

The other possible example I found is the test in [datafusion-streams](https://github.com/datafusion-contrib/datafusion-streams/blob/main/tests/basic_tests.rs), which implements `ExecutionPlan`, `TableProvider`, `ExecutionPlan` and others.

**Additional context**

I was thinking about simulating a Redis-like examples with two maps:

* one holding some data, with an integer as a key and a json as a value.
* the other map will simulate an index on one of the json field.

The example will generate a query that will use the index to retrieve the data. What do you think?

Which Traits should I be implemented in the example?

I would be happy to contribute the example :smile:

**Comment by houqp** [comment]
@PierreZ https://github.com/delta-io/delta-rs/blob/2fa81c611e74235c13e5d27813d2e9d815d10ad9/rust/src/delta_datafusion.rs#L218 is an example of how to implement a custom datasource for datafusion through the `TableProvider` trait. This is the most efficient and recommended way.

There is also a less involved hack, which is to read the data from your custom source into in memory Arrow record batches, then wrap them with a `MemTable`, here is an example of how I implemented a datasource for google spreadsheet using this approach: https://github.com/roapi/roapi/blob/cd271c65ac0769e41974f4c1cfe8499ab8e59bed/columnq/src/table/google_spreadsheets.rs#L300.

**Comment by houqp** [comment]
@GavinRay97 here is an example of how you can translate graphql queries into datafusion logical plans and execute these plana on any datasource that's supported by datafusion: https://github.com/roapi/roapi/blob/cd271c65ac0769e41974f4c1cfe8499ab8e59bed/columnq/src/query/graphql.rs#L183.

**Comment by GavinRay97** [comment]
@houqp Wow, thank you so much!

**Comment by PierreZ** [comment]
Thanks a lot @houqp! That will help me a lot :smile: 

Are you still interested for the example?

**Comment by houqp** [comment]
Yes, I think it would be helpful to have a simplistic example in our user doc :) At the very minimal, we could point to our memtable implementation if coming up with a simple example takes too much work.

**Comment by GavinRay97** [comment]
I had a read through the source of the `TableProvider` trait here:
https://github.com/apache/arrow-datafusion/blob/0b1bef123acc5f46f225950d13f296104a543727/datafusion/src/datasource/datasource.rs#L58-L96

Maybe a dumb question -- but I see that `project()` and `filter()` are part of the interface, but not `join()` or similar.
In relational algebra, is a join considered a specialized `project`, or how would you implement that with the `TableProvider` trait?

**Comment by houqp** [comment]
join is an operator that operates on two tables, but the table provider trait is an abstraction for a single table source, that's why it doesn't make sense to push down join into the scan method. join push down need to be implemented at a higher level, for example, as a custom extension plan node: https://github.com/apache/arrow-datafusion/blob/0b1bef123acc5f46f225950d13f296104a543727/datafusion/src/logical_plan/plan.rs#L362

**Comment by PierreZ** [comment]
> Yes, I think it would be helpful to have a simplistic example in our user doc :) At the very minimal, we could point to our memtable implementation if coming up with a simple example takes too much work.

I should be able to make two examples:

* one with a dummy implementation of `TableProvider`,
* The other with `MemTable`

I'm not sure if I will do the example with the index, as i have no idea on how to do this, but those two above should be easy enough :smile:

**Comment by houqp** [comment]
that sounds good to me, thanks a lot for the help @PierreZ :+1:

**Comment by PierreZ** [comment]
I just made [some examples](https://github.com/PierreZ/arrow-datafusion/commit/cf5aace1bcb5316dc3e49a8199bdcec61f2872cc), but I'm pretty sure we could improve them. Should I just open the PR for review? 

I didn't implement my manual-index lookup I was refering at the beginning of the issue because:

* It looks rather complex for an example,
* I have no idea on how to represent it.

Not sure I'm right, but a manual lookup in an index to fetch rows should:

* Create a Logical Plan composed of several TableScan somehow,
* Implements `children` correctly in the `ExecutionPlan` trait.
* Use the data from the children to make the table scan.

I did not find an example with a children, maybe it will be worth it to add another example.

What do you think @houqp?

**Comment by PierreZ** [comment]
Hey thanks @jychen7 :+1: Nice datasource BTW.

I will open the PR :rocket:
