### ISSUE TITLE
Add a script for running full db-benchmark suite

### ISSUE THREAD

**Issue by matthewmturner** [apache/arrow-datafusion#1870]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)
I've been working on db-benchmark and think it would be valuable to automate the full process so others could run the benchmarks as well

**Describe the solution you'd like**
A new shell script in `benchmarks/db-benchmark` that runs the full db-benchmark process

**Describe alternatives you've considered**

**Additional context**

**Comment by matthewmturner** [comment]
Given that db-benchmark uses R scripts to download the source data im wondering if i should assume that the user will take care of that or if i should wrap this all up in a docker container.

@houqp do you have a preference?

**Comment by matthewmturner** [comment]
@Dandandan also interested in your view on this

**Comment by matthewmturner** [comment]
i just keep forgetting people.

@realno i know you had expressed interest in benchmarking in the past as well so im curious if you have a preference on the above.

@alamb i know youre busy - so no rush - but you had initially raised #147 so interested in your view as well.

**Comment by realno** [comment]
@matthewmturner I like the idea using docker, it should be easier for dependency management.

**Comment by houqp** [comment]
agree with @realno , thanks @matthewmturner for taking care of this :)

**Comment by matthewmturner** [comment]
I hope it makes it easier to play with optimizations!
