### ISSUE TITLE
`cargo clippy` fails on the `master` branch

### ISSUE THREAD

**Issue by HaoYang670** [apache/arrow-datafusion#1880]
**Describe the bug**
After update `rustup` to the latest version `rustc 1.59.0`, running `cargo clippy` on master branch fails.

**To Reproduce**
1. update rustup to the latest version ` rustc 1.59.0`
2. run `cargo clippy --all-targets --workspace -- -D warnings` on `master` branch
3. build failed

**Expected behavior**
No error.

**Additional context**
Found the bug from #1878 
Same error in arrow-rs: https://github.com/apache/arrow-rs/issues/1362

**Comment by HaoYang670** [comment]
@houqp

**Comment by houqp** [comment]
This happens on almost every rust release :D @HaoYang670 please feel free to send a PR to fix those warnings.
