### ISSUE TITLE
Update `rust-version` to 1.59

### ISSUE THREAD

**Issue by HaoYang670** [apache/arrow-datafusion#1902]
**Describe the solution you'd like**
update `rust-version` from 1.58 to 1.59.

**Additional context**
https://blog.rust-lang.org/2022/02/24/Rust-1.59.0.html

**Comment by NaincyKumariKnoldus** [comment]
hey @HaoYang670 can i do this?

**Comment by HaoYang670** [comment]
> hey @HaoYang670 can i do this?

Sure, go ahead!
