### ISSUE TITLE
 TPC-H Query 6 has a wrong result

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#192]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-12218

TPC-H Query 6 gives a wrong result according to the test in the benchmarks.

{{TPCH_DATA=[..]/tpch-dbgen cargo test --release}}
Query 6 iteration 0 took 6137.1 ms
Query 6 avg time: 6137.09 ms
thread 'tests::q6' panicked at 'assertion failed: `(left == right)`
 left: `["123141078.23"]`,
 right: `["75207768.18550001"]`', benchmarks/src/bin/tpch.rs:1684:17

[~alamb]

**Comment by alamb** [comment]
🤔  maybe we need to use `Decimal` type rather than `Float` for such constants. When we initially ran TPCH we did not have support for this data type, but now thanks to the work from @liukun4515 (and others) we do!

**Comment by kmitchener** [comment]
> 🤔 maybe we need to use `Decimal` type rather than `Float` for constants. When we initially ran TPCH we did not have support for this data type, but now thanks to the work from @liukun4515 (and others) we do!

That would probably do it. Postgres also converts decimal literals in the sql statement to decimal types. https://stackoverflow.com/questions/68142210/what-is-the-type-of-100-0-in-postgresql 

I see where to make the change (parse_sql_number() inside planner.rs), but I'm struggling trying to figure out how to turn the string input to a Decimal128 type. Can you give me some pointers?

**Comment by kmitchener** [comment]
Hm, I realize now I should be converting from float to Decimal128 :)
