### ISSUE TITLE
Unnecessary Arc::clone per row in RowWriter benchmark

### ISSUE THREAD

**Issue by jhorstmann** [apache/arrow-datafusion#1973]
**Describe the bug**

The `jit` benchmark calls `batch.schema()` for each row, internally the `schema` method clones an `Arc`. Normally cloning an `Arc` is not a problem, but doing it for every row adds some overhead.

**To Reproduce**

Running the benchmark under a profiler like `perf` and then checking the hotspots shows some atomic instructions on the hot path

```
perf record cargo bench --features row,jit --bench jit
```

**Comment by yjshen** [comment]
Thanks @jhorstmann 👍
