### ISSUE TITLE
[Ballista] datafusion-cli  with ballista not support show tables and show columns 

### ISSUE THREAD

**Issue by Ted-Jiang** [apache/arrow-datafusion#1984]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
datafusion-cli  with ballista not support show tables and show columns 
```
RUST_LOG=INFO cargo run  --bin datafusion-cli --features=ballista  -- --host localhost --port 50050

create external table table1 stored as PARQUET location "/Users/yangjiang/ebay/kylin-native/examples/test_case_data/xxxx";
0 rows in set. Query took 0.006 seconds.

❯ \d table1;  🤔 Invalid statement: sql parser error: Expected an SQL statement, found: \
^C
❯ show tables;
Plan("SHOW TABLES is not supported unless information_schema is enabled")
❯


```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by liukun4515** [comment]
Have you tried to enable the `information_schema` from the error message "Plan("SHOW TABLES is not supported unless information_schema is enabled")"
@Ted-Jiang

**Comment by liukun4515** [comment]
Maybe I can help you to check this issue if I'm free on the weekend.

**Comment by gaojun2048** [comment]
In this pr: https://github.com/apache/arrow-datafusion/pull/1593 I added `show tables` and `show columns` in ballista context.  I think we can add a param named `with_information_schema` which type is `bool`. 
I can finish it in these days.
