### ISSUE TITLE
[Ballista] support datafusion built_in  UDAF work in ballista cluster

### ISSUE THREAD

**Issue by Ted-Jiang** [apache/arrow-datafusion#1985]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
support datafusion built_in  UDAF work in ballista cluster, It will make ballista more like a high-performance OLAP system for
production.

```
❯ select APPROX_DISTINCT(14) from table1;
[2022-03-11T03:27:22Z INFO  ballista_core::execution_plans::distributed_query] Connecting to Ballista scheduler at http://localhost:50050
Execution("Status { code: Internal, message: \"Job Gs7JJH3 failed due to General error: 
Could not save stage plan: Not implemented: Aggregate function not supported: ApproxDistinct { name: \\\"APPROXDISTINCT(Int64(14))\\\", input_data_type: Int64, expr: Literal { value: Int64(14) } }\",
 metadata: MetadataMap { headers: {\"content-type\": \"application/grpc\", \"date\": \"Fri, 11 Mar 2022 03:27:22 GMT\"} }, source: None }")
❯
```
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Ted-Jiang** [comment]
work  in client without ballista
```
select APPROX_DISTINCT("14") from table1;
+---------------------------+
| APPROXDISTINCT(table1.14) |
+---------------------------+
| 55                        |
+---------------------------+
1 row in set. Query took 0.015 seconds.
```

**Comment by jiangzhx** [comment]
FYI，It seems to be the same problem
https://github.com/apache/arrow-datafusion/pull/1881

**Comment by Ted-Jiang** [comment]
> FYI，It seems to be the same problem #1881

IMO, this PR not work for built in UDAF.

**Comment by Ted-Jiang** [comment]
@houqp  plz assign this to me. We need this in our situation.

**Comment by liukun4515** [comment]
I think many functions are missed in the ballista but implemented in the datafusion.
@Ted-Jiang 
You can give a plan to find them and fix them through the community.

**Comment by liukun4515** [comment]
@Ted-Jiang 
Do you mean the same thing with this issue https://github.com/apache/arrow-datafusion/issues/1988？
We should make it clear we just have two type functions, one is the built-in function and the other is UDF/UDAF.
You can refer to https://spark.apache.org/docs/latest/sql-ref-functions.html and get some knowledge about that.
https://github.com/apache/arrow-datafusion/pull/1881 is just wanting to resolve the issue of adding a new UDF/UDAF.
