### ISSUE TITLE
 Add support for AVG(Timestamp) types

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#200]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-12318

This is a follow on to ARROW-12277

Background: Support for Min/Max/Sum/Count were added for DataType::Timestamp(*) types in https://github.com/apache/arrow/pull/9970.

This ticket tracks adding support for Avg, which is slightly more involved as currently Avg assumes the output type is always F64, and in this case I think Avg(timestamp) should also be (timestamp). We should double check what postgres does in this case and follow its example

**Comment by alamb** [comment]
Comment from Andrew Lamb(alamb) @ 2021-04-11T09:48:09.161+0000:
<pre>[~Dandandan] notes that PostgreSQL doesn't support SUM or AVG for timestamps: https://www.postgresql.org/docs/13/functions-aggregate.html


so perhaps we should not support it in DataFusion either :thinking_face:</pre>

**Comment by waitingkuo** [comment]
@alamb 

Postgresql has `AVG` and `SUM` for `time` but not `timestamps`

Should we close this and submit another ticket for `AVG(Time)` and `SUM(Time)`?

**Comment by alamb** [comment]
@waitingkuo  -- I think that sounds like a good idea. I will do so.

**Comment by waitingkuo** [comment]
@alamb i just tested postgrseql, looks like SUM and AVG cast Time to Interval and then SUM / AVG them

```bash
willy=# select pg_typeof(SUM(time '00:00:00')),  pg_typeof(AVg(time '00:00:00'));
 pg_typeof | pg_typeof 
-----------+-----------
 interval  | interval
(1 row)
```

this make sense otherwise SUM(Time) is just quite strange

**Comment by alamb** [comment]
https://github.com/apache/arrow-datafusion/issues/3166 👍
