### ISSUE TITLE
Cannot run examples of ballista

### ISSUE THREAD

**Issue by doki23** [apache/arrow-datafusion#2014]
**Describe the bug**
When I try to run ballista-examples/src/bin/ballista-sql.rs, I got an error: 

> thread 'main' panicked at 'failed to get arrow data dir: env `ARROW_TEST_DATA` is undefined or has empty value, and the pre-defined data dir `/Users/doki/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow-10.0.0/../testing/data` not found

I find test data dir in df unit tests is:

>  datafusion::test_util::arrow_test_data()

in the example it's

> datafusion::arrow::util::test_util::arrow_test_data()

**Comment by xudong963** [comment]
Have you ever run `export ARROW_TEST_DATA=$(pwd)/testing/data/`? 
https://github.com/apache/arrow-datafusion/blob/master/CONTRIBUTING.md#bootstrap-environment

**Comment by doki23** [comment]
Setting the env var solves it surely, but why not use datafusion::arrow::util::test_util::arrow_test_data() directly?

**Comment by doki23** [comment]
I'd like to replace with `datafusion::test_util::arrow_test_data()` so that we can run it without setting the env var. 
@xudong963 How do you think?

**Comment by xudong963** [comment]
> I'd like to replace it with `datafusion::test_util::arrow_test_data()` so that we can run it without setting the env var. @xudong963 How do you think?

+1. I got your idea. Look forward to seeing your ticket! Thanks @doki23
