### ISSUE TITLE
Change the DataFusion explain plans to make it clearer that the predicate / filter in the scan may be inexact / partially applied

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#2021]
I wonder if we could/should change the DataFusion explain plans to make it clearer that the predicate / filter in the scan may be inexact / partially applied

In other words, if `TableProvider:: supports_filter_pushdown` returns `TableProviderFilterPushDown::Inexact`

https://github.com/apache/arrow-datafusion/blob/d31c1579fdc2ad060bc46c4fcfef14cc7676da6b/datafusion/src/datasource/datasource.rs#L116-L123

https://github.com/apache/arrow-datafusion/blob/d31c1579fdc2ad060bc46c4fcfef14cc7676da6b/datafusion/src/datasource/datasource.rs#L54-L67

_Originally posted by @alamb in https://github.com/apache/arrow-datafusion/issues/2015#issuecomment-1068820110_

**Comment by alamb** [comment]
@Ted-Jiang  has offered to help with this

I suggested it because it has been asked several other times and I think is somewhat confusing

**Comment by liukun4515** [comment]
> table_scan

which part of the field added in the `TableScan`,  can you point out them?

@Ted-Jiang

**Comment by liukun4515** [comment]
Maybe we can add some tag in the `filterexpr` and the tag can point out whether it is pushed down or not.
In the explain we can print the information for this.
I think it's not a good way to add useless filed in the `TableScan`

**Comment by alamb** [comment]
Maybe we can create two `Vec<expr>` lists on the TableScan like `exact_filters` and `inexact_filters` to make the filtering expectations very clear

That would lead to an explain like:

```
--------------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                                                                                                                               |
+---------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| logical_plan  | Projection: #test.request                                                                                                                                                                          |
|               |   Filter: #test.request = Utf8("foo")                                                                                                                                                              |
|               |     TableScan: ... inexact_filters=[#test.request = Utf8("foo")]  exact_filters=[#test.request = Utf8("bar")]                                                                  
```

Maybe terms like `partial_filters` and `full_filters` would be better? 🤔

**Comment by jackwener** [comment]
I think it's a better way.😃
