### ISSUE TITLE
 Implement date_trunc() function

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#203]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-12391

Implement the date_trunc function, as described in this PostGres manual:

[https://www.postgresql.org/docs/current/functions-datetime.html#FUNCTIONS-DATETIME-TRUNC]

 

This would allow for the following use cases to be solved:
 * casting of timestamps to other resolutions, such as millis and micros
 * rounding dates/timestamps 

It also allows the user to explicitly allow the truncation of timestamp precision.

**Comment by jwdeitch** [comment]
Looks like this was implemented in e5d147178ed64bb4b60a1b7fbf5ee6ad209a7368

datafusion/src/physical_plan/datetime_expressions.rs:311

:)

**Comment by jorgecarleitao** [comment]
Agreed :)

**Comment by alamb** [comment]
Thanks @jwdeitch !
