### ISSUE TITLE
UnionAll support for Ballista

### ISSUE THREAD

**Issue by yjshen** [apache/arrow-datafusion#2032]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Currently, UnionAll is only available in DataFusion core, it would be nice to also add this to Ballista.

**Comment by liukun4515** [comment]
There are some gaps between datafusion and ballista like https://github.com/apache/arrow-datafusion/issues/1985 and https://github.com/apache/arrow-datafusion/issues/1984

**Comment by yjshen** [comment]
@liukun4515 Do we have an umbrella ticket to track all these gaps?

**Comment by Ted-Jiang** [comment]
i will take this😊
