### ISSUE TITLE
support `explain raw plan` & `explain optimized plan`

### ISSUE THREAD

**Issue by xudong963** [apache/arrow-datafusion#2035]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
During reviewing PRs, I found `Explain raw plan` will be useful. (`raw plan` means the plan doesn't optimize).

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Materialize has the feature: https://materialize.com/docs/sql/explain/
Here is an example:
```
materialize=> EXPLAIN RAW PLAN FOR select * from posts where content = '1' and id = 1;
              Raw Plan
-------------------------------------
 %0 =                               +
 | Get materialize.public.posts (u1)+
 | Filter ((#2 = "1") && (#0 = 1))  +

(1 row)
```

**Comment by yjshen** [comment]
`explain verbose ...` provide these functionalities already? from raw logical plan to each optimization step results and the final physical plan?

**Comment by xudong963** [comment]
Thanks @yjshen
