### ISSUE TITLE
Do some pre-check when building LogicalPlan

### ISSUE THREAD

**Issue by doki23** [apache/arrow-datafusion#2041]
<s>Actually, it's not a functionality bug. It's my confusion about the unit test: **logical_plan::builder::tests::plan_using_join_wildcard_projection**

The following is some code in the test.
```
let plan = LogicalPlanBuilder::scan_empty(Some("t1"), &employee_schema(), None)?
            .join_using(&t2, JoinType::Inner, vec!["id"])?
            .project(vec![Expr::Wildcard])? // my question about here
            .build()?;
```

I find some error descriptions in other place of sql planner like:
```
Expr::Wildcard { .. } => Err(DataFusionError::Internal(
            "Wildcard expressions are not valid in a logical query plan".to_owned(),
        ))
```

And in the sql planner, we always expand the wildcard before generating a logical plan.
So the unit test may be wrong, please correct me if I am wrong.</s>

We should do some pre-check for building LogicalPlan to expose errors earlier.
For example, `SELECT id, first_name, last_name FROM person WHERE NOT id`

**Comment by doki23** [comment]
It's related to another pr: #2012

**Comment by alamb** [comment]
FWIW I would expect this code:

```rust
let plan = LogicalPlanBuilder::scan_empty(Some("t1"), &employee_schema(), None)?
            .join_using(&t2, JoinType::Inner, vec!["id"])?
            .project(vec![Expr::Wildcard])? // my question about here
            .build()?;
```

To generate a DataFusionError with "Wildcard expressions are not valid in a logical query plan"

**Comment by doki23** [comment]
As discussed in #2012 , it's necessary to support wildcard in dataframe api. So there's no problem in the code quoted by the issue. I'm going to change this issue to an enhancement that we should do some pre-check for building LogicalPlan.
