### ISSUE TITLE
zstd-sys error

### ISSUE THREAD

**Issue by MrBigtool** [apache/arrow-datafusion#2042]
Hi, I am new in rust but I want to do an experiment with this library in a web assembly project.

Just I am adding the lib: 

`[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.67"
datafusion = "7.0.0"
tokio = "1.17.0"
getrandom = { version = "0.2.5", features = ["js"] }`

And it is causing the error:

`error: failed to run custom build command for 'zstd-sys v1.6.3+zstd.1.5.2'`

I dont understand if I need to install ZSTD additionally in my mac to use this library.

**Comment by Igosuki** [comment]
You need zstd bindings for the target runtime, https://github.com/gyscos/zstd-rs/wiki/Compile-for-WASM

**Comment by alamb** [comment]
> I dont understand if I need to install ZSTD additionally in my mac to use this library.

This may be related to dependencies brought in by parquet

**Comment by alamb** [comment]
I think this is complete now (the parquet support is optional and we are tracking remaining items in https://github.com/apache/arrow-datafusion/issues/7651)
