### ISSUE TITLE
How to build a field of type Struct with DataFusion SQL?

### ISSUE THREAD

**Issue by lquerel** [apache/arrow-datafusion#2043]
DataFusion already gives us a way to access nested fields with this syntax field["nested_field"] (field being an arrow struct field). However I didn't find any example or documentation to do the reverse operation, i.e. creating a struct from multiple fields. A pseudo SQL query (inspired from BIGQUERY) will be something like: `SELECT STRUCT(a AS field_1, b AS field_2) AS struct_name FROM table`. Is there a way to express this type of construct with DataFusion SQL?

Support for this type of functionality will be particularly helpful for dealing with data sources that support nested fields (e.g. parquet and JSON) and when the query output MUST also be stored in a nested form. Example of use cases:
- Remove privacy sensitive fields from a struct field.
- Apply some transformations on some nested fields.
- Compute new nested fields based on the existing nested fields (e.g. add country, city nested fields from an ip_address nested field).  

Proposed solution:
- Add a new operator to create a field of type Struct. Simple syntax: `STRUCT (expr AS field_name, ...) AS struct_field_name`
- Support an EXCEPT keyword to remove one or several fields from a struct. e.g. `SELECT STRUCT (struct_a.* EXCEPT (field_1, field_2)) FROM xyz`. This type of syntax is robust to schema evolution as new fields will be automatically captured by the wildcard operator.
- Support wildcard operators to combine multiple structs into a single one. e.g. `SELECT STRUCT(struct_a.*, struct_b.*) AS combined_struct FROM xyz`. This must fail if the structures a and b have fields with the same name.

**Comment by matthewmturner** [comment]
Hello - thanks for raising this, im quite interested in operations on structs as well.  Do you have any examples of how other engines such as spark / postgres / athena etc handle what you are proposing?

**Comment by alamb** [comment]
BTW I started collecting known issues in  struct support in https://github.com/apache/arrow-datafusion/issues/2326

**Comment by Ted-Jiang** [comment]
@lquerel Are you taking this feature? If not i am glad to take this.❤️

**Comment by lquerel** [comment]
@Ted-Jiang No unfortunately I can't right now. Thanks in advance.

**Comment by lquerel** [comment]
@Ted-Jiang thanks for your PR. Really nice to see that integrated so quickly. 

Does this PR allow to create nested structs ?

**Comment by Ted-Jiang** [comment]
> @Ted-Jiang thanks for your PR. Really nice to see that integrated so quickly.
> 
> Does this PR allow to create nested structs ?

Sorry for the delay, No we can't create a nested, I think we should modify it in `sql-parser` for support this.

**Comment by chitralverma** [comment]
@Ted-Jiang based on https://github.com/apache/arrow-datafusion/pull/2389 and [this](https://arrow.apache.org/datafusion/user-guide/sql/scalar_functions.html#struct) I was wondering what all is possible to create struct columns in datafusion SQL.

for example I was trying to do something like the below but its broke,
``` 
select struct(a,b,c) from table

Failed to execute query: Arrow error: Invalid argument error: column types must match schema types, expected Struct([]) but found Struct([Field { name: \"c0\", data_type: Utf8, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: None }]) at column index 0"
```

**Comment by alamb** [comment]
I believe this was fixed by https://github.com/apache/arrow-datafusion/pull/6594 (thanks to @jiangzhx)

**Comment by alamb** [comment]
Doc reference: https://datafusion.apache.org/user-guide/sql/scalar_functions.html#struct-functions
