### ISSUE TITLE
[Ballista] Fill functional gaps between datafusion and ballista 

### ISSUE THREAD

**Issue by Ted-Jiang** [apache/arrow-datafusion#2062]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Current Ballista implementation is more like standalone system that  able to run the Datafusion operators in a distributed way. 
But threr are some gaps between them.

Currently we need fix:

- [x] https://github.com/apache/arrow-datafusion/issues/2032
- [x] https://github.com/apache/arrow-datafusion/issues/1984
- [x] https://github.com/apache/arrow-datafusion/issues/2007
- [x] https://github.com/apache/arrow-datafusion/issues/1985
- [x] https://github.com/apache/arrow-datafusion/issues/2092
- [x] #2096 
- [x] #2180 

Welcome to add missing part 😊! 

**Describe the solution you'd like**

**Describe alternatives you've considered**
Maybe we can find a solution to find functions that are missed in the ballista but implemented in the datafusion automatically.

**Comment by yjshen** [comment]
I've updated the list above with a `substr` item.
