### ISSUE TITLE
perhaps two different versions of crate `arrow` are being used?

### ISSUE THREAD

**Issue by zemelLeong** [apache/arrow-datafusion#2090]
I use [connectorx](https://github.com/sfu-db/connector-x) query data to datafusion got this error.
```markdown
mismatched types
expected reference `&Vec<datafusion::arrow::record_batch::RecordBatch>`
   found reference `&Vec<arrow::record_batch::RecordBatch>`
perhaps two different versions of crate `arrow` are being used?rustc[E0308](https://doc.rust-lang.org/error-index.html#E0308)
```
```rust
    debug!("loading database table data...");
    let mut destination = ArrowDestination::new();
    let source = MySQLSource::<BinaryProtocol>::new(t.get_uri_str(), 2).unwrap();
    let queries = &[format!("SELECT * FROM {}", t.name)];
    let dispatcher = Dispatcher::<
        MySQLSource<BinaryProtocol>,
        ArrowDestination,
        MySQLArrowTransport<BinaryProtocol>,
    >::new(source, &mut destination, queries, None);
    dispatcher.run().unwrap();
    let data: &Vec<RecordBatch> = &destination.arrow().unwrap();
```
![image](https://user-images.githubusercontent.com/26835087/160083299-f49f7a3c-0e6a-4622-8334-25a2030dab4d.png)

Is there any way to fix this?

**Comment by tustvold** [comment]
Could you maybe post the output of `cargo tree --duplicates` for your workspace. It is likely you have two crates depending on different versions of arrow in your source tree, and it is resulting in this error message as cargo will link in both versions. This will then cause an issue if you try to use a type from one arrow version with something expecting a type from the other version

**Comment by zemelLeong** [comment]
This is my `cargo tree --duplicates` result:
<details>
  <summary>cargo tree --duplicates result detials</summary>
  <pre>
    arrayvec v0.5.2
    └── lexical-core v0.7.6
        ├── arrow v5.5.0
        │   └── connectorx v0.2.3
        │       └── columnq v0.4.5 (H:\github-project\roapi\columnq)
        │           ├── columnq-cli v0.2.3 (H:\github-project\roapi\columnq-cli)
        │           └── roapi-http v0.6.0 (H:\github-project\roapi\roapi-http)
        └── lexical v5.2.2
            └── mysql_common v0.27.5
                └── mysql v21.0.2
                    └── r2d2_mysql v21.0.0
                        └── connectorx v0.2.3 (*)
    
    arrayvec v0.7.2
    ├── blake3 v1.3.1
    │   └── datafusion v7.0.0
    │       ├── columnq v0.4.5 (H:\github-project\roapi\columnq) (*)
    │       └── deltalake v0.4.1 (https://github.com/delta-io/delta-rs.git?rev=f5e4b5f94393b517d3d88c200d7169cce11b304b#f5e4b5f9)
    │           └── columnq v0.4.5 (H:\github-project\roapi\columnq) (*)
    └── rust_decimal v1.22.0
        ├── connectorx v0.2.3 (*)
        └── mysql_common v0.27.5 (*)
    
    arrow v5.5.0 (*)
    
    arrow v9.1.0
    ├── datafusion v7.0.0 (*)
    ├── datafusion-common v7.0.0
    │   ├── datafusion v7.0.0 (*)
    │   └── datafusion-expr v7.0.0
    │       └── datafusion v7.0.0 (*)
    ├── datafusion-expr v7.0.0 (*)
    ├── deltalake v0.4.1 (https://github.com/delta-io/delta-rs.git?rev=f5e4b5f94393b517d3d88c200d7169cce11b304b#f5e4b5f9) (*)
    └── parquet v9.1.0
        ├── datafusion v7.0.0 (*)
        ├── datafusion-common v7.0.0 (*)
        └── deltalake v0.4.1 (https://github.com/delta-io/delta-rs.git?rev=f5e4b5f94393b517d3d88c200d7169cce11b304b#f5e4b5f9) (*)
    
    block-buffer v0.9.0
    ├── md-5 v0.9.1
    │   └── rusoto_signature v0.47.0
    │       └── rusoto_core v0.47.0
    │           ├── columnq v0.4.5 (H:\github-project\roapi\columnq) (*)
    │           ├── rusoto_s3 v0.47.0
    │           │   └── columnq v0.4.5 (H:\github-project\roapi\columnq) (*)
    │           └── rusoto_sts v0.47.0
    │               └── columnq v0.4.5 (H:\github-project\roapi\columnq) (*)
    └── sha2 v0.9.9
        ├── mysql_common v0.27.5 (*)
        ├── rusoto_signature v0.46.0
        │   └── rusoto_core v0.46.0
        │       ├── deltalake v0.4.1 (https://github.com/delta-io/delta-rs.git?rev=f5e4b5f94393b517d3d88c200d7169cce11b304b#f5e4b5f9) (*)
        │       ├── dynamodb_lock v0.4.1 (https://github.com/delta-io/delta-rs.git?rev=f5e4b5f94393b517d3d88c200d7169cce11b304b#f5e4b5f9)
        │       │   └── deltalake v0.4.1 (https://github.com/delta-io/delta-rs.git?rev=f5e4b5f94393b517d3d88c200d7169cce11b304b#f5e4b5f9) (*)
        │       ├── rusoto_dynamodb v0.46.0
        │       │   ├── deltalake v0.4.1 (https://github.com/delta-io/delta-rs.git?rev=f5e4b5f94393b517d3d88c200d7169cce11b304b#f5e4b5f9) (*)
        │       │   └── dynamodb_lock v0.4.1 (https://github.com/delta-io/delta-rs.git?rev=f5e4b5f94393b517d3d88c200d7169cce11b304b#f5e4b5f9) (*)
        │       ├── rusoto_s3 v0.46.0
        │       │   └── deltalake v0.4.1 (https://github.com/delta-io/delta-rs.git?rev=f5e4b5f94393b517d3d88c200d7169cce11b304b#f5e4b5f9) (*)
        │       └── rusoto_sts v0.46.0
        │           └── deltalake v0.4.1 (https://github.com/delta-io/delta-rs.git?rev=f5e4b5f94393b517d3d88c200d7169cce11b304b#f5e4b5f9) (*)
        └── rusoto_signature v0.47.0 (*)
    
    block-buffer v0.10.2
    └── digest v0.10.3
        ├── blake2 v0.10.4
        │   └── datafusion v7.0.0 (*)
        ├── blake3 v1.3.1 (*)
        ├── hmac v0.12.1
        │   └── postgres-protocol v0.6.3
        │       ├── postgres-types v0.2.2
        │       │   └── tokio-postgres v0.7.5
        │       │       └── postgres v0.19.2
        │       │           └── rust_decimal v1.22.0 (*)
        │       └── tokio-postgres v0.7.5 (*)
        ├── md-5 v0.10.1
        │   ├── datafusion v7.0.0 (*)
        │   └── postgres-protocol v0.6.3 (*)
        └── sha2 v0.10.2
            ├── datafusion v7.0.0 (*)
            └── postgres-protocol v0.6.3 (*)
    
    clap v2.34.0
    └── bindgen v0.58.1
        [build-dependencies]
        └── mysql_common v0.27.5 (*)
    
    clap v3.1.6
    ├── columnq-cli v0.2.3 (H:\github-project\roapi\columnq-cli)
    └── roapi-http v0.6.0 (H:\github-project\roapi\roapi-http)
    
    crypto-mac v0.10.1
    └── hmac v0.10.1
        └── rusoto_signature v0.46.0 (*)
    
    crypto-mac v0.11.1
    └── hmac v0.11.0
        └── rusoto_signature v0.47.0 (*)
    
    digest v0.9.0
    ├── hmac v0.10.1 (*)
    ├── hmac v0.11.0 (*)
    ├── md-5 v0.9.1 (*)
    ├── rusoto_signature v0.47.0 (*)
    └── sha2 v0.9.9 (*)
    
    digest v0.10.3 (*)
    
    env_logger v0.8.4
    └── bindgen v0.58.1 (*)
    
    env_logger v0.9.0
    ├── columnq-cli v0.2.3 (H:\github-project\roapi\columnq-cli)
    └── roapi-http v0.6.0 (H:\github-project\roapi\roapi-http)
    
    hashbrown v0.11.2
    ├── hashlink v0.7.0
    │   └── rusqlite v0.25.4
    │       ├── connectorx v0.2.3 (*)
    │       └── r2d2_sqlite v0.18.0
    │           └── connectorx v0.2.3 (*)
    ├── indexmap v1.8.0
    │   ├── arrow v5.5.0 (*)
    │   ├── arrow v9.1.0 (*)
    │   ├── clap v3.1.6 (*)
    │   ├── h2 v0.3.12
    │   │   ├── hyper v0.14.17
    │   │   │   ├── axum v0.4.8
    │   │   │   │   └── roapi-http v0.6.0 (H:\github-project\roapi\roapi-http)
    │   │   │   ├── hyper-rustls v0.22.1
    │   │   │   │   ├── rusoto_core v0.46.0 (*)
    │   │   │   │   ├── rusoto_core v0.47.0 (*)
    │   │   │   │   └── yup-oauth2 v6.3.1
    │   │   │   │       └── columnq v0.4.5 (H:\github-project\roapi\columnq) (*)
    │   │   │   ├── hyper-rustls v0.23.0
    │   │   │   │   └── reqwest v0.11.10
    │   │   │   │       └── columnq v0.4.5 (H:\github-project\roapi\columnq) (*)
    │   │   │   │       [dev-dependencies]
    │   │   │   │       └── roapi-http v0.6.0 (H:\github-project\roapi\roapi-http)
    │   │   │   ├── reqwest v0.11.10 (*)
    │   │   │   ├── roapi-http v0.6.0 (H:\github-project\roapi\roapi-http)
    │   │   │   ├── rusoto_core v0.46.0 (*)
    │   │   │   ├── rusoto_core v0.47.0 (*)
    │   │   │   ├── rusoto_credential v0.46.0
    │   │   │   │   ├── deltalake v0.4.1 (https://github.com/delta-io/delta-rs.git?rev=f5e4b5f94393b517d3d88c200d7169cce11b304b#f5e4b5f9) (*)
    │   │   │   │   ├── rusoto_core v0.46.0 (*)
    │   │   │   │   └── rusoto_signature v0.46.0 (*)
    │   │   │   ├── rusoto_credential v0.47.0
    │   │   │   │   ├── columnq v0.4.5 (H:\github-project\roapi\columnq) (*)
    │   │   │   │   ├── rusoto_core v0.47.0 (*)
    │   │   │   │   └── rusoto_signature v0.47.0 (*)
    │   │   │   ├── rusoto_signature v0.46.0 (*)
    │   │   │   ├── rusoto_signature v0.47.0 (*)
    │   │   │   └── yup-oauth2 v6.3.1 (*)
    │   │   └── reqwest v0.11.10 (*)
    │   ├── serde_json v1.0.79
    │   │   ├── arrow v5.5.0 (*)
    │   │   ├── arrow v9.1.0 (*)
    │   │   ├── axum v0.4.8 (*)
    │   │   ├── columnq v0.4.5 (H:\github-project\roapi\columnq) (*)
    │   │   ├── columnq-cli v0.2.3 (H:\github-project\roapi\columnq-cli)
    │   │   ├── connectorx v0.2.3 (*)
    │   │   ├── deltalake v0.4.1 (https://github.com/delta-io/delta-rs.git?rev=f5e4b5f94393b517d3d88c200d7169cce11b304b#f5e4b5f9) (*)
    │   │   ├── mysql v21.0.2 (*)
    │   │   ├── mysql_common v0.27.5 (*)
    │   │   ├── reqwest v0.11.10 (*)
    │   │   ├── roapi-http v0.6.0 (H:\github-project\roapi\roapi-http)
    │   │   ├── rusoto_core v0.46.0 (*)
    │   │   ├── rusoto_core v0.47.0 (*)
    │   │   ├── rusoto_credential v0.46.0 (*)
    │   │   ├── rusoto_credential v0.47.0 (*)
    │   │   ├── rusoto_dynamodb v0.46.0 (*)
    │   │   └── yup-oauth2 v6.3.1 (*)
    │   └── serde_yaml v0.8.23
    │       └── roapi-http v0.6.0 (H:\github-project\roapi\roapi-http)
    │       [dev-dependencies]
    │       └── columnq v0.4.5 (H:\github-project\roapi\columnq) (*)
    └── lru v0.6.6
        └── mysql v21.0.2 (*)
    
    hashbrown v0.12.0
    └── datafusion v7.0.0 (*)
    
    hmac v0.10.1 (*)
    
    hmac v0.11.0 (*)
    
    hmac v0.12.1 (*)
    
    hyper-rustls v0.22.1 (*)
    
    hyper-rustls v0.23.0 (*)
    
    itoa v0.4.8
    ├── csv v1.1.6
    │   ├── arrow v5.5.0 (*)
    │   └── arrow v9.1.0 (*)
    └── serde_urlencoded v0.6.1
        └── rusoto_sts v0.46.0 (*)
    
    itoa v1.0.1
    ├── http v0.2.6
    │   ├── axum v0.4.8 (*)
    │   ├── axum-core v0.1.2
    │   │   └── axum v0.4.8 (*)
    │   ├── h2 v0.3.12 (*)
    │   ├── http-body v0.4.4
    │   │   ├── axum v0.4.8 (*)
    │   │   ├── axum-core v0.1.2 (*)
    │   │   ├── hyper v0.14.17 (*)
    │   │   ├── reqwest v0.11.10 (*)
    │   │   └── tower-http v0.2.5
    │   │       ├── axum v0.4.8 (*)
    │   │       └── roapi-http v0.6.0 (H:\github-project\roapi\roapi-http)
    │   ├── hyper v0.14.17 (*)
    │   ├── hyper-rustls v0.23.0 (*)
    │   ├── reqwest v0.11.10 (*)
    │   ├── rusoto_core v0.46.0 (*)
    │   ├── rusoto_core v0.47.0 (*)
    │   ├── rusoto_signature v0.46.0 (*)
    │   ├── rusoto_signature v0.47.0 (*)
    │   ├── tower-http v0.2.5 (*)
    │   └── yup-oauth2 v6.3.1 (*)
    ├── hyper v0.14.17 (*)
    ├── serde_json v1.0.79 (*)
    └── serde_urlencoded v0.7.1
        ├── axum v0.4.8 (*)
        ├── reqwest v0.11.10 (*)
        └── rusoto_sts v0.47.0 (*)
    
    lexical-core v0.7.6 (*)
    
    lexical-core v0.8.3
    └── arrow v9.1.0 (*)
    
    md-5 v0.9.1 (*)
    
    md-5 v0.10.1 (*)
    
    num-bigint v0.3.3
    └── bigdecimal v0.2.2
        └── mysql_common v0.27.5 (*)
    
    num-bigint v0.4.3
    ├── mysql_common v0.27.5 (*)
    ├── num v0.4.0
    │   ├── arrow v5.5.0 (*)
    │   ├── arrow v9.1.0 (*)
    │   └── parquet v9.1.0 (*)
    ├── num-rational v0.4.0
    │   └── num v0.4.0 (*)
    └── parquet v9.1.0 (*)
    
    ordered-float v1.1.1
    └── thrift v0.13.0
        ├── parquet v9.1.0 (*)
        └── parquet-format v4.0.0
            ├── deltalake v0.4.1 (https://github.com/delta-io/delta-rs.git?rev=f5e4b5f94393b517d3d88c200d7169cce11b304b#f5e4b5f9) (*)
            └── parquet v9.1.0 (*)
    
    ordered-float v2.10.0
    ├── datafusion v7.0.0 (*)
    └── datafusion-common v7.0.0 (*)
    
    parking_lot v0.11.2
    ├── r2d2 v0.8.9
    │   ├── connectorx v0.2.3 (*)
    │   ├── r2d2_mysql v21.0.0 (*)
    │   └── r2d2_sqlite v0.18.0 (*)
    ├── scheduled-thread-pool v0.2.5
    │   └── r2d2 v0.8.9 (*)
    └── tokio-postgres v0.7.5 (*)
    
    parking_lot v0.12.0
    ├── datafusion v7.0.0 (*)
    └── tokio v1.17.0
        ├── axum v0.4.8 (*)
        ├── columnq v0.4.5 (H:\github-project\roapi\columnq) (*)
        ├── columnq-cli v0.2.3 (H:\github-project\roapi\columnq-cli)
        ├── datafusion v7.0.0 (*)
        ├── deltalake v0.4.1 (https://github.com/delta-io/delta-rs.git?rev=f5e4b5f94393b517d3d88c200d7169cce11b304b#f5e4b5f9) (*)
        ├── dynamodb_lock v0.4.1 (https://github.com/delta-io/delta-rs.git?rev=f5e4b5f94393b517d3d88c200d7169cce11b304b#f5e4b5f9) (*)
        ├── h2 v0.3.12 (*)
        ├── hyper v0.14.17 (*)
        ├── hyper-rustls v0.22.1 (*)
        ├── hyper-rustls v0.23.0 (*)
        ├── postgres v0.19.2 (*)
        ├── reqwest v0.11.10 (*)
        ├── roapi-http v0.6.0 (H:\github-project\roapi\roapi-http)
        ├── rusoto_core v0.46.0 (*)
        ├── rusoto_core v0.47.0 (*)
        ├── rusoto_credential v0.46.0 (*)
        ├── rusoto_credential v0.47.0 (*)
        ├── rusoto_signature v0.46.0 (*)
        ├── rusoto_signature v0.47.0 (*)
        ├── tokio-postgres v0.7.5 (*)
        ├── tokio-rustls v0.22.0
        │   └── hyper-rustls v0.22.1 (*)
        ├── tokio-rustls v0.23.3
        │   ├── hyper-rustls v0.23.0 (*)
        │   └── reqwest v0.11.10 (*)
        ├── tokio-stream v0.1.8
        │   ├── datafusion v7.0.0 (*)
        │   └── deltalake v0.4.1 (https://github.com/delta-io/delta-rs.git?rev=f5e4b5f94393b517d3d88c200d7169cce11b304b#f5e4b5f9) (*)
        ├── tokio-util v0.6.9
        │   ├── h2 v0.3.12 (*)
        │   └── tokio-postgres v0.7.5 (*)
        ├── tokio-util v0.7.0
        │   └── tower v0.4.12
        │       ├── axum v0.4.8 (*)
        │       └── tower-http v0.2.5 (*)
        ├── tower v0.4.12 (*)
        └── yup-oauth2 v6.3.1 (*)
    
    parking_lot_core v0.8.5
    └── parking_lot v0.11.2 (*)
    
    parking_lot_core v0.9.1
    └── parking_lot v0.12.0 (*)
    
    rand v0.4.6
    └── tempdir v0.3.7
        [dev-dependencies]
        └── columnq v0.4.5 (H:\github-project\roapi\columnq) (*)
    
    rand v0.8.5
    ├── arrow v5.5.0 (*)
    ├── arrow v9.1.0 (*)
    ├── datafusion v7.0.0 (*)
    ├── mysql_common v0.27.5 (*)
    ├── parquet v9.1.0 (*)
    ├── postgres-protocol v0.6.3 (*)
    └── twox-hash v1.6.2
        └── mysql v21.0.2 (*)
    
    rusoto_core v0.46.0 (*)
    
    rusoto_core v0.47.0 (*)
    
    rusoto_credential v0.46.0 (*)
    
    rusoto_credential v0.47.0 (*)
    
    rusoto_s3 v0.46.0 (*)
    
    rusoto_s3 v0.47.0 (*)
    
    rusoto_signature v0.46.0 (*)
    
    rusoto_signature v0.47.0 (*)
    
    rusoto_sts v0.46.0 (*)
    
    rusoto_sts v0.47.0 (*)
    
    rustc_version v0.2.3
    [build-dependencies]
    ├── rusoto_core v0.46.0 (*)
    └── rusoto_signature v0.46.0 (*)
    
    rustc_version v0.4.0
    [build-dependencies]
    ├── rusoto_core v0.47.0 (*)
    └── rusoto_signature v0.47.0 (*)
    
    rustls v0.19.1
    ├── hyper-rustls v0.22.1 (*)
    ├── rustls-native-certs v0.5.0
    │   └── hyper-rustls v0.22.1 (*)
    ├── tokio-rustls v0.22.0 (*)
    └── yup-oauth2 v6.3.1 (*)
    
    rustls v0.20.4
    ├── hyper-rustls v0.23.0 (*)
    ├── reqwest v0.11.10 (*)
    └── tokio-rustls v0.23.3 (*)
    
    sct v0.6.1
    ├── ct-logs v0.8.0
    │   └── hyper-rustls v0.22.1 (*)
    └── rustls v0.19.1 (*)
    
    sct v0.7.0
    └── rustls v0.20.4 (*)
    
    semver v0.9.0
    └── rustc_version v0.2.3 (*)
    
    semver v1.0.6
    └── rustc_version v0.4.0 (*)
    
    serde_urlencoded v0.6.1 (*)
    
    serde_urlencoded v0.7.1 (*)
    
    sha2 v0.9.9 (*)
    
    sha2 v0.10.2 (*)
    
    shlex v0.1.1
    └── rusoto_credential v0.46.0 (*)
    
    shlex v1.1.0
    ├── bindgen v0.58.1 (*)
    └── rusoto_credential v0.47.0 (*)
    
    sqlparser v0.11.0
    └── connectorx v0.2.3 (*)
    
    sqlparser v0.14.0
    ├── columnq v0.4.5 (H:\github-project\roapi\columnq) (*)
    ├── datafusion v7.0.0 (*)
    ├── datafusion-common v7.0.0 (*)
    └── datafusion-expr v7.0.0 (*)
    
    strsim v0.8.0
    └── clap v2.34.0 (*)
    
    strsim v0.10.0
    └── clap v3.1.6 (*)
    
    textwrap v0.11.0
    └── clap v2.34.0 (*)
    
    textwrap v0.15.0
    └── clap v3.1.6 (*)
    
    time v0.1.43
    └── chrono v0.4.19
        ├── arrow v5.5.0 (*)
        ├── arrow v9.1.0 (*)
        ├── connectorx v0.2.3 (*)
        ├── datafusion v7.0.0 (*)
        ├── deltalake v0.4.1 (https://github.com/delta-io/delta-rs.git?rev=f5e4b5f94393b517d3d88c200d7169cce11b304b#f5e4b5f9) (*)
        ├── mysql_common v0.27.5 (*)
        ├── parquet v9.1.0 (*)
        ├── rusoto_credential v0.46.0 (*)
        ├── rusoto_credential v0.47.0 (*)
        ├── rusoto_signature v0.47.0 (*)
        ├── rusoto_sts v0.46.0 (*)
        ├── rusoto_sts v0.47.0 (*)
        ├── rusqlite v0.25.4 (*)
        └── yup-oauth2 v6.3.1 (*)
    
    time v0.2.27
    ├── mysql_common v0.27.5 (*)
    └── rusoto_signature v0.46.0 (*)
    
    tokio-rustls v0.22.0 (*)
    
    tokio-rustls v0.23.3 (*)
    
    tokio-util v0.6.9 (*)
    
    tokio-util v0.7.0 (*)
    
    webpki v0.21.4
    ├── hyper-rustls v0.22.1 (*)
    ├── rustls v0.19.1 (*)
    └── tokio-rustls v0.22.0 (*)
    
    webpki v0.22.0
    ├── rustls v0.20.4 (*)
    ├── tokio-rustls v0.23.3 (*)
    └── webpki-roots v0.22.2
        └── reqwest v0.11.10 (*)
    
    windows-sys v0.30.0
    └── fd-lock v3.0.4
        └── rustyline v9.1.2
            └── columnq-cli v0.2.3 (H:\github-project\roapi\columnq-cli)
    
    windows-sys v0.32.0
    └── parking_lot_core v0.9.1 (*)
    
    windows_x86_64_msvc v0.30.0
    └── windows-sys v0.30.0 (*)
    
    windows_x86_64_msvc v0.32.0
    └── windows-sys v0.32.0 (*)
  </pre>
</details>

### Brief info
```
 ~#@❯  cargo tree --duplicates | findstr /i "arrow connectorx datafusion"                                                                                                                      ❮  
    ??? arrow v5.5.0
    ?   ??? connectorx v0.2.3
                    ??? connectorx v0.2.3 (*)
?   ??? datafusion v7.0.0
    ??? connectorx v0.2.3 (*)
arrow v5.5.0 (*)
arrow v9.1.0
??? datafusion v7.0.0 (*)
??? datafusion-common v7.0.0
?   ??? datafusion v7.0.0 (*)
?   ??? datafusion-expr v7.0.0
?       ??? datafusion v7.0.0 (*)
??? datafusion-expr v7.0.0 (*)
    ??? datafusion v7.0.0 (*)
    ??? datafusion-common v7.0.0 (*)
    ?   ??? datafusion v7.0.0 (*)
    ?   ??? datafusion v7.0.0 (*)
        ??? datafusion v7.0.0 (*)
?       ??? connectorx v0.2.3 (*)
?           ??? connectorx v0.2.3 (*)
?   ??? arrow v5.5.0 (*)
?   ??? arrow v9.1.0 (*)
?   ?   ??? arrow v5.5.0 (*)
?   ?   ??? arrow v9.1.0 (*)
?   ?   ??? connectorx v0.2.3 (*)
??? datafusion v7.0.0 (*)
?   ??? arrow v5.5.0 (*)
?   ??? arrow v9.1.0 (*)
??? arrow v9.1.0 (*)
?   ??? arrow v5.5.0 (*)
?   ??? arrow v9.1.0 (*)
??? datafusion v7.0.0 (*)
??? datafusion-common v7.0.0 (*)
?   ??? connectorx v0.2.3 (*)
??? datafusion v7.0.0 (*)
    ??? datafusion v7.0.0 (*)
    ?   ??? datafusion v7.0.0 (*)
??? arrow v5.5.0 (*)
??? arrow v9.1.0 (*)
??? datafusion v7.0.0 (*)
??? connectorx v0.2.3 (*)
??? datafusion v7.0.0 (*)
??? datafusion-common v7.0.0 (*)
??? datafusion-expr v7.0.0 (*)
    ??? arrow v5.5.0 (*)
    ??? arrow v9.1.0 (*)
    ??? connectorx v0.2.3 (*)
    ??? datafusion v7.0.0 (*)
```

**Comment by houqp** [comment]
Yes, this is due to two different versions of arrow pinned between connectorx and datafusion. To fix this, we need to send a PR to connectorx to update its pinned arrow version.

**Comment by alamb** [comment]
Closing this as I think the question has been answered
