### ISSUE TITLE
Enable explain query in Ballista.

### ISSUE THREAD

**Issue by Ted-Jiang** [apache/arrow-datafusion#2096]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Now
```
explain select 1 as 'o_orderkey'  union all   select o_orderkey from orders order by o_orderkey limit 5;

[2022-03-26T05:17:46Z ERROR ballista_core::execution_plans::distributed_query] 
Job y4JTvKw failed: Job y4JTvKw failed due to General error: Could not save stage plan: Not implemented: PhysicalExtensionCodec is not provided
Execution("Job y4JTvKw failed: Job y4JTvKw failed due to General error: 
Could not save stage plan: Not implemented: PhysicalExtensionCodec is not provided")
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by doki23** [comment]
I'd like to take this issue if no one's working on it.

**Comment by Ted-Jiang** [comment]
> I'd like to take this issue if no one's working on it.

Thanks @doki23 ! ❤️

**Comment by doki23** [comment]
Hmm, I need some help. I have 2 solutions:

1. Generate a stage, and submit it. 
2. Ballista scheduler executes the query itself.

The first one needs small changes but unnecessary scheduler workload.
The second doesn't bring scheduler workload, but may need new api (I'm not very sure).
How do you think? @Ted-Jiang @yjshen Or is there another way?
