### ISSUE TITLE
Add support for group by Decimal numbers

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#210]
In the context of https://github.com/apache/arrow-datafusion/issues/107 from @joshuataylor

This will likely require  https://github.com/apache/arrow-rs/issues/230 (support for pretty-printing decimal numbers)

**Describe the solution you'd like**
It should be possible to group by data in columns of `DataType::Decimal` type

Right now you get an error such as:
```
(Internal("Unsupported GROUP BY type creating key Decimal(9, 0)"))
```

** Reproducer **
In the datafusion-cli:
```
CREATE EXTERNAL TABLE something STORED AS PARQUET LOCATION 'demo.parquet';
select O_ORDERKEY from something group by O_ORDERKEY;
```

Where demo.parquet is here: https://drive.google.com/file/d/1aCW7SW2rUVioSePduhgo_91F5-xDMyjp/view?usp=sharing

(note the file is large, so I am not sure how long this query will take)

**Comment by liukun4515** [comment]
@alamb 
this issue can be closed
```
❯ \d food
+---------------+--------------+------------+-------------+-----------------+-------------+
| table_catalog | table_schema | table_name | column_name | data_type       | is_nullable |
+---------------+--------------+------------+-------------+-----------------+-------------+
| datafusion    | public       | food       | a           | Decimal(10, 5)  | NO          |
| datafusion    | public       | food       | b           | Decimal(20, 15) | NO          |
| datafusion    | public       | food       | c           | Boolean         | NO          |
+---------------+--------------+------------+-------------+-----------------+-------------+
3 rows in set. Query took 0.010 seconds.
❯ select count(*),a from food group by a;
+-----------------+---------+
| COUNT(UInt8(1)) | a       |
+-----------------+---------+
| 3               | 0.00003 |
| 1               | 0.00001 |
| 4               | 0.00004 |
| 5               | 0.00005 |
| 2               | 0.00002 |
+-----------------+---------+
```

**Comment by houqp** [comment]
good work @liukun4515 :tada:

**Comment by liukun4515** [comment]
thanks for @alamb and @houqp pushing this feature forward.
There are many tasks about decimal or data type to do.

**Comment by alamb** [comment]
Thanks for all your help @liukun4515  and pushing it through. Really nicely done
