### ISSUE TITLE
Add datafusion design goals / invariants to repository

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#211]
As part of https://github.com/apache/arrow-datafusion/pull/55#pullrequestreview-645484795, @jorgecarleitao  refers to the following document that tries to summarize a proposed set of DataFusion invariants:

https://docs.google.com/document/d/1Asnz29uUS1t60QNbNBU9SiME274rja-hcDvX_RDraFU/edit

We would send this document around to the mailing lists (dev@arrow.apache.org)  (again) if we haven't already and then when sufficient consensus is reached, convert it to markdown and add it to this repo

**Comment by jorgecarleitao** [comment]
Wow, thanks a lot, @alamb ; excelent idea; I think the document is really old, and we did not have many of the practices and traction we have today

**Comment by alamb** [comment]
@jorgecarleitao  -- if you are interested in this, perhaps I can start the discussion on the mailing list / review the doc. It has been a while :)

**Comment by houqp** [comment]
+1 on formalizing this doc into datafusion repo!
