### ISSUE TITLE
Group by Alias

### ISSUE THREAD

**Issue by jychen7** [apache/arrow-datafusion#215]
**Describe the bug**
https://github.com/apache/arrow-datafusion/issues/110 suggests we can group by alias, however, I modify the existing test case `select_simple_aggregate_with_groupby_with_aliases` a bit, then it fails

**To Reproduce**
```
SELECT state AS a, MIN(age) AS b FROM person GROUP BY state
```
shows correct answer

```
SELECT state AS a, MIN(age) AS b FROM person GROUP BY a
```
raises error `Plan("Projection references non-aggregate values")`

**Expected behavior**
```
SELECT state AS a, MIN(age) AS b FROM person GROUP BY state

SELECT state AS a, MIN(age) AS b FROM person GROUP BY a
```
returns same answer

**Comment by jychen7** [comment]
I think we could `resolve_aliases_to_exprs` for `select.group_by`
similar to
datafusion/blob/e86ad26a678a32e2743bc031ae5cb81e6931a231/datafusion/src/sql/planner.rs#L563-L566

However, as a rust learner, I am still on the way struggling the rust typing system when deal with the array mapping

**Comment by alamb** [comment]
Thanks @jychen7  -- the expected behavior looks correct here 👍  Let us know if you need any help with the Rust
