### ISSUE TITLE
Research sort directly on raw bytes of composite sort keys for better performance

### ISSUE THREAD

**Issue by yjshen** [apache/arrow-datafusion#2150]
I hope to contribute improvements to the Sort performance (especially for multi-column sorts that include strings) this quarter as well. I don't have any writeup of that yet

_Originally posted by @alamb in https://github.com/apache/arrow-datafusion/pull/2133#discussion_r841062910_

**Comment by tustvold** [comment]
Closing as I believe this was implemented in https://github.com/apache/arrow-datafusion/pull/3386
