### ISSUE TITLE
Optimize InList implementation with native types rather than ScalarValue

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#2165]
The basic idea is that instead of using `ScalarValue` which has runtime dispatch overhead, we could use native rust types, like `HashSet<u32>`, etc. I think that could be a couple times faster.

_Originally posted by @Dandandan in https://github.com/apache/arrow-datafusion/pull/2156#discussion_r841898112_

**Comment by Dandandan** [comment]
In addition to higher memory usage and dispatching overhead there are two extra sources of overhead:

* Having to convert all values from array items to `ScalarValue`
* Hashing a `Scalarvalue` is slower than hashing a native type.
