### ISSUE TITLE
Move DataFusion cli/repl to own crate

### ISSUE THREAD

**Issue by Dandandan** [apache/arrow-datafusion#218]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
The Datafusion cli/repl functionality now lives inside the DataFusion tree.
This has two main implications:

* Building DataFusion fetches extra dependencies (`clap` `rustyline` and transitive dependencies) unneeded for the rest of DataFusion, slowing the development cycle down a bit (mainly for clean builds).
* Installing the binary using cargo is a bit more cumbersome, `cargo install datafusion --bin datafusion-cli --release`
* dependency constraints on the cli dependencies potentially can cause conflicts for DataFusion consumers

**Describe the solution you'd like**
Move the `datafusion-cli` to the root dir.
Publish the crate to `crates.io` as `datafusion-cli`. The tool now can be installed using `cargo install datafusion-cli --release` and now lives outside of the DataFusion crate.

**Describe alternatives you've considered**
Keep structure as is.

**Additional context**

**Comment by houqp** [comment]
+1 these cli dependencies could cause unnecessary dependency conflicts for downstream datafusion consumers as well.

**Comment by Dandandan** [comment]
That's a good one @houqp I'll add that as well.

**Comment by alamb** [comment]
I think this is a good idea. We might even get away without publishing the cli as a separate crate unless we have people who use it (perhaps we can pull the binary out and then publish a new crate if anyone wants it)

**Comment by andygrove** [comment]
I also filed https://github.com/apache/arrow-datafusion/issues/228 for publishing the DataFusion CLI as a Docker image
