### ISSUE TITLE
Replace Union.alias with SubqueryAlias

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#2213]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
In https://github.com/apache/arrow-datafusion/pull/2172 we added a new `SubqueryAlias` operator in the logical plan to wrap aliased table scans. This issue is to apply the same approach to unions and remove the `alias ` field from the `Union` struct.

**Describe the solution you'd like**
As described above.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by jackwener** [comment]
@andygrove  Hi, I'm willing to do this thing. I want to do it before #2172 because I think it's easier. 

After this finish, #2172 will be easy, just follow this.

**Comment by andygrove** [comment]
I am no longer sure if this is a good idea. Aliasing can only apply to certain operators. For example, it doesn't make sense to alias a filter operation. I am closing this for now.
