### ISSUE TITLE
Add unit test for case-sensitive SQL identifiers

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#2227]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
PR https://github.com/apache/arrow-datafusion/pull/2211 would have introduced a regression if merged, in case-sensitive comparisons of identifiers but did not cause any test failures, showing that we have a gap in test coverage.

**Describe the solution you'd like**
Implement a unit test based on the examples in the PR that would have caught the regression.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by alamb** [comment]
Note we didn't merge https://github.com/apache/arrow-datafusion/pull/2211 yet (so technically I don't think we added a regression yet)

**Comment by andygrove** [comment]
> Note we didn't merge #2211 yet (so technically I don't think we added a regression yet)

Good point. I updated the description to say *would have*.

**Comment by alamb** [comment]
And to be clear, the point is to add an **error** test showing that the query errors when incorrect capitalization is used
