### ISSUE TITLE
Move LogicalPlan to datafusion-expr crate

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#2245]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
I am trying to implement support for the expression `EXISTS (<subquery>)` and this requires having a new `Expr` variant that refers to a `LogicalPlan`. However, this is not possible because `LogicalPlan` is in the core `datafusion` crate which depends on the `datafusion-expr` crate that contains `Expr`, and therefore it is not possible to reference `LogicalPlan` from `Expr`.

**Describe the solution you'd like**
`LogicalPlan` and `Expr` should live in the same crate IMO so I propose moving `LogicalPlan` into the `datafusion-expr` crate.

**Describe alternatives you've considered**
None

**Additional context**
See the discussion in https://github.com/apache/arrow-datafusion/issues/2181 for more context

**Comment by matthewmturner** [comment]
Would it make sense to call this crate 'datafusion-logical-plan' after this change? At least to me it wouldn't be immediately obvious that logical plan was there from naming. But maybe that's just me.

**Comment by andygrove** [comment]
> Would it make sense to call this crate 'datafusion-logical-plan' after this change? At least to me it wouldn't be immediately obvious that logical plan was there from naming. But maybe that's just me.

Yes, that would make more sense to me too.

**Comment by andygrove** [comment]
So this doesn't look like it can work. The logical plan depends on the datasource module, which depends on the physical plan :disappointed: 

It might be better just to move the expressions back into the core crate.

**Comment by andygrove** [comment]
We need to address https://github.com/apache/arrow-datafusion/issues/2247 before we can make progress on this issue

**Comment by jychen7** [comment]
> Would it make sense to call this crate 'datafusion-logical-plan' after this change? At least to me it wouldn't be immediately obvious that logical plan was there from naming. But maybe that's just me.

+1
[minor] given we also have `physical-expr`, maybe we call it `logical-expr`?
