### ISSUE TITLE
`Concat` from Dataframe API no longer accepts multiple expressions

### ISSUE THREAD

**Issue by jorgecarleitao** [apache/arrow-datafusion#226]
The function has signature `concat(Expr)`, while some time ago it had the signature `concat(&[Expr])`.

I think that it makes sense to be `concat(&[Expr])`, as we AFAIK we hope to concatenate more than one expression.

Found while trying to bump python-datafusion to latest DataFusion.

**Comment by Jimexist** [comment]
i can probably take a look this week
