### ISSUE TITLE
Support "IS NOT TRUE/FALSE" syntax

### ISSUE THREAD

**Issue by wangxiaoying** [apache/arrow-datafusion#2265]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Currently when the sql query contains `is not true/false`, the following error will be thrown:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SQL(ParserError("Expected [NOT] NULL or [NOT] DISTINCT FROM after IS, found: NOT"))'
```

**Describe the solution you'd like**
`col is not true(false)` should have the same result with `col is NULL or col = false(true)`. For example in postgres, it works like follow:
<img width="720" alt="image" src="https://user-images.githubusercontent.com/5569610/163853092-79e660d7-13d6-4bff-801f-cc83034ab577.png">

**Describe alternatives you've considered**

**Additional context**
It looks like the error happens when parsing the query at [here](https://github.com/sqlparser-rs/sqlparser-rs/blob/main/src/parser.rs#L1116). Might need to support this syntax in `sqlparser` first.

**Comment by sarahyurick** [comment]
"IS NOT TRUE/FALSE" should be possible now that https://github.com/sqlparser-rs/sqlparser-rs/pull/583 has been merged. I can start working on this.

**Comment by sarahyurick** [comment]
@alamb do you think there's a quick solution (like #3235) for this case as well? Or should the implementation look similar to #3189?

**Comment by sarahyurick** [comment]
Mostly asking because if it's the latter, I could edit #3189 to be for "IS NOT TRUE/FALSE" instead. Otherwise, I'll close that PR.
