### ISSUE TITLE
Intermitent failure in CI join_with_hash_collision

### ISSUE THREAD

**Issue by jorgecarleitao** [apache/arrow-datafusion#227]
The CI is failing intermittently with

```
thread 'physical_plan::hash_join::tests::join_with_hash_collision' panicked at 'internal error: entered unreachable code: Hash should not be vacant', datafusion\src\physical_plan\hash_join.rs:1400:18
```

**Additional context**
See e.g. https://github.com/apache/arrow-datafusion/runs/2474850425?check_suite_focus=true

**Comment by Dandandan** [comment]
Thanks @jorgecarleitao I think the test should be improved / should set the `RandomState` explicitly or set hashes instead of values to make it deterministic.
