### ISSUE TITLE
Improve UX of looking up a DFSchema column by name

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#2319]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
I have a simple schema containing a column with the qualified name `df.a`:

``` rust
let schema = DFSchema::new_with_metadata(vec![
    DFField::new(Some("df"), "a", DataType::Int64, false),

], HashMap::new())?;
```

If I attempt to get the index of this column using `schema.index_of("df.a")` I get the very confusing error `No field named 'df.a'. Valid fields are 'df.a'.`.

There is an `index_of_column_by_name(&self, qualifier: Option<&str>, name: &str)` which would be a better API to call and this works as expected but it is not public.

As a workaround I have to use `index_of_column(&Column::from_qualified_name("df.a"))` instead, creating a temporary data structure and invoking a tokenizer which seems heavyweight.

**Describe the solution you'd like**
My proposal would be:

- Deprecate `index_of(&self, name: &str)` and also have it return an error if passed a qualified name
- Make `index_of_column_by_name` public

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by jdye64** [comment]
This would be helpful for something I am working on and am happy to work on this issue.

**Comment by andygrove** [comment]
I just noticed there is also `field_with_name` which would work fine, so I think all we need to is deprecate `index_of` and the check in there for qualified names

**Comment by andygrove** [comment]
Actually ignore my last comment - that is not an `index_of` method
