### ISSUE TITLE
[doc] Add code formatting instructions to CONTRIBUTING.md

### ISSUE THREAD

**Issue by jdye64** [apache/arrow-datafusion#2321]
A section in `CONTRIBUTING.md` for `Code Formatting` would be useful for new developers to understand patterns, standards, and also prevent unnecessary commits with linter errors.

**Describe the solution you'd like**
A short section in `CONTRIBUTING.md` explaining to new devs how to format their code from the cli and as part of pre-commit

**Comment by xudong963** [comment]
I think we just need to add explict hint?  Such as please run `cargo fmt` & `cargo lint` before committing?

**Comment by jdye64** [comment]
Yes, it really doesn't have to be much. Maybe a sentence explaining how to optionally install pre-commit

**Comment by timvw** [comment]
I tried to capture most of them in my PR [commit](https://github.com/apache/arrow-datafusion/pull/2394/commits/6ea9dbb0d3846a30847aacf2a84aae260009c5c9). (Because I managed to have failing builds due to these checks a couple of times 😛 )

**Comment by alamb** [comment]
Closed in https://github.com/apache/arrow-datafusion/pull/2444
