### ISSUE TITLE
Consider publishing crate as arrow-datafusion

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#234]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
This is probably a bad idea but we can at least document that we considered this :slightly_smiling_face: 

We are already at version 4.0.0 for the `datafusion` crate, and really that version number does not represent the maturity of the product.

Now that we have moved to a new repo, we could consider publishing a new `arrow-datafusion` crate and deprecate the existing `datafusion` crate. This would give us the opportunity to start again with version numbers and reset expectations.

**Describe the solution you'd like**
See above.

**Describe alternatives you've considered**
The alternative is to not do this and release 5.0.0 the next time we change an API.

**Additional context**
None.

**Comment by andygrove** [comment]
@alamb @jorgecarleitao It would be good to get your opinion on this

**Comment by alamb** [comment]
@andygrove  I personally think we should not confuse things by adding a new crate name. Once we get the arrow-rs versions releasing more regularly then I think we should start releasing datafausion on whatever cadence makes sense for it

I think people can draw their own conclusion of its maturity based on the number / frequency of major releases

Other than marketing / appearance of maturity, I don't think there is any  technical difference between publishing datafusion major versions and pre 1.0 versions 0.1, 0.2, etc.

**Comment by jorgecarleitao** [comment]
IMO it is more important to have a version that correctly represents the state of the software than `datafusion` in cargo.

IMO 0.X is the correct state of the software, both from a security point of view and if we plan to integrate Ballista more closely with DataFusion.

I find it odd that the vast majority of the software in Rust is pre-1, but arrow, parquet, DataFusion, etc, is post-1 (and all of them with an API that is essentially unstable). IMO that is an historical artifact, and we rather correct it sooner than later.

The perception of 3.0 in Rust is that the software had a significant maturation time.

From a users' perspective, the switch is a very low effort and I do think that we have the necessary channels to market any change (mailing, slack, github, cargo.io, etc).

**Comment by alamb** [comment]
I honestly don't have a strong opinion and can with whatever versioning
scheme. If I am left to my own devices, I would likely keep on the current
versioning scheme

**Comment by andygrove** [comment]
I personally think it is too late to consider this now. If anyone objects then feel free to re-open or create a new issue.
