### ISSUE TITLE
Enable discussion tab?

### ISSUE THREAD

**Issue by liurenjie1024** [apache/arrow-datafusion#2350]
Github allows discussion tab for open source projects, should we enable it for discussions?

**Comment by liurenjie1024** [comment]
@andygrove Please take a look.

**Comment by alamb** [comment]
Hi @liurenjie1024  -- the settings of this repo are controlled by asf.yaml 

It seems like a reasonable idea to me to enable them for this repo, but we will have to ask ASF infrstructure


https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features#Git.asf.yamlfeatures-GitHubDiscussions

**Comment by andygrove** [comment]
I have been thinking about this as well and I think it would be a good idea so that we can keep discussions and issues separate.

**Comment by andygrove** [comment]
I started a discussion on the mailing list about this

**Comment by alamb** [comment]
Mailing list link, in case anyone is interested: https://lists.apache.org/thread/o8d50n8fv989knxcqvnhosbg4fnzdlf8

**Comment by liurenjie1024** [comment]
It has been enabled, so we can close this now.
