### ISSUE TITLE
Optimize EXISTS subquery expressions by rewriting as semi-join

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#2351]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
I would like an optimizer rule that rewrites queries with EXISTS subqueries as semi-joins See discussion in https://github.com/apache/arrow-datafusion/pull/2344.

**Describe the solution you'd like**
See discussion in https://github.com/apache/arrow-datafusion/pull/2344 for an example.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by jon-chuang** [comment]
I'm currently halfway through implementing this, using heuristic rewrite rules, but I've decided to try to make it more generic as per DuckDB/Hyper's (and also apprently Materialize's) approach, which is to pushdown the dependent join through the subquery until all dependent/correlated predicates have been exfiltrated from the subquery. 

This was the intuition which occured to me as the most powerful and complete way, and thankfully there are trailblazers.

This is the best resource, DuckDB's pushdown logic for various logical operators:
https://github.com/duckdb/duckdb/blob/bee8017bdcc5e652aee26ce8cfb260990cf6a369/src/planner/subquery/flatten_dependent_join.cpp#L72

**Comment by andygrove** [comment]
I think this can be closed now
