### ISSUE TITLE
Validate subquery expressions

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#2361]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
The SQL query planner and the DataFrame API both allow logical plans to be created that contain subquery expressions but we do not yet do any validation on these expressions.

Examples of validation we should do:
- Scalar subqueries should return a single row and single column
- IN subqueries should return a single column

**Describe the solution you'd like**
I am leaning towards performing this validation in an optimizer rule because that would be applied regardless of how the logical plan was created.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by jon-chuang** [comment]
@andygrove is there any reason why we can't support multiple columns in the IN subquery? As far as implementation goes, it's fairly trivial.

**Comment by mingmwang** [comment]
I am working on it now.

**Comment by mingmwang** [comment]
@jon-chuang
I think we do not support named Struct in DataFusion today.

**Comment by mingmwang** [comment]
This issue is resolved.
