### ISSUE TITLE
Add support for `ROLLUP` and `CUBE` grouping sets in SQL query planner and logical plan

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#2378]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

I would like to be able to parse queries like this with the SQL query planner:

``` SQL
select a, b, c, count(*)          
 from  t1
 group by a, rollup (b, c);
```

**Describe the solution you'd like**
As above

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Jimexist** [comment]
see also:
- https://github.com/apache/arrow-datafusion/issues/1327
