### ISSUE TITLE
Support type-coercion from `Decimal` to `Float64`

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#2380]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

``` rust
#[tokio::test]
async fn sql_abs_decimal() -> Result<()> {
    let ctx = SessionContext::new();
    register_decimal_csv_table_by_sql(&ctx).await;
    let sql = "SELECT abs(c1) from decimal_simple";
    let actual = execute_to_batches(&ctx, sql).await;
```

Fails with

```
Coercion from [Decimal(10, 6)] to the signature Uniform(1, [Float64, Float32]) failed.
```

**Describe the solution you'd like**
I would like the decimal to be coerced into a floating-point value.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by comphead** [comment]
@andygrove Please check the PR

**Comment by comphead** [comment]
Opening new PR to resolve commit history
