### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by timvw** [apache/arrow-datafusion#2383]
**Describe the bug**
Currently a "cargo build" fails with the following error:
error[E0599]: no function or associated item named `from_str_unchecked` found for struct `proc_macro2::Literal` in the current scope
   --> /Users/timvw/.cargo/registry/src/github.com-1ecc6299db9ec823/quote-1.0.11/src/runtime.rs:301:41

**To Reproduce**
cargo build

**Expected behavior**
the build does not fail

**Comment by timvw** [comment]
PEBKAC: was still working on outdated fork.

**Comment by haoxins** [comment]
https://github.com/apache/arrow-datafusion/issues/1498
https://github.com/apache/arrow-datafusion/pull/1499
https://github.com/apache/arrow-datafusion/pull/1523

I think the only thing is to publish a new version on [crates.io](https://crates.io)
