### ISSUE TITLE
Move `data-access` crate to same level as other crates?

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#2424]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Most of the DataFusion crates are in subdirectories beneath `datafusion` but the `datafusion-cli` and `data-access` crates are outside of this structure. ~Is there a reason for this?~

Update: there is good reason for `datafusion-cli` to be at top-level because it depends on both DataFusion and Ballista.

**Describe the solution you'd like**
Why don't we move ~these two crates~ the `data-access` crate into the same structure as the rest of them? It would slightly simplify the release scripts.

**Describe alternatives you've considered**
We could just leave things as they are too. 

**Additional context**
None

**Comment by alamb** [comment]
>  Since creating this issue I realized that datafusion-cli probably is a special case since it depends on both ballista and datafusion so it makes sense to keep that at the top level.

Yes this is one reason. The other reason was to be able to commit a `Cargo.lock` file -- see discussion and linked PRs on https://github.com/apache/arrow-datafusion/issues/2071 (cc @happysalada )

**Comment by andygrove** [comment]
I have updated this issue to just discuss moving the `data-access` crate.
