### ISSUE TITLE
test_string_expressions test failure on Raspberry Pi (32-bit OS)

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#243]
**Describe the bug**
```
---- test_string_expressions stdout ----
thread 'test_string_expressions' panicked at 'called `Option::unwrap()` on a `None` value', datafusion/src/physical_plan/string_expressions.rs:584:70
```

**To Reproduce**
`cargo test`

**Expected behavior**
Test should pass

**Additional context**
- Commit: 5ecfb1b2a2750376c3721ea1754ef194469a161c
- Raspbian GNU/Linux 10
- Linux raspberrypi 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux
- rustc 1.51.0 (2fd73fabe 2021-03-23)

**Comment by andygrove** [comment]
Everything works fine with 64-bit Ubuntu on the Raspberry Pi so we should document that as the supported solution.

https://github.com/apache/arrow-datafusion/issues/247

**Comment by andygrove** [comment]
Amazingly, this issue is reproducible using Docker and cross. Make sure you have the Docker daemon running, then run:

```bash
cargo install cross
cross build --target armv7-unknown-linux-gnueabihf
cross test --target armv7-unknown-linux-gnueabihf
```

**Comment by returnString** [comment]
Having some issues with cross on Windows so can't repro, but do we _need_ the `to_usize` conversion for the failing `to_hex` function impl? From a cursory glance, looks like we're using `i64::MAX` as a test input, which doesn't fit into the ptr size on a 32-bit arch, but maybe there's a better way to handle the string formatting requirements here.

Personally I can't think of many other 32-bit use cases so am totally fine with the "use x64" workaround, but if we _do_ want to support it we should probably get some CI coverage going!

**Comment by andygrove** [comment]
Thanks. Commenting out that one test value does indeed fix the issue, so if we did want to add CI tests for 32-bit then this would be a good time to do it (before we add other cases that are 64-bit only). I really don't know how much interest there would be in 32-bit support though.

**Comment by returnString** [comment]
Maybe an agenda item for the sync call (possibly spilling over into community outreach on dev@, user@, and Slack)? It'd probably be good to decide either way for 32-bit support and either add test coverage, or document the limitations/prevent compilation outright, e.g.

```rust
#[cfg(target_pointer_width = "32")]
compile_error!("this crate does not support compilation for a 32-bit arch")
```

There might be benefits to supporting other ptr widths though, in terms of catching us doing silly things with `usize` etc for execptional inputs.

**Comment by andygrove** [comment]
I don't think this is a priority - I moved to 64 bit OS on Raspberry Pi
