### ISSUE TITLE
datafusion-cli crate has circular dependency

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#2433]
**Describe the bug**

`datafusion-cli` currently depends on both `ballista-0.6.0` and `datafusion-7.0.0`. `ballista-0.6.0` depends on `datafusion-6.0.0`.

![crate-deps](https://user-images.githubusercontent.com/934084/166486108-4952cf1e-d505-4106-a32c-b0b6b3db75c7.svg)

**To Reproduce**
N/A

**Expected behavior**
If we have one CLI that depends on both DataFusion and Ballista then it implies that we need to always release DataFusion and Ballista and release the CLI last.

**Additional context**
None

**Comment by jackwener** [comment]
I'm curious about this analysis tool. 😂 Could you please tell me what it is?
