### ISSUE TITLE
Result of window function with sort is wrong

### ISSUE THREAD

**Issue by doki23** [apache/arrow-datafusion#2448]
**Describe the bug**
Result of window function is wrong.

**To Reproduce**
Test with code 
```
    execute_with_partition(
        "select c2, SUM(c2) OVER (PARTITION BY c2 ORDER BY c1) as sum_c2 from test limit 5",
        4,
    )
```
The result vec is 
```
        "+----+--------+",
        "| c2 | sum_c2 |",
        "+----+--------+",
        "| 1  | 1      |",
        "| 1  | 2      |",
        "| 1  | 3      |",
        "| 1  | 4      |",
        "| .. | ..     |",
        "+----+--------+",
```

**Expected behavior**
```
        "+----+--------+",
        "| c2 | sum_c2 |",
        "+----+--------+",
        "| 1  | 4      |",
        "| 1  | 4      |",
        "| 1  | 4      |",
        "| 1  | 4      |",
        "| .. | ..     |",
        "+----+--------+",
```

**Additional context**
Problem is about `order by c1`.
It'll be correct if remove the `order by c1`.

**Comment by jhorstmann** [comment]
A bit difficult to analyze without seeing the corresponding values of `c1`. If the values for `c1` are distinct then the result seems correct since the presence of `ORDER BY` changes what is considered a peer of the current row. The [postgres documentation](https://www.postgresql.org/docs/14/sql-expressions.html#SYNTAX-WINDOW-FUNCTIONS) describes this as:

> The default framing option is RANGE UNBOUNDED PRECEDING, which is the same as RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW.

> **With ORDER BY**, this sets the frame to be all rows from the partition start **up through the current row's last ORDER BY peer**.

> **Without ORDER BY**, this means all rows of the partition are included in the window frame, **since all rows become peers of the current row**.

**Comment by doki23** [comment]
Oh, I get it! It's not a bug, the c1 column is distinct. Thanks! @jhorstmann
