### ISSUE TITLE
Document the process for publishing the user guide

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#246]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
We need a process for publishing the user guide each time we create a new release.

**Describe the solution you'd like**
New page in repo explaining how to publish the user guide.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by houqp** [comment]
This is now covered in https://github.com/apache/arrow-datafusion/tree/master/docs
