### ISSUE TITLE
`read_from_registered_table_with_glob_path` fails if path contains `//`

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#2465]
**Describe the bug**
`read_from_registered_table_with_glob_path` fails locally for me when running as part of `cargo test` but works fine in the IDE.

The issue appears to be when the path contains `//`.

When I run from `cargo test` I get the path `/home/andy/git/arrow-datafusion/parquet-testing/data//alltypes_plain*.parquet` and the test does not match any files.

I have `PARQUET_TEST_DATA` defined with a trailing slash:

``` bash
$ echo $PARQUET_TEST_DATA 
/home/andy/git/arrow-datafusion/parquet-testing/data/
```

We add another slash in the code:

``` rust
format!("{}/alltypes_plain*.parquet", parquet_test_data())
```

However, I would expect this to still work since the following works fine?

```
$ ls -l $PARQUET_TEST_DATA/alltypes_plain*.parquet
-rwxrwxr-x 1 andy andy 1851 Aug 17  2021 /home/andy/git/arrow-datafusion/parquet-testing/data//alltypes_plain.parquet
-rwxrwxr-x 1 andy andy 1736 Aug 17  2021 /home/andy/git/arrow-datafusion/parquet-testing/data//alltypes_plain.snappy.parquet
```

**To Reproduce**
Define `PARQUET_TEST_DATA` as above and run `cargo test`

**Expected behavior**
Test should pass

**Additional context**
None

**Comment by andygrove** [comment]
Hi @timvw - could I get your opinion on this? I can easily update the test to avoid having `//` but I wonder if this is a bug or not?

**Comment by timvw** [comment]
Hello @andygrove I can reproduce the behavior and it's consider it a bug indeed... Will further investigate.
