### ISSUE TITLE
Implement list_dir() for local filesysem

### ISSUE THREAD

**Issue by wjones127** [apache/arrow-datafusion#2466]
This was left as a todo earlier:

https://github.com/apache/arrow-datafusion/blob/5927bfceeba3a4eab7988289c674d925cc82ac05/data-access/src/object_store/local.rs#L51-L57

I don't know of any object store implementation that does implement it yet though.

**Comment by tustvold** [comment]
Potentially related to https://github.com/apache/arrow-datafusion/issues/2445
