### ISSUE TITLE
Add support for `GROUPING SETS` syntax in SQL planner

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#2469]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Issue https://github.com/apache/arrow-datafusion/issues/2378 adds support for `ROLLUP` and `CUBE` grouping sets. This is a follow on issue to also support `GROUPING SETS`, which may require changes to sqlparser-rs and also may require changes to the optimization rules to support `Vec<Vec<Expr>>`. See `optimizer/utils.rs` to see where this is not currently supported.

**Describe the solution you'd like**
Support `GROUP BY foo, GROUPING SETS (a (b, c), (c, d, e))`

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by alamb** [comment]
I agree changes to `sqlparser-rs` are required

**Comment by Jefffrey** [comment]
To be closed by https://github.com/apache/arrow-datafusion/pull/4770
