### ISSUE TITLE
Add Python documentation to user guide

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#255]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
As a user reading the user guide to understand how to use DataFusion, I would like to know how to use the Python bindings.

**Describe the solution you'd like**
The user guide should include a section on Python bindings and explain how to use them with DataFusion and Ballista (or explain what is and is not supported).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by matthewmturner** [comment]
I can take this.

Ok to use whats in `arrow-datafusion/python/README.md` as a start?

**Comment by houqp** [comment]
I believe by user guide, Andy was referring to https://github.com/apache/arrow-datafusion/tree/master/docs/user-guide. @Jimexist @jorgecarleitao do you have any opinion on this?

**Comment by matthewmturner** [comment]
@houqp thats what i was planning on updating.  I just thought that i could use the existing python walk through from the file i linked to as a starting point.  maybe i misunderstood the ask though.

**Comment by jorgecarleitao** [comment]
I would not recommend mixing Python in the Rust user guide.

Most users of Python do not care about Rust and vice-versa and each programming language usually has its own way of compiling guides tailored for the language (e.g. allow code with links to the playground in Rust).

For Python, I would recommend what fastAPI (and others) [do](https://github.com/tiangolo/fastapi/tree/master/docs/en) via [mkdocs](https://www.mkdocs.org/).

**Comment by houqp** [comment]
@Jimexist is already working on a dedicated python doc site for datafusion's python binding, perhaps we could just mention and link to that doc in the main user guide when it's ready?

**Comment by Jimexist** [comment]
I think I had a copy over at arrow git repo but might not have enough time to work on that this week. if you have time please feel free to take over.

**Comment by Jimexist** [comment]
my unmerged patch is at https://github.com/apache/arrow/pull/10982

**Comment by andygrove** [comment]
This was done some time ago: https://arrow.apache.org/datafusion/python/index.html
