### ISSUE TITLE
Update limit pushdown rule to support offsets

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#2550]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
PR https://github.com/apache/arrow-datafusion/pull/2521 adds support for `OFFSET`. The limit push down rule will not push the limit through offset so we should optimize this at some point.

**Describe the solution you'd like**
If we have offset 5 limit 10 then we should be able to push limit 15 (5  + 10)  beneath the offset operator in some cases. There is probably a lot more to this though.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Ted-Jiang** [comment]
I will take this. ❤️
