### ISSUE TITLE
Improve process for making changes to both `arrow-datafusion` and `arrow-ballista`

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#2583]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
As a follow-on to https://github.com/apache/arrow-datafusion/pull/2582 it would be nice if we could make the process a little easier and more automated.

**Describe the solution you'd like**
Perhaps we can implement a mechanism where we can say "Depends on ballista branch X" in the PR description and have the scripts pull that version?

**Describe alternatives you've considered**
Live with the current solution.

**Additional context**
None

**Comment by tustvold** [comment]
I've created https://github.com/apache/arrow-datafusion/pull/2632 to try to improve the workflow for arrow upgrades, as they're every two weeks. That said I feel something is a bit off with this, in my opinion Ballista should follow DataFusion upgrades, not lead them.

Perhaps in lieu of releasing DataFusion more frequently, we could simply update the git pin within Ballista more frequently. This is what we do with IOx, and often prior to a more risky DataFusion PR we will create a candidate IOx PR to test it out. I think this strikes a pragmatic balance, leaving reviewer discretion as to when to upgrade what.

When a breaking change is made to DataFusion, I think there should be an expectation that the contributor will help out with the corresponding changes to Ballista, but I think requiring the corresponding Ballista change in advance of changing DataFusion is a bit burdensome. My feeling is that at this stage in the arrow-rs and arrow-datafusion projects, which I'd describe as beta-ish, the priority should be iteration speed and trying out new ideas, and not on calcifying APIs for fear of breaking downstream code.

I don't know, I would appreciate your thoughts

**Comment by andygrove** [comment]
I think we can close this now. The current approach seems to be working well enough. Feel free to re-open is I am missing anything.
