### ISSUE TITLE
Add optimizer rule to remove `OFFSET 0`

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#2584]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Add optimizer rule to remove `OFFSET 0` since it is a no-op

**Describe the solution you'd like**
Add optimizer rule to remove `OFFSET 0`

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Ted-Jiang** [comment]
@andygrove  May i take this 😊?
