### ISSUE TITLE
Move logical optimizer rules out of the core datafusion crate

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#2599]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
As a user of DataFusion for SQL query planning, I would like to be able to use the logical plan optimizer rules without depending on the full datafusion crate containing the execution engine.

**Describe the solution you'd like**
I think there are two choices here:

1. Move the optimizer rules up to the `datafusion-expr` crate which contains the logical plans and expressions and already contains some of the expression rewriting logic that the optimizers depend on. This option would require us to make some changes to remove dependencies on the `physical-expr` crate as noted in https://github.com/apache/arrow-datafusion/issues/2535
2. Create a new `datafusion-optimizer` crate. This is an easier step because we can have it depend on `datafusion-physical-expr` for now and fix that later. It is also maybe good to use smaller crates where possible and keep different areas of functionality separate.

Tasks:

- [x] https://github.com/apache/arrow-datafusion/issues/2600

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by andygrove** [comment]
@alamb What would your preference be here?

**Comment by alamb** [comment]
> Create a new datafusion-optimizer crate. 

I would personally prefer this option as well
