### ISSUE TITLE
[enhancement] rules don't need to recursion inside themselves

### ISSUE THREAD

**Issue by jackwener** [apache/arrow-datafusion#2620]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Now, all rules in optimizer must handle `subplan` by recursing optimize themselves.

I'd like to let optimizer to handle `subplan`, rule just focus on the `optimize logic`.

I have add optimizer struct for this PR in #2616 .

**Describe the solution you'd like**
Handle the `subplan` in optimizer by  recursing optimization.

**Describe alternatives you've considered**

**Additional context**

**Comment by jackwener** [comment]
It need some time😄

**Comment by alamb** [comment]
I think it would be awesome to create some sort of `LogicalPlanRewriter` that is in the style of `ExprRewriter` or `ExprVisitor` and captures the traversal pattern across a plan

**Comment by jackwener** [comment]
Currently, `datafusion` optimize the plan many times. Because the all rules will traverse the whole plan tree one time.
Times is O(n). (n is number of rules).

I think it's not good choice. But now `explain verbose` print the changes after apply one rule. This ability depends on apply rule one by one.

I think the better and usual practice is traverse plan instead of traverse rules.

```
Now:
rules.foreach(
     plan.apply(rule)
)

After
DFS(plannode) {
     plannode.appy(rules).
}

```

**Comment by jackwener** [comment]
@alamb @Dandandan @andygrove @houqp 

How do you think about this trade-off

**Comment by alamb** [comment]
🎉
