### ISSUE TITLE
DataFrame TableProvider Circular Reference

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-datafusion#2659]
**Describe the bug**

Currently `DataFrame` implements `TableProvider` allowing it to be registered on a `SessionContext`, this will often be the same `SessionContext` from which its `Arc<RwLock<SessionState>>` came. For example

```
#[tokio::test]
    async fn register_table() -> Result<()> {
        let df = test_table().await?.select_columns(&["c1", "c12"])?;
        let ctx = SessionContext::new();
        let df_impl = Arc::new(DataFrame::new(ctx.state.clone(), &df.plan.clone()));
    
        // register a dataframe as a table
        ctx.register_table("test_table", df_impl.clone())?;
```

This will result in a circular reference that will prevent destruction of the SchemaProvider and the DataFrame.

**To Reproduce**

Inspect code

**Expected behavior**

It should not be possible to introduce circular dependencies. On a more holistic level, I'm not entirely sure what the purpose of this API is. Perhaps it could be removed and replaced with a combination of `DataFrame::to_logical_plan` and `ViewTable` (once #2657 is fixed)

**Additional context**

https://github.com/apache/arrow-datafusion/issues/2658

FYI @yjshen @xudong963

**Comment by matthewmturner** [comment]
FYI some additional context on this is https://github.com/apache/arrow-datafusion/issues/1698 and https://github.com/apache/arrow-datafusion/pull/1699.  Basically the idea was to enable registering a `DataFrame` as a table i.e. with a name.

**Comment by tustvold** [comment]
What did you think about this?

> Perhaps it could be removed and replaced with a combination of DataFrame::to_logical_plan and ViewTable

**Comment by matthewmturner** [comment]
Sounds good to me - is your idea to add a method like a `ctx.register_dataframe` method that would convert the `DataFrame` to a logical plan and register as `ViewTable`?
