### ISSUE TITLE
Improve readability of table scan projections in query plans

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#2697]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
From discussion in https://github.com/apache/arrow-datafusion/pull/2690#discussion_r889492584

What about only showing the projection when there is one and ommiting it when there are none.
This could remove the None/Some too:

```
TableScan a projection=[col1,col2]
```

vs

```
TableScan a
```

**Describe the solution you'd like**
As above

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by LiuYuHui** [comment]
I’d like to try it.
