### ISSUE TITLE
Version 0.6.0  Panic error during SQL execution

### ISSUE THREAD

**Issue by ike560** [apache/arrow-datafusion#2738]
**Describe the bug**
Panic error occurs when executing Join SQL. Refer to the attached jupyter execution result.

Exception: Arrow error: External error: Arrow error: External error: Execution error: Join Error: task 57 panicked
thread 'tokio-runtime-worker' panicked at 'range end index 83 out of range for slice of length 72'.

<img width="1150" alt="datafusion_panicError" src="https://user-images.githubusercontent.com/107613399/174028980-6428234a-db00-46a0-b20b-ecf2fbfb7b19.png">

**Additional context**
In version 0.5.2, No problem with the same SQL.

**Comment by ike560** [comment]
Additional Information

Column (company) value is UTF-8 Japanese string.
In company value is alpha-numeric string, there is no problem with the same SQL.

**Comment by ike560** [comment]
Solved!

After modifying the SQL as below, it was OK. **Help. Do you know why this modified SQL is OK?**
Before　  GROUP BY company
After　　 GROUP BY company, stock_code

```py
sql = '''
SELECT mas.company, SUM(CAST(trading_volume AS INTEGER)/10000000) AS sum_trading_volume FROM ( 
  SELECT stock_code, company FROM stock_master) AS mas 
    INNER JOIN stock_trading_info 
    USING (stock_code) 
  GROUP BY company, stock_code
  ORDER BY sum_trading_volume DESC 
  LIMIT 10
  '''
df = ctx.sql(sql)
```

**Comment by comphead** [comment]
@ike560 it is valid sql. You can group by  company, stock_code but still have only company in select. That doesn't make much sense, but it is still valid
