### ISSUE TITLE
Discord invite link in communication page has expired

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#2743]
**Describe the bug**
The discord link in https://arrow.apache.org/datafusion/community/communication.html#slack-and-discord has expired

Perhaps we should just ask people to email dev@ and ask for an invite instead?

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by houqp** [comment]
The discord link (https://discord.gg/Qw5gKqHxUM) is working for me, I saw two new members joined today as well. Were you getting an error?

**Comment by alamb** [comment]
Closing as resolved. Let's reopen if it is still causing a problem
