### ISSUE TITLE
Add optimization to remove unnecessary projections

### ISSUE THREAD

**Issue by Dandandan** [apache/arrow-datafusion#277]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Projections might be removed from a logical plan if they don't change the underlying plan.

**Describe the solution you'd like**
An optimization rule that removes any.
The most simple/basic way would be to only remove projections that refer to fields in the same order as the underlying plan.
A more complete optimization could also reorder underlying projections / table scans in order to remove projections. Also, expressions could be equivalent to those somewhere else in a plan, which could be considered.

**Describe alternatives you've considered**

**Additional context**

**Comment by waynexia** [comment]
Hi @Dandandan, it seems to be my problem to not link this issue with corresponding PR. I think we can close it now?

**Comment by Dandandan** [comment]
Thanks @waynexia
