### ISSUE TITLE
Migrate from avro_rs to apache_avro

### ISSUE THREAD

**Issue by martin-g** [apache/arrow-datafusion#2783]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

avro_rs has been [donated](https://github.com/flavray/avro-rs/#%EF%B8%8F-avro-rs-is-no-longer-maintained-here-please-refer-to-the-apacheavrorust-repository-instead-make-sure-you-read-the-apache-avro-guidelines-here-%EF%B8%8F) to Apache Avro project.
It would be good to use the new `apache_avro` crate.

Since it is not yet released the Pull Request will be a `Draft` until 0.14 is at https://crates.io.

**Describe the solution you'd like**
Migrate usage of `avro_rs` with `apache_avro` crate.

**Describe alternatives you've considered**

None

**Additional context**

N/A

**Comment by alamb** [comment]
Thanks @martin-g
