### ISSUE TITLE
EXTRACT(EPOCH from column)

### ISSUE THREAD

**Issue by mkmik** [apache/arrow-datafusion#2785]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Datafusion supports a few date parts like "year" or "seconds" in the `EXTRACT` operator.

Postgres offers a few more. In particular it offers an `EPOCH` date part which extracts the number of seconds since 1970-01-01 00:00:00-00 (can be negative). 

See https://www.postgresql.org/docs/8.1/functions-datetime.html

My particular use case is using pre-existing grafana postgres plugin, which crafts queries with such a construct. But I think it would be generally useful to support converting a timestamp to a unix epoch.

**Describe the solution you'd like**

```sql
select EXTRACT(EPOCH from column) from mytable;
```

**Describe alternatives you've considered**

```sql
select CAST(column AS bigint)/1000000000 from mytable;
```

**Comment by alamb** [comment]
BTW here is a nice contained test case: 

```
❯ select extract(epoch from '1825-08-29T07:29:01.256'::timestamp);
ArrowError(ExternalError(Execution("Date part 'EPOCH' not supported")))
```

I think this would be a good first issue

**Comment by toprakdeniz** [comment]
Hello Andrew,
I need to, and want to help datafusion project.
I think it is a good start for me.
I am new to Rust language and this will be the first open source support
for me.
I am familiar with software engineering and I have read Andrew Grove's book.
Best Regards,
Toprak Deniz

Andrew Lamb ***@***.***>, 12 Oca 2023 Per, 00:01 tarihinde
şunu yazdı:

**Comment by alamb** [comment]
Welcome to the community @toprakdeniz ! We have many first time Rust enthusiasts work on DataFusion and look forward to helping get this feature done.
