### ISSUE TITLE
panic when case statement returns null

### ISSUE THREAD

**Issue by kmitchener** [apache/arrow-datafusion#2798]
**Describe the bug**

I've boiled this down to a small test case which panics with this error:
thread 'main' panicked at 'NullArray data should not contain a null buffer, as no buffers are required'

**To Reproduce**

run this SQL from cli:
select case when b is null then null else b end from (select a,b from (values (1,null),(2,3)) as t (a,b)) a;

**Expected behavior**

In Postgres, it returns "null" and 3, as expected.

**Additional context**

Also, this query returns wrong results, as compared to PG:
select case when b is null then null else b end from (select a,b from (values (1,1),(2,3)) as t (a,b)) a;

in PG, that returns 2 rows: 1 and 3. In Datafusion, it returns 2 nulls.

**Comment by rostamn739** [comment]
also happens with
`select case when b is null then null else b end from (select a,b from (values (1,1),(2,null)) as t (a,b)) a;`


but does not happen with
`select case when b is null then null else 1 end from (select a,b from (values (1,null),(2,3)) as t (a,b)) a;`
