### ISSUE TITLE
Can't test or compile sub-model code after upgrade to arrow-rs 17.0.0

### ISSUE THREAD

**Issue by liukun4515** [apache/arrow-datafusion#2835]
**Describe the bug**
After upgrade to 17.0.0
I can't execute below command to build or test sub-model
```
cargo test  --manifest-path  arrow-datafusion/datafusion/common/Cargo.toml
   Compiling serde_json v1.0.78
error: expected item, found `"serde_json requires that either `std` (default) or `alloc` feature is enabled"`
 --> /Users/kliu3/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/serde_json-1.0.78/src/features_check/error.rs:1:1
  |
1 | "serde_json requires that either `std` (default) or `alloc` feature is enabled"
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected item
```

I just want to test the sub-model.

I think this is caused by the arrow-rs with some changes for Cargo dependency https://github.com/apache/arrow-rs/issues/1876

@martin-g 

@alamb 

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by liukun4515** [comment]
I try to resolve it by adding the 

```
default = ["crypto_expressions", "regex_expressions", "unicode_expressions", "serde_json_alloc"]
serde_json_alloc = ["serde_json/std"]
```
to the toml file.
But I am not sure if it is right

**Comment by tustvold** [comment]
Perhaps try updating serde_json, I also ran into this issue and deleting the lockfile made things work again

**Comment by liukun4515** [comment]
Do we need to fix that by give a pull request?

**Comment by liukun4515** [comment]
Just update lock for the dependency
