### ISSUE TITLE
Implement "SHOW CREATE TABLE" for external tables

### ISSUE THREAD

**Issue by mrob95** [apache/arrow-datafusion#2848]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Following on from #2529, it would be good to support external tables in "SHOW CREATE TABLE", [as spark does](https://docs.databricks.com/spark/latest/spark-sql/language-manual/sql-ref-syntax-aux-show-create-table.html).

**Describe the solution you'd like**
Implement `TableProvider::get_table_definition` for `ListingTable`, as in #2830. This will probably require implementing `Display` for `DFStatement` to convert it back into SQL, or generating SQL in `register_listing_table`.

**Describe alternatives you've considered**

**Additional context**

**Comment by psvri** [comment]
Hello,

If this is still open , I would like to pick this up.
