### ISSUE TITLE
Migrate the `cross join -> inner join optimization` from the planner to the optimizer

### ISSUE THREAD

**Issue by xudong963** [apache/arrow-datafusion#2859]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Migrate the cross join -> inner join optimization from the planner to the optimizer, and make it as an optimization rule.

Related code: https://github.com/apache/arrow-datafusion/blob/master/datafusion/sql/src/planner.rs#L770

**Additional context**
`cross join -> inner join optimization`: https://github.com/apache/arrow-datafusion/pull/1566

**Comment by Veeupup** [comment]
hi, @xudong963 I'm interested in trying this, may I try this?

**Comment by sadilet** [comment]
@Veeupup Hey, how is it coming along? @xudong963 could I also try to fix this issue?

**Comment by Veeupup** [comment]
sorry, I have been busy with some other stuff these times and forgot it...
@sadilet feel free to take it!

**Comment by xudong963** [comment]
@sadilet  Thanks!

**Comment by xudong963** [comment]
@sadilet  Hi, https://github.com/apache/arrow-datafusion/pull/3482 there is a related PR.
