### ISSUE TITLE
[Question] interested in helping with documentation

### ISSUE THREAD

**Issue by kmitchener** [apache/arrow-datafusion#2866]
Hi all,
I want to help with the documentation and I can pull issues from here to work on, but I have questions about how docs should be organized for the python project.

Datafusion-python is now in datafusion-contrib, outside of Apache. However, it's documentation is in the datafusion project repo. This leads to a weird dependency where docs will be created in the main datafusion repo, for versions of the python project managed by datafusion-contrib/datafusion-python. 

For example:
* there's a mismatch between datafusion's [python doc](https://github.com/apache/arrow-datafusion/blob/master/docs/source/python/index.rst) and the same documentation in the datafusion-python repo ([readme](https://github.com/datafusion-contrib/datafusion-python/blob/main/README.md))
* there are warnings when building the datafusion project docs that require changes to datafusion-python to fix. this is awkward.

It would be better if the docs for the datafusion-python project could be managed and published from that project, for consistency and ease of updating and possibly versioning of the docs in the future. Do you agree? Any ideas how to accomplish that? I'm willing to put in the work if there's agreement how to proceed.

**Comment by andygrove** [comment]
Thanks for raising this @kmitchener. The docs for the Python bindings should absolutely be in the repo that contains the python bindings and not in the core datafusion crate.

This can be accomplished by creating a PR to add the docs in `datafusion-python` and another PR to remove them from `arrow-datafusion`.
