### ISSUE TITLE
Add `cast` function for creating logical cast expression

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#2870]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
When using the dataframe API there is no easy way to cast a column to another type

**Describe the solution you'd like**
I would like a `cast` function something like this:

```rust
fn cast(expr: Expr, data_type: DataType) -> Expr {
    Expr::Cast {
        expr: Box::new(expr),
        data_type,
    }
}
```

This would allow me to then write dataframe code like this:

```rust
.with_column(
    "unixReviewTimestamp",
    cast(
        col("unixReviewTime"),
        DataType::Timestamp(TimeUnit::Millisecond, None),
    ),
)?
```

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by turbo1912** [comment]
I can pick this up if no one is working on it
