### ISSUE TITLE
serde_json requires that either `std` (default) or `alloc` feature is enabled

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#2896]
**Describe the bug**
I have recently been running into the error `serde_json requires that either ``std`` (default) or ``alloc`` feature is enabled` in CLion when working on DataFusion, or on projects that depend on DataFusion. This happens when attempting to run unit tests.

**To Reproduce**
I don't know if this is something specific to my environment or a more general issue.

**Expected behavior**
Should not get this error.

**Additional context**
None.

**Comment by andygrove** [comment]
My workaround locally is to add `serde_json = "1.0.82"` to `datafusion/common/Cargo.toml`

**Comment by andygrove** [comment]
@alamb fyi

**Comment by alamb** [comment]
Weird... I don't see this but then I don't use CLion / VSCode (I use emacs and tend to run the tests via `cargo run`)

Do we know what `cargo` command CLion is running underneath (aka can we reproduce this error outside of those IDEs?)

**Comment by tustvold** [comment]
This was caused for a while by a particular version of serde_json, running `cargo update` or deleting the lockfile should make it go away
