### ISSUE TITLE
csv_explain fails on RC verifier

### ISSUE THREAD

**Issue by nevi-me** [apache/arrow-datafusion#2916]
**Describe the bug**
When verifying the version 10 RC1, 3 csv tests fail because of an expected hardcoded string being different. `privateARROW_TEST_DATA` appears instead of `ARROW_TEST_DATA`.

`ARROW_TEST_DATA` is the path to a submodule that has test data (IIRC).

**To Reproduce**

Run `./dev/release/verify-release-candidate.sh 10.0.0 1`. I don't know if this occurs on all platforms, but I found the issue on macos aarch64

**Expected behavior**
Tests should pass

**Additional context**

Here's a gist with the failure log: https://gist.github.com/nevi-me/6813a794c1c52f0c36c642ff0e1aed33

**Comment by alamb** [comment]
For what it is worth, I saw (and still see a similar issue) https://github.com/apache/arrow-datafusion/issues/2719

Which @andygrove  said

>  I ran into this a while back and changed my ARROW_TEST_DATA env var to remove the trailing slash but we should really fix this. I will take a look in the next few days if nobody else picks this up.

I don't actually have `ARROW_TEST_DATA` set (I rely on the script to set it for me)

**Comment by alamb** [comment]
I think I see a way to fix this -- giving it a try...

**Comment by alamb** [comment]
Proposed fix in https://github.com/apache/arrow-datafusion/pull/2917
