### ISSUE TITLE
Rename a column name

### ISSUE THREAD

**Issue by jbabyhacker** [apache/arrow-datafusion#2919]
**Describe the solution you'd like**
Is it currently possible to rename a column name? The use case for me would be to read in csv files, then write out a parquet file with different column names.

**Describe alternatives you've considered**
I could use with with_column() and create a new column, then select a subset of the dataframe and save that.

**Comment by andygrove** [comment]
@jbabyhacker Sure. How does this look: https://github.com/apache/arrow-datafusion/pull/2920

**Comment by jbabyhacker** [comment]
Looks awesome. Thanks!
