### ISSUE TITLE
Support `mean` as synonym for `avg`

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#2922]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
This came up in https://github.com/datafusion-contrib/datafusion-python/issues/56

**Describe the solution you'd like**
Support "mean" as well as "avg"

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by andygrove** [comment]
If anyone is interested in picking this up, it looks like it is probably a one liner (plus tests).

We need to add an additional mapping here in `datafusion/expr/src/aggregate_function.rs`

```
impl FromStr for AggregateFunction {
    type Err = DataFusionError;
    fn from_str(name: &str) -> Result<AggregateFunction> {
        Ok(match name {
            "min" => AggregateFunction::Min,
            "max" => AggregateFunction::Max,
            "count" => AggregateFunction::Count,
            "avg" => AggregateFunction::Avg,
```

**Comment by BaymaxHWY** [comment]
I'm interested in this. May i try it?
