### ISSUE TITLE
bug: changing the number of partitions does not increase concurrency

### ISSUE THREAD

**Issue by sitano** [apache/arrow-datafusion#2928]
**Describe the bug**

Changing the number of partitions has no positive effect on the execution.

**To Reproduce**

1. take 10 GB CSV file
2. execute cli with 1 partition, it will take about 40 sec
3. -- CREATE EXTERNAL TABLE test (...) STORED AS CSV WITH HEADER ROW LOCATION 'test.csv';
4. -- SELECT SUM(total_amount) FROM test GROUP BY VendorID;
5. execute with 8 partitions (or 1000) (I have 8 real cores CPU), it will take 38 sec.

**Expected behavior**

At least some linear scalability per core number. For 8 parts = 40/8 ~ to be 5 sec.

**Additional context**
```
let mut session_config = SessionConfig::new()
        .with_information_schema(true)
        .with_target_partitions(args.threads);
```

maybe my patch to the CLI is wrong...

**Comment by Dandandan** [comment]
For reading csv, DataFusion reads the file sequentially. So setting the config on target partitions has limited effect on simple queries as reading CSV takes most of the time. Also by default it will use the number of logical cores available in the system.
For this query, I expect you will get faster results by splitting the CSV into 8 equal smaller CSV's (and, if it's more than testing, converting to parquet directly too).

**Comment by Dandandan** [comment]
Closing this for now, Feel free to reopen if you think it's a bug.
