### ISSUE TITLE
bug: file types handled wrong

### ISSUE THREAD

**Issue by sitano** [apache/arrow-datafusion#2929]
**Describe the bug**

If you create a CSV sourced table with the filename that does NOT have the .csv ending it will NOT work.

**To Reproduce**

1. CREATE EXTERNAL TABLE test (...) STORED AS CSV WITH HEADER ROW LOCATION 'afile'; // not afile.csv
2. SELECT * FROM test LIMIT 1;
3. Got nothing...

**Expected behavior**

It must work and return data.

**Additional context**

Table types must not depend on the filename...

**Comment by tustvold** [comment]
Closing as duplicate of #1736
