### ISSUE TITLE
Implement Debug for ColumnarValue

### ISSUE THREAD

**Issue by iajoiner** [apache/arrow-datafusion#2950]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

I'm frustrated because `ColumnarValue` does not have `Debug` implemented which makes debugging harder. 

**Describe the solution you'd like**
I'd like to implement `Debug` for `ColumnarValue`. Since it is already implemented for both `Array` and `ScalarValue` it should be very straightforward.

**Describe alternatives you've considered**
Something like `columnar_value.map(|cv| cv.into_array(1))` is doable but it is still not very straightforward.

**Comment by alamb** [comment]
Proposed fix: https://github.com/apache/arrow-datafusion/pull/3076
