### ISSUE TITLE
Example to show how to convert query result into rust struct

### ISSUE THREAD

**Issue by thomas-k-cameron** [apache/arrow-datafusion#2959]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Add an example that shows how to convert query result into rust struct.

**Describe the solution you'd like**
Add an example.

**Describe alternatives you've considered**
Implementing a macro to convert record batch into rust struct. 
Performance wise, this should have less overhead when implemented properly, but it takes some time to get it right. In the mean time, I think my solution is the most straight forward way to do this.

**Additional context**
Here is my implementation.
https://github.com/thomas-k-cameron/arrow-datafusion/blob/to_struct/datafusion-examples/examples/deserialize_to_struct.rs
If this is ok, I'd love to create a pull request.

I needed to convert the query result into rust struct for my project: I initially tried to implement a macro but after a while I discovered that you can actually do this using functions that are already implemented by the library.  It took me some time to figure this out, and I think this use case is relevant to many people.
I also saw a repository that is trying to implement a way to turn record batches into rust struct.

It would be very nice if you could let me know if I'm getting this wrong.

**Comment by andygrove** [comment]
Thanks @thomas-k-cameron. That looks like a very useful example to me.

**Comment by thomas-k-cameron** [comment]
> Thanks @thomas-k-cameron. That looks like a very useful example to me.

Thanks!
I just created a pull request.
https://github.com/apache/arrow-datafusion/pull/2969
