### ISSUE TITLE
to_timestamp timeunit to be consistent with postgresql's

### ISSUE THREAD

**Issue by waitingkuo** [apache/arrow-datafusion#2979]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Current [to_timestamp](https://arrow.apache.org/datafusion/user-guide/sql/datafusion-functions.html#to-timestamp) assume the input number is nanoseconds from 1970

```bash
❯ select to_timestamp(10);
+-------------------------------+
| totimestamp(Int64(10))        |
+-------------------------------+
| 1970-01-01 00:00:00.000000010 |
+-------------------------------+
1 row in set. Query took 0.000 seconds.
```

while postgresql's is to assume the number is seonds from 1970
```bash
willy=# select to_timestamp(10) at time zone 'utc';
      timezone       
---------------------
 1970-01-01 00:00:10
(1 row)
``` 

Should we align with postgrseql's?

**Describe the solution you'd like**

1. rename the original ```to_timestamp```  as to_timestamp_nanoseconds
2. we do have a [to_timestamp_seconds](https://arrow.apache.org/datafusion/user-guide/sql/datafusion-functions.html#to-timestamp-seconds) for now. we could either rename it to ```to_timestamp``` or make a new ```to_timestamp``` as ```to_timestamp_seconds```'s alias

**Comment by alamb** [comment]
Hi @waitingkuo  -- I think given the desire to make datafusion "A Declarative SQL query interface compatible with PostgreSQL" as described on https://arrow.apache.org/datafusion/specification/roadmap.html#datafusion compatible changing the current `to_timestamp` to be `to_timestamp_nanos()` and changing `to_timestamp()` to be the same as the current `to_timestamp_seconds` would be reasonable

Here are the docs, in case anyone is interested

https://github.com/apache/arrow-datafusion/blob/2598893ac7737e92b3be7b74f606280b32264e0e/docs/source/user-guide/sql/datafusion-functions.md#to_timestamp

**Comment by waitingkuo** [comment]
i'm interested in this, please assign me, thanks~

**Comment by alamb** [comment]
> Summary & My proposal

Makes sense to me. 👍 

cc @ovr @andygrove @seddonm1 @stuartcarnie   (not sure if anyone else is interested in this discussion too)

> start another thread for dicussing timezone implementation, I feel like this might break many things. And we also need to implement something like SET TIME ZONE AS xxx like what posgresql has

There are a variety of open issues known about timestamp handling -- for example https://github.com/apache/arrow-rs/issues/1936 https://github.com/apache/arrow-rs/issues/1380 https://github.com/apache/arrow-rs/issues/597 and others

It would be great to figure out how best to support these and start fixing it up.

**Comment by waitingkuo** [comment]
@alamb  should we consider `to_timestamp()` to output `timestamp with time zone`?

in postgresql `select timestamp '2020-01-01'` output `timestamp without time zone` but `to_timestamp()` output `timestamp with time zone`.

**Comment by waitingkuo** [comment]
@alamb  i could image that might breaks lots of thing

**Comment by waitingkuo** [comment]
@alamb 
after spend time figuring out how postgresql is working, i submitted a proposal here
#3100

probably we need to deal with datatype `date / time / timestamp / time zone` first and then move to this timestamp related functions

**Comment by alamb** [comment]
> probably we need to deal with datatype date / time / timestamp / time zone first and then move to this timestamp related functions

I agree that sounds wise

**Comment by waitingkuo** [comment]
@alamb it seems like now is a great time to align time-related functions with PostgreSQL, as most of the fundamental work has already been completed.

**Comment by alamb** [comment]
> @alamb it seems like now is a great time to align time-related functions with PostgreSQL, as most of the fundamental work has already been completed.

I agree -- it would be a good time.

Maybe we could make a new "date/time" epic and move all the unfinished stuff from https://github.com/apache/arrow-datafusion/issues/3148 to that new epic as a way to figure out what else is needed

**Comment by waitingkuo** [comment]
@alamb 
Sure, I am currently on vacation, and I will do it a little later.

**Comment by alamb** [comment]
Thanks @waitingkuo  -- no rush!
