### ISSUE TITLE
External parquet table fails when schema contains differing key / value metadata

### ISSUE THREAD

**Issue by stuartcarnie** [apache/arrow-datafusion#2982]
**Describe the bug**

Calling `create external table` for a set of `parquet` files fails with an error:

```
ArrowError(SchemaError("Fail to merge schema due to conflicting metadata."))
```

which originates from 

https://github.com/apache/arrow-rs/blob/08a7160fafafeacd1209ff568d5cb2fe55f889ea/arrow/src/datatypes/schema.rs#L148-L156

Versions prior to DataFusion 9.0.0 worked because typically the schema was decoded directly from the metadata:

https://github.com/apache/arrow-rs/blob/7d00e3c3b124bf39ad214ad08d1a1f49a4465dab/parquet/src/arrow/schema.rs#L53

Despite the arrow schema matching across all files.

**To Reproduce**

Create two parquet files with the same structure (columns and data types), but with differing values for a custom key and store this in the metadata.

**Expected behavior**

The following should succeed as the file data schemas match:

```
create external table docker_container_cpu stored as parquet location 'mydata/1/13/1/';
```

**Comment by alamb** [comment]
Amusingly / sadly there is a test for this (that I wrote) 🤦  -- it checks for different metadata but not incompatible metadata:

https://github.com/apache/arrow-datafusion/blob/3d4c7ef/datafusion/core/tests/sql/parquet.rs#L176-L226

I will fix this.

**Comment by stuartcarnie** [comment]
@alamb I have a hacky solution that removes all the metadata except the `ARROW:schema` key in this code path. 

I saw there is an option in the arrow-rs repo for the `ParquetFileArrowReader` to skip metadata:

https://github.com/apache/arrow-rs/blob/bedeb4f66663a868846c713bdd8ff0c5bd0983d4/parquet/src/arrow/arrow_reader.rs#L268-L270

However, a similar option wasn't available here. 

If you have a suggested direction for a fix, I am happy to work on a PR.

**Comment by alamb** [comment]
Thanks @stuartcarnie ! It was such a good one  I was working on a PR as well when you wrote this message (well, the test mostly) that basically does the same (adds a option to skip metadata)

The draft is here, but I ran out of time today: https://github.com/apache/arrow-datafusion/pull/2985

I think I like your naming of "skip" better than what I have there now. I will also look at the `ParquetFileArrowReader` 👍

**Comment by stuartcarnie** [comment]
Excellent, thanks @alamb!

**Comment by alamb** [comment]
https://github.com/apache/arrow-datafusion/pull/2985 is ready for review and I have verified that the usecase described in this ticket works now
