### ISSUE TITLE
The upcoming release of Arrow (20?) breaks datafusion

### ISSUE THREAD

**Issue by avantgardnerio** [apache/arrow-datafusion#3006]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Some changes to Decimal 128 & 256 require updating datafusion code to support.

**Describe the solution you'd like**

Decimal 128 to be supported.

**Describe alternatives you've considered**

I think we're going to have to do this.

**Additional context**

N/A

**Comment by alamb** [comment]
I think this has been resolved in #3007

**Comment by avantgardnerio** [comment]
> I think this has been resolved in #3007

The build is fully working in CI and for me locally, yes. There are still some failing checks I haven't looked into. Would you like me to undraft #3007?

**Comment by alamb** [comment]
> The build is fully working in CI and for me locally, yes. There are still some failing checks I haven't looked into. Would you like me to undraft https://github.com/apache/arrow-datafusion/pull/3007?

I don't have any strong preference

**Comment by liukun4515** [comment]
there are many api changes for decimal in arrow-rs.
upgrading the arrow-rs 20 for datafusion need to take effort.
Thanks for your work. @avantgardnerio
