### ISSUE TITLE
I want to query some files in a directory. Is there any way? 

### ISSUE THREAD

**Issue by yourenawo** [apache/arrow-datafusion#3013]
**Describe the bug**
There are 3000 parquet files named according to the timestamp in my directory. Now I just want to query some files, which can greatly reduce the query time.Thank you.

**Comment by andygrove** [comment]
Assuming that these files have the same or similar schema, then yes, you can just use the path to the directory rather than the path to an individual file.

**Comment by yourenawo** [comment]
thanks.
