### ISSUE TITLE
Create a `specification/` for `.md` documents with what we agreed upon

### ISSUE THREAD

**Issue by jorgecarleitao** [apache/arrow-datafusion#302]
I would like to propose that we create a directory `specification/` where we drop `.md` files that result from the discussions we have over google docs, so that they are given the proper visibility in this repository.

We would continue to use google docs to iterate on them. Once ready, I propose to PR them to this repo.

Reasons:
1. Licensing: the work on them imo should remain ASF-licensed
2. visibility: we have a simple place where we can refer to
3. easier to contribute: it is easy propose changes to those documents
4. audit: changes to those documents are properly versioned, specially after we "agreed" on them

**Comment by jorgecarleitao** [comment]
Any thoughts @alamb @andygrove @houqp @Dandandan @nevi-me ?

**Comment by houqp** [comment]
+1000, could we also serve them as part of datafusion's user/developer documentation?

**Comment by Dandandan** [comment]
I think it is a good idea. What about using the term RFC?

**Comment by alamb** [comment]
I think it is a great idea. I vaguely remember that Fernando suggested a more full featured version of a process to create the documents as well, but perhaps starting with recording the docs we do make is a good step towards formalizing the process more

In other words, 👍
