### ISSUE TITLE
Can I Filter Files During Multi-File Query?

### ISSUE THREAD

**Issue by bi-kai** [apache/arrow-datafusion#3027]
I have a folder containing .parquet files. The schemas of the files are the same, and the file names are distinguished by timestamp. 

The SQL statement, select * from table where timestamp 1645172395000 and 1645272395000, takes a long time for query. I want to filter out the files that are not within the time range during query.

In other words, I want to use the multi-file query function, but filter out files whose timestamp is not within the query time range. Is it possible?

**Comment by andygrove** [comment]
I think the solution here would be to implement a specialized version of `https://docs.rs/object_store/latest/object_store/trait.ObjectStore.html#tymethod.list` where a function can be passed to determine which files get selected (based on file names).

@tustvold WDYT?

**Comment by tustvold** [comment]
So DataFusion has fairly mature support for predicate pruning such as you describe, in particular https://docs.rs/datafusion/latest/datafusion/physical_optimizer/pruning/struct.PruningPredicate.html.

Assuming the predicate is pushed down to the [TableScan](https://docs.rs/datafusion/latest/datafusion/logical_plan/struct.TableScan.html). The following should happen automatically.

* If using [`ListingTable`](https://docs.rs/datafusion/latest/datafusion/datasource/listing/struct.ListingTable.html) as the catalog, any non-matching [partitions](https://docs.rs/datafusion/latest/datafusion/datasource/listing/struct.ListingOptions.html#structfield.table_partition_cols) will be filtered out
* If using `ListingTable` and enabled `collect_stat` the files will be pruned based on their metadata
* [ParquetExec](https://docs.rs/datafusion/latest/datafusion/physical_plan/file_format/struct.ParquetExec.html) will prune the row groups based on the filter

So at least theoretically, this should already be being performed. Perhaps you might be able to clarify:

* Do you have an actual catalog, or are you using `ListingTable`. In particular what [TableProvider](https://docs.rs/datafusion/latest/datafusion/datasource/datasource/trait.TableProvider.html) are you using
* Is your data partitioned at all? Is the `TableProvider` aware of this?
* Do you have a catalog that can provide file-level metadata?

>  think the solution here would be to implement a specialized version of https://docs.rs/object_store/latest/object_store/trait.ObjectStore.html#tymethod.list where a function can be passed to determine which files get selected (based on file names).

To me this sounds like a quirk of a very specific kind of data catalog. We could potentially add some sort of support for file-name extraction to `ListingTable`, but it is unclear why this would be pushed down to `ObjectStore`.

**Comment by alamb** [comment]
I think this ticket is not tracking anything -- it is too bad it is not a discussion so it may not be easy to find. However, I don't think it is actionable at this time so closing it
