### ISSUE TITLE
Why the PhysicalPlanner is an async trait ?

### ISSUE THREAD

**Issue by mingmwang** [apache/arrow-datafusion#3032]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

I have a question for the PhysicalPlanner, looks like in current DataFusion implement, the logical plan creation and optimization is the normal sync functions, but PhysicalPlanner is async, why ?

````
#[async_trait]
pub trait PhysicalPlanner: Send + Sync {
    /// Create a physical plan from a logical plan
    async fn create_physical_plan(
        &self,
        logical_plan: &LogicalPlan,
        session_state: &SessionState,
    ) -> Result<Arc<dyn ExecutionPlan>>;
}

````

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yjshen** [comment]
The `scan` in `TableProvider` which creates a physical scan plan from a logical table scan is async. It needs to list partitions and gather statistics that are async.

**Comment by mingmwang** [comment]
Thanks a lot for the explanation.
