### ISSUE TITLE
once now() is called in a statement, it forever returns the same value

### ISSUE THREAD

**Issue by kmitchener** [apache/arrow-datafusion#3057]
**Describe the bug**

```sql
select now();
-- ... 3 days later ...
select now(); -- returns same old value
```
It's correctly caching now() so it returns the same value when used multiple times in the same query, but it shouldn't be caching the value past statement execution, correct?

**To Reproduce**

**Expected behavior**

Would expect now() to return the same value for all instances in the same query, but a new value for a new statement in the same runtime context.

**Additional context**

**Comment by andygrove** [comment]
> It's correctly caching now() so it returns the same value when used multiple times in the same query, but it shouldn't be caching the value past statement execution, correct?

You are right. This is a bug.

**Comment by waitingkuo** [comment]
`now()` is using the time while session is created (i.e. the time datafusion-cli is launched).


<https://github.com/apache/arrow-datafusion/blob/master/datafusion/physical-expr/src/execution_props.rs#L32>

**Comment by alamb** [comment]
Agree -- now() should update between each statement but stay the same *within* a statement
