### ISSUE TITLE
eq operator doesn't work on binary data

### ISSUE THREAD

**Issue by ozgrakkurt** [apache/arrow-datafusion#3117]
Hello,

I am trying to use datafusion to query multiple parquet files.

Comparing a binary column with binary literal using eq operator doesn't work.

I expect this to just work since eq works on strings. 

I have this code:
```rust
let address = prefix_hex::decode::<Vec<u8>>(&self.address).map_err(Error::InvalidHexInAddress)?;
let mut expr = col("log.address").eq(lit(address));
```
and I get this error:
```
failed to execute query:\nArrow error: External error: Arrow error: External error: Execution error: Arrow error: External error: Arrow error: External error: Execution error: Arrow error: External error:
Internal error: Data type Binary(\"161,250,161,19,203,229,52,54,223,40,255,10,238,84,39,92,19,180,9,117\") not supported for scalar operation 'eq' on dyn array.
This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```

I tracked the error message to [here](https://github.com/apache/arrow-datafusion/blob/3eb55e9a0510d872f6f7765b1a5f17db46486e45/datafusion/physical-expr/src/expressions/binary.rs#L642)

Shouldn't there be a match arm for `Binary` data?

**Comment by alamb** [comment]
Thanks for the report @ozgrakkurt 

> Shouldn't there be a match arm for Binary data?

Yes I think you are exactly correct. 

If you have time, we would welcome a contribution to fix the issue

**Comment by ozgrakkurt** [comment]
@alamb created #3124
