### ISSUE TITLE
Support Time comparison

### ISSUE THREAD

**Issue by waitingkuo** [apache/arrow-datafusion#3157]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

we now have time but cannot be compared yet

```bash
DataFusion CLI v10.0.0
❯ select time '00:00:00';
+----------------------------------------------+
| CAST(Utf8("00:00:00") AS Time64(Nanosecond)) |
+----------------------------------------------+
| 00:00:00                                     |
+----------------------------------------------+
1 row in set. Query took 0.045 seconds.

❯ select time '00:00:00' = time '00:00:00';
ArrowError(NotYetImplemented("Comparing arrays of type Time64(Nanosecond) is not yet implemented"))

```

**Describe the solution you'd like**

support comparison for `Time64(Nanosecond)`

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
This query now works in datafusion 31:

```
DataFusion CLI v31.0.0
❯ select time '00:00:00' = time '00:00:00';
+-------------------------------------+
| Utf8("00:00:00") = Utf8("00:00:00") |
+-------------------------------------+
| true                                |
+-------------------------------------+
1 row in set. Query took 0.002 seconds.
```

Presumably due to all the work from @tustvold  and @berkaysynnada  getting these kernels in good shape
