### ISSUE TITLE
Support `SUM` `AVG`, `MIN`, `MAX` on `Time` columns. 

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#3166]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

DataFusion does not support `SUM`, `AVG`, `MIN` or `MAX` on `Time` type columns a standard SQL feature that could be used to sum how much cumulative time was spent doing some operation, for example

Reproducer is as follows:

```sql
select 
  sum(t), 
  avg(t)
from 
  (select cast ('11:00:00' as TIME) as t) as sq;
```

Doing so today will result in

```sql
❯ select 
  sum(t), 
  avg(t)
from 
  (select cast ('11:00:00' as TIME) as t) as sq;
Plan("The function Sum does not support inputs of type Time64(Nanosecond).")
❯ 
```

**Describe the solution you'd like**

**Describe alternatives you've considered**
N/A 

**Additional context**
As described in https://github.com/apache/arrow-datafusion/issues/200

**Comment by alamb** [comment]
I also think this is a relatively good first issue as it requires following the model for existing aggregates (e.g. SUM(int64)) so marking it as such.

**Comment by waitingkuo** [comment]
@alamb postgrseql cast time to interval and then do SUM and AVG

**Comment by alamb** [comment]
@waitingkuo notes that postgres does:

```bash
willy=# select pg_typeof(SUM(time '00:00:00')),  pg_typeof(AVg(time '00:00:00'));
 pg_typeof | pg_typeof 
-----------+-----------
 interval  | interval
(1 row)
```

this make sense otherwise SUM(Time) is just quite strange

**Comment by alamb** [comment]
`java.lang.ConcurrentModificationException` 😆  (our updates got crossed)

**Comment by waitingkuo** [comment]
do we have interval for now?
```bash
select '00:00:00'::interval;
NotImplemented("Unsupported SQL type Interval")
```

but this works
```bash
❯ select interval '1 second';
+------------------------------------------------+
| IntervalDayTime("1000")                        |
+------------------------------------------------+
| 0 years 0 mons 0 days 0 hours 0 mins 1.00 secs |
+------------------------------------------------+
```

**Comment by alamb** [comment]
Since we are treating `Time` literals as `Nanosecond` precision, I agree @waitingkuo  that the output of `SUM()` and `AVG()` of `TIME` should be `Interval(MonthDayNano)` 👍 

```shell
❯ select arrow_typeof(cast('10:00:00' as time));
+-----------------------------------------------------------+
| arrowtypeof(CAST(Utf8("10:00:00") AS Time64(Nanosecond))) |
+-----------------------------------------------------------+
| Time64(Nanosecond)                                        |
+-----------------------------------------------------------+
1 row in set. Query took 0.038 seconds.
```

**Comment by alamb** [comment]
> do we have interval for now?

🤔  looks like another feature gap https://github.com/apache/arrow-datafusion/pull/3167#discussion_r946145318

**Comment by waitingkuo** [comment]
> Since we are treating `Time` literals as `Nanosecond` precision, I agree @waitingkuo that the output of `SUM()` and `AVG()` of `TIME` should be `Interval(MonthDayNano)` 👍
> 
> ```shell
> ❯ select arrow_typeof(cast('10:00:00' as time));
> +-----------------------------------------------------------+
> | arrowtypeof(CAST(Utf8("10:00:00") AS Time64(Nanosecond))) |
> +-----------------------------------------------------------+
> | Time64(Nanosecond)                                        |
> +-----------------------------------------------------------+
> 1 row in set. Query took 0.038 seconds.
> ```

what about `select interval '1 second'`, should we output `Interval(MonthDayNano)` for making them all consistent?

**Comment by waitingkuo** [comment]
@alamb i've created a pull request for max and min #3178

`sum` and `avg` requires more work depends on some change for interval, i'll create another issue to discuss it. once we finished, i'll get back to this issue

```bash
❯ select min(t), max(t) from  (select '00:00:00' as t union select '00:00:01' union select '00:00:02');
+----------+----------+
| MIN(t)   | MAX(t)   |
+----------+----------+
| 00:00:00 | 00:00:02 |
+----------+----------+
1 row in set. Query took 0.009 seconds.
❯ 
```

**Comment by waitingkuo** [comment]
@alamb i was wrong, current interval implementation outputs different data type according to different input #3180

**Comment by alamb** [comment]
Thanks @waitingkuo  -- I am starting to work through my review backlog and will catch up with this shortly

**Comment by alamb** [comment]
cc @ovr
