### ISSUE TITLE
Re-implement parsing/planning for SHOW TABLES due to sqlparser changes

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#3188]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
We currently handle `SHOW TABLES` in in the planner when handling `Statement::ShowVariable` but sqlparser now returns `Statement::ShowTable` so we need to make corresponding changes.

**Describe the solution you'd like**
Make changes described above.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by andygrove** [comment]
Fixed in https://github.com/apache/arrow-datafusion/issues/3192

**Comment by NiwakaDev** [comment]
@andygrove 

Does `arrow-datafusion` supports `WHERE` clause in `SHOW TABLES`, such as `SHOW TABLES WHERE ~`?

**Comment by alamb** [comment]
> Does arrow-datafusion support WHERE clause in SHOW TABLES, such as SHOW TABLES WHERE ~?

I believe the answer is no

```sql
❯ show tables where table_name = tables;
Error during planning: Unsupported parameters to SHOW TABLES
```

I
