### ISSUE TITLE
sqlparser 0.21 upgrade

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#3192]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Tracking for work needed to upgrade to sqlparser 0.21. We are merging these changes into the `sqlparser-0.21` branch.

- [x] https://github.com/apache/arrow-datafusion/pull/3193
- [x] https://github.com/apache/arrow-datafusion/pull/3194
- [x] https://github.com/apache/arrow-datafusion/pull/3199
- [x] https://github.com/apache/arrow-datafusion/pull/3181
- [ ] https://github.com/apache/arrow-datafusion/pull/3202

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
Mailing list thread: https://lists.apache.org/thread/3h9gh68gw32xnzp2728r0wz485lrgbf9

I also think https://github.com/apache/arrow-datafusion/pull/3122 will be needed

@andygrove  is there a branch somewhere that you are using to do this integration?

**Comment by andygrove** [comment]
> @andygrove is there a branch somewhere that you are using to do this integration?

Yes, there is a `sqlparser-0.21` branch and some PRs already targeting it
