### ISSUE TITLE
Remove hard-coded Ballista version from scripts

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#32]
Ballista has some scripts for building Docker images and they have hard-coded versions, such as:

```bash
BALLISTA_VERSION=0.4.2-SNAPSHOT
```

We should change the scripts to get the version number from cargo instead. There are probably cargo utilities available to help with this.

**Comment by msathis** [comment]
I can take this 👍

**Comment by msathis** [comment]
I'll work on this once #23  is merged
