### ISSUE TITLE
datafusion cannot recognize chinese charactors.

### ISSUE THREAD

**Issue by ShaoDaTao** [apache/arrow-datafusion#3203]
**Describe the bug**
datafusion cannot recognize chinese charactors.

**To Reproduce**
1. simply create a csv file, put the title as name in chinese charactor: 扫描人
2. run the rust code as below,will get the parse error: Error: SQL(ParserError("Expected an expression:, found: 扫"))

`use datafusion::prelude::*;

#[tokio::main]
async fn main() -> datafusion::error::Result<()> {
  // register the table
  let ctx = SessionContext::new();
  ctx.register_csv("example", "lite.csv", CsvReadOptions::new()).await?;

  // create a plan to run a SQL query
  let df = ctx.sql("SELECT distinct 扫描人 FROM example").await?;

  // execute and print results
  df.show().await?;
  Ok(())
}`

**Expected behavior**
make datafusion recognize the chinese charactors.

**Additional context**

**Comment by francis-du** [comment]
You can try this

```
let df = ctx.sql("SELECT distinct \"扫描人\" FROM example").await?;
```

**Comment by ShaoDaTao** [comment]
Thanks.
