### ISSUE TITLE
Add `CREATE VIEW` documentation to user guide

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#3211]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
In docs/source/user-guide/sql/ddl.md we do not show that we support CREATE VIEW.

**Describe the solution you'd like**
Add docs

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by madihabdul** [comment]
Hi, I could take on this issue!

**Comment by alamb** [comment]
Thanks @madihabdul !

**Comment by kmitchener** [comment]
@madihabdul do you need some assistance with this issue? I'd be happy to help

**Comment by alamb** [comment]
> @madihabdul do you need some assistance with this issue? I'd be happy to help

@kmitchener   given there is no PR up if you don't hear from @madihabdul  I would recommend just proceeding. Thank you for checking first.

**Comment by retikulum** [comment]
Hi. As this issue is not closed or proceed, I will suggest following explanation for it. Is it enough?

# CREATE VIEW 
View is a virtual table based on the result of a SQL query. It can be created from an existing table or values list

<pre>
CREATE VIEW <i><b>view_name</i></b> AS statement;
</pre>

```sql
CREATE TABLE users AS VALUES(1,2),(2,3),(3,4),(4,5);
CREATE VIEW test AS SELECT column1 FROM users;
SELECT * FROM test;
+---------+
| column1 |
+---------+
| 1       |
| 2       |
| 3       |
| 4       |
+---------+
```
```sql
CREATE VIEW test AS VALUES(1,2),(5,6);
SELECT * FROM test;
+---------+---------+
| column1 | column2 |
+---------+---------+
| 1       | 2       |
| 5       | 6       |
+---------+---------+
```

**Comment by alamb** [comment]
Thanks @retikulum  -- your proposal looks great to me. We can always add some documentation and then expand upon it in future PRs

**Comment by retikulum** [comment]
I hope I will contribute datafusion more as I get used to codebase
