### ISSUE TITLE
Consider to categorize Operator

### ISSUE THREAD

**Issue by jackwener** [apache/arrow-datafusion#3216]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

categorize Operator.

----------- now ------------
Now, we put all operators in one level.
Like following:

```rust
pub enum Operator {
    /// Expressions are equal
    Eq,
    /// Expressions are not equal
    NotEq,
    /// Left side is smaller than right side
    Lt,
    /// Left side is smaller or equal to right side
    LtEq,
    /// Left side is greater than right side
    Gt,
    .....
}
```

**Describe the solution you'd like**

----------- want to do ------------

But, in fact, operator  are different categories.

we can 

```rust
pub enum ComparisonOp {
    Eq,
    NotEq,
    Lt,
    LtEq,
    Gt,
    GtEq,
}

pub enum Operator {
    ComparisonOp(ComparisonOp),
    other ...
}
```

**Describe alternatives you've considered**

**Additional context**

------- pg doc ---------

Like pg expr [operator](https://www.postgresql.org/docs/current/functions.html)

[9.2. Comparison Functions and Operators](https://www.postgresql.org/docs/current/functions-comparison.html)
....

------- project --------
In specific project

spark:
```scala
case class GreaterThan(left: Expression, right: Expression)
    extends BinaryComparison 
```
presto:
```java
public class ComparisonExpression
        extends Expression
{
    private final Operator operator;
    private final Expression left;
    private final Expression right;
}
```

**Comment by jackwener** [comment]
@alamb @liukun4515 @andygrove.

How do you think about this?

**Comment by jackwener** [comment]
This issue is inspired by my job.
I have researched many projects planner while working on new planner and cascades-optimizer for Apache Doris.
I think it's a points that can be optimized, which can make DF code is more clear and intuitive.

**Comment by alamb** [comment]
Hi @jackwener  -- sorry for my delay in responding I have been away. 

My opinion here is that your suggestion would make the code clearer. However, given the relative maturity (aka how many other people use it) of DataFusion making the change now would be realtively expensive; I am not sure the improvements would be worth the cost at this time.

**Comment by jackwener** [comment]
> However, given the relative maturity (aka how many other people use it) of DataFusion making the change now would be realtively expensive; I am not sure the improvements would be worth the cost at this time.

Agree with this,
