### ISSUE TITLE
Add support for `get` / `show` timezone

### ISSUE THREAD

**Issue by avantgardnerio** [apache/arrow-datafusion#3255]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Presently, `show timezone` does not work:

```
DataFusion CLI v11.0.0
❯ show time zone;
NotImplemented(“SHOW time.zone not implemented. Supported syntax: SHOW <TABLES>“)
```

**Describe the solution you'd like**

Instead, I would like:

```
show timezone;
```

To always return 'utc'.

```
set timezone 'utc';
```

Should succeed.

```
set timezone 'UTC+08`;
```
should return an error.

and
```
set timezone 'US/Mountain`;
```
should return the same error.

This should:
1. make the work @waitingkuo is doing easier by ignoring non-UTC zones for now
2. Stay technically compatible with ANSI SQL & postgres (as long as postgres is set to UTC)
3. allow the option to implement timezones at a future date.

PS:

Do the same for `select current_setting('TIMEZONE')`

**Describe alternatives you've considered**

- Having to violate ANSI SQL
- Having to tackle timezones while implementing `timestamp without timezone`

**Comment by avantgardnerio** [comment]
@andygrove @waitingkuo @alamb @tustvold

**Comment by alamb** [comment]
For what it is worth, here is what postgres does (mostly what @avantgardnerio  has proposed). Note there is an `=` in `SET TIMEONE=''`;

```sql
psql (14.4)
Type "help" for help.

alamb=# show timezone
alamb-# ;
     TimeZone     
------------------
 America/New_York
(1 row)

alamb=# set timezone='UTC+08';
SET
alamb=# show timezone;
 TimeZone 
----------
 UTC+08
(1 row)

alamb=# set timezone='US/Mountain';
SET
alamb=# show timezone;
  TimeZone   
-------------
 US/Mountain
(1 row)
```

**Comment by alamb** [comment]
(the proposal in this ticket sounds good to me)

**Comment by avantgardnerio** [comment]
Nice work @waitingkuo , thank you!!
