### ISSUE TITLE
Adopt physical plan serde from arrow-ballista

### ISSUE THREAD

**Issue by nvartolomei** [apache/arrow-datafusion#3257]
Hi. I'm wondering about your thoughts on adopting the physical plan serde code from ballista: https://github.com/apache/arrow-ballista/tree/master/ballista/rust/core/src/serde/physical_plan.

This will allow other users of datafusion to use and extend it (including ballista). The problem with using ballista code serde code in other projects is that it is ballista specific, rather than datafusion.

**Comment by avantgardnerio** [comment]
I would favor moving this into the DataFusion repo. It makes sense to have serialization be at the same level as the object that is being defined.

**Comment by alamb** [comment]
I agree it makes sense to me as well to have physical plan serialization in datafusion

**Comment by alamb** [comment]
I agree ! Thank you @nvartolomei
