### ISSUE TITLE
Introduce `Expr` variants for `IS [NOT] TRUE / FALSE / UNKNOWN`

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#3268]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
In https://github.com/apache/arrow-datafusion/pull/3252 we added support for SQL `IS [NOT] TRUE/FALSE` by mapping to the existing logical binary operator `Is[Not]DistinctFrom`. This resulted in a small PR compared to introducing new `Expr` variants such as `IsNotTrue`, but the downside is that we are now unable to implement type validation/coercion to ensure that the left expression is a boolean value.

**Describe the solution you'd like**
Introduce new `Expr` variants but still map to the physical plan for `IsDistinctFrom`.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by andygrove** [comment]
@sarahyurick fyi

**Comment by andygrove** [comment]
Another option would be to add `Operatror::IsTrue` instead of a new `Expr`.

**Comment by liukun4515** [comment]
> ~Another option would be to add `Operatror::IsTrue` instead of a new `Expr`~
> 
> Never mind, `IS TRUE` is a unary expression, not binary.

Hi @andygrove Do we need the  other unary expression for `IS_TRUE, IS_FALSE...`  ？
I go through preview pr for adding the sql syntax for above expr like that which convert the `IS_TRUE` to the binary expr
```
SQLExpr::IsNotTrue(expr) => Ok(Expr::BinaryExpr {
                left: Box::new(self.sql_expr_to_logical_expr(*expr, schema, ctes)?),
                op: Operator::IsDistinctFrom,
                right: Box::new(lit(true)),
            }),
```
I am not sure if it is a good way.
