### ISSUE TITLE
Support binary types in InList expression

### ISSUE THREAD

**Issue by ozgrakkurt** [apache/arrow-datafusion#3300]
Currently it gives `This feature is not implemented: InList does not support datatype Binary.` Should be straight forward to add a match arm for it in https://github.com/apache/arrow-datafusion/blob/3eb55e9a0510d872f6f7765b1a5f17db46486e45/datafusion/physical-expr/src/expressions/in_list.rs#L694

**Comment by HaoYang670** [comment]
Hi @ozgrakkurt, are you working on it? If not, I'd like to have a try.

**Comment by ozgrakkurt** [comment]
Hi @HaoYang670, yes sure thank you, I didn't start to work on it yet
