### ISSUE TITLE
test case `timestamp_add_interval_months` failed on master branch

### ISSUE THREAD

**Issue by waynexia** [apache/arrow-datafusion#3321]
**Describe the bug**

UT case `timestamp_add_interval_months` failed to run on master (commit 3d37016de3647d90e6f78fd0e106142923799969)

**To Reproduce**

```bash
git checkout 3d37016de3647d90e6f78fd0e106142923799969
cargo test
```

I got this error:
```plaintext
thread 'sql::timestamp::timestamp_add_interval_months' panicked at 'called `Option::unwrap()` on a `None` value', datafusion/core/tests/sql/timestamp.rs:1414:58
```

**Expected behavior**

Pass this test

**Additional context**

**Comment by waynexia** [comment]
I propose to add [this trigger](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch) to our CI file that allows us to trigger an action manually

**Comment by waynexia** [comment]
It looks like both #3305 ([action](https://github.com/apache/arrow-datafusion/runs/8129497515?check_suite_focus=true)) and #3320 ([action](https://github.com/apache/arrow-datafusion/runs/8130076973?check_suite_focus=true)) are affected by this.

**Comment by waynexia** [comment]
> I propose to add [this trigger](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch) to our CI file that allows us to trigger an action manually

Submitted #3323

**Comment by alamb** [comment]
We have disabled the failing test in https://github.com/apache/arrow-datafusion/pull/3329

It would be great if someone could help fix the test for real
