### ISSUE TITLE
Allow IDEs to recognize generated code

### ISSUE THREAD

**Issue by avantgardnerio** [apache/arrow-datafusion#3332]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Presently, prost generates code into the `target/` folder, which causes IDEs such as CLion to not be able to `go to definition`, or provide any auto-complete for this code, making it hard to work with.

**Describe the solution you'd like**

I'd like to move the generated code under the `src/` folder, but `.gitignore` it.

**Describe alternatives you've considered**

- Leave as is
- Check in the generated code

**Comment by alamb** [comment]
I believe these changes were also included in https://github.com/apache/arrow-datafusion/pull/3311

**Comment by tustvold** [comment]
FWIW I use CLion with generated code without issue, the trick is to run the build once, and then "Refresh Cargo Projects". You need to run the build first in order to actually generate the code
