### ISSUE TITLE
Add ability to get unoptimized logical plan from DataFrame

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#3340]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
It is only possible to get an optimized logical plan from a DataFrame (by calling `to_logical_plan`).

**Describe the solution you'd like**
Add ability to get unoptimized logical plan from DataFrame

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by iajoiner** [comment]
I will take this one.
