### ISSUE TITLE
Use `usize` to represent `Limit::skip`

### ISSUE THREAD

**Issue by HaoYang670** [apache/arrow-datafusion#3369]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
```rust
pub struct Limit {
    /// Number of rows to skip before fetch
    pub skip: Option<usize>,
    /// Maximum number of rows to fetch
    pub fetch: Option<usize>,
    /// The logical plan
    pub input: Arc<LogicalPlan>,
}
```
Since `skip = 0` and `skip = None` have same meaning, we can use pure `usize` to represent `skip` to reduce complexity.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Find this will work on #3355

**Comment by HaoYang670** [comment]
cc @alamb @andygrove @Dandandan .
Need your reviews this will cause some public API changes.

The reasons I want to do this are:
1. `skip = None` and `skip = Some(0)` are equivalent, so we don't need both of them.
2. This can avoid bugs in corner cases. While working on `limit_push_down`, I find there are lots of 'map_or, unwrap_or, ' and pattern matching with `return`, which is difficult to read and easy to have bug
3. We don't need to test `skip=None`, just to test `skip=0` is enough.

for `Limit::fetch`, we need the type `Optiona<usize>`, because `fetch = None` means fetching all rows, and we cannot express this in `usize`

**Comment by alamb** [comment]
I think this proposal makes sense to me as well. I can't think of any issues with it
