### ISSUE TITLE
`scalar::tests::size_of_scalar` failed on M1 Mac

### ISSUE THREAD

**Issue by HaoYang670** [apache/arrow-datafusion#3383]
**Describe the bug**
Tested on M1 Mac:
```
failures:

---- scalar::tests::size_of_scalar stdout ----
thread 'scalar::tests::size_of_scalar' panicked at 'assertion failed: `(left == right)`
  left: `48`,
 right: `64`', datafusion/common/src/scalar.rs:2583:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by HaoYang670** [comment]
Hi @alamb. Does the `cargo test (mac)` run on Intel or (M1 / M2)?
https://github.com/apache/arrow-datafusion/blob/master/.github/workflows/rust.yml#L201

**Comment by francis-du** [comment]
I have a similar error with my M2 Air

**Comment by alamb** [comment]
According to https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources:

```
Hardware specification for macOS virtual machines:

3-core CPU (x86_64)
14 GB of RAM
14 GB of SSD space
```

Thanks for filing this issue @HaoYang670

**Comment by alamb** [comment]
I recommend we #cfg this test to have the different size on ARM

Maybe with 
```rust
#[cfg(target_arch = "x86_64"))]
```

For example

**Comment by HaoYang670** [comment]
`x86_64` works on my M1 Mac.
