### ISSUE TITLE
Remove type-coercion from physical planner

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#3388]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Now that type coercion happens in the logical plan, we no longer need to do this in the physical plan.

See the discussion in https://github.com/apache/arrow-datafusion/pull/3254#issuecomment-1239345990 for an example of a bug that can occur if we do the type-coercion in both places.

**Describe the solution you'd like**
Remove type coercion from physical plan.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by liukun4515** [comment]
support the inlist type coercion in the logical phase https://github.com/apache/arrow-datafusion/issues/3468
