### ISSUE TITLE
pruning support cast/try_cast expr

### ISSUE THREAD

**Issue by liukun4515** [apache/arrow-datafusion#3414]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

In many case with the filter expr like c1 < 1, the filter expr many be cast to other data type through the type coercion logic.

After the optimizer, the filter may be added the cast/try_cast expr, but it can't be pruned with statistical data

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by liukun4515** [comment]
This also resolve the failed case in https://github.com/apache/arrow-datafusion/pull/3396

**Comment by alamb** [comment]
I think this is a dupe of https://github.com/apache/arrow-datafusion/issues/3377

**Comment by liukun4515** [comment]
> I think this is a dupe of #3377

Thank, I think i missing the issue in the list.
This issue are just inspired from the test case https://github.com/apache/arrow-datafusion/pull/3396

**Comment by liukun4515** [comment]
in order to make the correctness described in https://github.com/apache/arrow-datafusion/issues/3377, we should make the sure the type of value has order.

Now we will have the plan to support them:

- [ ] signed integer value and decimal
- [ ] unsigned integer value 
- [ ] time type
- [ ] TODO

**Comment by iajoiner** [comment]
On it.

**Comment by liukun4515** [comment]
> in order to make the correctness described in #3377, we should make the sure the type of value has order.
> 
> Now we will have the plan to support them:
> 
> * [ ]  signed integer value and decimal [support cast/try_cast in prune with signed integer and decimal #3422](https://github.com/apache/arrow-datafusion/pull/3422)
> * [ ]  unsigned integer value
> * [ ]  time type
> * [ ]  TODO

it is mentioned in the #3442  

I will close this issue
