### ISSUE TITLE
Support bitwise XOR operator (`#`)

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#3420]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
See usecase from @FauxFaux on https://github.com/apache/arrow-datafusion/issues/1619

The only remaining bitwise operator left to go is bitwise XOR (`#`) which is tracked by this ticket

**Describe the solution you'd like**
Implement  bitwise XOR operator (following the model of bitwise AND `&` and OR `|`) -- see PRs linked from https://github.com/apache/arrow-datafusion/issues/1619

I think this is a good first issue as there are existing operator examples which can be followed and newcomers could learn the codebase

**Comment by askoa** [comment]
I'll take a shot at this!
