### ISSUE TITLE
add datafusion-cli support of external table locations that object_store supports

### ISSUE THREAD

**Issue by kmitchener** [apache/arrow-datafusion#3424]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

**Describe the solution you'd like**

Within the datafusion-cli, I'd like to be able to run a `create external table` SQL with a location like an S3 bucket and have it try to acquire auth from the env.

```sql
create external table lineitem stored as parquet location 's3://my_bucket/lineitem/';
-- or 
create external table logs stored as csv partitioned by (year, month) location 's3://my_other_bucket/logs/';
-- or whatever location prefix for the Azure and GCP connection..
```

This will be useful for testing, as well as for tutorials showing features of DataFusion.

**Describe alternatives you've considered**

**Additional context**

**Comment by turbo1912** [comment]
Hi @kmitchener, did some digging on this issue and looks like there is some prior thinking on this. Most specifically [this issue](https://github.com/apache/arrow-datafusion/issues/1930).

**Comment by kmitchener** [comment]
@turbo1912 yes, and the object_store is new since then as well. Also, @timvw has just today published some cookbooks regarding object_store and s3 that may help with this: https://github.com/datafusion-contrib/datafusion-cookbook 

If you want to give it a shot, go for it!

**Comment by timvw** [comment]
More inspiration can be found in https://github.com/datafusion-contrib/datafusion-catalogprovider-glue where we take info from the metastore to register external tables...
