### ISSUE TITLE
How to read excel file with datafusion?

### ISSUE THREAD

**Issue by heyGrant** [apache/arrow-datafusion#3433]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
want to know how to read excel from datafusion, didn't find a demo for this.

**Comment by alamb** [comment]
Hi @heyGrant  -- I don't think we have any way to do that now. Maybe you could save excel as CSV and then read the CSV?

**Comment by heyGrant** [comment]
Thanks, Alamb.
