### ISSUE TITLE
support scientific notation for SQL literals

### ISSUE THREAD

**Issue by kmitchener** [apache/arrow-datafusion#3448]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

**Describe the solution you'd like**

Would like to be able to use scientific notation for numerics:

Currently, DataFusion takes the "e" notation as a column alias.
```sql
DataFusion CLI v11.0.0
❯ select 1e3;
+----+
| e3 |
+----+
| 1  |
+----+
1 row in set. Query took 0.012 seconds.
```

Add issue in sqlparser-rs to address the parsing issue: https://github.com/sqlparser-rs/sqlparser-rs/issues/610

**Describe alternatives you've considered**

**Additional context**

**Comment by Jefffrey** [comment]
Resolved by https://github.com/apache/arrow-datafusion/pull/4770 (which includes this fix https://github.com/sqlparser-rs/sqlparser-rs/pull/768)

Can now parse exponent literals:

```sql
DataFusion CLI v15.0.0
❯ select 1e3;
+---------------+
| Float64(1000) |
+---------------+
| 1000          |
+---------------+
1 row in set. Query took 0.002 seconds.
```

**Comment by alamb** [comment]
🎉
