### ISSUE TITLE
Support using offset index in `ParquetRecordBatchStream` when pushing down `RowFilter`

### ISSUE THREAD

**Issue by thinkharderdev** [apache/arrow-datafusion#3456]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

With https://github.com/apache/arrow-rs/pull/2552/files, using the offset index to prune page IO in `ParquetRecordBatchStream` should be stabilized. Once this is release in `arrow-rs` 23.0.0 we should allow users to enable offset indexes in `ParquetScanOptions`

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Ted-Jiang** [comment]
working on

**Comment by Ted-Jiang** [comment]
@thinkharderdev If you not starting this one, could you plz  assign this to me?

**Comment by thinkharderdev** [comment]
@Ted-Jiang It's all yours :)
