### ISSUE TITLE
Union columns with different types

### ISSUE THREAD

**Issue by gandronchik** [apache/arrow-datafusion#3467]
**Describe the bug**
You can union columns with different types. And it crashes if we order by this column

**To Reproduce**
it is just strange behavior:
`select 1 a union all select 'a';`
```
+---+
| a |
+---+
| 1 |
| a |
+---+
```

it should work, however since 1 is an integer and 1.1 is a decimal, it crashes:
`select 1 a union all select 1.1 order by 1;`

**Additional context**
Physical Sort Node does concat and it crashes. Looks like Union node has to autocast numeric types and returns error for rest types;

**Comment by gandronchik** [comment]
@alamb I am going to fix this problem. Is it fine if I will implement autocast for numeric types in UnionExec? Or you see better way?

**Comment by alamb** [comment]
> @alamb I am going to fix this problem. Is it fine if I will implement autocast for numeric types in UnionExec? Or you see better way?


I think the appropriate code to call would be "coerce" (as in the types of the union should be coerced to a common type). There is already code to do that for other similar operations (like `InList`, etc)

**Comment by liukun4515** [comment]
@gandronchik 
This is an error in the data type or type coercion which is not supported in the union.
You can follow the inlist or the binary type coercion do this in the union, we can help you to review the pr.

But now we are doing the migration the type coercion to logical phase https://github.com/apache/arrow-datafusion/issues/3388

**Comment by gandronchik** [comment]
@liukun4515 Got it. I will implement it in logical plan then

**Comment by liukun4515** [comment]
> @liukun4515 Got it. I will implement it in logical plan then

you can check this pr https://github.com/apache/arrow-datafusion/pull/3472

**Comment by gandronchik** [comment]
> > @liukun4515 Got it. I will implement it in logical plan then
> 
> you can refer this pr #3472

Why did you decide to do coercion in optimizators? At least in case with union I think it is better to do it directly in union building function

```
pub fn union_with_alias(
    left_plan: LogicalPlan,
    right_plan: LogicalPlan,
    alias: Option<String>,
) -> Result<LogicalPlan> {
```

**Comment by liukun4515** [comment]
> > > @liukun4515 Got it. I will implement it in logical plan then
> > 
> > 
> > you can refer this pr #3472
> 
> Why did you decide to do coercion in optimizators? At least in case with union I think it is better to do it directly in union building function
> 
> ```
> pub fn union_with_alias(
>     left_plan: LogicalPlan,
>     right_plan: LogicalPlan,
>     alias: Option<String>,
> ) -> Result<LogicalPlan> {
> ```

Yes, agree with you.

The type coercion should be done in the analyse phase, because of the codebase we can do this in the right place.

We do the type coercion in the physical phase when creating the physical expr.

cc @alamb @andygrove
