### ISSUE TITLE
The data type of predicate in the row filter should be same in the binary expr

### ISSUE THREAD

**Issue by liukun4515** [apache/arrow-datafusion#3469]
@alamb @thinkharderdev 
I find a issue caused by this rewrite in my work https://github.com/apache/arrow-datafusion/pull/3396
if we have two parquet, one has c1,c2, the other has c1,c3.
If the filter is c2 = 1, then it will produce a expr  NULL = 1 for the parquet with c1,c3 column.
After I remove the binary type coercion in the physical phase, the binary physical expr of `NULL = INT(1)` can't be created, because we don't need to support type coercion in creation physical expr.

_Originally posted by @liukun4515 in https://github.com/apache/arrow-datafusion/pull/3380#discussion_r970196771_

**Comment by liukun4515** [comment]
why not build the `build_row_filter` from the `phy expr`?

**Comment by liukun4515** [comment]
If the table schema is c1,c2,c3, the file schema is c1,c3 with filter c2 = lit.

Why not push the `predicate = false` to the parquet file directly to replace the c2 = NULL

**Comment by alamb** [comment]
> Why not push the predicate = false to the parquet file directly to replace the c2 = NULL

seems like a reasonable thing to me

**Comment by liukun4515** [comment]
> If the table schema is c1,c2,c3, the file schema is c1,c3 with filter c2 = lit.
> 
> Why not push the `predicate = false` to the parquet file directly to replace the c2 = NULL

cc @thinkharderdev

**Comment by alamb** [comment]
I think the more general flow here is to take a predicate like `c2 = lit` and a schema of `c1`, `c3` and replace `c2` with `NULL` -- which is what the code changed in https://github.com/apache/arrow-datafusion/pull/3470 is.

Then the predicate is `NULL = lit` which can be reduced to `false` if we run the constant evaluator on it
