### ISSUE TITLE
Improve display of operators in Explain output

### ISSUE THREAD

**Issue by Dandandan** [apache/arrow-datafusion#347]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Currently the plan shows the operators using the name instead of symbol. A readability improvement would be to use the operators symbols instead.

Old

```
Filter: #SUM(c) Gt Int64(10) And #b Gt Int64(10) And #SUM(c) Lt Int64(20)
```
New
```
Filter: #SUM(c) > Int64(10) AND #b > Int64(10) AND #SUM(c) < Int64(20)
```

**Describe the solution you'd like**
Change the `Debug` implementation to use `Display` for the  operator + fix the tests (74 tests need to be updated).

![image](https://user-images.githubusercontent.com/163737/118371742-4155a180-b5ae-11eb-989a-8a46845838ca.png)

**Describe alternatives you've considered**

**Additional context**

FYI @alamb

**Comment by alamb** [comment]
I think this is a great idea. Thank you

**Comment by jorgecarleitao** [comment]
IMO in general we should avoid relying on `{:?}` for printing things to end users. `{:?}` with `#[derive(Debug)]` is very useful to developers; usually users want less information.

**Comment by alamb** [comment]
I agree @jorgecarleitao

**Comment by Dandandan** [comment]
Exactly 👍 

IMO explain output also should be close or equal to SQL syntax, e.g. for the used expressions.

**Comment by alamb** [comment]
FWIW this requires implementing `Display` for `Expr`

**Comment by matthewmturner** [comment]
I can give this a shot.  To confirm - is the `BinaryExpr` the only variant of `Expr` that needs `Display` implemented?

**Comment by alamb** [comment]
> I can give this a shot. To confirm - is the BinaryExpr the only variant of Expr that needs Display implemented?


Thanks @matthewmturner  ! I think the intent is to have `Display` implemented for all variants of Expr (eventually) but it doesn't have to be all in one PR. I'll leave a comment on #971

**Comment by alamb** [comment]
(ps sorry for the belated reviews, but I am just catching up from being on vacation)
