### ISSUE TITLE
coercion between decimal and other types lacking, compared to other numeric types

### ISSUE THREAD

**Issue by kmitchener** [apache/arrow-datafusion#3479]
**Describe the bug**

**To Reproduce**
From test sql::expr::binary_mathematical_operator_with_null_lt 
```sql
❯ select null + 1::decimal;
Plan("'Null + Decimal128(38, 10)' can't be evaluated because there isn't a common type to coerce the types to")
```

or (from the "test_string_concat_operator" test):
```sql
❯ select 'a' || 1.1::decimal;
Plan("'Utf8 || Decimal128(38, 10)' can't be evaluated because there isn't a common type to coerce the types to")
```

**Expected behavior**

It should work like floats do:
```sql
❯ select null + 1::float;
+-----------------+
| NULL + Int64(1) |
+-----------------+
|                 |
+-----------------+
1 row in set. Query took 0.005 seconds.
```

```sql
❯ select 'a' || 1.1;
+---------------------------+
| Utf8("a") || Float64(1.1) |
+---------------------------+
| a1.1                      |
+---------------------------+
1 row in set. Query took 0.003 seconds.
```

**Additional context**

**Comment by liukun4515** [comment]
The `NULL` in the SQL syntax is associated with the `DataType::NULL`.
Now we don't support NULL data type with decimal data type yet.

But I think it is easy to support them.

I can help you to implement this.

@kmitchener

**Comment by liukun4515** [comment]
For `select 'a' || 1.1::decimal;` I think this should be support through the casting from decimal to utf8 https://github.com/apache/arrow-datafusion/issues/3478
