### ISSUE TITLE
Reduce compile time of DataFusion?

### ISSUE THREAD

**Issue by jorgecarleitao** [apache/arrow-datafusion#348]
During development of DataFusion I am getting a compile time that is hurting development. I am not sure if other feel the same, and I would like to gauge this here.

I admit I do not have a great machine, but I wonder if other also feel some pain in this front.

Note that this is unrelated with the dependencies; it is e.g. when changing a single physical node.

**Comment by andygrove** [comment]
FWIW, a full release build after `cargo clean` takes 1 min 35 seconds for me. The non-release build takes 58 seconds.

**Comment by houqp** [comment]
Being spoiled by Golang, I have to say it's relatively slow to the extend where i had to switch to do something else to wait for the build whenever I needed to test a change, even if it's just a single line.

**Comment by alamb** [comment]
I coworker reports that they can't work on datafusion with a mac mini with  8GB of RAM due to `rust_analyzer` swapping too much

It would be great to make this better somehow.

**Comment by alamb** [comment]
I ran the following to see where the time was going in my normal development loop: 
```
cargo +nightly test -p datafusion -Z timings
```


And the output was instructive. Specifically it seems to take 28.6 seconds to compile the actual datafusion crate, but a whopping 65.6s to compile the tests (aka `cfg(test)`). I'll keep plugging away at moving test code out of the `datafusion` crate and into integration tests 

```
   Completed datafusion v6.0.0 in 28.6s
   Completed datafusion v6.0.0 test "merge_fuzz" (test) in 4.6s
   Completed datafusion v6.0.0 test "order_spill_fuzz" (test) in 4.7s
   Completed datafusion v6.0.0 test "simplification" (test) in 4.8s
   Completed datafusion v6.0.0 test "dataframe" (test) in 6.1s
   Completed datafusion v6.0.0 test "provider_filter_pushdown" (test) in 6.7s
   Completed datafusion v6.0.0 test "custom_sources" (test) in 6.7s
   Completed datafusion v6.0.0 test "statistics" (test) in 6.8s
   Completed datafusion v6.0.0 test "path_partition" (test) in 6.9s
   Completed datafusion v6.0.0 test "user_defined_plan" (test) in 7.0s
   Completed datafusion v6.0.0 test "dataframe_functions" (test) in 7.4s
   Completed datafusion v6.0.0 test "parquet_pruning" (test) in 7.9s
   Completed datafusion v6.0.0 test "sql_integration" (test) in 19.2s
   Completed datafusion v6.0.0 lib (test) in 65.6s
```

**Comment by alamb** [comment]
@Jimexist  has a proposal to break datafusion into smaller crates here: https://github.com/apache/arrow-datafusion/issues/348

**Comment by alamb** [comment]
We bave broken the main datafusion crates up substantially since this ticket was filed. I think it is no longer specifically actionable, so closing it

Not that we can't improve compile time more, of course, just let's file tickets for more specific new symptoms
