### ISSUE TITLE
Allow configs to be set with string values

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#3500]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
In Ballista, I have key-value pairs for configs that I would like to pass along to DataFusion. However, ifI set configs this way and then DataFusion calls `get_u64` or `get_bool`, it will ignore the config because it has the wrong type.

**Describe the solution you'd like**
I would like to be able to pass string for any config and have DataFusion convert to the correct type.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by comphead** [comment]
Hi @andygrove, reg to your config comment https://github.com/apache/arrow-datafusion/pull/3522#issuecomment-1252865493

We refused to introduce automatic cast in `get_bool`, `get_u64`. 
`I would like to be able to pass string for any config and have DataFusion convert to the correct type.` -> this sounds like automatic cast still needed?
