### ISSUE TITLE
Release datafusion-cli 12.0.0 on Homebrew

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#3501]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
We should publish datafusion-cli 12.0.0 on Homebrew

**Describe the solution you'd like**
I would like someone to help with this as I ran into issues last time I tried this

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by iajoiner** [comment]
@andygrove I will do it manually this time and next time I will write a script to do it automatically. What this requires is really editing of a single file and filing a PR.

**Comment by iajoiner** [comment]
https://github.com/Homebrew/homebrew-core/pull/110829

**Comment by Jimexist** [comment]
the `brew` command should come with a bump pr command that helps you do this

**Comment by timvw** [comment]
Current PR will only download the source code. I
I would expect that the datafusion-cli binary is installed and made available instead...

WDYT @andygrove ?

**Comment by iajoiner** [comment]
@andygrove I think this can be closed since the update is complete haha.

**Comment by andygrove** [comment]
Thanks @iajoiner
