### ISSUE TITLE
What should be returned when trying to get a config in invalid format?

### ISSUE THREAD

**Issue by HaoYang670** [apache/arrow-datafusion#3505]
**Describe the bug**
Currently, when we get a config in invalid format, a default value will be returned. I'm not sure whether this is user-friendly.

**To Reproduce**
```rust
    #[test]
    fn get_config_in_invalid_format() {
        let config = ConfigOptions::new();
        let key = "datafusion.execution.batch_size";
        // this is great
        assert!(config.get(key).is_some());
        assert_eq!(8192, config.get_u64(key));

        // these are weird
        assert_eq!(false, config.get_bool(key));
        assert_eq!("", config.get_string(key));
    }
```

**Expected behavior**
Personally, I'd like the Datafusion to give some more precise information, for example returning `None` or an error message.

**Additional context**
This is related to #3500.

**Comment by alamb** [comment]
I agree getting an Error or None would be better
