### ISSUE TITLE
Push limit to sort

### ISSUE THREAD

**Issue by Dandandan** [apache/arrow-datafusion#3528]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
We can use the availability of a `Limit` to speed up sorts in DataFusion:

**Describe the solution you'd like**
We can start utilizing the limit in different places:
*  lexsort_to_indices supports a `limit` argument - this argument can be filled (if limit is smaller than batch size)
* a `LocalLimit` can be added before SortPreservingMergeExec (after https://github.com/apache/arrow-datafusion/pull/3527), limiting the input for this 
* Probably `SortPreservingMergeStream` can start utilizing optional limits too - only merging the first n sorted rows for each batch. 

This issue is about adding the limit to `lexsort_to_indices`. This will accomplish the following:

* using the faster `partial_sort`
* reducing the `take` input and thus size of output batches
* reducing the memory needed for `SortPreservingMergeExec`  (and spill to disk when running OOM / shuffle data in Ballista)

**Describe alternatives you've considered**

**Additional context**

**Comment by jychen7** [comment]
> lexsort_to_indices supports a limit argument 

for reference, it supports since 2021-03-16
https://github.com/apache/arrow-rs/commit/08b02709b5e5483c77b55058715a8309a0ab3b0e
