### ISSUE TITLE
ReduceOuterJoin optimizer support `cast or try_cast` expr.

### ISSUE THREAD

**Issue by liukun4515** [apache/arrow-datafusion#3565]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

In the join test `reduce_left_join_1`

```
let sql = "select * from t1 left join t2 on t1.t1_id = t2.t2_id where t2.t2_id < 100";
```

the below sql will be convert to the `inner join`. But after the  https://github.com/apache/arrow-datafusion/pull/3396 and move the `type coercion` in the beginning of the optimizer, we will do the cast first for the `t2.t2_id < 100`, and get the `cast(t2.t2_id as int64) < Int64(100)`.

If with the cast or try_cast, the `ReduceOuterJoin` will not work.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AssHero** [comment]
I'll try to handle this case.

**Comment by liukun4515** [comment]
> 


> I'll try to handle this case.
Thanks @AssHero 
I find a way to bypass it first.

**Comment by liukun4515** [comment]
@AssHero Do you have plan to do this recently?
