### ISSUE TITLE
`StringConcat` gives inconsistent result with `concat` when containing `null`

### ISSUE THREAD

**Issue by HaoYang670** [apache/arrow-datafusion#3569]
**Describe the bug**

**To Reproduce**
```
❯ select concat('a', null) from t;
+------------------------+
| concat(Utf8("a"),NULL) |
+------------------------+
| a                      |
+------------------------+
1 row in set. Query took 0.003 seconds.
❯ select 'a' || null from t;
+-------------------+
| Utf8("a") || NULL |
+-------------------+
|                   |
+-------------------+
1 row in set. Query took 0.003 seconds.
❯ 
```

**Expected behavior**
The two queries should return the same result.
In Spark, string_concat always return null when there is `null` element: (on Spark3.3.0)
```scala
scala> df.selectExpr("'a' || null ").show
+---------------+
|concat(a, NULL)|
+---------------+
|           null|
+---------------+


scala> df.selectExpr("concat('a' || null)").show
+-----------------------+
|concat(concat(a, NULL))|
+-----------------------+
|                   null|
+-----------------------+
```

**Additional context**

**Comment by HaoYang670** [comment]
Oh, I see in the postgresql, `concat` will ignore `null` but `||` won't: https://www.postgresqltutorial.com/postgresql-string-functions/postgresql-concat-function/
This is a little weird. @alamb should we follow the behavior of Spark or Postgresql?

**Comment by doki23** [comment]
I prefer the pg-like style because it provides more options for users.

**Comment by HaoYang670** [comment]
Thank you, @doki23 @alamb. This makes sense and I will close this issue.
