### ISSUE TITLE
register_csv allow space in table_path

### ISSUE THREAD

**Issue by crc-sstubbs** [apache/arrow-datafusion#3589]
**Describe the bug**
table_path when using:
```
context.register_csv
```
does not support spaces in path.

**To Reproduce**
```
context = SessionContext::new();

context
.register_csv("testing", "/folder/test folder/testing.csv", CsvReadOptions::new())
.await
```

**Expected behavior**
function to work as it does for paths without spaces.

**Comment by alamb** [comment]
Thanks @crc-sstubbs  -- I think this would make a good first issue for someone who wanted to learn some of the datafusion codebase

**Comment by unvalley** [comment]
I'll take a look!
