### ISSUE TITLE
Publically export Arrow crate from datafusion 

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#36]
As suggested by @andygrove  and @returnString on https://github.com/apache/arrow-datafusion/pull/33#issuecomment-824860644

# Rationale:
Make it easy for crates that depend on DataFusion to get the correct version of the arrow-rs crate without having to manually keep versions in check

# Proposed Changes:
DataFusion should `pub`lically  re-export the Arrow crate so that dependent crates automatically get the same Arrow version

**Comment by returnString** [comment]
I'll take this later today if no-one else wants to claim it immediately :)

**Comment by jorgecarleitao** [comment]
I though that dependencies could only be declared in `Cargo.toml`. Or is the idea that we use `pub use arrow::*` in `datafusion/arrow.rs`, and ask people to use `use datafusion::arrow::X` instead of `arrow::X` in their crates?

**Comment by returnString** [comment]
> I though that dependencies could only be declared in `Cargo.toml`. Or is the idea that we use `pub use arrow::*` in `datafusion/arrow.rs`, and ask people to use `use datafusion::arrow::X` instead of `arrow::X` in their crates?

Yeah, my understanding here is we'd use the latter approach of explicitly reexporting arrow. It'd still be possible for people to declare a dependency on arrow and use it directly, but the `datafusion::arrow` reexport would allow for people to get an appropriate version of arrow _by default_, rather than having to manually upgrade deps in lockstep :)

**Comment by jorgecarleitao** [comment]
Makes a lot of sense to me 👍

I think we will need to remember to bump datafusion's major whenever we bump arrow's major in `Cargo.toml`, as datafusions' public API will now contain arrows' public API (right?)

**Comment by alamb** [comment]
Thank you @returnString !
