### ISSUE TITLE
Support window functions with window frame

### ISSUE THREAD

**Issue by Jimexist** [apache/arrow-datafusion#361]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

Implement [frame spec in window clause](https://www.postgresql.org/docs/current/sql-expressions.html#SYNTAX-WINDOW-FUNCTIONS)

**Describe the solution you'd like**

We'd like to support window function in three or more steps:
1. #359 basic structure 
2. #298 empty over clause
3. #299 with partition clause
4. #360 with order by
5. #361 with window frame (this one)

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
For anyone following this, a window frame query looks like this (the `ROWS BETWEEN 2 PRECEDING AND 0 FOLLOWING`)

```sql
SELECT water_level, avg(water_level) OVER (ORDER BY time desc ROWS BETWEEN 2 PRECEDING AND 0 FOLLOWING)
FROM
  "h2o_feet"
WHERE
  time >= cast ('2019-09-17T20:00:00Z' as timestamp) AND
  time <= cast ('2019-09-17T21:42:00Z' as timestamp);
```

Which results in an error
```
This feature is not implemented: window expression with window frame definition is not yet supported
```

**Comment by alamb** [comment]
It appears there is some work afoot to support this in https://github.com/synnada-ai/arrow-datafusion/pull/1

**Comment by ozankabak** [comment]
> It appears there is some work afoot to support this in [synnada-ai#1](https://github.com/synnada-ai/arrow-datafusion/pull/1)

Yes, we plan to submit a PR draft early next week that makes progress on this issue. We hope to resolve it fully once we get community feedback.

**Comment by Ted-Jiang** [comment]
i am going to fix this `window func` issue. So we can do `window func`  in ballista ✌️

**Comment by Ted-Jiang** [comment]
I have run some query success in out internal version ballista 😄 and fix a lot issue

**Comment by Ted-Jiang** [comment]
@ozankabak Thanks again for supporting window frame.👍

**Comment by alamb** [comment]
I am going to claim this ticket is done. Thank you to the Synnada team and @ozankabak  and @mustafasrepo  for helping make it happen 👏

**Comment by ozankabak** [comment]
You are welcome, looking forward to helping in the future too!
