### ISSUE TITLE
`INTERSECT` and `EXCEPT` don't return an error when 2 sets have the different number of columns

### ISSUE THREAD

**Issue by HaoYang670** [apache/arrow-datafusion#3632]
**Describe the bug**

**To Reproduce**
```sql
❯ select 1 as a, 2 as b
intersect
select 1 as a;
+---+---+
| a | b |
+---+---+
| 1 | 2 |
+---+---+
1 row in set. Query took 0.009 seconds.
❯ select 1 as a, 2 as b
except
select 2 as a;
+---+---+
| a | b |
+---+---+
| 1 | 2 |
+---+---+
```

**Expected behavior**
We should return an error, which is the behaviour in the Postgresql: https://onecompiler.com/postgresql/3yhau7n8a

**Additional context**

**Comment by askoa** [comment]
I looked into this issue and have some questions.

The below check already seems to do the job. The below function is called in the function `intersect_or_except` which seems to be the common function for intersect and expect. Is there any other place we need to look into?

https://github.com/apache/arrow-datafusion/blob/6d2b417def2d536e81eb80e082d9cc3ca4e7f5fc/datafusion/expr/src/logical_plan/builder.rs#L490-L495

**Comment by HaoYang670** [comment]
I guess the problem is in the `intersect_or_except` where we should check the number of columns before we zip the the `join_keys`: https://github.com/apache/arrow-datafusion/blob/6d2b417def2d536e81eb80e082d9cc3ca4e7f5fc/datafusion/expr/src/logical_plan/builder.rs#L784-L794

**Comment by askoa** [comment]
I see. So the zip works when the iterators are of different size. I'll fix this.
