### ISSUE TITLE
LEFT JOIN not working as expected, error message is confusing

### ISSUE THREAD

**Issue by paddyhoran** [apache/arrow-datafusion#3639]
**Describe the bug**
I am trying to get a very basic LEFT JOIN to work and I cannot.

**To Reproduce**
I may be mistaken (new to SQL) but I believe this SQL should work:
```sql
-- create left table
create table t1_1 as select 1 as a, 4 as b;
create table t1_2 as select 1 as a, 5 as b;
create table t1 as
    select * from t1_1
    union all
    select * from t1_2;

-- create right table
create table t2 as select 1 as aa, 10 as c;

-- join
select * from t2 left join t1 t2 on t2.aa = t1.a
```

**Additional context**
Also, the error message seems to list all fields as members of the `t2` table:
```
SchemaError(FieldNotFound { qualifier: Some("t1"), name: "a", valid_fields: Some(["t2.aa", "t2.c", "t2.a", "t2.b"]) })
```

I ran into this with views but could reproduce with tables and I am using datafusion-cli version `12.0.0` on Mac.

**Comment by Dandandan** [comment]
`left join t1 t2` ? Creates an alias `t2` for `t1`. Is this what you meant? What if you remove the `t2`?

**Comment by paddyhoran** [comment]
Ah so it's just my lack of SQL experience...  Looks like `select * from t2 left join t1 on t2.aa = t1.a` is what I need.

I was going off of `select * from x left join x y ON x.column_1 = y.column_2;` from [this](https://arrow.apache.org/datafusion/user-guide/sql/select.html#left-outer-join) example.

Thanks very much.
