### ISSUE TITLE
[Question] output_ordering() in SortMergeJoinExec

### ISSUE THREAD

**Issue by mingmwang** [apache/arrow-datafusion#3652]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

One question about the implementation of this method, not sure my understanding is correct or not.
The output order should be the join key after applying the sorting, why the current implementation just return the left or right's output ordering? Does the implementation already assume the left/right inputs are already sorted ?

````

    fn output_ordering(&self) -> Option<&[PhysicalSortExpr]> {
        match self.join_type {
            JoinType::Inner | JoinType::Left | JoinType::Semi | JoinType::Anti => {
                self.left.output_ordering()
            }
            JoinType::Right => self.right.output_ordering(),
            JoinType::Full => None,
        }
    }

````
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
> Does the implementation already assume the left/right inputs are already sorted ?

Yes, it is a merge operation
