### ISSUE TITLE
CSV inference reads in the whole file to memory, regardless of row limit

### ISSUE THREAD

**Issue by kmitchener** [apache/arrow-datafusion#3658]
**Describe the bug**
When inferring the schema, the complete CSV will be read into memory even if you leave it at the default 1000 rows to infer from.

**To Reproduce**

```rust
let df = ctx.read_csv("./test/", CsvReadOptions::new()).await?;
```

Happens here:
https://github.com/apache/arrow-datafusion/blob/master/datafusion/core/src/datasource/file_format/csv.rs#L109

**Expected behavior**
It should read in only as much data as it needs for the given row count to infer data from.

**Additional context**

**Comment by tustvold** [comment]
This should just be a case of hooking up https://github.com/apache/arrow-datafusion/pull/2936. I think the inference code dates from a time before that
