### ISSUE TITLE
Add simplification rules for the `Modulo` operator

### ISSUE THREAD

**Issue by HaoYang670** [apache/arrow-datafusion#3664]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

Simplify the modulus expression: `A % B`

**Describe the solution you'd like**
This could be similar to the `Divide` operator: https://github.com/apache/arrow-datafusion/blob/master/datafusion/optimizer/src/simplify_expressions.rs#L774-L791

**Describe alternatives you've considered**

**Additional context**

**Comment by askoa** [comment]
I'll pick this up.

**Comment by askoa** [comment]
I could think of below rules. Is there anything else to be added?

```
A % 1 = 0
A % A = 0
A % 0 = DivByZeroErr
```

**Comment by HaoYang670** [comment]
Thank you, @askoa, for picking this. The rules you listed are good. 
For `A % A`, we should think more, because when `A` contains `0` the result will be `DivByZeroErr`; when `A` contains `null`, the result will be `Null`; and in other cases, the result is `0`. 
\My opinion is that we could not add `A % A` rules now.
