### ISSUE TITLE
using Decimal(0) make system panicked

### ISSUE THREAD

**Issue by waitingkuo** [apache/arrow-datafusion#3665]
**Describe the bug**

**To Reproduce**

```bash
DataFusion CLI v12.0.0
❯ select 1::decimal(0);
thread 'main' panicked at 'attempt to subtract with overflow', /Users/willy/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow-23.0.0/src/datatypes/datatype.rs:1001:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Expected behavior**

show something like this
```bash
❯ select 10::decimal(1);
ArrowError(InvalidArgumentError("10 is too large to store in a Decimal128 of precision 1. Max is 9"))
```

**Additional context**

**Comment by HaoYang670** [comment]
This is a bug in the `validate_decimal_precision` in arrow-rs: https://github.com/apache/arrow-rs/blob/master/arrow-data/src/decimal.rs#L755-L756

Should we file an issue in arrow-rs?

cc @liukun4515

**Comment by alamb** [comment]
We should file a bug (and even better a fix!) upstream 👍

**Comment by liukun4515** [comment]
> This is a bug in the `validate_decimal_precision` in arrow-rs: https://github.com/apache/arrow-rs/blob/master/arrow-data/src/decimal.rs#L755-L756
> 
> Should we file an issue in arrow-rs?
> 
> cc @liukun4515

@HaoYang670 @waitingkuo I think we should file a issue or fix to check the precision which should be greater than 0

**Comment by HaoYang670** [comment]
BTW, we could use `nonZeroU8` to represent `precision`: https://doc.rust-lang.org/std/num/struct.NonZeroU8.html

**Comment by HaoYang670** [comment]
We can fix this bug without waiting for arrow-rs. I will file a PR.

**Comment by waitingkuo** [comment]
LGTM, thank you @HaoYang670
