### ISSUE TITLE
Proposal: Rename MergeExec 

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#369]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
The name `MergeExec` has long confused me. 

The name `MergeExec` implies to me that its purpose is to "merge sorted streams" into another sorted stream

However,   `MergeExec` does something more like `UNION ALL` of streams into a single stream, combining the input streams in some arbitrary output order. Something that looks to me like an actual "merge" operation is described in  https://github.com/apache/arrow-datafusion/issues/362. 

**Describe the solution you'd like**
I propose renaming  `MergeExec` to `UnionToSingleStreamExec` to make it clearer

It could also potentially combined with the existing `UnionExec` (which preserves partitioning) as another flag

**Describe alternatives you've considered**
As this would be a fairly invasive (and backwards incompatible change) leaving the current naming is also a possibility.

**Comment by alamb** [comment]
Do you have any thoughts on this @Dandandan  @jorgecarleitao @andygrove @returnString ?

**Comment by jorgecarleitao** [comment]
agree 👍

**Comment by andygrove** [comment]
I agree that we should change the name. If I had to pick a new name I would probably be thinking more along the lines of `CoalescePartitionsExec` since this is a specialized form of repartitioning. That said, I don't have a strong opinion on the new name.

**Comment by Dandandan** [comment]
I agree that the name is confusing. Union would be confusing too, as a UNION all doesn't actually combine the partitions.

`CoalescePartitionsExec` sounds great to me :+1:

**Comment by Dandandan** [comment]
Another thing which makes some sense to me is making this a special case of `RepartitionExec` with a `SinglePartition` option (next to round robin / hash)

**Comment by alamb** [comment]
I like`CoalescePartitionsExec` 👍
