### ISSUE TITLE
support unsigned numeric data type in UnwrapCastInBinaryComparison rule

### ISSUE THREAD

**Issue by liukun4515** [apache/arrow-datafusion#3702]
This plan doesn't look ideal to me -- since `col_int32` is int32 I think the exprs could be rewritten to 

```
CASE WHEN #test.col_int32 > Int32(0) THEN Int32(1) ELSE Int32(0) END
```

Could be done as a follow on PR for sure

_Originally posted by @alamb in https://github.com/apache/arrow-datafusion/pull/3699#discussion_r986810683_

**Comment by alamb** [comment]
To implement this, as @liukun4515  notes, the `UnwrapCastInBinaryComparison` code just needs to be extended to support unsigned types as well

**Comment by alamb** [comment]
I am working on this feature as we need it for IOx

**Comment by liukun4515** [comment]
> am working on this feature as we need

look forward your pr

**Comment by alamb** [comment]
PR is now ready for review https://github.com/apache/arrow-datafusion/pull/4149
