### ISSUE TITLE
Optimizer rule 'projection_push_down' failed due to unexpected error: Error during planning: Aggregate schema has wrong number of fields. Expected 3 got 8

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#3704]
**Describe the bug**
There was a recent regression causing several test failures in a test suite that we use with Dask SQL.

```
Optimizer rule 'projection_push_down' failed due to unexpected error: Error during planning: Aggregate schema has wrong number of fields. Expected 3 got 8
```

**To Reproduce**

```rust
#[test]
fn case_when_aggregate() -> Result<()> {
    let sql = "SELECT col_utf8, SUM(CASE WHEN col_int32 > 0 THEN 1 ELSE 0 END) AS n FROM test GROUP BY col_utf8";
    let plan = test_sql(sql)?;
    let expected = "";
    assert_eq!(expected, format!("{:?}", plan));
    Ok(())
}
```

Fails with

```
Error: Internal("Optimizer rule 'projection_push_down' failed due to unexpected error: 
  Error during planning: Aggregate schema has wrong number of fields. Expected 1 got 2")

```

**Expected behavior**
Should not see this error

**Additional context**
None

**Comment by alamb** [comment]
For what it is worth, I am working through some errors upgrading IOx to use the latest datafusion (see  https://github.com/influxdata/influxdb_iox/pull/5792) and I am also hitting errors related to type coercion as well. I will file and fix issues in DataFusion if appropriate when I have debugged it

**Comment by andygrove** [comment]
Related: https://github.com/apache/arrow-datafusion/pull/3706

**Comment by alamb** [comment]
Starting to look into this

**Comment by alamb** [comment]
I believe I have found the root cause. Fix incoming

**Comment by alamb** [comment]
Here is a proposed fix: https://github.com/apache/arrow-datafusion/pull/3710

It seems to have some sort of other planning regression (something is no longer simplified). I am about to run out of time tonight but I will continue investigation tomorrow
