### ISSUE TITLE
Add missing functions to python

### ISSUE THREAD

**Issue by jorgecarleitao** [apache/arrow-datafusion#374]
All functions to build logical plans are [here](https://github.com/apache/arrow-datafusion/blob/master/datafusion/src/prelude.rs). 

Let's add them to the python bindings, [here](https://github.com/apache/arrow-datafusion/blob/master/python/src/functions.rs).

**Comment by jgoday** [comment]
@jorgecarleitao PR #388 tries to implement this issue.

If it is correct, should I update the PR to include more python test with the new exported functions ?

**Comment by jorgecarleitao** [comment]
Closed in #388
