### ISSUE TITLE
[User Guide] Add `EXPLAIN` to SQL reference

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#3755]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
I wanted to lookup the syntax for `EXPLAIN` but I couldn't find it in the user guide.

**Describe the solution you'd like**
Add `EXPLAIN` to SQL reference

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by unvalley** [comment]
I'll take a look!
