### ISSUE TITLE
SortExec Multiple Partition Support

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-datafusion#377]
SortExec currently returns an error if it is given an input ExecutionPlan with more than 1 partition. However, I would expect it to just sort each partition independently, preserving the input partitioning. These partitions could then be stitched together with an order preserving merge operator, which I happen to be implementing as part of #362

**Comment by e-dard** [comment]
@tustvold was this resolved with https://github.com/apache/arrow-datafusion/pull/378?
