### ISSUE TITLE
benchmarks fail against parquet with decimal types

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#3772]
**Describe the bug**

```
Error: ArrowError(ExternalError(ArrowError(ExternalError(Execution("Arrow error: External error: Execution error: Arrow error: External error: Execution error: Failed to map column projection for field l_quantity. Incompatible data types Decimal128(11, 2) and Decimal128(15, 2)")))))
```

**To Reproduce**

```
./target/release/tpch benchmark datafusion --query 1 --path /mnt/bigdata/tpch/sf10-parquet/ --format parquet --iterations 1 -n 48
```

**Expected behavior**

**Additional context**
The same benchmarks work fine in Apache Spark

**Comment by alamb** [comment]
FYI @liukun4515

**Comment by liukun4515** [comment]
Do we have the logical plan for this sql? @andygrove 
Maybe there are some errors in type coercision

**Comment by Dandandan** [comment]
@andygrove I think this can be closed?

**Comment by alamb** [comment]
I have run all the TPCH queries successfully recently with the benchmark runner, so closing this. Let's reopen it if necessary
