### ISSUE TITLE
Make `Expr` enum consistent with `LogicalPlan` by using structs for each variant

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#3807]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
See the discussion at https://github.com/apache/arrow-datafusion/issues/2175 for background context, but the basic issue is that there are different styles between `LogicalPlan` and `Expr`.

## LogicalPlan

Each variant in LogicalPlan wraps a struct. The structs typically have `try_new` methods with some validation logic.

```rust
pub enum LogicalPlan {
    Projection(Projection),
    Filter(Filter),
    ..
}
```

## Expr

Expr has a mixed style. Some variants wrap structs and some do not.

```rust
pub enum Expr {
    Alias(Box<Expr>, String),
    Column(Column),
    Between {
        /// The value to compare
        expr: Box<Expr>,
        /// Whether the expression is negated
        negated: bool,
        /// The low end of the range
        low: Box<Expr>,
        /// The high end of the range
        high: Box<Expr>,
    },
    Like {
        negated: bool,
        expr: Box<Expr>,
        pattern: Box<Expr>,
        escape_char: Option<char>,
    },
```

**Describe the solution you'd like**
We would like each variant in `Expr` to wrap a struct (except perhaps for the very simple ones that contain one or two items) and add `new` and/or `try_new` methods to those structs as appropriate.

- [x] https://github.com/apache/arrow-datafusion/pull/3757
- [x] BinaryExpr - https://github.com/apache/arrow-datafusion/pull/3835
- [x] Like / ILike / SimilarTo - https://github.com/apache/arrow-datafusion/pull/3836
- [x] GetIndexedField - https://github.com/apache/arrow-datafusion/pull/3860
- [x] Between
- [x] Cast - https://github.com/apache/arrow-datafusion/pull/3931
- [x] TryCast
- [x] Sort
- [x] ScalarFunction
- [x] ScalarUDF
- [x] AggregateFunction
- [x] AggregateUDF
- [x] WindowFunction
- [x] InList
- [x] Exists
- [x] InSubquery
- [x] PlaceHolder

**Describe alternatives you've considered**
Do nothing

**Additional context**
None

**Comment by jackwener** [comment]
I prepare to finish this task. I invite some contributor, if you are interested in this issue.
Please reply the part which you want to do.

**Comment by SkyFan2002** [comment]
> I prepare to finish this task. I invite some contributor, if you are interested in this issue. Please reply the part which you want to do.

Hi, I am new to this project. Can I help with `InList`?

**Comment by jackwener** [comment]
> Hi, I am new to this project. Can I help with InList?
It's OK, Thank you @SkyFan2002

**Comment by QuenKar** [comment]
Hello，I‘m a noob to this project and interested in Exists part.May I have a try?

**Comment by jackwener** [comment]
> Hello，I‘m a noob to this project and interested in Exists part.May I have a try?

It's OK, Thank you @QuenKar

**Comment by gitccl** [comment]
Hi, I'd like to try InSubquery.

**Comment by jackwener** [comment]
> Hi, I'd like to try InSubquery.

@gitccl welcome, thanks

**Comment by jackwener** [comment]
Already finish it, thanks everyone!❤️

**Comment by alamb** [comment]
Pretty amazing @jackwener and everyone else who helped out here -- very nice
