### ISSUE TITLE
chrono crate : specify 0.4.22 as the minimum version due to spurious build failures

### ISSUE THREAD

**Issue by stormasm** [apache/arrow-datafusion#3827]
Compiling datafusion-benchmarks v13.0.0 (/Users/ma/j/tmp06/arrow-datafusion/benchmarks)
error[E0277]: the trait bound `chrono::datetime::DateTime<chrono::offset::utc::Utc>: std::default::Default` is not satisfied
   --> benchmarks/src/bin/parquet_filter_pushdown.rs:284:24
    |
284 |         last_modified: Default::default(),
    |                        ^^^^^^^^^^^^^^^^ the trait `std::default::Default` is not implemented for `chrono::datetime::DateTime<chrono::offset::utc::Utc>`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `datafusion-benchmarks` due to previous error

**Comment by andygrove** [comment]
I can reproduce this on mac but not linux

**Comment by andygrove** [comment]
I ran `cargo update`:

```
    Updating chrono v0.4.19 -> v0.4.22
```

This resolved it, so we probably need to specify 0.4.22 as the minimum version

**Comment by stormasm** [comment]
I blew everything away and started over and this time I no longer see the issue...

**Comment by stormasm** [comment]
I love rust !

The only place we check in a Cargo.lock file is here:
datafusion-cli/Cargo.lock

Because we do not check in a Cargo.lock file anywhere else
the error that I was seeing shows up...

Because my Cargo.lock file had chrono version 0.4.19

Once you blow target away and start over it reproduces (I think)
what @andygrove did with the cargo update command...

So some developers will see my error and some developers will not...

**Comment by alamb** [comment]
We should increase the declared minimum version of chrono in Datafusion's Cargo.toml to be "0.4.22" if we use features that appear only in versions 0.4.22 or later

https://github.com/apache/arrow-datafusion/search?l=TOML&q=chrono

**Comment by alamb** [comment]
Proposed fix https://github.com/apache/arrow-datafusion/pull/3959
