### ISSUE TITLE
Support parquet page filtering for more types: String, Binary(Decimal), Int96

### ISSUE THREAD

**Issue by Ted-Jiang** [apache/arrow-datafusion#3833]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

https://github.com/apache/arrow-datafusion/blob/144dcca360fd95c9bf33f38555fffcb2338bd2c1/datafusion/core/src/physical_plan/file_format/parquet.rs#L853-L857

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
Here is a PR for filtering on strings: https://github.com/apache/arrow-datafusion/pull/4132

**Comment by alamb** [comment]
Int96 appears to be the only unsupported type left

https://github.com/apache/arrow-datafusion/blob/ba73c8180ebd874614cabc33be8cbb0d1db52518/datafusion/core/src/physical_plan/file_format/parquet/page_filter.rs#L478-L481

I don't think Int96 is a widely used type nor supported for most other implementation -- thus I suggest we close this PR
