### ISSUE TITLE
[SQL] - Support cache/uncache table syntax

### ISSUE THREAD

**Issue by francis-du** [apache/arrow-datafusion#3842]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Currently, DataFrame can cache tables in memory, but cannot cache DataFusion tables or views through SQL. 

**Describe the solution you'd like**

I want to cache views and tables via `CACHE TABLE <table_name>` syntax like Spark SQL.At the same time, it is also necessary to support the `UNCACHE TABLE <table_name>` syntax to allow users to delete tables and views that do not require caching in memory.

Here are some docs about`CACHE TABLE` and `UNCACHE TABLE` in Spark SQL:

1.`CACHE TABLE`: https://docs.databricks.com/spark/latest/spark-sql/language-manual/sql-ref-syntax-aux-cache-cache-table.html

2.`UNCACHE TABLE`: https://docs.databricks.com/spark/latest/spark-sql/language-manual/sql-ref-syntax-aux-cache-uncache-table.html

**Describe alternatives you've considered**

I has been implemented the syntax in https://github.com/sqlparser-rs/sqlparser-rs/pull/670, I will support it in DataFusion next, if anyone is interested, welcome to discuss here.

**Comment by Dandandan** [comment]
How much different is this from `CREATE TABLE AS` (which currently also creates an in memory table)?

I am not necessarily against this, but I think the syntax is very spark-specific. We can do about the same currently?

**Comment by francis-du** [comment]
I looked at some code and I found `CREATE TABLE` is indeed possible to create an in-memory table. And also use`DROP TABLE` uncache in-memory table. 😢

**Comment by francis-du** [comment]
It doesn't look like it's necessary to support those syntax 😥
