### ISSUE TITLE
Implement statistics estimation for `FilterExec`

### ISSUE THREAD

**Issue by Dandandan** [apache/arrow-datafusion#3845]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
@isidentical implemented more statistics-rules for joins. When a `FilterExec` is between a `TableScan` however, we do not return a join estimation yet.

**Describe the solution you'd like**
We should provide an estimation based on the filterexpressions and statistics information that we have.

**Describe alternatives you've considered**

**Additional context**

**Comment by isidentical** [comment]
This was next on my list, so I'd be happy to work on it!

**Comment by Dandandan** [comment]
Awesome @isidentical I assigned you on this issue!

**Comment by Dandandan** [comment]
I would be very interested to see if we're getting any changes in TCP-H queries after this.

**Comment by isidentical** [comment]
Will be sure to include some benchmarks 👍🏻

**Comment by mingmwang** [comment]
@Dandandan I see there are couple of stats related issues opening,  is there an umbrella task/task lists? Or maybe we can tag all related issue as CBOStats ?

**Comment by alamb** [comment]
I think @isidentical  started a discussion on https://github.com/apache/arrow-datafusion/issues/3898 -- @mingmwang could you take a look? Perhaps it would be time to start socializing that ticket more broadly (I could send some email / slack messages to bring it to the community's attention)

**Comment by mingmwang** [comment]
@alamb Thanks, I will go through all the tickets and take a closer look at the current code base , I can help working on some 
of the open tasks.
