### ISSUE TITLE
Add collect statistics configuration 

### ISSUE THREAD

**Issue by Dandandan** [apache/arrow-datafusion#3847]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Currently, the collection of statistics is off by default. This means that any statistics-based optimization will not do anything.

**Describe the solution you'd like**
Introduce a setting for the collection of statistics, so it can be enabled by the user/consumer.

**Describe alternatives you've considered**

**Additional context**

**Comment by isidentical** [comment]
Hit the same thing on #3774 too 😄
