### ISSUE TITLE
Factorize common AND factors out of OR predicates to support filterPushDown as possible

### ISSUE THREAD

**Issue by Ted-Jiang** [apache/arrow-datafusion#3858]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
A predicate is of the from `p AND q1 OR p AND q2 ` it would help to factorize out the AND factor p, to the equivalent expression `p AND (q1 OR q2)`. This is useful when p contains predicates from just one col of a filter and can be pushed down

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
Sadly I had to revert https://github.com/apache/arrow-datafusion/pull/3859 so also reopening this one
