### ISSUE TITLE
Replace `Filter: Boolean(false)` with `EmptyRelation`

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#3864]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
I have a query that looks like this after optimization:

```
Union 
  Projection
    ...
  Projection
    Filter: Boolean(false)
      Aggregate
        Inner Join
          Inner Join
```        

**Describe the solution you'd like**
Remove everything under the `Filter` that is always false and replace with `EmptyRelation` so that we avoid executing the join and aggregate.

**Describe alternatives you've considered**

**Additional context**

**Comment by mingmwang** [comment]
We can have two general rules: `FoldFilters` and `EmptyRelationPropagation`.
`FoldFilters` can remove the filters which can be evaluated trivially. If `Filter` condition is alway false,  replace it with an `EmptyRelation`

`EmptyRelationPropagation` can propagate the empty relation up to the tree, for example, inner join with `EmptyRelation` can return `EmptyRelation`.

**Comment by mingmwang** [comment]
@andygrove Looks like there is already a rule `EliminateFilter` for this purpose.

**Comment by alamb** [comment]
Perhaps the changes in https://github.com/apache/arrow-datafusion/pull/3841 from @Dandandan  made it possible to simplify the filter

Perhaps we could solve this issue by adding another  run of `EliminateFilter`  at the end of the list in datafusion/optimizer/src/optimizer.rs

**Comment by alamb** [comment]
@andygrove  can you share a reproducer? We can then add it to the regression tests to make sure the empty filter is indeed eliminated and doesn't come back in

**Comment by jackwener** [comment]
Datafusion only can propagate `EmptyRelation` just `optimizer_config.max_passes` times. Because we depend on multi-passes optimization to multiply elimination.

In other words, we currently don't  have really `EmptyRelationPropagation`.

We can reproduce it. 

 After 3 optimizations, the plan can continue to be eliminated.

```sql
 CREATE TABLE IF NOT EXISTS t1 AS VALUES(1,'HELLO'),(12,'DATAFUSION');
 CREATE TABLE IF NOT EXISTS t2 AS VALUES(1,'HELLO'),(12,'DATAFUSION');
 CREATE TABLE IF NOT EXISTS t3 AS VALUES(1,'HELLO'),(12,'DATAFUSION');

explain verbose  select column1 from t1 join ( select column1 from t2 join (select column1 from t3 where false ) as ta2 on t2.column1 = ta2.column1 ) as ta1 on t1.column1 = ta1.column1;
```

The `root` cause is currently optimization is incomplete. We just have top-down optimize, we don't have bottom-up optimize.

If we have bottom-up optimize, we can do `EmptyRelationPropagation` in once optimization.

**Comment by jackwener** [comment]
So I believe that it's a future ticket, it should fix after we have bottom-up optimization. like #3972
