### ISSUE TITLE
CI checks stuck in queued mode

### ISSUE THREAD

**Issue by comphead** [apache/arrow-datafusion#3883]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
CI checks stuck in queued mode. Last 3 PRs blocked

**Describe the solution you'd like**
Fix CI checks

**Describe alternatives you've considered**
None
**Additional context**
None

**Comment by alamb** [comment]
I believe the issue is that the entire apache github organization shares the same pool of github CI workers. And thus sometimes there is a queue.

It will likely clear (but it will take some time to do so) 😭

**Comment by alamb** [comment]
The queue appears to have cleared now and the jobs have run. Closing this ticket
