### ISSUE TITLE
`count(Literal)` gives wrong column name

### ISSUE THREAD

**Issue by HaoYang670** [apache/arrow-datafusion#3891]
**Describe the bug**

**To Reproduce**
Tested on the latest datafusion-cli
```sql
❯ select count(2.2);
+-----------------+
| COUNT(UInt8(1)) |
+-----------------+
| 1               |
+-----------------+
```
**Expected behavior**
I'd like the column name to be
```
COUNT(Float64(2.2))
```

**Additional context**

**Comment by comphead** [comment]
There is a hardcoded value in `COUNT_STAR_EXPANSION` that expands to `pub const COUNT_STAR_EXPANSION: ScalarValue = ScalarValue::UInt8(Some(1));`, @andygrove should we fixed this as above?
