### ISSUE TITLE
Simplify `a AND a` and `a OR a`.

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#3895]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Some features like https://github.com/apache/arrow-datafusion/pull/3859 may find / introduce seemingly nonsensical predicates like `a AND a` -- in this case the expression simplifier should remove them. 

**Describe the solution you'd like**
Add rewrite rules to rewrite
`a AND a` --> `a`
`a OR a` --> `a`

Rewrite rules are https://github.com/apache/arrow-datafusion/blob/feff5dc/datafusion/optimizer/src/simplify_expressions.rs#L793

**Comment by alamb** [comment]
Marking as good first issue as there are many examples and existing tests to follow

**Comment by retikulum** [comment]
I will take a look!

**Comment by alamb** [comment]
As pointed out by @src255 this is already implemented https://github.com/apache/arrow-datafusion/pull/3915#issuecomment-1287373139 🤔
