### ISSUE TITLE
[DOC] - There are unsupported DDL in the official documentation

### ISSUE THREAD

**Issue by francis-du** [apache/arrow-datafusion#3904]
**Describe the bug**

Found an error when I run this  DDL:

```sql
CREATE TABLE valuetable IF NOT EXISTS AS VALUES(1,'HELLO'),(12,'DATAFUSION'); 
```
Error:

![image](https://user-images.githubusercontent.com/25944814/196922923-769fa937-1adb-4c21-90c1-fa2d562e1a77.png)

Docs: https://arrow.apache.org/datafusion/user-guide/sql/ddl.html

**Comment by alamb** [comment]
I think the right syntax is CREATE TABLE IF NOT EXISTST

```sql
❯ CREATE TABLE IF NOT EXISTS valuetable AS VALUES(1,'HELLO'),(12,'DATAFUSION'); 
0 rows in set. Query took 0.003 seconds.
```

**Comment by jackwener** [comment]
```
CREATE [OR REPLACE] TABLE [IF NOT EXISTS] table_name AS [SELECT | VALUES LIST];
```

Doc is right, you have missed `table_name`.

**Comment by alamb** [comment]
I think the problem is with this example from https://arrow.apache.org/datafusion/user-guide/sql/ddl.html

> CREATE TABLE valuetable IF NOT EXISTS AS VALUES(1,'HELLO'),(12,'DATAFUSION');
