### ISSUE TITLE
Better api for setting `ConfigOptions` from SessionContext

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#3908]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Related to #3887 

I want to set configuration options given a session context. Right now I need to do it like 🤮 

```rust
        let session_ctx = SessionContext::new();

        {
            // lock scope
            let state = session_ctx.state.write();
            let mut config_options = state.config.config_options.write();
            config_options.set_bool(OPT_PARQUET_PUSHDOWN_FILTERS, true);
            config_options.set_bool(OPT_PARQUET_REORDER_FILTERS, true);
        }
```

**Describe the solution you'd like**

I would like an API like this:
```rust
        let session_ctx = SessionContext::new()
          .with_bool(OPT_PARQUET_PUSHDOWN_FILTERS, true)
          .with_bool(OPT_PARQUET_REORDER_FILTERS, true);
```

As well as
```rust
        let session_ctx = SessionContext::new();
        session_ctx.set_bool(OPT_PARQUET_PUSHDOWN_FILTERS, true);
        session_ctx.set_bool(OPT_PARQUET_REORDER_FILTERS, true);
```                                                                                      

**Describe alternatives you've considered**

**Additional context**

**Comment by comphead** [comment]
@alamb I'm wondering if you ok with current working alternative

`
    let ctx = SessionContext::with_config(SessionConfig::new().set_bool("key", true).set_bool("key2", false));
`

**Comment by alamb** [comment]
@comphead it is probably OK. 

I don't plan to work on the ConfigOptions any more once I consolidate the parquet options. I guess I'll see if others have some ideas on how to make the API nicer

**Comment by alamb** [comment]
Let's discuss this in the larger context of https://github.com/apache/arrow-datafusion/issues/4349
