### ISSUE TITLE
Support inlining view / dataframes logical plan

### ISSUE THREAD

**Issue by Dandandan** [apache/arrow-datafusion#3913]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
DataFusion supports filter/limit/projection pushdown for views and dataframes via the tableprovider interface after https://github.com/apache/arrow-datafusion/pull/3905 . Inlining the LogicalPlan (as an optimization rule) would bring more opportunities for optimizations.

**Describe the solution you'd like**
Support optimization rule that inlines view and dataframes.
A method could be added to the tableprovider trait that returns a `Option<LogicalPlan>`. This can be used by an optimization rule (e.g. `InlineTableProvider`).

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
I vaguely remember a discussion about this topic though I can't find it again now -- perhaps @HaoYang670 ?

**Comment by alamb** [comment]
🎉
