### ISSUE TITLE
Implement serialization for `ScalarValue::FixedSizeBinary`

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#3928]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

@maxburke's PR added `ScalarFixedSizeBinary` support:  https://github.com/apache/arrow-datafusion/pull/3911 

However, it did not implement the serialization code to send `ScalarValue::FixedSizeBinary` over the network 

**Describe the solution you'd like**

Fill out the code in datafusion/proto/src/to_proto.rs

```rust
            scalar::ScalarValue::FixedSizeBinary(_, _) => {
                return Err(Error::General(
                    "FixedSizeBinary is not yet implemented".to_owned(),
                ))
            }
```

And add a test for round trip serialization

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
Should be a good first issue as there are plenty of other examples to follow along

**Comment by retikulum** [comment]
It looks interesting. Can you assign it to me?

**Comment by alamb** [comment]
See also- https://github.com/apache/arrow-datafusion/pull/3612 - the serialization code is a bit of a mess now but hopefully we can get it better
