### ISSUE TITLE
Update the Roadmap.md

### ISSUE THREAD

**Issue by HaoYang670** [apache/arrow-datafusion#3935]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
```
Having Ballista as part of the DataFusion codebase helps ensure that DataFusion remains suitable for distributed compute. 
...
```
Should we update this part as Ballista has been a top-level repo ?

link: https://github.com/apache/arrow-datafusion/blob/master/docs/source/contributor-guide/roadmap.md?plain=1#L100-L102

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by HaoYang670** [comment]
cc @andygrove.

**Comment by alamb** [comment]
It would be great to update the roadmap

**Comment by jackwener** [comment]
We also can consider other part, some content is outdate.
