### ISSUE TITLE
Move physical plan serde from Ballista to DataFusion

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#3949]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
`datafusion-proto` supports logical plan serde, but physical plan serde is in Ballista.

**Describe the solution you'd like**
Move most physical plan serde code to DataFusion. Ballista will still need serde code for its own physical operators that are not part of DataFusion.

**Describe alternatives you've considered**
None

**Additional context**
See discussion at https://github.com/apache/arrow-datafusion/pull/3907#discussion_r1003700588

**Comment by ygf11** [comment]
Similar issue: 
* https://github.com/apache/arrow-datafusion/issues/3257

Happy to see it move on.

**Comment by Kikkon** [comment]
🤓 I'm not that experienced in Ballista and DataFusion but this issue seems not to be complicate ? May I have a try ?
