### ISSUE TITLE
Incorrect results with parquet filtering pushdown enabled

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#4005]
**Describe the bug**
DataFusion gets different answers when parquet pushdown is enabled

NOTE that pushdown filtering is not enabled by default (as we are still working on it) so this issue will not likely affect users:

**To Reproduce**
1. Download data from 
[repro.zip](https://github.com/apache/arrow-datafusion/files/9890904/repro.zip)
2. Run datafusion CLI 

The query run is
```sql
select count(*) from foo where container = 'backend_container_0' OR pod = 'aqcathnxqsphdhgjtgvxsfyiwbmhlmg';
```

**Expected behavior**
Same answer should be produced with and without page index filtering enabled. However, the answers are different

Without filter pushdown `39982` rows are produced

```shell
$ DATAFUSION_EXECUTION_PARQUET_PUSHDOWN_FILTERS=false datafusion-cli -f script.sql
...
+-----------------+
| COUNT(UInt8(1)) |
+-----------------+
| 39982           |
+-----------------+
```

With it enabled:

```shell
DATAFUSION_EXECUTION_PARQUET_PUSHDOWN_FILTERS=true datafusion-cli -f script.sql
+-----------------+
| COUNT(UInt8(1)) |
+-----------------+
| 0               |
+-----------------+
1 row in set. Query took 0.004 seconds.
```

**Additional context**
Found by the test here https://github.com/apache/arrow-datafusion/pull/3976

**Comment by tustvold** [comment]
I wonder if this relates to pushing down an empty projection, it is possible there is a bug there, I don't remember seeing a test in arrow-rs for this

**Comment by tustvold** [comment]
I can reproduce this with

```
#[test]
    fn foo() {
        use arrow::datatypes::Int32Type as ArrowInt32Type;
        let file = File::open("/home/raphael/Downloads/data.parquet").unwrap();

        let builder = ParquetRecordBatchReaderBuilder::try_new(file).unwrap();
        let container_idx = builder.schema.index_of("container").unwrap();
        let projection =
            ProjectionMask::leaves(builder.parquet_schema(), [container_idx]);
        let p1 = ArrowPredicateFn::new(projection, |b| {
            arrow::compute::eq_dyn_utf8_scalar(
                as_dictionary_array::<ArrowInt32Type>(b.column(0)),
                "backend_container_0",
            )
        });

        let pod_idx = builder.schema.index_of("pod").unwrap();
        let projection = ProjectionMask::leaves(builder.parquet_schema(), [pod_idx]);
        let p2 = ArrowPredicateFn::new(projection, |b| {
            arrow::compute::eq_dyn_utf8_scalar(
                as_dictionary_array::<ArrowInt32Type>(b.column(0)),
                "aqcathnxqsphdhgjtgvxsfyiwbmhlmg",
            )
        });

        let filter = RowFilter::new(vec![Box::new(p1), Box::new(p2)]);

        let reader = builder.with_row_filter(filter).build().unwrap();
        let count: usize = reader.map(|x| x.unwrap().num_rows()).sum();
        assert_eq!(count, 39982)
    }
```

**Comment by tustvold** [comment]
Ok so the bug is that `DatafusionArrowPredicate` is assuming that `ProjectionMask` is order preserving, and so is not remapping the columns before passing them to `PhysicalExpr`. In reality `ProjectionMask` is not order preserving, and so the batch passed to `ArrowPredicate::evaluate` has columns in the order of the file's schema. In the case of this query, this results in it evaluating the predicates against the wrong columns, resulting in no rows that pass the predicate.

You can see this, by reordering the predicates in the query

```
select count(*) from foo where pod = 'aqcathnxqsphdhgjtgvxsfyiwbmhlmg' OR container = 'backend_container_0';
+-----------------+
| COUNT(UInt8(1)) |
+-----------------+
| 39982           |
+-----------------+
1 row in set. Query took 0.107 seconds.
```

This is likely also the issue behind #4006

**Comment by alamb** [comment]
Thank you for debugging / fixing this @tustvold
