### ISSUE TITLE
Internal error when parquet predicate pushdown is enabled "Error evaluating filter predicate:"

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#4006]
**Describe the bug**
DataFusion generates an error for some predicates when predicate pushdown is enabled

NOTE that pushdown filtering is not enabled by default (as we are still working on it) so this issue will not likely affect users:

**To Reproduce**
1. Download data from 
[repro.zip](https://github.com/apache/arrow-datafusion/files/9890904/repro.zip)
2. Run datafusion CLI 

The query run is
```sql
select count(*) from foo where request_duration_ns > 791684060 OR client_addr NOT in ('213.120.214.213');
```

**Expected behavior**
Same answer should be produced with and without row  filtering enabled. However, with row filtering an error is produced

```shell
datafusion-cli -f script.sql 
+-----------------+
| COUNT(UInt8(1)) |
+-----------------+
| 53819           |
+-----------------+
1 row in set. Query took 0.006 seconds.
```

With it enabled:

```shell
DATAFUSION_EXECUTION_PARQUET_PUSHDOWN_FILTERS=true datafusion-cli -f script.sql 
...
1 row in set. Query took 0.002 seconds.
ArrowError(ExternalError(Execution("Arrow error: External error: Arrow: underlying Arrow error: Compute error: Error evaluating filter predicate: Internal(\"Cannot evaluate binary expression Gt with types Utf8 and Int32\")")))
```

**Additional context**
Found by the test here https://github.com/apache/arrow-datafusion/pull/3976

**Comment by tustvold** [comment]
It looks like this has the same underlying cause as https://github.com/apache/arrow-datafusion/issues/4005#issuecomment-1295949956

Reordering the predicates works

```
❯ select count(*) from foo where client_addr NOT in ('213.120.214.213') OR request_duration_ns > 791684060;
+-----------------+
| COUNT(UInt8(1)) |
+-----------------+
| 53819           |
+-----------------+
1 row in set. Query took 0.247 seconds.
```
