### ISSUE TITLE
Use f64::total_cmp instead of OrderedFloat

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-datafusion#4051]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

DataFusion uses OrderedFloat in various places to order floats, this is different from arrow-rs which makes use of https://doc.rust-lang.org/std/primitive.f32.html#method.total_cmp.

**Describe the solution you'd like**

Moving away from OrderedFloat will:

* Ensure consistency
* Eliminate a dependency

**Describe alternatives you've considered**

**Additional context**

**Comment by comphead** [comment]
@tustvold please assign this to me

**Comment by comphead** [comment]
@tustvold Looks like `OrderedFloat` also implements `Hash` and `Eq` for floats.
`Hash` required for ScalarValue, `Eq` required for centroids. Do you want to make our own impl for Eq,Hash for `f64`?

**Comment by tustvold** [comment]
I added a HashValue trait in hash_utils.rs we can likely use / make public
