### ISSUE TITLE
Support `SET` command

### ISSUE THREAD

**Issue by waitingkuo** [apache/arrow-datafusion#4067]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

a `SET` command to change the value in `config_options`

**Describe the solution you'd like**

following what postgresql has except `[LOCAL]`
https://www.postgresql.org/docs/current/sql-set.html

assignment operator should support both `TO` and `=`
value should support `single quoted string` / `number` / `bool` / `non space separate string`

```bash
SET [VARIABLE] [TO | =] [VALUE | 'VALUE']
```

e.g. 
```bash
❯ set datafusion.execution.batch_size = 1;

```
```bash
❯ set datafusion.execution.coalesce_batches to 'false';
```

support alias `TIME ZONE` and `TIMEZONE` (same as postgrseql https://www.postgresql.org/docs/current/sql-set.html)
```bash
❯ set time zone = 1;
```

note that this should return error for now as discussed in https://github.com/apache/arrow-datafusion/issues/3148#issuecomment-1226105182
cc @avantgardnerio @alamb 

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
YES!  This will be awesome

Note there is still some nonsense related to Config settings (e.g. see https://github.com/apache/arrow-datafusion/pull/3885#pullrequestreview-1152448744) but I think supporting the `SET` command will provide us that much more reason to unify the configuration story
