### ISSUE TITLE
The percentile argument for ApproxPercentileCont must be Float64, not Decimal128(2, 1)

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#4103]
**Describe the bug**
I found this when testing https://github.com/apache/arrow-datafusion/pull/4102. `csv_query_approx_percentile_cont` fails with:

```
The percentile argument for ApproxPercentileCont must be Float64, not Decimal128(2, 1)
```

**To Reproduce**
Run tests in https://github.com/apache/arrow-datafusion/pull/4102

**Expected behavior**
I assume we need to add type coercion to convert function args to the correct type

**Additional context**

**Comment by comphead** [comment]
@andygrove please assign this to me

**Comment by comphead** [comment]
Local test to reproduce
```
#[tokio::test]
async fn test_approx_percentile_cont() -> Result<()> {
    let ctx = SessionContext::new();
    register_aggregate_csv(&ctx).await?;
    let sql = "SELECT approx_percentile_cont(c2, cast(1.0 as decimal(10,2))) FROM aggregate_test_100";
    execute_to_batches(&ctx, sql).await;

    Ok(())
}
```
