### ISSUE TITLE
Add CI check that configs.md is up-to-date

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#4108]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
We have a partially automated solution for keeping the configuration guide up-to-date.

When new configs are added in `config.rs`, we can run `cargo run --bin print_config_docs` to generate the markdown for the user guide and then manually copy it into `docs/source/user-guide/configs.md`.

We do not have CI checks to make sure that this is being done when new configs are added.

**Describe the solution you'd like**
In CI:

- Run `cargo run --bin print_config_docs`
- Check that there are no modified files

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by mvanschellebeeck** [comment]
Hey @andygrove, first time contributor here - happy to take this one!

Just to sanity check my thinking - does as run of [./dev/update_config_docs.sh](https://github.com/apache/arrow-datafusion/blob/master/dev/update_config_docs.sh) and then a new job that runs a diff in [workflows/dev.yml](https://github.com/apache/arrow-datafusion/blob/master/.github/workflows/dev.yml) make sense here?
