### ISSUE TITLE
Allow additional options when creating an external table

### ISSUE THREAD

**Issue by timvw** [apache/arrow-datafusion#4125]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
CREATE EXTERNAL TABLE should allow for custom (table type specific options).

Eg: For CSV the has_header and delimiter option are available but it's not possible to add custom options but it's not possible to specify the timestamp for loading a delta/iceberg table.

In spark this is possible via the generic [OPTIONS](https://spark.apache.org/docs/latest/sql-ref-syntax-ddl-create-table-datasource.html) parameter.

**Describe the solution you'd like**
Extend datafusion such that these options can be provided

```
CREATE EXTERNAL TABLE magic 
STORED AS DELTALAKE 
OPTIONS ( at='1667827882' )
LOCATION 's3://mybucket/magic'
```

**Describe alternatives you've considered**
We could not support this

**Additional context**
Relates to https://github.com/apache/arrow-datafusion/pull/3867

**Comment by avantgardnerio** [comment]
@timvw I think this is an excellent idea. Syntactically it's in line with postgres' [create external table](https://www.postgresql.org/docs/current/sql-createforeigntable.html) and I think it allows for run-time extensibility that is required if we want to have a healthy ecosystem of 3rd party TableProviders .

**Comment by timvw** [comment]
Ok, currently the syntax is slightly different, but happy to change that ;)

current: [ OPTIONS ( option='value' [, ... ] ) ]
postgres: [ OPTIONS ( option 'value' [, ... ] ) ]

**Comment by timvw** [comment]
Updated the code to be the same as postgres..
