### ISSUE TITLE
Optimize sort preserving merge

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#416]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
The new sort preserving merge operator, introduced in #379 likely has room for performance improvement.

**Describe the solution you'd like**
1. Create a benchmark for the merging operator 
2. Optimize / improve benchmark as appropriate

Here is a suggestion from @jhorstmann  https://github.com/apache/arrow-datafusion/pull/379/files#r637948151 as a separate ticket so it doesn't get lost:

For bigger number of partitions, storing the cursors in a BinaryHeap, sorted by their current item, would be beneficial.

A rust implementation of that approach can be seen in [this blog post and the first comment under it][1]. I have implemented the same approach in java before. I agree with @alamb though to make it work first, and then optimize later.

[1]: https://dev.to/creativcoder/merge-k-sorted-arrays-in-rust-1b2f

- [x] https://github.com/apache/arrow-datafusion/pull/3386
- [ ] https://github.com/apache/arrow-datafusion/issues/3609

**Comment by jorgecarleitao** [comment]
Also for inspiration: https://github.com/jorgecarleitao/arrow2/blob/main/src/compute/merge_sort/mod.rs

**Comment by tustvold** [comment]
Closing this ticket as I believe it is not tracking anything anymore.

SortPreservingMerge is now implemented as an n-way tournament tree making use of an order-preserving row encoding for multi-column sorts, and specialized cursors for single column sorts. I'm not aware of any major low-hanging fruit to make it run faster
