### ISSUE TITLE
Use arrow row format in GroupByHash rather than datafusion row format

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#4179]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Arrow now has a row format https://docs.rs/arrow/26.0.0/arrow/row/index.html that is both well documented and likely to get additional functionality (as it will be used for sorting, etc) 

It would be good to use that in DataFusion to benefit from upstream efforts including more type support as it is added

**Describe the solution you'd like**
It would be great to use the Arrow row format instead of `Compact` layout: https://github.com/apache/arrow-datafusion/blob/f2f846512ab032845de5dcee768a8a69ddf17eac/datafusion/row/src/layout.rs#L68

**Describe alternatives you've considered**

**Additional context**
As part of https://github.com/apache/arrow-datafusion/issues/3940 and https://github.com/apache/arrow-datafusion/issues/3941 I believe @crepererum  is working on this feature

cc @yjshen  and @tustvold

**Comment by crepererum** [comment]
Only for the group key, not for the group state.

**Comment by alamb** [comment]
I think we should probably file a follow on ticket for the group state (aka the aggregates) as I am not sure the existing row format is actually the right thing. I'll try and sort this out tomorrow when filing tickets
