### ISSUE TITLE
What happened for NDJSON support on CLI?

### ISSUE THREAD

**Issue by thomas-k-cameron** [apache/arrow-datafusion#4198]
**Describe the bug**
When I tried to run this script, it shown an error.
I believe that it worked before.

```sql
CREATE EXTERNAL TABLE IF NOT EXISTS asdf STORED AS NDJSON LOCATION 'some.ndjson';
SELECT * FROM asdf LIMIT 5;
```
> Execution("Unable to find factory for NDJSON")

contents of the file is
```json
{"asdf": 1}
{"asdf": 2}
```

**To Reproduce**
Use that file and run that script.

**Expected behavior**
It should create a table.

**Additional context**
> datafusion-cli 14.0.0

When I tried it with `STORED AS JSON` it still didn't work.
```sql
CREATE EXTERNAL TABLE IF NOT EXISTS asdf STORED AS JSON LOCATION 'some.ndjson';
SELECT * FROM asdf LIMIT 5;
```

**Comment by andygrove** [comment]
There have been changes in how table providers are registered so this is likely a regression. It would be good to get some regression tests added when we fix this.

I am guessing that the fix is simply to add `NDJSON` to this code in datafusion-cli:

```rust
fn create_runtime_env() -> Result<RuntimeEnv> {
    let mut table_factories: HashMap<String, Arc<dyn TableProviderFactory>> =
        HashMap::new();
    table_factories.insert(
        "csv".to_string(),
        Arc::new(ListingTableFactory::new(FileType::CSV)),
    );
    table_factories.insert(
        "parquet".to_string(),
        Arc::new(ListingTableFactory::new(FileType::PARQUET)),
    );
    table_factories.insert(
        "avro".to_string(),
        Arc::new(ListingTableFactory::new(FileType::AVRO)),
    );
    table_factories.insert(
        "json".to_string(),
        Arc::new(ListingTableFactory::new(FileType::JSON)),
    );
```

**Comment by thomas-k-cameron** [comment]
What do you think about adding several test-cases for the datafusion-cli to check if some features works as intended?

**Comment by timvw** [comment]
Seems to have been gone missing in https://github.com/apache/arrow-datafusion/pull/1010

**Comment by timvw** [comment]
Seems that this now available as regular "json" format:
https://github.com/apache/arrow-datafusion/blob/master/datafusion/core/src/datasource/file_format/json.rs#L46

The following works on my machine:
`DataFusion CLI v14.0.0
❯ create external table x stored as json location 'datafusion/core/tests/jsons/1.json';
0 rows in set. Query took 0.021 seconds.
❯ select * from x;
+-----+----------------+---------------+------+
| a   | b              | c             | d    |
+-----+----------------+---------------+------+
| 1   | [2, 1.3, -6.1] | [false, true] | 4    |
| -10 | [2, 1.3, -6.1] | [true, true]  | 4    |
| 2   | [2, , -6.1]    | [false, ]     | text |
|     |                |               |      |
+-----+----------------+---------------+------+
4 rows in set. Query took 0.030 seconds.
`

I have updated [PR-4427](https://github.com/apache/arrow-datafusion/pull/4227) such that both JSON and NDJSON are registered by default

**Comment by thomas-k-cameron** [comment]
I'm closing this issue because the problem has been fixed with [PR-4427](https://github.com/apache/arrow-datafusion/pull/4227).
