### ISSUE TITLE
Support for `!=` predicate in pruning predicates

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#420]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

While evaluating queries against data stored in containers / multiple files, it is helpful to prune entire files using statistics (see #363 for more details). DataFusion has this logic already for `==`, `<`, `<=`, `>` and `>=` operators in the pruning predicate. 

However, as @NGA-TRAN  noticed, there is no support for `!=` at the moment. 

https://github.com/apache/arrow-datafusion/blob/14f1eebef068a9e65f556ed74d2b6d98376c97f4/datafusion/src/physical_plan/parquet.rs#L683

**Describe the solution you'd like**
Add support and tests for `!=` in predicate pruning logic

**Comment by jgoday** [comment]
Can I try to solve this issue ?

If I understand it correctly, for the non equal predicate the expression should be pruned if the literal value does not fall between the min and max values, Am I right ?

**Comment by jgoday** [comment]
@alamb  Can I try to solve this issue ?

If I understand it correctly, for the non equal predicate the expression should be pruned if the literal value does not fall between the min and max values, Am I right ?
(I have already tried to implement it here (https://github.com/jgoday/arrow-datafusion/commit/3bb55a4464d23e2a4eb319aac1b51361f31c7485), I can make a PR if you approve it)

**Comment by alamb** [comment]
Thanks @jgoday ! That would be great 

For `!=` I think we would prune the container (aka return false or NULL) from the predicate if the constant value *did* fall within the min/max bounds.

**Comment by jgoday** [comment]
@alamb  I think that I express myself incorrectly :)
Created #544 PR.
