### ISSUE TITLE
Bug displaying fractional seconds in `IntervalMonthDayNano` 

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#4220]
thank you @Jefffrey 

there's a bug while displaying IntervalMonthDayNano
```bash
❯ select interval '0.0001 second';
+----------------------------------------------------+
| IntervalMonthDayNano("100000")                     |
+----------------------------------------------------+
| 0 years 0 mons 0 days 0 hours 0 mins 0.100000 secs |
+----------------------------------------------------+
1 row in set. Query took 0.002 seconds.
```
i checked the underline value it's correct `(month: 0, day: 0, nanos: 100000)`
i think this is the display issue

_Originally posted by @waitingkuo in https://github.com/apache/arrow-datafusion/pull/4186#pullrequestreview-1178643913_

**Comment by alamb** [comment]
Oh, I think this will be fixed by https://github.com/apache/arrow-rs/pull/3093 (in the next release after arrow 27.0.0)

**Comment by waitingkuo** [comment]
@alamb just found another bug while displaying fraction seconds

```bash
❯ select interval '-0.0001 second';
+-------------------------------------------------------+
| IntervalMonthDayNano("-100000")                       |
+-------------------------------------------------------+
| 0 years -1 mons -1 days 0 hours 0 mins 0.-100000 secs |
+-------------------------------------------------------+
1 row in set. Query took 0.002 seconds.
```
do you preferred submit another issue? I think it's arrow-rs's prettyprint issue as well

**Comment by waitingkuo** [comment]
@alamb i submit another issue since negative value isn't pure display issue

**Comment by Jefffrey** [comment]
Resolved by https://github.com/apache/arrow-rs/pull/3491 via arrow-rs v31 update https://github.com/apache/arrow-datafusion/pull/4927

```sql
DataFusion CLI v16.0.0
❯ select interval '-0.0001 second';
+--------------------------------------------------------+
| IntervalMonthDayNano("18446744073709451616")           |
+--------------------------------------------------------+
| 0 years 0 mons 0 days 0 hours 0 mins -0.000100000 secs |
+--------------------------------------------------------+
1 row in set. Query took 0.002 seconds.
❯
```

**Comment by alamb** [comment]
❤️
