### ISSUE TITLE
Clippy failures

### ISSUE THREAD

**Issue by mvanschellebeeck** [apache/arrow-datafusion#4245]
**Describe the bug**
Clippy returns errors after running ` ./dev/rust_lint.sh`

**To Reproduce**
` ./dev/rust_lint.sh`

**Comment by mvanschellebeeck** [comment]
Turns out I was running it on nightly - closing

**Comment by alamb** [comment]
FWIW the clippy stuff on nightly is often good to fix in advance because many eventually get promoted into stable and then we have to fix them.

Thanks again @mvanschellebeeck
