### ISSUE TITLE
Cargo test fail 

### ISSUE THREAD

**Issue by Ted-Jiang** [apache/arrow-datafusion#4253]
**Describe the bug**
run cargo test
```
error[E0609]: no field `alias` on type `&datafusion_expr::Union`
   --> datafusion/optimizer/src/propagate_empty_relation.rs:123:35
    |
123 | ...                   union.alias.clone(),
    |                             ^^^^^ unknown field
    |
    = note: available fields are: `inputs`, `schema`

```
Seems due to two recent two commits
https://github.com/apache/arrow-datafusion/commit/5de9709fadf1344baca1ed3e1f9a44e06dfa9a63
and 
https://github.com/apache/arrow-datafusion/commit/4dcf9857c0aad3d11050037bd46889a54f83a394

@jackwener  could mind take a look ?

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by jackwener** [comment]
#4250 #4252
