### ISSUE TITLE
`create external table` should fail to parse if syntax is incorrect

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#4262]
**Describe the bug**
When using `create external table` with csv files we can specify `with header row` to indicate that the file contains headers.

I ran this and forgot the syntax and omitted the word `row` and it did not process the header row and also did not fail and tell me that the syntax was incorrect.

**To Reproduce**

```
❯ create external table taxi_zone stored as csv with header location "/mnt/bigdata/nyctaxi/taxi+_zone_lookup.csv";
0 rows in set. Query took 0.008 seconds.
❯ select * from taxi_zone limit 10;
+------------+---------------+-------------------------+--------------+
| column_1   | column_2      | column_3                | column_4     |
+------------+---------------+-------------------------+--------------+
| LocationID | Borough       | Zone                    | service_zone |
| 1          | EWR           | Newark Airport          | EWR          |
| 2          | Queens        | Jamaica Bay             | Boro Zone    |
| 3          | Bronx         | Allerton/Pelham Gardens | Boro Zone    |
| 4          | Manhattan     | Alphabet City           | Yellow Zone  |
| 5          | Staten Island | Arden Heights           | Boro Zone    |
| 6          | Staten Island | Arrochar/Fort Wadsworth | Boro Zone    |
| 7          | Queens        | Astoria                 | Boro Zone    |
| 8          | Queens        | Astoria Park            | Boro Zone    |
| 9          | Queens        | Auburndale              | Boro Zone    |
+------------+---------------+-------------------------+--------------+
```

**Expected behavior**
SQL should have failed to parse.

**Additional context**
None

**Task list**
- [x] with header row (#4268)
- [ ] compression type
- [x] partitioned by (#4268)

**Comment by HaoYang670** [comment]
Same errors when parsing `compression type`:
```sql
DataFusion CLI v14.0.0
❯ create external table t5 stored as csv with header row compression location "../datafusion/core/tests/example.csv";
0 rows in set. Query took 0.007 seconds.
❯ select * from t5;
+---+---+---+
| a | b | c |
+---+---+---+
| 1 | 2 | 3 |
+---+---+---+
```

**Comment by HaoYang670** [comment]
Task lists:
- [ ] with header row
- [ ] compression by
- [ ] partitioned by

**Comment by HaoYang670** [comment]
By the way, we implement our own `consume_token` in the datafusion currently, Should we update the `comsume_token` function in sqlparser (which I mean `ignore case` https://github.com/apache/arrow-datafusion/pull/1237) so that we can remove the deplicate implementation in Datafusion.

**Comment by HaoYang670** [comment]
I've file an issue in the sqlparser to add `COMPRESSION` as a `Keyword`: https://github.com/sqlparser-rs/sqlparser-rs/issues/718

**Comment by HaoYang670** [comment]
Remove the `waiting-on-upstream` label because the `sqlparser-rs` has been updated to version 28.0.0
