### ISSUE TITLE
optimize `limit-full join` in the limit push down rule

### ISSUE THREAD

**Issue by liukun4515** [apache/arrow-datafusion#4275]
I think we can also optimize `limit - FULL Join` pattern. @jackwener

_Originally posted by @liukun4515 in https://github.com/apache/arrow-datafusion/issues/4257#issuecomment-1319729561_
      

Now we have support the `limit-left join` and `limit-right join`, I think the `limit-full join` also can be optimized

**Comment by jackwener** [comment]
We can do it after #4276

**Comment by liukun4515** [comment]
After careful consideration, this optimization has bug.
