### ISSUE TITLE
optimizer: support `unsigned <-> decimal` for unwrap_cast_in_comparion rule

### ISSUE THREAD

**Issue by liukun4515** [apache/arrow-datafusion#4287]
I found this with the test (which failed when it tried to invoke the arrow cast kernels for decimal <--> unsigned)

_Originally posted by @alamb in https://github.com/apache/arrow-datafusion/pull/4149#discussion_r1020749024_
      
after the next arrow-rs release including the https://github.com/apache/arrow-rs/pull/3106 commit

**Comment by liukun4515** [comment]
closed by https://github.com/apache/arrow-datafusion/pull/4634

**Comment by alamb** [comment]
🎉
