### ISSUE TITLE
LogicalPlan::inputs function should return the input plan for Explain enum

### ISSUE THREAD

**Issue by NGA-TRAN** [apache/arrow-datafusion#430]
**Describe the bug**
While trying to get `explain verbose` for a query, I have discovered that the physical plan displays almost nothing. After some investigation, the problem sounds like the [inputs function](https://github.com/apache/arrow-datafusion/blob/14f1eebef068a9e65f556ed74d2b6d98376c97f4/datafusion/src/logical_plan/plan.rs#L318) of `Explain` does not return its logical plan.

Here is the current code:
`LogicalPlan::Explain { .. } => vec![]`

It should have been:
`LogicalPlan::Explain { plan } => vec![plan]`
and the line should be moved above '// plans without inputs'

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by alamb** [comment]
Assigning to @NGA-TRAN  per her request
