### ISSUE TITLE
Revisit get_statistics_with_limit() method in datasource mod

### ISSUE THREAD

**Issue by mingmwang** [apache/arrow-datafusion#4323]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

This method will return `num_rows = 0` by default which is incorrect, should return Option.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
cc @isidentical
