### ISSUE TITLE
can't compare NULL type with NULL type

### ISSUE THREAD

**Issue by liukun4515** [apache/arrow-datafusion#4335]
**Describe the bug**

```
❯ select null and null;
ArrowError(ExternalError(Internal("Cannot evaluate binary expression And with types Null and Null")))
❯ select null or null;
ArrowError(ExternalError(Internal("Cannot evaluate binary expression Or with types Null and Null")))
```

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by liukun4515** [comment]
maybe has been fixed by https://github.com/apache/arrow-datafusion/pull/4242

**Comment by HaoYang670** [comment]
Two cases not supported yet:
```sql
❯ select null and null;
ArrowError(ExternalError(Internal("Cannot evaluate binary expression And with types Null and Null")))
❯ select null or null;
ArrowError(ExternalError(Internal("Cannot evaluate binary expression Or with types Null and Null")))
```
While on Postgre, we get nulls: https://onecompiler.com/postgresql

**Comment by jackwener** [comment]
Not supported is normal, the two types are not compatible.

**Comment by jackwener** [comment]
I can do it.

**Comment by melgenek** [comment]
@jackwener Hey! This issue is assigned to you. But I bumped into it and decided to give it a try, so I opened a pr https://github.com/apache/arrow-datafusion/pull/5158. I hope it is alright.

**Comment by jackwener** [comment]
Thank you @melgenek 
I try to fix it but meet problem, so I forgot it🥲, sorry for it.
