### ISSUE TITLE
Add serialization for entire LogicalPlans to datafusion-proto

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#4338]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

In order to serialize subquery expressions (https://github.com/apache/arrow-datafusion/issues/4337) we would need to serialize entire `LogicalPlans` which `datafusion-proto` does not do . 

**Describe the solution you'd like**
I would like to have the ability to serialize / deserialize `LogicalPlans` in the datafusion. I believe we can take a friendly look / downright copy this code from ballista:

https://github.com/apache/arrow-ballista/blob/acbdf608807697e72122a249c4bf7505274906d0/ballista/core/proto/datafusion.proto

**Describe alternatives you've considered**

**Additional context**
https://github.com/apache/arrow-datafusion/issues/4337

cc @andygrove @thinkharderdev @avantgardnerio 

I am marking this as "good first isseu" because I think it would mostly be an exercise in porting code and tests from one repo to another.

**Comment by l0kr** [comment]
Let me take a stab at this. @alamb anything changed since this task was created?

**Comment by alamb** [comment]
THanks @l0kr  -- sorry for the old ticket. I think this task is actually is mostly done https://github.com/apache/arrow-datafusion/tree/main/datafusion/proto/src/logical_plan

It would be very valuable if you were able to go through and fill out the various "Not implemented" in the plan conversion.

Closing
