### ISSUE TITLE
Panic with function `to_hex` 

### ISSUE THREAD

**Issue by ZuoTiJia** [apache/arrow-datafusion#4339]
**Describe the bug**
Panic with `to_hex(-1)`

**To Reproduce**
```
DataFusion CLI v14.0.0
❯ SELECT to_hex(-1);
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', .cargo/registry/src/github.com-1ecc6299db9ec823/datafusion-physical-expr-14.0.0/src/string_expressions.rs:579:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It looks like the problem is caused by using the `to_usize` method

https://github.com/apache/arrow-datafusion/blob/f4996b9f475b04bd260221f2a2bb074ab09b96be/datafusion/physical-expr/src/string_expressions.rs#L570-L584

**Comment by retikulum** [comment]
I agree that the error is in usage of `to_usize` method. I tried it with `to_isize` and it works correctly. If `isize` usage is OK then I will create a PR. What do you think @alamb 

![image](https://user-images.githubusercontent.com/15185911/204267935-5990f885-6eb3-4b05-b638-bd5ced0ae5a4.png)

**Comment by alamb** [comment]
Converting to `isize` will now cause issues for large positive numbers

What do you think about first trying `to_usize` and if that fails (returns an `Option`) then  try `to_isize`?

There is also `NATIVE` on `ArrowPrimtiveType` (as this function is already parameterized on `T` in theory we should be able to pick the correct conversion at compile time: https://docs.rs/arrow/27.0.0/arrow/array/trait.ArrowPrimitiveType.html
