### ISSUE TITLE
The CLI panics when passing an invalid `explain` query

### ISSUE THREAD

**Issue by HaoYang670** [apache/arrow-datafusion#4378]
**Describe the bug**
```sql
❯ explain explain select 1;
thread 'main' panicked at 'Explain can not be created from utils::from_expr', 
./datafusion/expr/src/utils.rs:573:13
```

Related code: https://github.com/apache/arrow-datafusion/blob/ba73c8180ebd874614cabc33be8cbb0d1db52518/datafusion/expr/src/utils.rs#L565-L578

**To Reproduce**

**Expected behavior**
Return an error instead of panicking.

**Additional context**

**Comment by comphead** [comment]
@HaoYang670 can I take this?

**Comment by HaoYang670** [comment]
Sure!

**Comment by HaoYang670** [comment]
I file https://github.com/sqlparser-rs/sqlparser-rs/issues/744 in the sqlparser-rs to fix this parsing bug
