### ISSUE TITLE
Enhancement: split the SQL `planner` into smaller modules

### ISSUE THREAD

**Issue by jackwener** [apache/arrow-datafusion#4392]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
The current planner file is too large, we can split it.

Like 
- query.rs
- select.rs
- set_expr.rs
- ....

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jackwener** [comment]
@mingmwang @andygrove @liukun4515 @alamb 
How do you think about it.

**Comment by jackwener** [comment]
Maybe we can add label `good-first-issue`

**Comment by alamb** [comment]
I agree this would be an excellent idea

The planner code I think is the code that translates from SQL statements to LogicalPlan: https://github.com/apache/arrow-datafusion/blob/a31b44eae236920d43ddd3ef7fadf8f9abf18976/datafusion/sql/src/planner.rs

**Comment by alamb** [comment]
I agree this would be a good first issue as it will be mostly a software engineering exercise and doesn't require much datafusion internals knowledge. Thank you @jackwener
