### ISSUE TITLE
Support `INSERT INTO` statement

### ISSUE THREAD

**Issue by mvanschellebeeck** [apache/arrow-datafusion#4397]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Support the `INSERT INTO` expression, e.g.
`INSERT INTO t1(e,c,b,d,a) VALUES(103,102,100,101,104)`

Executing with datafusion-cli:
```bash
DataFusion CLI v14.0.0
❯ CREATE TABLE abc AS VALUES (1,2,3), (4,5,6);
0 rows in set. Query took 0.004 seconds.
❯ SELECT * FROM abc;
+---------+---------+---------+
| column1 | column2 | column3 |
+---------+---------+---------+
| 1       | 2       | 3       |
| 4       | 5       | 6       |
+---------+---------+---------+
2 rows in set. Query took 0.005 seconds.
❯ INSERT INTO abc(column1, column2, column3) values (7,8,9);
NotImplemented("Unsupported SQL statement: Some(\"INSERT INTO abc (column1, column2, column3) VALUES (7, 8, 9)\")")
```

**Additional context**
The ability to insert values via the cli throughout a sessions forms the basis of a lot of [sqllogictests](https://www.sqlite.org/sqllogictest/file?name=test/select1.test&ci=tip) we want to incorporate into testing. See https://github.com/apache/arrow-datafusion/issues/4248

**Comment by alamb** [comment]
Anything involving arrow is going to be non ideal with multiple "INSERT INTO" statements. 

I suggest we implement support for `INSERT INTO` statements (and possibly https://github.com/apache/arrow-datafusion/issues/4396) as part of the test harness rather than in DataFusion itself
