### ISSUE TITLE
Helper to get "root" error

### ISSUE THREAD

**Issue by crepererum** [apache/arrow-datafusion#4435]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
It would be nice to get the typed "original" error, even when it is wrapped into a chain of `ExternalError`, `ArrowError`, `Arc` etc. The original error could be used to generate HTTP status codes in certain situations, e.g. "resource exhausted".

**Describe the solution you'd like**
```rust
impl DataFusionError {
    /// Get underlying error.
    ///
    /// This may be the same as `self`.
    pub fn find_root(&self) -> &Self {...}
}
```

**Describe alternatives you've considered**
String parsing? Sounds like bad code smell.

**Additional context**
See #4434 for improvements on the error generation. See #3940 for an application.

**Comment by crepererum** [comment]
FYI: I have an improved implementation of what we have in InfluxDB IOx. It just needs some clean ups and I'll file a PR for that.

**Comment by mingmwang** [comment]
There was a similar ticket I raised before.

https://github.com/apache/arrow-datafusion/issues/3410
