### ISSUE TITLE
Make AggregateFunction take a single argument

### ISSUE THREAD

**Issue by Dandandan** [apache/arrow-datafusion#444]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
This makes the representation of aggregate functions more correct, makes code dealing with aggregate functions more simple.

**Describe the solution you'd like**
Instead of `Vec<Expr>` use `Box<Expr>`

**Describe alternatives you've considered**
Keeping it as is.

**Additional context**

**Comment by jorgecarleitao** [comment]
fyi, the goal of being `Vec` was to allow multi-argument aggregates. An example is the person correlation between two columns (which can currently be implemented via a UDAF)

**Comment by Dandandan** [comment]
@jorgecarleitao Ah, yeah I think that makes sense. I'll just take care of it.

I think there is still some code (e.g. in Ballista protobuf I believe) that assumes only 1 argument, so when we are going to support that, it should be adapted.
