### ISSUE TITLE
How to register a http url to the `object_store`

### ISSUE THREAD

**Issue by elliot14A** [apache/arrow-datafusion#4491]
I was trying to register a http url to the `object_store` I was not able to find any examples on how to do it. I was able to successfully use and register s3 urls but, cannot find a way on how to use http.
`register_object` takes `scheme`, `host`, `object_store` as arguments can anybody help on how to pass http url to this function and register.

**Comment by tustvold** [comment]
What API does this HTTP server expose? Is it an object store?

**Comment by elliot14A** [comment]
Yes @tustvold !

**Comment by tustvold** [comment]
Depending on the API it exposes you should be able to do something like


```
let store = AmazonS3Builder::new()
    .with_bucket_name(...)
    .with_endpoint(...)
    .build()
    .unwrap();

ctx.runtime_env()
        .register_object_store("http", "", store);
```

**Comment by elliot14A** [comment]
For example if I have a http url `https://some_example.com/blogs.csv`

How should I use it to build `AmazonS3Builder`

**Comment by tustvold** [comment]
Currently DataFusion only supports querying from remote object stores, not arbitrary HTTP servers. I've created https://github.com/apache/arrow-rs/issues/3294 to track adding limited support for this, but DataFusion may require list support, which isn't possible on an arbitrary HTTP server AFAIK

**Comment by tustvold** [comment]
This was added in https://github.com/apache/arrow-rs/pull/3380 and will be included in the next release https://github.com/apache/arrow-rs/issues/3422
