### ISSUE TITLE
Implement column number / column type verification for sqllogictest

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#4499]
https://duckdb.org/dev/sqllogictest/result_verification

> The standard way of verifying results of queries is using the query statement, followed by the letter I times the number of columns that are expected in the result.

```sql
query II
SELECT 42, 84 UNION ALL SELECT 10, 20;
----
42	84
10	20
```

At the moment, the datafusion sqllogictest framework entirely ignores the number of `I` after the `query` command

The goal of this ticket is to update the framework (and tests) to error if the number of `I`s doesn't match the number of columns

**Comment by xxchan** [comment]
related issue: https://github.com/risinglightdb/sqllogictest-rs/issues/36

**Comment by alamb** [comment]
> I think having more than one type is useful.

I agree

As long as the `--complete` mode is able to populate the appropriate types automatically I am all for adding more specific types. It would be unfortunate if in order to write sqllogictests in datafusion you had to know a mapping from type to character code that has more than three entries :)

**Comment by melgenek** [comment]
Hi.

I opened a pr to define the sqllogictest output types and check them https://github.com/apache/arrow-datafusion/pull/5253.

The `--complete` doesn't work yet. There is a pr in `sqllogictest-rs` to make it work https://github.com/risinglightdb/sqllogictest-rs/pull/164.
