### ISSUE TITLE
Extract from timestamp doesn't support nanosecond

### ISSUE THREAD

**Issue by comphead** [apache/arrow-datafusion#4528]
**Describe the bug**
Faced this when worked with #4385 
`date_part` parses nanoseconds correctly
```
    test_expression!(
        "date_part('nanosecond', to_timestamp('2020-09-08T12:00:12.12345678+00:00'))",
        "12123456780"
    );
```
**To Reproduce**
```
     test_expression!(
         "EXTRACT(nanosecond FROM to_timestamp('2020-09-08T12:00:12.12345678+00:00'))",
         "1212345678"
     );

Invalid statement: sql parser error: Expected date/time field, found: nanosecond
```
**Expected behavior**
Should work

**Additional context**

**Comment by comphead** [comment]
Waiting for https://github.com/sqlparser-rs/sqlparser-rs/issues/748

**Comment by comphead** [comment]
@waitingkuo please assign this ticket to me

**Comment by comphead** [comment]
Depends on https://github.com/apache/arrow-datafusion/issues/4573

**Comment by comphead** [comment]
@waitingkuo reg to your PR https://github.com/sqlparser-rs/sqlparser-rs/issues/748 what sqlparser version it will go to? I just checked recently released 0.28, but there is no change yet

**Comment by waitingkuo** [comment]
@comphead  0.28 released right before this pr merged. we need 0.29 here

**Comment by comphead** [comment]
Depends on https://github.com/apache/arrow-datafusion/pull/4770

**Comment by alamb** [comment]
🎉
