### ISSUE TITLE
Move datafusion-substrait project into arrow-datafusion repo

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#4536]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
I would like to discuss moving the [datafusion-substrait](https://github.com/datafusion-contrib/datafusion-substrait) project into the main DataFusion repo.

The crate is receiving contributions from both NVIDIA and Greptimedb and is starting to have enough functionality to be useful.

It would be nice to be able to expose this to DataFusion's Python bindings as well.

**Describe the solution you'd like**
Move the crate into this repo. This will not impact any other DataFusion crates.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by andygrove** [comment]
@waynexia @nseekhao @Dandandan fyi

**Comment by waynexia** [comment]
Thanks for bringing this up @andygrove. DataFusion-Substrait is a beneficial integration to GreptimeDB. We use it to communicate logical plans between instances to achieve distributed execution. I'd like to contribute and migrate our [implementation](https://github.com/GreptimeTeam/greptimedb/tree/develop/src/common/substrait/src) to this official one :heart:

**Comment by alamb** [comment]
This seems like a reasonable idea to me -- it would be great to eventually migrate away from using protobuf serialization and instead use substrait (as that would allow even better ecosystem integration)

**Comment by mingmwang** [comment]
👍

**Comment by yahoNanJing** [comment]
👍
