### ISSUE TITLE
Add option to determine whether to convert identifiers 

### ISSUE THREAD

**Issue by jiacai2050** [apache/arrow-datafusion#4551]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

In CeresDB, we use datafusion for SQL execution, and find #1746 change unquoted identifiers to lowercase, which is a breaking change for us.

I agree with what #1746 does, but it there any possibilities to add an option to configure this? By default it will do the normalization, and users can choose not to do.

**Describe the solution you'd like**
Add on option to determine whether to convert identifiers.

If maintainers agree with this, I'd be glad to submit a PR.

**Describe alternatives you've considered**

**Additional context**
- https://github.com/CeresDB/ceresdb/issues/442

**Comment by jiacai2050** [comment]
@alamb Would you mind sharing your thoughts?

**Comment by alamb** [comment]
@jiacai2050 I think an option to control the case identifier behavior sounds very reasonable to me 👍

**Comment by jiacai2050** [comment]
Thanks, I will open a PR to add this.
