### ISSUE TITLE
Bump Datafusion sql-parser dependency to 0.28

### ISSUE THREAD

**Issue by comphead** [apache/arrow-datafusion#4573]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Bump sql-parser version from 0.27 to 0.28
https://github.com/sqlparser-rs/sqlparser-rs

**Describe the solution you'd like**
Change Datafusion sql-parser dependencies to 0.28 and fix all conflicts

**Describe alternatives you've considered**
Not doing this

**Additional context**
None

**Comment by jackwener** [comment]
#4568

**Comment by comphead** [comment]
@jackwener please close this issue as #4568 fixed that
