### ISSUE TITLE
Add need_data_exchange in the ExecutionPlan to indicate whether a physical operator needs data exchange

### ISSUE THREAD

**Issue by yahoNanJing** [apache/arrow-datafusion#4585]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Currently there's no explicit way to indicate whether an execution plan needs a data exchange, which is not so clear for the caller, like Ballista, to judge whether it's necessary to add an additional data exchange operator to deal with the shuffling.

**Describe the solution you'd like**

It's better to classify and clarify which execution plans needs data exchange explicitly. 

Currently there are 3 kinds of execution plan which needs data exchange
  1. RepartitionExec for changing the partition number between two operators
  2. CoalescePartitionsExec for collapsing all of the partitions into one without ordering guarantee
  3. SortPreservingMergeExec for collapsing all of the sorted partitions into one with ordering guarantee 

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
This might be a dumb question, but can this not be inferred from if the ExecutionPlan alters the partitioning of its input?

**Comment by alamb** [comment]
> This might be a dumb question, but can this not be inferred from if the ExecutionPlan alters the partitioning of its input?

I tried to think of a case where checking if input partitioning and output partitioning match was insufficient and I could not 🤔

**Comment by yahoNanJing** [comment]
Hi @tustvold and @alamb, thanks for your suggestion. The PR is ready. One method of _need_data_exchange_ is added to the trait **_ExecutionPlan_**, which may be much more clear

**Comment by mingmwang** [comment]
My preference is to keep the ExecutionPlan Trait simple and leverage other methods or pattern matching to decide what kind of actions need to take to adjust the plan tree.

**Comment by yahoNanJing** [comment]
Agree
