### ISSUE TITLE
[window function] support min max with self define sliding window.

### ISSUE THREAD

**Issue by Ted-Jiang** [apache/arrow-datafusion#4603]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)
Now run 
```
 SELECT s_suppkey, s_nationkey, s_acctbal, (max(s_acctbal) over (
                               ORDER BY s_acctbal DESC ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING)) wr
   FROM supplier

limit 10;
ArrowError(ExternalError(Internal("Retract should be implemented for aggregate functions when used with custom window frame queries")))
```
Got error because of `min`, `max` accumulator not support  `retract_batch`

https://github.com/alamb/arrow-datafusion/blob/394c5eebf0cfb080698485bd32a8d2fb2230fb80/datafusion/expr/src/accumulator.rs#L61

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Ted-Jiang** [comment]
I will file a pr tommorow.

**Comment by alamb** [comment]
cc @metesynnada @retikulum

**Comment by metesynnada** [comment]
cc @mustafasrepo
