### ISSUE TITLE
Make table statistics available to logical plan optimizer rules

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#4625]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

I have been working on a [join reordering optimization](https://github.com/apache/arrow-datafusion/pull/4620) in the logical plan and have this working in Dask SQL, but now that I try and upstream it to DataFusion, I have run into a blocker. The PR relies on accessing underlying table sizes for `TableScan`s in the logical plan. I had previously added the `TableSource.statistics` method that I hoped to leverage for this. The problem that I run into when trying to plumb this through to `ListingTable` is that I need a `SessionContext` and of course, optimizer rules do not have access to that.

**Describe the solution you'd like**
I am not sure.

**Describe alternatives you've considered**
An alternative would be to implement this as a physical optimizer rule instead, but then this is not available to Dask SQL.

**Additional context**
None

**Comment by andygrove** [comment]
@alamb @tustvold I would appreciate any insights you have on this. This feels like a bit of a dead end at the moment.

**Comment by andygrove** [comment]
Maybe I need to find a way to have `ListingTable` pre-populated with the stats before the optimizer is invoked :thinking:

**Comment by tustvold** [comment]
> Maybe I need to find a way to have ListingTable pre-populated with the stats before the optimizer is invoked thinking

I see no issue with pre-fetching statistics for `ListingTable` if configured to do so. This will be expensive, but there isn't really a way around this. If people have large numbers of parquet files, they should probably invest in a proper catalog and not be using `ListingTable`.

This would, however, entail also baking the list of files in at creation time, which I think would be a behavior change, although I personally think is an improvement.

One thing that wasn't clear to me when I tried to do something similar the other day is how to combine Statistics together, I think this would also be a pre-requisite for this, as Statistics are currently collected per file and would need to be aggregated to per-table.

> to ListingTable is that I need a SessionContext and of course, optimizer rules do not have access to that.

Given the nature of ListingTable I think moving it away from needing SessionState is going to be fairly hard

**Comment by andygrove** [comment]
Thanks for the feedback. That is very helpful. I am experimenting with this approach now and it seems to work. I am aggregating stats but just the row count for now.

**Comment by alamb** [comment]
Note that there is already a physical rule that does some amount of reordering https://github.com/apache/arrow-datafusion/blob/master/datafusion/core/src/physical_optimizer/join_selection.rs

cc @mingmwang  and @liukun4515  and @yahoNanJing  

As I recall there were various opinions on how / when reordering should be done and when statistics would be available. There is always a tension between doing reordering earlier (logical planning) and later (physical planning) where the former is easier to express but the later often has more information

Also @isidentical  has been working on expression / selectivity analysis (though also in the PhysicalPlan layer)

**Comment by andygrove** [comment]
I no longer believe that we should be trying to implement cost-based optimizations in the logical plan, so I am closing this issue.
