### ISSUE TITLE
Timestamp <-> Date32 compare doesn't work

### ISSUE THREAD

**Issue by comphead** [apache/arrow-datafusion#4672]
**Describe the bug**
Make conversion seemless

**To Reproduce**
```
❯ select now() = '2000-01-01'::date;
Plan("'Timestamp(Nanosecond, Some(\"+00:00\")) = Date32' can't be evaluated because there isn't a common type to coerce the types to")
```
**Expected behavior**
Shouldnt fail

**Additional context**

**Comment by comphead** [comment]
@waitingkuo

**Comment by waitingkuo** [comment]
@comphead  is this same as #4644 ?

**Comment by comphead** [comment]
> @comphead is this same as #4644 ?

right, I found it when testing #4644. The solution may be common for both problems, but the error messages are different for both issues. 
I'm fixing #4644 if it also happens to close this issue, that will be great
