### ISSUE TITLE
Install `protoc` automatically when building `datafusion/proto` crate

### ISSUE THREAD

**Issue by ShiKaiWi** [apache/arrow-datafusion#4684]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

I have to install `protoc` manually when introducing the crate `datafusion/proto`, which may bring me some trouble when compiling on different platforms (I have to find different ways to install the `protoc` dependency).

**Describe the solution you'd like**
I guess we can use the crate [protoc-bin-vendored](https://crates.io/crates/protoc-bin-vendored) to install `protoc` automatically.

**Describe alternatives you've considered**
Still install `protoc` manually.

**Additional context**

**Comment by ShiKaiWi** [comment]
@alamb If you think this idea is ok, I can make a PR to implement it.

**Comment by tustvold** [comment]
FWIW you should only need protoc when compiling from source. I think if this is insufficient the next port of call would be to make the build script a binary that is run manually, rather than relying a third-party vendor crate

**Comment by ShiKaiWi** [comment]
👌. It is indeed weird to rely on a third-party vendor crate. Thanks for your response!
