### ISSUE TITLE
Enhancement: don't print rule which don't work.

### ISSUE THREAD

**Issue by jackwener** [apache/arrow-datafusion#4690]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

We can remove all `SAME TEXT AS ABOVE`.
Print them is meaningless.
```
| logical_plan after inline_table_scan                       | SAME TEXT AS ABOVE 
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Weijun-H** [comment]
Just to confirm, are you referring to the text generated by the "SAME TEXT AS ABOVE" prompt in the explain feature?

**Comment by jackwener** [comment]
Close this issue, I think remove them will make optimize-stage period is not obvious
