### ISSUE TITLE
DataFrame.collect() should return async stream rather than a Vec<RecordBatch>

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#47]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Currently, any DataFrame implementation must load the entire result set into RAM in the `collect()` method because it has to return a `Vec<RecordBatch>`. 

**Describe the solution you'd like**
Change the signature to return an async stream of batches.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by djKooks** [comment]
@andygrove hope to touch on this if it's not on work yet 🙏

**Comment by djKooks** [comment]
@andygrove currently `collect` is collecting `SendableRecordBatchStream` to Vector inside function before returning.
Are you intend to make this not collecting before return?
