### ISSUE TITLE
Support compression in `IPCWriter`

### ISSUE THREAD

**Issue by Dandandan** [apache/arrow-datafusion#4708]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Currently `IPCWriter` writes the arrow data in the default way (without compression).
We should  support writing it with compression.

**Describe the solution you'd like**
Introduce a method `try_new_with_options` with a new `IpcWriteOptions` parameter. This can be forwarded to the underlying `FileWriter`.

**Describe alternatives you've considered**

**Additional context**

**Comment by askoa** [comment]
I'll pick this up.

**Comment by Dandandan** [comment]
> I'll pick this up.

Awesome 😎
