### ISSUE TITLE
Run all sqllogictest, even if there are test failures in between

### ISSUE THREAD

**Issue by xudong963** [apache/arrow-datafusion#4734]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Run all sqllogictest, even if there are test failures in between.

When tests are run on CI, it will be more efficient if logictests can be run all the way through and report all failed cases.

**Describe the solution you'd like**
Does sqllogictest-rs have support for this, or does it need to be implemented on the user side? cc @xxchan 

**Describe alternatives you've considered**

**Additional context**

**Comment by xxchan** [comment]
> Does sqllogictest-rs have support for this, or does it need to be implemented on the user side?

Currently sqllogictest runner only has very thin wrappers (`run_multi`, `run_file`) over `run` (record). You need to implement custome testing logic. BTW, you may refer to `sqllogictest-bin`.

**Comment by xxchan** [comment]
BTW, if you want to keep running later records in a file, that might be problematic, e.g., imagine a `CREATE TABLE` failed. But anyway you can implement any suitable policy using the basic building blocks.

**Comment by alamb** [comment]
After reviewing this request I think https://github.com/apache/arrow-datafusion/pull/6393 will fix it (runs all test files and reports errors)
