### ISSUE TITLE
Page Filtering Incorrectly Handles Pages with Different Row Counts

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-datafusion#4744]
**Describe the bug**

`prune_pages_in_one_row_group` uses the size of the previous page when computing the next value of `sum_row`. This causes it to produce incorrect `RowSelection` when computing for a row group containing different size pages.

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by alamb** [comment]
Related to https://github.com/apache/arrow-datafusion/issues/4085
