### ISSUE TITLE
Sub Query bug

### ISSUE THREAD

**Issue by The-Mr-L** [apache/arrow-datafusion#4874]
hey first of thank you for sharing. It is appreciated

**Describe the bug**
Error: Plan("Projection references non-aggregate values: Expression users.id could not be resolved from available columns: MAX(users.id)")
**To Reproduce**
select
    id,
    max_id
from
    (
        select
            id,
            max(id) max_id
        from
            users
    )

**Expected behavior**
id and max_id

**Comment by Jefffrey** [comment]
This seems to be working as intended, since the subquery is incorrect:

```sql
select id, max(id) max_id from users
```

If you specify a non-aggregate column in the project list then you also need a group by, like so:

```sql
select id, max(id) max_id from users group by id
```

Though I'm not sure what your query is intended to do.

**Comment by The-Mr-L** [comment]
thanks for the reply,  so yes the query is just a stupid reproduction example.  but I might  as you say be wrong here but the query I mentioned works in sqlite and will just return the same as you point out in your comment.  I mean why is the result the same from doing "select id, max(id) max_id from users" vs  "select id,  max_id from (select id, max(id) max_id from users)"

do I really need to group by id for the max id of all  records ?

**Comment by Jefffrey** [comment]
This seems to be a SQLite specific feature: https://sqlite.org/lang_select.html#bare_columns_in_an_aggregate_query

Specifically:

> Most other SQL database engines disallow bare columns. If you include a bare column in a query, other database engines will usually raise an error. The ability to include bare columns in a query is an SQLite-specific extension.

Indeed when I try the same query (`select id, max(id) max_id from users`) on Postgres I get an error:

> SQL Error [42803]: ERROR: column "users.id" must appear in the GROUP BY clause or be used in an aggregate function

And I believe this project mainly uses Spark/Postgres as reference for implementation.

**Comment by The-Mr-L** [comment]
well okay my bad then. Thanks  @Jefffrey  :)

**Comment by jackwener** [comment]
Looks like the problem has been solved
