### ISSUE TITLE
Add datafusion-substrait to workspace

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#4880]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
PR https://github.com/apache/arrow-datafusion/pull/4879 updates datafusion-substrait so that it builds correctly against the version of the datafusion in the repo but I could not add it to the workspace due to a build failure in Windows in CI.

```
 error: failed to run custom build command for `substrait v0.2.0`

Caused by:
  process didn't exit successfully: `D:\a\arrow-datafusion\arrow-datafusion\target\debug\build\substrait-a6509fbb99b47d6b\build-script-build` (exit code: 1)
  --- stdout
  cargo:rerun-if-env-changed=FORCE_REBUILD

  --- stderr
  Error: "protobuf compilation failed: protoc failed: Missing input file.\r\n"
```

**Describe the solution you'd like**
Fix the build issue and add the crate to he workspace

**Describe alternatives you've considered**

**Additional context**

**Comment by waynexia** [comment]
I noticed that commits in `datafusion-contrib/datafusion-substrait` after Dec 7, 2022 are not included. How do we handle them? Not sure if upgrading to `substrait v0.3` can resolve this.
