### ISSUE TITLE
Substrait donation follow-on work

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#4897]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
We need to re-apply some PRs from the old repo. This issue is to track the work.

PRs to re-apply:

- Original PR: https://github.com/datafusion-contrib/datafusion-substrait/pull/35
  - [x] New PR: https://github.com/apache/arrow-datafusion/pull/4896
- Original PR: https://github.com/datafusion-contrib/datafusion-substrait/pull/37
  - [x] New PR: https://github.com/apache/arrow-datafusion/pull/5050
- Original PR: https://github.com/datafusion-contrib/datafusion-substrait/pull/38
  - [x] New PR: https://github.com/apache/arrow-datafusion/pull/5051
- Original PR: https://github.com/datafusion-contrib/datafusion-substrait/pull/39
  - [ ] New PR: https://github.com/apache/arrow-datafusion/pull/5054
- Original PR: https://github.com/datafusion-contrib/datafusion-substrait/pull/40
  - [ ] New PR: TBD

Follow-on issues after that:

- In PR https://github.com/apache/arrow-datafusion/pull/4896/files we ignored a test and have to fix that

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by andygrove** [comment]
@waynexia @nseekhao fyi

**Comment by nseekhao** [comment]
@andygrove New PR for the original [PR#40](https://github.com/datafusion-contrib/datafusion-substrait/pull/40) is at https://github.com/apache/arrow-datafusion/pull/5077

**Comment by nseekhao** [comment]
@andygrove A small PR to fix the ignored failed test is at https://github.com/apache/arrow-datafusion/pull/5083
