### ISSUE TITLE
Ballista cannot upgrade to DataFusion 16 due to API changes

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#4920]
**Describe the bug**

These fields are now private and Ballista currently depends on accessing and/or mutating them:

- `SessionState.session_id`
- `SessionContext.state`

**To Reproduce**
See https://github.com/apache/arrow-ballista/pull/603

**Expected behavior**

**Additional context**

**Comment by mingmwang** [comment]
@yahoNanJing 
Could you please help to take look ?

**Comment by yahoNanJing** [comment]
Hi @andygrove, you are right. I think we need to patching this before the datafusion dependency upgrade in Ballista.
