### ISSUE TITLE
Release DataFusion 16.1.0 (patch release)

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#4948]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Ballista cannot upgrade to DataFusion 16.0.0

Follow on to https://github.com/apache/arrow-datafusion/issues/4776

**Describe the solution you'd like**
Now that https://github.com/apache/arrow-datafusion/pull/4933 is merged, I would like to create a 16.1.0 release so that Ballista can upgrade.
- [x] https://github.com/apache/arrow-datafusion/pull/4951

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by alamb** [comment]
cc @jonmmease as I think you you may have some ideas of what would be good to backport too

Also cc @maxburke who I think was working with an upgrade

**Comment by jonmmease** [comment]
FWIW, here are the post 16.0 PRs I'm currently backporting for VegaFusion (https://github.com/jonmmease/arrow-datafusion/pull/126). It's basically #4873 and a handful of PRs to finish wiring things up so that mean and variance-based aggregates work in windows with custom frames.

Thanks for the ping!

**Comment by andygrove** [comment]
@jonmmease I reviewed those PRs, and it seems reasonable to apply them all to the patch release. Could you create the necessary PR(s) to apply those changes to the `maint-16.x` branch?

**Comment by jonmmease** [comment]
Sure thing

**Comment by jonmmease** [comment]
@andygrove, turns out the window aggregated fixes did make it into 16.0.0, so there's only one backport PR needed for #4873:  Here's the PR: https://github.com/apache/arrow-datafusion/pull/4959
