### ISSUE TITLE
Is there a describe method on DataFrame like Polars?

### ISSUE THREAD

**Issue by DataPsycho** [apache/arrow-datafusion#4974]
I was trying to generate a summary on the data frame but could not find any relevant methods like `describe` or `summary` which can provide [this kind](https://docs.rs/polars/latest/polars/frame/struct.DataFrame.html#example-45) of table on the data which Polars data frame has an implementation.

**Describe the solution you'd like**
A described the method on the data frame `&df.describe().await?` should return a new summary dataframe with mean, median, and max values for each column. In more advance case metric name can be provided as vec so that it only compute/statistically estimate tose values for example `&df.describe(vec!["min", "max", "25%"]).await?`

**Comment by andygrove** [comment]
No, this does not currently exist. It would be an excellent addition though.

**Comment by jiangzhx** [comment]
polars got method to calc result for describe, does datafusion got this method?
- count
- null_count
- mean
- std
- min
- max
- quantile


https://github.com/pola-rs/polars/blob/64abfa409355e876e3774521d8cdcdfbe8ee9ddf/polars/polars-core/src/frame/mod.rs#L2452
