### ISSUE TITLE
Explain verbose should include optimized physical plan 

### ISSUE THREAD

**Issue by NGA-TRAN** [apache/arrow-datafusion#499]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
The Explain Verbose currently shows physical plan before its final optimized step that includes CoalesceBatches, RepartitionExec, and MergeExec operators. This is a request to show the plan that includes all physical operators that will be executed.

**Describe the solution you'd like**
If you look at this [create_physical_plan](https://github.com/apache/arrow-datafusion/blob/33ff660318bf60d0c9aa45ceba2c4c943bfe9438/datafusion/src/physical_plan/planner.rs#L90), the explain is created in the `create_initial_plan` which happens before the `optimize_plan` is invoked. The explain should be created after the `optimize_plan`

**Comment by alamb** [comment]
Possible related to https://github.com/apache/arrow-datafusion/issues/497

**Comment by Dandandan** [comment]
Also related: https://github.com/apache/arrow-datafusion/issues/221

**Comment by alamb** [comment]
Closed in https://github.com/apache/arrow-datafusion/issues/499
