### ISSUE TITLE
Implement `std::error::Error` for DataFusionError

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#4991]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
In IOx (and in DataFusion) we often want to know what the root cause of an error is (e.g was it a bug or was it a resources exhausted). ArrowError can wrap other errors with Arrow::External (and DataFusion has something similar) but there is no easy way to get at the source of the error to walk the chain without knowing all the possible types that may be present

See https://github.com/apache/arrow-datafusion/blob/dde23efed94704044822bcefe49c0af7f9260088/datafusion/common/src/error.rs#L361-L439 for what we need to do now in datafusion 🤮

**Describe the solution you'd like**
1. Add DataFusionError::source()
2. Update find_root() to use that

**Describe alternatives you've considered**
N/A

**Additional context**
PR in arrow-rs: https://github.com/apache/arrow-rs/pull/3567

**Comment by avantgardnerio** [comment]
@alamb does this also resolve https://github.com/apache/arrow-datafusion/issues/4981 ?

**Comment by alamb** [comment]
> @alamb does this also resolve https://github.com/apache/arrow-datafusion/issues/4981 ?

@avantgardnerio  I think it may

@DDtKey what do you think?

**Comment by avantgardnerio** [comment]
> > @alamb does this also resolve #4981 ?
> 
> @avantgardnerio I think it may
> 
> @DDtKey what do you think?

That was my 3-second appraisal. I've since reviewed @DDtKey 's PR and think it is in addition to, not instead of your work.
