### ISSUE TITLE
Add `release-crates` bash script

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#5042]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
One part of the release process that is time-consuming is running the individual `cargo publish` commands. 

The `cargo publish` process has improved recently and the command will not complete until the crate has been propagated to the crates.io index so this makes it more compelling to automate this process.

**Describe the solution you'd like**

Write a script that runs the following commands. The script should check that the command is not being run from a git repository (we need to run from the downloaded tarball).

The documentation at `dev/release/README.md` should also be updated.

```shell
(cd datafusion/common && cargo publish)
(cd datafusion/expr && cargo publish)
(cd datafusion/sql && cargo publish)
(cd datafusion/jit && cargo publish)
(cd datafusion/row && cargo publish)
(cd datafusion/physical-expr && cargo publish)
(cd datafusion/optimizer && cargo publish)
(cd datafusion/core && cargo publish)
(cd datafusion/proto && cargo publish)
(cd datafusion-cli && cargo publish --no-verify)
```

**Describe alternatives you've considered**
Keep doing this manually

**Additional context**
None

**Comment by iajoiner** [comment]
On it
