### ISSUE TITLE
Incorrect results on queries with `distinct` and orderby

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#5065]
**Describe the bug**
Distinct is being applied incorrectly when the query has an order by

**To Reproduce**
```shell
cd datafusion-cli
cargo run
...
```
```sql
❯ create table foo as values (1, 2), (3, 4), (5, 6);
0 rows in set. Query took 0.000 seconds.
❯ select distinct '1' from foo;
+-----------+
| Utf8("1") |
+-----------+
| 1         |
+-----------+
1 row in set. Query took 0.001 seconds.
❯ select distinct '1' from foo order by column1;
+-----------+
| Utf8("1") |
+-----------+
| 1         |
| 1         |
| 1         |
+-----------+
```

**Expected behavior**
I expect `select distinct '1' from foo order by column1;` to produce an error, or posibly a single row

Here is postgres output:

```sql
postgres=# create table foo as values (1, 2), (3, 4), (5, 6);
SELECT 3
postgres=# select distinct '1' from foo;
 ?column? 
----------
 1
(1 row)

postgres=# select distinct '1' from foo order by column1;
ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list
LINE 1: select distinct '1' from foo order by column1;
                                              ^
postgres=# 
```

**Additional context**
Found while looking into https://github.com/apache/arrow-datafusion/issues/4854

FWIW the logical order of operations is like this (from https://learnsql.com/blog/sql-order-of-operation)

![image](https://user-images.githubusercontent.com/490673/211674490-041940f2-05d2-453b-b71f-043ada380190.png)

**Comment by xiaoyong-z** [comment]
I'm intersted on this issue, please assign it to me if no one else is already working on it!

**Comment by alamb** [comment]
Thanks @xiaoyong-z !

**Comment by xiaoyong-z** [comment]
For `select distinct '1' from foo order by column1;`, column1 will be added to group by exp, 
the group by expr is ` 1, column1 `, it will generate 3 rows.

![image](https://user-images.githubusercontent.com/31178013/215777850-14cd57c1-8aef-4f11-bf27-57f1f2af5b29.png)

**Comment by xiaoyong-z** [comment]
If the table is 
`create table foo as values (1, 2), (1, 4), (1, 6);`

then `select distinct '1' from foo order by column1;` will only output 1 row

**Comment by xiaoyong-z** [comment]
![image](https://user-images.githubusercontent.com/31178013/215778907-f329f614-79f3-48fc-bbec-fcbe1e23e86b.png)
