### ISSUE TITLE
Re-implement `DataFrame.write_*` to use `LogicalPlan::Write`

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#5076]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
We have DataFrame methods such as `write_parquet` that create a physical plan and execute it, then write the results to disk. This was implemented this way because, at the time, there was no "write" concept in the logical plan.

We now have `LogicalPlan:Dml` for Insert/Update/Delete, but I think we need a more generic `LogicalPlan::Write` operation, as well as a physical operator to perform the write. This is a common pattern for ETL tasks that execute a query, perform a transformation, and then write the results to disk.

**Describe the solution you'd like**
As described.

**Describe alternatives you've considered**

**Additional context**

**Comment by metesynnada** [comment]
We can also support `Statement::Copy` in SQL with this `LogicalPlan::Write`. So it may handle
```
Statement::Copy {
                table_name,
                columns,
                to,
                target,
                options,
                legacy_options,
                values
            }
```
properties, i.e support on `CopyTarget::File` with `CopyOption`.  Perhaps We can handle the same options in `DataFrame.write_*`,

**Comment by tustvold** [comment]
> The downsides are that such an ExecutionPlan is kind of strange

In addition to the points r.e. sort order, etc... from a scheduling / partitioning standpoint the result is not especially 

> Add specific runner / executor for Inserts / Update / Deletes

I'm likely missing something but does this even need to be a separate abstraction, is this not an implementation detail of `TableProvider::insert_into`? This would also allow it to make table-specific decisions w.r.t preserving partitioning, transaction handling, etc... Basically https://github.com/apache/arrow-datafusion/pull/6049 but returning `Result<()>`

**Comment by alamb** [comment]
I think something needs to call `execute()` on the ExecutionPlan and then push the results into the `TableProvider` (or whatever other sink of data)

It is a very reasonable question about how much code that requires and if it should be done in DataFuson or outside

**Comment by ozankabak** [comment]
I find Idea #1 reasonable. If we think of `ExecutionPlan`'s as nodes in the computation graph, writer nodes are simply terminal/sink nodes -- but they are still nodes. Therefore some methods like `output_ordering` not being consumed by anyone doesn't seem unnatural to me, this would be analogous to sink nodes not having any outgoing edges. All in all, I think following Spark's approach is reasonable in this case.

I am curious to hear what @andygrove thinks about @alamb's points, though.

**Comment by thinkharderdev** [comment]
> The downsides are that such an ExecutionPlan is kind of strange (it makes no output, so therefore most of the methods like "output ordering" are basically useless)

I think it's useful to have write operations be able to produce outputs. In many use cases you actually want metadata about what was written (file locations, total bytes, etc). This seems like a natural way to, for example, update a catalog with the new table.

**Comment by avantgardnerio** [comment]
I don't have a strong opinion here, since I haven't had much time to look in depth and we fork execution at the LogicalPlan level before it ever gets to the physical plan anyway. 

I do see how adding support for DML in TableProvider and PhysicalExec would be the next logical step. I would like to weigh in and say if we do that:

1. Don't forget there are folks like me that do have the ability to mutate data. I have no idea how this would work in the broader `arrow-rs` sense though (happy to talk about how we do it)
2. If it is for write-once type things like `CTAS` we probably want some `TableProviderFactory` support for it rather than `TableProvider`

**Comment by andygrove** [comment]
I'm possibly too influenced by Spark's approach, but option 1 seems to work well. For example, Ballista has a `ShuffleWriterExec,` which is an execution plan that executes its child query and repartitions the output and writes it to disk. `ShuffleWriterExec` then produces its own output, which is metadata about the data that was written out.

https://github.com/apache/arrow-ballista/blob/main/ballista/core/src/execution_plans/shuffle_writer.rs#L329

That said, I have stronger opinions about including the logical plan representation than I do about how this is implemented in the physical plan.

**Comment by ozankabak** [comment]
@andygrove, can you take a look at #6049? It implements an `ExecutionPlan` to write to `MemTable`. If the pattern there looks OK to you as a first step, we have some follow-ups in the same vein for writing to `ListingTable`s etc.
