### ISSUE TITLE
Sort operator disappear in physical_plan

### ISSUE THREAD

**Issue by xiaoyong-z** [apache/arrow-datafusion#5100]
**Describe the bug**
After we disable the repartition ProjectionExec when it does not compute anything, sort operator in subquery went wrong

**To Reproduce**
CREATE EXTERNAL TABLE aggregate_test_100 (
  c1  VARCHAR NOT NULL,
  c2  TINYINT NOT NULL,
  c3  SMALLINT NOT NULL,
  c4  SMALLINT,
  c5  INT,
  c6  BIGINT NOT NULL,
  c7  SMALLINT NOT NULL,
  c8  INT NOT NULL,
  c9  BIGINT UNSIGNED NOT NULL,
  c10 VARCHAR NOT NULL,
  c11 FLOAT NOT NULL,
  c12 DOUBLE NOT NULL,
  c13 VARCHAR NOT NULL
)
STORED AS CSV
WITH HEADER ROW
LOCATION 'xxxx/csv/aggregate_test_100.csv';

SELECT * FROM aggregate_test_100 ORDER BY c13 LIMIT 1;
0VVIHzxWtNOFLtnhjHEKjXaJOSLJfm

SELECT array_agg(c13) FROM (SELECT * FROM aggregate_test_100 ORDER BY c13 LIMIT 1);
6WfVFBVGJSQb7FhA7E0lBwdvjfZnSW

explain  SELECT array_agg(c13) FROM (SELECT * FROM aggregate_test_100 ORDER BY c13 LIMIT 1);
![image](https://user-images.githubusercontent.com/31178013/215267482-c6b51e61-aca8-4663-ac04-e7b1d7e92645.png)

**Expected behavior**
There is a sort operator in logical_plan, but there is no sort exec in c. 

**Additional context**
Found in https://github.com/apache/arrow-datafusion/pull/5074

**Comment by xiaoyong-z** [comment]
plan in master branch
![image](https://user-images.githubusercontent.com/31178013/215268319-e77ccefe-0388-4c15-ada3-8f50c78caabd.png)

**Comment by xiaoyong-z** [comment]
it seems that sort enforing deletes this:
![image](https://user-images.githubusercontent.com/31178013/215268840-074a2bac-7636-4089-87d4-f6bd9d8a9848.png)

**Comment by ozankabak** [comment]
Yes, this seems to be a bug. Thanks for reporting, @mustafasrepo will fix it.
