### ISSUE TITLE
parquet page level skipping (page index pruning) doesn't work with evolved schemas

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#5104]
**Describe the bug**
parquet page level skipping (page index pruning) panic's  with evolved schemas

**To Reproduce**

Enable setting like

```rust
        pub enable_page_index: bool, default = true
```

And then run test:
```shell
cargo test -p datafusion --lib -- evolved_schema_disjoint_schema_filter
```

Which fails

```
test physical_plan::file_format::parquet::tests::evolved_schema_disjoint_schema_filter ... FAILED

failures:

---- physical_plan::file_format::parquet::tests::evolved_schema_disjoint_schema_filter stdout ----
thread 'physical_plan::file_format::parquet::tests::evolved_schema_disjoint_schema_filter' panicked at 'index out of bounds: the len is 1 but the index is 1', /Users/alamb/.cargo/registry/src/github.com-1ecc6299db9ec823/parquet-31.0.0/src/file/metadata.rs:251:10
```

**Expected behavior**
Test should pass

**Additional context**
I found this while working to enable this feature by default
https://github.com/apache/arrow-datafusion/pull/5099

**Comment by alamb** [comment]
FYI @Ted-Jiang -- I plan to fix this

**Comment by alamb** [comment]
I am pretty sure the issue is that the page pruning is trying to use a column index into the merged schema to find the relevant statistics, but each file schema can be slightly different. I think the fix will be to look up statistics based on name rather than index

**Comment by Ted-Jiang** [comment]
@alamb Thanks for ping me! i got some time to fix this this weekend! 😄

**Comment by alamb** [comment]
The tests that fail are:

```

failures:
    physical_plan::file_format::parquet::tests::evolved_schema_disjoint_schema_filter
    physical_plan::file_format::parquet::tests::evolved_schema_disjoint_schema_with_filter_pushdown
    physical_plan::file_format::parquet::tests::evolved_schema_intersection_filter
    physical_plan::file_format::parquet::tests::evolved_schema_intersection_filter_with_filter_pushdown

```
