### ISSUE TITLE
Pipeline file opening in `FileStream`

### ISSUE THREAD

**Issue by thinkharderdev** [apache/arrow-datafusion#5129]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

Current `FileStream` is a state machine that goes from Open (read metadata and build reader) -> Scan (scan decode `RecordBatch`) in sequence until all files are scanned. 

For parquet in particular, the `Opener` may need to do multiple sequential IO requests:
1. Read footer to get metadata start offset
2. Read footer
3. Fetch page/offset indexes

Seems like it might be possible to parallelize the scan with opening the next file.

**Describe the solution you'd like**

`FileStream::Scan` adds an `Option<FileOpenFuture>`. If polled in a scan state, try and pop another file and initialize it's `FileOpenFuture` (eg try and open the file in parallel) so metadata IO can be done in parallel to scanning of the current file. 

**Describe alternatives you've considered**

Not do anything

**Additional context**

Not sure if this will be workable but want to experiment with it.

**Comment by tustvold** [comment]
Fetching metadata in parallel seems like it could yield fairly significant savings :+1:
