### ISSUE TITLE
Supporting Grafana global variables 

### ISSUE THREAD

**Issue by Jayclifford345** [apache/arrow-datafusion#5144]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
We have created a FlightSQL plugin for grafana: https://github.com/influxdata/grafana-flightsql-datasource. 
I am currently creating example dashboards based on the FlightSQL dialect but hit a rough patch with global Grafana variables:

Here is a query:
```
SELECT
  DATE_BIN(INTERVAL '$__interval_ms MILLISECONDS', time, '${__to:date}'::TIMESTAMP) AS time,
  avg(used_percent) AS 'average used_percent'
FROM mem
WHERE host='${linux_host}' AND time BETWEEN '${__from:date:iso}' AND '${__to:date:iso}'
GROUP BY time
```
It would be great instead of utilising `INTERVAL '$__interval_ms MILLISECONDS'` and `time BETWEEN '${__from:date:iso}' AND '${__to:date:iso}'` we could use the following variables Grafana has inbuilt:

[$timeFilter or $__timeFilter](https://grafana.com/docs/grafana/latest/dashboards/variables/add-template-variables/#timefilter-or-__timefilter)

and 

[$__interval](https://grafana.com/docs/grafana/latest/dashboards/variables/add-template-variables/#__interval)

**Describe the solution you'd like**
If we could support the above variables our query could now look like this:
```
SELECT
  DATE_BIN(INTERVAL '$__interval', time, '${__to:date}'::TIMESTAMP) AS time,
  avg(used_percent) AS 'average used_percent'
FROM mem
WHERE host='${linux_host}' AND $timeFilter
GROUP BY time
```
this would become the following query after translation:

```
SELECT
  DATE_BIN(INTERVAL '30d', time, '2023-02-01T11:21:14.644Z'::TIMESTAMP) AS time,
  avg(used_percent) AS 'average used_percent'
FROM mem
WHERE host='foo' AND time > now() - 7d
GROUP BY time
```

**Describe alternatives you've considered**
Currently using the original query as a work around.

**Additional context**
<img width="957" alt="Screenshot 2023-02-01 at 11 32 13" src="https://user-images.githubusercontent.com/45856600/216031529-65d33163-b174-44f3-8565-ad4cd7bdd5e8.png">
<img width="942" alt="Screenshot 2023-02-01 at 11 32 32" src="https://user-images.githubusercontent.com/45856600/216031534-ebc6b23d-ede6-41ff-bfc2-83299433f86f.png">

**Comment by alamb** [comment]
Hi @Jayclifford345  -- this I will let the rest of the community weigh in on if they think this feature belongs in DataFusion

Another alternative is to implement this expansion https://github.com/influxdata/influxdb_iox in IOx (rather than in DataFusion) given that it is valuable for our usecase.

**Comment by Jayclifford345** [comment]
Thanks, @alamb, that sounds like a good plan. I hope it will be beneficial to anyone who plans to use Grafana with FlightSQL if the plugin is generic enough.

**Comment by brettbuddin** [comment]
These variable/macro expansions are on the Grafana plugin side. We can support whatever you need, @Jayclifford345. No need to push down to IOx or DataFusion.

**Comment by Jayclifford345** [comment]
Issues being resolved in plugin issue can be closed
