### ISSUE TITLE
Unnecessary `Filter` on Parquet datasources

### ISSUE THREAD

**Issue by Dandandan** [apache/arrow-datafusion#5149]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Now that Parquet supports pushing down predicates to the scanning phase, we could remove the additional filter, as we're no longer providing an inexact filter.

**Describe the solution you'd like**
Add a method to `FileFormat` that returns whether the format supports exact filter pushdown.
The `supports_filter_pushdown` function should be updated accordingly.

**Describe alternatives you've considered**

**Additional context**

**Comment by tustvold** [comment]
I think this may be a duplicate of https://github.com/apache/arrow-datafusion/issues/4028

**Comment by Dandandan** [comment]
Yeah, it is. Thanks @tustvold
