### ISSUE TITLE
Ignoring of memory-pool limits & OOM on large cartesian-product join

### ISSUE THREAD

**Issue by DDtKey** [apache/arrow-datafusion#5162]
**Describe the bug**
There is an issue with possible OOM instead of `ResourcesExhausted`
Probably related to usage of unbounded channels (I believe it should be avoided actually)

**To Reproduce**

MRE to achieve ignoring of memory-pool with large Cartesian product:

CSV File example (250mb): [GDrive link](https://drive.google.com/file/d/1q_-p8BvvO2w-0IH7SyxvDIOYK44yQIKt/view?usp=share_link) - it's random file and column to join by has the same value for all records (so it's cartesian product)

Memory pool limit: `FairSpillPool::new(4 * 1024 * 1024 * 1024)`

SQL:
`SELECT * FROM rnd rnd1 JOIN rnd rnd2 ON rnd1."s3_drive" = rnd2."s3_drive"`

**Expected behavior**

It should return`ResourcesExhausted` error with configured `MemoryPool`

**Additional context**

A part of this was described in the discussion here: https://github.com/apache/arrow-datafusion/issues/5108#issuecomment-1412491794, but there was mentioned the regression. 
This example isn't regression and it's reproducible for old versions

**Comment by DDtKey** [comment]
I've changed the description, because this case isn't regression like one that was mentioned in #5108 by me. And probably more related to #3941.

**Comment by alamb** [comment]
> I've changed the description, because this case isn't regression like one that was mentioned in https://github.com/apache/arrow-datafusion/issues/5108 by me. And probably more related to/part of https://github.com/apache/arrow-datafusion/issues/3941.

Thank you @DDtKey  -- I agree this is a feature gap (limiting memory usage by joins)

**Comment by korowa** [comment]
It seems I was wrong about #5339 closes this issue, my bad 😞 . This query shouldn't produce `CROSS JOIN`, and memory limitation for hash join required to fix this issue.

**Comment by DDtKey** [comment]
> It seems I was wrong about https://github.com/apache/arrow-datafusion/pull/5339 closing this issue, my bad 😞 . This query shouldn't produce CROSS JOIN, and memory limitation for hash join required to fix this issue.

Yes, I think so, because this query produces `hash-join` in plan, but results in Cartesian product actually due to the same values in columns

**Comment by korowa** [comment]
I guess I'll fix Hash Join using the same approach in a couple of days then 🙃

**Comment by alamb** [comment]
Thank you @korowa

**Comment by Dandandan** [comment]
This

**Comment by Dandandan** [comment]
Closed by https://github.com/apache/arrow-datafusion/pull/5564
