### ISSUE TITLE
no hyperlink to blaze-rs [doc: README-"Use Cases"]

### ISSUE THREAD

**Issue by jiang13021** [apache/arrow-datafusion#5175]
**Describe the bug**
README-"Use Cases", there are hyperlinks to other projects, but there is no hyperlink to "blaze-rs". Does "blaze-rs" mean https://github.com/blaze-init/blaze? 
![image](https://user-images.githubusercontent.com/45600652/216750455-0c5cfae6-5161-47ed-b781-ca190855c50c.png)

**Expected behavior**
Add a hyperlink to "blaze-rs" in the corresponding position of README

**Comment by jiangzhx** [comment]
i got this. https://github.com/apache/arrow-datafusion/pull/5190

**Comment by jiangzhx** [comment]
should close this issue. already fixed by https://github.com/apache/arrow-datafusion/pull/5190
