### ISSUE TITLE
CI is currently broken on git diff: Not a git repository

### ISSUE THREAD

**Issue by viirya** [apache/arrow-datafusion#5180]
**Describe the bug**

A few Github Actions jobs which run `git diff --exit-code` received a error currently:

```
warning: Not a git repository. Use --no-index to compare two paths outside a working tree
usage: git diff --no-index [<options>] <path> <path>
```

e.g. https://github.com/apache/arrow-datafusion/actions/runs/4093544289/jobs/7059343655, https://github.com/apache/arrow-datafusion/actions/runs/4092342002/jobs/7057053547

Found some similar issues like https://github.com/actions/checkout/issues/363, but it was reported long time ago, not sure why suddenly this happens to datafusion CI.

**To Reproduce**

See action links.

**Expected behavior**

CI should work.
**Additional context**

**Comment by alamb** [comment]
I believe this was fixed by https://github.com/apache/arrow-datafusion/pull/5177
