### ISSUE TITLE
Add SQL function overload `LOG(base, x)` for logarithm of x to base

### ISSUE THREAD

**Issue by stuartcarnie** [apache/arrow-datafusion#5206]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

As a user, I would like to determine the logarithm of a value, $x$ to base $b$.

**Describe the solution you'd like**

Add an overload to the `log` function, which takes two arguments. Using PostgreSQL for inspiration per [the documentation](https://www.postgresql.org/docs/current/functions-math.html):

> `log ( b numeric, x numeric ) → numeric`
> Logarithm of $x$ to base $b$
> log(2.0, 64.0) → 6.0000000000000000  

**Describe alternatives you've considered**

DataFusion strives for PostgreSQL compatibility, so it makes sense to use the PostgreSQL solution.

**Additional context**

**Comment by comphead** [comment]
@alamb on top of my head we dont have overloaded scalar functions yet? 
We know how to to create different aliases for the same function, but not overloading

**Comment by stuartcarnie** [comment]
@comphead there are already examples in DF of this, for example the `ltrim` function takes 1 or 2 arguments:

https://github.com/apache/arrow-datafusion/blob/ac876dbc9729b16e272e00496c51e53d9f649173/datafusion/physical-expr/src/string_expressions.rs#L355-L369

**Comment by comphead** [comment]
Thanks @stuartcarnie with `log` I came out to the similar solution, inspecting `len()` :) but was wondering if we already have something more elegant to provide default values, seems we dont have it yet

**Comment by stuartcarnie** [comment]
In the case of the `LOG` function, if there is a single argument, it is assumed to be LOG $x$ base 10:

> ```
> log ( numeric ) → numeric
> log ( double precision ) → double precision
>      Base 10 logarithm
>      log(100) → 2
```

**Comment by stuartcarnie** [comment]
@comphead no worries – I looked for other solutions too, but that is all I could find for now.

**Comment by comphead** [comment]
Thats okay, I'll implement it using `len()` but going forward probably we may want to think how we can substitute default values, in case of different signatures for the same scalar function

**Comment by stuartcarnie** [comment]
@comphead awesome, thanks for doing that!
