### ISSUE TITLE
Move `type_coercion` to the front of logical optimizer

### ISSUE THREAD

**Issue by HaoYang670** [apache/arrow-datafusion#5235]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
This is just a placeholder, which we can't do this until completing #4615.

`Type_coercion` and type checking is something we must do on a query, not an optional optimizing pass. So it is more reasonable to move it to the front of the logical optimization.

Also, we should try to remove the `type_coercion` in physical plan, so that our queries can be totally statically typed.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wolffcm** [comment]
I commented on #4615 with a DF use case (for IOx) that I think also relevant here: https://github.com/apache/arrow-datafusion/issues/4615#issuecomment-1483288017

**Comment by HaoYang670** [comment]
Close this as it has been fixed by #5831
