### ISSUE TITLE
TopDown EnforceSorting implementation

### ISSUE THREAD

**Issue by mingmwang** [apache/arrow-datafusion#5289]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

A new top down approach to remove/add Sort when unnecessary. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by simonvandel** [comment]
Can this be closed with https://github.com/apache/arrow-datafusion/pull/5661 merged? It seems the two were never linked together.

**Comment by alamb** [comment]
I agree -- thank you @simonvandel 

FYI @mingmwang
