### ISSUE TITLE
Trim the duplicated sort keys in Order By clause

### ISSUE THREAD

**Issue by mingmwang** [apache/arrow-datafusion#5296]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

```rust
let sql = "select c1, c2 from aggregate_test_100 order by c1, c2, c1";
let expected = {
        vec![
            "SortExec: expr=[c1@0 ASC NULLS LAST,c2@1 ASC NULLS LAST], global=true",
            "  ProjectionExec: expr=[c1@0 as c1, c2@1 as c2]",
        ]
    };
```

The duplicate sort keys should be removed.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jackwener** [comment]
I will do it.
