### ISSUE TITLE
data file without suffix can't be read correctly

### ISSUE THREAD

**Issue by RTEnzyme** [apache/arrow-datafusion#5301]
**Describe the bug**
My data files in linux don't have ".csv" suffix. When I use ctx.read_csv("path/to/csv"), It read blank data rather than the data in my files or an error.

**To Reproduce**
Use the case in the example `csv_sql.rs`. I remove the csv file's suffix and cpy /path/to/aggregate_test_100.csv /path/to/aggregate_test_100.
```Rust
  // register csv file with the execution context
  ctx.register_csv(
      "aggregate_test_100",
      &format!("{testdata}/csv/aggregate_test_100"),
      CsvReadOptions::new(),
  )
  .await?;
 // execute the query
    let df = ctx
        .sql(
            "SELECT c1, MIN(c12), MAX(c12) \
        FROM aggregate_test_100 \
        WHERE c11 > 0.1 AND c11 < 0.9 \
        GROUP BY c1",
        )
        .await?;

    // print the results
    df.show().await?;
```

The result:
```
Error: SchemaError(FieldNotFound { field: Column { relation: None, name: "c11" }, valid_fields: [] })
```

**Expected behavior**
I think that either the file can be read correctly in this case, or an error that the file suffix does not match will be reported.

**Additional context**

**Comment by tustvold** [comment]
I think this is a duplicate of https://github.com/apache/arrow-datafusion/issues/1736

**Comment by RTEnzyme** [comment]
> I think this is a duplicate of #1736

Emm..I think so..
