### ISSUE TITLE
Investigate performance drop for DISTINCT queries

### ISSUE THREAD

**Issue by comphead** [apache/arrow-datafusion#5313]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
ClickBench reported a performance drop for `COUNT(DISTINCT)` computation  https://github.com/apache/arrow-datafusion/issues/5276#issuecomment-1431892334

**Describe the solution you'd like**
Its needed to investigate a performance drop root cause in DISTINCT queries and find out how is it possible to increase the speed.

**Describe alternatives you've considered**
Not doing this

**Additional context**
Metrics can be found https://github.com/apache/arrow-datafusion/issues/5276#issuecomment-1433650162
Reproduce the case https://github.com/apache/arrow-datafusion/issues/5276#issuecomment-1432070491

**Comment by comphead** [comment]
![df-distinct-graph](https://user-images.githubusercontent.com/10247224/219758353-c5b40d5c-5a2b-4ff0-9e66-4b904e941b19.svg)
Adding Flamegraph profiler for query 
```SELECT COUNT(*) AS c, COUNT(DISTINCT "UserID") FROM hits GROUP BY "RegionID" LIMIT 10;```

**Comment by Dandandan** [comment]
So here we have the answer - it's very inefficient because of inefficiently tracking memory (which was added some versions ago). FYI @alamb

**Comment by alamb** [comment]
> So here we have the answer - it's very inefficient because of inefficiently tracking memory (which was added some versions ago). FYI @alamb



Nice sluthing -- thank you @comphead  and @Dandandan  - - I can file a ticket for the regression related to tracking memory if that would help

**Comment by comphead** [comment]
> So here we have the answer - it's very inefficient because of inefficiently tracking memory (which was added some versions ago). FYI @alamb

Thanks @Dandandan I haven't yet mapped to gr

**Comment by comphead** [comment]
@Dandandan do you mean this one? 
https://github.com/apache/arrow-datafusion/pull/4342/files#diff-08e5824197365dbe355c53949deee767063f6ac52f65974e19da0c0a63ae4f7cR222

**Comment by comphead** [comment]
so yeah, `size` function needed to calc additional number of bytes that were allocated during `aggregate_batch` process.
I have commented this out and the same query runs 4 sec instead of 100sec. 

@Dandandan @alamb I'll file a ticket to optimize this part

**Comment by Dandandan** [comment]
> so yeah, `size` function needed to calc additional number of bytes that were allocated during `aggregate_batch` process. I have commented this out and the same query runs 4 sec instead of 100sec.
> 
> @Dandandan @alamb I'll file a ticket to optimize this part

Yes, some quadratic complexity because of the growing state.

**Comment by Dandandan** [comment]
(you could identify it from your flamegraph, it's just the longest bar at the top consuming all the time)

**Comment by comphead** [comment]
Right, the function was evident to identify, but it was introduced recently, took some time to figure out its purpose.

**Comment by comphead** [comment]
Filed https://github.com/apache/arrow-datafusion/issues/5325

@Dandandan @alamb should we close this ticket?

**Comment by alamb** [comment]
I agree the analysis is done -- thank you @comphead
