### ISSUE TITLE
Support min/max statistics in ParquetTable and ParquetExec

### ISSUE THREAD

**Issue by Dandandan** [apache/arrow-datafusion#537]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
Min/max column statistics support doing statistics based optimizations, for example join reordering.

**Describe the solution you'd like**
Add min/max statistics while preparing parquet data.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by tustvold** [comment]
I believe this is now supported, but feel free to reopen if I am mistaken
