### ISSUE TITLE
Add check logic to validate the subquery expressions before any logical optimization rules

### ISSUE THREAD

**Issue by mingmwang** [apache/arrow-datafusion#5463]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

Some logical plans should not allow sub query exprs(`Exists`/`InSubquery`/`ScalarSubquery`), for example, `TableScan`, `Values`.

And for correlated subqueries, sometimes they might refer to invalid out plan's columns.
Need to add validation logic to fail the invalid plans before any logical optimization rules.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mingmwang** [comment]
Current there is no Analysis phase in DataFusion. Need to find out a place to add the validation logic.
@alamb @liukun4515 @jackwener 
Do you have any suggestion ?

**Comment by alamb** [comment]
I think we have discussed adding an analysis phase before, specifically for TypeCoercion which is also not really an Optimzer.

https://github.com/apache/arrow-datafusion/blob/e9852074bacd8c891d84eba38b3417aa16a2d18c/datafusion/optimizer/src/optimizer.rs#L210-L211

My personal opinion is it would be best to just add an Analysis phase so we have a place to put these types of checks.

Maybe we could start by simply calling it right before the current optimizers are called 🤔

**Comment by mingmwang** [comment]
Sure, I will work on it.

**Comment by mingmwang** [comment]
> I think we have discussed adding an analysis phase before, specifically for TypeCoercion which is also not really an Optimzer.
> 
> https://github.com/apache/arrow-datafusion/blob/e9852074bacd8c891d84eba38b3417aa16a2d18c/datafusion/optimizer/src/optimizer.rs#L210-L211
> 
> My personal opinion is it would be best to just add an Analysis phase so we have a place to put these types of checks.
> 
> Maybe we could start by simply calling it right before the current optimizers are called 🤔

Sure, I will work on it.

**Comment by mingmwang** [comment]
Close this.
