### ISSUE TITLE
`upper` (and other string functions) don't support String `Dictionary` types: Internal error: The "upper" function can only accept strings.

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#5471]
**Describe the bug**
Running `upper(col)` where col is a dictionary results in an internal error:

```
Internal error: The "upper" function can only accept strings.. This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```

**To Reproduce**
Requires the arrow_cast function in https://github.com/apache/arrow-datafusion/pull/5166

```sql
DataFusion CLI v19.0.0
❯ select upper('foo');
+--------------------+
| upper(Utf8("foo")) |
+--------------------+
| FOO                |
+--------------------+
1 row in set. Query took 0.004 seconds.
❯ select upper(arrow_cast('foo', 'Dictionary(Int32, Utf8)'));
Internal error: The "upper" function can only accept strings.. This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```

**Expected behavior**
The test should pass and produce `FOO`

**Additional context**
Reported by  @sanderson at https://github.com/influxdata/docs-v2/pull/4773#issuecomment-1452256546

**Comment by tustvold** [comment]
https://docs.rs/arrow-array/latest/arrow_array/array/struct.DictionaryArray.html#method.with_values might be useful here

**Comment by alamb** [comment]
I strongly suspect the bug/limitiation is in type coercion somewhere. Perhaps https://github.com/apache/arrow-datafusion/blob/main/datafusion/expr/src/type_coercion/functions.rs

**Comment by alamb** [comment]
I started looking into this -- in general the string expressions need some love. Roughly:
- [ ] Improve the tests (so I have some place to add the reproducer for dictionaries as well as LargeStringArray)
- [ ] Update the code to handle dictionaries,

**Comment by alamb** [comment]
length / character_length has the same issue:

```
❯ select length("labels.chart") from 'incoming_lines.count' limit 1;
Internal error: The "character_length" function can only accept strings.. This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```

**Comment by alamb** [comment]
The code for these functions is in https://github.com/apache/arrow-datafusion/blob/main/datafusion/physical-expr/src/string_expressions.rs

As an initial step, I recommend creating some sqllogictests reproducing the issue. sqllogictest is explained here: https://github.com/apache/arrow-datafusion/tree/main/datafusion/core/tests/sqllogictests

Perhaps by extending what is in https://github.com/apache/arrow-datafusion/blob/main/datafusion/core/tests/sqllogictests/test_files/functions.slt

**Comment by alamb** [comment]
BTW a workaround is to cast explicitly to varchar:

```sql
select upper(col::varchar)
```

**Comment by appletreeisyellow** [comment]
I'm going to put up a PR soon

**Comment by appletreeisyellow** [comment]
These are all the functions that generate the same error as `upper`:

```
$ grep utf8_to_str_type

datafusion/expr/src/built_in_function.rs
600:                utf8_to_str_type(&input_expr_types[0], "btrim")
628:                utf8_to_str_type(&input_expr_types[0], "initcap")
630:            BuiltinScalarFunction::Left => utf8_to_str_type(&input_expr_types[0], "left"),
632:                utf8_to_str_type(&input_expr_types[0], "lower")
634:            BuiltinScalarFunction::Lpad => utf8_to_str_type(&input_expr_types[0], "lpad"),
636:                utf8_to_str_type(&input_expr_types[0], "ltrim")
638:            BuiltinScalarFunction::MD5 => utf8_to_str_type(&input_expr_types[0], "md5"),
651:                utf8_to_str_type(&input_expr_types[0], "regex_replace")
654:                utf8_to_str_type(&input_expr_types[0], "repeat")
657:                utf8_to_str_type(&input_expr_types[0], "replace")
660:                utf8_to_str_type(&input_expr_types[0], "reverse")
663:                utf8_to_str_type(&input_expr_types[0], "right")
665:            BuiltinScalarFunction::Rpad => utf8_to_str_type(&input_expr_types[0], "rpad"),
667:                utf8_to_str_type(&input_expr_types[0], "rtrimp")
711:                utf8_to_str_type(&input_expr_types[0], "split_part")
718:                utf8_to_str_type(&input_expr_types[0], "substr")
740:                utf8_to_str_type(&input_expr_types[0], "translate")
742:            BuiltinScalarFunction::Trim => utf8_to_str_type(&input_expr_types[0], "trim"),
744:                utf8_to_str_type(&input_expr_types[0], "upper")
```

```
$ grep utf8_to_int_type

datafusion/expr/src/built_in_function.rs
597:                utf8_to_int_type(&input_expr_types[0], "bit_length")
603:                utf8_to_int_type(&input_expr_types[0], "character_length")
645:                utf8_to_int_type(&input_expr_types[0], "octet_length")
715:                utf8_to_int_type(&input_expr_types[0], "strpos")
```

**Comment by tustvold** [comment]
I presume this is what you intend to do, but I would recommend implementing this by evaluating the function on the dictionary values using the existing kernels, and then passing the result from this into the take kernel with the dictionary keys as the second argument. This should not only be less code, but will avoid a codegen explosion from parameterising generic code on both dictionary key types and value types

**Comment by alamb** [comment]
I just tested this out after https://github.com/apache/arrow-datafusion/pull/7262 was merged and the functions still don't work for arrays it seems:

```sql
create table foo(x varchar) as values ('foo'), ('bar');
create table foo_dict as select arrow_cast(x, 'Dictionary(Int32, Utf8)') as x from foo;
select upper(x) from foo_dict;
```

Results in an internal error:

```
DataFusion CLI v28.0.0
❯ create table foo(x varchar) as values ('foo'), ('bar');
create table foo_dict as select arrow_cast(x, 'Dictionary(Int32, Utf8)') as x from foo;
select upper(x) from foo_dict;

0 rows in set. Query took 0.034 seconds.

0 rows in set. Query took 0.039 seconds.

Internal error: The "upper" function can only accept strings.. This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
````

So I think https://github.com/apache/arrow-datafusion/pull/7262 made things better but there is still something not working

**Comment by alamb** [comment]
> I presume this is what you intend to do, but I would recommend implementing this by evaluating the function on the dictionary values using the existing kernels, and then passing the result from this into the take kernel with the dictionary keys as the second argument. 

@tustvold  Since this is such a common operation (write a function that applies a function to a `StringArray` / `LargeStringArray` / `DictionaryArray`) I was wondering if we could make a function like https://docs.rs/arrow/latest/arrow/compute/fn.unary.html to do the dispatch and apply

Maybe something like

```rust
// apply f to each element of array, which writes the result to a temporary string
// resulting in the same type of array out
fn unary_str<F>(apply: &dyn Array, f: F) -> Result<ArrayRef> 
where:
  F: FnMut(&str) -> Cow<str>
{
...
}
```

Then writing `upper` would look like

```rust
unary_str(&input_array, |in| {
  // this cold be substantially fancier and avoid allocations, etc if the output 
  // was already upper case, etc 
  Cow::from(in.to_uppercase())
}
```

**Comment by tustvold** [comment]
You could but it seems odd to me that you would special case strings, it feels like you should be able to wrap an arbitrary unary function and produce a new function that can handle dictionaries. This is a completely general transformation that need not know anything about the values in question?

Provided you are able to pass the input schema to create_physical_fun this should be relatively straightforward

**Comment by alamb** [comment]
> You could but it seems odd to me that you would special case strings, it feels like you should be able to wrap an arbitrary unary function and produce a new function that can handle dictionaries. 

What I am struggling with is that [`unary`](https://docs.rs/arrow/latest/arrow/compute/fn.unary.html) only works for `ArrowPrimitiveTypes` (aka not `StringArray` / `LargeStringArray`)

I do agree that under the covers the handling of Non `DictionaryArray` and `DictionaryArray` could be general

Maybe we could also add a function like the following to handle it 🤔 

```rust
/// Applies an array --> array transform function 
/// that will apply the function to dictionary values as well
fn apply<F>(input: &dyn Array, f: F) -> Result<ArrayRef> 
where
  F: FnMut(&dyn Array) -> Result<ArrayRef> 
{
  // if input is dictionary, apply f to values()
  // otherwise, apply f to input
}
```

Maybe it doesn't even need to be dynamic so we could avoid additional code bloat 🤔

**Comment by tustvold** [comment]
So the current state of play is we have a function to obtain a type erased function that operates on ColumnarValue and produces a ColumnarValue for non-dictionary arrays.

It should therefore be trivial to make this same function recurse for the values type, and then return a type-erased function that operates on dictionaries.

This would be simpler, avoid codegen, and naturally generalise to all functions and argument types.

**Comment by alamb** [comment]
>  So the current state of play is we have a function to obtain a type erased function that operates on ColumnarValue and produces a ColumnarValue for non-dictionary arrays

Do you mean something in DataFusion?

Perhaps https://github.com/apache/arrow-datafusion/blob/00627785718d9d98998021bf44585f32c33af3ea/datafusion/physical-expr/src/functions.rs#L294

Are you suggesting we handle evaluating scalar functions on DictionaryArrays in the generic function evaluate function rather than doing something special for string functions?

**Comment by appletreeisyellow** [comment]
I was trying to implement something you both described above, and before I add any code, I tried to run sqllogictests and `datafusion-cli`. Then I found something weird:

* When I ran `cargo test -p datafusion --test sqllogictests -- functions`, all the tests passed
* Then I ran `cargo build`. When I copied the queries from the test file to `datafusion-cli`, I got the same error message `Internal error: The "upper" function can only accept strings.. `

https://github.com/apache/arrow-datafusion/blob/6ad79165f6554a66aa5ed4c5d432401c2c162f69/datafusion/core/tests/sqllogictests/test_files/functions.slt#L616

* Why the same query passes in sqllogictests, but it gets an error in `datafusion-cli`? Am I missing anything?

**Comment by alamb** [comment]
> Why the same query passes in sqllogictests, but it gets an error in datafusion-cli? Am I missing anything

Maybe you are still using an old version of `datafusion-cli` 🤔  What exact commands are you using to do "cargo build. When I copied the queries from the test file to datafusion-cli"

I think it should be something like this:

```shell
cd datafusion-cli
cargo build
./target/debug/datafusion-cli 
```

If you want to install `datafusion-cli` in your path you need to do something like
```shell
cd datafusion-cli
cargo install 
# now you can run datafusion-cli anywhere
datafusion-cli
```

**Comment by appletreeisyellow** [comment]
Ah! I just ran `datafusion-cli` directly without cd into the `datafusion-cli` dir and I didn't use `./target/debug/datafusion-cli`, so I was using the old version of datafusion cli 🤦‍♀️

This is what I tired:
1. Pull the latest `arrow-datafusion` repo
2. Ran the following:
```shell
$ cd datafusion-cli
$ cargo build
$ ./target/debug/datafusion-cli 
DataFusion CLI v29.0.0
❯ SELECT upper('foo');
+--------------------+
| upper(Utf8("foo")) |
+--------------------+
| FOO                |
+--------------------+
1 row in set. Query took 0.035 seconds.

❯ select upper(arrow_cast('foo', 'Dictionary(Int32, Utf8)'));
+--------------------+
| upper(Utf8("foo")) |
+--------------------+
| FOO                |
+--------------------+
1 row in set. Query took 0.002 seconds.

❯ create table foo(x varchar) as values ('foo'), ('bar');
0 rows in set. Query took 0.016 seconds.

❯ create table foo_dict as select arrow_cast(x, 'Dictionary(Int32, Utf8)') as x from foo;
0 rows in set. Query took 0.017 seconds.

❯ select upper(x) from foo_dict;
+-------------------+
| upper(foo_dict.x) |
+-------------------+
| FOO               |
| BAR               |
+-------------------+
2 rows in set. Query took 0.004 seconds.
```

I cannot re-produce the error 🤔 Definitely `DataFusion CLI v29.0.0` doesn't have the error, but some point in `v28.0.0` the error still exist. I tested that the error exists in `v28.0.0` before [this PR](https://github.com/apache/arrow-datafusion/commit/7a5354fe5908b8ac7db163d6c484dbf1d85a142e). 

@alamb Can you verify for me?

**Comment by alamb** [comment]
🤔  I got the same results as you did @appletreeisyellow 

```
(arrow_dev) alamb@MacBook-Pro-8:~/Downloads/arrow-datafusion/datafusion-cli$ ./target/debug/datafusion-cli
DataFusion CLI v29.0.0
❯ create table foo(x varchar) as values ('foo'), ('bar');
0 rows in set. Query took 0.006 seconds.

❯ create table foo_dict as select arrow_cast(x, 'Dictionary(Int32, Utf8)') as x from foo;
0 rows in set. Query took 0.005 seconds.

❯ select upper(x) from foo_dict;
+-------------------+
| upper(foo_dict.x) |
+-------------------+
| FOO               |
| BAR               |
+-------------------+
2 rows in set. Query took 0.004 seconds.
```

And in fact the plan looks reasonable (though not performant) by automatically casting the argument to a varchar

```
❯ explain select upper(x) from foo_dict;
+---------------+-----------------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                          |
+---------------+-----------------------------------------------------------------------------------------------+
| logical_plan  | Projection: upper(CAST(foo_dict.x AS Utf8))                                                   |
|               |   TableScan: foo_dict projection=[x]                                                          |
| physical_plan | ProjectionExec: expr=[upper(CAST(x@0 AS Utf8)) as upper(foo_dict.x)]                          |
|               |   MemoryExec: partitions=16, partition_sizes=[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] |
|               |                                                                                               |
+---------------+-----------------------------------------------------------------------------------------------+
2 rows in set. Query took 0.004 seconds.
```

Thus I am not sure why it was failing in IOx in https://github.com/influxdata/influxdb_iox/pull/8479 🤔  I think more investigation is needed

**Comment by alamb** [comment]
This query now works in DataFusion so closing this ticket. Sorry for the confusion
