### ISSUE TITLE
Change logical plan TableScan to use OwnedTableReference for table_name

### ISSUE THREAD

**Issue by Jefffrey** [apache/arrow-datafusion#5522]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

From discussion https://github.com/apache/arrow-datafusion/pull/5343#discussion_r1119370108

https://github.com/apache/arrow-datafusion/pull/5343 introduces `OwnedTableReference` for column relation, and this is used to compare with `table_name` in `TableScan`

**Describe the solution you'd like**

Change `table_name` in `TableScan` to be an `OwnedTableReference`, and fix this check:

https://github.com/apache/arrow-datafusion/blob/35a3acf562e4e982564f1ebb1b1ce1edef07a1b1/datafusion/optimizer/src/push_down_projection.rs#L500

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
I hit this issue -- specifically trying to call LogicalPlan::scan with a table name `TheMeasurement` (which after https://github.com/apache/arrow-datafusion/pull/5343 is parsed to `themeasurement`) which causes "column not found" issues.

I plan to fix this issue
