### ISSUE TITLE
Release script needs updating to change top-level workspace.package version

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#5548]
**Describe the bug**

Because of the changes in https://github.com/apache/arrow-datafusion/pull/5519, we need to update the `dev/update_datafusion_version.sh` script. I have made most of the changes in https://github.com/apache/arrow-datafusion/pull/5539, but it does not update the top-level version in `workspace.package` and I updated that manually for this release.

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by Jefffrey** [comment]
Looks to have been resolved by https://github.com/apache/arrow-datafusion/pull/5767

cc @andygrove @alamb

**Comment by alamb** [comment]
I agree -- it looks like the code is present in https://github.com/apache/arrow-datafusion/blob/d24228a6b9552f2dce166836e60c1b928116933f/dev/update_datafusion_versions.py#L49-L62

Thanks @Jefffrey
