### ISSUE TITLE
Dataframe describe() method cannot handle dataframes without a numeric type column

### ISSUE THREAD

**Issue by Jefffrey** [apache/arrow-datafusion#5558]
**Describe the bug**

If calling `describe(...)` on a dataframe without a numeric type method then it returns an error.

**To Reproduce**

```rust
    ctx.sql("select 'a' as a")
        .await?
        .describe()
        .await?
        .show()
        .await?;
```

Causes error:

```
Error: Plan("Aggregate requires at least one grouping or aggregate expression")
```

**Expected behavior**

Either be able to handle this properly or return a more informative error

**Additional context**

Caused by filters for certain aggregations:

https://github.com/apache/arrow-datafusion/blob/ecbc843a1a8c38b2466748bc92a6e22ce08d51ed/datafusion/core/src/dataframe.rs#L371-L449

- See mean, std, median

Also worth testing for if the input dataframe has only boolean boolean/binary column, like so:

```rust
    ctx.sql("select true as a")
        .await?
        .describe()
        .await?
        .show()
        .await?;
```

- See max & min in above code snippet

**Comment by jiangzhx** [comment]
```
import polars as pl
pl.DataFrame({"bool": [True, False, True]}).describe()
```
work well on polars
```
┌────────────┬──────────┐
│ describe   ┆ bool     │
│ ---        ┆ ---      │
│ str        ┆ f64      │
╞════════════╪══════════╡
│ count      ┆ 3.0      │
│ null_count ┆ 0.0      │
│ mean       ┆ 0.666667 │
│ std        ┆ 0.57735  │
│ min        ┆ 0.0      │
│ max        ┆ 1.0      │
│ median     ┆ 1.0      │
└────────────┴──────────┘
```
