### ISSUE TITLE
Implement `to_unixtime` function

### ISSUE THREAD

**Issue by waynexia** [apache/arrow-datafusion#5568]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Like `from_unixtime` in #2871, `to_unixtime` is sometimes also useful when compared with other data that is in UNIX timestamp format or don't want to care about the timezone.

**Describe the solution you'd like**

Take [`to_unix_timestamp`](https://spark.apache.org/docs/2.3.0/api/sql/index.html#to_unix_timestamp) in spark as example:
```
select to_unixtime(ts) from t;

-> 1460041200
```

**Describe alternatives you've considered**

**Additional context**

**Comment by comphead** [comment]
@waynexia As a workaround please use #5555 

```
select extract(epoch from ts)
```

@alamb here we comes again to spark functions, should we support all of them like listed here https://spark.apache.org/docs/3.2.0/api/sql/

**Comment by alamb** [comment]
> should we support all of them like listed here https://spark.apache.org/docs/3.2.0/api/sql/ even if not all of them compatible with PG

I don't think we have a strong or consistent story here -- my personal opinion is to focus on postgres compatibility, and only add spark functions for thing that have no postgres equivalent. 

Given DataFusion has all the extension points already, maybe we could add a separate crate for "spark_extensions" or something 🤔  that way anyone who wanted the spark library functions could have them if they wanted but it could be opt in.

**Comment by waynexia** [comment]
>@waynexia As a workaround please use https://github.com/apache/arrow-datafusion/pull/5555

Thanks for this 👍 

>Given DataFusion has all the extension points already, maybe we could add a separate crate for "spark_extensions" or something

Also makes sense to me. We can implement and provide it in a separate crate (something like `datafusion-spark-ext`?) so that others can easily integrate wanted functions (like `to_unixtime` in this ticket) while keeping the core clean. I'd like to help if we decide to do it.

**Comment by alamb** [comment]
Cross posting link to discussion on spark functions: https://github.com/apache/arrow-datafusion/issues/5600

**Comment by Tangruilin** [comment]
@alamb I can help with this.

Please assign to me

**Comment by alamb** [comment]
Thanks @Tangruilin  -- you already have  several items assigned to you:

https://github.com/apache/arrow-datafusion/issues/assigned/Tangruilin

If there are some that you are not working on, or we found blockers, perhaps you can unassign yourself so it is clear what the status is.

Thank you so much for your help

**Comment by Tangruilin** [comment]
> Thanks @Tangruilin -- you already have several items assigned to you:
> 
> https://github.com/apache/arrow-datafusion/issues/assigned/Tangruilin
> 
> If there are some that you are not working on, or we found blockers, perhaps you can unassign yourself so it is clear what the status is.
> 
> Thank you so much for your help

I unassign #8824, other issues i am all working on now.
I will finish them in two weeks.
