### ISSUE TITLE
`LogicalPlan::replace_params_with_values` should not take `&Vec<_>`

### ISSUE THREAD

**Issue by kawadakk** [apache/arrow-datafusion#5573]
**Describe the bug**
[`LogicalPlan::replace_params_with_values`](https://docs.rs/datafusion-expr/19.0.0/datafusion_expr/logical_plan/enum.LogicalPlan.html#method.replace_params_with_values) takes `&Vec<ScalarValue>`, forcing the caller to collect inputs in `Vec<ScalarValue>` (instead of an arbitrary continuous container) with no benefits.

https://github.com/apache/arrow-datafusion/blob/aeb593f719508973fa4564a32bc2adc767c3713e/datafusion/expr/src/logical_plan/plan.rs#L630-L636

**To Reproduce**
N/A

**Expected behavior**
A common practice, enforced by [the `ptr_arg` Clippy lint](https://rust-lang.github.io/rust-clippy/master/index.html#ptr_arg), is to pass such parameters by slice references (`&[ScalarValue]`).

**Additional context**
N/A

**Comment by HaoYang670** [comment]
Thank you, @kawadakk, for reporting this. I will try to fix it this weekend.
