### ISSUE TITLE
CREATE TABLE defaults to NON nullable (should be nullable to follow postgres)

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#5575]
`CREATE TABLE` statements create tables with non-nullable columns by default, which contradicts PostgreSQL 15.

```sql
CREATE TABLE table_without_values(field1 BIGINT, field2 BIGINT);
```
DDL query. It defaults to non-nullable columns while creating a table, which is not the case in [PostgreSQL 15](https://www.postgresql.org/docs/current/sql-createtable.html).

> NULL
> The column is allowed to contain null values. This is the default.
> This clause is only provided for compatibility with non-standard SQL databases. Its use is discouraged in new applications.

PS: The code piece that results non-nullable default:
https://github.com/apache/arrow-datafusion/blob/1a22f9fd436c9892566b668e535e0d6c8cb9fbd3/datafusion/sql/src/planner.rs#L127-L144

_Originally posted by @metesynnada in https://github.com/apache/arrow-datafusion/issues/5520#issuecomment-1465991022_
            

# Desired behavior:
Make the default columns NULLABLE 

this should work (and insert a single null value into `foo`)

```sql
create table foo(x int);
insert into foo values (null);
```

**Comment by alamb** [comment]
I think this is a good first issue as the desired behavior is well understood and the code location is identified

**Comment by Weijun-H** [comment]
I tried to test `CREATE TABLE table_without_values(field1 BIGINT NULL, field2 BIGINT NULL);`, but found `Error: NotImplemented("Only `CREATE TABLE table_name AS SELECT ...` statement is supported")`. Is it reasonable?

**Comment by metesynnada** [comment]
> I tried to test `CREATE TABLE table_without_values(field1 BIGINT NULL, field2 BIGINT NULL);`, but found `Error: NotImplemented("Only `CREATE TABLE table_name AS SELECT ...` statement is supported")`. Is it reasonable?

>  I can create a separate ticket for traditional create table stmt

Given that MemTable can now be appended, incorporating support for it in the planner is a simple task. There is no need to restrict the creation of an empty memory table  @comphead .

Also, I believe this would also make for a good first issue.

**Comment by alamb** [comment]
> @alamb I can create a separate ticket for traditional create table stmt

Thank you @comphead  -- that would be great!
