### ISSUE TITLE
How to modify `OptimizerRule` fields?

### ISSUE THREAD

**Issue by sarahyurick** [apache/arrow-datafusion#5583]
Hi, I was wondering if it's currently possible to change or update `OptimizerRule` fields within the `try_optimize` function? Below, I've detailed the issues I'm running into and some things I've tried that didn't work.

**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
I'm currently working on an optimizer rule for the Dask-SQL project, but I'm running into some annoying logic with DataFusion's optimizer. Basically, I'd like to be able to constantly update a field of the new rule's struct within the `try_optimize` function, but because it takes in a reference to the struct instead of the struct itself ([source code](https://github.com/apache/arrow-datafusion/blob/d0bd28eef34ca001d5e43d2732761a1b4cf09c71/datafusion/optimizer/src/optimizer.rs#L53)), the field can't be updated. To give a high-level example, let's say I have an optimizer rule:

```
pub struct MyRule {
    my_set: HashSet<Expr>,
}
```

It would be nice to be able to use `ApplyOrder::TopDown` with it, but as I'm going down the `LogicalPlan` I want to insert any filters from any `Join` in the plan to `my_set`, so that this information can later be used to update a `TableScan`. However, within the `try_optimize` function, doing something like `self.my_set.insert(...)` isn't valid because it's a `&MyRule` and not a `MyRule`.

**Describe the solution you'd like**
I'm not sure if there's already a way to modify these fields when desired, but from my experimentation I couldn't get it to work. One solution I imagine is to change [`&self`](https://github.com/apache/arrow-datafusion/blob/d0bd28eef34ca001d5e43d2732761a1b4cf09c71/datafusion/optimizer/src/optimizer.rs#L61) to `self`, although I'm not sure if that's desirable.

**Describe alternatives you've considered**
I also tried within the `MyRule` implementation to create new instances of `MyRule` with logic like:

```
fn try_optimize(
        &self,
        plan: &LogicalPlan,
        _config: &dyn OptimizerConfig,
    ) -> Result<Option<LogicalPlan>> {
        let my_expr = get_expr_func(&plan);
        let mut new_set = self.my_set.clone();
        new_set.insert(my_expr);
        let new_self = MyRule { my_set: new_set };
        // Some type of conditions, extra logic, etc. for when to recurse with try_optimize
        &new_self.try_optimize(plan, _config)
}
```

but was seeing some wonky logic where the updates would only carry to the next step and not through the rest of the steps down the plan. However, a similar solution could be possible.

I also tried something like:

```
impl MyRule {
    pub fn new() -> Self {
        Self { my_set: HashSet::new() }
    }
    
    pub fn set_myset(mut self, value: HashSet<Expr>) {
        self.my_set = value;
    }
}

impl OptimizerRule for MyRule {
    fn name(&self) -> &str {
        "my_rule"
    }

    fn apply_order(&self) -> Option<ApplyOrder> {
        Some(ApplyOrder::TopDown)
    }

    fn try_optimize(
        &self,
        plan: &LogicalPlan,
        _config: &dyn OptimizerConfig,
    ) -> Result<Option<LogicalPlan>> {
        let new_set = HashSet::from([...]);
        self.set_myset(new_set);
    }
}
```

which didn't work either.

**Additional context**
This isn't blocking any of my work on the Dask-SQL side; it's just that currently, the workaround I have to use requires a lot more lines of code than I would imagine should be needed.

@andygrove @jdye64 I wanted to know your thoughts on this?

**Comment by sarahyurick** [comment]
If it would be helpful, I can also provide a full Rust file example/create a Dask-SQL branch to further demonstrate the trouble I'm having. A simple example I've been working with is the case where we just have a `counter` numeric field and are trying to increment the counter by 1 between steps.

**Comment by sarahyurick** [comment]
Thanks @jdye64 ! Using `&mut self` makes sense to me. I've started working toward a solution in https://github.com/apache/arrow-datafusion/pull/5605

**Comment by alamb** [comment]
FYI @jackwener  I think recently did some work in this area for avoiding optimizer state -- they maybe have some ideas that can help

**Comment by tustvold** [comment]
This might be a naive question, but shouldn't OptimizerRules be pure, i.e. side-effect free. I think taking `&mut self` not only runs the risk of making OptimizerRule sensitive but also lead to unbounded memory usage - the `OptimizerRule` are created once per `SessionContext`.

I'm not familiar with the more recent changes in this space, but I would have expected the `OptimizerRule` to walk the tree itself to perform this rewrite, similar to how `PhysicalOptimizerRule` such as `EnforceDistribution` perform nested rewrites

**Comment by alamb** [comment]
> I'm not familiar with the more recent changes in this space, but I would have expected the OptimizerRule to walk the tree itself to perform this rewrite, similar to how PhysicalOptimizerRule such as EnforceDistribution perform nested rewrites

Yes, I think that is effectively what @jackwener did

**Comment by alamb** [comment]
Specifcally the tickets linked to https://github.com/apache/arrow-datafusion/issues/4267

**Comment by sarahyurick** [comment]
Ah okay, if it's preferred that the fields remain immutable, then I'll just have to do it a different way. Thanks for the responses!
