### ISSUE TITLE
Warnings about incorrect README location when publishing crates

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#5596]
**Describe the bug**

There was a recent change to add a `[workspace.package]` section in the top level Cargo.toml, with the readme specified there. This does not appear to be working as intended, as it is trying to publish the top-level README in each crate.

```
warning: readme `../../README.md` appears to be a path outside of the package, but there is already a file named `README.md` in the root of the package. The archived crate will contain the copy in the root of the package. Update the readme to point to the path relative to the root of the package to remove this warning.
```

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by alamb** [comment]
Closed by https://github.com/apache/arrow-datafusion/pull/7964
