### ISSUE TITLE
`timestamp` - interval results in `The type of Timestamp(Nanosecond, Some("+00:00")) Minus Utf8 of binary physical should be same`

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#5650]
**Describe the bug**
I ran a query and got an internal error

**To Reproduce**
Using `datafusion-cli`:

```sql
❯ create table foo(x timestamp) as select '2023-03-01'::timestamp;
0 rows in set. Query took 0.002 seconds.
❯ select * from foo;
+---------------------+
| x                   |
+---------------------+
| 2023-03-01T00:00:00 |
+---------------------+
1 row in set. Query took 0.001 seconds.
❯ select * from foo where x < now() - '1 day';
The type of Timestamp(Nanosecond, Some("+00:00")) Minus Utf8 of binary physical should be same. This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```

Note it is possible to use the `interval` syntax things work out correctly

```
❯ select * from foo where x < now() - interval '1 day';
+---------------------+
| x                   |
+---------------------+
| 2023-03-01T00:00:00 |
+---------------------+
```

Note if you try to use the same predicate outside of the where clause, we get a planning error (correctly):
```
❯ select now()  - '1 day';
Error during planning: 'Timestamp(Nanosecond, Some("+00:00")) - Utf8' can't be evaluated because there isn't a common type to coerce the types to
```

**Expected behavior**
1. (minimum) `select * from foo where x < now() - '1 day';` should produce a planning error (rather than an internal error)
2. (ideal) Make the query work

**Additional context**

**Comment by comphead** [comment]
@alamb `select * from foo where x < now() - '1 day'` such kind of queries doesn't work in PG. I would think it is expected behavior as '1 day' is really string.

**Comment by alamb** [comment]
> @alamb select * from foo where x < now() - '1 day' such kind of queries doesn't work in PG. I would think it is expected behavior as '1 day' is really string.

I was imagining that we could coerce Utf8 --> interval automatically -- see https://github.com/apache/arrow-datafusion/issues/5652

For this ticket, I think we should generate a `Plan` error rather than an `Internal` error
