### ISSUE TITLE
Implement `COPY ...  TO` statement 

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#5654]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
I would like to parquet data from one format to another, for example to see the effects of page pruning -- https://github.com/apache/arrow-datafusion/issues/4085 or different orderings on compression and other properties

arrow-rs and DataFusion have all the parts we need (reading from files, sorting, writing to files) we just now need to put them together

We do have a  very specialized version in the tpch benchmark driver
https://github.com/apache/arrow-datafusion/blob/26e1b20ea3362ea62cb713004a0636b8af6a16d7/benchmarks/src/tpch.rs#L332-L400

**Describe the solution you'd like**
I would like DataFusion to support duckdb style `COPY` sql statements 

For example:

```sql
-- export the table `t` to data.parquet
COPY t TO 'data.parquet' (FORMAT PARQUET);
-- export as parquet, compressed with ZSTD, with a row_group_size of 100000
COPY t TO 'data.parquet' (FORMAT PARQUET, COMPRESSION ZSTD, ROW_GROUP_SIZE 100000);
--- export the output of of a query `SELECT * FROM tbl`
COPY (SELECT * FROM tbl ORDER BY time) TO 'data.parquet' (FORMAT PARQUET);
```

Reference:
1. https://duckdb.org/docs/sql/statements/copy
2. https://duckdb.org/docs/sql/statements/export

**Describe alternatives you've considered**
@metesynnada  is working on `INSERT INTO` style syntax in https://github.com/apache/arrow-datafusion/issues/5130

Bonus points for CSV support (ideally the code structure will allow support in the long term but not as part of the initial PR)

```sql
-- export as CSV with the given options
COPY t TO 'data.csv'  (FORMAT CSV, DELIMITER '|', HEADER);
```

**Additional context**

 https://github.com/apache/arrow-datafusion/issues/5130#issuecomment-1430323461

**Comment by doki23** [comment]
If I'm not mistaken, we could implement it by deleting all the target files and then executing an `insert into t select ... from ...` query as #5130 proposes.
I'd like to contribute this if no one is working on it.

**Comment by metesynnada** [comment]
At the moment, we do not support the `INSERT INTO` operation for files. However, we have developed an implementation and are awaiting the version updates of arrow-rs and object-store. You can find more details about this implementation in the following pull request: https://github.com/synnada-ai/arrow-datafusion/pull/62.

In addition to this, the `COPY TO` syntax is a widely adopted method for sinking data. Therefore, we should introduce a new API in the `TableProvider` to accommodate this functionality.

**Comment by doki23** [comment]
> Therefore, we should introduce a new API in the TableProvider to accommodate this functionality.

`COPY TO` is close to `INSERT INTO SELECT FROM`. The difference is copy needs clean up existed data while insert not. So maybe they could share the same api like `sink(&self, state: &SessionState, input: &LogicalPlan, truncate: bool)`?

**Comment by metesynnada** [comment]
The similarity you mention does not apply to `MemTable` or `ViewTable`, `INSERT INTO` does not imply sinking to a file in these cases. It's possible that some `dyn TableProvider` implementations may not support the `INSERT INTO` operation, while others may not implement the `COPY to` operation. While there is some resemblance, it is essential not to over-generalize the behavior of the `ListingTable`.

Maybe we can find a better way to reduce duplicates in logic.

**Comment by alamb** [comment]
Thanks @timrobertson100  -- I think we are quite close to having all the pieces -- e.g. https://github.com/apache/arrow-datafusion/pull/6049 from @metesynnada

**Comment by doki23** [comment]
I'm busy recently and not working on it. Anyone interesting feels free to take it.

**Comment by aprimadi** [comment]
https://github.com/sqlparser-rs/sqlparser-rs/issues/857

**Comment by metesynnada** [comment]
> The current sqlparser implementation doesn't support arbitrary query as a source in `COPY <source> TO ..` statement. This issue and pull request address that.
> 
> [sqlparser-rs/sqlparser-rs#857](https://github.com/sqlparser-rs/sqlparser-rs/issues/857)

Yeah, it would be a great contribution.

**Comment by alamb** [comment]
I had some free time this afternoon and so I hacked up an initial implementation here: https://github.com/apache/arrow-datafusion/pull/6313

I was able to write a custom parser in DataFusion, as well as hook  it up via the same mechanism as used by `CREATE TABLE AS SELECT`.

**Comment by alamb** [comment]
The basic feature was completed by @devinjdangelo  in https://github.com/apache/arrow-datafusion/pull/7283. There are still some pieces left but I am closing this ticket as done for now
