### ISSUE TITLE
`date_bin` doesn't work with `months` or `years`

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#5689]
### Describe the bug

`date_bin('1 month', column1)` does not work, but (confusingly) `date_bin('1 day', column1)` does

### To Reproduce

In `datafusion-cli`: 

```sql
❯ select date_bin('1 month', column1)
from (values
  (timestamp '2022-01-01 00:00:00'),
  (timestamp '2022-01-01 01:00:00'),
(timestamp '2022-01-02 00:00:00')
) as sq;
Error during planning: Coercion from [Interval(YearMonth), Timestamp(Nanosecond, None)] to the signature OneOf([Exact([Interval(DayTime), Timestamp(Nanosecond, None), Timestamp(Nanosecond, None)]), Exact([Interval(DayTime), Timestamp(Nanosecond, None)])]) failed.
```

Note using `1 hour` works great:
```sql
select date_bin('1 hour', column1) 
from (values 
  (timestamp '2022-01-01 00:00:00'), 
  (timestamp '2022-01-01 01:00:00'), 
(timestamp '2022-01-02 00:00:00')
) as sq;

+------------------------------------+
| datebin(Utf8("1 hour"),sq.column1) |
+------------------------------------+
| 2022-01-01T00:00:00                |
| 2022-01-01T01:00:00                |
| 2022-01-02T00:00:00                |
+------------------------------------+
3 rows in set. Query took 0.001 seconds.
```

### Expected behavior

I expect `date_bin('1 month')` to work and return the same value for all three rows

```
| 2022-01-01T00:00:00                |
``` 

### Workarounds

One can use `DATE_TRUNC('month',time)` to get monthly aggregates. It doesn't work with intervals of multiple months though. (thanks to our user for this idea!)

### Additional context

This was reported by an IOx user

If you look at the error, the problem is that `Interval(YearMonth)` has a different unit than `Interval(DayTime)`

That happens because the code that parses `'1 hour'` ([source link](https://github.com/apache/arrow-datafusion/blob/1ddc4b904028e456c65b1c50176a3525158cb3f3/datafusion/common/src/parsers.rs#L119-L269)) determines it should be `Interval(DayTime)` but that `'1 month'` is `Interval(YearMonth)` (as 1 month can not correctly be represented as a `Interval(DayTime)`).

Thanfully, the `Interval(MonthDayNano)` type ([doc link](https://docs.rs/arrow/35.0.0/arrow/datatypes/struct.IntervalMonthDayNanoType.html)) was introduced to solve this problem and can represent the full range.

Thus my desired solution is:
1. Change the signature of date_bin to take a `Interval(MonthDayNano)`
2. Change the parsing of literal intervals to produce `Interval(MonthDayNano)` always -- see https://github.com/apache/arrow-datafusion/issues/5651
3. Add equivalent coercion rules for Interval(MonthDayNano)

**Comment by alamb** [comment]
I plan to look into this issue later in the week

**Comment by NGA-TRAN** [comment]
I start looking into this. The `date_bin` on month interval no longer errors out

```SQL
select date_bin('1 month', column1)
from (values
  (timestamp '2022-01-01 00:00:00'),
  (timestamp '2022-01-01 01:00:00'),
(timestamp '2022-01-02 00:00:00')
) as sq;
+-------------------------------------+
| datebin(Utf8("1 month"),sq.column1) |
+-------------------------------------+
| 2021-12-29T00:00:00                 |
| 2021-12-29T00:00:00                 |
| 2021-12-29T00:00:00                 |
+-------------------------------------+
3 rows in set. Query took 0.008 seconds.
```

I will read the `date_bin` document to see if this is the right output

**Comment by NGA-TRAN** [comment]
So here are things I think we want to do:

1. Make date_bin on constant and column data consistent
2. If we decide to throw error, make the message more general and include both month & year as in Postgres one
3. Why PostgreSQL throw error on Months/years? Is it because they do not mean much?
4. If we want to support month/year, we need to define the expect behaviors:

**What is the right answers for these?**

```SQL
select date_bin('1 hour', column1, TIMESTAMP '1970-01-01T00:00:00Z').  -- note it starts from first day of the month
from (values
  (timestamp '2022-01-01 00:00:00'),     --  expected answer: '2022-01-01 00:00:00' ?
  (timestamp '2022-01-01 01:00:00'),     --  expected answer: '2022-01-01 00:00:00' ?   note the hour is 0
  (timestamp '2022-01-02 00:00:00'),    --  expected answer: '2022-01-01 00:00:00' ?   note first day of Jan
  (timestamp '2022-02-02 00:00:00'),   --  expected answer: '2022-02-01 00:00:00' ?   note first day of Feb
  (timestamp '2022-02-15 00:00:00'),     -- expected answer: '2022-02-01 00:00:00' ?   note first day of Feb
  (timestamp '2022-03-31 00:00:00')    --  expected answer: '2022-03-01 00:00:00' ?   note first day of Mar
) as sq;
```

**How about if the start is  not first day of the month?**

select date_bin('1 hour', column1, TIMESTAMP '1970-01-09T05:45:00Z')
from (values
  (timestamp '2022-01-01 00:00:00'),    -- expected answer: '2021-12-09 05:45:00' ?
  (timestamp '2022-01-01 01:00:00'),    -- expected answer: '2021-12-09 05:45:00' ?
  (timestamp '2022-01-02 00:00:00'),   -- expected answer: '2021-12-09 05:45:00' ?
  (timestamp '2022-02-02 00:00:00'),   -- expected answer: '2022-01-09 05:45:00' ?
  (timestamp '2022-02-15 00:00:00'),   -- expected answer: '2022-02-09 05:45:00' ?
  (timestamp '2022-03-31 00:00:00')    -- expected answer: '2022-02-09 05:45:00' ?
) as sq;

**Comment by NGA-TRAN** [comment]
[Chrono's month](https://docs.rs/chrono/0.4.24/chrono/struct.Months.html#impl-Add%3CMonths%3E-for-DateTime%3CTz%3E) seems provide what we need

So task for this
- [ ] Make `date_bin` on constant and column data consistent
- [ ] Support `month` interval using chromo's month

**Comment by NGA-TRAN** [comment]
Update: 2 major things I need to do:

1. We should support `IntervalMonthDayNano` [here](https://github.com/apache/arrow-datafusion/blob/263bded3e250311311b136182fec54228cc09166/datafusion/physical-expr/src/datetime_expressions.rs#L390). This query hits this:2. 
   ```SQL
   SELECT DATE_BIN(INTERVAL '1 month', TIMESTAMP '2022-01-01 00:00:00Z', TIMESTAMP '1970-01-01T00:00:00Z');
   ```

3. We should don't convert month interval into `IntervalDayTime` that leads us [here](https://github.com/apache/arrow-datafusion/blob/263bded3e250311311b136182fec54228cc09166/datafusion/physical-expr/src/datetime_expressions.rs#L375). This query hist this:
   ```SQL
   select date_bin('1 month', column1)
from (values
  (timestamp '2022-01-01 00:00:00')
) as sq;
   ```

**Comment by alamb** [comment]
I believe @NGA-TRAN  is working on this
