### ISSUE TITLE
Support JOIN table alias

### ISSUE THREAD

**Issue by houqp** [apache/arrow-datafusion#57]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Support self join queries with table alias:

```sql
SELECT * FROM t1 JOIN t1 as t2 ON t1.id = t2.id
```

**Describe the solution you'd like**

Datafusion should execute this query without error.

**Comment by Dandandan** [comment]
This might also resolve TPC-H queryes 7 / 8:
 Error: Plan("Schema contains duplicate unqualified field name \'n_nationkey\'")
