### ISSUE TITLE
Executing LocalLimitExec with no column should not return an Err 

### ISSUE THREAD

**Issue by kazuyukitanimura** [apache/arrow-datafusion#5701]
### Describe the bug

This is similar to https://github.com/apache/arrow-datafusion/issues/4911
Executing LocalLimitExec with no column will return an Err ArrowError(InvalidArgumentError("must either specify a row count or at least one column")).

### To Reproduce

It may not be hitting this error from SQL query directly. For some query optimization might create projection with no column. I got this error when converting optimized query from other query engine to DataFusion.

**Comment by comphead** [comment]
HI @kazuyukitanimura 
Looks like it comes from arrow-rs, not from datafusion itself. 
https://github.com/apache/arrow-rs/blob/4e4a7f7dbfa348d97a806240954eec8402d3b259/arrow-array/src/record_batch.rs#L152


```
    /// Optional row count, useful for specifying a row count for a RecordBatch with no columns
    pub row_count: Option<usize>,
```
