### ISSUE TITLE
Only single quote string is allowed in where clause?

### ISSUE THREAD

**Issue by NiwakaDev** [apache/arrow-datafusion#5746]
### Describe the bug

Right now, I guess that we can't use `double quote` in `where` clause, like so:

```sql
SELECT * FROM example where cpu = "host1"
```

### To Reproduce

Execute the following commands on the terminal:

```
touch example.csv
echo "cpu, memory" > example.csv
echo "host1, 2" >> example.csv
```

And then execute `cargo run` for the following
```rust

use datafusion::prelude::*;


#[tokio::main]
async fn main() -> datafusion::error::Result<()> {
  // register the table
  let ctx = SessionContext::new();
  ctx.register_csv("example", "example.csv", CsvReadOptions::new()).await?;

  // create a plan to run a SQL query
  let df = ctx.sql(r#"SELECT * FROM example where cpu = "host1""#).await?;

  // execute and print results
  df.show().await?;
  Ok(())
}
```

And then we get the following error:
```
Error: SchemaError(FieldNotFound { field: Column { relation: None, name: "host1" }, valid_fields: [Column { relation: Some("example"), name: "cpu" }, Column { relation: Some("example"), name: " memory" }] })
```

### Expected behavior

The expected behavior is to allow users to use `double quote` such as `single quote` in `where` clause, like so:

```
+-------+---------+
| cpu   |  memory |
+-------+---------+
| host1 |  2      |
+-------+---------+
```

### Additional context

Related to https://github.com/GreptimeTeam/greptimedb/issues/1210.

**Comment by andygrove** [comment]
> That is correct -- in sql (at least in postgres),

Also correct in ANSI SQL specification.

Spark SQL differs from ANSI in that it allows double quotes for string literals and uses backticks for identifiers, so maybe you are looking for Spark SQL compatibility.

**Comment by NiwakaDev** [comment]
Thanks!!!
