### ISSUE TITLE
Remove type coercion of case expression in Expr::Schema

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#5821]
As part of fixing https://github.com/apache/arrow-datafusion/issues/5733 in https://github.com/apache/arrow-datafusion/pull/5734 we installed a workaround that manipulates the calculation of the type of a Case expression

A better solution would be to fix the expression initially (by coercing the types correctly), but that was blocked on https://github.com/apache/arrow-datafusion/issues/5733

Once https://github.com/apache/arrow-datafusion/issues/5733 is complete, we should remove the workaround put in Expr::schema

Details below:

              The type coercion is implemented as an optimizer - and it changes schemas of particular `Expr`essions.
And it **takes care** of `Expr::Case`.

But `Expr::Projection` caches the schema in itself - so it is not updated! Therefore we get a mismatch between declared schema vs batch schema.

Essentially this PR makes `Expr::Case` to **not** change a schema during the coercion optimizer.

_Originally posted by @mslapek in https://github.com/apache/arrow-datafusion/pull/5734#discussion_r1153540699_

**Comment by jackwener** [comment]
I'm working on it
