### ISSUE TITLE
change all quotes to smart quotes within error messages

### ISSUE THREAD

**Issue by Jimexist** [apache/arrow-datafusion#583]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

so far some of the test messages require escaping either single `'` or double `"` quotes. this is error prone and and sometimes introduces confusions.

**Describe the solution you'd like**

we can easily resolve this issue by replacing all current and future usage of quotes into smart quotes `‘` `’` and `“` `”`

**Describe alternatives you've considered**

**Additional context**

**Comment by Jimexist** [comment]
@Dandandan @alamb @houqp and @jorgecarleitao WDYT?

**Comment by Dandandan** [comment]
I am not sure changing the error messages for the sake of easier testing makes sense to me.

What about using raw string literals in the tests instead?https://rahul-thakoor.github.io/rust-raw-string-literals/

**Comment by Jimexist** [comment]
> I am not sure changing the error messages for the sake of easier testing makes sense to me.
> 
> What about using raw string literals in the tests instead?https://rahul-thakoor.github.io/rust-raw-string-literals/

it's a great point - i'll close this in #581
