### ISSUE TITLE
Additional math functions

### ISSUE THREAD

**Issue by izveigor** [apache/arrow-datafusion#5838]
### Is your feature request related to a problem or challenge?

Arrow-DataFusion at this stage has few mathematical expressions and operations. In this issue I describe possible futures features about the problem.

Most significant features:
- [x] Cbrt (Support: PostgreSQL, Rust, Numpy) https://github.com/apache/arrow-datafusion/pull/5839
- [x] Mathematical constant Pi (3,1415..) (Support: PostgreSQL, Rust, Numpy, MySQL) https://github.com/apache/arrow-datafusion/pull/5965
- [ ] Factorial (Support: PostgreSQL, Rust, Numpy)
- [x] Hyperbolic functions (Support: PostgreSQL, Rust, Numpy) https://github.com/apache/arrow-datafusion/pull/5884
- [x] Degrees, Radians (Support: PostgreSQL, Numpy, Rust, MySQL) https://github.com/apache/arrow-datafusion/pull/6023

Least Significant features:
- [ ] GCD and LCM (Numpy)
- [ ] Support radian/degree trigonometric functions (Like PostgreSQL COS/COSD) (Support: PostgreSQL)

### Describe the solution you'd like

Series of PR, active discussion of features.

### Describe alternatives you've considered

The significance of some features can be disproven as a result of conversations.

### Additional context

Sources:
- PostgreSQL math functions: https://www.postgresql.org/docs/current/functions-math.html
- MySQL math functions: https://dev.mysql.com/doc/refman/8.0/en/mathematical-functions.html
- Rust f64 in-built functions: https://doc.rust-lang.org/std/primitive.f64.html
- Numpy (using with Pandas) math functions: https://numpy.org/doc/stable/reference/routines.math.html

**Comment by mingmwang** [comment]
👍

**Comment by waynexia** [comment]
FYI: it also helps to integrate PromQL's [function](https://prometheus.io/docs/prometheus/latest/querying/functions/#trigonometric-functions), thanks for this 👍
