### ISSUE TITLE
`LogicalPlan::replace_params_with_values` panics if a placeholder with id `$0` is present

### ISSUE THREAD

**Issue by kawadakk** [apache/arrow-datafusion#5856]
### Describe the bug

`LogicalPlan::replace_placeholders_with_values` subtracts one from a parsed `usize` value, which may result in a panic due to integer overflow.

<https://github.com/apache/arrow-datafusion/blob/fd350fa176b11ae6dc82d7813ed57290ac026c26/datafusion/expr/src/logical_plan/plan.rs#L617-L623>

### Expected behavior

Returning an `Err(_)` value to indicate the problem, like it does in other error cases.

### Additional context

Similar to #5786 but concerns a later stage.

**Comment by kawadakk** [comment]
This also panics if `id` is empty.

**Comment by alamb** [comment]
Thanks @kawadakk  -- I agree this is definitely a bug.
