### ISSUE TITLE
`datafusion::physical_expr::datetime_expressions::to_timestamp_millisto_timestamp_millis`  Unsupported data type Timestamp(Nanosecond, None)

### ISSUE THREAD

**Issue by dust1** [apache/arrow-datafusion#5857]
### Describe the bug

When I was in use date_bin functions, it needs to be the result of milliseconds. I try to use this method for the following transformations:
```rust
        let arrow_record_batch: ArrowRecordBatch = ....;
        let columns = arrow_record_batch.columns();
        let nanosecond_columns = ColumnarValue::Array(columns[0].clone());
        let millis_columns = to_timestamp_millis(&[nanosecond_columns ]);
        match result {
            Ok(m) => {
                println!("cast ok:{:?}", m);
            },
            Err(e) => {
                println!("cast fail:{}", e);
            }
        };
```
the error info is :
```
cast fail:Internal error: Unsupported data type Timestamp(Nanosecond, None) for function to_timestamp_millis. This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```

### Expected behavior

the type cast was ok

**Comment by comphead** [comment]
Probably the field type was another. `to_timestamp_millis ` supports the cast from Utf8/LargeUtf8

**Comment by waitingkuo** [comment]
https://github.com/apache/arrow-datafusion/blob/6d1ec7ae22fd2181be32d18a4a269777755ae9b1/datafusion/physical-expr/src/datetime_expressions.rs#L138-L145

`to_timestamp_millis` uses `string_to_timestamp_nanos_shim` which only accept `&str` as input

**Comment by dust1** [comment]
Thank you very much two answer, I now through ` TimestampMillisecondBuilder ` for type conversion, maybe I can try to assemble it for Expr to invoke another ` to_timestamp_millis `

**Comment by waitingkuo** [comment]
@dust1 

perhaps you could use `cast_column`
https://github.com/apache/arrow-datafusion/blob/e41711b29e72f2d9a8a25c1ed00ccf3ed369f3bc/datafusion/physical-expr/src/functions.rs#L91-L109

**Comment by dust1** [comment]
That's just what I wanted. Thank you!!! @waitingkuo
