### ISSUE TITLE
Create a struct with the specified field names and values

### ISSUE THREAD

**Issue by yukkit** [apache/arrow-datafusion#5861]
### Is your feature request related to a problem or challenge?

I want to construct struct from literal or expression by using sql or rust interface.

like: 
- https://docs.databricks.com/sql/language-manual/functions/named_struct.html
- https://duckdb.org/docs/sql/data_types/struct.html
- https://www.postgresql.org/docs/current/sql-expressions.html#SQL-SYNTAX-ROW-CONSTRUCTORS

### Describe the solution you'd like

Add a NamedStruct expression similar to what spark does

sql usage:
```sql
SELECT named_struct('a', 1, 'b', 2, 'c', 3);
```

### Additional context

If this issue is useful, I will implement it

**Comment by crepererum** [comment]
Note that there is currently NO way to construct a struct with custom field names, because DF also doesn't support casting structs that were constructed using `struct(1, 2, 3)`. But even if such a workaround would be possible, I think having a direct constructor would still be nice.

**Comment by alamb** [comment]
There is a PR up to support `named_struct` https://github.com/apache/arrow-datafusion/pull/9743 and work afoot to support nicer literal syntax: https://github.com/apache/arrow-datafusion/issues/9820 🚀
