### ISSUE TITLE
SortPreservingMerge does not account for memory usage

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-datafusion#5885]
### Is your feature request related to a problem or challenge?

SortPreservingMerge currently has extremely limited memory accounting functionality, with no accounting for buffered batches or cursors.

The only memory accounting is a static assignment at construction time by `ExternalSorter` of the size of the in memory batches, when merging spilled and in-memory data. This assignment is never decremented, and does not take into account any memory usage resulting from loading the spilled data back into memory.

### Describe the solution you'd like

SortPreservingMerge should account for the memory usage of the data it has buffered

Additionally the various streams created by `ExternalSorter`, both for in-memory and spilled data, should be accounted for

### Additional context

#5879 tracks unifying the sorting implementations, which may help make this story more consistent.

**Comment by alamb** [comment]
There is a PR open for this feature -- I think it is valuable to complete. However, it currently doesn't pass the PR tests (I think the tests need some updating)

**Comment by alamb** [comment]
We saw this cause troubles for us during some internal testing. More details to come

**Comment by alamb** [comment]
Specifically, we have pretty good evidence that for dictionary encoded arrays with high cardinality, the interned dictionary values consume an ever increasing amount of memory
