### ISSUE TITLE
LogicalPlan API: Getting catalog name

### ISSUE THREAD

**Issue by BubbaJoe** [apache/arrow-datafusion#5888]
### Is your feature request related to a problem or challenge?

There doesn't seem to be a way of getting the catalog name from a logical plan: https://docs.rs/datafusion-expr/20.0.0/datafusion_expr/logical_plan/enum.LogicalPlan.html

### Describe the solution you'd like

`logical_plan.catalog_name: String`
`logical_plan.catalog_name() -> String`

**Comment by Jefffrey** [comment]
Not sure if this can be a generic method on `LogicalPlan` itself, as for example if you join two tables with different catalog names, then what would the `catalog_name()` method return for a `Join` logical plan node?

Currently you can kinda retrieve the catalog name from a `TableScan` logical plan node via its `table_name` field.

Could you expand on the potential use case for such a method to give some more context?

**Comment by BubbaJoe** [comment]
Hello @Jefffrey, i didn't consider joins... In this case, i guess we can forget it.
