### ISSUE TITLE
Add the repo to the `arrow` GitHub topic

### ISSUE THREAD

**Issue by alippai** [apache/arrow-datafusion#591]
Maybe some other topics should be considered as well.

Context:
![image](https://user-images.githubusercontent.com/240729/122648862-554f6e80-d12b-11eb-8133-19ffe7c91b63.png)

**Comment by alippai** [comment]
Eg. spark has these:
![image](https://user-images.githubusercontent.com/240729/122648888-744e0080-d12b-11eb-83c8-82d0773444df.png)

**Comment by houqp** [comment]
I think this is controlled through https://github.com/apache/arrow-datafusion/blob/master/.asf.yaml, perhaps someone can start a PR and others can add more suggestions during code review.
