### ISSUE TITLE
fix an issue where aliases are not respected in generating downstream schemas in window expr

### ISSUE THREAD

**Issue by Jimexist** [apache/arrow-datafusion#592]
> looks like integration test is failing due to mismatch between logical schema and physical schema for window queries, i will dig into this.

thanks, it might be because of some edge cases that i did miss. i didn't find time to fix it but so far this query will fail:

```sql
> select max(c1) over () max_c1, max(c1) over (partition by c2) max_c1_by_c2 from test;
Plan("Schema contains duplicate unqualified field name 'MAX(c1)'")
```

_Originally posted by @Jimexist in https://github.com/apache/arrow-datafusion/pull/55#issuecomment-864556916_

**Comment by houqp** [comment]
looks like the error only shows up when `partition by c2` is provided in the second column.
