### ISSUE TITLE
wrong type coercion for binary expr of two interval

### ISSUE THREAD

**Issue by jackwener** [apache/arrow-datafusion#5933]
### Describe the bug

Error: Context("type_coercion", Plan("Cannot automatically convert Interval(YearMonth) to Interval(MonthDayNano)"))

### To Reproduce

```rs
    // define the query using the DataFrame trait
    let df = ctx
        .read_parquet(filename, ParquetReadOptions::default())
        .await?
        // IntervalYearMonth 1 - IntervalDayTime 1
        .select(vec![lit((ScalarValue::IntervalYearMonth(Some(1)))).add(lit(ScalarValue::IntervalDayTime(Some(1))))])?;
```

**Comment by aprimadi** [comment]
Hi @jackwener. Isn't this bug already fixed by PR: https://github.com/apache/arrow-datafusion/pull/6270?

If not, can you describe what the bug is, I may be able to take a look into it.

**Comment by jackwener** [comment]
Thanks @aprimadi , this problem is from `arrow-rs`, I will fix it.
