### ISSUE TITLE
doc site sidebar icon is glitched/bugged

### ISSUE THREAD

**Issue by Jefffrey** [apache/arrow-datafusion#5935]
### Describe the bug

On documentation site: https://arrow.apache.org/datafusion/index.html

Sidebar is glitched with the logo at the bottom obscuring links, see:

![image](https://user-images.githubusercontent.com/22608443/230799717-d8f20f72-7747-41db-919f-b2a34e5c3c00.png)

(this is bottom of page)

Can't see contributor guide links, unless expand another menu which then pushes them into visibility:

![image](https://user-images.githubusercontent.com/22608443/230799732-44b929ae-1b30-463d-9785-be35e8ccefb1.png)

Can reproduce by adjusting size of browser window, can see the datafusion logo kinda floats around:

![image](https://user-images.githubusercontent.com/22608443/230799873-10099976-f17e-4e47-b9ec-3614915b1dcc.png)

### Additional context

Firefox on linux

**Comment by alamb** [comment]
I will look into this - it happens for me on Mac / chrome as well

**Comment by alamb** [comment]
I have a PR that I think will fix this: https://github.com/apache/arrow-datafusion/pull/5962

**Comment by Jefffrey** [comment]
Hi @alamb thanks for the PR, but it seems this issue is still persisting:

![image](https://user-images.githubusercontent.com/22608443/231581835-d9cbd1ec-8811-48fd-80ea-4f8614907d8f.png)

Reproducible again via making the window size smaller on Firefox desktop

**Comment by alamb** [comment]
Reopened 

I am out of ideas of how to fix this, sadly

**Comment by Jefffrey** [comment]
I can try look into this
