### ISSUE TITLE
LogicalPlan COPY TO statement support

### ISSUE THREAD

**Issue by metesynnada** [apache/arrow-datafusion#5988]
### Is your feature request related to a problem or challenge?

I want to be able to use 

```
Statement::Copy {
                table_name,
                columns,
                to,
                target,
                options,
                legacy_options,
                values
            }
```

in the logical plan, from SQLParser. It is mentioned in https://github.com/apache/arrow-datafusion/issues/5076 and https://github.com/apache/arrow-datafusion/issues/5130.

### Describe the solution you'd like

Add a logical plan enum for this operator that supports the `statement::copy` fields.

### Describe alternatives you've considered

NA

### Additional context

NA

**Comment by alamb** [comment]
This is included in https://github.com/apache/arrow-datafusion/pull/6313

**Comment by alamb** [comment]
I plan a PR for this shortly

**Comment by alamb** [comment]
Proposed PR: https://github.com/apache/arrow-datafusion/pull/6355
