### ISSUE TITLE
Support for Null in JSON reader

### ISSUE THREAD

**Issue by BubbaJoe** [apache/arrow-datafusion#6026]
### Is your feature request related to a problem or challenge?

Hello,

I keep getting this error in my when trying to read json data. 

```
"Arrow error: Not yet implemented: Support for Null in JSON reader"
```

**Comment by jiangzhx** [comment]
@BubbaJoe Could you provide a test case to reproduce the issue?

**Comment by BubbaJoe** [comment]
@jiangzhx if you register a json with an empty array like this

```
{"items": []}
```

**Comment by jiangzhx** [comment]
> @jiangzhx if you register a json with an empty array like this
> 
> ```
> {"items": []}
> ```

I'm afraid we don't have the "capability" to support nulls in JSON reader.
This is because the specific data type of an empty array [] in JSON format cannot be inferred when there is only one row of data.

 consider the following JSON string, JSON reader will use `infer_json_schema` method to inferred the datatype.
```
{"items": []}
{"items": [1,2]}
```

OR

you can specify the schema to the reader.

```
#[tokio::test]
async fn json_single_nan_array_schema() {
    let ctx = SessionContext::new();
    let path = format!("{TEST_DATA_BASE}/4.json");
    let schema = Schema::new(vec![Field::new(
        "items",
        DataType::List(FieldRef::new(Field::new("item", Int32, true))),
        false,
    )]);

    let options = NdJsonReadOptions::default().schema(&schema);

    ctx.register_json("single_array_nan", &path, options)
        .await
        .unwrap();

    let sql = "SELECT items FROM single_array_nan";
    let dataframe = ctx.sql(sql).await.unwrap();
    let results = dataframe.collect().await.unwrap();
    print_batches(&results);
}
```

**Comment by BubbaJoe** [comment]
I see, thanks!

**Comment by Jefffrey** [comment]
Although this has been closed as intended behaviour, I wonder if it's at least worth opening a PR to fix the error message to be more informative?


```
"Arrow error: Not yet implemented: Support for Null in JSON reader"
```

Can be confusing, compared to something like

```
Cannot infer schema for empty JSON array
```

For example

**Comment by jiangzhx** [comment]
> Although this has been closed as intended behaviour, I wonder if it's at least worth opening a PR to fix the error message to be more informative?
> 
> ```
> "Arrow error: Not yet implemented: Support for Null in JSON reader"
> ```
> 
> Can be confusing, compared to something like
> 
> ```
> Cannot infer schema for empty JSON array
> ```
> 
> For example
> 
> Edit: assuming the error occurs during schema inference, otherwise I'm not so sure
@Jefffrey  thanks,it's a good idea.  i will try to add specific error log.
