### ISSUE TITLE
Support DROP SCHEMA statements

### ISSUE THREAD

**Issue by scsmithr** [apache/arrow-datafusion#6027]
### Is your feature request related to a problem or challenge?

We're able to create schemas with datafusion, but can't drop them. I'm mostly concerned about doing cleanup in sqllogictests that create schemas (e.g. https://github.com/apache/arrow-datafusion/pull/6022). Without a way to drop, we might end up with name conflicts.

### Describe the solution you'd like

Support `DROP SCHEMA <schema> [CASCADE]`

### Describe alternatives you've considered

Again, I'm mostly concerned about sqllogictests. The alternative being we just ensure every test case uses a unique schema name if it needs a schema.

**Comment by jaylmiller** [comment]
I need something like this for my own project so I can tackle this!

**Comment by jaylmiller** [comment]
I've tackled this in PR #6096 😀
