### ISSUE TITLE
in_list expression not working

### ISSUE THREAD

**Issue by BubbaJoe** [apache/arrow-datafusion#6073]
### Describe the bug
I am getting an error when i try to use the in_list expression: `"Error during planning: Invalid function 'in_list'"`

[documentation link](https://arrow.apache.org/datafusion/user-guide/expressions.html#other-expressions)

### To Reproduce

I am running this query in `SessionContext::sql` btw
`select in_list('word', list) from data`
where list is a utf8 array

### Expected behavior

to return 'true'

**Comment by jiangzhx** [comment]
In_list did not register as a UDF function.
the doc last updated by @izveigor. 
hope @izveigor  help for check.

**Comment by BubbaJoe** [comment]
@izveigor sSorry I am a bit confused, can you give an SQL example?

**Comment by jiangzhx** [comment]
> 

@BubbaJoe, the document you linked is not for SQL functions. SQL scalar and aggregate functions can be found at https://arrow.apache.org/datafusion/user-guide/sql/scalar_functions.html#.

I believe we do not have an SQL function to check if an expression is in an array.

**Comment by BubbaJoe** [comment]
@jiangzhx Basically some of the functions and operators here:
https://www.postgresql.org/docs/9.2/functions-array.html

The most important being: array_length(anyarray), unnest(anyarray), and checking if an item is in an array.

Example: ([`select * from any(items) = 'item'`](https://www.postgresql.org/docs/current/functions-subquery.html#FUNCTIONS-SUBQUERY-ANY-SOME))

BTW this query seems to parse correctly in datafusion, i just get an Unsupported/implemented error. I would perfer this way instead of something like array_contains(anyarray, anyelement)

This is the error i get: `"This feature is not implemented: Unsupported ast node in sqltorel: AnyOp(Identifier(Ident { value: \"items\", quote_style: None }))"`

**Comment by BubbaJoe** [comment]
@izveigor Doesn't even parse the sql, it would need something like `unnest` to make the array elements into rows to be able to process it as a subquery.

**Comment by BubbaJoe** [comment]
https://github.com/apache/arrow-datafusion/issues/6075

**Comment by BubbaJoe** [comment]
Let me close this issue since in_list isn't here: https://arrow.apache.org/datafusion/user-guide/sql/scalar_functions.html

Thanks for the clarification!
