### ISSUE TITLE
Code refactor, combine the two rules: DecorrelateWhereExists and DecorrelateWhereIn

### ISSUE THREAD

**Issue by mingmwang** [apache/arrow-datafusion#6086]
### Is your feature request related to a problem or challenge?

Combine the two rules to one, the process of the two rules are almost the same and there are duplicate code.
I will try to combine the two rules to one unified rule

**Comment by mingmwang** [comment]
@jackwener

**Comment by jackwener** [comment]
I think it's a great job.

ExistsSubquery and InSubquery is similar in semantic. some paper already conclude it. Such as: 

AGE IN (SELECT AGE)  --> a.age=b.age[0] OR a.age=b.age[1] OR ... OR a.age=b.age[n]
Exists (SELECT AGE) --> b.age[0] is not null OR b.age[1] is not null OR ... OR b.age[n] is not null
