### ISSUE TITLE
Remove input schema from PhysicalExpr, move the validation logic to phyiscal expression planner

### ISSUE THREAD

**Issue by mingmwang** [apache/arrow-datafusion#6117]
### Describe the bug

https://github.com/apache/arrow-datafusion/pull/6114

The `input_schema` was added to the `InListExpr` by mistake, it cause issues during `transform()` rewrite process, should remove it.

**Comment by alamb** [comment]
I may be interested in helping with this one as it affected us upstream in IOx and I am looking for excuses to help clean up DataFUsion code
