### ISSUE TITLE
CI fails with "cannot find value `env_var` in crate `gix_path`"

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#6132]
### Describe the bug

CI is failing like this: 

https://github.com/apache/arrow-datafusion/actions/runs/4813082830/jobs/8569157024?pr=6131
```
   Compiling gix-config v0.20.1
error[E0425]: cannot find value `env_var` in crate `gix_path`
  --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/gix-config-0.20.1/src/file/init/comfort.rs:31:54
   |
31 |                     .storage_location(&mut gix_path::env_var)
   |                                                      ^^^^^^^ not found in `gix_path`

error[E0425]: cannot find function `home_dir` in crate `gix_path`
  --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/gix-config-0.20.1/src/file/init/comfort.rs:44:30
   |
44 |         let home = gix_path::home_dir();
   |                              ^^^^^^^^ not found in `gix_path`
   |
help: consider importing one of these items
   |
1  | use gix_path::env::home_dir;
   |
1  | use std::env::home_dir;
   |
help: if you import `home_dir`, refer to it directly
   |
44 -         let home = gix_path::home_dir();
44 +         let home = home_dir();
   |
```

It happens on several unrelated PRs: 
* https://github.com/apache/arrow-datafusion/actions/runs/4811369397/jobs/8565283735?pr=6130
* https://github.com/apache/arrow-datafusion/actions/runs/4810955979/jobs/8564306963?pr=6129

### To Reproduce

Make a new PR without any code changes on datafusion

### Expected behavior

CI should pass

### Additional context

The crate in question appears to have released a new version 5 hours ago, about the same time that the tests started failing: https://crates.io/crates/gix-config

**Comment by crepererum** [comment]
https://github.com/substrait-io/substrait-rs/pull/97

**Comment by crepererum** [comment]
Fixed by gitoxide's release engineering :). CI should be back to normal.
