### ISSUE TITLE
Utilize PRIMARY KEY information better

### ISSUE THREAD

**Issue by mustafasrepo** [apache/arrow-datafusion#6190]
### Is your feature request related to a problem or challenge?

Consider the query below
```sql
SELECT s.sn, s.amount
            FROM sales_global AS s
            GROUP BY sn
```
When `sn` is `PRIMARY KEY` (each `sn` will have unique values) we know that, all the columns the table `sales_global` e.g `s` can be emitted after aggregation (since for each group all rows would have same value).  Corresponding query can run in Postgre. However, datafusion can only emit `s.sn` after aggregation from the original table.

### Describe the solution you'd like

I would like to have this support.

### Additional context

To reproduce the problem one can use the test below
```rust
#[tokio::test]
async fn test_primary_key_aggregation() -> Result<()> {
    let config = SessionConfig::new()
        .with_target_partitions(1);
    let ctx = SessionContext::with_config(config);
    ctx.sql("CREATE TABLE sales_global (
      sn INT PRIMARY KEY,
      ts TIMESTAMP,
      currency VARCHAR(3),
      amount INT
    ) as VALUES
      (1, '2022-01-01 08:00:00'::timestamp, 'EUR', 50.00),
      (2, '2022-01-01 11:30:00'::timestamp, 'EUR', 75.00),
      (3, '2022-01-02 12:00:00'::timestamp, 'EUR', 200.00),
      (4, '2022-01-03 10:00:00'::timestamp, 'EUR', 100.00)").await?;
    let sql = "SELECT s.sn, s.amount
        FROM sales_global AS s
        GROUP BY sn";

    let msg = format!("Creating logical plan for '{sql}'");
    let dataframe: DataFrame = ctx.sql(sql).await.expect(&msg);
    let physical_plan = dataframe.create_physical_plan().await?;
    let batches = collect(physical_plan, ctx.task_ctx()).await?;
    print_batches(&batches)?;
    Ok(())
}
```

**Comment by alamb** [comment]
I think primary key could be modeled by the existing "distinct count" in the statistics: https://docs.rs/datafusion/latest/datafusion/physical_plan/struct.ColumnStatistics.html

**Comment by alamb** [comment]
I am not sure that datafusion itself should have any notion of "primary key" per se -- that seems like something that would be engine specific

**Comment by mustafasrepo** [comment]
> 

Thanks @alamb I will explore how can we utilize distinct count statistic to support this feature. Thanks for the suggestion.
