### ISSUE TITLE
Port remaining sql integration tests from `rust `to `sqllogictest`

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#6195]
### Is your feature request related to a problem or challenge?

As described in https://github.com/apache/arrow-datafusion/tree/main/datafusion/core/tests/sqllogictests DataFusion has many tests that use the sqllogictest framework which is easy to write and update compared to rust tests

We still have a non trivial number of old tests that are written in Rust and run in the sql integration test:
https://arrow.apache.org/datafusion/contributor-guide/index.html#rust-integration-tests

```
cargo test -p datafusion --test sql_integration
```

This ticket tracks the work to port the tests from rust to sqllogictests

### Describe the solution you'd like

Port tests from [datafusion/core/tests/sql](https://github.com/apache/arrow-datafusion/tree/master/datafusion/core/tests/sql) to sqllogictests in [datafusion/core/tests/sqllogictests/test_files](https://github.com/apache/arrow-datafusion/tree/main/datafusion/core/tests/sqllogictests/test_files)

For each test, the goal is to:
1. Port as many tests as possiible (follow the example of https://github.com/apache/arrow-datafusion/pull/6158 or one of the other tests linked to https://github.com/apache/arrow-datafusion/issues/4495)

Then we can figure out what to do with the tests that can not be ported easily
# Remaining items:
- [x] https://github.com/apache/arrow-datafusion/issues/6208
- [x] https://github.com/apache/arrow-datafusion/issues/6216
- [x] https://github.com/apache/arrow-datafusion/issues/6210
- [x] https://github.com/apache/arrow-datafusion/issues/6211
- [x] https://github.com/apache/arrow-datafusion/issues/6212
- [x] https://github.com/apache/arrow-datafusion/issues/6213
- [x] https://github.com/apache/arrow-datafusion/issues/6214
- [x] https://github.com/apache/arrow-datafusion/issues/6215
- [x] #6233
- [x] #6299
- [x] #6298
- [x] #6297
- [x] #6300
- [x] #6301
- [x] #6302
- [x] #6303
- [x] #6668
- [x] #8194
- [x] #8195
- [x] #8196
- [x] #8197
- [x] #8198
- [x] #8199
- [x] #8200
- [x] #8201
- [x] #8202
- [x] #8203
- [x] #8204
- [x] #8205
- [x] #8206
- [x] #8207
- [x] #8208
- [x] #8209
- [x] #8210
- [x] #8211
- [x] #8212
- [x] #8213
- [x] #8214
- [x] #8215
- [x] #8216

### Additional context

Follow on to https://github.com/apache/arrow-datafusion/issues/4495

Marking this as a good first issue as there are many examples and it will get people familiar with how to run tests and how to use datafusion as a library, while also helping the community

**Comment by jiangzhx** [comment]
i'm start working on [Port tests in joins.rs to sqllogictest #6302](https://github.com/apache/arrow-datafusion/issues/6302)

**Comment by alamb** [comment]
Thank you to everyone who helped get this done!
