### ISSUE TITLE
sqllogictest statement error no escaping

### ISSUE THREAD

**Issue by aprimadi** [apache/arrow-datafusion#6258]
### Is your feature request related to a problem or challenge?

Currently `(` and `)` character needs to be escaped in sqllogictest statement error. Not sure if this is possible but it would be great if I can just supply a string that is an exact match of the output and not need to escape the character.

Expected
```
statement error ParserError("blablabla")
```

Current
```
statement error ParserError\("blablabla"\)
```

**Comment by alamb** [comment]
FYI @melgenek  -- this seems very similar to https://github.com/apache/arrow-datafusion/issues/5727

 I wonder if we can apply a similar fix 🤔

**Comment by melgenek** [comment]
>  it would be great if I can just supply a string that is an exact match of the output and not need to escape the character.

If I understand correctly, there is no issue at the moment, and validation works correctly when symbols are escaped.

`sqllogictest-rs` makes an explicit choice to have errors as Regexp, that's why there is a need to escape characters that have special meaning in Regex like `(`,`)`,`.`,`[`,`]`

**Comment by alamb** [comment]
I think I have seen errors (maybe where newlines aren't escaped?) I'll pay attention to this in more detail if it happens again

**Comment by alamb** [comment]
Closing this ticket as working as expected, I think
