### ISSUE TITLE
Improve error message for `CREATE EXTERNAL TABLE` typos

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#6288]
If a user puts a typo like this (`HEAD` rather than `HEADER`) in their SQL

```sql
CREATE EXTERNAL TABLE t(c1 int)
STORED AS CSV
WITH HEAD ROW
LOCATION 'foo.csv';
```

The Parser returns the somewhat confusing error `sql parser error: Missing LOCATION clause in CREATE EXTERNAL TABLE statement` 

It would be great if the message was something more "expected LOCATION, HEADER, ... got HEAD" that gave the user a hint of what was was wrong

See original suggestion  posted by @tz70s in https://github.com/apache/arrow-datafusion/pull/6257#discussion_r1186779655

**Comment by parkma99** [comment]
I'm going to work it
