### ISSUE TITLE
Port tests in `explain.rs` to sqllogictests

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#6297]
### Is your feature request related to a problem or challenge?

Part of https://github.com/apache/arrow-datafusion/issues/6195. We are trying to keep the DataFusion code base clean and easy to contribute to and modify. Part of doing so is having a single location for most test coverage so new tests can be added easily and people can follow the existing patterns easily 

### Describe the solution you'd like

Port the tests in https://github.com/apache/arrow-datafusion/blob/main/datafusion/core/tests/sql/explain.rs to `explain.slt` in https://github.com/apache/arrow-datafusion/tree/main/datafusion/core/tests/sqllogictests/test_files

For this particular test, I think the best thing to do is to test `EXPLAIN VERBOSE` on a simple explain plan which will show the different passes

Notes: 
1. Instructions for running sqllogitest are here: https://github.com/apache/arrow-datafusion/tree/main/datafusion/core/tests/sqllogictests
2.

**Comment by my-vegetable-has-exploded** [comment]
I'd like to try it.

**Comment by alamb** [comment]
Thank you @my-vegetable-has-exploded  (great github tag btw)

**Comment by my-vegetable-has-exploded** [comment]
Get it! 
Thanks, @alamb
