### ISSUE TITLE
Port tests in `information_schema.rs` to sqllogictest

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#6301]
### Is your feature request related to a problem or challenge?

Part of https://github.com/apache/arrow-datafusion/issues/6195. We are trying to keep the DataFusion code base clean and easy to contribute to and modify. Part of doing so is having a single location for most test coverage so new tests can be added easily and people can follow the existing patterns easily 

### Describe the solution you'd like

Port the tests in https://github.com/apache/arrow-datafusion/blob/main/datafusion/core/tests/sql/information_schema.rs to `ddl.slt` in https://github.com/apache/arrow-datafusion/tree/main/datafusion/core/tests/sqllogictests/test_files

Note you can create catalogs and schema via SQL now 

Catalogs: https://arrow.apache.org/datafusion/user-guide/sql/ddl.html#create-database
Schema: https://arrow.apache.org/datafusion/user-guide/sql/ddl.html#create-schema

Notes: 
1. Instructions for running sqllogitest are here: https://github.com/apache/arrow-datafusion/tree/main/datafusion/core/tests/sqllogictests

**Comment by edmondop** [comment]
I'd like to work on this , #6300 and #6209 . Is anyone already preparing a PR?

**Comment by palash25** [comment]
Hi, I would like to work on this if no one is actively working on this.

**Comment by alamb** [comment]
Thank you @palash25  -- that would be awesome!

**Comment by palash25** [comment]
@alamb i wanted to clarify something. the issue description mentions that the tested should be ported to `ddl.slt`, but i saw that already some rust tests from `information_schema.rs` were ported to `information_schema.slt`, is there a reason why the remaining tests need to be in `ddl.slt` file and not in `information_schema.slt`?

**Comment by alamb** [comment]
> , is there a reason why the remaining tests need to be in ddl.slt file and not in information_schema.slt?

@palash25  -- No not to my knowledge -- I think they should be put wherever they best fit.
