### ISSUE TITLE
Port tests in `joins.rs` to sqllogictest

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#6302]
### Is your feature request related to a problem or challenge?

Part of https://github.com/apache/arrow-datafusion/issues/6195. We are trying to keep the DataFusion code base clean and easy to contribute to and modify. Part of doing so is having a single location for most test coverage so new tests can be added easily and people can follow the existing patterns easily 

### Describe the solution you'd like

Port the tests in https://github.com/apache/arrow-datafusion/blob/main/datafusion/core/tests/sql/joins.rs to `joins.slt` in https://github.com/apache/arrow-datafusion/tree/main/datafusion/core/tests/sqllogictests/test_files

This is a subtantial task -- and perhaps is done best in several smaller PRs 

Notes: 
1. Instructions for running sqllogitest are here: https://github.com/apache/arrow-datafusion/tree/main/datafusion/core/tests/sqllogictests
2. If you have questions or hit issues, please let me know

**Comment by parkma99** [comment]
I'm going to work it

**Comment by alamb** [comment]
Thank you @parkma99  -- really apprecaited
