### ISSUE TITLE
Avoid reading entire stream to determine schema of arrow file

### ISSUE THREAD

**Issue by jonmmease** [apache/arrow-datafusion#6368]
Follow on to https://github.com/apache/arrow-datafusion/pull/6337. 

Currently when reading an arrow file from a stream, the entire stream is parsed as a file in order to determine the schema:

https://github.com/apache/arrow-datafusion/blob/8a47c42096311cf9b6191cfb9d96e2d9ba3a630d/datafusion/core/src/datasource/file_format/arrow.rs#L60-L63

This will result in parsing the stream multiple times (once to determine the schema and again later to actually build RecordBatches from the stream).

Can we be more efficient here by only looking as far into the stream as necessary to read the schema?

**Comment by jayzhan211** [comment]
I can try on this, we can extract out the read_schema part from the FileReader.try_new(), so we can read schema only in infer_schema().
