### ISSUE TITLE
Optimize min/max queries based on table statistics

### ISSUE THREAD

**Issue by Dandandan** [apache/arrow-datafusion#640]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
In #620 a feature has been added to optimize queries like `select count(*) from table`.
We can do the same with `min` / `max` queries (`select min(col) from table`).

**Describe the solution you'd like**
Get the table statistics based on the column name from the table provider, add it to `AggregateStatistics` optimization rule.

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
Following the example in https://github.com/apache/arrow-datafusion/pull/620 probably makes this PR fairly approachable to anyone who is interested

**Comment by Dandandan** [comment]
For it to work on parquet and in-memory data, a bit of work also has to be done there to summarize / expose those statistics.

https://github.com/apache/arrow-datafusion/issues/537

**Comment by b41sh** [comment]
I'd like to do this.

**Comment by alamb** [comment]
Assigning to @b41sh  per request. Thank you!
