### ISSUE TITLE
Substrait: Expr::ScalarFunction support

### ISSUE THREAD

**Issue by nseekhao** [apache/arrow-datafusion#6411]
### Is your feature request related to a problem or challenge?

Currently, only binary expression is supported. Request to add support for arbitrary `ScalarFunction`.

### Describe the solution you'd like

Add procedure to match `expr` to `Expr::ScalarFunction` in [to_substrait_rex()](https://github.com/apache/arrow-datafusion/blob/main/datafusion/substrait/src/logical_plan/producer.rs#L529-L700).

### Describe alternatives you've considered

N/A

**Comment by jayzhan211** [comment]
I would like to try on this, it might be similar to https://github.com/apache/arrow-datafusion/blob/de2d1c5bac1f1bd770394761a8c7bb58657315bb/datafusion/substrait/src/logical_plan/producer.rs#L546-L562, instead we need to handle for arbitrary args?
