### ISSUE TITLE
[Contributor Guide] Unclear Protobuf installation instructions

### ISSUE THREAD

**Issue by LouisGariepy** [apache/arrow-datafusion#6418]
### Is your feature request related to a problem or challenge?

This [section](https://arrow.apache.org/datafusion/contributor-guide/index.html#protoc-installation) of the contributor guide explains how to install the Protobuf system dependencies:

> dnf install -y protobuf-compiler

This command is not sufficient to be able to build `arrow-datafusion`, at least not with the Fedora version I tested (Fedora 38).

### Describe the solution you'd like

Instead of suggesting `protobuf-compiler`, the docs should use `protobuf-devel` (which also installs the compiler).

> dnf install -y protobuf-devel

**Comment by LouisGariepy** [comment]
I suspect that there might be a similar issue for apt-based systems, where you would need to install `libprotobuf-dev` (I'm not sure if that also install the compiler though, would have to check).

This is what I gathered from this [SO post](https://stackoverflow.com/questions/41594991/compile-protobuf-client-code-on-ubuntu-but-include-file-is-not-found) at least.

**Comment by edmondop** [comment]
> Thanks for the suggestion @LouisGariepy

If we support gitpod, in GitPod we can handle all of those and standardize the development worfklow. People would open https://gitpod.io#/https://github.com/apache/arrow-datafusion and start coding.

**Comment by LouisGariepy** [comment]
GitPod looks cool, but there will most likely always be contributors who prefer local development. Therefore I believe that it's still worth maintaining installation instructions.

Fortunately, DataFusion's Protobuf dependencies are simple and manageable, it's just a matter of being a bit more precise as to what needs to be installed.

I could setup containers/VMs for the relevant operating systems to verify that the installation procedure works as intended. If this is welcome, I'll submit a PR with the adjustments that must be made to the docs.

**Comment by LouisGariepy** [comment]
Alright, so I tested on debian, ubuntu, and arch, and the install instructions seem to be correct :smile:. Only Fedora seems to require an adjustment.
