### ISSUE TITLE
Support Type Coercion in Parquet Reader

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-datafusion#6427]
### Is your feature request related to a problem or challenge?

https://github.com/apache/arrow-datafusion/pull/6404 by @e1ijah1 added support for type coercion within SchemaAdapter, we should hook up ParquetExec to make use of this to allow for mixed schema within a single ParquetExec

### Describe the solution you'd like

I would like to be able to read a set of parquet files with different schema and have them coerced to the same schema

**Comment by e1ijah1** [comment]
@tustvold  
I have implemented this feature in my latest commit. Could you please review it when you are available? Thank you.
