### ISSUE TITLE
Incorrect function-name matching with disabled `enable_ident_normalization` 

### ISSUE THREAD

**Issue by DDtKey** [apache/arrow-datafusion#6436]
### Describe the bug

For versions `24` & `25` DF returns `Invalid function 'LENGTH'` when `enable_ident_normalization`  is disabled.
It was working with `22`.

For example, it fails for  upper-case functions names, like `LENGTH`, `CONCAT` and etc.

I don't think normalization should affect it, because the name of functions should be case insensitive 

### To Reproduce

Set `enable_ident_normalization: false` and use select with any scalar-function in upper-case, like `select LENGTH(x) from my table`

With CLI:
```sql
SET datafusion.sql_parser.enable_ident_normalization=false;

SELECT LENGTH('str');
Error during planning: Invalid function 'LENGTH'
```

### Expected behavior

Name of functions should be case insensitive, normalization is separate step.

**Comment by alamb** [comment]
Seems reasonable to me. I think this is probably a good first issue as it has a good reproducer and explanation of expected behavior

**Comment by parkma99** [comment]
I would like to work it😉
