### ISSUE TITLE
Inconsistencies in `Expr` operator code.

### ISSUE THREAD

**Issue by LouisGariepy** [apache/arrow-datafusion#6437]
# Problem

Some operations are implemented both directly on `Expr` and as built-in traits (here's an example: [trait impl](https://github.com/apache/arrow-datafusion/blob/32144501be634253b254aca34660b4b3e81dbc1f/datafusion/expr/src/operator.rs#L299-L305C2) compared with [type impl](https://github.com/apache/arrow-datafusion/blob/32144501be634253b254aca34660b4b3e81dbc1f/datafusion/expr/src/expr.rs#LL744C1-L746C6)).

As far as I can tell, these implementations could (and should) use the same underlying logic (the trait impls should use `Expr`'s methods). Instead, the logic is duplicated at both sites (as you can see from the snippets I linked). This increases the potential for bugs as it would be very easy to introduce changes in say one of `Expr`'s methods and not the corresponding trait impl (or vice-versa).

Another inconsistency is that `Expr`'s methods don't have the same name as the corresponding trait methods, so we end up in a situation where, for example, `bitwise_and` (type impl), `bitand` and `&` (trait impl) all do the same thing. This can cause confusion for users since it's not immediately clear that these are in fact intended to be the same.

Finally, the `Not` trait implementation is located in the `expr` module ([here](https://github.com/apache/arrow-datafusion/blob/32144501be634253b254aca34660b4b3e81dbc1f/datafusion/expr/src/expr.rs#L912-L938)), while all other operator trait impls are located in the `operator` module.

# Potential solution
In my opinion, the `Expr` impl should not duplicate built-in operator trait methods. The duplicated methods should be removed from `Expr`, and only the trait impls be kept. This is more in line with idiomatic Rust code, removes duplication, and reduces potential user confusion.

Likewise, the `Not` trait impl should be moved to the `operator` module and the corresponding type method be removed.

# Alternatives
If the duplicated type impls won't be removed, then the trait impls should be derived from the `Expr` methods to at least remove the duplication in implementation.

# Discussion
Please let me know what you think. It's possible that I misunderstood why the code is laid out this way.

If there is in fact a problem, then I'm prepared to make a PR to solve this after we've discussed of the appropriate solution.

**Comment by alamb** [comment]
> In my opinion, the Expr impl should not duplicate built-in operator trait methods. The duplicated methods should be removed from Expr, and only the trait impls be kept. This is more in line with idiomatic Rust code, removes duplication, and reduces potential user confusion.

I agree a single Rust idomatic pattern sounds good to me. 

I wonder if it might cause issues for python bindings, or other non rust users -- @andygrove  or @jdye64  do you have any insight?

Thank you for working on cleaning this up 🙏 

> Likewise, the Not trait impl should be moved to the operator module and the corresponding type method be removed.

I agree

**Comment by jdye64** [comment]
@alamb thanks for checking. @LouisGariepy proposal will not cause any issue on the Python bindings side (however good to know so we can expect and adjust for the change). However I can't speak for other non-rust bindings.
