### ISSUE TITLE
Configurable error handling in `FileStream`

### ISSUE THREAD

**Issue by thinkharderdev** [apache/arrow-datafusion#6476]
### Is your feature request related to a problem or challenge?

If you are scanning a large number of files then a single misssing/corrupt file could cause the entire query to fail. This can happen in a number of different scenarios:
1. File is deleted between the time of listing and time of scan
2. Listing is done from a catalog which is only eventually consistent with underlying data source
3. A partial/failed write creates a file which is unreadable. 

### Describe the solution you'd like

In some cases, failing the entire query is the desired result, but in other cases it would be better to simply move on and scan what we can (and surface the failed scans as a metric for visibility). 

`FileStream` can take an enum:
```
/// Describes the behavior of the `FileStrem` if file opening or scanning fails
enum OnError {
  /// Continue scanning, ignoring the failed file
  Skip,
  /// Fail the entire stream and return the underlying
  Fail
}
```

For our use case it's not really necessary but it might be useful as well to decompose this into different error handling configs for failed opening and failed scanning. 

### Describe alternatives you've considered

We could leave the current behavior unchanged

**Comment by tustvold** [comment]
FWIW the way IOx handles this particular issue is to make use of soft-deletes, i.e. the file is only deleted from the catalog, and later (e.g. 1 day) removed from the underlying backing store. Not sure if this would be practical for your use-case, just thought I would mention it. Permitting missing files would of course result in a loss of transaction isolation

**Comment by thinkharderdev** [comment]
> FWIW the way IOx handles this particular issue is to make use of soft-deletes, i.e. the file is marked deleted within the catalog, but only actually deleted at a later date by a garbage collector.  

Indeed. In our case we have no way of preventing objects being deleted outside of the normal process so we have to deal with it this way. 

> Permitting missing files would of course result in a loss of transaction isolation

Yeah, the default should remain the way it is now and this should only be an escape hatch that can be used in specialized circumstances
