### ISSUE TITLE
DISCUSS: merge Expr::CrossJoin into Expr::Join

### ISSUE THREAD

**Issue by jackwener** [apache/arrow-datafusion#6480]
### Is your feature request related to a problem or challenge?

Currently, Expr enum exist `CrossJoin` and `Join`, I think `CrossJoin` is duplicated, `CrossJoin` should be a type of `Join` instead of a single Expr Typ.

It make we often write more code to match pattern to handle`Expr::CrossJoin` and write repetitive code.

I think we can Merge it into `Expr::Join`.

### Describe alternatives you've considered

I'm worried about this change, because It's a api-breaking behavior.

This change may affect other projects related with `datafusion`, like `ballista`, `datafusion-python-binding`, `substrait` ....

**Comment by mingmwang** [comment]
I would prefer keep the `CrossJoin`, it will make the plan more clear that it is a `CrossJoin`.
