### ISSUE TITLE
Substrait: Add Union/Unions all support (or all SetOps)

### ISSUE THREAD

**Issue by nseekhao** [apache/arrow-datafusion#6490]
### Is your feature request related to a problem or challenge?

Set operations are currently not supported.

### Describe the solution you'd like

Add support for set operations.

### Describe alternatives you've considered

If not all of the set operations can be added at this time, then only `union` and `union all` are needed to support TPC-DS queries.

**Comment by waynexia** [comment]
We have [`union all` execution plan](https://docs.rs/datafusion/latest/datafusion/physical_plan/union/struct.UnionExec.html) and [`distinct` optimizer](https://docs.rs/datafusion-optimizer/latest/datafusion_optimizer/replace_distinct_aggregate/index.html). And APIs on `DataFrame` to build [`union`](https://docs.rs/datafusion/latest/datafusion/dataframe/struct.DataFrame.html#method.union) and [`union distinct`](https://docs.rs/datafusion/latest/datafusion/dataframe/struct.DataFrame.html#method.union_distinct) plan. Is this ticket finished?
