### ISSUE TITLE
Main builds fail with `error: symbol `init___rust_ctor___ctor` is already defined`

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#6495]
### Describe the bug

https://github.com/apache/arrow-datafusion/actions/runs/5125505760/jobs/9218772590

Fails with 

```

error: symbol `init___rust_ctor___ctor` is already defined
   --> datafusion/optimizer/src/scalar_subquery_to_join.rs:311:5
    |
311 |     #[ctor::ctor]
    |     ^^^^^^^^^^^^^
    |
    = note: this error originates in the attribute macro `ctor::ctor` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `datafusion-optimizer` due to previous error
```

### To Reproduce

If you run `cargo update` 

```
    Updating ctor v0.2.0 -> v0.2.1
```

Then the link error will happen

It appears this crate was released about the same time as our CI started failing: https://crates.io/crates/ctor/0.2.1

**Comment by alamb** [comment]
I filed https://github.com/mmastrac/rust-ctor/issues/283 upstream

**Comment by jiangzhx** [comment]
I am facing the same problem. 
If you have already performed a cargo update, you can fix this issue by running the command:

`cargo update -p ctor --precise v0.2.0`

**Comment by alamb** [comment]
Proposed fix: https://github.com/apache/arrow-datafusion/pull/6505/files

**Comment by mmastrac** [comment]
ctor 0.2.2 is pushed without #[no_mangle]. Please let me know if this fixes it.

**Comment by alamb** [comment]
Thanks @mmastrac  -- we have found a workaround.
