### ISSUE TITLE
Disambiguate nested modules with repeated names (`clippy::module_inception`)

### ISSUE THREAD

**Issue by LouisGariepy** [apache/arrow-datafusion#6496]
# Problem

This is a follow-up to #207 where this issue was identified.

There are two instances of `allow(clippy:module_inception)` left in the code: [catalog::catalog](https://github.com/apache/arrow-datafusion/blob/ff2fd62ee8fdae42ae63bcbc4d5f6b4afadeb056/datafusion/core/src/catalog/mod.rs#L25-L26) and [datasource::datasource](https://github.com/apache/arrow-datafusion/blob/ff2fd62ee8fdae42ae63bcbc4d5f6b4afadeb056/datafusion/core/src/datasource/mod.rs#L23-L24).

Ideally, modules should have a descriptive name that allows users to efficiently navigate the library.

I'd like to establish a path forward to solve these.

# Solution

### `catalog::catalog`

The parent module is described as containing "table namespacing concepts, including catalogs and schemas". A good name that encompasses both catalogs and schemas might be something like `metadata`, or `table_metadata`.

Thus, we'd end up with `metadata::catalog` or `table_metadata::catalog`.

### `datasource::datasource`

The child module only contains two items: `TableProvider` and `TableProviderFactory`. That module could be renamed to `provider` or `table_provider`.

Thus, we'd end up with `datasource::provider` or `datasource::table_provider`.

# Alternative

Alternatively, we could leave things as is. In that case, the `TODO(clippy)` that were linked in the Problem section above should be removed.

**Comment by alamb** [comment]
> catalog::catalog

I think `catalog` is a common "database"y term for what is in `catalog`

What do you think about simply moving the contents of `catalog/catalog.rs` into `catalog/mod.rs` ? 

https://github.com/apache/arrow-datafusion/blob/3907997cd0bcf24e1f4e50c272ec50265bc07c23/datafusion/core/src/catalog/catalog.rs#L18

So instead of `catalog::catalog::Catalog` code could just refer to `catalog::Catalog`?

**Comment by alamb** [comment]
> datasource::datasource

> That module could be renamed to provider or table_provider.

I like the idea of `provider` -- or likewise we could move the code up one level to be `datasource::TableProvider` (rather than `datasource::datasource::TableProvider`

**Comment by LouisGariepy** [comment]
> What do you think about simply moving the contents of catalog/catalog.rs into catalog/mod.rs ?

Sounds good!

> I like the idea of provider -- or likewise we could move the code up one level to be datasource::TableProvider (rather than datasource::datasource::TableProvider

I don't have a strong opinion on this. Both seem like fine options to me. I guess it depends how many provider-Related items and implementations are expected to be added in the future. If it's always mostly going to stay the same (just `TableProvider` and `TableProviderFactory` definitions), then moving them to the parent module is fine. Otherwise, I'd keep the submodule.

Once a consensus has been reached, I'll submit a PR to solve this :smile:

**Comment by alamb** [comment]
Perhaps @Dandandan  / @mustafasrepo  / @tustvold / @jackwener or @mingmwang  have opinions they would like to share?

**Comment by LouisGariepy** [comment]
@alamb Sorry to ping, I just wanted to ask if there's a path forward for this issue?

Otherwise, feel free to close this issue :smile:

**Comment by alamb** [comment]
> @alamb Sorry to ping, I just wanted to ask if there's a path forward for this issue?


I think we should bias towards action: you make a PR with the proposal you like best and we'll see if anyone wants to comment then (understanding they had a chance to comment before too).

**Comment by LouisGariepy** [comment]
@alamb Got it! I'll go ahead :)
