### ISSUE TITLE
Main branch gives clippy error

### ISSUE THREAD

**Issue by mustafasrepo** [apache/arrow-datafusion#6529]
### Describe the bug

Main branch gives clippy error 
```rust
error: this is an outer doc comment and does not apply to the parent module or crate
  --> datafusion/expr/src/conditional_expressions.rs:19:1
   |
19 | ///! Conditional expressions
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#suspicious_doc_comments
   = note: `-D clippy::suspicious-doc-comments` implied by `-D warnings`
help: use an inner doc comment to document the parent module or crate
```

### Additional context

This error occurred after doing `rustup update`. I think latest changes, brought extra checks, and previously allowed patterns are now rejected

**Comment by alamb** [comment]
I will submit a fix for this 

It appears that rust 1.70.0 has been released: https://blog.rust-lang.org/2023/06/01/Rust-1.70.0.html

**Comment by alamb** [comment]
https://github.com/apache/arrow-datafusion/pull/6535
