### ISSUE TITLE
Substrait: Support for more flexible join condition expressions

### ISSUE THREAD

**Issue by nseekhao** [apache/arrow-datafusion#6544]
### Is your feature request related to a problem or challenge?

If you run a roundtrip test on
```sql
SELECT d1.b, d2.c FROM data d1 JOIN data d2 ON CAST(d1.b AS int) = d2.e
```
you'll got the error `Error: Internal("invalid join condition expression")`.

This is due to the lack of support of expressions not in the form `AND(f0(...), ..., fk(...))`, where `fi()` is `EQ()` in the consumer ([ref](https://github.com/apache/arrow-datafusion/blob/main/datafusion/substrait/src/logical_plan/consumer.rs#LL367C5-L367C5)).

### Describe the solution you'd like

Support for more arbitrary join condition expressions.

### Describe alternatives you've considered

This effort can be incremental. I just wanted to make sure this gets brought up and tracked.

**Comment by alamb** [comment]
I wonder if https://github.com/apache/arrow-datafusion/pull/6135 fixes this?

**Comment by nseekhao** [comment]
> I wonder if https://github.com/apache/arrow-datafusion/pull/6135 fixes this?

Hmmm I don't think so. Because of these [lines](https://github.com/apache/arrow-datafusion/pull/6135/files#diff-d1c5f4c37ac8286d2045acb61bee17382179469557132eb02844413b260ae41bR267-R269) in the producer:
``` rust
            if join.filter.is_some() {
                return Err(DataFusionError::NotImplemented("join filter".to_string()));
            }
```

**Comment by waynexia** [comment]
The new roundtrip tests cover SQL in this issue (except the `CAST` part). Closing this ticket
