### ISSUE TITLE
Improve performance of SortPreservingMergeExec

### ISSUE THREAD

**Issue by NGA-TRAN** [apache/arrow-datafusion#655]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
While doing experience in IOx, we have discovered that `SortPreservingMergeExec` is expensive and very CPU bound. [The issues are fully described here](https://github.com/influxdata/influxdb_iox/issues/1885) 

**Describe the solution you'd like**
The SortPreservingMergeExec is known the be sub-optimal when it was implemented and at least 3 improvements have been identified inside the code. This ticket is to improve those and further if any.

**Comment by alamb** [comment]
I believe @e-dard  has plans to look into this ticket
