### ISSUE TITLE
Supports NULL in arrays

### ISSUE THREAD

**Issue by izveigor** [apache/arrow-datafusion#6556]
### Is your feature request related to a problem or challenge?

Follow on to https://github.com/apache/arrow-datafusion/pull/6384

The function `make_array` was implemented in `arrow-datafusion` without supporting null elements, I think it would be better to take the concept to support NULLS in different arrays and their methods.

All methods should support this feature, especially the method `array_to_string` (See PR: https://github.com/apache/arrow-datafusion/pull/6384) should support `null_string` argument to replace NULL with it.

### Describe the solution you'd like

I suggest to consider use `try_new` method (See https://docs.rs/arrow/latest/arrow/array/struct.PrimitiveArray.html#method.try_new)

Examples:
```
select make_array(NULL);
----
NULL
```

```
select make_array(1, NULL, 2, 3, NULL);
----
1 NULL 2 3 NULL
```

```
select array_to_string(make_array(1, NULL, 2, 3, NULL), ',', '*');
----
1,*,2,3,*
```

### Additional context

Simillar Issues:
https://github.com/apache/arrow-datafusion/issues/6119

Simillar PR:
https://github.com/apache/arrow-datafusion/pull/3122
https://github.com/apache/arrow-datafusion/pull/3199

**Comment by jackwener** [comment]
thanks @izveigor !
