### ISSUE TITLE
Cast between array elements

### ISSUE THREAD

**Issue by izveigor** [apache/arrow-datafusion#6558]
### Is your feature request related to a problem or challenge?

Arter Pull Request: https://github.com/apache/arrow-datafusion/pull/6384, In `arrow-datafusion` casting between arrays elements stopped working. The feature could be of great help when working with different types of data.

### Describe the solution you'd like

All rules should be simillar to the `cast` function in `arrow-rs` (See https://docs.rs/arrow/latest/arrow/compute/kernels/cast/index.html)

For example, if we create new array with `Int32Type` and `Int64Type` should return `Int64Array`.
```
select make_array(Int32(1), Int64(2));
----
Int64(1), Int64(2)
```

### Additional context

Simillar Issues:
https://github.com/apache/arrow-datafusion/issues/6119
https://github.com/apache/arrow-datafusion/issues/6075

Simillar PR:
https://github.com/apache/arrow-datafusion/pull/6384

**Comment by jayzhan211** [comment]
How to determine the final data type? Can with have a data_type argument in make_array(array, target_data_type) to check whether the elements are all possible to cast to target_data_type?

**Comment by jayzhan211** [comment]
I will take this
