### ISSUE TITLE
Support empty array

### ISSUE THREAD

**Issue by izveigor** [apache/arrow-datafusion#6561]
### Is your feature request related to a problem or challenge?

Follow on to https://github.com/apache/arrow-datafusion/pull/6384
The basic idea is to create an empty array using the function `array_make` when it takes empty arguments. Also, all array functions must accept an empty array and work with it.

### Describe the solution you'd like

Examples:
```
select make_array();
----
[]
```

```
select array_concat(trim_array(make_array(1, 2, 3), 3), make_array(4, 5), make_array())
----
[4, 5]
```

### Describe alternatives you've considered

If in the course of conversations it turns out that the feature is useless. 

### Additional context

Simillar Issues:
https://github.com/apache/arrow-datafusion/issues/6119
https://github.com/apache/arrow-datafusion/issues/6075.

**Comment by alamb** [comment]
I think this is a good first issue for someone to help with

**Comment by parkma99** [comment]
I'd like to work on this . Is anyone already preparing a PR?
