### ISSUE TITLE
Why exclude datafusion-cli from workspace?

### ISSUE THREAD

**Issue by r4ntix** [apache/arrow-datafusion#6577]
### Describe the bug

The tests for `datafusion-cli` is failing in the current main branch, but our CI doesn't find it.
```shell
$ cargo test
   Compiling datafusion-cli v26.0.0 (/Users/r4ntix/Workspace/github/arrow-datafusion/datafusion-cli)
error[E0277]: the `?` operator can only be applied to values that implement `Try`
   --> datafusion-cli/src/exec.rs:251:17
    |
251 |                 create_external_table(&ctx, cmd)?;
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the `?` operator cannot be applied to type `impl Future<Output = std::result::Result<(), datafusion::error::DataFusionError>>`
    |
    = help: the trait `Try` is not implemented for `impl Future<Output = std::result::Result<(), datafusion::error::DataFusionError>>`
help: consider `await`ing on the `Future`
    |
251 |                 create_external_table(&ctx, cmd).await?;
    |                                                 ++++++

For more information about this error, try `rustc --explain E0277`.
error: could not compile `datafusion-cli` due to previous error
```

I noticed that we currently exclude `datafusion-cli` from workspace.

### To Reproduce

```
$ cd datafusion-cli
$ cargo test
```

**Comment by r4ntix** [comment]
The current test bug of datafusion-cli has been fixed in #6576 . 
But should we add datafusion-cli to workspace to guarantee that the tests are covered？

**Comment by jiangzhx** [comment]
HaHa
 i find the PR to exclude datafusion-cli. hope it's help for you.

https://github.com/apache/arrow-datafusion/pull/2112#issuecomment-1081477416
and also 
@liukun4515 ask the same question too.

**Comment by alamb** [comment]
> The current test bug of datafusion-cli has been fixed in https://github.com/apache/arrow-datafusion/pull/6576 .

Thank you!

> But should we add datafusion-cli to workspace to guarantee that the tests are covered？

There were reasons (related to publishing datafusion-cli as a package -- https://github.com/apache/arrow-datafusion/issues/2071  -- as I remember 🤔 ) for not putting it i the workspace. 

I think we could run the datafusion-cli tests by adding a specific CI job that ran them, like:
```shell
cd datafusion/datafusion-cli
cargo test --all-features
```

What do you think @r4ntix ?

**Comment by r4ntix** [comment]
@alamb @jiangzhx Thanks.
From #2071 's comment, I see that it can make sense. 
I will try to add datafusion-cli test to the CI Job.
