### ISSUE TITLE
Add datafusion to the DuckDB flavored h2o.ai benchmark

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#6584]
### Is your feature request related to a problem or challenge?

DuckDB has revived the h20.ai benchmark: https://duckdb.org/2023/04/14/h2oai.html

Previously we have done various versions of the h20.ai benchmarks (e.g. https://github.com/apache/arrow-datafusion/issues/147) -- see full list [here](https://github.com/apache/arrow-datafusion/issues?q=is%3Aissue+h2o+is%3Aclosed)

@kszlim has requested that DataFusion be added to the new incarnation of the benchmark
https://github.com/duckdblabs/db-benchmark/issues/5

### Describe the solution you'd like

Help add datafusion to the benchmark

**Comment by Dandandan** [comment]
https://github.com/duckdblabs/db-benchmark/pull/18

**Comment by Dandandan** [comment]
Closed by https://github.com/duckdblabs/db-benchmark/pull/18
