### ISSUE TITLE
Discuss: don't allow not() param is `IntegerType`

### ISSUE THREAD

**Issue by jackwener** [apache/arrow-datafusion#6589]
### Describe the bug

I'm working for `type coercion`. I find

now
```sql
tests/sqllogictests/test_files/scalar.slt:914

query BB
SELECT not(1), not(0)
----
-2 -1
```

I think we should allow it. it break `type system` and its result is strange.

pg

```sql
psql:commands.sql:15: ERROR:  argument of NOT must be type boolean, not type integer
LINE 1: SELECT not(1), not(0);
```

**Comment by jackwener** [comment]
cc @liukun4515 @alamb @Dandandan

**Comment by alamb** [comment]
FYI @izveigor  who I think added this feature

I think `not(int)` means the same as `bitwisenot` -- aka `~ int` in postgres: https://www.postgresql.org/docs/9.4/functions-bitstring.html

I don't have any strong opinoion about supporting not(int) vs only `~`.

**Comment by jackwener** [comment]
if we let `not(int)` same with `bitwisenot`, there will be incompatibility at the point of processing NULL.

- `not(null)` is `true`
- `~(NULL:int)` is `null`

```sql
SELECT ~(NULL::int) is NULL;
-
t

SELECT not(NULL) is true;
-
t
```

**Comment by liukun4515** [comment]
> cc @liukun4515 @alamb @Dandandan

I need more time to look at the current implementation.

**Comment by jackwener** [comment]
related PR #5902
