### ISSUE TITLE
Support nested structs in Struct expression

### ISSUE THREAD

**Issue by oridag** [apache/arrow-datafusion#6598]
### Is your feature request related to a problem or challenge?

Required to allow transformations the produce complex structured data

### Describe the solution you'd like

Allow structs and array within a struct expression

### Additional context

Currently, only primitive types are supported:
```rust
/// Currently supported types by the struct function.
pub static SUPPORTED_STRUCT_TYPES: &[DataType] = &[
    DataType::Boolean,
    DataType::UInt8,
    DataType::UInt16,
    DataType::UInt32,
    DataType::UInt64,
    DataType::Int8,
    DataType::Int16,
    DataType::Int32,
    DataType::Int64,
    DataType::Float32,
    DataType::Float64,
    DataType::Utf8,
    DataType::LargeUtf8,
];
```

**Comment by jiangzhx** [comment]
https://github.com/apache/arrow-datafusion/issues/2326

**Comment by jayzhan211** [comment]
This could be closed
