### ISSUE TITLE
Optimizer rule `scalar_subquery_to_join` generates a different schema

### ISSUE THREAD

**Issue by jonahgao** [apache/arrow-datafusion#6606]
### Describe the bug

Internal error: Optimizer rule 'scalar_subquery_to_join' failed, due to generate a different schema, 
  
original schema: DFSchema { fields: [DFField { qualifier: None, field: Field { name: "t.a > **AVG(t.a)**", data_type: Boolean, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} } }], metadata: {} }, 

new schema  : DFSchema { fields: [DFField { qualifier: None, field: Field { name: "t.a > **__scalar_sq_1.__value**", data_type: Boolean, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} } }], metadata: {} }. 

This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker

### To Reproduce

```shell
DataFusion CLI v26.0.0
❯ create table t(a int);
0 rows in set. Query took 0.005 seconds.

❯ select a > (select avg(a) from t) from t;
scalar_subquery_to_join
caused by
Internal error: Optimizer rule 'scalar_subquery_to_join' failed, due to generate a different schema, original schema: DFSchema { fields: [DFField { qualifier: None, field: Field { name: "t.a > AVG(t.a)", data_type: Boolean, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} } }], metadata: {} }, new schema: DFSchema { fields: [DFField { qualifier: None, field: Field { name: "t.a > __scalar_sq_1.__value", data_type: Boolean, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} } }], metadata: {} }. This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker

```

**Comment by mingmwang** [comment]
I will take a look

**Comment by parkma99** [comment]
> I will take a look

I think it's because the code [L98](https://github.com/apache/arrow-datafusion/blob/d584d55a9dd1c729ef8ef6d1a3d9151d221ee7d9/datafusion/optimizer/src/scalar_subquery_to_join.rs#L98) to [L102](https://github.com/apache/arrow-datafusion/blob/d584d55a9dd1c729ef8ef6d1a3d9151d221ee7d9/datafusion/optimizer/src/scalar_subquery_to_join.rs#L102) should check subquery is a `scalar query` or not.

**Comment by mingmwang** [comment]
@parkma99 
I think the issue is fixed after this PR https://github.com/apache/arrow-datafusion/pull/6457.
I had verified and the error is gone.

**Comment by mingmwang** [comment]
@alamb
