### ISSUE TITLE
build failure in object store

### ISSUE THREAD

**Issue by mingmwang** [apache/arrow-datafusion#6650]
### Describe the bug

error[E0599]: no method named `build_split` found for struct `RequestBuilder` in the current scope
   --> /Users/mingmwang/.cargo/registry/src/github.com-1ecc6299db9ec823/object_store-0.6.1/src/aws/credential.rs:231:38
    |
231 |         let (client, request) = self.build_split();
    |                                      ^^^^^^^^^^^ method not found in `RequestBuilder`

error[E0599]: no function or associated item named `from_parts` found for struct `RequestBuilder` in the current scope
   --> /Users/mingmwang/.cargo/registry/src/github.com-1ecc6299db9ec823/object_store-0.6.1/src/aws/credential.rs:238:15
    |
238 |         Self::from_parts(client, request)
    |               ^^^^^^^^^^ function or associated item not found in `RequestBuilder`

### To Reproduce

cargo clean

cargo build

**Comment by mingmwang** [comment]
Is the version correct ?
 
Compiling reqwest v0.11.13

**Comment by alamb** [comment]
Maybe we need to update the minimum versions declared in Cargo.toml somewhere
