### ISSUE TITLE
aliasing a field renders it missing in the order by clause

### ISSUE THREAD

**Issue by Jimexist** [apache/arrow-datafusion#669]
**Describe the bug**

aliasing a field renders it missing in the order by clause. possible tightly coupled with #609 

**To Reproduce**

```sql
select c1 x from test order by c1
```

```
Plan("No field with unqualified name 'c1'. Valid fields are 'x'.")
```

**Expected behavior**

it shall work

**Additional context**

**Comment by houqp** [comment]
Yes, this is likely caused by the same root cause from #609. We currently cannot filter on non-projected columns.

**Comment by Jefffrey** [comment]
Looks resolved as of latest master

```sql
DataFusion CLI v16.0.0
❯ CREATE EXTERNAL TABLE test STORED AS CSV LOCATION 'test.csv';
0 rows in set. Query took 0.010 seconds.
❯ select column_1 x from test order by column_1 desc;
+---+
| x |
+---+
| 4 |
| 1 |
+---+
2 rows in set. Query took 0.014 seconds.
❯ select column_1 x from test order by x desc;
+---+
| x |
+---+
| 4 |
| 1 |
+---+
2 rows in set. Query took 0.014 seconds.
❯
```

**Comment by alamb** [comment]
I believe I have a fix for another part of this as well https://github.com/apache/arrow-datafusion/pull/5067

**Comment by alamb** [comment]
Thanks @Jefffrey  -- feel free to tag me on any ticket if you thing it should be closed
