### ISSUE TITLE
bug: array_length only return 1 element

### ISSUE THREAD

**Issue by BubbaJoe** [apache/arrow-datafusion#6693]
### Describe the bug

`select array_field from table`

| array_field |
|---|
| `[abc, acb]` |
| `[bca, bac]` |
| `[cab, cba]` |

`select array_length(array_field) from table`
| array_length(array_field) |
|---|
| 2 |

### To Reproduce

`select array_length(array_field) from table`

### Expected behavior

`select array_length(array_field) from table`
| array_length(array_field) |
|---|
| 2 |
| 2 |
| 2 |

### Additional context

array_field: Utf8

**Comment by parkma99** [comment]
I will take it and #6694

**Comment by Weijun-H** [comment]
I believe this problem arises from our approach of treating all instances of `List` as the same situation.
https://github.com/apache/arrow-datafusion/blob/94c442c8ff24a2b23f29d7579a0560c6daf76be9/datafusion/physical-expr/src/array_expressions.rs#L951-L958
