### ISSUE TITLE
DataFusion logo needs a white background

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#67]
**Describe the bug**
The logo looks bad for users using GitHub in dark mode:

![dflogodarkmode](https://user-images.githubusercontent.com/934084/115996571-0c50c300-a59d-11eb-9091-be87a4c1fa8c.png)

**To Reproduce**
Use dark mode.

**Expected behavior**
Logo should look good. Perhaps a white background?

**Additional context**
None

**Comment by msathis** [comment]
We already have two different logos for light, dark modes. But unfortunately github doesn't support conditional image switching in markdown https://github.community/t/support-theme-context-for-images-in-light-vs-dark-mode/147981/35

So your idea of making it white background is the best option. If anyone has better suggestions, Please share.
