### ISSUE TITLE
good first PR: add SQL metrics to window function expressions

### ISSUE THREAD

**Issue by Jimexist** [apache/arrow-datafusion#672]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
(This section helps Arrow developers understand the context and *why* for this feature, in addition to  the *what*)

similar to that in hash aggregates, we can have SQL metrics to be added to physical expressions of window functions

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alamb** [comment]
added in https://github.com/apache/arrow-datafusion/pull/1018
