### ISSUE TITLE
Support `Like` and other familiar exprs in substrait

### ISSUE THREAD

**Issue by waynexia** [apache/arrow-datafusion#6731]
### Is your feature request related to a problem or challenge?

Logical expr `Expr::Like` is a common expression.

### Describe the solution you'd like

Support it in substrait logical plan

### Additional context

related to https://github.com/GreptimeTeam/greptimedb/pull/1806

**Comment by nseekhao** [comment]
Hi @waynexia.

Have you started working on this issue yet?

If so, do you have an ETA on this support? No rush, though. Just want to understand the timeline 😅 

Thanks for reporting and working on this!

**Comment by waynexia** [comment]
I plan to do it this week 😉
