### ISSUE TITLE
Implement serialization for UDWF as window function in plan protobuf #4584

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#6733]
### Is your feature request related to a problem or challenge?

Similarly to https://github.com/apache/arrow-datafusion/issues/4584

Follow on to https://github.com/apache/arrow-datafusion/pull/6703 to add serialization support for user defined window functions when serializing plans

**Comment by parkma99** [comment]
I would like to work this.Could you give me some tips for starting this issue?

**Comment by alamb** [comment]
The basic idea would be to fix this code: https://github.com/apache/arrow-datafusion/blob/80d1750fda0f8d1d09d7bbf5b05662b1f6618954/datafusion/proto/src/logical_plan/to_proto.rs#L593-L597

I think you can generally follow the model of `AggregateUDF`

So I would recommend this order:
1. Write a round trip test first -- following the model of https://github.com/apache/arrow-datafusion/blob/80d1750fda0f8d1d09d7bbf5b05662b1f6618954/datafusion/proto/src/logical_plan/mod.rs#L2606-L2663
2. Write the code

**Comment by parkma99** [comment]
> I think you can generally follow the model of AggregateUDF

@alamb  Thanks, I will have a look late.😊

**Comment by Jefffrey** [comment]
This issue looks good to close?

cc @alamb

**Comment by alamb** [comment]
I agree -- thanks @Jefffrey  (and @parkma99 !)
