### ISSUE TITLE
Trouble getting fancy with ARRAY_AGG (DISTINCT ARRAY_AGG)

### ISSUE THREAD

**Issue by bellwether-softworks** [apache/arrow-datafusion#6743]
### Describe the bug

`ARRAY_AGG` usage in SQL results in an error when used in conjunction with `DISTINCT` parameter alongside another aggregate field.

### To Reproduce

1. Establish example data:
  ```sql
  CREATE TABLE example(id INT, parent_id INT, tag VARCHAR) AS VALUES
      (1, 0, 'bob'),
      (2, 0, 'cat'),
      (3, 1, 'tom'),
      (4, 1, 'cat'),
      (5, 1, 'tom');
  ```
2. Execute query using `ARRAY_AGG` and `DISTINCT` parameter:
  ```sql
  SELECT
          parent_id,
          COUNT(id) AS count_of,
          ARRAY_AGG(DISTINCT tag) AS tags
      FROM example
      GROUP BY parent_id;
  ```

Executing the above results in the following message:
```
ArrowError(ExternalError(Internal("Inconsistent types in ScalarValue::iter_to_array. Expected Utf8, got List([tom,cat])")))
```

### Expected behavior

Desired output should be similar to the following:

| parent_id | count_of | tags            |
|-----------|----------|-----------------|
| 1         | 3        | [tom, cat] |
| 0         | 2        | [bob, cat]      |

### Additional context

Omitting either the `COUNT` field, or the `DISTINCT` clause in `ARRAY_AGG`, allows the query to complete successfully.

The above was initially discovered in v17.0.0 and verified to still be presenting in v26.0.0.

**Comment by parkma99** [comment]
It probably panic in here https://github.com/apache/arrow-datafusion/blob/8be5a8ced87ccf4fb09d33f1f52c525027696e2b/datafusion/common/src/scalar.rs#L2317.

I am confusing where the `sv` defined.

Same question in https://github.com/apache/arrow-datafusion/blob/8be5a8ced87ccf4fb09d33f1f52c525027696e2b/datafusion/common/src/scalar.rs#L2285

cc @alamb

**Comment by alamb** [comment]
> I am confusing where the sv defined.

In the code you referenced this is basically the catch all meaning "if the type doesn't match one of the other branches"

**Comment by alamb** [comment]
Thanks for the report @bellwether-softworks  -- I added this to https://github.com/apache/arrow-datafusion/issues/2326

**Comment by parkma99** [comment]
> In the code you referenced this is basically the catch all meaning "if the type doesn't match one of the other branches"

Sorry I make a stupid question.😂

**Comment by alamb** [comment]
> Sorry I make a stupid question.😂

Not at all -- we are all learning here together!
