### ISSUE TITLE
Allow usage of datafusion-cli from other programs

### ISSUE THREAD

**Issue by collimarco** [apache/arrow-datafusion#6763]
### Is your feature request related to a problem or challenge?

If we had these two options we could invoke `datafusion-cli` directly from other programs and languages:

1. a `-command ` option to pass the SQL query directly as an argument on the command line
2. a `-format` option to create an output that is machine readable, like CSV, JSON or Parquet

Both options are supported for example by `psql` (Postgresql client) and it would be nice to have the same feature for `datafusion`. This would allow to invoke a standalone program (datafusion-cli) from other programs or from bash, for example to query a file using SQL.

**Comment by r4ntix** [comment]
The current datafusion-cli has the ability to execute sql file and format the output:
```shell
$ echo 'show tables;' > sql.txt

$ ./target/debug/datafusion-cli --file sql.txt --format json
DataFusion CLI v26.0.0
[{"table_catalog":"datafusion","table_name":"tables","table_schema":"information_schema","table_type":"VIEW"},{"table_catalog":"datafusion","table_name":"views","table_schema":"information_schema","table_type":"VIEW"},{"table_catalog":"datafusion","table_name":"columns","table_schema":"information_schema","table_type":"VIEW"},{"table_catalog":"datafusion","table_name":"df_settings","table_schema":"information_schema","table_type":"VIEW"}]
4 rows in set. Query took 0.045 seconds.
```

I don't know if this will work for you? 🤔️

**Comment by collimarco** [comment]
@r4ntix Wow, great.

The only thing that is missing is the ability to **pass the SQL query directly as a command line argument**, instead of creating a file with the SQL. 

That would be useful when you invoke the datafusion-cli from other programs and it would be similar to other databases (like the `-c` option of `psql`).

**Comment by r4ntix** [comment]
@collimarco  it make sense to me, thanks for your suggestion. I am going to make a PR for this.
