### ISSUE TITLE
Support binary data type literals

### ISSUE THREAD

**Issue by ShiKaiWi** [apache/arrow-datafusion#6764]
### Is your feature request related to a problem or challenge?

Currently, the binary data can't be used in the query sql, e.g., if submit the query `select * from demo where value = x'11`, the error `Error during planning: Unsupported Value 'HexStringLiteral(\"11\")'"` will be thrown.

### Describe the solution you'd like

After digging into the code, https://github.com/apache/arrow-datafusion/blob/8c7678a0b10d14029b5c34f822dc2605e00390fd/datafusion/sql/src/expr/value.rs#L30-L47

`Value::HexStringLiteral`  is not found in the match arms. Maybe a simple solution is to add such an arm to handle hex string literals.

### Describe alternatives you've considered

None.

**Comment by jackwener** [comment]
Are you trying to fix it, if so I can assign it to you.

**Comment by ShiKaiWi** [comment]
> Are you trying to fix it? if so I can assign it to you.

Ok.I am glad to fix it.

**Comment by ShiKaiWi** [comment]
@jackwener I've submitted a PR to address this issue. Would you like to give a look at https://github.com/apache/arrow-datafusion/pull/6767?
