### ISSUE TITLE
Blog post with DataFusion Jun - Sep 2023

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#6780]
### Is your feature request related to a problem or challenge?

We have had good luck writing up quarterly updates for DataFusion, most recently:
https://arrow.apache.org/blog/2023/06/24/datafusion-25.0.0/

(see https://github.com/apache/arrow-datafusion/issues/5812)

### Describe the solution you'd like

It would be great to write another about what has happened in the last few months of DataFusion

Things I expect will be good to highlight (🤞 ):
* Improved Struct/array support (@izveigor ❤️ )
* better group by performance with many distinct groups 
* better insert performance

Others?

**Comment by alamb** [comment]
Ideas of Major items to include in this post

1. User defined window functions: https://github.com/apache/arrow-datafusion/issues/6781
2. faster aggregatge performance -- https://github.com/apache/arrow-datafusion/issues/4973
3. Support for ARRAY / Lists -- https://github.com/apache/arrow-datafusion/issues/6863 etc (thanks @izveigor  and @jayzhan211 )

**Comment by Dandandan** [comment]
Improved join performance would maybe be another thing to highlight. Maybe we show a benchmark with improvements (TCP-H, ClickBench, ...) from version 25 -> 28.

- https://github.com/apache/arrow-datafusion/pull/6724
- https://github.com/apache/arrow-datafusion/pull/6679

**Comment by alamb** [comment]
There has been major work on `INSERT` and `COPY` as well, thanks to @devinjdangelo : https://github.com/apache/arrow-datafusion/issues/6569

**Comment by alamb** [comment]
Also https://github.com/apache/arrow-datafusion/pull/7400 spilling group by

**Comment by alamb** [comment]
Another topic: the new library user guide: https://arrow.apache.org/datafusion/library-user-guide/index.html

**Comment by alamb** [comment]
FYI this is very much on my list, but I need to focus on the SIGMOD paper for a while. If someone else has the time and inclination to start a PR I would be most appreciative

**Comment by alamb** [comment]
Realistically I am very tied up with https://github.com/apache/arrow-datafusion/issues/6782 and so won't have time to work on a blog post until after that is submitted (end of Nov). If someone else has time to work on this it would be very much apprecaited

**Comment by alamb** [comment]
This is going to have to be more like a 2023 retrospective 🤔

**Comment by alamb** [comment]
I am starting to draft this now

**Comment by alamb** [comment]
Here is a PR with a draft (still needs more work): https://github.com/apache/arrow-site/pull/457

**Comment by alamb** [comment]
Let's capture other items to highlight here https://github.com/apache/arrow-datafusion/issues/9602
