### ISSUE TITLE
Allow multiple statements in `datafusion-cli`

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#6793]
### Is your feature request related to a problem or challenge?

This has annoyed me for a while so I am filing a ticket in case someone has time to  fix it

I am trying to copy/paste the reproducer for https://github.com/apache/arrow-datafusion/issues/6790 into `datafusion-cli`

When I try to do so I get an error about "you entered more than one statement"

```
❯ create table "MyTable" (
"A"    VARCHAR,
"B"    VARCHAR,
"time" timestamp
);


SELECT "A", COUNT(DISTINCT("B"))
FROM "MyTable"
WHERE time >= now() - interval '1 month'
GROUP BY "A"
LIMIT 10;
🤔 You entered more than one statement
```

### Describe the solution you'd like

I would like `datafusion-cli` to execute all the statements I entered, one at at time

### Additional context

to run datafusion-cli:

```
cd datafusion-cli
cargo run
```

I think this is a good first issue as the code is localized and would be a nice usability improvement

**Comment by alamb** [comment]
cc @r4ntix  as I think you have been improving datafusion-cli recently

**Comment by r4ntix** [comment]
@alamb 
Thanks, I too think this is a good first issue. 
If there are new contributors who would like to try it, I can help with this. Or on the weekend, I will come to try to improve.

**Comment by alamb** [comment]
> Thanks, I too think this is a good first issue.

👍 

> If there are new contributors who would like to try it, I can help with this. Or on the weekend, I will come to try to improve.

Over the weekend often times I see new contributors look for things to do, so I would recommend giving it a few days and see if anyone responds

**Comment by NiwakaDev** [comment]
I'd like to work on this issue.
