### ISSUE TITLE
Enrich CSV reader config: `quote` & `escape`

### ISSUE THREAD

**Issue by DDtKey** [apache/arrow-datafusion#6854]
### Is your feature request related to a problem or challenge?

Currently CSV reader doesn't allow to set: `quote` & `escape` chars.

### Describe the solution you'd like

`CsvReadOptions` should contains methods to set `quote` & `escape` (like `delimiter`)

For example, how it works in `csv` crate: [escape](https://docs.rs/csv/latest/csv/struct.ReaderBuilder.html#method.escape) & [quote](https://docs.rs/csv/latest/csv/struct.ReaderBuilder.html#method.quote)

### Additional context

Escaping is optional stuff, usually it's just double usage of quote char, but it would be nice to be able to override.

**Comment by alamb** [comment]
I think this would be a matter of adding `quote` and `escape` to 
https://docs.rs/datafusion/latest/datafusion/datasource/file_format/options/struct.CsvReadOptions.html

The arrow csv parser has support for these already: https://docs.rs/arrow-csv/43.0.0/arrow_csv/reader/struct.ReaderBuilder.html

Thus I think this would be a matter of connecting some APIs and extending tests

**Comment by hi-rustin** [comment]
I am working on this.

**Comment by parkma99** [comment]
I would like to take it.😊
