### ISSUE TITLE
Implement `array_pop_front` function

### ISSUE THREAD

**Issue by izveigor** [apache/arrow-datafusion#6996]
## Summary

| Characteristic        | Description                                                                                                                                                               |
| --------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Function name:        | `array_pop_front`                                                                                                                                                         |
| Aliases:              | `list_pop_front`                                                                                                                                                          |
| Original function?:   | No                                                                                                                                                                        |
| Function Description: | <b>ClickHouse:</b> Removes the first item from the array. </br> <b>DuckDB:</b> Returns the list without the first element.                                                |
| Sources:              | [Concept](https://github.com/apache/arrow-datafusion/discussions/6855) [DuckDB](https://duckdb.org/docs/sql/functions/nested) [ClickHouse](https://clickhouse.com/docs/en/sql-reference/functions/array-functions#arraypopfront) |

## Examples:

```
D select array_pop_front([1, 2, 3, 4]);
┌──────────────────────────────────────────────┐
│ array_pop_front(main.list_value(1, 2, 3, 4)) │
│                   int32[]                    │
├──────────────────────────────────────────────┤
│ [2, 3, 4]                                    │
└──────────────────────────────────────────────┘
D select array_pop_front([[1, 2], [3, 4], [4, 2]]);
┌──────────────────────────────────────────────────────────────────────────────┐
│ array_pop_front(main.list_value(main.list_value(1, 2), main.list_value(3, …  │
│                                  int32[][]                                   │
├──────────────────────────────────────────────────────────────────────────────┤
│ [[3, 4], [4, 2]]                                                             │
└──────────────────────────────────────────────────────────────────────────────┘
```

**Comment by smallzhongfeng** [comment]
Hi, I'm interested in it. could I have a try? @izveigor

**Comment by smallzhongfeng** [comment]
Sorry for not seeing it in time! @Weijun-H

**Comment by Veeupup** [comment]
hi everyone! anything new? maybe I can help with this issue  : )

**Comment by tanruixiang** [comment]
> hi everyone! anything new? maybe I can help with this issue : )

Hi @Veeupup  I haven't had time to do this issue lately, you are welcome to participate, you can refer to  https://github.com/apache/arrow-datafusion/pulls
