### ISSUE TITLE
Error on Join: Schema error: Schema contains duplicate unqualified field name 

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#7027]
### Describe the bug

When trying to join two relations that have a column with the same name, we see an error

> Schema error: Schema contains duplicate unqualified field name cron_job_name

### To Reproduce

```
DataFusion CLI v27.0.0
❯ SELECT *
FROM (
VALUES ('catan-prod1-daily', 'success')
) as jobs(cron_job_name, status)
JOIN (
VALUES ('catan-prod1-daily', 'high')
) as severity(cron_job_name, level) ON (severity.cron_job_name =
jobs.cron_job_name);
Schema error: Schema contains duplicate unqualified field name cron_job_name
❯
```

### Expected behavior

Query should run

**Comment by dburton-influxdata** [comment]
@alamb Should this fix be applied to the customer's cluster environment or will it be applied sometime in the future? Also should the query work if the customer used the INNER JOIN instead of just JOIN?
