### ISSUE TITLE
IsNull filter seems not working correctly when there is only null values

### ISSUE THREAD

**Issue by xuchen-plus** [apache/arrow-datafusion#7038]
### Describe the bug

When applied `IsNull` filter on a dataframe's column with only `null` values, the filtered result is empty.

### To Reproduce

I used datafusion python binding with version 27.0.0 as a simple example. 
```
>>> import datafusion
>>> datafusion.__version__
'27.0.0'
```

```python
import pandas as pd
from datafusion import functions as f

pandas_df = pd.DataFrame({"a": [None], "b": [1]})
ctx = SessionContext()
df = ctx.from_pandas(pandas_df)
df.show()
```

The above prints the dataframe where `a`'s value is null:
```
>>> df.show()
DataFrame()
+---+---+
| a | b |
+---+---+
|   | 1 |
+---+---+
```

Now filter column `a` with is_null:
```python
df.filter(f.col("a").is_null()).show()
```

The result is empty:
```
DataFrame()
++
++
```

However if there are more rows with non-null values, the filtered result is correct:
```
>>> pandas_df = pd.DataFrame({"a": [None, 1], "b": [1, 2]})
>>> df = ctx.from_pandas(pandas_df)
>>> df.show()
DataFrame()
+-----+---+
| a   | b |
+-----+---+
|     | 1 |
| 1.0 | 2 |
+-----+---+
>>> df.filter(f.col("a").is_null()).show()
DataFrame()
+---+---+
| a | b |
+---+---+
|   | 1 |
+---+---+
```

### Expected behavior

The filtered result should contain the rows with null value.

**Comment by tustvold** [comment]
I think this is an upstream bug, will fix

**Comment by smiklos** [comment]
It seems that pandas will infer the [None] as Binary type but will infer [None, 1] as float. 

Binary types will become Null types in the conversion to datafusion and the compute kernel has a bug that will return false for `is_null` when the column type is Null. 

I've submitted an issue here https://github.com/apache/arrow-rs/issues/4565. 

In the meantime, if you specify the type of the column in advance it'll work as expected

**Comment by xuchen-plus** [comment]
Hi @smiklos , thanks for the prompt reply and fix. I'll try to test it later with the patch. I'll close this issue for now.
