### ISSUE TITLE
Improve physical plan with SortPreservingRepartitionExec when unioning sorted and unsorted inputs

### ISSUE THREAD

**Issue by wolffcm** [apache/arrow-datafusion#7077]
### Is your feature request related to a problem or challenge?

In IOx, many of our queries need to union data both from parquet files (which are sorted) and data from `RecordBatchesExec` (which is not sorted). The output of the union usually needs to be deduplicated (remove rows that have the same primary key). Deduplicating can be expensive. It requires sorted input, but it can be parallelized across multiple partitions.

Recently I started to experiment with using `SortPreservingRepartitionExec` to improve performance of deduplication. It works fine if the input is completely sorted, but if it is a union of sorted and unsorted data, I end up with a plan that sorts everything (even the parquet files which are already sorted) and doesn't use the sort-preserving variant of `RepartitionExec`.

That is to say, I end up with a plan that looks like this:
```text
DeduplicateExec: [tag@3 ASC,time@4 ASC]
  SortExec: expr=[tag@3 ASC,time@4 ASC,__chunk_order@0 ASC]
    CoalesceBatchesExec: target_batch_size=8192
      RepartitionExec: partitioning=Hash([tag@3, time@4], 4), input_partitions=4
        RepartitionExec: partitioning=RoundRobinBatch(4), input_partitions=2
          UnionExec
            RecordBatchesExec: batches_groups=1 batches=1 total_rows=2
            ParquetExec: file_groups={1 group: [[...]]}
```
(The back-to-back `RepartitionExec` also seems undesirable here)

But I would like to have a plan that looks like this:
```
DeduplicateExec: [tag@3 ASC,time@4 ASC]
  CoalesceBatchesExec: target_batch_size=8192
    SortPreservingRepartitionExec: partitioning=Hash(...), input_partitions=4  
      UnionExec
        SortExec: expr=[...]
          RecordBatchesExec: batches_groups=1 batches=1 total_rows=2
        ParquetExec: file_groups={1 group: [[...]]}
```
In practice, I have seen that re-sorting all the data makes performance quite a bit worse, even considering that deduplication can be parallelized.

### Describe the solution you'd like

I think this could be addressed by updating existing planner rules (like `replace_partition_execs`) or perhaps adding one or more new ones.

### Describe alternatives you've considered

The alternative here I think is what IOx does now, which is that it does not parallelize operations that require sorted input at all.

### Additional context

🎉 PR that introduced physical planner rules to create `SortPreservingRepartitionExec`: https://github.com/apache/arrow-datafusion/pull/6921

Related IOx issue: https://github.com/influxdata/influxdb_iox/issues/8292

**Comment by wolffcm** [comment]
cc @alamb @mertak @ozankabak @mustafasrepo

I would like to start working on this, provided no one else has plans to... please let me know. It seems like this case might be pretty specific to IOx.

**Comment by alamb** [comment]
> I would like to start working on this, provided no one else has plans to... please let me know. It seems like this case might be pretty specific to IOx.

I know if no other specific plans

**Comment by mustafasrepo** [comment]
I have opened the [PR](https://github.com/apache/arrow-datafusion/pull/7090) for refactor.

**Comment by wolffcm** [comment]
@mustafasrepo Your PR will be a very nice improvement. 

As I understand it, your PR looks for opportunities to remove explicit sorts when it's possible to preserve sort order by transforming `RepartitionExec -> SortPreservingRepartitionExec` or `CoalescePartitionsExec -> SortPreservingMergeExec`.

I think what I want to do is a similar generalization but for the `pushdown_sorts` pass of `EnforceSorting`. So I don't think what I want to do conflicts with your open PR.

As background, currently the pass `pushdown_sorts` works very nicely when a sort sits directly above a union:
```
DeduplicateExec: [...]
  SortPreservingMergeExec: [...]
    SortExec: expr=[...]
      UnionExec
        RecordBatchesExec: batches_groups=1 batches=1 total_rows=1
        ParquetExec: file_groups={...}
```
becomes
```
DeduplicateExec: [...]
  SortPreservingMergeExec: [...]
    UnionExec
      SortExec: expr=[...]
        RecordBatchesExec: batches_groups=1 batches=1 total_rows=1
      ParquetExec: file_groups={...}
```
-----
What I want to do is extend `pushdown_sorts` to do something like this:
```
DeduplicateExec: [...]
  SortExec: expr=[...]
    RepartitionExec: partitioning=Hash(...), input_partitions=12
      UnionExec
        RecordBatchesExec: batches_groups=1 batches=1 total_rows=1
        ParquetExec: file_groups={...}
```
Should become
```
DeduplicateExec: [...]
  SortPreservingRepartitionExec: partitioning=Hash(...), input_partitions=12
    UnionExec
      SortExec: expr=[...]
        RecordBatchesExec: batches_groups=1 batches=1 total_rows=1
      ParquetExec: file_groups={...}
```

**Comment by wolffcm** [comment]
Looking into this more I can see that `pushdown_sorts` will not push a `SortExec` through a `RepartitionExec` node. This makes sense since in general this means that the sort will be performed on parallel streams of data, which is good.

The problem is that in some cases (the case that I care about) we can further push down the sort through `UnionExec` node then end up not needing to sort in one or more inputs to the union which is advantageous. Incidentally, if no `SortExec` nodes were needed at all, such as if both sides of the `UnionExec` were sorted, I think that `replace_with_order_preserving_variants` would catch this case.

So I am left with wanting to push a `SortExec` node through `RepartionExec`s but only some of the time. I think the right heuristic is: push down `SortExec` if it would result in needing to sort fewer tuples overall. This is a new bit of analysis that I think `pushdown_sorts` will need to perform.

@alamb @mustafasrepo @ozankabak Do you all think that this approach makes sense?

**Comment by alamb** [comment]
> So I am left with wanting to push a SortExec node through RepartionExecs but only some of the time. I think the right heuristic is: push down SortExec if it would result in needing to sort fewer tuples overall. This is a new bit of analysis that I think pushdown_sorts will need to perform.

This sounds very much like a cost (estimate) based optimization. DataFusion has very few of these at the moment, and I think in general they cause confusion in other systems because what they will do is hard to predict (and relies on data properties, and thus hard to reproduce as well). 

In addition, estimating cardinalities is a known hard problem (especially with correlated predicates, data skew, joins, etc) 

For the IOx specific case, here are some possible alternatives:
1. A `ConfigOptions` setting to control if the sort is pushed through repartition 
2. A special case optimizer in IOx that pushes the sorts through unions / partitions
