### ISSUE TITLE
Deduplicate `README.md` files in root and datafusion directory

### ISSUE THREAD

**Issue by Dandandan** [apache/arrow-datafusion#71]
**Describe the bug**
The `README.md` files in the root and in the `datafusion` directory are (mostly) copies of each other.
There are small differences between the two, e.g. added functionality that is not included.

**Expected outcome **
Differences between the two are removed. Unneeded details in the root readme should be avoided.

**Comment by Dandandan** [comment]
@andygrove I suggest this is also a good first issue

**Comment by andygrove** [comment]
For some context on this, I had originally just moved the README from datafusion/ to top-level but then the build failed (rustdoc issue IIRC) so I just copied it to get the build working.
