### ISSUE TITLE
Update Clickbench results with DataFusion 28.0.0

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#7108]
### Is your feature request related to a problem or challenge?

With the release of DataFusion 28, it would be great to update the DataFusion performance reported on https://benchmark.clickhouse.com/

Notably, #6904 and related PRs for faster grouping performance show 2-3x performance improvements

### Describe the solution you'd like

Update the results. I am not 100% sure how to do so, but I think the discussions on https://github.com/apache/arrow-datafusion/issues/5276 contain the answer

The datafusion scripts are in https://github.com/ClickHouse/ClickBench/tree/main/datafusion

maybe @jychen7 knows / can provide some hints

**Comment by jychen7** [comment]
the readme of https://github.com/ClickHouse/ClickBench/blob/main/datafusion/README.md was updated at Apr this year and is likely still updated.

**Comment by jychen7** [comment]
I could set it up in weekend for v28

**Comment by jychen7** [comment]
the result is nice! Especially previous timeout query 32 now finish in 8s
https://github.com/ClickHouse/ClickBench/pull/127/files

**Comment by jychen7** [comment]
Also shall we create an issue to add `DataFusion (Parquet, partitioned)` to Clickbench? Current one is single parquet

**Comment by alamb** [comment]
> Also shall we create an issue to add DataFusion (Parquet, partitioned) to Clickbench? Current one is single parquet

Yes please do @jychen7 -- that would be amazing 

Note there is at least one query that will fail with the partitioned dataset in datafusion 28.0.0 due to https://github.com/apache/arrow-datafusion/issues/7039. @jonahgao  fixed the problem on main but I don't think the fix is in the 28.0.0 release

**Comment by alamb** [comment]
We just released datafusion 33, so I think this ticket is somewhat stale. If someone wants to update ClickBench again with the latest release, that would be great -- perhaps we can open a new ticket
