### ISSUE TITLE
Improve `GetIndexedField` in protobuf

### ISSUE THREAD

**Issue by izveigor** [apache/arrow-datafusion#7146]
### Is your feature request related to a problem or challenge?

Follow on to https://github.com/apache/arrow-datafusion/pull/6936.
The current implementation `GetIndexedField` in protocol buffer does not support optional argument `extra_key` (except of this, `GetIndexedField` supports only two required arguments).

So, what we should do:
-  [ ] We can call `GetIndexedField` in protocol buffer without `extra_key` (like `index[i]`)
-  [ ] We can call `GetIndexedField` in protocol buffer with `extra_key` (like `index[i:j]`)

**Comment by parkma99** [comment]
I would like to take it.

**Comment by parkma99** [comment]
Every thing is OK, I am at home this week.
