### ISSUE TITLE
Support simplifying expressions such as `~ ^(ba_r|foo)$` , where the string includes underline

### ISSUE THREAD

**Issue by tanruixiang** [apache/arrow-datafusion#7185]
### Describe the bug

Strings with underline are very common, e.g. id_1,id_2. But the current regrex expression optimization ignores underline. For regrex expressions of the form `~ ^(id_1|id_2)$`, we are required to support the string with underline.

`str = ~  ^(id_1|id_2)$`
could be rewritten as
`str = id_1 or str = id_2`

**Comment by tanruixiang** [comment]
> `_` has special meaning in SQL regex syntax, specifically matching any single character. Thus I am not sure the rewrite you propose is correct

Hi @alamb, Thank you very much for your reply.
`_`  has special meaning just in `Like`, Postgres(or mysql) use the `~` to  do the regex match.
If it's just the test cases I've given, there should be no correctness issues, but I'm not sure if the current complex datafusion rewrite rules cause `Like` to be hidden. Strings with `_` should be very common in the data, and if the current optimization framework doesn't support it, maybe we need to redesign the optimization framework.

```
test_db=> select 'id_1'  ~  '^(id_1)$';
 ?column?
----------
 t
(1 row)

test_db=> select 'id1'  ~  '^(id_1)$';
 ?column?
----------
 f
(1 row)

test_db=> select 'id%1'  ~  '^(id_1)$';
 ?column?
----------
 f
(1 row)

test_db=> select 'idt1'  ~ '^(id_1)$';
 ?column?
----------
 f
(1 row)
``

**Comment by alamb** [comment]
@tanruixiang  that makes sense -- thank you for clarifying

**Comment by alamb** [comment]
I think this is a nice new feature rather than a bug (incorrect results, or similar)
