### ISSUE TITLE
TPC-H q8 fails with overflow (since version 28)

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#7216]
### Describe the bug

```
Arrow error: Compute error: Overflow happened on: 19293795273 * 100000000000000000000000000000000000000
```

### To Reproduce

Here is a Google colab notebook that demonstrates the issue

https://colab.research.google.com/drive/13vCffhO1-IP3NtXT1FgO-j6MwoQZlPtm?usp=sharing

### Additional context

This was originally discovered by Mimoune Djouallah:

https://twitter.com/mim_djo/status/1686955130812542976?s=20

**Comment by alamb** [comment]
I think this may be fixed now  that https://github.com/apache/arrow-datafusion/pull/6832 has been merged

**Comment by viirya** [comment]
I've added additional cast to make TPCH q8 pass under benchmark. Let's see now if it can be passed after #6832.
