### ISSUE TITLE
Global limit isn't really limiting parquet file reads and stops earlier

### ISSUE THREAD

**Issue by Jimexist** [apache/arrow-datafusion#725]
**Describe the bug**

When given a global limit:

```sql
select * from some_large_data limit 50;
```

even with a `-c` being 100 i.e. small batch size, the global limit isn't really cutting running time small.

**To Reproduce**

this is easily reproducible given a large data set.

**Expected behavior**

this shall be giving answers rather immediately if global limit is small.

**Additional context**

**Comment by Dandandan** [comment]
I added some form of limit push down to parquet some time ago.
Might be that it isn't applied to your dataset somehow? Or maybe getting the metadata / statistics itself might be slow?

https://github.com/apache/arrow/pull/9672

**Comment by Jimexist** [comment]
> I added some form of limit push down to parquet some time ago.
> Might be that it isn't applied to your dataset somehow? Or maybe getting the metadata / statistics itself might be slow?
> 
> [apache/arrow#9672](https://github.com/apache/arrow/pull/9672)

I tried generating another file using https://gist.github.com/Jimexist/82717bc3ef32a366e11ef60e6e876fcc and it turns out that limit indeed works. that's 6405008 rows and `select * from table limit 10` returns within 0.5s, and selecting only one column returns in less than 0.03s, so i guess that's indeed taking effect.

i guess my original slow case was due to that the parquet file was directly pulled from HDFS, in which case the statistics are not working?

**Comment by Dandandan** [comment]
> > I added some form of limit push down to parquet some time ago.
> > Might be that it isn't applied to your dataset somehow? Or maybe getting the metadata / statistics itself might be slow?
> > [apache/arrow#9672](https://github.com/apache/arrow/pull/9672)
> 
> I tried generating another file using https://gist.github.com/Jimexist/82717bc3ef32a366e11ef60e6e876fcc and it turns out that limit indeed works. that's 6405008 rows and `select * from table limit 10` returns within 0.5s, and selecting only one column returns in less than 0.03s, so i guess that's indeed taking effect.
> 
> i guess my original slow case was due to that the parquet file was directly pulled from HDFS, in which case the statistics are not working?

Hm that's weird. We don't use the statistics for the limit, but reduce the amount scanned per file.
Would be great to have some reproduction on this. Maybe it has to do with large row groups?
