### ISSUE TITLE
Refactoring the array ecosystem

### ISSUE THREAD

**Issue by izveigor** [apache/arrow-datafusion#7279]
### Is your feature request related to a problem or challenge?

File codebase `array_expressions` increased from a few lines to a thousand in a few weeks. Arrow Datafusion now supports more than 20 array functions: we can create array by `make_array` function, find any element or replace it. At this stage, it would be wise to clean up the code.

Goals of refactoring 🎯:
- [ ] data types
- [ ] tests
- [ ] functionality of array functions
- [ ] add beautiful comments

**Comment by alamb** [comment]
cc @tustvold  who was just showing me that the amount of code generated for some of the array functions consumed non trivial code sapce

**Comment by jayzhan211** [comment]
This can be closed together with #7988

**Comment by alamb** [comment]
Thank you very much @jayzhan211
