### ISSUE TITLE
Test in information_schema.slt fails consistently

### ISSUE THREAD

**Issue by sarutak** [apache/arrow-datafusion#7285]
### Describe the bug

After #7270, test in `information_schema.slt` fails consistently.
https://github.com/apache/arrow-datafusion/actions/runs/5858702865/job/15883449656

**Comment by devinjdangelo** [comment]
This is ultimately my bad for hardcoding the Datafusion version in the test. I will look into a permanent fix prior to the next release so this doesn’t hit us again.

**Comment by jonahgao** [comment]
> This is ultimately my bad for hardcoding the Datafusion version in the test. I will look into a permanent fix prior to the next release so this doesn’t hit us again.

@devinjdangelo 
I think we can set it to a fixed value before executing `SHOW ALL`. 
This will help to handle future version upgrades.
```
statement ok
SET datafusion.execution.parquet.created_by=datafusion
```
