### ISSUE TITLE
Make it easier to install / get started with DataFusion

### ISSUE THREAD

**Issue by Dandandan** [apache/arrow-datafusion#7297]
### Is your feature request related to a problem or challenge?

Currently when someone stumbles on arrow-datafusion it is hard to find the installation instructions / starting guide. 

We should make it easier to get started with DataFusion by optimizing those pages.

https://github.com/apache/arrow-datafusion
https://arrow.apache.org/datafusion/

### Describe the solution you'd like

e.g. compared to 
https://duckdb.org/
https://www.pola.rs/

etc. has some clear links / buttons with installation instructions (`pip install ...`), `brew install ...`) and some example to be inspire the new user.

**Comment by Weijun-H** [comment]
datafusion has existed in `brew` and `pip`.

https://github.com/Homebrew/homebrew-core/blob/master/Formula/d/datafusion.rb
https://pypi.org/project/datafusion/
