### ISSUE TITLE
Library Guide: Adding User Defined Functions: Scalar/Window/Aggregate/

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#7307]
### Is your feature request related to a problem or challenge?

Part of https://github.com/apache/arrow-datafusion/issues/7014

If we want to have DataFusion used as the core of many new systems, we need it to be as easy as possible for someone to get their idea working on top of DataFusion.

Thanks to @tshauck we now have a basic Library Users Guide ❤️ and this ticket describes expanding it out

### Describe the solution you'd like

Fill in the content of https://arrow.apache.org/datafusion/library-user-guide/adding-udfs.html

Example Outline
1. How to create and register a `ScalarUDF`
1. How to create and register a `AggregateUDF`
1. How to create and register a `WindowUDF`

The examples directory holds a bunch more of examples: https://github.com/apache/arrow-datafusion/tree/main/datafusion-examples

**Comment by Veeupup** [comment]
hi! I can help with this issue, can I have a try?

**Comment by alamb** [comment]
@Veeupup  please! Thank you for crushing through the ticket load in the last few days

**Comment by alamb** [comment]
Note that https://github.com/apache/arrow-datafusion/issues/8045 may be related
