### ISSUE TITLE
Document DML statements

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#7319]
### Is your feature request related to a problem or challenge?

DataFusion now supports basic `INSERT` and `COPY` statements. 

### Describe the solution you'd like

We should update https://arrow.apache.org/datafusion/user-guide/sql/index.html to reflect this

Examples are in https://github.com/apache/arrow-datafusion/blob/main/datafusion/sqllogictest/test_files/copy.slt and https://github.com/apache/arrow-datafusion/blob/main/datafusion/sqllogictest/test_files/insert_to_external.slt

**Comment by spaydar** [comment]
I'll work on this
