### ISSUE TITLE
Consolidate  `OutputFileFormat` and `FileType`

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#7323]
### Is your feature request related to a problem or challenge?

https://github.com/apache/arrow-datafusion/pull/7283#discussion_r1294561258 added a `OutputFileFormat` enum  that is very similar to the existing [`FileType`](https://docs.rs/datafusion/latest/datafusion/datasource/file_format/file_type/enum.FileType.html) enum: 

https://github.com/apache/arrow-datafusion/blob/f2c0100a5a10bf3ea166a1a590d94b8c9b6cf673/datafusion/expr/src/logical_plan/dml.rs#L45-L53

### Describe the solution you'd like

Move `FileType` into `datafusion_common` and remove `OutputFileFormat` so it could be used by both the logical plan and datasource?

The tricky bit of this PR will be disentangling FileType from the code that instantiates compression: https://github.com/apache/arrow-datafusion/blob/f2c0100a5a10bf3ea166a1a590d94b8c9b6cf673/datafusion/core/src/datasource/file_format/file_type.rs#L287

I think we could move `FileType` over, however, and define some trait with `get_ext_with_compression` for the appropriate code

### Additional context

@devinjdangelo  and I discussed this here: https://github.com/apache/arrow-datafusion/pull/7283#discussion_r1294561258 

I think this would be a good first issue as it is primarily a code movement thing, doesn't require intimate knowledge of DataFusion's code, and would be a good introduction to the development workflow.

**Comment by devinjdangelo** [comment]
> The tricky bit of this PR will be disentangling FileType from the code that instantiates compression:

The idea I went with here is moving the entire file_type.rs file to common i.e.:

`git mv datafusion/core/src/datasource/file_format/file_type.rs datafusion/common/src/`

Loads of file imports to clean up after that, but it seems like it worked (PR: #7336 )
