### ISSUE TITLE
Wrong error for `substr` function

### ISSUE THREAD

**Issue by DDtKey** [apache/arrow-datafusion#7326]
### Describe the bug

Passing wrong type into `substr` function causes the `DataFusionError::InternalError`

```
Internal error: The "substr" function can only accept strings.. This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```

### To Reproduce

```sh
# with datafusion-cli
select substr(123, 1);
```

### Expected behavior

I'd expect the error kind to be `DataFusionError::Plan` probably, like these ones: https://github.com/apache/arrow-datafusion/blob/c50268670f8bee2022a9892a0c67073fc360352a/datafusion/expr/src/type_coercion/aggregates.rs#L147-L150

### Additional context

I guess the reason is here: https://github.com/apache/arrow-datafusion/blob/c50268670f8bee2022a9892a0c67073fc360352a/datafusion/expr/src/built_in_function.rs#L1404-L1417
There are several usages of  `InternalError` in the file.

_No response_

**Comment by alamb** [comment]
Thank you @DDtKey  -- I agree this is a problem. 
I think this is a good first issue as the code change will be small and involve writing a test and getting experience with the DataFusion code
