### ISSUE TITLE
Filters inside of Left Joins are ignored?

### ISSUE THREAD

**Issue by caseykneale** [apache/arrow-datafusion#7420]
### Describe the bug

I have a query like:
```SQL
                SELECT a.foreign_key, a.parent_type FROM table_a AS a
                LEFT JOIN table_b AS b
                ON a.thing = b.thing
                AND a.parent_type = 'OneOption' 
                AND b.parent_type = 'OneOption'
                AND a.is_thing = TRUE
                AND b.is_thing = TRUE
  ```
  
Unfortunately, when I run this query I see the results for all `parent_type` values rather than being exclusive to one as specified in the subqueries. I will see "OneOption", "TwoOption", etc. Meaning, the filter on the parent_type column is not working. I am able to add a WHERE clauses to filter after the joins which is less than ideal, but an acceptable workaround. Maybe I can make subqueries with the filtration step before the join as well.

### To Reproduce

Make a small CSV file containing the fields specified in the query, run the query and observe that filtration does not work on Left Joins. Load the same CSV in as table_a and table_b to a SessionContext.

### Expected behavior

Filtering on Left Joins allows for filtration via AND statements. Or warns if it cannot.

**Comment by Dandandan** [comment]
Can you provide an example of expected in/output? Left join will produce all left rows by definition, so the condition `a.parent_type='OneOption'` will have no effect on the query output (but will have when put in `WHERE`).

**Comment by caseykneale** [comment]
Oh shoot that's me forgetting SQL from not using it for 2 years. No worries!
