### ISSUE TITLE
Atomicity and Locking in Data Fusion [Question]

### ISSUE THREAD

**Issue by a-agmon** [apache/arrow-datafusion#7429]
I have a service that registers a table based on parquet files on S3, and then creates a mem table on top of it in order to enable fast access. 
`CREATE mem_table as SELECT * FROM s3_parquet_table`

My question is how to refresh the data while its being actively queried - perhaps by other threads?
Will running the DDL above safely lock the table until its refreshed? Will it fail incoming SQL queries?

**Comment by jiangzhx** [comment]
It's not a good idea to load all data into memory.  it's only save some disk I/O time.

about "safely lock",
you could consider creating two mem_tables and switching the query over to the 'refreshed' table.
this approach will use twice the amount of memory.

**Comment by a-agmon** [comment]
Thanks, @jiangzhx  - In my case, the IO is to object storage (S3) so it really helps in performance when I need to cache (it's not a lot of data cached). 
re the second issue, but is there a lock on the table once its being recreated? or would queries fail?

**Comment by jiangzhx** [comment]
Regarding local cache, perhaps JuiceFS or Alluxio would do a better job.
No, I don't think there is a 'lock' mechanism to ensure that the table is created. 

`pub async fn sql(&self, sql: &str) -> Result<DataFrame>`
You can use the returned parameter to confirm whether the SQL statement was executed successfully or not.

**Comment by alamb** [comment]
> My question is how to refresh the data while its being actively queried - perhaps by other threads?
> Will running the DDL above safely lock the table until its refreshed? Will it fail incoming SQL queries?

I expect that

```sql
CREATE mem_table as SELECT * FROM s3_parquet_table
-- run a query against mem_table
```

And then in another thread run something like
```sql
CREATE or replace mem_table as SELECT * FROM s3_parquet_table
```

The first query against `mem_table` will use the original data. When the second query completes it will entirely replace the `mem_table` with a new table provider instance and all queries planned after that point will use the new data. Any queries that are already running will continue to use the old data

A query will not see partial results / partial updates

However, you will have two copies of your data in memory until the first query completes

**Comment by a-agmon** [comment]
That sounds good to me. Thanks @alamb
