### ISSUE TITLE
Regression: write_parquet no longer supports compression options

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#7433]
### Describe the bug

After upgrading the DataFusion Python bindings to version 30, I saw some test failures for writing compressed Parquet files.

https://github.com/apache/arrow-datafusion-python/pull/464#issuecomment-1695692034

It looks like this feature was removed from DataFusion in [this commit](https://github.com/apache/arrow-datafusion/pull/7283). Note the comment `// TODO implement options`.

### To Reproduce

Try writing a parquet file and specify a compression level in the writer properties:

```rust
        let writer_properties = WriterProperties::builder()
            .set_compression(compression_type)
            .build();
```

### Expected behavior

The option should not be ignored.

**Comment by devinjdangelo** [comment]
I am working on adding support back in for these options in #7390 and #7435. The API will still be slightly different after these PRs though, requiring an additional argument.  Apologies for not flagging these breaking changes more clearly prior to the 30.0.0 release!

I discussed a possible workaround in the meantime in #7423 to use `SessionContext::write_parquet` which still uses the previous write implementation.
