### ISSUE TITLE
Broken behavior: `write_{format}` methods crate wrong csv files in local FS

### ISSUE THREAD

**Issue by DDtKey** [apache/arrow-datafusion#7436]
### Describe the bug

Methods `write_csv`, `write_parquet`, `write_json` and etc have been broken after switching to `object-store`.

They produce files with wrong extension with additional suffix, for example: `filename_4.csv#1`

The name seems to change [here](https://github.com/apache/arrow-rs/blob/cb793a5d54e155b121bc5c33534a37bf94651c84/object_store/src/local.rs#L658) and is not controlled directly by datafusion. 
I think this is more an issue of `object_store` for local file-system implementation, but the behavior have been broken for datafusion after switching so I raised the issue.
It would be nice to cover with tests.

### To Reproduce

```rs
    let ctx = SessionContext::new();
    // register tables
    let data_frame = ctx.sql("...").await?; // any valid SELECT

    data_frame.write_csv().await?;
```

### Expected behavior

Filenames should be with correct extension, without suffix of `#1`. 

`write_{format}` methods used to create file per thread (currently it's controlled by `per_thread_output: true`) with correct names and an index: `{filename}_{index}.{ext}`.

**Comment by devinjdangelo** [comment]
Which version of DataFusion are you using? I was not able to replicate this behavior using the current `main` branch or using v30.0.0. I

If you are using DataFusion version prior to 30.0.0, try that and see if it is resolved.

**Comment by DDtKey** [comment]
I encountered it exactly against '30.0.0' after updating from '28.0.0'. 
Let me provide some reproducible example

**Comment by DDtKey** [comment]
Sorry, my bad. Seems it works as expected

Looks like it happens in case of:
- error in one of threads which interrupts the execution of others (when files weren't fully written to disk)
- stopping of the runtime

I.e when rename call by `object_store` wasn't completed (https://github.com/apache/arrow-rs/blob/cb793a5d54e155b121bc5c33534a37bf94651c84/object_store/src/local.rs#L8111)

**Comment by devinjdangelo** [comment]
I think there may still be an issue here with the behavior you are seeing. When one thread encounters an error, no files should be written to disk, so we may want to add some logic to clean up the staged local files (unclear to me if that logic should be in the ObjectStore crate or DF at a glance).

**Comment by DDtKey** [comment]
That's definitely right point to avoid staged files.
I think `ObjectStore` should create staged files as a temporary files (probably just hidden ones) with `Drop` logic to delete them in case they weren't completed. 

I don't think DF should care of the way `object_store` handles the staging. If a file write/upload wasn't completed - intermediate files should be cleaned up.  Probably this may be configurable behavior 

WDYT? 

cc @tustvold @alamb

**Comment by tustvold** [comment]
Yes ideally we would stage the files in such a way that they get automatically cleaned up if the operation aborts. On Unix platforms this is fairly straightforward as there is the unlink command, it gets a bit mess on Windows though... I can add it to my list

**Comment by DDtKey** [comment]
Yeah, that's true

Perhaps a wrapper with `Drop` (with remove file call) is an option? as a fallback, it can of course fail and is not guaranteed, but at least it covers typical flows.

**Comment by alamb** [comment]
Would it be good to file a ticket in arrow-rs / obect-store for this behavior (even if it is non trivial to implement)?

**Comment by tustvold** [comment]
I created https://github.com/apache/arrow-rs/issues/4778 to track although I'm not sure how actually sure how to implement it, as Rust futures don't have an async Drop facility...
