### ISSUE TITLE
Allow Setting Column Specific Parquet Write Options via SQL StatementOptions

### ISSUE THREAD

**Issue by devinjdangelo** [apache/arrow-datafusion#7442]
### Is your feature request related to a problem or challenge?

Currently StatementOptions only enables setting parquet writer options for all columns at once (the default value). In many cases, we would want to set column level encodings or other settings based on the data type and properties of that specific column.

### Describe the solution you'd like

Implement a syntax to allow specifying column level parquet settings. A possible syntax for this would be:

```sql
COPY my_table
TO ./path
(format parquet,
encoding_default plain,
encoding '(colA RLE, nested.col.path.colB dictionary, ...)',
)
```

### Describe alternatives you've considered

DuckDB supports a different syntax than described above for setting field_id for each column. See https://duckdb.org/docs/sql/statements/copy.html

**Comment by parkma99** [comment]
https://github.com/apache/arrow-datafusion/blob/85ec31433615735a05d332f87cd0bdfc11aac663/datafusion/core/src/physical_planner.rs#L555-L598

May be we can get `output_schema` by using table origin schema and `statement_options`!
