### ISSUE TITLE
Mismatch in query results in the local machine

### ISSUE THREAD

**Issue by berkaysynnada** [apache/arrow-datafusion#7458]
When I run the sqllogictests on my computer, all query results including a NaN value give an error in scalar.slt file. Some examples:
```
External error: query result mismatch:
[SQL] select round(ln(a), 5), round(ln(b), 5), round(ln(c), 5) from signed_integers;
[Diff] (-expected|+actual)
-   -NaN 4.60517 -NaN
-   -NaN 9.21034 -NaN
-   0.69315 -NaN 4.81218
-   1.38629 NULL NULL
+   0.69315 NaN 4.81218
+   1.38629 NULL NULL
+   NaN 4.60517 NaN
+   NaN 9.21034 NaN
at test_files/scalar.slt:543
```

```
External error: query result mismatch:
[SQL] select log(a, 64) a, log(b), log(10, b) from signed_integers;
[Diff] (-expected|+actual)
-   -NaN 2 2
-   -NaN 4 4
    3 NULL NULL
-   6 -NaN -NaN
+   6 NaN NaN
+   NaN 2 2
+   NaN 4 4
at test_files/scalar.slt:595
```

Rows with NaN values are somehow listed towards the end of the table. So the tests don't pass in my local but in CI I don't get an error. Do you have any opinion about this problem?

**Comment by berkaysynnada** [comment]
Expected -NaN results in the query outputs become NaN in my local tests. What could be the reason for this? As far as I know, there is no -NaN in IEEE 754.

**Comment by jonahgao** [comment]
I encountered the same error on my ARM MacBook.
```
Running "scalar.slt"
External error: query result mismatch:
[SQL] select round(ln(a), 5), round(ln(b), 5), round(ln(c), 5) from signed_integers;
[Diff] (-expected|+actual)
-   -NaN 4.60517 -NaN
-   -NaN 9.21034 -NaN
-   0.69315 -NaN 4.81218
-   1.38629 NULL NULL
+   0.69315 NaN 4.81218
+   1.38629 NULL NULL
+   NaN 4.60517 NaN
+   NaN 9.21034 NaN
at test_files/scalar.slt:543

Error: Execution("1 failures")
error: test failed, to rerun pass `-p datafusion-sqllogictest --test sqllogictests`
```

**Comment by jayzhan211** [comment]
> I encountered the same error on my ARM MacBook.
> 
> ```
> Running "scalar.slt"
> External error: query result mismatch:
> [SQL] select round(ln(a), 5), round(ln(b), 5), round(ln(c), 5) from signed_integers;
> [Diff] (-expected|+actual)
> -   -NaN 4.60517 -NaN
> -   -NaN 9.21034 -NaN
> -   0.69315 -NaN 4.81218
> -   1.38629 NULL NULL
> +   0.69315 NaN 4.81218
> +   1.38629 NULL NULL
> +   NaN 4.60517 NaN
> +   NaN 9.21034 NaN
> at test_files/scalar.slt:543
> 
> Error: Execution("1 failures")
> error: test failed, to rerun pass `-p datafusion-sqllogictest --test sqllogictests`
> ```

Same.

**Comment by jonahgao** [comment]
> Expected -NaN results in the query outputs become NaN in my local tests. What could be the reason for this? As far as I know, there is no -NaN in IEEE 754.

I also think so. 

We can accept `+NAN` and `-NAN` as inputs just like PostgreSQL does. However, when outputting, it should no longer differentiate them because `NAN` represents an exception and the sign is no longer meaningful.
```
postgres=# select '+NAN'::float,'+NAN'::float;
 float8 | float8
--------+--------
    NaN |    NaN
(1 row)
```
