### ISSUE TITLE
Queries with date filters in the format 'yyyymmdd' give an error

### ISSUE THREAD

**Issue by osawyerr** [apache/arrow-datafusion#7465]
### Describe the bug

Hi there. When running queries with date filters that are in the format ```'yyyymmdd'``` , DataFusion throws an error. This is valid Postgres syntax. However dates in the format ```'yyyy-mm-dd'``` succeed. Both are valid postgres syntax. 

For both queries below, both are valid postgres syntax however:

```sql
--this query fails
select * from orders where o_orderdate = '19961006'

--but this succeeds
select * from orders where o_orderdate = '1996-10-06'
```

### To Reproduce

For a date column run a query with the date in string format ``'yyyymmdd'`` as shown below
```sql
select * from orders where o_orderdate = '19961006'
```

Error thrown is 
```
Arrow error: Cast error: Cannot cast string '19961006' to value of Date32 type
```

### Expected behavior

This should return the correct result and not fail

**Comment by tustvold** [comment]
Without delimiters how can a parser distinguish between dd-mm-yyyy or yyy-mm-dd? I'm very surprised postgres supports this and would be somewhat inclined not to copy this...

**Comment by osawyerr** [comment]
> Is there some particular use case for why you want this functionality?

Not specifically. I was querying a date column and realised it didn't work the same as postgres did. I assumed DataFusion was intended to support postgres-esque queries thats why I raised this as an issue.

**Comment by jackwener** [comment]
> Without delimiters how can a parser distinguish between dd-mm-yyyy or yyyy-mm-dd?

When there isn't delimiters, '20200101' will be treated as format `yyyymmdd`.

Same above, '200101' will be treated as format `yymmdd`.

Both `MySQL` and `PG` support it. Just in my opinion, it quite is a common usage.

**Comment by alamb** [comment]
Another option here might be to implement the two argument for of [`to_timestamp`](https://www.postgresql.org/docs/current/functions-formatting.html) / `to_date` / `to_time` where the second argument is a format string. I think this is tracked with https://github.com/apache/arrow-datafusion/issues/5398

**Comment by Tangruilin** [comment]
@alamb . Maybe I can try to fix it.

**Comment by alamb** [comment]
Thank you @Tangruilin

**Comment by tustvold** [comment]
It is actually https://docs.rs/arrow-cast/47.0.0/src/arrow_cast/parse.rs.html#571 that would need modification. It should be a relatively straightforward case of adding an additional match case

**Comment by Tangruilin** [comment]
@alamb Maybe you can assign this issue to me.

**Comment by Tangruilin** [comment]
Otherwise I can't find this issue well

> @alamb Maybe you can assign this issue to me.

**Comment by jackwener** [comment]
I have assigned this issue to you, thanks @Tangruilin

**Comment by Tangruilin** [comment]
I have already fix this in arrow，this issue can be closed
