### ISSUE TITLE
Potential Interval vs Duration Operations During Constraint Propagation

### ISSUE THREAD

**Issue by berkaysynnada** [apache/arrow-datafusion#7474]
### Is your feature request related to a problem or challenge?

After changing the resulting datatype of **timestamp - timestamp** operations from **time interval** to **duration**, we may encounter a scenario like this in the constraint propagation algorithm:

**Parent Node**: Timestamp
**Left Node**: Timestamp - **Operator**: Plus - **Right Node**: Interval

In this case, when we propagate to the right child, we subtract the updated value of the left child from the parent and then intersect it with the right child. During this intersection operation, one of the interval types is a time interval, and the other one is a duration, causing problems in the interval library. Similar issues may arise in different placements like this.

We want to provide this support in order not to deprive users of using values such as `1 month` in filters.

### Describe the solution you'd like

In the `propagate_arithmetic` function (also in `propagate_comparison`), if there is a time interval child, and If it contains a non-zero month or day field, we can return it as it is because we can't accurately convert it to a duration type without a valid timestamp reference (this check can be performed in one of the outer scopes). Otherwise, we simply convert the time interval type to a duration type, and after the propagation, we convert the duration back to the time interval type again.

**Comment by tustvold** [comment]
I'm afraid I am not familiar with how the range analysis framework is implemented, so I am quite possibly missing something, but I'm not really sure how intervals can reliably be used in range analysis.

In particular the basic identities below do **not** hold for intervals

```
a < b <=> a - b < 0
a + b = c <=> a = c - b
```

The only circumstances where these hold is for intervals that are durations, i.e. that are entirely encoded as a number of seconds or nanoseconds. If they contain a non-zero number of days, months or years, etc... they are no longer meaningful outside the context of a particular timestamp.

That being said if the range analysis framework is only interested in bounding computation, we could potentially just use the maximum values for each of the constituent parts, so 25 hours for a day, 31 days for a month, etc... :thinking:

**Comment by berkaysynnada** [comment]
> I'm afraid I am not familiar with how the range analysis framework is implemented, so I am quite possibly missing something, but I'm not really sure how intervals can reliably be used in range analysis.
> 
> In particular the basic identities below do **not** hold for intervals
> 
> ```
> a < b <=> a - b < 0
> a + b = c <=> a = c - b
> ```
> 
> The only circumstances where these hold is for intervals that are durations, i.e. that are entirely encoded as a number of seconds or nanoseconds. If they contain a non-zero number of days, months or years, etc... they are no longer meaningful outside the context of a particular timestamp.
> 
> That being said if the range analysis framework is only interested in bounding computation, we could potentially just use the maximum values for each of the constituent parts, so 25 hours for a day, 31 days for a month, etc... 🤔

Thanks for thinking about it. We also do not prefer to do range analysis on intervals, that's why I suggested converting to duration where conversions are possible. However, there may be joins having a filter predicate of "timestamp_column - 1 month". Currently, pruning of tables with that kind of filter does not work safely, and we want to fix this where possible.

**Comment by tustvold** [comment]
What do you think of using the maximum/minimum possible values when converting, might that work?

**Comment by berkaysynnada** [comment]
> What do you think of using the maximum/minimum possible values when converting, might that work?

I believe [this PR](https://github.com/apache/arrow-datafusion/pull/7475#pullrequestreview-1610718513) properly handles the cases where the interval value is a scalar, not an array (because we don't shrink). Your proposed convention can be useful when we want to handle interval-type columns, but I prefer to do it on the following PRs.

**Comment by ozankabak** [comment]
> What do you think of using the maximum/minimum possible values when converting, might that work?

This is possible theoretically and will produce better results than refusing to propagate. The latter (and current) approach is safe, but may miss some pruning opportunities.

I will keep this in mind and probably scope this work and get it implemented in the upcoming months.
