### ISSUE TITLE
Deprecate `ScalarValue::get_datatype()`

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#7506]
### Is your feature request related to a problem or challenge?

We introduced `ScalarValue::data_type()` in https://github.com/apache/arrow-datafusion/pull/7492 to be consistent with other APIs for getting `DataType`. 

However the previous `ScalarValue::get_datatype()`

https://github.com/apache/arrow-datafusion/pull/7492#event-10314345235

### Describe the solution you'd like

1. Mark `ScalarValue::get_datatype()` deprecated (like this): 

https://github.com/apache/arrow-datafusion/blob/93c209f1b5d0a17b2aa5c6743cbd3cb189a406c8/datafusion/expr/src/table_source.rs#L81-L87

2. Update the uses in the datafusion codebase to pass clippy (update to use `ScalarValue::data_type()`)

**Comment by Weijun-H** [comment]
I am glad to handle this later.
