### ISSUE TITLE
Move `FileCompressionType` out of `common` and into `core`

### ISSUE THREAD

**Issue by universalmind303** [apache/arrow-datafusion#7516]
### Is your feature request related to a problem or challenge?

`FileCompressionType` appears to be the only item in `common` that uses several heavy dependencies in the `common` crate such as `tokio`. As result causes it to be a dependency of all crates using `common`, such as `expr`. Other than for `FileCompressionType` there is no usage of async in any crate except `core` _(tests excluded)_

By moving `FileCompressionType`, or the associated `convert_X` functions to `core`, we'd remove several heavy dependencies from all crates except core

### Describe the solution you'd like

A quick look over the codebase, it seems that `FileCompressionType` is only used in `core`. So it seems natural that it could easily be moved in to `core`. 

### Describe alternatives you've considered

- Make all async dependencies optional & control them via feature flags. 
- Keep FileCompressionType in `common`, but move the `convert_X` functions in to `core`.

**Comment by alamb** [comment]
I agree -- thank you @universalmind303  -- marking this as a good first issue as it is primarily a code motion exercise and does not require deep datafusion internals knowledge

**Comment by haohuaijin** [comment]
I want to work on this issue.
