### ISSUE TITLE
[docs] Update or Remove Quarterly Roadmap Documentation

### ISSUE THREAD

**Issue by graydenshand** [apache/arrow-datafusion#7535]
The [Quarterly Roadmap](https://arrow.apache.org/datafusion/contributor-guide/quarterly_roadmap.html) is intended to  "give the DataFusion community visibility into the priorities of the projects contributors". However, the most recent entry is for Q2 2022.

This documentation should either be updated to reflect current priorities (e.g. for Q4 2023), or removed.

Happy to help out with this if I can!

**Comment by alamb** [comment]
Thank you @graydenshand  -- that would be super helpful to update this documentation 

The major items I know of that are currently ongoing are:
1. @devinjdangelo  is cranking along with improving write / output capabulity #7079 
2. @jayzhan211 and @izveigor are leading the charge for adding support for array

There is also writing of a paper #6782 

In the past I have found a good way to get a community roadmap is to create a skeleton PR with some ideas and then we'll solict help from others to add what they are thinking of / planning on working on

**Comment by yjshen** [comment]
I have been occupied with preparing an internal product for launch recently and almost finished. My next goal is to develop a stand-alone AP engine service using DataFusion and FlightSQL. (And use it internally as an alternative to Spark for small OLAP queries for both cost and performance efficiency). I have seen some impressive implementations inside InfluxDB and Greptime, and I would like to know if this project (`datafusion-jdbc` maybe?) has a broader interest.

**Comment by alamb** [comment]
I think an example / reference implementation of FlightSQL in rust would be helpful for many reasons
