### ISSUE TITLE
`ptree` crate is old and uses old outdated dependencies

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#7550]
### Describe the bug

`ptree` was added as a dependency in https://github.com/apache/arrow-datafusion/pull/7192

However the most recent version of ptree is 2 years old https://crates.io/crates/ptree/versions

And it pulls in older versions of serde and various other dependencies.

### To Reproduce

Look at datafusion-cli/Cargo.lock

### Expected behavior

I would like to avoid all the old dependencies -- so either by updating ptree somehow or maybe simply by avoiding the dependency

**Comment by alamb** [comment]
@avantgardnerio  any thoughts here?

**Comment by avantgardnerio** [comment]
I only included it as a dev-dependency for ease of reading/asserting tree balancing. Let me see if I can find another equivalent crate, or we can do more ugly asserts.

**Comment by avantgardnerio** [comment]
how's this:? https://crates.io/crates/termtree

**Comment by avantgardnerio** [comment]
I checked - it has no dependencies. I'll sub it in shortly...

**Comment by alamb** [comment]
> I checked - it has no dependencies

❤️
