### ISSUE TITLE
Optimize FilterExec::statistics / don't ignore errors

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#7553]
### Is your feature request related to a problem or challenge?

This came up from looking at the backgrace in https://github.com/apache/arrow-datafusion/issues/7522  where we saw a significant amount of planning time going to creating `DataFusionError` which were then thrown away. 

I tracked this down to creating the error (which is ignored) here:

https://github.com/apache/arrow-datafusion/blob/c47ae0d13dbc9474897609f3dea4f80a93cf4de0/datafusion/physical-plan/src/filter.rs#L206-L209

### Describe the solution you'd like

I would like less time being spent creating erorrs that are thrown away. I can see two potential ways to do this:

1. Stop ignoring the error and instead fix whatever the underlying issue is
2. Cache the calculation of the statistics so it doesn't get called multiple times

Both might be appropriate

### Additional context

cc @berkaysynnada  as I believe this came in #6982

I don't think this is a critical fix, but I wanted to file it given I had tracked it down

**Comment by liukun4515** [comment]
I also find this thing when I do this pr https://github.com/apache/arrow-datafusion/pull/7428
The statistics can't be passed or pass an error result when meet error in the process.

**Comment by liukun4515** [comment]
> 1. Stop ignoring the error and instead fix whatever the underlying issue is

I think this is the root solution.

**Comment by berkaysynnada** [comment]
I am working on this issue and will send the PR solving this issue once https://github.com/apache/arrow-datafusion/pull/7544 is merged.
