### ISSUE TITLE
SQL Filter casting problem

### ISSUE THREAD

**Issue by metesynnada** [apache/arrow-datafusion#7601]
### Describe the bug

I get `Error: ArrowError(InvalidArgumentError("Invalid comparison operation: UInt64 > Int64"))` when I call
```sql
SELECT n_regionkey FROM nation WHERE n_nationkey > 10;
```

### To Reproduce

```rust
#[cfg(test)]
mod tmp2 {
    use crate::common::Result;
    use crate::physical_plan::{collect, execute_stream, ExecutionPlan};
    use crate::prelude::SessionContext;
    use arrow::util::pretty::print_batches;
    use datafusion_execution::config::SessionConfig;
    use futures::StreamExt;
    use std::sync::Arc;

    fn print_plan(plan: &Arc<dyn ExecutionPlan>) -> () {
        let formatted = crate::physical_plan::displayable(plan.as_ref())
            .indent(true)
            .to_string();
        let actual: Vec<&str> = formatted.trim().lines().collect();
        println!("{:#?}", actual);
    }
    #[tokio::test(flavor = "multi_thread", worker_threads = 8)]
    async fn test_unbounded_hash_selection2() -> Result<()> {
        let config = SessionConfig::new()
            .with_target_partitions(1)
            .with_repartition_joins(false)
            .with_batch_size(10);
        let ctx = SessionContext::with_config(config);
        let abs = "YOUR_WORK_SPACE/datafusion/core/tests/tpch-csv/";
        ctx.sql(&format!(
            "CREATE EXTERNAL TABLE nation (
                    n_nationkey BIGINT,
                    n_name VARCHAR,
                    n_regionkey BIGINT,
                    n_comment VARCHAR,
                    n_rev VARCHAR,
            ) STORED AS CSV
            WITH ORDER (n_nationkey ASC)
            LOCATION '{abs}nation.csv';"
        ))
            .await?;

        let sql = "SELECT n_regionkey FROM nation WHERE n_nationkey > 10;";

        let msg = format!("Creating logical plan for '{sql}'");
        let dataframe = ctx.sql(sql).await.expect(&msg);
        let physical_plan = dataframe.create_physical_plan().await?;
        print_plan(&physical_plan);
        let mut stream = execute_stream(physical_plan, ctx.task_ctx())?;
        while let Some(batch) = stream.next().await {
            print_batches(&[batch?])?;
        }
        Ok(())
    }
}

```

### Expected behavior

Just working.

**Comment by alamb** [comment]
I would expect that the type coercion logic should handle this 

https://github.com/apache/arrow-datafusion/blob/bcdda391ae6336f75db8cafc8a91b199e5abbdf9/datafusion/expr/src/type_coercion/binary.rs#L66-L78

**Comment by metesynnada** [comment]
I'm surprised to see the error. If no one else addresses it, I'll fix it in a few days.

**Comment by Tangruilin** [comment]
@metesynnada I see that the issue is not assigned to you. Do you have time to fix it. If not, I'm interested in it.

**Comment by metesynnada** [comment]
You can work on this, thanks for the contribution 😀

**Comment by Tangruilin** [comment]
> > You can work on this, thanks for the contribution 😀
> 
> @alamb /assigned me

Thanks

**Comment by Tangruilin** [comment]
@metesynnada Hey! I can not repeat this bug. I copy the code and run on my machine, but it get `Error: ArrowError(CsvError("incorrect number of fields for line 1, expected 5 got 4"))` for the n_rev is not in nation.csv.

If i delete it, it will get `Error: ArrowError(ParseError("Error while parsing value n_nationkey for column 0 at line 0"))`

I do not know if it should get this @alamb ,maybe you can ensure?
but i can not get error `Error: ArrowError(InvalidArgumentError("Invalid comparison operation: UInt64 > Int64"))`

The PR is repeat of error

**Comment by Tangruilin** [comment]
> @metesynnada Hey! I can not repeat this bug. I copy the code and run on my machine, but it get `Error: ArrowError(CsvError("incorrect number of fields for line 1, expected 5 got 4"))` for the n_rev is not in nation.csv.
> 
> If i delete it, it will get `Error: ArrowError(ParseError("Error while parsing value n_nationkey for column 0 at line 0"))`
> 
> I do not know if it should get this @alamb ,maybe you can ensure? but i can not get error `Error: ArrowError(InvalidArgumentError("Invalid comparison operation: UInt64 > Int64"))`
> 
> The PR is repeat of error

The PR can get error `Error: ArrowError(ParseError("Error while parsing value n_nationkey for column 0 at line 0"))` but not `Error: ArrowError(InvalidArgumentError("Invalid comparison operation: UInt64 > Int64"))`

**Comment by alamb** [comment]
> I do not know if it should get this @alamb ,maybe you can ensure?

that doesn't sound right to me -- it sounds like an error parsing the CSV file perhaps

**Comment by metesynnada** [comment]
I'm unable to reproduce the issue either. This code appears to be functioning as expected. Consequently, I'm closing the issue for now, as I'm uncertain about the nature of the problem I encountered earlier. It's possible that the issue was resolved by other means that I'm not aware of at this time.

```rust
#[cfg(test)]
mod tmp2 {
    use crate::common::Result;
    use crate::physical_plan::{collect, execute_stream, ExecutionPlan};
    use crate::prelude::SessionContext;
    use arrow::util::pretty::print_batches;
    use datafusion_execution::config::SessionConfig;
    use futures::StreamExt;
    use std::sync::Arc;

    fn print_plan(plan: &Arc<dyn ExecutionPlan>) -> () {
        let formatted = crate::physical_plan::displayable(plan.as_ref())
            .indent(true)
            .to_string();
        let actual: Vec<&str> = formatted.trim().lines().collect();
        println!("{:#?}", actual);
    }
    #[tokio::test(flavor = "multi_thread", worker_threads = 8)]
    async fn test_unbounded_hash_selection2() -> Result<()> {
        let config = SessionConfig::new()
            .with_target_partitions(1)
            .with_repartition_joins(false)
            .with_batch_size(10);
        let ctx = SessionContext::new_with_config(config);
        let abs = "/Users/metehanyildirim/Documents/Synnada/Coding/arrow-datafusion-synnada/datafusion/core/tests/tpch-csv/";
        ctx.sql(&format!(
            "CREATE EXTERNAL TABLE nation (
                    n_nationkey BIGINT,
                    n_name VARCHAR,
                    n_regionkey BIGINT,
                    n_comment VARCHAR,
            ) STORED AS CSV
            WITH HEADER ROW
            WITH ORDER (n_nationkey ASC)
            LOCATION '{abs}nation.csv';"
        ))
            .await?;

        let sql = "SELECT n_regionkey FROM nation WHERE n_nationkey < 3;";

        let msg = format!("Creating logical plan for '{sql}'");
        let dataframe = ctx.sql(sql).await.expect(&msg);
        let physical_plan = dataframe.create_physical_plan().await?;
        print_plan(&physical_plan);
        let mut stream = execute_stream(physical_plan, ctx.task_ctx())?;
        while let Some(batch) = stream.next().await {
            print_batches(&[batch?])?;
        }
        Ok(())
    }
}
```
As @alamb pointed out, the parsing error you encountered was due to a previous incorrect definition of the table in the code.
