### ISSUE TITLE
Make `parquet` support  optional 

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#7653]
### Is your feature request related to a problem or challenge?

DataFusion aspires to be a modular query engine, and not all users need support for parquet

The [parquet](https://docs.rs/parquet/latest/parquet/index.html) crate has a non trivial number of dependencies (some of which prevent compiling DataFusion to WASM -- see https://github.com/apache/arrow-datafusion/issues/7652)

Also there have been reports like https://github.com/apache/arrow-datafusion/issues/2042 where some of the native dependencies like `zstd` cause build issues

### Describe the solution you'd like

I would like to make `parquet` support optional, the same way `avro` support is 

Avro is marked as `optional`: https://github.com/apache/arrow-datafusion/blob/5f38135d5d21160d6b1ef7213578dd5eddfa4f95/datafusion/core/Cargo.toml#L53

It would be great to mark `parquet` as optional too
https://github.com/apache/arrow-datafusion/blob/5f38135d5d21160d6b1ef7213578dd5eddfa4f95/datafusion/core/Cargo.toml#L82

In order to make this work, we would likely need to encapsulate the parquet code in a more modular fashion (rather than sprinkling `#[cfg(feature = parquet)]` all over the code

**Comment by alamb** [comment]
The same thing probably applies to CSV and JSON

**Comment by alamb** [comment]
If someone wanted a fun software engineering challenge that is well specified, I think this one is pretty reasonable

It isn't a great "new to rust programming" project, but it is a good "new to datafusion" project for someone already familiar with rust

**Comment by universalmind303** [comment]
arrow-rs dependency may make this a bit tricky as they don't have a parquet feature flag. 

see https://github.com/apache/arrow-rs/issues/4764

**Comment by tustvold** [comment]
> arrow-rs dependency may make this a bit tricky as they don't have a parquet feature flag.

Parquet depends on arrow-rs not the other way round?

**Comment by universalmind303** [comment]
> > arrow-rs dependency may make this a bit tricky as they don't have a parquet feature flag.
> 
> Parquet depends on arrow-rs not the other way round?

sorry I misunderstood the issue linked. Please disregard.

**Comment by fudini** [comment]
Maybe this issue needs reopening because it no longer compiles without default features with following error:
```bash
error[E0412]: cannot find type `ParquetSink` in this scope
   --> datafusion/proto/src/physical_plan/mod.rs:962:32
    |
962 |                 let data_sink: ParquetSink = sink
    |                                ^^^^^^^^^^^ not found in this scope
    |
help: consider importing one of these items
    |
18  + use crate::protobuf::ParquetSink;
```

**Comment by alamb** [comment]
> Maybe this issue needs reopening because it no longer compiles without default features with following error:

@fudini  -- thanks for the report. Can you provide a command to reproduce this error?

**Comment by fudini** [comment]
> > Maybe this issue needs reopening because it no longer compiles without default features with following error:
> 
> @fudini -- thanks for the report. Can you provide a command to reproduce this error?

Sure, it's:
```cargo build --no-default-features```

**Comment by alamb** [comment]
> argo build --no-default-features

Thank you -- filed https://github.com/apache/arrow-datafusion/issues/8844
