### ISSUE TITLE
Supported expression operators should be documented

### ISSUE THREAD

**Issue by ongchi** [apache/arrow-datafusion#7681]
### Is your feature request related to a problem or challenge?

There are some flaws in documentation of the [Expression API](https://arrow.apache.org/datafusion/user-guid/expressions.html):
1. Several [operator overloads](https://github.com/apache/arrow-datafusion/blob/bcc2acd8d10204b32b64fa3b77372655eaee8f06/datafusion/expr/src/operator.rs#L267-L400) are implemented but not mentioned in the Expression API section.
2. Bitwise operation methods of `Expr` are not implemented as stated in the [documentation](https://arrow.apache.org/datafusion/user-guide/expressions.html#bitwise-expressions). For example, `bitwise_and(expr1, expr2)` can also be `expr1.bitwise_and(expr2)` according to the document, but `Expr::bitwise_and` is not implemented.
3. Bitwise XOR shoud be `^` in [Bitwise Operators](https://arrow.apache.org/datafusion/user-guide/expressions.html#bitwise-operators). It would be `#` in SQL but it does not work in rust. Additionally, I'm not sure if the [`fmt::Display` impl of `Operator::BitwiseXor`](https://github.com/apache/arrow-datafusion/blob/main/datafusion/expr/src/operator.rs#L256) is used elsewhere, but it returns "BIT_XOR".

### Describe the solution you'd like

1. Add a section on supported operators and rearranging sections (Boolean Expressions, Bitwise Expressions, Bitwise Operators) in the Expression API.
2. The functions are already implemented, and they just need to be wired up. We can either add bitwise operations methods (`bitwise_and`, `bitwise_or`, `bitwise_xor`, `bitwise_shift_right`, `bitwise_shift_left`) to `Expr`, and/or simply refer to its operator override functions and update the documentation accordingly.
3. Replacing `#` with `^` in the document. Maybe change "BIT_XOR" to "#" in the `Display` impl.

**Comment by alamb** [comment]
Thank you @ongchi  -- this ticket is very well written and I think could be easily implemented by someone, so marking as good first issue.
