### ISSUE TITLE
Error in the timestamp add interval test

### ISSUE THREAD

**Issue by berkaysynnada** [apache/arrow-datafusion#7696]
### Describe the bug

There is a test case named `timestamp_add_interval_months()` that adds 17 months to the current time. However, after 17 months, it tries to get 29/02/2025 but there is no such date and the test fails. I believe we should modify the test to avoid getting errors when we reach the end of some months.

### To Reproduce

Run the test` timestamp_add_interval_months()`

**Comment by alamb** [comment]
I believe this was fixed by @jayzhan211  in https://github.com/apache/arrow-datafusion/pull/7701
