### ISSUE TITLE
Confirm git tagging strategy for releases

### ISSUE THREAD

**Issue by thisisnic** [apache/arrow-datafusion#770]
Please could you confirm what convention you'll be using for tagging releases?

I am currently working on a ticket in the `apache/arrow` repo which involves updating the release script that generates lists of committers and contributors for the Apache Arrow website (https://issues.apache.org/jira/browse/ARROW-12701).  I'd like to make sure that contributions to the `arrow-datafusion` repository are recognised on the website and blog page.

I'd just like to check what git tags you are going to use for different releases?  I think the `apache/arrow` repo uses `apache-arrow-x.y.z` and `apache/arrow-rs` uses `x.y.z` where `x.y.z` is the release version number.  The script I have uses these tags to work out the numbers needed for the contributor list - I'll adapt it to take into account however you are managing this.

**Comment by alamb** [comment]
@thisisnic  -- I am not sure what our release plan for this would be. 

Would it work to use the same strategy here as `arrow-rs` -- namely tags with the version numbers (4.0.0 and 5.0.0, etc)? Note that we don't actually have those tags in the datafusion repo yet

**Comment by alamb** [comment]
@andygrove  / @Dandandan  / @jorgecarleitao  do you have any thoughts in this area?

**Comment by thisisnic** [comment]
> @thisisnic -- I am not sure what our release plan for this would be.
> 
> Would it work to use the same strategy here as `arrow-rs` -- namely tags with the version numbers (4.0.0 and 5.0.0, etc)? Note that we don't actually have those tags in the datafusion repo yet

@alamb That would definitely be the simplest strategy for me, in terms of integrating with the current script I'm using, but if you'd prefer a different approach, I am happy to adapt to that.

**Comment by alamb** [comment]
Unless I hear differently I will plan to use the same strategy in
arrow-datafusion

Note it isn't clear to me when we will have a 5.0.0 release -- I have
started a conversation here:
https://github.com/apache/arrow-datafusion/issues/771

**Comment by alamb** [comment]
I believe this is the strategy that @houqp  is implementing in https://github.com/apache/arrow-datafusion/issues/771 so closing this ticket out
