### ISSUE TITLE
Support parameter ($1) type inference for BETWEEN predicates

### ISSUE THREAD

**Issue by andrelmartins** [apache/arrow-datafusion#7702]
### Is your feature request related to a problem or challenge?

We are trying to run a query like this:

```sql
SELECT ... WHERE col BETWEEN $1 AND $2
```
However the type inference logic in

[arrow-datafusion/datafusion/sql/src/expr/mod.rs](https://github.com/apache/arrow-datafusion/blob/85f3578f5fb47d28a8bc3a7b9be0284b3ced0fcd/datafusion/sql/src/expr/mod.rs#L737)

does not handle this type of expressions.

### Describe the solution you'd like

I would like the type inference logic to handle BETWEEN predicates.

**Comment by alamb** [comment]
Thank you @andrelmartins  -- this would be a great addition
