### ISSUE TITLE
[Docs] How to get data type of a logical expression

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#7725]
### Is your feature request related to a problem or challenge?

It is not always apparent to new users how to get the data type for a logical expression.

### Describe the solution you'd like

Add some docs explaining ExprSchemable.

Quick example:

```rust
use arrow_schema::DataType;
use datafusion::common::DFField;
use datafusion::common::DFSchema;
use datafusion::logical_expr::col;
use datafusion::logical_expr::ExprSchemable;
use std::collections::HashMap;

fn main() {
    let expr = col("foo");
    let schema = DFSchema::new_with_metadata(
        vec![DFField::new_unqualified("foo", DataType::Utf8, true)],
        HashMap::new(),
    )
    .unwrap();
    print!("type = {}", expr.get_type(&schema).unwrap());
}
```

**Comment by r3stl355** [comment]
If this wasn't done yet I'd like to make an attempt. (I don't see it in `Expr` or `ExprSchemable` docstrings)

**Comment by alamb** [comment]
Thank you @r3stl355  🙏 

Perhaps we could:
1. Add an example to [`Expr::get_type`](https://docs.rs/datafusion/latest/datafusion/logical_expr/enum.Expr.html#method.get_type),  perhaps showing an expression like `sqrt(a)` and then calling `get_type` to get the type for that expression.

Bonus points would be to
1. Add a similar example to https://github.com/apache/arrow-datafusion/blob/main/datafusion-examples/examples/expr_api.rs 
3. Add a paragraph in https://arrow.apache.org/datafusion/library-user-guide/working-with-exprs.html

**Comment by r3stl355** [comment]
Cool, I'll do all that
