### ISSUE TITLE
Update explain plan to show when topk operator is used

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#7750]
### Is your feature request related to a problem or challenge?

After https://github.com/apache/arrow-datafusion/pull/7721 a `SortExec` with a limit will use a special [`TopK` operator](https://github.com/apache/arrow-datafusion/blob/e95a24b5a260e0e2f603d52682d36cce192676f8/datafusion/physical-plan/src/topk/mod.rs#L40-L75)

However, I don't think it  is clear from the EXPLAIN plan that this will be used (you have to know that sort with a limit is specially optimized to not actually sort). 

Using DataFusion CLI  and the dataset described here: https://github.com/apache/arrow-datafusion/pull/7721#pullrequestreview-1658084301, the explain plan looks like 

```
❯ explain select trace_id from 'traces.parquet' order by time desc limit 10;
+---------------+-------------------------------------------------------------------------------------------------------------------+
| plan_type     | plan                                                                                                              |
+---------------+-------------------------------------------------------------------------------------------------------------------+
| logical_plan  | Projection: traces.parquet.trace_id                                                                               |
|               |   Limit: skip=0, fetch=10                                                                                         |
|               |     Sort: traces.parquet.time DESC NULLS FIRST, fetch=10                                                          |
|               |       Projection: traces.parquet.trace_id, traces.parquet.time                                                    |
|               |         TableScan: traces.parquet projection=[time, trace_id]                                                     |
| physical_plan | ProjectionExec: expr=[trace_id@0 as trace_id]                                                                     |
|               |   GlobalLimitExec: skip=0, fetch=10                                                                               |
|               |     SortExec: fetch=10, expr=[time@1 DESC]         <----- ****  this uses the TopK operator |                                                               
|               |       ProjectionExec: expr=[trace_id@1 as trace_id, time@0 as time]                                               |
|               |         ParquetExec: file_groups={1 group: [[traces.parquet]]}, projection=[time, trace_id] |
|               |                                                                                                                   |
+---------------+-------------------------------------------------------------------------------------------------------------------+
2 rows in set. Query took 0.004 seconds.
```

### Describe the solution you'd like

I would like to make it clearer in the explain plan that this new operator is used. Perhaps something like

```
SortExec: TopK(fetch=10), expr=[time@1 DESC]         <----- **** This is updated |                                                               
```

See comment in https://github.com/apache/arrow-datafusion/pull/7721/files#r1343969678 for exactly where this code that controls the output is

### Describe alternatives you've considered

We can leave the explain plans alone, but I think that is confusing

**Comment by alamb** [comment]
I think this is an excellent task for new users as the code is quite straightforward and most of this work will be to learn how to run the various tests and update them for the new explain plans.

**Comment by alamb** [comment]
Note there is already a partial version in https://github.com/apache/arrow-datafusion/pull/7751

With a good comment here: https://github.com/apache/arrow-datafusion/pull/7751#discussion_r1349536708

Maybe you can base your efforts on that PR

**Comment by MayurShirodkarOfficial** [comment]
hello !! can i try working on this issue?

**Comment by alamb** [comment]
> 
hello !! can i try working on this issue?


Absolutely -- I think we are just waiting on someone to make a PR that passes CI :)
