### ISSUE TITLE
Lower &mut SessionContext to &SessionContext in substrait consumer/producer

### ISSUE THREAD

**Issue by amartins23** [apache/arrow-datafusion#7836]
### Is your feature request related to a problem or challenge?

Currently functions to convert from substrait to DataFusion plans, or to produce a substrait plan from a DataFusion logical plan, require a mutable reference to SessionContext. However, none of the implementations seems to require that. Since state access in the session context does not require a mutable pointer, I don't see the need to take a mutable reference to the session context.

Allowing shared references to SessionContext to be used would simplify consuming code and should not be a breaking as you can pass an &mut reference to a function expecting a shared reference.

### Describe the solution you'd like

Change the various conversion functions in the datafusion-substrait crate to receive &SessionContext instead of &mut SessionContext.

**Comment by alamb** [comment]
Hi @amartins23 

It seems like the consumer functions such as 
https://docs.rs/datafusion-substrait/latest/datafusion_substrait/logical_plan/consumer/fn.from_substrait_plan.html
https://docs.rs/datafusion-substrait/latest/datafusion_substrait/physical_plan/consumer/fn.from_substrait_rel.html

Require mutable access, but the producers do not (they already take `&SessionContext`, not `&mut SessionContext`)
https://docs.rs/datafusion-substrait/latest/datafusion_substrait/logical_plan/producer/fn.to_substrait_plan.html

This I think this ticket would require:
1. Converting from &mut SessionContext` to &SessionContext`
2. Ideally add some doc comments / examples of how to do this conversion

This seems straightforward and a good first project so marking it as such

Note there may be some subtlety I don't understand that would make this not feasible.

**Comment by my-vegetable-has-exploded** [comment]
I'd like to have a try.

**Comment by my-vegetable-has-exploded** [comment]
> 2\. Ideally add some doc comments / examples of how to do this conversion

Sorry for the delay in completing this task.   Would an example like [this](https://medium.com/@omri-levy/one-query-plan-three-different-engines-e5dc74aeb52f) be OK?

**Comment by alamb** [comment]
> Sorry for the delay in completing this task. 

No worries -- thank you for doing so!

**Comment by alamb** [comment]
Fixed in ull/7965

**Comment by alamb** [comment]
Fixed in https://github.com/apache/arrow-datafusion/pull/7965
