### ISSUE TITLE
`HashJoinStream` memory tracking insufficient

### ISSUE THREAD

**Issue by crepererum** [apache/arrow-datafusion#7848]
### Describe the bug

Using a hash join may lead to OOM kills / very large memory consumption even when a memory limit is set.

### To Reproduce

No reproduction steps yet.

We have a flame graph from a prod environment though:

![flame](https://github.com/apache/arrow-datafusion/assets/1529400/913b7f27-4f00-45e5-9e22-f96187ae0254)

### Expected behavior

Memory manager report "out of memory", the query fails.

### Additional context

I think the code only tracks `HashJoinStream::visited_left_side` but `build_equal_condition_join_indices` is completely untracked.

**Comment by alamb** [comment]
cc @korowa  who I think did the initial work for Join memory tracking in case they have ideas.

**Comment by korowa** [comment]
Can't remember of anything "leaky" except for build-side data and visited build-side indices 🤔  -- I'll check it out and try to submit PR

**Comment by alamb** [comment]
@korowa  I think adding support for the working batch sounds like a good idea, as long as it doesn't get too complex.

**Comment by alamb** [comment]
@korowa  is there any update on this? If now, I may try and work on it this week

**Comment by korowa** [comment]
Unfortunately I've started only a day ago with first option (emitting batches from hash join) -- so, I hope during this week there will be at least draft for this. But, ofc, feel free to pick this issue!

**Comment by alamb** [comment]
Thanks @korowa  -- I'll let you know

**Comment by alamb** [comment]
Related ticket: https://github.com/apache/arrow-datafusion/issues/8130 which I believe is blocking this code.
