### ISSUE TITLE
Support `float`  arguments to  `to_timestamp` function

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#7868]
### Is your feature request related to a problem or challenge?

In https://github.com/apache/arrow-datafusion/pull/7844 we are (about to) change `to_timestamp` to be aligned with postgres by taking seconds instead of milliseconds. 

To fully align with postgres, we should also add support `double` (`Float64`) arguments as well

The postgres documentation for `to_timestamp` is [here](https://www.postgresql.org/docs/current/functions-datetime.html#FUNCTIONS-DATETIME-TABLE)

### Describe the solution you'd like

I would like the `to_timestamp` function to also support  Float64 point arguments:

For example, (not the `1.1` at the end of the timestamp)
```bash
willy=# select to_timestamp(1.1);
       to_timestamp       
--------------------------
 1970-01-01 08:00:01.1+08
```

### Additional context

Note the string / two argument version of `to_timestamp` is covered by https://github.com/apache/arrow-datafusion/issues/5398

**Comment by alamb** [comment]
Thanks @spaydar  -- note that we haven't merged https://github.com/apache/arrow-datafusion/pull/7844 yet, so you probably would need to start from that branch if you want to work on this prior to @comphead merges

**Comment by edmondop** [comment]
Is this still up for grab?

**Comment by spaydar** [comment]
I'm still working on this; it's been a bit more involved than I expected. Is this blocking other issues?

**Comment by comphead** [comment]
No blocking issues as of now, rather this is one of the missing pieces for timestamp
