### ISSUE TITLE
Make data type of FileScanConfig.table_partition_cols a vector of Field

### ISSUE THREAD

**Issue by NGA-TRAN** [apache/arrow-datafusion#7875]
### Is your feature request related to a problem or challenge?

Currently, the `table_partition_cols` of `FileScanConfig` is a vector of `(String, DataType)` to store only column name and data type https://github.com/apache/arrow-datafusion/blob/37d6bf08c948418fe6c72d072d988c2875d81e02/datafusion/core/src/datasource/physical_plan/file_scan_config.rs#L104

In our IOx case, a column has more meaning than just `name` and `data type` and need the [Field](https://github.com/apache/arrow-rs/blob/7e134f4d277c0b62c27529fc15a4739de3ad0afd/arrow-schema/src/field.rs#L37C5-L37C5) data type to convey that. We hit a bug of missing column schema information because of missing other information a Field provides

### Describe the solution you'd like

Replace   `pub table_partition_cols: Vec<(String, DataType)>,`
with         `pub table_partition_cols: Vec<Field>,`

**Comment by NGA-TRAN** [comment]
@alamb 
If there is no objection, I will start working on this

**Comment by crepererum** [comment]
That sounds reasonable to me.

**Comment by alamb** [comment]
It is reasonable in theory, however, this will likely be a non trivial API change, so we should take significant care needs to be taken on the API to make migration as easy as possible (for example, a function that takes the old data type and makes a new one), or maybe a `with_partition_columns` type function

**Comment by NGA-TRAN** [comment]
> It is reasonable in theory, however, this will likely be a non trivial API change, so we should take significant care needs to be taken on the API to make migration as easy as possible (for example, a function that takes the old data type and makes a new one), or maybe a with_partition_columns type function

Agreed. I will keep the current API and add one more to make sure it still works for current folks

**Comment by NGA-TRAN** [comment]
I start working on this today
