### ISSUE TITLE
Maybe a misuse of `plan_err`

### ISSUE THREAD

**Issue by waynexia** [apache/arrow-datafusion#7879]
### Describe the bug

https://github.com/apache/arrow-datafusion/blob/37d6bf08c948418fe6c72d072d988c2875d81e02/datafusion/physical-expr/src/sort_expr.rs#L64-L73

This function (`PhysicalSortExpr::evaluate_to_sort_column()`) is in the execution phase. Errors at this stage should be `exec_err!` rather than `plan_err!`, right?

I also see other places have similar behavior and open this ticket to confirm. I'll submit a patch to change them if so.

**Comment by alamb** [comment]
I agree this would be better as a `execution_error`
