### ISSUE TITLE
Implement `~` pattern matching operator

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#795]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
DataFusion supports the `LIKE` operator which has a limited form of regular expression matching
It also supports `regexp_match` which adds support to extract matched strings (kudos to @seddonm1  !)
However, it doesn't expose any way to do full on posix style regular expression matching, such as `~` as described in the postgres manual: https://www.postgresql.org/docs/9.3/functions-matching.html

**Describe the solution you'd like**
Support syntax such as the following:

```sql
select * from foo where column ~ 'a.*b';
```

**Describe alternatives you've considered**
N/A

**Additional context**
@atingchen asked about this downstream in IOx: https://github.com/influxdata/influxdb_iox/issues/2137

**Comment by b41sh** [comment]
I'd like to work on this issue.

**Comment by alamb** [comment]
That is awesome @b41sh  -- thank you!
