### ISSUE TITLE
Use released version of arrow

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-datafusion#80]
Currently the Datafusion crates pin a version of arrow by git revision. Unfortunately this makes it complicated to use Datafusion with other libraries that also depend on arrow, making it is necessary to update all the version pins in lock-step across potentially multiple repositories. #39 helps somewhat with this, but doesn't help with crates that Datafusion isn't dependent on that themselves depend on arrow, or if you want to configure different feature flags from what Datafusion sets.

Unfortunately there is an outstanding [bug /feature omission](https://github.com/rust-lang/cargo/issues/5478) with cargo that makes patch not work for overriding git version pins, and the workarounds on the ticket no longer seem to work.

If Datafusion instead depended instead on a released version of arrow, Cargo's semver compatibility rules would avoid a lot of this pain for most users, and would allow users to use the patch syntax to override the arrow version in use for all their dependencies within their workspace, if they want to use an unreleased arrow version.

I'm not sure how feasible any of this is, but thought I would raise a ticket to maybe kickstart a discussion on this

**Comment by andygrove** [comment]
@tustvold Does https://github.com/apache/arrow-datafusion/pull/39 help with this?

**Comment by tustvold** [comment]
> @tustvold Does #39 help with this?

It helps, but doesn't solve the underlying issue. If you depend on another crate that in turn depends on arrow and isn't exposed by DataFusion, e.g. arrow-flight, or you want to set different features from what DataFusion sets, you end up having to replicate the exact version pins from DataFusion into all other crates

**Comment by tustvold** [comment]
> datafusion writes something like ^4.0.0 on its cargo.toml

Yes, this would be my ideal for the reasons you articulated.

> we release arrow more often and strictly according to semver

This would definitely be something I'd be supportive of, but possibly somewhat tangential to making DataFusion as a library easier to consume. Cargo has a good story for overriding dependencies within a workspace, including indirect dependencies, provided those versions aren't pinned within the libraries. Therefore if DataFusion were to move to a released version of arrow it wouldn't preclude users from opting-in to newer, potentially unreleased versions of arrow. 

However, DataFusion itself would not be able to opt-in to unreleased arrow functionality, and so if there are frequent DataFusion changes coupled with arrow changes, then yes a more frequent arrow release cycle would possibly be a pre-condition of moving to using a released version of arrow.

> I am not sure whether we could get away with the multiple paths approach, e.g.

I've not come across this approach, I'd worry that it might be vulnerable to https://github.com/rust-lang/cargo/issues/5478 which would prevent users from opting into newer versions of arrow within their workspaces, which imo would be unfortunate

**Comment by jorgecarleitao** [comment]
> but possibly somewhat tangential to making DataFusion as a library easier to consume

I agree.

My point is that the reason we use pinned hashes of arrow is so that we do not have to wait for a new release. So, I _think_  that to stop pinning in DataFusion, we need to release arrow more frequently. But I agree that from the consumers' point of view, it is not needed, as you can just point to a hash in `arrow-rs` ^_^

**Comment by Jimexist** [comment]
@alamb this can be closed now

**Comment by alamb** [comment]
Indeed -- thanks @Jimexist  -- this issue was closed in https://github.com/apache/arrow-datafusion/issues/393 I think
