### ISSUE TITLE
Test `dataframe_subquery` fails

### ISSUE THREAD

**Issue by smallzhongfeng** [apache/arrow-datafusion#8015]
### Describe the bug

When running datafreme's subquery-related test class, an exception will be thrown. The reason for the error is that no optimization rules are matched.
```
Error: Context("Optimizer rule 'common_sub_expression_eliminate' failed", SchemaError(FieldNotFound { field: Column { relation: Some(Bare { table: "t1" }), name: "c1" }, valid_fields: [Column { relation: Some(Bare { table: "t2" }), name: "c1" }, Column { relation: Some(Bare { table: "t2" }), name: "c2" }, Column { relation: Some(Bare { table: "t2" }), name: "c3" }, Column { relation: Some(Bare { table: "t2" }), name: "c4" }, Column { relation: Some(Bare { table: "t2" }), name: "c5" }, Column { relation: Some(Bare { table: "t2" }), name: "c6" }, Column { relation: Some(Bare { table: "t2" }), name: "c7" }, Column { relation: Some(Bare { table: "t2" }), name: "c8" }, Column { relation: Some(Bare { table: "t2" }), name: "c9" }, Column { relation: Some(Bare { table: "t2" }), name: "c10" }, Column { relation: Some(Bare { table: "t2" }), name: "c11" }, Column { relation: Some(Bare { table: "t2" }), name: "c12" }, Column { relation: Some(Bare { table: "t2" }), name: "c13" }] }))
```

### To Reproduce

 cargo run --example dataframe_subquery

**Comment by smallzhongfeng** [comment]
cc @alamb thx. If you can give me some suggestions, I'd be willing to try to fix it

**Comment by haohuaijin** [comment]
the error is becuase subquery use the outer query's column(`t1.c1`), maybe you can use `out_ref_col` instead of `col` to fix this.

**Comment by smallzhongfeng** [comment]
> the error is becuase subquery use the outer query's column(`t1.c1`), maybe you can use `out_ref_col` instead of `col` to fix this.

Thank you for your suggestion. This is indeed the cause of the problem. I will submit a PR to fix it. @haohuaijin : )
