### ISSUE TITLE
Support udf `range`

### ISSUE THREAD

**Issue by smallzhongfeng** [apache/arrow-datafusion#8028]
### Is your feature request related to a problem or challenge?

Currently our udf function does not have `range`. This is a commonly used function. I understand that I should add it.
try:
`select range(10);`
result: 
`Error: Plan("Invalid function 'range'.\nDid you mean 'nanvl'?")`
 
And duckdb or clickhouse has supported it.
duckdb: [https://duckdb.org/docs/archive/0.9.1/sql/functions/](https://duckdb.org/docs/archive/0.9.1/sql/functions/nested#:~:text=%27k%27-,Range%20Functions,-The%20functions%20range)
clickhouse: [https://clickhouse.com/docs/en/sql-reference/functions/array-functions](https://clickhouse.com/docs/en/sql-reference/functions/array-functions#rangeend-rangestart--end--step:~:text=Syntax-,range(%5Bstart%2C%20%5D%20end%20%5B%2C%20step%5D),-Arguments)

### Describe the solution you'd like

Add the udf function.

**Comment by alamb** [comment]
Added as subtask of https://github.com/apache/arrow-datafusion/issues/6980

**Comment by Veeupup** [comment]
hi @alamb  maybe I can try this issue?  : )

**Comment by alamb** [comment]
sure -- thanks @Veeupup  -- sorry for the delays in reviewing!
