### ISSUE TITLE
Error from example `catalog`

### ISSUE THREAD

**Issue by smallzhongfeng** [apache/arrow-datafusion#8041]
### Describe the bug

For the catalog test in the `example` directory, when running the `dict-page-offset-zero.parquet` file, an unparsable exception will be thrown.

### To Reproduce

```cargo run --example catalog```

``` Parquet error: Parquet error: Could not parse metadata: protocol error```

**Comment by smallzhongfeng** [comment]
It seems like there weren't that many parquet files to read before? https://github.com/apache/arrow-datafusion/pull/5326#pullrequestreview-1304611968

**Comment by alamb** [comment]
> It seems like there weren't that many parquet files to read before? https://github.com/apache/arrow-datafusion/pull/5326#pullrequestreview-1304611968

That could be -- maybe the next upgrade of parquet-rs will handle this 🤔
