### ISSUE TITLE
ListingTable with LocalFilesystem's new_with_prefix option leads to duplicate addition of root prefix.

### ISSUE THREAD

**Issue by trueleo** [apache/arrow-datafusion#8068]
### Describe the bug

Based on datafusion 32, any listing scan seems to fail with ` ObjectStore NotFound` when using `object_store::local::LocalFileSystem` where root path is not `/`. Somewhere during the query/scan flow the root specified in local fs object store unconditionally applied to all parsed ListTableUrl paths. 

```
thread 'main' panicked at src/main.rs:45:14:
called `Result::unwrap()` on an `Err` value: ObjectStore(NotFound { path: "/home/trueleo/rust/datafusion-localfs-test/home/trueleo/rust/datafusion-localfs-test/data.parquet", source: Os { code: 2, kind: NotFound, message: "No such file or directory" } })
````

This does not seem to be the case for s3 path where `s3://bucket` is used to find right object store for a listed file and path prefixed with this seems to work just fine.

In the example below i have manually registered a LocalFileSystem with it's root path set to example project's directory where i have a `data.parquet` file.

### To Reproduce

```rust 

use std::{env::current_dir, sync::Arc};

use datafusion::{
    arrow::util::pretty::pretty_format_batches,
    datasource::{
        file_format::parquet::ParquetFormat,
        listing::{ListingOptions, ListingTable, ListingTableConfig, ListingTableUrl},
    },
    execution::{
        object_store::{DefaultObjectStoreRegistry, ObjectStoreRegistry},
        runtime_env::{RuntimeConfig, RuntimeEnv},
    },
    prelude::{SessionConfig, SessionContext},
};
use object_store::local::LocalFileSystem;

#[tokio::main]
async fn main() {
    let project_dir = current_dir().unwrap();
    let url = url::Url::parse(&format!("file://{}", project_dir.display())).unwrap();
    let store = Arc::new(LocalFileSystem::new_with_prefix(&project_dir).unwrap());

    let object_store_registry = Arc::new(DefaultObjectStoreRegistry::new());
    object_store_registry.register_store(&url, store);

    let runtime = Arc::new(
        RuntimeEnv::new(RuntimeConfig::new().with_object_store_registry(object_store_registry))
            .unwrap(),
    );

    let ctx = SessionContext::new_with_config_rt(SessionConfig::default(), runtime);

    let listing_options =
        ListingOptions::new(Arc::new(ParquetFormat::new())).with_file_extension(".parquet");

    let table = Arc::new(
        ListingTable::try_new(
            ListingTableConfig::new(
                ListingTableUrl::parse(
                    "file:///home/trueleo/rust/datafusion-localfs-test/data.parquet",
                )
                .unwrap(),
            )
            .with_listing_options(listing_options)
            .infer_schema(&ctx.state())
            .await
            .unwrap(),
        )
        .unwrap(),
    );

    ctx.register_table("table", table).unwrap();

    let df = ctx.sql("select count(*) from table").await.unwrap();
    let res = df.collect().await.unwrap();
    println!("{}", pretty_format_batches(&res).unwrap())
}

```

### Expected behavior

The query should have just worked based on registered object store prefix and absolute path provided. 

### Additional context

I've also tried following paths but still the same error occurs
`/home/trueleo/rust/datafusion-localfs-test/data.parquet`
`data.parquet`

**Comment by tustvold** [comment]
> LocalFileSystem::new_with_prefix(&project_dir)

You are creating a LocalFileSystem with a given prefix, and then addressing the file `home/trueleo/rust/datafusion-localfs-test/data.parquet`

As can be seen in the error message, this gets resolved to

```
/home/trueleo/rust/datafusion-localfs-test/home/trueleo/rust/datafusion-localfs-test/data.parquet
```

There are two solutions here:

* Initialize the filesystem with `LocalFileSystem::new`
* Use a relative path in the file URI

**Comment by trueleo** [comment]
@tustvold 
> Use a relative path in the file URI
I am not sure what would that look like. I would like to use relative URIs but something like `data.parquet` resolves to absolute path during parsing

**Comment by tustvold** [comment]
> data.parquet resolves to absolute path during parsing

All paths eventually will get resolved to an absolute path, correct, this is how filesystems work. However, if you create a store with a prefix the URL you specify can contain a path relative to this prefix.

So if you used `LocalFileSystem::new_with_prefix("/home/foo/my_root")` the URL `file:///bar.parquet` would resolve to `/home/foo/my_root/bar.parquet`.

Perhaps you could explain what it is you are trying to achieve here?

**Comment by trueleo** [comment]
Thank you. `file:///data.parquet` worked. Isn't this an absolute path from `/` tho ?.

**Comment by tustvold** [comment]
It is just a URL with a scheme of `file`, no `host` and a path of `/data.parquet`. If this were interpreted as a normal file URI then yes it would describe an absolute path, however, you are overloading the URL scheme of `file` to make it be interpreted differently.

You could alternatively register the store with a different scheme / host to avoid this discrepancy, but it isn't harmful
