### ISSUE TITLE
run_first_last_multi_partitions fails in some environments

### ISSUE THREAD

**Issue by theotherandygrove** [apache/arrow-datafusion#8069]
### Describe the bug

`run_first_last_multi_partitions` fails when I run `cargo test` on my M1 Macbook Air with 16 GB RAM. It passes on my Ubuntu workstation with 128 GB RAM.

```
---- aggregates::tests::run_first_last_multi_partitions stdout ----
Error: ResourcesExhausted("Failed to allocate additional 632 bytes for GroupedHashAggregateStream[0] with 1829 bytes already allocated - maximum available is 605")
```

**Comment by alamb** [comment]
Perhaps this is somehow related to the updates in https://github.com/apache/arrow-datafusion/commit/f1f8d79ab80039ca531e0b20cd4ac4381a073713 to support spilling group by hash: https://github.com/apache/arrow-datafusion/pull/7400

https://github.com/apache/arrow-datafusion/blame/308c35404939ed39e4e398054d6fc78c89817109/datafusion/physical-plan/src/aggregates/mod.rs#L1891-L1899

**Comment by alamb** [comment]
I ran this on my macbook (x86) that has 64GB of ram

Maybe the failure is related to ARM vs Intel 🤔
