### ISSUE TITLE
Make default filter selectivity estimate configurable

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#8133]
### Is your feature request related to a problem or challenge?

PR https://github.com/apache/arrow-datafusion/pull/8126 updates FilterExec statistics method so that it will assume that the filter will select 20% of input rows in the case where it is not possible to estimate the output cardinality of the filter.

It would be better to make this configurable, so that users can select a default filter selectivity value between 0.0 (selects no rows) and 1.0 (selects all rows).

### Describe the solution you'd like

Add a new configuration option and plumb it through to FilterExec.

**Comment by smallzhongfeng** [comment]
Hi~ @andygrove can I try to fix this issue? : )

**Comment by edmondop** [comment]
@andygrove is this up for grab?

**Comment by andygrove** [comment]
> @andygrove is this up for grab?

@edmondop yes, absolutely.
