### ISSUE TITLE
Port tests in `displayable.rs` to sqllogictest

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#8199]
Part of https://github.com/apache/arrow-datafusion/issues/6195. We are trying to
1. keep the DataFusion code base clean and easy to contribute to and modify
2. Understand what features are covered and what are not

Part of doing so is having a single location for most test coverage so new tests can be added easily and people can follow the existing patterns easily

### Describe the solution you'd like

Port the tests in https://github.com/apache/arrow-datafusion/blob/main/datafusion/core/tests/sql/displayable.rs to
`displayable.slt` in https://github.com/apache/arrow-datafusion/tree/main/datafusion/sqllogictest/test_files

Note you can create catalogs and schema via SQL now

Catalogs: https://arrow.apache.org/datafusion/user-guide/sql/ddl.html#create-database
Schema: https://arrow.apache.org/datafusion/user-guide/sql/ddl.html#create-schema

Notes:
1. Instructions for running sqllogitest are here: https://github.com/apache/arrow-datafusion/tree/main/datafusion/sqllogictest

### Additional context

I think these are good first issues as they teach the contributor about the DataFusion codebase and tests, as well as see the end user apis in practice.

**Comment by alamb** [comment]
I actually think this test may be covered by `explain.slt` already

**Comment by simicd** [comment]
Hi @alamb, I looked into this and it seems `displayable.rs` was already migrated with #8246, there is no such file anymore [in the test folder](https://github.com/apache/arrow-datafusion/tree/b7e13a0af711477ad41450566c14430089edd3f2/datafusion/core/tests/sql). I think this issue can be closed.

**Comment by alamb** [comment]
> Hi @alamb, I looked into this and it seems `displayable.rs` was already migrated with #8246, there is no such file anymore [in the test folder](https://github.com/apache/arrow-datafusion/tree/b7e13a0af711477ad41450566c14430089edd3f2/datafusion/core/tests/sql). I think this issue can be closed as resolved.

Thank you @simicd  -- I think you are right. Closing!
