### ISSUE TITLE
[DataFusion] Add validation for unreferenced table in query

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#82]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-8260

This is an edge case but the query "SELECT 1 FROM t" causes an error in the Parquet reader because we are not reading any columns. We should have the query planner recognize this and fail the query is invalid.

**Comment by jackwener** [comment]
I find the column `1` isn't handled in `validate_schema_satisfies_exprs`.
 
Whene column is `1`, run
```sql
select * from information_schema.tables;
```

`validate_schema_satisfies_exprs`
doesn't actually go into the handler code segment
``` rust
|col| match col {
....
}
```

**Comment by jackwener** [comment]
When column is `1`,  match  `col` should match `_ => Err(`, but it didn't.

I'm confused.

**Comment by alamb** [comment]
I am not sure this issue is relevant anymore . Sorry for the poor ticket hygiene @jackwener 


```shell
cargo run --bin datafusion-cli
...

DataFusion CLI v7.0.0
❯ create table t1 as select * from (values (11, 'a'), (22, 'b'), (33, 'c'), (44, 'd'), (77, 'e')) as sq;
0 rows in set. Query took 0.047 seconds.
❯ select 1 from t1;
+----------+
| Int64(1) |
+----------+
| 1        |
| 1        |
| 1        |
| 1        |
| 1        |
+----------+
5 rows in set. Query took 0.008 seconds.

```
