### ISSUE TITLE
Port tests in `group_by.rs` to sqllogictest

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#8202]
### Is your feature request related to a problem or challenge?

Part of https://github.com/apache/arrow-datafusion/issues/6195. We are trying to
1. keep the DataFusion code base clean and easy to contribute to and modify
2. Understand what features are covered and what are not

Part of doing so is having a single location for most test coverage so new tests can be added easily and people can follow the existing patterns easily

### Describe the solution you'd like

Port the tests in https://github.com/apache/arrow-datafusion/blob/main/datafusion/core/tests/sql/group_by.rs to
`group_by.slt` in https://github.com/apache/arrow-datafusion/tree/main/datafusion/sqllogictest/test_files

Note you can create catalogs and schema via SQL now

Catalogs: https://arrow.apache.org/datafusion/user-guide/sql/ddl.html#create-database
Schema: https://arrow.apache.org/datafusion/user-guide/sql/ddl.html#create-schema

Notes:
1. Instructions for running sqllogitest are here: https://github.com/apache/arrow-datafusion/tree/main/datafusion/sqllogictest

### Additional context

I think these are good first issues as they teach the contributor about the DataFusion codebase and tests, as well as see the end user apis in practice.

**Comment by hiltontj** [comment]
I will work on this when I get some spare time.

Note, there is already a `groupby.slt` test file, which is quite large, but from a quick search does not look to cover the test cases from `group_by.rs`. I will port the tests to `groupby.slt`. If we are picky about the name, I can move `groupby.slt` to `group_by.slt` as well.

**Comment by alamb** [comment]
Thank you @hiltontj  -- any improvements you can make in this area are most appreciated
