### ISSUE TITLE
Port tests in `select.rs` to sqllogictest

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#8213]
### Is your feature request related to a problem or challenge?

Part of https://github.com/apache/arrow-datafusion/issues/6195. We are trying to
1. keep the DataFusion code base clean and easy to contribute to and modify
2. Understand what features are covered and what are not

Part of doing so is having a single location for most test coverage so new tests can be added easily and people can follow the existing patterns easily

### Describe the solution you'd like

Port the tests in https://github.com/apache/arrow-datafusion/blob/main/datafusion/core/tests/sql/select.rs to
`select.slt` in https://github.com/apache/arrow-datafusion/tree/main/datafusion/sqllogictest/test_files

Note you can create catalogs and schema via SQL now

Catalogs: https://arrow.apache.org/datafusion/user-guide/sql/ddl.html#create-database
Schema: https://arrow.apache.org/datafusion/user-guide/sql/ddl.html#create-schema

Notes:
1. Instructions for running sqllogitest are here: https://github.com/apache/arrow-datafusion/tree/main/datafusion/sqllogictest

### Additional context

I think these are good first issues as they teach the contributor about the DataFusion codebase and tests, as well as see the end user apis in practice.

**Comment by fansehep** [comment]
i want to try this. 😄

**Comment by alamb** [comment]
This one I think is still a good first issue / maybe even covered by existing tests

**Comment by Tangruilin** [comment]
@alamb maybe this can assign to me

**Comment by Tangruilin** [comment]
I need some help，https://github.com/apache/arrow-datafusion/blob/31b9b48b08592b7d293f46e75707aad7dadd7cbc/datafusion/core/tests/sql/select.rs#L121

**Comment by Tangruilin** [comment]
> I need some help，
> 
> https://github.com/apache/arrow-datafusion/blob/31b9b48b08592b7d293f46e75707aad7dadd7cbc/datafusion/core/tests/sql/select.rs#L121

Here it create a column with struct, but i do not know how to create it by sql

**Comment by Tangruilin** [comment]
> > I need some help，
> > https://github.com/apache/arrow-datafusion/blob/31b9b48b08592b7d293f46e75707aad7dadd7cbc/datafusion/core/tests/sql/select.rs#L121
> 
> Here it create a column with struct, but i do not know how to create it by sql

@alamb

**Comment by alamb** [comment]
> > I need some help，
> > https://github.com/apache/arrow-datafusion/blob/31b9b48b08592b7d293f46e75707aad7dadd7cbc/datafusion/core/tests/sql/select.rs#L121
> 
> Here it create a column with struct, but i do not know how to create it by sql

I think you can use the `struct` function:
https://arrow.apache.org/datafusion/user-guide/sql/scalar_functions.html#struct-functions

**Comment by simicd** [comment]
Hi both - @Tangruilin seems like we we're working independently on the topic 😮 I had raised two PRs previously but seems they remained unnoticed. Guess we should try to consolidate into a single PR, feel free to take over whatever you're missing currently from #8953 and #8939 and integrate into yours if that's ok with you as well. 

In #8939 you will find how I implemented the structs.


![image](https://github.com/apache/arrow-datafusion/assets/10134699/b907c438-37bd-4b91-a4a3-b5340cceeb13)

**Comment by Tangruilin** [comment]
> Guess we should try to consolidate into a single PR,

I have already sloved the problem of struct in my CR.
It seems my CR have sloved this issue.

**Comment by Tangruilin** [comment]
> Hi both - @Tangruilin seems like we we're working independently on the topic 😮 I had raised two PRs previously but seems they remained unnoticed. Guess we should try to consolidate into a single PR, feel free to take over whatever you're missing currently from #8953 and #8939 and integrate into yours if that's ok with you as well.
> 
> In #8939 you will find how I implemented the structs.
> 
> ![image](https://private-user-images.githubusercontent.com/10134699/299402375-b907c438-37bd-4b91-a4a3-b5340cceeb13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNDkzNDIsIm5iZiI6MTcwNjE0OTA0MiwicGF0aCI6Ii8xMDEzNDY5OS8yOTk0MDIzNzUtYjkwN2M0MzgtMzdiZC00YjkxLWE0YTMtYjUzNDBjY2VlYjEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDAyMTcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjZGFiYmI2OWE0MzZhYzQxNTQ4MGFiZDYwYzZmYmZmM2VkMDljZTAwMjEwODk3MGE5OTc0M2ZjNjI5YjFmNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e3Y9Cm0q_KjHjZJo4PNK4-oSb7atWTHgXBKI8LkVYdA)

Maybe We can use my CR?
Or do you have some suggestions?

**Comment by simicd** [comment]
> Maybe We can use my CR?
> Or do you have some suggestions?

Yes sounds good!

**Comment by alamb** [comment]
Yes, sorry -- I am backed up on reviews. I am hoping other committers can find more time to help. I am working to try and get the backlog down
