### ISSUE TITLE
Change output ordering display of sources

### ISSUE THREAD

**Issue by mustafasrepo** [apache/arrow-datafusion#8297]
### Is your feature request related to a problem or challenge?

Current source executors(`CsvExec, etc.`) contains `outpout_ordering` inside display. For the following table
```sql
CREATE EXTERNAL TABLE multiple_ordered_table (
  a0 INTEGER,
  a INTEGER,
  b INTEGER,
  c INTEGER,
  d INTEGER
)
STORED AS CSV
WITH HEADER ROW
WITH ORDER (a ASC, b ASC)
WITH ORDER (c ASC)
LOCATION '../core/tests/data/window_2.csv';
```
display would be 

```sql
----CsvExec: file_groups={1 group: [[path]]}, projection=[a, b], output_ordering=[a@0 ASC NULLS LAST, b@1 ASC NULLS LAST], has_header=true
```

It would be nice, if output ordering would contain all of the valid orderings at the source such as following

```sql
----CsvExec: file_groups={1 group: [[path]]}, projection=[a, b], output_orderings=[[a@0 ASC NULLS LAST, b@1 ASC NULLS LAST], [c@2 ASC NULLS LAST]], has_header=true
```

**Comment by alamb** [comment]
I agree this would be a great first issue

I think the relevant code is https://github.com/apache/arrow-datafusion/blob/2cd8f40ce91aa6a3d8db385b674f5b4e85ad47fc/datafusion/core/src/datasource/physical_plan/mod.rs#L138-L142

**Comment by QuenKar** [comment]
hi, I am new here and curious about this.

**Comment by mustafasrepo** [comment]
Thanks @QuenKar!
