### ISSUE TITLE
Port tests in `array_expression.rs` to `sqllogictest`

### ISSUE THREAD

**Issue by jayzhan211** [apache/arrow-datafusion#8324]
The goal is that there is no rust test in this file anymore.

Part of https://github.com/apache/arrow-datafusion/issues/6195

_Originally posted by @alamb in https://github.com/apache/arrow-datafusion/pull/8313#discussion_r1405386301_

File an issue to list the pending test to avoid duplicate work
- [ ] make_array
- [ ] array_element
- [ ] array_pop_back
- [ ] array_slice
- [ ] array_append
- [ ] array_prepend
- [ ] array_concat
- [ ] array_position
- [ ] array_to_string
- [ ] cardinality
- [ ] array_length
- [ ] array_dims
- [ ] Port other function to common::utils  or just remove it

**Comment by Veeupup** [comment]
hi @jayzhan211, I can help with `make_array` `array_element`

**Comment by jayzhan211** [comment]
> hi @jayzhan211, I can help with `make_array` `array_element` `array_pop_back`

Sure! Go ahead.

**Comment by Veeupup** [comment]
: )
I find that almost all test cases have been added to the `sqllogictest`, so I just remove some duplicate test codes then

**Comment by jayzhan211** [comment]
> : ) I find that almost all test cases have been added to the `sqllogictest`, so I just remove some duplicate test codes then

Close this issue with only delete, cools
