### ISSUE TITLE
Rename `expr::window_function::WindowFunction` to `WindowFunctionDefintion` for consistency

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#8347]
### Is your feature request related to a problem or challenge?

Part of  https://github.com/apache/arrow-datafusion/issues/8045 we are working
to consolidate the function implementation in DataFusion to make it easier to
manage DataFusion's built in list of functions as well as ensure user defined
and built in functions have the same feature sets.

I think it is also important to keep the Expr representation consistent for
Aggregate and Window functions to make DataFusion easier to work with, as well
as to permit eventually applying the same unification of built in and user
defined functions to aggregates and window functions.

### Describe the solution you'd like

I would like to rename the `WindowFunction` in to https://github.com/apache/arrow-datafusion/blob/4c914ea1e5d3dc61f3552adcffb8356c90d73bac/datafusion/expr/src/window_function.rs#L35-L44 to `WindowFunctionDefinition` so we didn't have so many things named `WindowFunction` and to mirror the structure of ScalarFunction

Edited: ~I would like to unify `Expr::WindowFunction` and `Expr::WindowUDF` following the pattern in https://github.com/apache/arrow-datafusion/pull/8258 @2010YOUY01:~

### Additional context

I think this is a pretty good first issue because we have an existing pattern in https://github.com/apache/arrow-datafusion/pull/8258

**Comment by haohuaijin** [comment]
it seems like we already unified `WindowFunction` in 
https://github.com/apache/arrow-datafusion/blob/4c914ea1e5d3dc61f3552adcffb8356c90d73bac/datafusion/expr/src/expr.rs#L515-L526
and
https://github.com/apache/arrow-datafusion/blob/4c914ea1e5d3dc61f3552adcffb8356c90d73bac/datafusion/expr/src/window_function.rs#L35-L44

**Comment by alamb** [comment]
> it seems like we already unified `WindowFunction` in

That is an excellent point. Thank you for the research @haohuaijin 

Maybe we could rename https://github.com/apache/arrow-datafusion/blob/4c914ea1e5d3dc61f3552adcffb8356c90d73bac/datafusion/expr/src/window_function.rs#L35-L44 to `WindowFunctionDefinition` so we didn't have so many things named `WindowFunction` and to mirror the structure of ScalarFunctions

**Comment by edmondop** [comment]
@haohuaijin are you already working on it or can I pick it up?

**Comment by haohuaijin** [comment]
@edmondop I haven't started working yet, feel free to pick it up.

**Comment by alamb** [comment]
> @alamb I am probably losing some pre-requisite, the Expr doesn't contain a WindowUDF variant but only a WindowFunction variant https://github.com/apache/arrow-datafusion/blob/main/datafusion/expr/src/expr.rs#L156 there is an AggregateUDF though...

You are right that the ticket description was incorrect, as @haohuaijin  noted in https://github.com/apache/arrow-datafusion/issues/8347#issuecomment-1832226281

I have updated it to say "rename WindowFunction` to `WindowFunctionDefinition`" -- sorry for the confusion

I think `AggregateUDF` is covered by https://github.com/apache/arrow-datafusion/issues/8346
