### ISSUE TITLE
Release documentation for python binding

### ISSUE THREAD

**Issue by houqp** [apache/arrow-datafusion#837]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

Follow up from https://github.com/apache/arrow-datafusion/issues/771#issuecomment-888160309 and https://github.com/apache/arrow-datafusion/issues/771#issuecomment-888490358.

**Describe the solution you'd like**

We should have a python API and user doc similar to https://arrow.apache.org/docs/python.

**Describe alternatives you've considered**

**Additional context**

Discussion on how to host datafusion website: https://lists.apache.org/thread.html/r0ed76cc60cdf651e8cf5c82a21cc64114c1f6d174dc5487434bd32ef%40%3Cdev.arrow.apache.org%3E

**Comment by houqp** [comment]
@Jimexist I likely won't have the capacity to get this done for the upcoming 5.1.0 release. But if you have time to help with setting up the doc, please let us know so we can add it to the 5.1.0 milestone :)

**Comment by Jimexist** [comment]
> @Jimexist I likely won't have the capacity to get this done for the upcoming 5.1.0 release. But if you have time to help with setting up the doc, please let us know so we can add it to the 5.1.0 milestone :)

i wonder what would be the conclusion for hosting site? this will likely impact on how the docs are organized so i'd like that to be sorted out.

also @andygrove or @alamb any suggestions?

**Comment by alamb** [comment]
@Jimexist  I don't have any specific suggestions / opinions on the tech for site hosting. The gh-pages idea seemed like a good one ( https://github.com/apache/arrow-datafusion/pull/244 and https://github.com/apache/arrow-datafusion/pull/245) but I can't remember why those PRs got closed

**Comment by Jimexist** [comment]
> @Jimexist I don't have any specific suggestions / opinions on the tech for site hosting. The gh-pages idea seemed like a good one ( #244 and #245) but I can't remember why those PRs got closed

maybe @houqp can confirm that https://github.com/apache/arrow-datafusion/issues/771#issuecomment-888490358 was the reason?

**Comment by houqp** [comment]
Yes, I believe @andygrove closed them because the discussion from the mailing list suggested to use the main arrow site instead. Also see https://github.com/apache/arrow-datafusion/pull/244#issuecomment-833006211.

**Comment by Jimexist** [comment]
this is likely to be closed by https://github.com/apache/arrow/pull/10982
