### ISSUE TITLE
Minor: small refactoring for ints/floats to timestamps conversions

### ISSUE THREAD

**Issue by comphead** [apache/arrow-datafusion#8370]
### Is your feature request related to a problem or challenge?

Follow up on #8159 #8193

While implementing fixes for two tickets above there is a small tech debt which needs to be adressed

### Describe the solution you'd like

Its needed to do a small refactoring on timestamp conversions
- use arrow-rs cast kernel for  Float -> Timestamp conversion
- get rid of double cast on Integer -> Timestamp conversion

**Comment by comphead** [comment]
Depends on https://github.com/apache/arrow-rs/pull/5123 to be released

**Comment by alamb** [comment]
I think this may be fixed now
