### ISSUE TITLE
Make it easier to create `ScalarValue` from `String` and `&str`

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#8380]
### Is your feature request related to a problem or challenge?

Someone reported on Discord: https://discord.com/channels/885562378132000778/1166447479609376850/1179899297483980941

>  currently when I'm trying to pass a String into ScalarValue::from(), the compiler is telling me that the trait bound ScalarValue: From<std::string::String> is not satisfied

Let's make it easier for people to get started with DataFusioN!

### Describe the solution you'd like

Make it so the following code works

```rust
let scalar = ScalarValue::from("foo");
let scalar = ScalarValue::from("foo".to_string());
```

### Additional context

I think this is a good first issue as it is well specified and would be a nice usability improvement

Related PR: https://github.com/apache/arrow-datafusion/pull/8378 (it would be nice to add an example of creating ScalarValue from a string there too)

**Comment by QuenKar** [comment]
Hi, I want to do this issue

**Comment by alamb** [comment]
> I met some question in `scalar.rs`. when adding a test case for it, it can't compiled in vscode. It seems to have something to do with parquet.

THanks @QuenKar -- I think this is https://github.com/apache/arrow-datafusion/issues/8250 (also noticed by @jayzhan211 )


Here is the workaround: https://github.com/apache/arrow-datafusion/issues/8250#issuecomment-1817007301

It would be great for someone to fix this
