### ISSUE TITLE
SQL: Ambiguous reference when aliasing in combination with ORDER BY

### ISSUE THREAD

**Issue by Jesse-Bakker** [apache/arrow-datafusion#8391]
### Describe the bug

When using an un-aliased name in an `ORDER BY` clause, while that name is aliased to the same name in a projection, datafusion raises an `AmbiguousReference` error.

If the name is not manually aliased, or the aliased name is used, no error is raised.

### To Reproduce

datafusion-cli:
```
❯ CREATE TABLE t (a INTEGER);
0 rows in set. Query took 0.003 seconds.
❯ SELECT t.a AS a FROM t ORDER BY t.a;
Schema error: Schema contains qualified field name t.a and unqualified field name a which would be ambiguous
```

The following variations do not raise an error:
```sql
SELECT a FROM t ORDER BY a;
SELECT a FROM t ORDER BY t.a;
SELECT t.a FROM t ORDER BY a;
SELECT t.a FROM t ORDER BY t.a;
SELECT t.a AS a FROM t ORDER BY a;
```

### Expected behavior

The result of the query `SELECT t.a AS a FROM t ORDER BY t.a` should be the same as from, for example `SELECT t.a AS a FROM t ORDER BY a` and `SELECT t.a FROM t ORDER BY t.a`

**Comment by alamb** [comment]
It might be good to verify the expected results in spark / postgres before making a fix

**Comment by Jesse-Bakker** [comment]
Spark:
```python
>>> spark.sql("SELECT t.a AS a FROM t ORDER BY t.a").show()
+---+
|  a|
+---+
|  1|
|  2|
+---+
```
Postgres:
```
# SELECT t.a AS a FROM t ORDER BY t.a;
 a
---
 1
 2
(2 rows)
```

**Comment by Asura7969** [comment]
Do you have any plans to fix this bug? If you don't have time I'll follow up @Jesse-Bakker

**Comment by Asura7969** [comment]
Do you have any plans to fix this bug? If you don't have time I'll follow up @Jesse-Bakker

**Comment by Jesse-Bakker** [comment]
@Asura7969 I won't get to it any time soon, so it would be great if you could pick it up!
