### ISSUE TITLE
`collection_size_threshold` incorrectly used in `supports_collect_by_size`

### ISSUE THREAD

**Issue by Dandandan** [apache/arrow-datafusion#8405]
### Describe the bug

In `supports_collect_by_size`, `collection_size_threshold` to compare the threshold for both `total_byte_size` (correct), but incorrectly as fallback for `num_rows`.
This leads to large planning differences for when estimated size is / is not available.

### To Reproduce

Read the code.

### Expected behavior

As a first step, introduce `hash_join_single_partition_threshold_rows`, being number of times (e.g. 10x) smaller than the number of bytes. Adapt `hash_join_single_partition_threshold` as well (may need to increase it).

We also can improve the estimation of size by improving the estimation.

**Comment by maruschin** [comment]
@Dandandan, hi!

I created a draft pull request, did I understand the idea correctly?

**Comment by Dandandan** [comment]
Thank you @maruschin <3
