### ISSUE TITLE
Support `IN` lists with more than three constants in predicates for bloom filters

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#8436]
### Is your feature request related to a problem or challenge?

BloomFilter support was added in https://github.com/apache/arrow-datafusion/pull/7821 by @hengfeiyang ❤️ 

There is partial support for optimizing queries that have `IN` List predicates,.  as suggested by @Ted-Jiang : https://github.com/apache/arrow-datafusion/pull/7821#discussion_r1366398648 and tested via https://github.com/apache/arrow-datafusion/blob/0d7cab055cb39d6df751e070af5a0bf5444e3849/datafusion/core/src/datasource/physical_plan/parquet/row_groups.rs#L1056-L1084

However, this only supports queries where there are three or fewer items in the IN list:

```
SELECT * 
FROM parquet_file 
WHERE col IN ('foo', 'bar', 'baz')
```

It only works for small numbers of constants because the current implementation only checks for predicates like `col = 'foo' OR col = 'bar'`. The reason this works for `InList`s is that with small numbers of items ( `3`) are rewritten to `OR` chains) by this code in the optimizer:

https://github.com/apache/arrow-datafusion/blob/0d7cab055cb39d6df751e070af5a0bf5444e3849/datafusion/optimizer/src/simplify_expressions/expr_simplifier.rs#L500-L549

Thus, the the current bloom filter code will not work for queries with large numbers (more than the `THRESHOLD_INLINE_INLIST`)  of constants in the `IN` list, such as

```sql
SELECT * 
FROM parquet_file 
WHERE col IN (
  'constant1',
  'constant2',
  ..,
  'constant99',
  'constant100',
)
```

### Describe the solution you'd like

I would like the bloom filter code to directly support `InListExpr` and thus also support `IN` / `NOT IN` queries with large numbers of constants

In terms of implementation, after https://github.com/apache/arrow-datafusion/pull/8437  is merged and https://github.com/apache/arrow-datafusion/issues/8376 is closed, this should be a straightforward matter of:
1. Adding support in `LiteralGurantee` code (see https://github.com/apache/arrow-datafusion/pull/8437 )
2. Add tests in `LiteralGurantee`
3. Add a integration test for Bloom filters in `datafusion/core/src/datasource/physical_plan/parquet/row_groups.rs`

### Additional context

Found while I was working on https://github.com/apache/arrow-datafusion/issues/8376

**Comment by alamb** [comment]
@my-vegetable-has-exploded  -- thank you -- can you please implement it in terms of `LiteralGuarantee` https://github.com/apache/arrow-datafusion/pull/8437 ?

**Comment by hengfeiyang** [comment]
@alamb @my-vegetable-has-exploded I found if there are more than three values the bloomfilter also can't work.

This works
```sql
SELECT *  FROM tbl where (trace_id='3c7dbf90d1a66e3faffa344519c3bac3' OR trace_id='1' OR trace_id='2') LIMIT 150;
```

This doesn't works
```sql
SELECT *  FROM tbl where (trace_id='3c7dbf90d1a66e3faffa344519c3bac3' OR trace_id='1' OR trace_id='2' OR trace_id='3') LIMIT 150;
```

**Comment by alamb** [comment]
> I think we can use Short-circuit evaluation here, if left satisfy some condition, we can skip right.
> 

I am in the middle of rewriting the bloom filter implementation to be more general  (see https://github.com/apache/arrow-datafusion/pull/8442). 

I believe the new (not yet merged) code correctly handles predicates like `where trace_id='3c7dbf90d1a66e3faffa344519c3bac3' OR trace_id='1' OR trace_id='2' OR trace_id='3'`

However, the new code does not handle explicit `IN` expressions

This ticket was perhaps a bit over eager -- basically I recommend not changing the existing implementation as I am rewriting it.

However, if you would like to that is fine, I can update the change as part of my PRs.

**Comment by my-vegetable-has-exploded** [comment]
> I recommend not changing the existing implementation as I am rewriting it.
> 
> 

Get it.

**Comment by alamb** [comment]
The relevant PRs have been merged now, so I think it would be possible to add support to `LiteralGuarantee`s which would automatically add support for BloomFilters

**Comment by my-vegetable-has-exploded** [comment]
thanks @hengfeiyang @alamb

**Comment by domyway** [comment]
if items more than 10 , it still can’t use bloom filter

**Comment by my-vegetable-has-exploded** [comment]
> if items more than 10 , it still can’t use bloom filter

Can you provide an example of reproducing the problem？ Thanks.

**Comment by alamb** [comment]
How do you know the bloom filter isn't being used?  Is there a reproducer (a parquet file) you can share?

It appears that there is no good way to know if the bloom filter code is working via logging or metrics 🤔 
https://github.com/apache/arrow-datafusion/blob/f39c040ace0b34b0775827907aa01d6bb71cbb14/datafusion/core/src/datasource/physical_plan/parquet/row_groups.rs#L111-L168

**Comment by alamb** [comment]
I wonder if https://github.com/apache/arrow-datafusion/pull/8669 from @yahoNanJing  is related (which basically adds IN list pruning based on `min`/`max` statistics rather than on the bloom filters)

**Comment by domyway** [comment]
> How do you know the bloom filter isn't being used? Is there a reproducer (a parquet file) you can share?
> 
> It appears that there is no good way to know if the bloom filter code is working via logging or metrics 🤔
> 
> https://github.com/apache/arrow-datafusion/blob/f39c040ace0b34b0775827907aa01d6bb71cbb14/datafusion/core/src/datasource/physical_plan/parquet/row_groups.rs#L111-L168

I conducted a test locally by writing 200GB of data. When using a Bloom filter for queries, I observed that the query only takes 0.1 seconds, whereas without using the Bloom filter, the query takes 1 second. If a query takes 1 second, I can infer that it is not using the Bloom filter because using the Bloom filter should yield results within 0.1 seconds.

**Comment by alamb** [comment]
> I conducted a test locally by writing 200GB of data

Thank you @domyway  -- I filed https://github.com/apache/arrow-datafusion/issues/8685 with your report to get some more visibility to this issue so others may be able to find it and help. Let's continue the conversation there
