### ISSUE TITLE
The file name have to be added when I query sql with datafusion-cli

### ISSUE THREAD

**Issue by xiaobai721** [apache/arrow-datafusion#8448]
### Describe the bug

It works when table_name has been added 
![1701929695546](https://github.com/apache/arrow-datafusion/assets/19648428/5d887122-4463-4473-99b4-ac51e704b92e)
It failed:
![1701929738194](https://github.com/apache/arrow-datafusion/assets/19648428/745c32e1-76ff-404d-9b29-e4884c7420b0)
 How to query data without table name before field ?

### To Reproduce

datafusion-cli version: v33.0.0

**Comment by haohuaijin** [comment]
I think you should use "SECURITY_ID" in the second query. Because use double quotes to treat field names as case-sensitive identifiers, the "security_id" is not equal to "SECURITY_ID".

**Comment by alamb** [comment]
I agree with @haohuaijin 's suggestion that this is not a bug. What do you think @xiaobai721 ?

**Comment by xiaobai721** [comment]
You are right. My bad... And I will close this issue. Many thanks
