### ISSUE TITLE
Invalid timezone information is ignored after `Z` in timestamp literals

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#8452]
### Describe the bug

Some timestamps that should error are actally parsed, leading to confusing cases when users make a mistake

For example this timestamp is invalid  `'2023-12-05T21:58:10.45ZZTOP'` but it is parsed as though it were `'2023-12-05T21:58:10.45Z'` (the trailing content is ignored)

### To Reproduce

using `datafusion-cli`, 

```sql
❯ select TIMESTAMP '2023-12-05T21:58:10.45ZZTOP';
+-------------------------------------+
| Utf8("2023-12-05T21:58:10.45ZZTOP") |
+-------------------------------------+
| 2023-12-05T21:58:10.450             |
+-------------------------------------+
1 row in set. Query took 0.001 seconds.
```

### Expected behavior

I expect the query to error, similarly to what happens if the `Z` is not present

```
❯ select TIMESTAMP '2023-12-05T21:58:10.45 hello';
Optimizer rule 'simplify_expressions' failed
caused by
Arrow error: Parser error: Invalid timezone "hello": 'hello' is not a valid timezone
```

This is consistent with postgres, which errors for such cases:

```sql
postgres=# select TIMESTAMP '2023-12-05T21:58:10.45ZZTOP';
ERROR:  invalid input syntax for type timestamp: "2023-12-05T21:58:10.45ZZTOP"
LINE 1: select TIMESTAMP '2023-12-05T21:58:10.45ZZTOP';
                         ^
postgres=# select timestamp '2023-12-05T21:58:10.45 hello';
ERROR:  invalid input syntax for type timestamp: "2023-12-05T21:58:10.45 hello"
LINE 1: select timestamp '2023-12-05T21:58:10.45 hello';
                         ^
postgres=# select timestamp '2023-12-05T21:58:10.45';
       timestamp
------------------------
 2023-12-05 21:58:10.45
(1 row)
```

### Additional context

Kudos to @reidkaufmann for finding this downstream 

This appears to be a bug in arrow: https://github.com/apache/arrow-rs/issues/5182

Once it is fixed in arrow, then we can write a test for it in DataFusion and close the issue

**Comment by razeghi71** [comment]
Can I give this a shot?

**Comment by razeghi71** [comment]
I've made the change on `arrow-rs` in here: https://github.com/apache/arrow-rs/pull/5189, should be merged in a few weeks and then we can update the version and write the tests here.

**Comment by alamb** [comment]
Thank you @razeghi71

**Comment by ZhengLin-Li** [comment]
Is this issue still opening? I am interested in adding more test cases to test if it works as expected.

**Comment by alamb** [comment]
Thanks @ZhengLin-Li  

I double checked and the issue appears to be fixed in the latest DataFusion

Adding a test case would be most appreciated 🙏 

```
DataFusion CLI v35.0.0
❯ select TIMESTAMP '2023-12-05T21:58:10.45ZZTOP';
Arrow error: Parser error: Invalid timezone "ZZTOP": 'ZZTOP' is not a valid timezone
```

**Comment by MohamedAbdeen21** [comment]
Hi @ZhengLin-Li ,

I think you're confusing arrow's parser with DF's parser.

The job of a parser in a programming language is to validate the syntax and build an AST. TIMESTAMP '2023-12-05T21:58:10.45ZZTOP' is syntactically correct, as TIMESTAMP 'x' and TIMESTAMP '' (empty string).

This is a semantics issue which, in typical programming languages, is check by the semantic analysis step. In the case of SQL, and as stated in the issue's expected behavior, this should be handled by the optimizer; or worst case scenario by the query executor (think of interpreted languages that catch semantics error during execution).
