### ISSUE TITLE
Reported very slow performance compared to DuckDB in ibis-project

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#8492]
### Describe the bug

As reported by @cpcloud  in https://github.com/ibis-project/ibis/pull/7703

The most relevant portions:

**DataFusion**
DataFusion never ran out of memory and had a memory profile similar to DuckDB:
single digit GBs peak memory.

However, it was still extremely slow compared to DuckDB, about 9-10 minutes to
run the whole workload.

Similarly to Polars I compared both the Ibis implementation and a hand-written
SQL version (built from the generated Ibis code). Both had the same performance

I also looked at perf top while the DataFusion workload was running and saw this:

![289368886-a33bf90f-8877-43b0-8a4d-328f9721f264](https://github.com/apache/arrow-datafusion/assets/490673/bde9dc16-b7fb-4bde-9af6-b980f3f0e07a)

### To Reproduce

TBD (first thing would be to get a datafusion only reproducer)

Looks like the query, from https://github.com/ibis-project/ibis/pull/7703 is

```sql
SELECT
  month,
  ext,
  COUNT(DISTINCT project_name) AS project_count
FROM (
  SELECT
    project_name,
    DATE_TRUNC('month', uploaded_on) AS month,
    NULLIF(
      REPLACE(
        REPLACE(
          REPLACE(
            REGEXP_REPLACE(
              REGEXP_REPLACE(
                REGEXP_MATCH(path, CONCAT('(', '\.([a-z0-9]+)$', ')'))[2],
                'cxx|cpp|cc|c|hpp|h',
                'C/C++',
                'g'
              ),
              '^f.*$',
              'Fortran',
              'g'
            ),
            'rs',
            'Rust'
          ),
          'go',
          'Go'
        ),
        'asm',
        'Assembly'
      ),
      ''
    ) AS ext
  FROM pypi
  WHERE COALESCE(
      ARRAY_LENGTH(
        REGEXP_MATCH(path, '\.(asm|c|cc|cpp|cxx|h|hpp|rs|[Ff][0-9]{0,2}(?:or)?|go)$')
      ) > 0,
      FALSE
    )
    AND NOT COALESCE(ARRAY_LENGTH(REGEXP_MATCH(path, '(^|/)test(|s|ing)')) > 0, FALSE)
    AND NOT STRPOS(path, '/site-packages/') > 0
)
WHERE ext IS NOT NULL
GROUP BY month, ext
ORDER BY month DESC, project_count DESC
```

**Comment by alamb** [comment]
I wonder if the slowness in regexp / time spent compiling stuff is related to not being able to pre-compile the argument and instead re-creating the regular expression for each batch.

@thinkharderdev  mentioned something similar for  https://github.com/apache/arrow-datafusion/issues/8051

**Comment by cpcloud** [comment]
Thanks for creating the issue!

The example can be simplified a bit.

It should be sufficient to see the performance difference between DuckDB by:

1. Using any single file from the dataset (they're all big enough to take some noticeable amount of time)
2. Removing the aggregation and using only the inner `SELECT`.

**Comment by Dandandan** [comment]
A similar problem (recompiling the regex again and again) I found some time ago in the clickbench benchmark as well (query 28): 
https://github.com/JayjeetAtGithub/datafusion-duckdb-benchmark/blob/main/clickbench/queries-datafusion.sql#L29

**Comment by Weijun-H** [comment]
> test with simple regexp_match query with `index-0.parquet` `array-datafusion` took 47.847 seconds.
> 
> ```
> SELECT COUNT(*) FROM '*.parquet' WHERE
>     ARRAY_LENGTH(
>       REGEXP_MATCH(path, '\\.(asm|c|cc|cpp|cxx|h|hpp|rs|[Ff][0-9]{0,2}(?:or)?|go)$')
>     ) > 0;
> 
> 
> DataFusion CLI v33.0.0
> +----------+
> | COUNT(*) |
> +----------+
> | 5834398  |
> +----------+
> 1 row in set. Query took 47.847 seconds.
> 
> ../datafusion-cli/target/release/datafusion-cli -f d0.sql  225.03s user 5.77s system 477% cpu 48.353 total
> ```
> 
> `duckdb` took 3.029 seconds
> 
> ```
> SELECT COUNT(*) FROM '*.parquet' WHERE
>     ARRAY_LENGTH(
>       REGEXP_EXTRACT_ALL(path, '\.(asm|c|cc|cpp|cxx|h|hpp|rs|[Ff][0-9]{0,2}(?:or)?|go)$')
>     ) > 0;
> 
> 
> ┌──────────────┐
> │ count_star() │
> │    int64     │
> ├──────────────┤
> │      5834398 │
> └──────────────┘
> ../../duckdb/build/release/duckdb -s "`cat d1.sql`"  15.70s user 1.78s system 576% cpu 3.029 total
> ```

Maybe related to this #8524

**Comment by cpcloud** [comment]
Seems unlikely to be related to #8524. The issue is present for a single file.

**Comment by alamb** [comment]
I had some ideas on how to speed up regular expression evaluation here: https://github.com/apache/arrow-datafusion/issues/8051#issuecomment-1855953090

**Comment by comphead** [comment]
![df-distinct-graph](https://github.com/apache/arrow-datafusion/assets/10247224/6fe4587d-b311-4a2f-adcd-9ffdecbf7934)
Attaching Flamegraph for the query 
```
SELECT COUNT(*) FROM '*.parquet' WHERE
    ARRAY_LENGTH(
      REGEXP_EXTRACT_ALL(path, '\.(asm|c|cc|cpp|cxx|h|hpp|rs|[Ff][0-9]{0,2}(?:or)?|go)$')
    ) > 0;
```

**Comment by alamb** [comment]
The blog post is now published: https://ibis-project.org/posts/pydata-performance-part2/

**Comment by alamb** [comment]
@viirya  found some very low hanging fruit: https://github.com/apache/arrow-datafusion/pull/8538

**Comment by cpcloud** [comment]
Happy to try the query again once the next release it out!

**Comment by viirya** [comment]
It is #8631 actually. 😄

**Comment by my-vegetable-has-exploded** [comment]
> ![df-distinct-graph](https://private-user-images.githubusercontent.com/10247224/290721703-6fe4587d-b311-4a2f-adcd-9ffdecbf7934.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExNzA1NzgsIm5iZiI6MTcxMTE3MDI3OCwicGF0aCI6Ii8xMDI0NzIyNC8yOTA3MjE3MDMtNmZlNDU4N2QtYjMxMS00YTJmLWFkY2QtOWZmZGVjYmY3OTM0LnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDA1MDQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5OTE4ZjNkMWI3OTQ5MWZkY2E0NjI1ZjcwMmY1ZjU4YzI1NTc1ZTlkYjE4MjIyZjIxYTI0N2E0MWYwMjZhYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gDdXyK9-USVP81YDFSxVyZo4AjGPCh_kQ8huHu-QK04) Attaching Flamegraph for the query
> 
> ```
> SELECT COUNT(*) FROM '*.parquet' WHERE
>     ARRAY_LENGTH(
>       REGEXP_EXTRACT_ALL(path, '\.(asm|c|cc|cpp|cxx|h|hpp|rs|[Ff][0-9]{0,2}(?:or)?|go)$')
>     ) > 0;
> ```

Hi, could you share the method to draw the flamegraph? 

There is a large "unknown" in my flame graph, which prevents me from tracking the function call chain.

![图片](https://github.com/apache/arrow-datafusion/assets/48236141/81e3ad20-07d5-429a-9ff2-4de6dcf58d7c)

Here is my shell to generate the flamegraph using `datafusion-cli`.

```shell
#!/bin/bash
PERF_DATA_FILE="$1"
../../datafusion-cli/target/debug/datafusion-cli -f repro-range-query.sql &
# datafusion-cli -f repro-range-query.sql &
PID=$!
# use perf to collect data
sudo /usr/bin/perf_5.15 record --call-graph=dwarf -e cpu-clock -F 100 -p $PID -- sleep 30
sudo /usr/bin/perf_5.15 script -i perf.data >"perf.unfold"
FLAMEGRAPH_DIR="/home/deepin/sdk/FlameGraph"
"$FLAMEGRAPH_DIR/stackcollapse-perf.pl" "perf.unfold" >"perf.folded"

"$FLAMEGRAPH_DIR/flamegraph.pl" "perf.folded" >"$1.svg"

rm "perf.unfold" "perf.folded"
echo "Flame graph SVG created: $1.svg"
```

**Comment by alamb** [comment]
> Hi, could you share the method to draw the flamegraph?


@comphead  recently added this to the contributor guide: https://arrow.apache.org/datafusion/library-user-guide/profiling.html#building-a-flamegraph
