### ISSUE TITLE
[Rust][Datafusion] Add datafusion-cli to the docker-compose setup

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#85]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-5170

See dockerfile: https://github.com/apache/arrow/pull/4147/files#diff-2233b99f64d6acbef4e9d964e29fa76bR18

**Comment by paolorechia** [comment]
Hi, is this still relevant? I couldn't find a `docker-compose.yaml` in the repository.

**Comment by alamb** [comment]
I agree -- not relevant. Thanks for pointing it out @paolorechia
