### ISSUE TITLE
Add ScalarValue::Union variant

### ISSUE THREAD

**Issue by thinkharderdev** [apache/arrow-datafusion#8500]
### Is your feature request related to a problem or challenge?

Currently there is no scalar representation of a `Union` type which can cause issue in cases where we rely on `ScalarValue` (see https://github.com/apache/arrow-datafusion/issues/8499 for the issue that is prompting this request)

### Describe the solution you'd like

Define a `ScalarValue::Union` variant. I **think** this should be as simple as:
```
enum ScalarValue {
   ...
   Union(i8,Box<ScalarValue>)
}
```

That is, just wraps another `ScalarValue` along with the `type_id`

### Describe alternatives you've considered

Not do anything

**Comment by Tangruilin** [comment]
@thinkharderdev This looks interesting，are you working on it？
