### ISSUE TITLE
Parallel Arrow file format reading

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#8503]
### Is your feature request related to a problem or challenge?

DataFusion can now automatically read CSV and parquet files in parallel (see https://github.com/apache/arrow-datafusion/issues/6325 for CSV)

It would be great to do the same for "Arrow" files 

### Describe the solution you'd like

Basically implement what is described in https://github.com/apache/arrow-datafusion/issues/6325 for Arrow -- and read a single large arrow file in parallel

### Describe alternatives you've considered

Some research may be required -- I am not sure if finding record boundaries is feasible

### Additional context

I found this while writing tests for https://github.com/apache/arrow-datafusion/issues/8451

**Comment by my-vegetable-has-exploded** [comment]
I'd like to have a try.

**Comment by my-vegetable-has-exploded** [comment]
I read related pr about parquet and csv.
Parquet parallel scan is based on rowgroup and csv is based on line. Both of them can be splitted by row and then output RecordBatchs using  a certain method.
I don't think arrow can be handled like that, since arrow file is purely column-based. 
But I am wondering whether we can split the scan process into several parts and rebuild the whole Batch, since there maybe more than one array in file.
![图片](https://github.com/apache/arrow-datafusion/assets/48236141/8e7a8b19-f302-4678-96a8-d2d3af5f4c56)

Merry Christmas!

**Comment by alamb** [comment]
> But I am wondering whether we can split the scan process into several parts and rebuild the whole Batch, since there maybe more than one array in file.

This sounds like a good idea to me in theory -- I am not sure how easy/hard it would be to do with the existing arrow IPC reader

In general, the strategy for paralleizing Paruqet and CSV is to be to split up the file by ranges,  and then have each of the `ArrowFileReader`s partitions read row groups (or CSV lines) that have their first byte within their assigned rnage

Perhaps we could do the same for arrow files which could use the first byte of the RecordBatches 🤔

**Comment by my-vegetable-has-exploded** [comment]
> Perhaps we could do the same for arrow files which could use the first byte of the RecordBatches 🤔
> 

There maybe several RecordBatches(blocks in arrow-rs) in a Arrow file(I didn't notice it before). We can handle it like rowgroups in parquet. 

I will check whether DICTIONARY can be handled correctly since there maybe Delta DICTIONARY.

Thanks.

**Comment by my-vegetable-has-exploded** [comment]
> I will check whether DICTIONARY can be handled correctly since there maybe Delta DICTIONARY.

It seems that delta dictionary batches not supported yet.

And I think a pub function to provide offsets is needed in upstream.  Like 

```rust
impl<R: Read + Seek> FileReader<R> {
    pub fn blocks(&self) -> Vec<Block> {
        &self.blocks
    }
   //OR
    pub fn blocks(&self) -> Vec<i64> {
        &self.blocks.iter().map(Block::offset).collect()
    }
}
```

**Comment by tustvold** [comment]
https://github.com/apache/arrow-rs/pull/5249 adds a lower-level reader that should enable this and other use-cases

**Comment by my-vegetable-has-exploded** [comment]
> > Delta DICTIONARY.
> 
> Delta and replacement dictionaries are only supported by IPC streams, not files

get it! Thanks

**Comment by alamb** [comment]
The next release is tracked by https://github.com/apache/arrow-rs/issues/5234
