### ISSUE TITLE
Optimizer adds CoalesceBatchesExec after Hash Repartition

### ISSUE THREAD

**Issue by Blajda** [apache/arrow-datafusion#8523]
### Describe the bug

I have an `ExecutionPlan` with the following input distribution requirement.
```
  fn required_input_distribution(&self) -> Vec<Distribution> {
      vec![Distribution::HashPartitioned(vec![self.expr.clone()]); 1]
  }
```
where expr is typical `col("a")`

When the plan is built a RepatriationExec is created with the expected expression but immediately after a CoalesceBatchesExec is inserted causing records with the same hash to arrive in different partitions and violating the required input distribution.

This [optimization rule ](https://github.com/apache/arrow-datafusion/blob/d091b55be6a4ce552023ef162b5d081136d3ff6d/datafusion/core/src/physical_optimizer/coalesce_batches.rs#L65) is likely the culprit.

Setting `with_coalesce_batches(false);` is a workaround for this

### Expected behavior

If an node requires an specific input distribution then the optimizer would respect that requirement.

**Comment by Dandandan** [comment]
Can you give more details about your use case `CoalesceBatchesExec` doesn't change the partitions of data, only combines batches within the same partition, so it shouldn't lead to this.

**Comment by Blajda** [comment]
Looking further into it's an issue with the new operator I'm implementing and coalescing just exposes the issue.
