### ISSUE TITLE
How to build DataFusion python wheel 

### ISSUE THREAD

**Issue by mmuru** [apache/arrow-datafusion#853]
The latest python datafusion release 0.2.0 (from PyPi) was Dec 9, 2020. The DataFusion 4.0.0 version released but no official DataFusion release for Python. I am trying to build a wheel from the source but no setup.py or instructions how to build a wheel package. Please, can someone provide the steps or instructions how to build a wheel package? Thanks.

**Comment by houqp** [comment]
We will hopefully be able to release 0.3.0 this week. In the mean time you can follow the instructions at https://github.com/apache/arrow-datafusion/tree/master/python#how-to-develop. `maturin` is the command you want to use. `maturin develop` to build and install the binding into local python virtualenv. `maturin release` to build a release wheel that can be published to pypi index.
