### ISSUE TITLE
Remove ListingTable and FileScanConfig Unbounded

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-datafusion#8540]
### Is your feature request related to a problem or challenge?

Following on from #7994 it should be possible to remove the unbounded stream support from ListingTable, as this is now provided by StreamTable.

@ozankabak @metesynnada Am I correct in thinking this?

### Describe the solution you'd like

I would like to remove `FileScanConfig::infinite_source` and the corresponding options on CsvReadOptions, etc...

**Comment by ozankabak** [comment]
AFAICT you are correct. I will consult with @metesynnada tomorrow to make sure about CSV options structs etc.

**Comment by metesynnada** [comment]
It is logical to delete them.

**Comment by alamb** [comment]
I think this would be a good first issue for anyone interested in helping clean up the codebase
