### ISSUE TITLE
Remove External Table Backwards Compatibility Options

### ISSUE THREAD

**Issue by tustvold** [apache/arrow-datafusion#8547]
### Is your feature request related to a problem or challenge?

https://github.com/apache/arrow-datafusion/pull/8539 and https://github.com/apache/arrow-datafusion/pull/8017 made various `CREATE EXTERNAL TABLE` options do nothing, but avoided making them return an error if specified so as to preserve backwards compatibility.

### Describe the solution you'd like

We should remove this backwards compatibility logic

### Additional context

https://github.com/apache/arrow-datafusion/issues/8540 and https://github.com/apache/arrow-datafusion/issues/8548 will likely remove further options

**Comment by yyy1000** [comment]
Can I help this? 
It seems a code clean task about removing `insert_mode` option.

**Comment by alamb** [comment]
Seems reasonable to me -- @tustvold  do you have any other hints?

**Comment by yyy1000** [comment]
Created #9105 that may help it. :)
