### ISSUE TITLE
Add serde support for CSV FileTypeWriterOptions

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#8597]
### Is your feature request related to a problem or challenge?

DataFusion supports many FileTypeWriterOptions:

```rust
pub enum FileTypeWriterOptions {
    #[cfg(feature = "parquet")]
    Parquet(ParquetWriterOptions),
    CSV(CsvWriterOptions),
    JSON(JsonWriterOptions),
    Avro(AvroWriterOptions),
    Arrow(ArrowWriterOptions),
}
```

The serde support in the `datafusion-proto` crate currently only supports JSON:

```protobuf
message FileTypeWriterOptions {
  oneof FileType {
    JsonWriterOptions json_options = 1;
  }
}
```

### Describe the solution you'd like

Add serde support for CSV FileTypeWriterOptions

**Comment by devinjdangelo** [comment]
I am interested in helping out with this (and the related FileTypeWriterOption / copy serde support issues). I can take a look later today or tomorrow if you aren't too far along already.

**Comment by andygrove** [comment]
> I am interested in helping out with this (and the related FileTypeWriterOption / copy serde support issues). I can take a look later today or tomorrow if you aren't too far along already.

Sorry, just saw this message, and I have a draft PR up for this one now. Would be great to get your review and also would be good to work with you on this. 

Would you be interested in picking up https://github.com/apache/arrow-datafusion/issues/8632?

**Comment by devinjdangelo** [comment]
@andygrove Yes, I can take a look at the draft PR, and happy to pick up #8632 as well.
