### ISSUE TITLE
Add serde support for Arrow FileTypeWriterOptions

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#8599]
### Is your feature request related to a problem or challenge?

DataFusion supports many FileTypeWriterOptions:

```rust
pub enum FileTypeWriterOptions {
    #[cfg(feature = "parquet")]
    Parquet(ParquetWriterOptions),
    CSV(CsvWriterOptions),
    JSON(JsonWriterOptions),
    Avro(AvroWriterOptions),
    Arrow(ArrowWriterOptions),
}
```

The serde support in the `datafusion-proto` crate currently only supports JSON:

```protobuf
message FileTypeWriterOptions {
  oneof FileType {
    JsonWriterOptions json_options = 1;
  }
}
```

### Describe the solution you'd like

Add serde support for Arrow FileTypeWriterOptions

**Comment by tushushu** [comment]
@andygrove Hey, Andy. May I work on this issue?

**Comment by alamb** [comment]
> @andygrove Hey, Andy. May I work on this issue?

Please do -- thank you @tushushu !
