### ISSUE TITLE
Support computing ScalarValue return types from argument values (e.g. constants) rather than just types

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#8624]
### Def one UDF: 

```rust
my_udf(expr, 'return_type')
```

### Using:

case1:
```rust
my_duf(col, 'UInt32')

Return Type is:
DataType::UInt32
```

case2:
```rust
my_duf(col, 'UInt64')

Return Type is:
DataType::UInt64
```

At present, the above udf cannot be realized through the `ReturnTypeFunction`. This is because the `ReturnTypeFunction` provides only the data types of the input parameters.

As we discussed on https://github.com/apache/arrow-datafusion/discussions/7657#discussioncomment-7146772 `arrow_cast` does this but it is handled specially. This ticket tracks adding UDF support for it

_Originally posted by @JasonLi-cn in https://github.com/apache/arrow-datafusion/discussions/7657_

**Comment by alamb** [comment]
I think we can probably work on this now that https://github.com/apache/arrow-datafusion/issues/8568 is merged

**Comment by yyy1000** [comment]
Since my first PR is close to be merged. I'd like to work on this as a next. 😀

**Comment by yyy1000** [comment]
I created a PR in #8985 that wants to fix this. ❤️
