### ISSUE TITLE
Split equivalence code into smaller modules

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#8633]
### Is your feature request related to a problem or challenge?

As equivalence and ordering become ever more important, I would like to break the code up into smaller modules to make it harder to handle.

At almost 3000 lines with several large classes that are overlapping. the existing equivalence.rs is hard to understand.

I would like to break it up into smaller modules.

In fact I didn't even realize there were so many equivalence tracking structures until I started looking at the code more closely.

### Describe the solution you'd like

Move `EquivalenceClass`, `EquivalenceGroup`, `OrderingEquivalenceClass`, `ProjectionMapping`, `EquivalenceProperties`; and into their own modules, updating any internal apis if necessary

I made a PR (that has gone stale) that did this: https://github.com/apache/arrow-datafusion/pull/8235

### Additional context

I think this is a relatively good first issue as there is a PR that shows how to do it and it is mostly a software engineering exercise in moving code around rather than requiring deep DataFusion knowledge

**Comment by alamb** [comment]
FYI @mustafasrepo and @ozankabak

**Comment by tushushu** [comment]
@alamb  Hey Andrew, may I take this one?
