### ISSUE TITLE
Add serde support for CSV and Parquet FileSinkExec nodes

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#8645]
### Is your feature request related to a problem or challenge?

We have serde support for `JsonSinkExec` but not for other file types.

```protobuf
message JsonSink {
  FileSinkConfig config = 1;
}

message JsonSinkExecNode {
  PhysicalPlanNode input = 1;
  JsonSink sink = 2;
  Schema sink_schema = 3;
  PhysicalSortExprNodeCollection sort_order = 4;
}
```

### Describe the solution you'd like

Implement serde for CSV and Parquet `FileSinkExec`

**Comment by Jefffrey** [comment]
Related to https://github.com/apache/arrow-datafusion/issues/7303
