### ISSUE TITLE
ParquetExec should parallelize statistics scan operations

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#867]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
ParquetExec currently uses a single thread to iterate over all input files and collect statistics. This can be very slow at scale (> 30 seconds) and it would be good to parallelize this work.

**Describe the solution you'd like**
We currently split the list of file names into chunks (partitions) and then iterate over in a single thread like this:

```rust
for chunk in chunks {
  for filename in filenames {
    ..
  }
}
```

I propose that we process each chunk in parallel, something like this:

```rust
let mut tasks = vec![];
for chunk in chunks {
  let task = tokio:spawn(async move {
    for filename in filenames {
      ..
    }
  });
  tasks.push(task);
}
// wait for all tasks to complete
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Dandandan** [comment]
This (and more) should be parallelized by now.
