### ISSUE TITLE
Standardize compression encoding in protobuf

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#8680]
### Is your feature request related to a problem or challenge?

We currently have two mechanisms for serializing compression formats in datafusion.proto.

`CreateExternalTableNode` uses a string representation:

```protobuf
string file_compression_type = 10;
```

`JsonWriterOptions` uses an enum:

```protobuf
CompressionTypeVariant compression = 1;
```

Here is the definition of `CompressionTypeVariant`:

```protobuf
enum CompressionTypeVariant {
  GZIP = 0;
  BZIP2 = 1;
  XZ = 2;
  ZSTD = 3;
  UNCOMPRESSED = 4;
}
```

### Describe the solution you'd like

It would be better to standardize on one approach for a more consistent API.

**Comment by tushushu** [comment]
Hey Andy, may I take this one?

**Comment by alamb** [comment]
> Hey Andy, may I take this one?

In general, feel free to work on any issue @tushushu  -- it is good practice, as you are doing here, to announce your intent to let other contributors know what you are doing and thus to avoid duplicated work when possible, but there is no need to wait to begin work either

**Comment by tushushu** [comment]
> > Hey Andy, may I take this one?
> 
> In general, feel free to work on any issue @tushushu -- it is good practice, as you are doing here, to announce your intent to let other contributors know what you are doing and thus to avoid duplicated work when possible, but there is no need to wait to begin work either

Thanks @alamb, I'll follow your advice.

**Comment by tushushu** [comment]
The `CreateExternalTableNode` appears 15 times while the `CompressionTypeVariant` appears 104 times in the repo. I would arbitrarily assume that using the latter would result in smaller changes.

**Comment by tushushu** [comment]
And the `JsonWriterOptions` appears 34 times.

**Comment by alamb** [comment]
> The `CreateExternalTableNode` appears 15 times while the `JsonWriterOptions` appears 34 times.. I would arbitrarily assume that using the latter would result in smaller changes and impact.

https://github.com/search?q=repo%3Aapache%2Farrow-datafusion%20CreateExternalTableNode&type=code shows only 3 matches 🤔  

there are a few files that are generated (e.g. pbjson or protobuf) which perhaps is what you are finding but would not show up in your seach

**Comment by tushushu** [comment]
> > The `CreateExternalTableNode` appears 15 times while the `JsonWriterOptions` appears 34 times.. I would arbitrarily assume that using the latter would result in smaller changes and impact.
> 
> https://github.com/search?q=repo%3Aapache%2Farrow-datafusion%20CreateExternalTableNode&type=code shows only 3 matches 🤔
> 
> there are a few files that are generated (e.g. pbjson or protobuf) which perhaps is what you are finding but would not show up in your seach

The link above shows 3 file matches. If I add a file filter in my VSCode where filetype = `*.rs`, `CreateExternalTableNode` shows 13 results in 3 files. `JsonWriterOptions` shows 32 results in 8 files.
