### ISSUE TITLE
Regression: datafusion-cli can no longer run `EXPLAIN ANALYZE` 

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#8690]
### Describe the bug

datafusion-cli can no longer run `EXPLAIN ANALYZE` 

### To Reproduce

```shell
datafusion-cli -c "explain analyze select * from './parquet-testing/data/data_index_bloom_encoding_stats.parquet';"
DataFusion CLI v34.0.0
Internal error: Optimization not supported for ANALYZE.
This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```

### Expected behavior

I expect the query to run and produce an EXPLAIN plan annotated with output counters

### Additional context

The code that makes the error appears to be https://github.com/apache/arrow-datafusion/blob/ba50a8b178eece7e79b100d0b73bdc9d6d3ec6d5/datafusion/physical-plan/src/analyze.rs#L119

I suspect this is only a datafusion-cli issue, and that it started happening after https://github.com/apache/arrow-datafusion/pull/8651 from @berkaysynnada  (which now checks 'unbounded output')

**Comment by berkaysynnada** [comment]
Should we remove the panic in `unbounded_output()` and simply reflect its input plan's unboundedness in AnalyzeExec?

**Comment by alamb** [comment]
> Should we remove the panic in `unbounded_output()` and simply reflect its input plan's unboundedness in AnalyzeExec?

Yes, I think that would be the best solution.  I think returning `Ok(false)` is probably the easiest fix.
