### ISSUE TITLE
Windows CI test is extremely long (~3 hours)

### ISSUE THREAD

**Issue by Jefffrey** [apache/arrow-datafusion#8696]
### Describe the bug

Some examples:

- https://github.com/apache/arrow-datafusion/actions/runs/7369048334/job/20053938917
- https://github.com/apache/arrow-datafusion/actions/runs/7364543678/job/20045028037
- https://github.com/apache/arrow-datafusion/actions/runs/7358744456/job/20032462383

### Additional context

Not sure if it was like this in the past too? But a 3hr runtime seems odd

**Comment by Jefffrey** [comment]
From logs in https://github.com/apache/arrow-datafusion/actions/runs/7358744456/job/20032462383

```
     Running tests\tpcds_planning.rs (target\debug\deps\tpcds_planning-b7c04ff6bee7c82a.exe)
...
test result: ok. 190 passed; 0 failed; 8 ignored; 0 measured; 0 filtered out; finished in 5068.19s
```

Seems would be a good start point for investigating this, as accounts for almost half that runtime.

Skimming through the logs, can't see any other part that significantly contributes to the runtime

**Comment by Jefffrey** [comment]
CI is still taking extremely long after switching to windows-2019 runner

**Comment by Jefffrey** [comment]
Some debugging thoughts:

**Due to image change**

Unlikely.

27min runtime: https://github.com/apache/arrow-datafusion/actions/runs/7347591698/job/20004278779#step:1:1

```
Current runner version: '2.311.0'
Operating System
  Microsoft Windows Server 2022
  10.0.20348
  Datacenter
Runner Image
  Image: windows-2022
  Version: 20231217.2.0
  Included Software: https://github.com/actions/runner-images/blob/win22/20231217.2/images/windows/Windows2022-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20231217.2
Runner Image Provisioner
  2.0.321.1
```

3hr 20min run: https://github.com/apache/arrow-datafusion/actions/runs/7351057731/job/20013780063#step:1:1

```
Current runner version: '2.311.0'
Operating System
  Microsoft Windows Server 2022
  10.0.20348
  Datacenter
Runner Image
  Image: windows-2022
  Version: 20231217.2.0
  Included Software: https://github.com/actions/runner-images/blob/win22/20231217.2/images/windows/Windows2022-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20231217.2
Runner Image Provisioner
  2.0.321.1
```

Runner image versions are the exact same.

**Some regression in Datafusion code**

Probably unlikely? I don't have a Windows machine to test to be certain that it's not only CI.

Given example run: https://github.com/apache/arrow-datafusion/actions/runs/7390088229/job/20104324232

The tests that have extreme runtime are:

- sqllogictests
  - https://github.com/apache/arrow-datafusion/actions/runs/7390088229/job/20104324232#step:5:5719
  - Turn on timestamps via cog wheel
  - Starts `Tue, 02 Jan 2024 21:44:15 GMT` and last log from it is `Tue, 02 Jan 2024 22:05:57 GMT` (but next test doesn't start until `Tue, 02 Jan 2024 23:27:39 GMT` leaving a 1hr 42min gap)
- tests\tpcds_planning.rs
  - https://github.com/apache/arrow-datafusion/actions/runs/7390088229/job/20104324232#step:5:2124
  - Takes about 1hr 20min

Rest of the run doesn't have any major anomalies, so these are the offending tests.

**Some other runner issue**

Not sure how to debug this, might need to raise another issue with runner repo?

**Comment by comphead** [comment]
@Jefffrey thanks for creating this, do you have windows machine to run tests locally?

**Comment by Jefffrey** [comment]
> @Jefffrey thanks for creating this, do you have windows machine to run tests locally?

I don't have access to a Windows machine easily unfortunately. Can try get access to one if necessary, will see how latest CI test pans out

**Comment by comphead** [comment]
I'm also trying to find a solution in https://github.com/apache/arrow-datafusion/pull/8730

**Comment by Jefffrey** [comment]
https://github.com/apache/arrow-datafusion/pull/8728

Windows test finished in 28min @comphead 

Looks like its due to Rust 1.75.0 upgrade, will check its changelog

**Comment by comphead** [comment]
good finding, on 1.75.0 even the compilation is way slower

**Comment by Jefffrey** [comment]
After a bunch of debugging, I found this:

Tests run fast on toolchain: nightly-2023-10-29 (rust e5cfc5547)

Tests run extremely slow on toolchain: nightly-2023-10-30 (rust 608e9682f)

I might raise an issue on rust lang repo, after checking if a similar issue hasn't already been raised

**Comment by Jefffrey** [comment]
Raised issue on Rust repo: https://github.com/rust-lang/rust/issues/119560
