### ISSUE TITLE
datafusion-cli: results of group by aggregation query not showing

### ISSUE THREAD

**Issue by Jefffrey** [apache/arrow-datafusion#8702]
### Describe the bug

datafusion-cli isn't showing results for queries involving selecting count when group by.

### To Reproduce

Given input file:

```csv
col1,col2
A,
B,b
C,c
```

Querying this file in datafusion-cli:

```
DataFusion CLI v34.0.0
❯ CREATE EXTERNAL TABLE kumachan STORED AS CSV WITH HEADER ROW LOCATION '/home/jeffrey/Downloads/kumachan.csv';
0 rows in set. Query took 0.029 seconds.

❯ select * from kumachan;
+------+------+
| col1 | col2 |
+------+------+
| A    |      |
| B    | b    |
| C    | c    |
+------+------+
3 rows in set. Query took 0.005 seconds.

❯ select count(*) from kumachan group by col1;
3 rows in set. Query took 0.010 seconds.

❯
```

### Expected behavior

Should get results like:

```
+----------+
| COUNT(*) |
+----------+
| 1        |
| 1        |
| 1        |
+----------+
```

**Comment by alamb** [comment]
Maybe some other fallout from https://github.com/apache/arrow-datafusion/pull/8651 -- I had some work in progress to try and consolidate / clean up the output code more in https://github.com/alamb/arrow-datafusion/tree/alamb/cli-cleanup but I have not finished it

**Comment by alamb** [comment]
I think this is a regression and we should try and fix it before datafusion 35 release https://github.com/apache/arrow-datafusion/issues/8863 -- cc @andygrove

**Comment by alamb** [comment]
I can try to help debug this tomorrow if no one else beats me to it

**Comment by Jefffrey** [comment]
Problem is here:

https://github.com/apache/arrow-datafusion/blob/ffaa67904ed0ca454267ccc5832582bcb669a5c0/datafusion-cli/src/print_format.rs#L164

Specifically the `batches[0].num_rows() == 0`

It seems my query will have some empty RecordBatches initially, which causes this check to completely ignore printing the rest of the potentially data-filled RecordBatches

**Comment by alamb** [comment]
Thanks @Jefffrey  -- I will make a patch

**Comment by alamb** [comment]
This appears to have been introduced in https://github.com/apache/arrow-datafusion/pull/8651

**Comment by alamb** [comment]
PR ready for review: https://github.com/apache/arrow-datafusion/pull/8895
