### ISSUE TITLE
Handle Serde for Custom `ScalarUDFImpl` traits

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#8706]
### Is your feature request related to a problem or challenge?

https://github.com/apache/arrow-datafusion/pull/8578 added a `ScalarUDFImpl` trait for implementing ScalarUDF. 

@thinkharderdev  said: https://github.com/apache/arrow-datafusion/pull/8578#issuecomment-1870338011

> Nice! It would be very useful to be able to handle serde as well for custom implementations (perhaps in a different PR?). I think this could fit relatively easily into `LogicalExtensionCodec`

**Comment by yyy1000** [comment]
I'd also like to work on this. 😃

**Comment by yyy1000** [comment]
I need some guide on this. 🤔
It seems ScalarUDF can handle Serde now, what would this PR want to implement?
https://github.com/apache/arrow-datafusion/blob/7a0af5be2323443faa75cc5876651a72c3253af8/datafusion/proto/src/logical_plan/from_proto.rs#L1818-L1826

**Comment by alamb** [comment]
Maybe @thinkharderdev  can comment -- perhaps nothing is needed?

**Comment by yyy1000** [comment]
Aha, maybe I can help other issues first. 😄

**Comment by thinkharderdev** [comment]
Hey @yyy1000 I think there is some work to do here. Currently the serialization for udf looks like 

```
                    ScalarFunctionDefinition::UDF(fun) => Self {
                        expr_type: Some(ExprType::ScalarUdfExpr(
                            protobuf::ScalarUdfExprNode {
                                fun_name: fun.name().to_string(),
                                args,
                            },
                        )),
                    },
```

eg, we just use the `name` and assume wherever it is being deserialized will just have a registry where it can look up the scalar function definition by name. 

But ideally we would be able to serialize a custom scalar function that has some sort of associated state. For example, a regex scalar function that actually contains the compiled regex in it's struct definition like:

```
struct MyRegexUdf {
   compiled_regex: Vec<u8> // just assume we have some serialization of the regex state machine here
}

impl ScalarUDFImpl for MyRegexUdf {
  fn invoke(&self, args: &[ColumnarValue]) -> Result<ColumnarValue> {
     // do something with compiled regex here
  }
}

```

Currently the mechanism that is used for this kind of thing is to define a custom `LogicalExtensionCodec`. So here I think we would add methods to that trait like 

```
impl LogicalExtensionCodec for DefaultLogicalExtensionCodec {

  fn try_encode_scalar_udf(
        &self,
        _node: Arc<dyn ScalarUdfImpl>,
        _buf: &mut Vec<u8>,
    ) -> Result<()> {
        not_impl_err!("LogicalExtensionCodec is not provided")
    };


   fn try_decode_scalar_udf(
        &self,
        _buf: &[u8],
        _ctx: &SessionContext,
    ) -> Result<Arc<dyn ScalarUDFImpl>> {
        not_impl_err!("LogicalExtensionCodec is not provided")
    }
}

```

So then I would be able to define my own UDFs that contain internal state and then define an extension codec like
```
struct MyLogicalExtensionCodec;

impl LogicalExentionCodec for MyLogicalExtensionCodec {
    fn try_encode_scalar_udf(
        &self,
        node: Arc<dyn ScalarUdfImpl>,
        buf: &mut Vec<u8>,
    ) -> Result<()> {
        if let Some(regex_udf) = node.as_any().downcast_ref::<MyRegexUdf> {
           let proto = MyRegexUdfProto {
             compiled_regex: regex.compiled_regex.clone()
           }

           proto.encode(buf)?;

           Ok(())
        } else {
           not_impl_err!("LogicalExtensionCodec is not provided")
        }
    }; 

   fn try_decode_scalar_udf(
        &self,
        buf: &[u8],
        _ctx: &SessionContext,
    ) -> Result<Arc<dyn ScalarUDFImpl>> {
        if let Ok(proto) = MyRegexUdfProto::decode(buf) {
           Ok(Arc::new(MyRegexUdf { compiled_regex: proto.compiled_regex)))
        } else {
           not_impl_err!("LogicalExtensionCodec is not provided")
        }
    }

}

```

However, this doesn't play very nicely with how the serde is currently defined because we have no way to get a `LogicalExtensionCodec` in our `impl TryFrom<&Expr> for protobuf::LogicalExprNode` which we would need

**Comment by thinkharderdev** [comment]
Perhaps this could be incorporated into `FunctionRegistry` and we have a `serialize_expr(expr: &Expr, registry: &dyn FunctionRegistry)` similar to how we do the deserialization?

**Comment by yyy1000** [comment]
@thinkharderdev Much appreciated! I understand the issue now.
Another question is there some example code for `deserialization` so that I can refer to them to think how to write `serialize_expr` function?

**Comment by thinkharderdev** [comment]
> @thinkharderdev Much appreciated! I understand the issue now. Another question is there some example code for `deserialization` so that I can refer to them to think how to write `serialize_expr` function?

Hey @yyy1000, looking at this a bit and I think what we want here is:

1. Have `ScalarUDFExprNode` take an optional opaque payload to potentially contain the serialized function:
```
message ScalarUDFExprNode {
  string fun_name = 1;
  repeated LogicalExprNode args = 2;
  optional bytes fun_definition = 3;
}
```

Would do a similar thing for `AggregateUDFExprNode` and `WindowExprNode`

2. Add a new trait to shim in custom function serialization
```
pub trait FunctionExtensionCodec: Debug + Send + Sync {
    fn try_decode_udf(
        &self,
        name: &str,
        buf: &[u8],
    ) -> Result<Arc<ScalarUDF>>;

    fn try_encode_udf(&self, node: &ScalarUDF, buf: &mut Vec<u8>) -> Result<()>;

    fn try_decode_udaf(
        &self,
        name: &str,
        buf: &[u8],
    ) -> Result<Arc<AggregateUDF>>;

    fn try_encode_udaf(&self, node: &AggregateUDF, buf: &mut Vec<u8>) -> Result<()>;

    fn try_decode_udwf(
        &self,
        name: &str,
        buf: &[u8],
    ) -> Result<Arc<WindowUDF>>;

    fn try_encode_udwf(&self, node: &WindowUDF, buf: &mut Vec<u8>) -> Result<()>;
}
```

This trait should have a default implementation which just returns a `NotImplmented` error (similar to `DefaultLogicalExtensionCodec`)

3. Modify the `FunctionRegistry` to allow registering a custom function codec

```
pub trait FunctionRegistry {
  ... current methods remain unchanged

  fn register_extension_codec(&self, codec: Arc<dyn FunctionExtensionCodec>);

  fn extension_codec(&self) -> &dyn FunctionExtensionCodec;

}
```

4. Replace `impl TryFrom<&Expr> for protobuf::LogicalExprNode` with a free function
```
pub fn serialize_expr(expr: &Expr, registry: &dyn FunctionRegistry) -> Result<protobuf::LogicalExprNode> {
   ...
}
```

This would be mostly unchanged from the existing `TryFrom` implementation except for handling of `Expr::ScalarFunction/AggregateFunction/WindowFunction`. We would handle `Expr::ScalarFunction` something like:

```
            Expr::ScalarFunction(ScalarFunction { func_def, args }) => {
                let args = args
                    .iter()
                    .map(|expr| expr.try_into())
                    .collect::<Result<Vec<_>, Error>>()?;
                match func_def {
                    ScalarFunctionDefinition::BuiltIn(fun) => {
                        let fun: protobuf::ScalarFunction = fun.try_into()?;
                        Self {
                            expr_type: Some(ExprType::ScalarFunction(
                                protobuf::ScalarFunctionNode {
                                    fun: fun.into(),
                                    args,
                                },
                            )),
                        }
                    }
                    ScalarFunctionDefinition::UDF(fun) => {
                        let mut buf = Vec::new();
                        registry.extension_codec.try_encode_udf(fun.as_ref(), &mut buf)?;

                        let fun_definition = if buf.is_empty() {
                            None
                        } else {
                            Some(buf)
                        };

                        Self {
                            expr_type: Some(ExprType::ScalarUdfExpr(
                                protobuf::ScalarUdfExprNode {
                                    fun_name: fun.name().to_string(),
                                    fun_definition,
                                    args,
                                },
                            )),
                        }
                    },
                    ScalarFunctionDefinition::Name(_) => {
                        return Err(Error::NotImplemented(
                    "Proto serialization error: Trying to serialize a unresolved function"
                        .to_string(),
                ));
                    }
                }
            }

```

4. Similarly, in existing `parse_expr` we try and use the extension codec to deserialize the function if `fun_definition` is present:
```
pub fn parse_expr(
    proto: &protobuf::LogicalExprNode,
    registry: &dyn FunctionRegistry,
) -> Result<Expr, Error> {
  ... handling of other expr types unchanged
  
  ExprType::ScalarUdfExpr(protobuf::ScalarUdfExprNode { fun_name, fun_definition, args }) => {
  
     let scalar_fn = match fun_definition {
        Some(buf) => registry.extension_codec().try_decode_udf(&fun_name, &buf)?,
        None => registry.udf(fun_name.as_str())?,
     };
      Ok(Expr::ScalarFunction(expr::ScalarFunction::new_udf(
            scalar_fn,
            args.iter()
                    .map(|expr| parse_expr(expr, registry))
                    .collect::<Result<Vec<_>, Error>>()?,
            )))
     }

}
```

If you don't have bandwidth now to work on this let me know, My team can take this up as we are hoping to be able to use this functionality soon.

**Comment by thinkharderdev** [comment]
ah, also we would need to provide `$dyn FunctionRegistry` to `AsLogicalPlan::try_from_logical_plan` and `AsExecutionPlan::try_from_physical_plan`

**Comment by yyy1000** [comment]
Thanks so much for your detailed instructions! @thinkharderdev 
I can try to implement it now and will seek your help if needed :)

**Comment by yyy1000** [comment]
A question I have is, replace Replace `impl TryFrom<&Expr> for protobuf::LogicalExprNode` with a free function may lead a lot of places like `expr.try_into()` to `serialize_expr(expr, codec)`, would this be OK for the code base? @thinkharderdev

**Comment by thinkharderdev** [comment]
> A question I have is, replace Replace `impl TryFrom<&Expr> for protobuf::LogicalExprNode` with a free function may lead a lot of places like `expr.try_into()` to `serialize_expr(expr, codec)`, would this be OK for the code base? @thinkharderdev

Yeah I think so. @alamb do you see any issues with that?

**Comment by yyy1000** [comment]
Also I wonder how to deal with some other places which don't need a `LogicalExtensionCodec` like `to_bytes`
https://github.com/apache/arrow-datafusion/blob/c439bc73b6a9ba9efa4c8a9b5d2fb6111e660e74/datafusion/proto/src/bytes/mod.rs#L87-L92. I think add a param of type `LogicalExtensionCodec` to the function will work, and what to do when calling this method, should I initialize a impl `LogicalExtensionCodec`? 🤔
