### ISSUE TITLE
Implement trait based API for defining `WindowUDF`

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#8711]
Similarly to https://github.com/apache/arrow-datafusion/issues/8568

### Is your feature request related to a problem or challenge?

The current way a user implements a [WindowUDF](https://docs.rs/datafusion/latest/datafusion/logical_expr/struct.WindowUDF.html#) is awkward and very hard to extend in backwards compatible ways:

They must wade through several `Arc<dyn<...>` typedefs to figure out how to provide the type signature and implementation

```rust
impl WindowUDF {

/// Create a new WindowUDF 
pub fn new(
    name: &str,
    signature: &Signature,
    return_type: &Arc<dyn Fn(&[DataType]) -> Result<Arc<DataType>, DataFusionError> + Send + Sync>,
    partition_evaluator_factory: &Arc<dyn Fn() -> Result<Box<dyn PartitionEvaluator>, DataFusionError> + Send + Sync>
) -> WindowUDF
```

### Describe the solution you'd like

Follow the pattern in https://github.com/apache/arrow-datafusion/pull/8578

1. Create a `WindowUDFImpl` trait, and `WindowUDF::new_from_impl` that creates an `WindowUDF` from the impl
2. Add an example in `datafusion-examples/examples/advanced_udwf.rs` of using this API

I am not sure why this API is implemented like it is (other than it was consistent with `ScalarUDF`). As a user I would expect to be able to use a trait object like this

like

```rust
struct MyWindowFunction { 
..
}

impl WindowUDFImpl for MyWindowFunction {
  fn name(&self) -> &str, 
  fn return_type(&self) -> &DataType, 
...
}
```

**Comment by guojidan** [comment]
I will try to implement this
