### ISSUE TITLE
Clean internal implementation of ScalarUDF to use `ScalarUDFImpl` (rather than the function pointers)

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#8712]
### Is your feature request related to a problem or challenge?

Follow on to https://github.com/apache/arrow-datafusion/pull/8578 / https://github.com/apache/arrow-datafusion/issues/8568

### Describe the solution you'd like

Basically now that we have a trait object based way of defining UDFs the internal function pointer implementation is awkward and unecessary. We could use the trait object directly as discussed in https://github.com/apache/arrow-datafusion/pull/8578/files#r1430521000

**Comment by istvan-fodor** [comment]
Hi @alamb, any ideas when this feature will be release? I am working on a project with a lot of need to custom UDFs and would be awesome to use the new API.  

Thank you!

**Comment by alamb** [comment]
> Hi @alamb, any ideas when this feature will be released? I am working on a project with a lot of custom UDFs and it would be awesome to use the new API.
> 
> Thank you!

I believe @andygrove  plans to do so soon -- https://github.com/apache/arrow-datafusion/issues/8863 tracks the release that will have this feature
