### ISSUE TITLE
Clean internal implementation of WindowUDF to use WindowUDFImpl (rather than the function pointers)

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#8734]
### Is your feature request related to a problem or challenge?

Similiarly to https://github.com/apache/arrow-datafusion/issues/8712  (see the rationale there)

@guojidan made a trait for creating WindowUDFs (thank you!) -- https://github.com/apache/arrow-datafusion/pull/8719 but the existing `WindowUDF` struct still uses function pointers for implementation. 

### Describe the solution you'd like

I would like to apply the same basic pattern as in https://github.com/apache/arrow-datafusion/pull/8713 to `WindowUDF` so that the implementation of `WindowUDF` is an `inner: Arc<WindowUDFImpl>` rather than

**Comment by guojidan** [comment]
I will deal this issue 😄
