### ISSUE TITLE
Add http(s) support to the cli

### ISSUE THREAD

**Issue by kcolford** [apache/arrow-datafusion#8752]
### Is your feature request related to a problem or challenge?

It's low hanging fruit that counterparts like duckdb already support so we might as well.

### Describe the solution you'd like

Just integrate with https://docs.rs/object_store/0.8.0/object_store/http/index.html to get this functionality

### Describe alternatives you've considered

none considered

### Additional context

This issue was opened in respose to the PR template asking for all PRs to include an issue. This was really just a change I made to make something possible for myself so I'm upstreaming it for others to enjoy as well.

**Comment by alamb** [comment]
This feature has a PR https://github.com/apache/arrow-datafusion/pull/8753 that just needs a few tests and docs and it will be good to merge. It would make a good issue for someone to help with
