### ISSUE TITLE
Use correct attribution in footer of documentation pages

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#8755]
### Is your feature request related to a problem or challenge?

To be inline with ASF policy, we should update the text in the footer used in the docs (e.g. https://arrow.apache.org/datafusion/) to match the footer used in the main website (https://arrow.apache.org/). i.e. add the trademark attribution test.

This applies to docs for DataFusion, the Python bindings, and Ballista

**Comment by alamb** [comment]
I will take a shot at doing this

**Comment by alamb** [comment]
I filed https://github.com/apache/arrow-datafusion/pull/8760 for DataFusion and I filed seprate tickets for the subprojects (and linked them back to the main epic https://github.com/apache/arrow/issues/39462)

- [ ] https://github.com/apache/arrow-datafusion-python/issues/553 (DataFusion Python)
- [ ] https://github.com/apache/arrow-ballista/issues/950 (Ballista)
- [ ] https://github.com/apache/arrow-ballista-python/issues/64 (Ballista Python)
