### ISSUE TITLE
Implement monotonicity for ScalarUDF

### ISSUE THREAD

**Issue by guojidan** [apache/arrow-datafusion#8756]
### Is your feature request related to a problem or challenge?

part of #8045 .

Now `ScalarUDF` is not supported `monotonicity` -- this means that certain sort related optimizations can not be applied to expressions that use ScalarUDF.

### Describe alternatives you've considered

I think `ScalarUDF's` monotonicity should defined by User-self, so we can add `monotonicity` function for `ScalarUDFImpl` trait, like this:
```
pub trait ScalarUDFImpl {
    fn monotonicity() -> Result<Option<FuncMonotonicity>> {
        Ok(None)
    }
}
```

**Comment by guojidan** [comment]
cc @alamb, Is there any mistake in my understanding? if not I will implement this.

**Comment by alamb** [comment]
> cc @alamb, Is there any mistake in my understanding? if not I will implement this.

Thank you @guojidan  -- I agree this looks good. I also added it to the tracking epic in https://github.com/apache/arrow-datafusion/issues/8045
