### ISSUE TITLE
Support stride for `array_slice`

### ISSUE THREAD

**Issue by Weijun-H** [apache/arrow-datafusion#8784]
### Is your feature request related to a problem or challenge?

Currently, the `array_slice` function only accepts three arguments: the `array`, `from`, and `to`. However, it would be more convenient if it also supported a `stride` parameter.

Expect result
```
array_slice([1, 2, 3, 4], 1, 3, 2) --> [1, 3]
```

**Comment by Weijun-H** [comment]
I will work on this ticket.

**Comment by alamb** [comment]
I wonder if there is any other database system that has array_slice and that we can use as a prototype for our syntax and function support?

**Comment by Weijun-H** [comment]
> I wonder if there is any other database system that has array_slice and that we can use as a prototype for our syntax and function support?

In DuckDB, it has `list_slice(list, begin, end, step)` @alamb
