### ISSUE TITLE
Create new logo for Apache DataFusion

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#8788]
### Is your feature request related to a problem or challenge?

We anticipate that DataFusion will become a top-level ASF project, named "Apache DataFusion". Our current logo contains the word "DataFusion" and has no Apache affiliation.

### Describe the solution you'd like

We should design a new logo. Source files for our current logo can be found at https://github.com/apache/arrow-datafusion/tree/main/docs/logos

**Comment by andygrove** [comment]
Here is one proposal for the new logo.

![Screenshot from 2024-01-08 09-32-25](https://github.com/apache/arrow-datafusion/assets/934084/271eda16-17d3-4bd9-9e1a-9f1d0acd8bb5)

**Comment by alamb** [comment]
I think we also need to have a (TM) somewhere, for example how Spark does it:
![image](https://github.com/apache/arrow-datafusion/assets/490673/9ccdeaea-83f1-41d6-b3bd-1ccb7b34720c)

**Comment by andygrove** [comment]
Here is an updated version with the trademark symbol and fixing a small alignment issue.

![image](https://github.com/apache/arrow-datafusion/assets/934084/31e548cb-c9bd-4020-bce6-54aa1d0a4d04)

**Comment by andygrove** [comment]
I've also requested a version of this that has APACHE ARROW on the top line that we could use until the project moves.

**Comment by ozankabak** [comment]
I will ask our designer to come up with a bunch of logos and post them here today

**Comment by ozankabak** [comment]
Here are [a few candidate logos](https://www.figma.com/file/cEknMqk4KTILMOk0PArGxJ/Datafusion-New-Logo-Ideas?type=whiteboard&node-id=0%3A1&t=BK5f5GfB9O8oulTq-1) that are in tune with the original logo. You can log in to Figma via Google to leave comments there, or can just drop a note here. We can create variations of these based on suggestions or add other new candidates based on original ideas from the community.

**Comment by alamb** [comment]
They all look good to me (I have no preference). Let's see if anyone else offers an opinion

**Comment by ozankabak** [comment]
These are the variations on the top two logos (with and without arrow symbol):
![Datafusion Logo with 3 orbits and arrow](https://github.com/apache/arrow-datafusion/assets/2006258/2bed8883-48b6-4712-aa2e-d0ab8af365c9)
![Datafusion Logo with 3 orbits](https://github.com/apache/arrow-datafusion/assets/2006258/e5b90770-e047-402a-8853-3acc0a4d799e)
![Datafusion Logo with 2 orbits](https://github.com/apache/arrow-datafusion/assets/2006258/829d889f-daa5-458b-9279-3e11a08e3db0)
![Datafusion Logo with 2 orbits and arrow](https://github.com/apache/arrow-datafusion/assets/2006258/9b09c3df-59b1-4c17-be08-8171cdead72f)

**Comment by andygrove** [comment]
Just my view, but the logo with the Arrow >>> symbol seems a bit busy. I am not sure that we should include this design element.

**Comment by ozankabak** [comment]
> Just my view, but the logo with the Arrow >>> symbol seems a bit busy. I am not sure that we should include this design element.

Agreed. Seems like second variation is the leading candidate for now then

**Comment by maruschin** [comment]
Additional variations: [figma link](https://www.figma.com/file/lCwbd4HqkvwabL2e3ErSvn/Datafusion-logo?type=design&node-id=0%3A1&mode=design&t=F5F8L48dRU28lE9z-1).

![Datafusion logo](https://github.com/apache/arrow-datafusion/assets/678620/cb35f871-d0db-4cab-89b4-845378b66065)

**Comment by alamb** [comment]
I like the meatball ![Screenshot 2024-01-21 at 8 14 51 AM](https://github.com/apache/arrow-datafusion/assets/490673/2c534930-ac9f-4cc9-90c3-cb6f6956734d)

Reminds me of the [Plum Pudding Model of the Atom](https://en.wikipedia.org/wiki/Plum_pudding_model)

**Comment by metesynnada** [comment]
If the designs outside of the nuclear context of "fusion" could also be considered, maybe we can explore options beyond nuclear fusion. What do you think, @alamb?

**Comment by alamb** [comment]
> If the designs outside of the nuclear context of "fusion" could also be considered, maybe we can explore options beyond nuclear fusion. What do you think, @alamb?

Sounds good to me. I really don't have a strong opinion in this area

What I recommend for consensus is that someone who is willing to "rebrand" the project (aka go update the logo in the documentation) propose a specific new logo (perhaps via a PR to update the logo). Then we'll review that PR (and we can send a note to the mailing list for extra visibility) and when it merges the project logo would be updated

**Comment by pinarbayata** [comment]
Hello, I’m Pınar, the Founding Designer at Synnada, collaborating with @ozankabak. I’ve explored three themes for DF: futuristic, modern, and generic. I’ve started with a monochrome design and will incorporate typography and color in the next iterations. Feel free to select your favorite theme and logo by specifying the number.![image](https://github.com/apache/arrow-datafusion/assets/32200755/041b6b04-84be-4f7d-ad9a-e69ed3d85471)![image](https://github.com/apache/arrow-datafusion/assets/32200755/fbf35e5b-112b-4fee-8aae-6dec1789357d)![image](https://github.com/apache/arrow-datafusion/assets/32200755/6c1c860c-0421-422a-b090-b341f5b7d14c)

**Comment by alamb** [comment]
Thanks @pinarbayata  -- I have sent a note around to slack and discord asking the broader community for feedback so hopefully we'll get some more comments here

**Comment by avantgardnerio** [comment]
Thank you! I love them. I'd vote for any of the ones with the plan on the atom.

**Comment by wjones127** [comment]
> I like the meatball ![](https://private-user-images.githubusercontent.com/490673/298384950-2c534930-ac9f-4cc9-90c3-cb6f6956734d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMjEyMjcsIm5iZiI6MTcwNjEyMDkyNywicGF0aCI6Ii80OTA2NzMvMjk4Mzg0OTUwLTJjNTM0OTMwLWFjOWYtNGNjOS05MGMzLWNiNmY2OTU2NzM0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNFQxODI4NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYjRhMTZlN2Q4OWMyN2Q4ZjZhMmI0MWI2YzJmMjJkZTI5ZWFlNGM4ZWU2NDE5NTFlYzNhY2UzYjVjNWYxZjYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YESpAaJ8wzypCvCe8KJem6nc_ZbFFlFj3WGvs2loMHE)

I too like "the meatball" (🤣).  It keeps with the atomic theme but is visually distinct from a similar project, Velox:

![Velox logo with atom](https://dbdb.io/media/logos/velox.svg)


Though options 12 and 6 of the black + white images are quite good too

**Comment by andygrove** [comment]
Thanks @pinarbayata! These look really great. We will need to add a TM trademark symbol and I think it is important that the word "Apache" appears before DataFusion since the trademark is for "Apache DataFusion".

**Comment by philippemnoel** [comment]
I would cast my vote for having "datafusion" on the same line. I think 16, and 6 are my favorites

**Comment by pinarbayata** [comment]
Hello again, after the first round of logo discussions and feedback, we have been able to narrow down to a few finalists. These designs have been refined and improved, and now we're looking for your input once again. Please feel free to share your thoughts, and let us know your top picks.
![Finalists](https://github.com/apache/arrow-datafusion/assets/32200755/4152d6df-0ef8-4de0-b316-196c15a36cac)

**Comment by matthewmturner** [comment]
My vote is for 7 :)

**Comment by liurenjie1024** [comment]
I would vote for  3

**Comment by ozankabak** [comment]
I like 3 too

**Comment by jayzhan211** [comment]
vote for 7

**Comment by Omega359** [comment]
#7 is my preference.

**Comment by delsehi** [comment]
I like 3 😍

**Comment by andygrove** [comment]
I like 3, 6, and 7 the most.

**Comment by andygrove** [comment]
It looks like 3 is leading, with 7 being a close second.

**Comment by andygrove** [comment]
@pinarbayata Is it possible to see a version of 3 with a white background, or would that just be 6?

**Comment by pinarbayata** [comment]
Sure here it is
![datafusion_3](https://github.com/apache/arrow-datafusion/assets/32200755/924f8477-873f-45c9-8721-82ae4cca3f80)

**Comment by pinarbayata** [comment]
Hi everyone, thank you all for your feedback. The finalists are options 3 and 7. Now, it's time for the final round of voting to choose your top pick. Below are the two most popular versions, each with different color variations. The numbers correspond to each column. Please take a moment to review them and cast your vote.
![iteration1](https://github.com/apache/arrow-datafusion/assets/32200755/581774da-948c-4d34-9872-70b43aa66337)
![iteration2](https://github.com/apache/arrow-datafusion/assets/32200755/314b8c6f-000a-404a-bc3d-f1530aabf350)

**Comment by Omega359** [comment]
I'm partial to orange for some reason so #4 then #7

**Comment by metesynnada** [comment]
1

**Comment by leoyvens** [comment]
5

**Comment by slyons** [comment]
Nth-ing 5, but I like the colours in 8

**Comment by andygrove** [comment]
5

**Comment by jayzhan211** [comment]
5

**Comment by liurenjie1024** [comment]
3

**Comment by pinarbayata** [comment]
Hi everyone, thank you all for voting. I have noticed that the first set of variations was missing logomarks, unlike the second set. This was unfair, so I have edited my comment to include logomarks for the first set (see third row). If this change impacts your vote, I kindly request you to adjust it accordingly. I apologize for any confusion caused.

**Comment by matthewmturner** [comment]
5

**Comment by ozankabak** [comment]
Seeing the logomarks I like 1 (followed by 3)

**Comment by matthewmturner** [comment]
btw thank you for the work on this @pinarbayata all the designs are great

**Comment by comphead** [comment]
@pinarbayata is this possible to get most favorable logs and then have 1 post per logo, so people can put likes under each of them? Later it would be easy to calculate

**Comment by sunchao** [comment]
6

Looking forward to some DataFusion stickers in future!

**Comment by viirya** [comment]
2

**Comment by Jefffrey** [comment]
3

**Comment by alamb** [comment]
7

**Comment by comphead** [comment]
Thanks @pinarbayata 
I like 7

**Comment by Weijun-H** [comment]
vote for 3
Thanks, @pinarbayata, remarkable work!

**Comment by pinarbayata** [comment]
Hi everyone, voting ends on Sunday at 12:00 PM in San Francisco Time. I will announce the finalists afterwards.

**Comment by mustafasrepo** [comment]
1

**Comment by pinarbayata** [comment]
Hi again, the voting has officially ended 🎊 and the finalist is number 5:
![finalist](https://github.com/apache/arrow-datafusion/assets/32200755/ba3bbad2-56f7-4113-b40b-07b2a45db74c)
I will open a PR and continue the branding process from there.
