### ISSUE TITLE
Documenting building with simd feature

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#882]
**Describe the bug**
```
~/release/apache-arrow-datafusion-5.0.0 via 🦀 v1.54.0 
✦ ❯ cargo build --release --features "simd"
   Compiling packed_simd_2 v0.3.5
error[E0554]: `#![feature]` may not be used on the stable release channel
   --> /home/andy/.cargo/registry/src/github.com-1ecc6299db9ec823/packed_simd_2-0.3.5/src/lib.rs:214:1
    |
214 | / #![feature(
215 | |     const_generics,
216 | |     repr_simd,
217 | |     rustc_attrs,
...   |
227 | |     llvm_asm
228 | | )]
    | |__^

```

**To Reproduce**
Run command above.

**Comment by andygrove** [comment]
I am probably doing something wrong and/or we need better docs around this

**Comment by jorgecarleitao** [comment]
I think you need the nightly channel to use simd, as packed_simd requires
nightly.

**Comment by alamb** [comment]
`cargo +nightly build --release --features "simd"`

**Comment by Dandandan** [comment]
I changed the issue to add some docs around this.

Btw, @andygrove AFAIK the SIMD option doesn't help a lot with the TPC-H queries. Building with snmalloc or mimalloc and fat LTO (longer build time) does improve execution times.

**Comment by houqp** [comment]
It would be good if we can provide doc on how to produce the most optimized build: simd + snmalloc + LTO.

**Comment by alamb** [comment]
I also think we should suggest building with `native` and/or at least `avx2` instructions (by default my `rustc` only used sse/sse2, presumably for compatibility)

**Comment by Dandandan** [comment]
Here is an example of using all the options:

https://github.com/h2oai/db-benchmark/pull/182/files

**Comment by matthewmturner** [comment]
Hello.  I could try this.  To confirm - is the idea to add docs just for SIMD? Or for the most optimized build?

**Comment by houqp** [comment]
I would love to have docs for the most optimized build, but we can start with SIMD if that's too much :)
