### ISSUE TITLE
Add documentation to datafusion-substrait crate about what it does

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#8820]
### Is your feature request related to a problem or challenge?

The documentation for the datafusion-substrait crate is pretty much non existent which makes it hard for users to know what it does and how to use it

https://docs.rs/datafusion-substrait/latest/datafusion_substrait/#

### Describe the solution you'd like

I would like documentation like datafusion-proto that gives an example and describes what datafusion substrait can be used for

https://docs.rs/crate/datafusion-proto/latest

**Comment by alamb** [comment]
I think this is a good first issue as there is an example of how to make it in datafusion-proto

**Comment by caicancai** [comment]
I want to try it but it might take me a little time because I don't know the use of datafusion-substrait either

**Comment by caicancai** [comment]
![Screenshot_29](https://github.com/apache/arrow-datafusion/assets/77189278/da0bc640-d281-4fb9-9afb-b36322aee236)
Hello, I found some bad links but I'm not sure how to fix them properly, one is https://crates.io/crates/datafusion-proto and one is https://github.com/apache/arrow -datafusion/blob/HEAD/datafusion/proto/examples/expr_serde.rs

**Comment by caicancai** [comment]
https://crates.io/crates/datafusion-proto/examples
There is no such link

**Comment by caicancai** [comment]
> 
> 🤔 https://crates.io/crates/datafusion-proto works for me
> 
> And when I click on the examples link I see
> 
> https://github.com/apache/arrow-datafusion/blob/HEAD/datafusion/proto/examples/expr_serde.rs
> 
> Maybe we need to move the examples into `lib.rs` so it shows up in rustdoc 🤔

Can you let me try him?

**Comment by caicancai** [comment]
@alamb Hello, excuse me. I would like to ask where lib.rs is located

**Comment by alamb** [comment]
> @alamb Hello, excuse me. I would like to ask where lib.rs is located

I am referring to https://github.com/apache/arrow-datafusion/blob/main/datafusion/proto/src/lib.rs

The documentation on crates.io https://crates.io/crates/datafusion-proto can be generated locally with a command like

```shell
cargo doc -p datafusion-proto --open
```

**Comment by caicancai** [comment]
> > @alamb Hello, excuse me. I would like to ask where lib.rs is located
> 
> I am referring to https://github.com/apache/arrow-datafusion/blob/main/datafusion/proto/src/lib.rs
> 
> The documentation on crates.io https://crates.io/crates/datafusion-proto can be generated locally with a command like
> 
> ```shell
> cargo doc -p datafusion-proto --open
> ```

let me try it

**Comment by caicancai** [comment]
I am very sorry that I have been busy with work recently. I will start this part of work

**Comment by caicancai** [comment]
@alamb Hello, excuse me. Do I need to move the test samples here?
https://github.com/apache/arrow-datafusion/blob/main/datafusion/proto/src/lib.rs

**Comment by alamb** [comment]
> @alamb Hello, excuse me. I need to move the test sample here, I don’t remember it clearly, I’m very sorry. https://github.com/apache/arrow-datafusion/blob/main/datafusion/proto/src/lib.rs

I don't think any movement is needed.

Basically the goal of this ticket is to make https://docs.rs/datafusion-proto/latest/datafusion_proto/ better explain what the crate is for and provide an example of encoding/decoding `LogicalPlan` and `ExecutionPlan`

The content of https://docs.rs/datafusion-proto/latest/datafusion_proto/ can be previewed locally using

```
cargo doc -p datafusion-proto --open
```

Does that make sense @caicancai ?

**Comment by alamb** [comment]
For an example, you can probably adapt one of the existing tests in datafusion-proto -- perhaps 

https://github.com/apache/arrow-datafusion/blob/9d1502bce08172a3501524fb3ef4754af3cf98b6/datafusion/proto/tests/cases/roundtrip_logical_plan.rs#L275-L282

**Comment by alamb** [comment]
> @alamb Hello, excuse me. I need to move the test sample here, I don’t remember it clearly, I’m very sorry. https://github.com/apache/arrow-datafusion/blob/main/datafusion/proto/src/lib.rs

I don't think any movement is needed.

Edit I was confused


Basically the goal of this ticket is to make these two pages better:
1.  https://docs.rs/datafusion-substrait/latest/datafusion_substrait/#
2. https://crates.io/crates/datafusion-substrait

Following the model of
1. https://crates.io/crates/datafusion-proto
2. https://docs.rs/datafusion-proto/latest/datafusion_proto/


Now that I review those pages, however, it seems like they could be improved substantially. I may try to take a shot at this myself

**Comment by caicancai** [comment]
> > @alamb Hello, excuse me. I need to move the test sample here, I don’t remember it clearly, I’m very sorry. https://github.com/apache/arrow-datafusion/blob/main/datafusion/proto/src/lib.rs
> 
> I don't think any movement is needed.
> 
> Edit I was confused
> 
> Basically the goal of this ticket is to make these two pages better:
> 
>     1. https://docs.rs/datafusion-substrait/latest/datafusion_substrait/#
> 
>     2. https://crates.io/crates/datafusion-substrait
> 
> 
> Following the model of
> 
>     1. https://crates.io/crates/datafusion-proto
> 
>     2. https://docs.rs/datafusion-proto/latest/datafusion_proto/
> 
> 
> Now that I review those pages, however, it seems like they could be improved substantially. I may try to take a shot at this myself

Thank you for your patient reply, then I will start working on this issue, thank you

**Comment by caicancai** [comment]
Looks like it'll take some time for me

**Comment by alamb** [comment]
Thanks for trying and being so communicative @caicancai - I'll put it on my own list

**Comment by alamb** [comment]
Here is a PR: https://github.com/apache/arrow-datafusion/pull/9260
