### ISSUE TITLE
Test failure in sqllogictest `aggregates_topk.slt` on mac

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#8845]
### Describe the bug

sqllogic
```
External error: query result mismatch:
[SQL] select trace_id, other, MIN(timestamp) from traces group by trace_id, other order by MIN(timestamp) asc limit 4;
[Diff] (-expected|+actual)
    a -1 -1
    b 0 0
    NULL 0 0
-   c 1 1
+   a 1 1
at test_files/aggregate.slt:2566
```

### To Reproduce

I run this on my Mac M3:

```
cargo test --test sqllogictests
```

### Expected behavior

The test should pass

**Comment by mustafasrepo** [comment]
What about changing timestamp field in the table so that, it is unique (hence `order by MIN(timestamp)` will be deterministic. Given that groups are distinct).

**Comment by mustafasrepo** [comment]
> What about changing timestamp field in the table so that, it is unique (hence `MIN(timestamp)` will generate different results for each different distinct group).

Filed a mini [PR8993](https://github.com/apache/arrow-datafusion/pull/8993) implementing this suggestion. It will be nice if you have time to double check whether result is indeed deterministic.
