### ISSUE TITLE
Update datafusion-cli to support Ballista, or implement new ballista-cli

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#886]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
The DataFusion CLI is very handy for demos and testing. It would be nice if we had a similar capability for Ballista.

**Describe the solution you'd like**
I would like a CLI that works with Ballista.

**Describe alternatives you've considered**
Add Ballista support to datafusion-cli, or create a new ballista-cli crate.

**Additional context**
N/A

**Comment by alamb** [comment]
I think a single CLI would be the best as it reduces the number of crates to keep track of (for users and contributors) as well as makes the close connection of ballista/datafusion apparent.

If we are worried (as I am sometimes) about an unreasonable  number of additional dependencies, we could add a `ballista` rust feature to the `datafusion-cli` to conditionally include ballista
