### ISSUE TITLE
Please update the ring crate to 17.x

### ISSUE THREAD

**Issue by yurivict** [apache/arrow-datafusion#8872]
### Describe the bug

This is needed to prevent failures like [this](https://github.com/briansmith/ring/issues/1904).

**Comment by alamb** [comment]
DataFusion doesn't appear to have a direct dependency on ring -- it does use `object_store` which has a dependency on ring. However, that crate already depends on 0.17

https://crates.io/crates/object_store/0.9.0/dependencies
https://crates.io/crates/object_store/0.8.0/dependencies

Thus I am not sure what this specific request is for. If you can be more specific about what needs to be changed in datafusion please let us know

**Comment by yurivict** [comment]
When cargo pulled dependencies for the version 34.0.0 it pulled these 2:
```
                ring-0.16.20 \
                ring-0.17.7 \
```

So ring-0.16.20 is somewhere in the dependency tree.

**Comment by alamb** [comment]
Can you please provide your Cargo.toml file ?

I tried adding datafusion 34 locally as a dependency and I do not see these dependencies, so I probably don't have the same configuration

```
(venv) andrewlamb@Andrews-MacBook-Pro:~/Software/df_test$ cat Cargo.toml
[package]
name = "df_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
datafusion = "34.0.0"

(venv) andrewlamb@Andrews-MacBook-Pro:~/Software/df_test$ cargo update
    Updating crates.io index
(venv) andrewlamb@Andrews-MacBook-Pro:~/Software/df_test$ grep ring Cargo.lock
 "arrow-string",
name = "arrow-string"
```

**Comment by jonahgao** [comment]
I can find it in my local aged repository, and the branch is also 34.0.0.
`cargo tree` shows the following result: 
```sh
├── object_store v0.9.0
│   ├── reqwest v0.11.18
│   │   ├── hyper-rustls v0.24.1
│   │   │   ├── rustls v0.21.6
│   │   │   │   ├── ring v0.16.20
```

I think the simplest fix might be to run `cargo update`.
```sh
$ cargo update
Updating rustls v0.21.6 -> v0.21.10
Removing ring v0.16.20
Adding ring v0.17.7
```

**Comment by tustvold** [comment]
Closing this, as it doesn't appear to require changes to DataFusion
