### ISSUE TITLE
Shouldn't extract common sub expression for  short-circuited operation.

### ISSUE THREAD

**Issue by haohuaijin** [apache/arrow-datafusion#8874]
### Describe the bug

As @jackwener said in https://github.com/apache/arrow-datafusion/pull/8833#discussion_r1452107106, we shouldn't extract common sub-expressions for short-circuited operations, such as COALESCE | OR.
In #8833, we deal with `CASE WHEN,` but all short-circuited expressions shouldn't be extracted from common sub-expressions.

### Expected behavior

Shouldn't extract common sub-expressions for short-circuited operation.

**Comment by liukun4515** [comment]
Do we have any method to make sure that the contributor will not import the same bug for this optimizer rule If the contributor are unfamiliar with the `common sub expr rule` when they add new expr/function in the datafusion?

@jackwener @haohuaijin @alamb

**Comment by alamb** [comment]
> Do we have any method to make sure that the contributor will not import the same bug for this optimizer rule If the contributor are unfamiliar with the `common sub expr rule` when they add new expr/function in the datafusion?

I do not know of such a method -- perhaps we can add some documentation to the optimizer rule trait 🤔
