### ISSUE TITLE
[rust][datafusion] optimize count(*) queries on parquet sources

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#89]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-8902

Currently, as far as I can tell, when you perform a `select count(*) from dataset` in datafusion against a parquet dataset, the way this is implemented is by doing a scan on column 0, and counting up all of the rows (specifically I think it counts the # of rows in each batch).

 

However, for the specific case of just counting _everythign_ in a parquet file, you can just read the rowcount from the footer metadata, so it's O(1) instead of O(n)

**Comment by alamb** [comment]
Comment from Andrew Lamb(alamb) @ 2021-04-26T12:31:08.482+0000:
<pre>Migrated to github: https://github.com/apache/arrow-rs/issues/75</pre>

**Comment by Dandandan** [comment]
This is implemented

**Comment by alamb** [comment]
Closed in https://github.com/apache/arrow-datafusion/pull/620
