### ISSUE TITLE
Implement `information_schema.schemata`

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#8917]
The idea is to implement https://www.postgresql.org/docs/current/infoschema-schemata.html in DataFusion to make it easier to work with standard tools like Apache Superset

**Comment by Tangruilin** [comment]
I am interested on this problem.
Maybe you can assign it to me

**Comment by alamb** [comment]
Thanks @Tangruilin !

cc @JanKaul  who made the original request in Discord

**Comment by JanKaul** [comment]
Thanks @Tangruilin ! 

Let me know if I can assist you somehow.

**Comment by Tangruilin** [comment]
> Thanks @Tangruilin !
> 
> Let me know if I can assist you somehow.

I have read about some of the code.
But I am a little confused how to start. Could you tell me where the metadata like `information_schema.table` add in the code, and I will look at that part

**Comment by JanKaul** [comment]
I think the following steps could work:

1. Create a `InformationSchemaSchemataBuilder` (similar to the [TablesBuilder](https://docs.rs/datafusion/latest/src/datafusion/catalog/information_schema.rs.html#276)) that has all the columns of the `information_schema.schemata` table.
2. Create a `make_schemata` function (similar to [make_tables](https://docs.rs/datafusion/latest/src/datafusion/catalog/information_schema.rs.html#79)) that obtains the schemas from the catalog list. This can be used to populate the previously created builder.
3. Create a `InformationSchemaSchemata` (similar to [InformationSchemaTables](https://docs.rs/datafusion/latest/src/datafusion/catalog/information_schema.rs.html#79)) that uses the `make_schemata` method to implement the `PartitionStream` trait.

Maybe it helps
