### ISSUE TITLE
support join conditions in where clause

### ISSUE THREAD

**Issue by houqp** [apache/arrow-datafusion#892]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

tpch query 8 is taking forever to execute in ballista because its subquery is planned as a cross join across 8 tables.

**Describe the solution you'd like**

The join conditions for query 8 are specified in the where clause. Our optimizer should pick this up and rewrite the part of the cross join into inner join.

**Describe alternatives you've considered**

Handle the rewrite in sql planner, but this will won't benefit dataframe users.

**Additional context**
Surfaced from https://github.com/apache/arrow-datafusion/pull/891.

**Comment by xudong963** [comment]
@houqp  I want to try it!

**Comment by xudong963** [comment]
If I read right, the issue has been solved? https://github.com/apache/arrow-datafusion/blob/master/datafusion/src/sql/planner.rs#L691

**Comment by houqp** [comment]
You are right @xudong963. I think there is a bug in that rewrite that resulted in inefficient cross join in an edge-case. I filed https://github.com/apache/arrow-datafusion/issues/1293 to track that problem instead.
