### ISSUE TITLE
Make test_row_group_prune test more readable

### ISSUE THREAD

**Issue by Ted-Jiang** [apache/arrow-datafusion#8922]
There are so many parameters here it is getting hard to read the tests I think (as you have three different constants that need to be remembered)

Maybe we can (as a follow on PR) make a more self documenting, something like

```suggestion
    RowGroupPruningTest::new()
        .with_scenario(Scenario::Timestamps)
        .with_query("SELECT * FROM t where nanos < to_timestamp('2020-01-02 01:01:11Z')"),
        .with_expected_errors(Some(0)),
        .with_pruned_by_stats(Some(1)),
        .with_pruned_by_bloom_filter(Some(0)),
        .with_expected_rows(10)
    )
    .await;
```

_Originally posted by @alamb in https://github.com/apache/arrow-datafusion/pull/8921#discussion_r1460358000_

**Comment by alamb** [comment]
I think this is a good issue for someone new to DataFusion as it doesn't require deep knowledge of the codebase but would get you familiar with exisitng code, patterns and tools

Here is an example of tests written in this style:
https://github.com/alamb/arrow-datafusion/blob/f16bc8bd93b9ea29c8f84f6e0ddf2f3500503c19/datafusion/core/tests/memory_limit.rs#L304-L320

**Comment by Lordworms** [comment]
I think I can handle it and get to know more about the codebase, how many tests should I cover in this issue?

**Comment by Lordworms** [comment]
hello @alamb  I just fixed this issue and since I am new here, please review my PR and give me more issues to solve to get more familiar with the structure, Thanks!

**Comment by alamb** [comment]
Amazing -- thank you @Lordworms  -- I'll look at https://github.com/apache/arrow-datafusion/pull/8941 shortly

Feel free to take / look at anything on this list:

https://github.com/apache/arrow-datafusion/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22
