### ISSUE TITLE
"cargo msrv verify" in CI

### ISSUE THREAD

**Issue by mustafasrepo** [apache/arrow-datafusion#8961]
### Describe the bug

I am not sure here is the correct place to ask this. I am asking here in case someone experienced or someone who encountered similar problem can help me. 

While working in a PR, CI fails during `cargo msrv verify` with error
```sql
Using check command cargo check
   Failed check command cargo check didn't succeed
Crate source was found to be incompatible with its MSRV '1.70.0', as defined in '/__w/arrow-datafusion/arrow-datafusion/datafusion/core/Cargo.toml'
```
However, it doesn't really say what is the problem. In the PR I didn't change any `Cargo.toml` file. I am not sure, how I triggerred it. Is there anyone with suggestions?

**Comment by haohuaijin** [comment]
It seems like you use the rust feature that rust version > `1.70.0`.
 `cargo msrv verify` check datafusion should work for `1.70.0`

**Comment by mustafasrepo** [comment]
Thanks @haohuaijin It seems that `ahash=0.8.7` has features from `rust=1.75.0`. It seems to be the problem.

**Comment by alamb** [comment]
What PR caused the problem?

**Comment by mustafasrepo** [comment]
> What PR caused the problem?

It was this [PR](https://github.com/synnada-ai/arrow-datafusion/pull/270) in synnada repo. However, upgrading dependencies fixed it. It no longer has this problem. I asked here, in case someone could help me understand better the root cause. 
Closing this issue now it is not relevant with datafusion per se. @haohuaijin for the suggestion again

**Comment by alamb** [comment]
> > What PR caused the problem?
> 
> It was this [PR](https://github.com/synnada-ai/arrow-datafusion/pull/270) in synnada repo. However, upgrading dependencies fixed it. It no longer has this problem. I asked here, in case someone could help me understand better the root cause. Closing this issue now it is not relevant with datafusion per se. @haohuaijin for the suggestion again

I filed https://github.com/apache/arrow-datafusion/pull/8995 to add some comments to try and help anyone else who may encounter this issue
