### ISSUE TITLE
NOT operator should not return internal error when args are not boolean value

### ISSUE THREAD

**Issue by haohuaijin** [apache/arrow-datafusion#8965]
### Describe the bug

```
❯ select not('hi');
Internal error: NOT 'Literal { value: Utf8("hi") }' can't be evaluated because the expression's type is Utf8, not boolean or NULL.
This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
❯ select 1 and 2;
Error during planning: Cannot infer common argument type for logical boolean operation Int64 AND Int64
```
I think the return error message of NOT should like `And` operator, they both only work for boolean value.

_Originally posted by @haohuaijin in https://github.com/apache/arrow-datafusion/pull/8957#discussion_r1463345264_

**Comment by alamb** [comment]
Ideally, something early in the code (perhaps the type coercion logic) should return an error if the argument to `not` can't be coerced to Boolean

It looks like perhaps we need to add a clause to
https://github.com/apache/arrow-datafusion/blob/af3d19038ef40e45c70c6e9a28798ee53795dfe9/datafusion/optimizer/src/analyzer/type_coercion.rs#L179-L182

Perhaps following the model of `Expr::IsNotNull`

As @haohuaijin  notes we may want to update https://github.com/apache/arrow-datafusion/blob/e642cc2a94f38518d765d25c8113523aedc29198/datafusion/physical-expr/src/expressions/not.rs#L83-L92 to not check for `is_null`

**Comment by alamb** [comment]
I think this is a good first issue -- the code should be a matter of following existing patterns and ensuring there is some tests for this

**Comment by guojidan** [comment]
I want try implement this 😄

**Comment by guojidan** [comment]
> As @haohuaijin notes we may want to update
> 
> https://github.com/apache/arrow-datafusion/blob/e642cc2a94f38518d765d25c8113523aedc29198/datafusion/physical-expr/src/expressions/not.rs#L83-L92
> 
> to not check for `is_null`

I think we still need check `is_null`, because `get_casted_expr_for_bool_op` will convert `null` to `ScalarValue::Boolean(NULL)`, but `ScalarValue::Boolean(NULL)` can not `try_into()` to `bool` type, so it will throw an error: Internal error: Cannot convert Boolean(NULL) to bool.
