### ISSUE TITLE
Implement the `POSITION` function

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#8969]
### Is your feature request related to a problem or challenge?

The idea is to support the `position` function from postgres:

https://www.postgresql.org/docs/9.1/functions-string.html

```sql
position(substring in string)	
```

For example
```sql
postgres=# select position('world' in 'Helloworld');
 position
----------
        6
(1 row)
```

### Describe the solution you'd like

As @zy-kkk points out on https://github.com/apache/arrow-datafusion/pull/8862#issuecomment-1906262994 postgres has special syntax 

To support the syntax `position('world' in 'Helloworld') = 6` we probably need to do it in at https://github.com/sqlparser-rs/sqlparser-rs and add support for this syntax , which may be like adding the `overlay` function in https://github.com/sqlparser-rs/sqlparser-rs/pull/594. 

Then we can change the datafusion planner to recognize that special syntax and call the `instr` function in https://github.com/apache/arrow-datafusion/pull/8862

### Additional context

This came up while implementing https://github.com/apache/arrow-datafusion/pull/8862

**Comment by alamb** [comment]
I think this is a good first issue, though it will require updating sqlparser-rs and then waiting for that to be released and making a change in datafusion

**Comment by Lordworms** [comment]
I would like to try that

**Comment by Lordworms** [comment]
Hello, @alamb  I have created a PR plz review it if you have time. Additionally, I have some other problems:
1. what is the suitable resolution time for a picked-up issue? 
2. It might be slow and other problems may happen if I test the full test locally, may I create a PR first to test it?
3. the rust-analyzer really consumes my CPU and RAM, is there any better way for a better Rust environment?
I would appreciate so much for your answer

**Comment by alamb** [comment]
> Hello, @alamb I have created a PR plz review it if you have time. Additionally, I have some other problems:

Thank you @Lordworms - I have it on my 

> 1. what is the suitable resolution time for a picked-up issue?

From my perspective there is no particular deadline for any issue. 

Instead, if someone is working on an issue but wasn't able to finish it before someone else needs / wants to work on the same thing, that other person can simply make a PR. 

I think most contributors are polite and check with the person who first signaled interest before working on something, but just because someone else might be working on something doesn't prevent anyone else from doing so


> 2. It might be slow and other problems may happen if I test the full test locally, may I create a PR first to test it?

I think making a draft PR to run the full suite of tests so you know which ones may need to run locally is a very reasonable strategy

> 3. the rust-analyzer really consumes my CPU and RAM, is there any better way for a better Rust environment?
>    I would appreciate so much for your answer

I don't have a good answer for this -- Rust development environments in general do require significant resources

**Comment by Lordworms** [comment]
Thank you, got it!

**Comment by SteveLauC** [comment]
Seems that we should close this issue as it was completed in #8988

**Comment by alamb** [comment]
> Seems that we should close this issue as it was completed in #8988

Thank you @SteveLauC  -- good call
