### ISSUE TITLE
Add a to_date function

### ISSUE THREAD

**Issue by Omega359** [apache/arrow-datafusion#8987]
### Is your feature request related to a problem or challenge?

In a similar vein to #8886 I believe it would be useful to have a to_date function that mirrors the functionality found in [postgresql](https://www.postgresql.org/docs/current/functions-formatting.html) and [spark](https://spark.apache.org/docs/latest/api/sql/#to_date). The format options however would follow the same pattern as #8886 and use the chrono library's formats (at least for the initial implementation)

Passing a single argument to the function would behave in a similar manner to the to_timestamp function where it was attempt to infer the date from either a number type (inferred as seconds/millis/etc since epoch), a timestamp or a utf8/largeutf8 string.  arrow-cast has a parse_date function invoked from the cast from string -> date32 that seems to handle a few common formats that can be documented in the user guide and examples.

The return type of this new function would be Date32 for arrow, Date for SQL.

### Describe the solution you'd like

A to_date(expr[,.format_n]) function that can be invoked from a dataframe or via sql in the same manner as to_timestamp.

### Describe alternatives you've considered

The basic implementation can likely be done using arrow_cast functionality currently however having a full function would allow for additional formatting options.

**Comment by Tangruilin** [comment]
May be this can be assigned to me @Omega359 ， I am interested on this problem

**Comment by Omega359** [comment]
Feel free to submit a pull request - I haven't started any work on this myself. I have the logic in a UDF however it's not exactly complex.

**Comment by Tangruilin** [comment]
Please assigned it to me
Thanks @alamb
