### ISSUE TITLE
explicitly list out all Expr types in `TypeCoercionRewriter::mutate`

### ISSUE THREAD

**Issue by guojidan** [apache/arrow-datafusion#8990]
It might make sense to remove the catch all  from this `match` expression

https://github.com/apache/arrow-datafusion/blob/bc0ba6a724aaaf312b770451718cbce696de6640/datafusion/optimizer/src/analyzer/type_coercion.rs#L413

And explicitly list out all Expr types so that we don't accidentally another Expr type in the future

Is that something you might be willing to do in another PR @guojidan  ?

_Originally posted by @alamb in https://github.com/apache/arrow-datafusion/pull/8982#discussion_r1464993523_

**Comment by guojidan** [comment]
wait #8982 merged

**Comment by alamb** [comment]
> wait #8982 merged

Sorry for the delay, #8982 is now merged
