### ISSUE TITLE
support `list_reverse` in array

### ISSUE THREAD

**Issue by Weijun-H** [apache/arrow-datafusion#9021]
### Is your feature request related to a problem or challenge?

```
list_reverse([3, 2, 1])  ---> [1, 2, 3]
```

### Additional context

[arrayReverse(arr)](https://clickhouse.com/docs/en/sql-reference/functions/array-functions#arrayreversearr)
[list_reverse](https://duckdb.org/docs/sql/functions/nested#list-functions)

**Comment by Tangruilin** [comment]
Did you mean list_reverse function?
@Weijun-H

**Comment by Tangruilin** [comment]
Like 

`select list_reverse([1, 2, 3]);` and get  `[3, 2, 1]`

**Comment by Weijun-H** [comment]
> Like
> 
> `select list_reverse([1, 2, 3]);` and get `[3, 2, 1]`

Yes, it is.

**Comment by Tangruilin** [comment]
> > Like
> > `select list_reverse([1, 2, 3]);` and get `[3, 2, 1]`
> 
> Yes, it is.

You can assign it to me. I know what to do.

**Comment by Weijun-H** [comment]
> > > Like
> > > `select list_reverse([1, 2, 3]);` and get `[3, 2, 1]`
> > 
> > 
> > Yes, it is.
> 
> You can assign it to me. I know what to do.

Sorry @Tangruilin I almost have completed this issue, maybe you could pick another one.

**Comment by Tangruilin** [comment]
> > > > Like
> > > > `select list_reverse([1, 2, 3]);` and get `[3, 2, 1]`
> > > 
> > > 
> > > Yes, it is.
> > 
> > 
> > You can assign it to me. I know what to do.
> 
> Sorry @Tangruilin I almost have completed this issue, maybe you could pick another one.

Okey ~~~
