### ISSUE TITLE
Add a make_date function

### ISSUE THREAD

**Issue by Omega359** [apache/arrow-datafusion#9024]
### Is your feature request related to a problem or challenge?

Currently there isn't a way to make a date from separate component fields without doing a fair bit of work along the lines of:
```
arrow_cast(to_timestamp_seconds(concat(col(date_year), '-', lpad(arrow_cast(col(date_month), 'Utf8'), 2, '0'), '-', lpad(arrow_cast(col(date_day), 'Utf8'), 2, '0'), 'T00:00:00.000Z')), 'Date32')
```

A function with the same signature as the [postgresql](https://www.postgresql.org/docs/16/functions-datetime.html) or [spark ](https://spark.apache.org/docs/latest/api/sql/#make_date) functions would be a useful addition.

### Describe the solution you'd like

A make_date(year, month, day) function that would take expressions for all arguments with a return type of Date32 for dataframes, Date for SQL.

**Comment by alamb** [comment]
A similar request (make interval) is https://github.com/apache/arrow-datafusion/issues/6951

**Comment by Omega359** [comment]
> A similar request (make interval) is #6951

I can work on that one after I complete this one.

**Comment by alamb** [comment]
Thanks @Omega359 ! 

BTW I am not sure if you are interested, but https://github.com/apache/arrow-datafusion/issues/8282 contains a list of tickets we have gathered relating to date/time issues
