### ISSUE TITLE
Internal error when negating strings

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#9060]
### Describe the bug

Negating an string results in an internal error

### To Reproduce

```sql
❯ select -'100';
Internal error: Can't create negative physical expr for (- 'Literal { value: Utf8("100") }'), the type of child expr is Utf8, not signed numeric.
This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```

However, if the explicit cast is added things work great:
```sql
❯ select -'100'::int;
+-----------------+
| (- Utf8("100")) |
+-----------------+
| -100            |
```

### Expected behavior

The query should probably an error that says something like `negate only supports numeric types`

Related PR:  https://github.com/apache/arrow-datafusion/pull/8982 can be applied here too

**Comment by alamb** [comment]
I think this would be a reasonable first issue that would teach someone about the datafusion codebase

**Comment by alamb** [comment]
>  Can I help it ? (Or left it as an issue for a new comer) 😃


how about we wait a day or two to see if anyone else is interested ?

Thank you !

**Comment by yyy1000** [comment]
> >  Can I help it ? (Or left it as an issue for a new comer) 😃
> 
> 
> 
> 
> 
> how about we wait a day or two to see if anyone else is interested ?
> 
> 
> 
> Thank you !

🤣That's OK.
I can try to help other old issues now.😆

**Comment by trungda** [comment]
I took the liberty and submitted a PR. Thanks @yyy1000 and @alamb
