### ISSUE TITLE
Optimize `make_date`

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#9089]
### Is your feature request related to a problem or challenge?

I think there is significant performance to be had when creating dates and now thanks to @Omega359  there are benchmarks

To run the benchmarks, do:
```shell
cargo bench --bench make_date
```

### Describe the solution you'd like

Make  the function faster, as defined by the command above

The high level procedure for this is to profile the function and figure out how to make it go faster while still computing the same results

### Describe alternatives you've considered

It may not be possible to make this faster and in that case no worries.

### Additional context

I think this is actually a pretty good initial project for someone because 
1. The code is relatively straightforward
2. The benchmark is in place

**Comment by r3stl355** [comment]
A quick experiment replacing `value_fn` with pre-computed arrays shows about 50% improvement for benchmarks using columns but about 20% regression for scalar only benchmark (I think I should be able to get that scalar version back to baseline). If you think this is significant I can carry on working on it

**Comment by alamb** [comment]
Sounds pretty great to me -- thanks @r3stl355

**Comment by Omega359** [comment]
I think with #9112 this issue could be closed @alamb  ?

**Comment by alamb** [comment]
> I think with #9112 this issue could be closed @alamb ?

I agree -- thank you for the ping

**Comment by vojtechtoman** [comment]
@alamb I was looking at this out of interest and I just noticed that this issue has been closed in the meantime. I introduced some further improvements in https://github.com/apache/arrow-datafusion/pull/9600 which lead to about 10% performance gain for the cases involving arrays and about 20% for the scalars-only case.

**Comment by alamb** [comment]
Thank you @vojtechtoman  -- very exciting
