### ISSUE TITLE
ci: run cargo audit

### ISSUE THREAD

**Issue by Jefffrey** [apache/arrow-datafusion#9116]
### Is your feature request related to a problem or challenge?

Run cargo audit as part of CI

### Describe the solution you'd like

See arrow-rs: https://github.com/apache/arrow-rs/pull/5160

### Describe alternatives you've considered

Don't do this

### Additional context

Looks like this was attempted before: https://github.com/apache/arrow-datafusion/pull/599

Though this was attempting to run it on schedule. In the arrow-rs PR above it only runs on PR/commits to master

DataFusion probably moves fast enough that commits to main are enough for triggering audit check, but can explore making it scheduled again

Note that will not be able to use the audit GitHub action and will instead need to run it manually, as was not able to use the GitHub action due to some policy blocking external action use (or something like that)

**Comment by Jefffrey** [comment]
Marking as good first issue as there is the arrow-rs to base off from, and is self contained to only CI for this repo

**Comment by ongchi** [comment]
I noticed there is a [fork](https://github.com/rustsec/audit-check) of original audit-check action. I think this could be trusted since it is run by the Rust Secure Code WG.
It would save much time and bandwidth on compilation and installation of cargo-audit in CI.

**Comment by Jefffrey** [comment]
> I noticed there is a [fork](https://github.com/rustsec/audit-check) of original audit-check action. I think this could be trusted since it is run by the Rust Secure Code WG. It would save much time and bandwidth on compilation and installation of cargo-audit in CI.

I think I tried that action before but was unable to get it to run in CI, see:

https://github.com/apache/arrow-rs/pull/5160#discussion_r1415540561

So I opted for just including the shell steps manually, but if there's another way to get around that above error and use that audit-check action then all for it :+1:

**Comment by ongchi** [comment]
Hello @Jefffrey,
I tried that action and it seems to works well.
Here is the [log](https://github.com/ongchi/arrow-datafusion/actions/runs/7811652430/job/21307138257).

**Comment by Jefffrey** [comment]
Ah that's great then :+1: 

Feel free to submit a PR with this added :eyes:

**Comment by alamb** [comment]
> DataFusion probably moves fast enough that commits to main are enough for triggering audit check, but can explore making it scheduled again


I agree triggering on commits to main would be good enough. Thank you @ongchi and @Jefffrey
