### ISSUE TITLE
CI: add support for M1 macOS runner 

### ISSUE THREAD

**Issue by Weijun-H** [apache/arrow-datafusion#9117]
### Is your feature request related to a problem or challenge?

Github Action supports M1 macOS runner, and it will be better to integrate it in the current ci. 
https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

**Comment by alamb** [comment]
Yes, this would be very nice (and give us coverage of the aarch64 architecture which we don't have yet)

**Comment by alamb** [comment]
I think this would be a matter of changing https://github.com/apache/arrow-datafusion/blob/10e6d1870280296b31c6faff29ddf3f8fe98bbc4/.github/workflows/rust.yml#L295-L309

However, that already says "macos latest" so maybe we are already running in M1 macs 🤔

**Comment by alamb** [comment]
> The new runner operates exclusively on macOS 14 and to use it, simply update the runs-on key in your YAML workflow file to macos-14.

I double checked and the latest CI seems to run on `macos-12` 

https://github.com/apache/arrow-datafusion/actions/runs/7818251058/job/21328033495

**Comment by alamb** [comment]
I think this would be a pretty good issue for someone new to the project
