### ISSUE TITLE
Allow the contributor to self-assign the issue

### ISSUE THREAD

**Issue by r3stl355** [apache/arrow-datafusion#9124]
### Is your feature request related to a problem or challenge?

Instead of asking if it's ok to work on an issue, and waiting for someone to respond, would it be easier just to comment a keyword (say `take`) to the issue, which would trigger a GitHub workflow and assign the issue to the person who wrote the comment?

### Describe the solution you'd like

I've implemented this for couple of projects (delta-rs and delta sharing rust) and contributors found it useful. It is a very simple GitHub workflow. All that the contributor needs to do is to submit a simple comment to the issue (e.g. `take`) and the issue gets auto-assigned to the user. Once that's done, if needed then a contributor can un-assign the issue using the UI (e.g. they no longer have time or skills to handle it)

**Comment by Jefffrey** [comment]
This seems like a good idea :+1:
