### ISSUE TITLE
Document: Enhance ScalarUDF document

### ISSUE THREAD

**Issue by yyy1000** [apache/arrow-datafusion#9136]
### Is your feature request related to a problem or challenge?

When I read the document of https://arrow.apache.org/datafusion/library-user-guide/adding-udfs.html
I found it still use `create_udf` to create a scalarUDF. It would be deprecated in the new version.

### Describe the solution you'd like

Update the doc using`impl ScalarUDFImpl ` to create the scalarUDF.

### Additional context

I can work on it if it's worth doing!

**Comment by alamb** [comment]
> I can work on it if it's worth doing!

Yes @yyy1000  this is definitely worth doing and would be most appreciated. Maybe @tshauck  has some additional insight to share on this too.

**Comment by alamb** [comment]
There are some good examples  in https://github.com/apache/arrow-datafusion/blob/main/datafusion-examples/examples/advanced_udf.rs and the documentation I think is pretty good too

**Comment by yyy1000** [comment]
take

**Comment by tshauck** [comment]
That'd be great! Yeah, those docs were written before the trait based solution, so could use an update.
