### ISSUE TITLE
consolidate all the `InList` rewrites into a single pass 

### ISSUE THREAD

**Issue by guojidan** [apache/arrow-datafusion#9140]
Thank you @guojidan  -- this looks good to me. I think as a follow on PR it would be nice to consolidate all the `InList` rewrites into a single pass (rather than `ShortenInListSimplifier` and `InListSimplifier` but this PR seems like a good step in that direction

Thanks again

_Originally posted by @alamb in https://github.com/apache/arrow-datafusion/pull/9037#pullrequestreview-1861422186_

**Comment by alamb** [comment]
I am not sure if @guojidan  plans to work on this one. If not I think it would make a good first issue for someone

**Comment by guojidan** [comment]
I don't have much time recently because the Spring Festival holiday has arrived. So If everyone is interested, let's implement this 😄

**Comment by manoj-inukolunu** [comment]
@guojidan  @alamb  , would love to help here.thx. 😄

**Comment by manoj-inukolunu** [comment]
Hello @alamb  @guojidan  , I was working through a PR for this . I have a question on `ShortenInListSimplifier` what is the significance of `THRESHOLD_INLINE_INLIST` ? Thank you.

**Comment by alamb** [comment]
I think it is a heuristic that avoids pathalogical cases when there are large numbers constants in the `IN` list (sometimes machine generated SQL can have 1000s of elements)

https://github.com/apache/arrow-datafusion/blob/afb169cd069e0227fb0ef6d39f44d5eabbdc21a2/datafusion/optimizer/src/simplify_expressions/inlist_simplifier.rs#L53-L59

**Comment by manoj-inukolunu** [comment]
Thank you @alamb  , I will add a comment. I attempted to do the in list simplifier in one pass . I am not really sure if its possible in a single pass. Here is the test which is failing if i try that . 
```
// c1 IN (1,2,3,4,5,6) AND c1 IN (1,3,5,6) AND c1 IN (3,6) -> c1 = 3 OR c1 = 6
```
After the first pass it simplifies to 
```
c1 IN (3,6)
```
After the `ShortenInListSimplifier` it simplifies to 
```
 c1 = 3 OR c1 = 6
 ```
 If i try to combile the `ShortenInListSimplifier` with the `InListSimplifier`  , in the first pass itself 
 ```
 c1 IN (3,6)
 ```
 is getting simplified to ` c1 = 3 OR c1 = 6` according to the `ShortenInListSimplifier` which is breaking the test . Additionaly i attempted a benchmark , the additional pass seems to be adding around 6% overhead.

**Comment by alamb** [comment]
> If i try to combile the ShortenInListSimplifier with the InListSimplifier , in the first pass itself

Ths sounds like the logic for the two simplifications is being invoked in a different order (or maybe only one is being invoked? 🤔 ). Could we perhaps invoke both simplications but invoke the code to simplify first and then the code to shorten?

> Additionaly i attempted a benchmark , the additional pass seems to be adding around 6% overhead. 

That is good data and more reason I think to consolidate the passes. Thank you

**Comment by guojidan** [comment]
hi @manoj-inukolunu , `ShortenInListSimplifier` should be executed after `InListSimplifier` has executed. one Expr will be executed recursively at each `Simplifier`
example: 
> c1 IN (1,2,3,4,5,6) AND c1 IN (1,3,5,6) AND c1 IN (3,6)  

`InListSimplifier`
1. c1 IN (1,2,3,4,5,6) -> c1 IN (1,2,3,4,5,6)
2. c1 IN (1,3,5,6)  -> c1 IN (1,3,5,6)
3. c1 IN (3,6) -> c1 IN (3,6)
4. c1 IN (1,2,3,4,5,6) AND c1 IN (1,3,5,6) -> c1 IN (1,3,5,6)
5. c1 IN (1,3,5,6) AND c1 IN (3,6)
6. c1 IN (3,6)

`ShortenInListSimplifier`
8. c1 = 3 OR c1 = 6

if we combile the `ShortenInListSimplifier` with the `InListSimplifier`, it will become below workflow:
1. c1 IN (1,2,3,4,5,6) -> c1 IN (1,2,3,4,5,6)
2. c1 IN (1,3,5,6)  -> c1 IN (1,3,5,6)
3. c1 IN (3,6) -> c1 = 3 OR c1 = 6
4. c1 IN (1,2,3,4,5,6) AND c1 IN (1,3,5,6) -> c1 IN (1,3,5,6)
5. c1 IN (1,3,5,6) AND c1 = 3 OR c1 = 6

maybe you can view older version inlist simplifier logical(before my pr), I can got more inspiration

**Comment by guojidan** [comment]
So, the key of this issue is how to determine the time to execute `ShortenInListSimplifier`, Separate execution is the simplest 🤔

**Comment by jayzhan211** [comment]
@manoj-inukolunu @guojidan Are any working on this currently? If not, I will take a a look on this issue.

**Comment by guojidan** [comment]
> @manoj-inukolunu @guojidan Is anyone working on this currently? If not, I will take a a look on this issue.

I am not working on this, thank you

**Comment by alamb** [comment]
FYI @jayzhan211  I had started playing with this at some point but didn't finish

One approach might be to port individual parts of the inlist rewrite in multiple PRs (the entire logic was quite tricky, so doing it incrementally would likely be easier to code and easier to review)

**Comment by jayzhan211** [comment]
> port individual parts of the inlist rewrite in multiple PRs
@alamb Are you talking about removing cloned or moving short in list into inlist simplifier

I'm looking into the issue moving short inlist, and I currently think it is not able to move into the inlist simplifier. Short Inlist to OrList should be started after the other 3 rules have been done **recursively.** Do you have an idea to run those rules recursively in order.
