### ISSUE TITLE
Support `multiple_members` on compression decoders?

### ISSUE THREAD

**Issue by tshauck** [apache/arrow-datafusion#9156]
### Is your feature request related to a problem or challenge?

The challenge is that currently when trying to use the gzip decoder from `async-compression` to decode block-gzipped files, the query ends after the first block in the file _not_ the EOF.

Based on an issue filed here: https://github.com/Nullus157/async-compression/issues/260, bgzip works if the decoder is modified to support [multiple members](https://docs.rs/async-compression/latest/async_compression/tokio/bufread/struct.GzipDecoder.html#method.multiple_members) (I've confirmed this is the case).

### Describe the solution you'd like

So my feature request is the ability to specify to call this method or have it set by default (though I'm not sure the performance implications).

I'd be happy to take a look a this, but I'm not sure what an appropriate path would be that's congruent with datafusion overall.

**Comment by Lordworms** [comment]
I can try to do this one

**Comment by alamb** [comment]
It sounds like the request here is "support block-gzipped files"? 

If so that seems reasonable to me. Maybe we could just add `CompressionType::BGZIP` or something?

**Comment by tshauck** [comment]
Sorry, I did the ol' "ask for the solution I think I want vs what I want in the end"... thought more about it when I started the implementation to open https://github.com/apache/arrow-datafusion/pull/9160.
