### ISSUE TITLE
Probably incorrect result when the column referenced in GROUP BY is ambiguous

### ISSUE THREAD

**Issue by jonahgao** [apache/arrow-datafusion#9162]
### Describe the bug

The result might be incorrect when the column referenced in the GROUP BY clause is ambiguous; that is, when the column exists in both the select list and the input. This behavior is different from PostgreSQL.

### To Reproduce

Run the following queries in DataFusion CLI .
```sh
DataFusion CLI v35.0.0
❯ create table t(a bigint);
0 rows in set. Query took 0.009 seconds.

❯ insert into t values(1),(2),(3);
+-------+
| count |
+-------+
| 3     |
+-------+
1 row in set. Query took 0.007 seconds.

❯ select 0 as "t.a" from t group by t.a;
+-----+
| t.a |
+-----+
| 0   |
+-----+
1 row in set. Query took 0.010 seconds.
```

### Expected behavior

The result should ideally be the same as PostgreSQL, MySQL, and DuckDB.
```
psql => select 0 as "t.a" from t group by t.a;
 t.a
-----
   0
   0
   0
(3 rows)
```

**Comment by jonahgao** [comment]
take

**Comment by alamb** [comment]
I agree matching the other behavior would be good
