### ISSUE TITLE
Internal_err! is over used in core code and should be replaced with exec_err! or plan_err! in many places

### ISSUE THREAD

**Issue by Omega359** [apache/arrow-datafusion#9164]
### Describe the bug

internal_err! is used as a general error macro in many spots in the code where in fact the problem the error is propagating is not caused by an oversight, bug, etc in the code but rather by user error. A good example of this can be seen in PR #9137  [comment](https://github.com/apache/arrow-datafusion/pull/9137#discussion_r1480303798) where it's being used to let the user know they provided a datatype as an argument to a function that it doesn't support. This in fact should be an exec_err! in this example.

### Expected behavior

In most cases where the error is caused by incorrect data types or invalid argument counts exec_err! should be used.

**Comment by comphead** [comment]
Related to #6108

**Comment by comphead** [comment]
looking fwd for the PR :)

**Comment by Omega359** [comment]
take

**Comment by alamb** [comment]
Bug squashed 
![image](https://github.com/apache/arrow-datafusion/assets/490673/853c72fc-412e-47dc-a0f9-401d8a7762c2)
