### ISSUE TITLE
Improve Cargo.toml files by making tokio a workspace dependency (pull into root level)

### ISSUE THREAD

**Issue by Omega359** [apache/arrow-datafusion#9165]
### Is your feature request related to a problem or challenge?

![image (1)](https://github.com/apache/arrow-datafusion/assets/226258/e893b11f-4273-4bb5-ab49-c2ae973544ad)

Currently the versions and features being used across DataFusion for the tokio crate are not consistent. Pulling tokio into the root level and workspace = true in the other crates would allow for a consistent versioning for tokio.

### Describe the solution you'd like

```
tokio = { version = "1.36", features = ["macros", "rt", "rt-multi-thread", "sync", "fs", "parking_lot"] }
```
in root level Cargo.toml, 

```
tokio = { workspace = true }
```
in the other toml files.

**Comment by alamb** [comment]
I think this is a good first issue as it is well specified and doesn't involve deep knowledge of the codebase
