### ISSUE TITLE
Build abi3 wheels for python binding

### ISSUE THREAD

**Issue by houqp** [apache/arrow-datafusion#921]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**

For every python binding release, we are building python wheels for specific python patch versions.

**Describe the solution you'd like**

Build a single abi3 wheel for each platform for better forward compatibility and reduce complexity.

Here is an example of what abi3 wheel looks like: https://pypi.org/project/deltalake/#files. 
It can be configured like so https://github.com/delta-io/delta-rs/blob/3f87e76d0462621993095760e537dcf21999c348/python/Cargo.toml#L27.

**Comment by houqp** [comment]
@jorgecarleitao @Jimexist @kszucs do you know if there is any particular reason why we are not building abi3 wheels? It's been working really well for deltalake's python binding, so I figured we might want to go with the same setup for datafusion as well.

**Comment by kszucs** [comment]
In theory we should be able to build abi3 wheels. There are some [limitations](https://pyo3.rs/v0.13.2/building_and_distribution.html#missing-features), but abi3 wheels look promising. 

We may want to keep this issue open for later evaluation.

**Comment by houqp** [comment]
Good call @kszucs , I wasn't aware of that. I filed https://github.com/apache/arrow-datafusion/issues/955 to keep the task description more specific.
