### ISSUE TITLE
Constant expression in order-by produces an error

### ISSUE THREAD

**Issue by helgikrs** [apache/arrow-datafusion#9212]
### Describe the bug

EnforceSorting produces an error when the sort expression is a constant.

This is the error produced
```
EnforceSorting
caused by
Internal error: Wrong number of children.
This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
```

### To Reproduce

Ordering by a constant expression (without any column references) produces the above error, e.g.,

```
DataFusion CLI v35.0.0
❯ create table a;
0 rows in set. Query took 0.001 seconds.

❯ select * from a order by 'foo';
EnforceSorting
caused by
Internal error: Wrong number of children.
This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
❯ 
```

### Expected behavior

No error.

**Comment by mustafasrepo** [comment]
@helgikrs when I run the reproducer above on the main branch. Query succeeds. Is there any config parameter, you overwrite the default. Maybe some config parameters trigger this behavior.

**Comment by helgikrs** [comment]
I forgot to check latest main, I just checked the v35.0.0 release. I can confirm that this has indeed been fixed there. Closing the issue. Thanks!
