### ISSUE TITLE
`to_char(.., null)` should be NULL, not `..`

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#9217]
The newly added `to_char`'s null handling is not quite correct -- specifically when the format string is null, the output should be null, but now it returns the first argument

Goal is to make `to_char` do what postgres does: 

              Postgres seems to think this should be null
```sql
postgres=# select to_char(interval '1 day', null);
 to_char
---------

(1 row)
```

_Originally posted by @alamb in https://github.com/apache/arrow-datafusion/pull/9181#discussion_r1487974457_

**Comment by manoj-inukolunu** [comment]
take

**Comment by tinfoil-knight** [comment]
@manoj-inukolunu Are you still working on this? (If not, could you please un-assign yourself. I'd like to attempt the fix for this issue)

**Comment by manoj-inukolunu** [comment]
Hey so sorry not working on it right now , swamped with work .

**Comment by manoj-inukolunu** [comment]
unassign

**Comment by tinfoil-knight** [comment]
take
