### ISSUE TITLE
cargo test generates untracked file

### ISSUE THREAD

**Issue by mustafasrepo** [apache/arrow-datafusion#9247]
### Describe the bug

When I run the cargo test command on my locale
```
datafusion/core/output.csv
datafusion/core/output.json
datafusion/core/output.parquet
```
files are generated. 
I think, we should delete them after generation for cleanup. Or we should track them, to reduce surprise. These seems to originate from doctests of `write_csv`, `write_json`, `write_parquet` methods of `DataFrame`

**Comment by Omega359** [comment]
take
