### ISSUE TITLE
Add support for `CopyTo::partition_by` field in datafusion_proto

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#9248]
After https://github.com/apache/arrow-datafusion/pull/9240 datafusion protobuf will will silently ignore partition_by options;

The task is
1.  add code to  serialize / deserialize the `CopyTo::partition_by` field, added in https://github.com/apache/arrow-datafusion/pull/9240 to the existing serialization code (similarly to how copy_to is done) https://github.com/apache/arrow-datafusion/blob/f1dcbf978210be6aa69b07892cf47321905aeece/datafusion/proto/src/logical_plan/mod.rs#L850

2. Update the test in `datafusion/proto/tests/cases/roundtrip_logical_plan.rs` to send a non empty partition column list

_Originally posted by @devinjdangelo in https://github.com/apache/arrow-datafusion/pull/9240#discussion_r1491159044_

**Comment by alamb** [comment]
Once https://github.com/apache/arrow-datafusion/pull/9240  is merged, I think this would be a good first issue as it will be small and self contained

**Comment by PhVHoang** [comment]
I can work on this one.

**Comment by alamb** [comment]
> I can work on this one.

Thanks @PhVHoang  🙏 

https://github.com/apache/arrow-datafusion/pull/9240 was just merged so I think this one is now actionable

**Comment by PhVHoang** [comment]
take
