### ISSUE TITLE
feature flag to statically link liblzma

### ISSUE THREAD

**Issue by universalmind303** [apache/arrow-datafusion#9256]
### Is your feature request related to a problem or challenge?

datafusion automatically dynamically links `lzma` if you have the `compression` feature enabled due to the dependency on `xz2`

### Describe the solution you'd like

add a new feature to statically link lzma, or at the very least document the workaround provided below. 

### Describe alternatives you've considered

You can manually statically link by adding the following to your cargo.toml

```toml
lzma-sys = { version = "*", features = ["static"] }
```

### Additional context

some bugs caused by this
- https://github.com/GlareDB/glaredb/pull/2631
- https://github.com/lancedb/lance/issues/1912

**Comment by guojidan** [comment]
Can we add `xz2 = { version = "0.1", optional = true, features = ["static"] }` into https://github.com/apache/arrow-datafusion/blob/main/datafusion/core/Cargo.toml#L100 ? 😕  cc @alamb

**Comment by alamb** [comment]
It would certainly be good to add a feature flag (though it might be better to simply always statically link?)

I think statically linking by default makes sense to me and is consistent with most of the rest of the rust ecosystem / crates.

**Comment by universalmind303** [comment]
@alamb i agree. Statically linking by default makes a lot of sense & greatly simplifies things for downstream users. Happy to make this change if you want to assign issue to me.

**Comment by alamb** [comment]
> this need re-opening as same issue arise with now liblzma crate

Thanks @rphlo  -- can you please open a new ticket with a description of what problem you are seeing / symptoms? 

That will likely help get a resolution faster than reopening an old ticket
