### ISSUE TITLE
Cannot release DataFusion 36.0.0 to crates.io due to circular dependency

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#9277]
### Describe the bug

It is not possible to publish `datafusion-physical-expr` to crates.io because it has a dependency on `datafusion` (datafusion-core), and datafusion-core depends on `datafusion-physical-expr`.

```
Caused by:
  failed to select a version for the requirement `datafusion = "^36.0.0"`
  candidate versions found which didn't match: 35.0.0, 34.0.0, 33.0.0, ...
  location searched: crates.io index
  required by package `datafusion-physical-expr v36.0.0 (/home/andy/git/apache/arrow-datafusion/target/package/datafusion-physical-expr-36.0.0)`
```

**Comment by andygrove** [comment]
The dependency was introduced in https://github.com/apache/arrow-datafusion/pull/9137

**Comment by Omega359** [comment]
It should be just a dev dependency - I had to add it to get the rustdocs to work. I am unsure how that would affect crates.io deployment but removing it I think would require the removal (or moving ... to where I don't know) of the rustdoc for  regexp_like.

**Comment by Omega359** [comment]
Someone else with the same issue: https://users.rust-lang.org/t/circular-dev-dependency/69519/8

**Comment by andygrove** [comment]
As a short-term fix, we can tag the rustdoc with `ignore` until we figure out a better solution. I have a PR up:

https://github.com/apache/arrow-datafusion/pull/9279
