### ISSUE TITLE
ParquetExec: don't evalute predicates unless corresponding pushdowns are enabled

### ISSUE THREAD

**Issue by SteveLauC** [apache/arrow-datafusion#9282]
### Is your feature request related to a problem or challenge?

Currently `ParquetExec::new()` would create `PruningPredicate` and `PagePruningPredicate` if the `predicate` argument is `Some()`, this does not seem to be useful if the corresponding pushdowns are disabled.

### Describe the solution you'd like

Only create them if the corresponding pushdowns are enabled

### Describe alternatives you've considered

No

### Additional context

Related code snippet:

https://github.com/apache/arrow-datafusion/blob/cf92f3b01ff064308c5e7ca2e15c20770d48a88a/datafusion/core/src/datasource/physical_plan/parquet/mod.rs#L123-L149

**Comment by Lordworms** [comment]
May I try this one?

**Comment by Jefffrey** [comment]
> May I try this one?

With https://github.com/apache/arrow-datafusion/pull/9132 now merged, feel free to comment `take` to self-assign this issue :+1:

**Comment by Lordworms** [comment]
take

**Comment by SteveLauC** [comment]
Kinda think this would require an API change, a builder API should be sufficient

**Comment by SteveLauC** [comment]
Close as this issue does not exist. For more info, see [this comment](https://github.com/apache/arrow-datafusion/pull/9314#issuecomment-1962240794).
