### ISSUE TITLE
Move `make_array` to datafusion-functions

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#9288]
### Is your feature request related to a problem or challenge?

Part of https://github.com/apache/arrow-datafusion/issues/9285 and https://github.com/apache/arrow-datafusion/issues/8045

The goal is to extract function definitions out of the datafusion core.

Note the `make_array` function is somewhat special in that it has several special cases in datafusion core at the moment.
Not only do the special cases make it hard to move, it also means some datafusion functionality is not available to scalar udf functions

I think this ticket will be blocked on  removing the [special case handling of `MakeArray`in the expression rewriter(link)](https://github.com/apache/arrow-datafusion/blob/ee9736fc81b4461d417b409baeaeb9f5e01ad962/datafusion/optimizer/src/analyzer/rewrite_expr.rs#L135-L146) -- I will file a follow on ticket

### Describe the solution you'd like

Move the make_array function to datafusion-functions-array

### Additional context

Note I have a draft PR with some of this code: https://github.com/apache/arrow-datafusion/pull/9222 but likely won't have time to work on it for a while

**Comment by alamb** [comment]
I think https://github.com/apache/arrow-datafusion/issues/9289 may be able to help us with the simplify example

**Comment by alamb** [comment]
@jayzhan211  I wonder if you have thoughts or time to work on this ticket?

**Comment by jayzhan211** [comment]
not sure how to do yet, but I will take it.

/take
