### ISSUE TITLE
[Rust]  Implement pretty print for physical query plan

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#93]
*Note*: migrated from original JIRA: https://issues.apache.org/jira/browse/ARROW-9482

Implement pretty print for physical query plan. similar to what we have for the logical plan.

**Comment by alamb** [comment]
Comment from Andrew Lamb(alamb) @ 2021-04-26T12:32:34.670+0000:
<pre>Migrated to github: https://github.com/apache/arrow-rs/issues/88</pre>

**Comment by houqp** [comment]
@alamb i think this is already implemented?

**Comment by alamb** [comment]
Yes, this is definitely implemented. Introduced in https://github.com/apache/arrow-datafusion/pull/337 I think
