### ISSUE TITLE
Non cancel-safe tokio spawns

### ISSUE THREAD

**Issue by DDtKey** [apache/arrow-datafusion#9317]
### Describe the bug

I see a lot of cases of using `tokio::spawn` without wrapping `JoinHandle`s correctly.
So if we stop execution (e.g `tokio::select!`) - we can find some tasks that are still alive.
We can even see panic after canceling an execution (at least I did)

Examples:
- `demux_task`: [a function](https://github.com/apache/arrow-datafusion/blob/02c948d91b82f3e8988fafd12a072a476500c13d/datafusion/core/src/datasource/file_format/write/demux.rs#L73-L113) and then just [await on JoinHandle ](https://github.com/apache/arrow-datafusion/blob/02c948d91b82f3e8988fafd12a072a476500c13d/datafusion/core/src/datasource/file_format/arrow.rs#L298-L308)
- parquet [spawn_rg_join_and_finalize_task](https://github.com/apache/arrow-datafusion/blob/02c948d91b82f3e8988fafd12a072a476500c13d/datafusion/core/src/datasource/file_format/parquet.rs#L822-L847)
- parquet [spawn_column_parallel_row_group_writer](https://github.com/apache/arrow-datafusion/blob/02c948d91b82f3e8988fafd12a072a476500c13d/datafusion/core/src/datasource/file_format/parquet.rs#L778-L779)
- orchestration [serialize_rb_stream_to_object_store](https://github.com/apache/arrow-datafusion/blob/02c948d91b82f3e8988fafd12a072a476500c13d/datafusion/core/src/datasource/file_format/write/orchestration.rs#L61-L65)

### To Reproduce

Easiest way, is to create a long-running query which probably may even fail, and track the tokio tasks with tokio console after cancelling the execution.
I.e wrap it to select or timeout and check that spawned tasks are still working after cancelling by another branch.

### Expected behavior

I believe execution should be cancel-safe, and I think we need to care more about spawned tasks.
We already had such issues before, e.g: https://github.com/apache/arrow-datafusion/issues/5178

But I think even `AbortOnDropMany` doesn't solve all edge-cases, for example there are places when we do return `Vec<JoinHandle>` or just `JoinHandle`, but actually the execution can be canceled before wrapping into `AbortOnDropMany` (if there are any async calls in between). 
So I'd say https://github.com/apache/arrow-datafusion/issues/6513 is more relevant now, I guess even single task should be spawned with `JoinSet`

### Additional context

How can we protect of introducing this? 
I think we need to disallow `tokio::spawn` or pay attention to any `spawn` during review at least

**Comment by DDtKey** [comment]
take

**Comment by devinjdangelo** [comment]
Thank you for flagging and working on this. I'm happy to help if you run into any issues moving to JoinSet as I wrote most of these instances of tokio::spawn.

Another potential cancelation safety issue to consider in the referenced code is use of 
https://docs.rs/tokio/latest/tokio/io/trait.AsyncWriteExt.html#method.write_all which is not cancel safe.

I don't think the consequences will be too bad canceling in the middle of a multipart upload since  I think the ObjectStore itself should provide some protection.

**Comment by DDtKey** [comment]
It works now
For `ReparitionExec` I had to wrap each task into `JoinSet` and collect them to `Vec<>` to guarantee the order

**Comment by DDtKey** [comment]
> Another potential cancelation safety issue to consider in the referenced code is use of
https://docs.rs/tokio/latest/tokio/io/trait.AsyncWriteExt.html#method.write_all which is not cancel safe.
>
> I don't think the consequences will be too bad canceling in the middle of a multipart upload since I think the ObjectStore itself should provide some protection.

Yeah, sounds reasonable to me!
