### ISSUE TITLE
move make_array array_append array_prepend array_concat function to datafusion-functions-array crate

### ISSUE THREAD

**Issue by guojidan** [apache/arrow-datafusion#9322]
### Is your feature request related to a problem or challenge?

sub-issue of #9285

**Comment by guojidan** [comment]
take

**Comment by jayzhan211** [comment]
I plan to work on `make_array`. Not sure which one are you working on, but I think it is better to move the functions one by one unless they are similar.

**Comment by guojidan** [comment]
I already do make_array array_append array_prepend array_concat, because this function is related in `optimizer`

**Comment by Lordworms** [comment]
You can leave Range, since I would do to cover this issue #9323

**Comment by guojidan** [comment]
I changed this issue title, as @jayzhan211 said, it is better to move the functions one by one unless they are similar.
