### ISSUE TITLE
add 'unnest' table function 

### ISSUE THREAD

**Issue by l1t1** [apache/arrow-datafusion#9324]
### Is your feature request related to a problem or challenge?

the 'unnest' table function reads an array or list, and out put a table

### Describe the solution you'd like

the result is same as that of postgresql
```sql
select unnest(ARRAY[1,2,3]);
 unnest
--------
      1
      2
      3

select * from unnest(ARRAY[1,2,3]);
 unnest
--------
      1
      2
      3
```

**Comment by jayzhan211** [comment]
I think it is duplicated issue from #6555
btw, first example is implemented

**Comment by l1t1** [comment]
when will the function available?

**Comment by jayzhan211** [comment]
first one should be available now.
second one it not planned

**Comment by jonahgao** [comment]
take

**Comment by jonahgao** [comment]
`Unnest` seems to be recognized as a [TableFactor](https://github.com/sqlparser-rs/sqlparser-rs/blob/1a07c5d67c13c0b635cfe0b3e6b13b5be6cae275/src/ast/query.rs#L723) in `sqlparser-rs`, and implementing support for it in DataFusion might be straightforward.

I'll work on this issue after PR #9342.
