### ISSUE TITLE
Substrait : Get a ScalarFunction from name

### ISSUE THREAD

**Issue by yyy1000** [apache/arrow-datafusion#9336]
### Is your feature request related to a problem or challenge?

Part of #9285
Substrait only register BuiltinScalarFunction.
If we port BuiltInFunctons to datafusion-functions-* crates, then substrait can't call ScalarFunction because they can't find, see: https://github.com/apache/arrow-datafusion/pull/9313#discussion_r1498624486

### Describe the solution you'd like

I'm not quiet clear how to solve this, maybe we can register the functions in datafusion-functions-* like before, i.e. using an enum to contain all functions?

**Comment by jayzhan211** [comment]
\take

**Comment by alamb** [comment]
Thank you @jayzhan211 🙏
