### ISSUE TITLE
Add support for TRIM BOTH/LEADING/TRAILING

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#935]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
The more standard SQL datafusion supports, the easier it will be to integrate it into the rest of the analytics ecosystem

**Describe the solution you'd like**
I would like to be able to run the following queries without error:

```shell
cargo run --bin datafusion-cli
```

```sql
-- works
SELECT TRIM('  bar   ');

-- does not work (examples from mysql)
SELECT TRIM(LEADING 'x' FROM 'xxxbarxxx');
SELECT TRIM(BOTH 'x' FROM 'xxxbarxxx');
SELECT TRIM(TRAILING 'xyz' FROM 'barxxyz');
```

Actual output:
```sql
> SELECT TRIM('  bar   ');

+------------------------+
| trim(Utf8("  bar   ")) |
+------------------------+
| bar                    |
+------------------------+
1 row in set. Query took 0.003 seconds.


> SELECT TRIM(LEADING 'x' FROM 'xxxbarxxx');
Plan("TRIM LEADING is not yet supported ")

> SELECT TRIM(BOTH 'x' FROM 'xxxbarxxx');
Plan("TRIM BOTH is not yet supported ")

> SELECT TRIM(TRAILING 'xyz' FROM 'barxxyz');
Plan("TRIM TRAILING is not yet supported ")
```

**Describe alternatives you've considered**

**Additional context**
SQL (postgres and mysql) offer support for extended `TRIM` syntax, and with https://github.com/apache/arrow-datafusion/pull/934 DataFusion's SQL parser can parse this syntax.

Here are links to the references:
* https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_trim
* https://www.postgresql.org/docs/current/functions-string.html

Here is a copy of the syntax from the mysql manual:

```
TRIM([{BOTH | LEADING | TRAILING} [remstr] FROM] str), TRIM([remstr FROM] str)

Returns the string str with all remstr prefixes or suffixes removed. If none of the specifiers BOTH, LEADING, or TRAILING is given, BOTH is assumed. remstr is optional and, if not specified, spaces are removed.

mysql> SELECT TRIM('  bar   ');
        -> 'bar'
mysql> SELECT TRIM(LEADING 'x' FROM 'xxxbarxxx');
        -> 'barxxx'
mysql> SELECT TRIM(BOTH 'x' FROM 'xxxbarxxx');
        -> 'bar'
mysql> SELECT TRIM(TRAILING 'xyz' FROM 'barxxyz');
        -> 'barx'
```

Note that thanks to @seddonm1  DataFusion already has the `ltrim` and `rtrim` functions

So supporting this syntax:
```sql
> SELECT TRIM(TRAILING 'xyz' FROM 'barxxyz');
Plan("TRIM TRAILING is not yet supported ")
```

Should end up creating the same plan as this (which works today):

```sql
> SELECT RTRIM('barxxyz', 'xyz');
+------------------------------------+
| rtrim(Utf8("barxxyz"),Utf8("xyz")) |
+------------------------------------+
| bar                                |
+------------------------------------+
1 row in set. Query took 0.003 seconds.
```

**Comment by seddonm1** [comment]
I believe this should be very easy now the parser supports it and just needs a tiny bit of plumbing and a few tests.

**Comment by alamb** [comment]
> I believe this should be very easy now the parser supports it and just needs a tiny bit of plumbing and a few tests.

Indeed -- a perfect good first issue
