### ISSUE TITLE
Schma merging check is too strict

### ISSUE THREAD

**Issue by sergiimk** [apache/arrow-datafusion#936]
**Describe the bug**
I am attempting to read two parquet files (produced by Spark) as a single table and getting error:
```
Error during planning: The Parquet files have 2 different schemas and DataFusion does not yet support schema merging
```

Inspecting both files with `parquet-schema` shows identical schemas:
```
message spark_schema {
  required int96 system_time;
  optional int32 date (DATE);
  optional int64 usd_am (DECIMAL(18,4));
  optional int64 usd_pm (DECIMAL(18,4));
  optional int64 gbp_am (DECIMAL(18,4));
  optional int64 gbp_pm (DECIMAL(18,4));
  optional int64 euro_am (DECIMAL(18,4));
  optional int64 euro_pm (DECIMAL(18,4));
}
```

Inspecting with `parquet-meta` seems to show only one relevant difference:
* First file has `extra:       org.apache.spark.version = 3.0.1`
* Second file has `extra:       org.apache.spark.version = 3.1.2` 

**To Reproduce**
Place attached files in a directory and use `ExecutionContext::read_parquet` API.
[example.tar.gz](https://github.com/apache/arrow-datafusion/files/7036002/example.tar.gz)

**Expected behavior**
Insignificant differences in metadata are ignored and true cases that require schema merging are reported.

**Comment by houqp** [comment]
perhaps we should just ignore the metadata hashmap entirely?

**Comment by Smurphy000** [comment]
I can take a look at this

**Comment by Smurphy000** [comment]
@houqp I have tried using the `try_merge` on the schema, but I am not sure when it might not be ok to ignore the metadata hashmap. Do you think we should somehow make it optional but ignore by default? I can't think of a case of the top of my head right now, but somebody else may want to be strict on metadata when possibly merging schemas

**Comment by houqp** [comment]
I also cannot think of a good use-case for enforcing strict metadata on schema merge, on the other hand, it's very common to have slightly different metadata for the files in the same table due to writer version upgrade as demonstrated in the bug report. My preference would be to not make it configurable for now since it will add complexity to the API. We can make it configurable later in the future when valid use-cases are reported to us.

**Comment by Smurphy000** [comment]
I currently just changed the check to compare on schema fields, since the `try_merge` is in arrow and it does try to merge metadata I thought maybe we could just resolve this issue with this simple change.

**Comment by houqp** [comment]
Thanks @Smurphy000 ! I think that's good enough, we can tackle that as a follow up task, which we already have an open issue at https://github.com/apache/arrow-datafusion/issues/132.
