### ISSUE TITLE
Intermittent failure on `dataframe::write_partitioned_parquet_results`

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#9368]
### Describe the bug

`dataframe::write_partitioned_parquet_results` sometimes passes and sometimes fails

This test was recently added in https://github.com/apache/arrow-datafusion/pull/9316

### To Reproduce

Example failure https://github.com/apache/arrow-datafusion/actions/runs/8063185942/job/22024675172

```


---- dataframe::write_partitioned_parquet_results stdout ----
thread 'dataframe::write_partitioned_parquet_results' panicked at datafusion/core/tests/dataframe/mod.rs:1978:5:
assertion `left == right` failed: 

expected:

[
    "+-----+-----+",
    "| c1  | c2  |",
    "+-----+-----+",
    "| abc | 123 |",
    "| def | 456 |",
    "+-----+-----+",
]
actual:

[
    "+-----+-----+",
    "| c1  | c2  |",
    "+-----+-----+",
    "| def | 456 |",
    "| abc | 123 |",
    "+-----+-----+",
]
```

### Expected behavior

I think we can just update the test to use `assert_batches_sorted_eq`  https://docs.rs/datafusion/latest/datafusion/macro.assert_batches_sorted_eq.html so that the ordering is normalized

**Comment by alamb** [comment]
I think this is a good first issue as it would let someone figure out how to run the tests / make a PR

**Comment by alamb** [comment]
Dupe of  #9358

**Comment by tshauck** [comment]
Eeek, sorry for introducing this

**Comment by alamb** [comment]
> Eeek, sorry for introducing this

No worries -- it was fixed asap!
