### ISSUE TITLE
Add "show" support to DataFrame API

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#937]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
While developing projects with datafusion, often times it is useful to preview the output.

Right now it is somewhat awkward to print the results of a DataFrame to `stdout` as it requires something like the following from the examples

```rust
    let df = ctx
        .read_parquet(filename)?
        .select_columns(&["id", "bool_col", "timestamp_col"])?
        .filter(col("id").gt(lit(1)))?;

    let results = df.collect().await?;
    pretty::print_batches(&results)?;
```

**Describe the solution you'd like**
it would be nice to allow a user to simply call a `show` function

```rust
    let df = ctx
        .read_parquet(filename)?
        .select_columns(&["id", "bool_col", "timestamp_col"])?
        .filter(col("id").gt(lit(1)))?;

    df.show().await;
```

**Describe alternatives you've considered**

**Additional context**

**Comment by francis-du** [comment]
I will open an issue by myself next time, thanks for your job.
