### ISSUE TITLE
Remove instr code, add instr as an alias for strpos

### ISSUE THREAD

**Issue by Omega359** [apache/arrow-datafusion#9391]
### Is your feature request related to a problem or challenge?

strpos:
```
Returns the starting position of a specified substring in a string. Positions begin at 1. If the substring does not exist in the string, the function returns 0.

strpos(str, substr)
```
instr:
```
Returns the location where substr first appeared in str (counting from 1). If substr does not appear in str, return 0.

instr(str, substr)
```

These seem to be functionally identical but have separate implementations. There isn't a good reason why instr shouldn't just be an alias for strpos that I can see.

### Describe the solution you'd like

instr function is removed and replaced with an alias to strpos. Docs and everything else updated to reflect the change.

### Describe alternatives you've considered

Leave the code duplication in place.

### Additional context

Noted in #9026

**Comment by SteveLauC** [comment]
take
