### ISSUE TITLE
Format plan with line number.

### ISSUE THREAD

**Issue by my-vegetable-has-exploded** [apache/arrow-datafusion#9443]
### Is your feature request related to a problem or challenge?

When I try to complete #8416 , I found it hard to review changes in plan in tpch sqllogictests.

I think the main reason is that CoalesceBatchesExec and RepartitionExec::RoundRobinBatch would make git diff aligns the result in unexcepted position. 

Takes q11.slt.part as example,  it aligns CoalesceBatchesExec and RepartitionExec::RoundRobinBatch but ignore the `--` changes. 

![图片](https://github.com/apache/arrow-datafusion/assets/48236141/1d63f320-8108-4aff-ad75-dd604f4fc8a5)

If we remove CoalesceBatchesExec and RepartitionExec::RoundRobinBatch, it works well to find the `--` changes. 

![图片](https://github.com/apache/arrow-datafusion/assets/48236141/c2840127-5fc5-4215-8707-c7edc314feb8)

![图片](https://github.com/apache/arrow-datafusion/assets/48236141/9cd56e42-fc25-4514-aba3-72b9c3212fc0)

**Comment by my-vegetable-has-exploded** [comment]
I think adding a line number to the front of each line is a easier way.

**Comment by alamb** [comment]
Adding a line number seems like a reasonable thing to try to me. 

The reason we had `--` as the prefix was that sqllogictest stripped off leading  spaces

**Comment by my-vegetable-has-exploded** [comment]
Maybe we can mark it as a 'good first issue' if needed, and slt tests can regenerate by running `cargo test --test sqllogictests -- --include-tpch --complete`.

**Comment by alamb** [comment]
> Maybe we can mark it as a `good first issue` if needed, and slt tests can regenerate by running `cargo test --test sqllogictests -- --include-tpch --complete`.

Good idea @my-vegetable-has-exploded  -- I hav done so. Thank you

**Comment by duongcongtoai** [comment]
Hi, i would love to take this issue as a starting point

**Comment by my-vegetable-has-exploded** [comment]
> Hi, i would love to take this issue as a starting point

I think it maybe helpful to take a breif look `explain.rs`  
https://github.com/apache/arrow-datafusion/blob/2f1c3ab679fd553ea9e18067ed894fc6cf1f567a/datafusion/physical-plan/src/explain.rs#L126-L178

**Comment by duongcongtoai** [comment]
hi @alamb could you help me give one more review to this PR?

**Comment by alamb** [comment]
Thanks again for https://github.com/apache/arrow-datafusion/pull/10019 @duongcongtoai  -- great stuff. 🚀
