### ISSUE TITLE
Update `trim` to match Postgres/duckdb

### ISSUE THREAD

**Issue by tshauck** [apache/arrow-datafusion#9487]
### Is your feature request related to a problem or challenge?

I'm not sure if this is a bug or not, but generally, the `trim` function does not behave as I'd expect (or the same way postgres/duckdb handle it)...

E.g. in postgres:

```
SELECT trim('test.com', '.com');
btrim 
-------
 test
```

I.e. it seems to be using btrim and removing the second argument.

This behavior is the same in duckdb:

```
SELECT TRIM('test.com', '.com');
test
```

In datafusion, the following happens:

```
❯ SELECT TRIM('test.com', '.com') AS t;
+----------+
| t        |
+----------+
| test.com |
+----------+
1 row in set. Query took 0.021 seconds.
```

Calling `btrim` directly does work as expected...

```
❯ SELECT BTRIM('test.com', '.com') AS t;
+------+
| t    |
+------+
| test |
+------+
1 row in set. Query took 0.003 seconds.
```

### Describe the solution you'd like

I'd like `trim` to work on whatever the second parameter is without using `btrim` directly.

**Comment by Weijun-H** [comment]
It should be a bug.
https://github.com/apache/arrow-datafusion/blob/f3836a53122e86f2b73c25557deaa5b800e488e9/datafusion/physical-expr/src/functions.rs#L733-L741

**Comment by tshauck** [comment]
Cool, I can't change the GitHub issue, but I'll look into it. I think the issue is upstream as the second arg isn't making it into `btrim`...

```
❯ SELECT TRIM('test.com', '.com');
calling trim with: [StringArray
[
  "test.com",
]]
+------------------------+
| trim(Utf8("test.com")) |
+------------------------+
| test.com               |
+------------------------+
1 row in set. Query took 0.002 seconds.
```

I added a debug statement to show the args, and note the inferred column name.

**Comment by tshauck** [comment]
Hmmm... maybe not supported in `sqlparser`, except for snowflake and bigquery? Maybe wroth raising an issue there?

https://github.com/sqlparser-rs/sqlparser-rs/blob/5da66adda99d8cf7a36c1512d41815d94ce542b5/src/ast/mod.rs#L571-L582

**Comment by tshauck** [comment]
Made a draft PR here that I think fixes the bug: https://github.com/apache/arrow-datafusion/pull/9521
