### ISSUE TITLE
Port `StringToArray` to `function-arrays`

### ISSUE THREAD

**Issue by jayzhan211** [apache/arrow-datafusion#9497]
### Is your feature request related to a problem or challenge?

It is part of https://github.com/apache/arrow-datafusion/issues/9285. 
It is a good first issue. ArrayToString is already done in https://github.com/apache/arrow-datafusion/pull/9113, so you can easily find out which files are needed to modify.

#9352 #9425 are also nice for reference

### Describe the solution you'd like

Port StringToArray.

**Comment by erenavsarogullari** [comment]
@jayzhan211 I can work on this

**Comment by erenavsarogullari** [comment]
take
