### ISSUE TITLE
datafusion-cli cursor isn't on the right position in windows 7 cmd

### ISSUE THREAD

**Issue by l1t1** [apache/arrow-datafusion#9501]
### Describe the bug

use pageup key to get the history command,
if I move the cursor to the left position of g and press `(`, it insert the `(` after g
```
❯ select g(enerate_series(1,10);
```

### To Reproduce
```
datafusion-cli
```
input 

````
select g(enerate_series(1,10);
+-------------------------------------+
| generate_series(Int64(1),Int64(10)) |
+-------------------------------------+
| [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]     |
+-------------------------------------+
```

then 
use pageup key to get the history command,
if I move the cursor to the left position of g and press `(`


### Expected behavior

insert `(` before g

### Additional context

_No response_

**Comment by l1t1** [comment]
maybe the root of the problem is the prompt `❯` is a utf-8 character, it occupied multi-bytes, suggest use an ASCII charactor, such as 
`>`

**Comment by l1t1** [comment]
this prompt displayed as a box in cmd of windows 7
![2024-03-13_082138](https://github.com/apache/arrow-datafusion/assets/23301704/82637d20-ee44-4fe6-b2e8-39bb2406909f)

**Comment by alamb** [comment]
I think this is a good first issue for someone with a windows machine to test on

**Comment by colommar** [comment]
@alamb Hi! I have a windows machine and changed all those `❯` to `>`. Is this OK?
And I wanna test if the change does work how can I rebuild the datafusion to update the change by using the command `datafusion-cli`

**Comment by alamb** [comment]
Great @colommar !

To test the change locally you can do something like this
```shell
cd datafusion/datafusion-cli
cargo run
```

**Comment by colommar** [comment]
@l1t1 I guess it was fine now. Can you help me test it on your pc?

**Comment by l1t1** [comment]
could you attach the binary file?

**Comment by l1t1** [comment]
> > could you attach the binary file?
> 
> @l1t1 Sure! Is this OK? Does it help you? [datafusion-cli.zip](https://github.com/apache/arrow-datafusion/files/14934061/datafusion-cli.zip)

it works, very thanks
