### ISSUE TITLE
Move  date_part, date_trunc, date_bin functions to datafusion-functions

### ISSUE THREAD

**Issue by Tangruilin** [apache/arrow-datafusion#9511]
### Is your feature request related to a problem or challenge?

As part of https://github.com/apache/arrow-datafusion/issues/9285 the date* datetime functions should be migrated to the new datafusion-functions crate in the new structure

### Describe the solution you'd like

Functions are migrated to the new crate and use the new patterns as described in https://github.com/apache/arrow-datafusion/issues/9286 & https://github.com/apache/arrow-datafusion/pull/9216,

**Comment by Tangruilin** [comment]
take

**Comment by Omega359** [comment]
already covered by https://github.com/apache/arrow-datafusion/pull/9435. Please check the issue tracker first :)

**Comment by alamb** [comment]
Indeed, closing as a dupe of https://github.com/apache/arrow-datafusion/issues/9421
