### ISSUE TITLE
Inconsistent behavior for Interval type with document

### ISSUE THREAD

**Issue by yyy1000** [apache/arrow-datafusion#9525]
### Describe the bug

When I take #9524, I found the behavior of the function is inconsistent with the actual CLI output.
Docs:
https://github.com/apache/arrow-datafusion/blob/eebdbe8be61ba1944b7a7e14d3edeed0259a7d74/docs/source/user-guide/sql/data_types.md?plain=1#L32-L38
Output from local CLI:
DataFusion CLI v35.0.0
❯ select arrow_typeof(interval '1 month');
+---------------------------------------------------------------------+
| arrow_typeof(IntervalMonthDayNano("79228162514264337593543950336")) |
+---------------------------------------------------------------------+
| Interval(MonthDayNano)                                              |
+---------------------------------------------------------------------+
1 row in set. Query took 0.001 seconds.

### To Reproduce

Run the same sql

### Additional context

I'm researching whether it's because the docs is outdated or there's some issue related to Interval type

**Comment by yyy1000** [comment]
take

**Comment by alamb** [comment]
I don't think this is related to `arrow_typeof`, I think think it is that the `interval ` syntax always returns a type of `IntervalMonthDayNano` ... for reasons I can't remember now.

**Comment by yyy1000** [comment]
> I don't think this is related to `arrow_typeof`, I think think it is that the `interval ` syntax always returns a type of `IntervalMonthDayNano` ... for reasons I can't remember now.

Yeah, I also think so.
I found the reason is https://github.com/apache/arrow-datafusion/issues/5801
So I think for this issue, I can just update the document.
Also I have a question, when `IntervalYearMonth` will be used?  If it will not be used maybe we can remove this type?

**Comment by alamb** [comment]
> Also I have a question, when `IntervalYearMonth` will be used? If it will not be used maybe we can remove this type? @alamb

I don't understand this question -- I think the idea is that IntervalYearMonth is the most general interval type that can support most non fixed width intervals (e.g. 1 month vs 28, 29, 30, 31 days)
