### ISSUE TITLE
Replace `GetFieldAccessExpr::NamedStructField` with `ScalarFunction::Struct`

### ISSUE THREAD

**Issue by jayzhan211** [apache/arrow-datafusion#9532]
### Is your feature request related to a problem or challenge?

Follow up from #9492, we replace ListRange and ListIndex to array_slice and array element respectively.
`NamedStructField` is also possible to be rewritten to `Struct` function.

https://github.com/apache/arrow-datafusion/blob/f1f09653319aea3186c2b1f9ca103ef7030c2da1/datafusion/physical-expr/src/expressions/get_indexed_field.rs#L138-L162

### Describe the solution you'd like

Replace `NamedStructField` with Struct function
I think it may be relative easy issue since it should be similar to #9492. But, not sure if it is easy enough to be a good first issue. I think you can consider it as good second issue 😆

**Comment by alamb** [comment]
Specificlaly, I think we would need to:
1. Add a "get_field(struct_array, field_name)" function
2. Use that function instead of `NamedStructField`

**Comment by yyy1000** [comment]
I port Struct function in https://github.com/apache/arrow-datafusion/pull/9546
I think after that I can take this issue. :)

**Comment by yyy1000** [comment]
take

**Comment by yyy1000** [comment]
Ah, I found the `struct` function has different meaning than `NamedStructField`, so I'm trying to implement `get_field(struct_array, field_name)` as @alamb said. It will take some time because I kind of stuck on `return_type_from_exprs` method. (I think the return type will depends on the param)

**Comment by yyy1000** [comment]
Update: I finished the PR at #9563
Could you help me review it when you are available? @alamb @jayzhan211
Thanks!
