### ISSUE TITLE
Move take concat, concat_ws, ends_with, initcap, to datafusion-functions

### ISSUE THREAD

**Issue by Tangruilin** [apache/arrow-datafusion#9540]
### Is your feature request related to a problem or challenge?

As part of https://github.com/apache/arrow-datafusion/issues/9285 the remaining datetime functions should be migrated to the new datafusion-functions crate in the new structure

### Describe the solution you'd like

Functions are migrated to the new crate and use the new patterns as described in https://github.com/apache/arrow-datafusion/issues/9286 & https://github.com/apache/arrow-datafusion/pull/9216

**Comment by Omega359** [comment]
How is the progress going on this ticket @Tangruilin ?

**Comment by Omega359** [comment]
take

**Comment by Tangruilin** [comment]
> take

You can work with it.

Thanks~~~

**Comment by Omega359** [comment]
This is ready to push but I'm going to wait for #9939 to land first before pushing this as this will mean that BuiltinScalarFunction will be removed along with everything that depends on it.
