### ISSUE TITLE
Non deterministic result for window function

### ISSUE THREAD

**Issue by jayzhan211** [apache/arrow-datafusion#9544]
### Is your feature request related to a problem or challenge?

This query failed sometimes.
https://github.com/apache/arrow-datafusion/actions/runs/8222295671/job/22483743010
https://github.com/apache/arrow-datafusion/actions/runs/8221664632/job/22482282908?pr=9524

It is not always reproducible.
```
[SQL] select lag(a) over () as x1
        from
        (select 2 id, 'b' a union all select 1 id, null a union all select 3 id, null);
[Diff] (-expected|+actual)
    NULL
Error: Execution("1 failures")
    NULL
-   b
+   NULL
at test_files/window.slt:4302
```
### Describe the solution you'd like

Not sure what is the root cause yet. We expect not to meet this failure again.

**Comment by mustafasrepo** [comment]
This problem is fixed with the [PR9559](https://github.com/apache/arrow-datafusion/pull/9559). I wasn't aware of this issue. Hence didn't mention it in the PR.

**Comment by jayzhan211** [comment]
> Thanks @jayzhan211 for this issue. This problem is fixed with the [PR9559](https://github.com/apache/arrow-datafusion/pull/9559). I wasn't aware of this issue. Hence didn't mention this issue in the PR. If you agree that this problem no longer happens, we can close this issue.

I see, thanks @mustafasrepo
