### ISSUE TITLE
Eliminate code duplication between math UDFs

### ISSUE THREAD

**Issue by jonahgao** [apache/arrow-datafusion#9552]
### Is your feature request related to a problem or challenge?

The codes in [acos.rs](https://github.com/apache/arrow-datafusion/blob/main/datafusion/functions/src/math/acos.rs), [asin.rs ](https://github.com/apache/arrow-datafusion/blob/main/datafusion/functions/src/math/asin.rs) under the new functionn packege and codes in #9535 are quite similar.
Perhaps they could be simplified with the help of a common macro.

### Describe the solution you'd like

A common macro similar to [math_unary_function](https://github.com/apache/arrow-datafusion/blob/88187d4dcc060d4d8ae7c680594e72fdfbc24c6a/datafusion/physical-expr/src/math_expressions.rs#L83), used to define math UDFs.

**Comment by alamb** [comment]
Thank you @jonahgao  -- I agree this would be very helpful

**Comment by jonahgao** [comment]
take
