### ISSUE TITLE
Inconsistent cast behavior

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#957]
**Describe the bug**

I have a string column containing floating-point values but I want to cast this to an integer using `CAST(col AS int)` but this fails with `Cast error: Cannot cast string '1.20' to value of arrow::datatypes::types::Int32Type type`. However, we support casting floats to ints and I can do `CAST(CAST(col AS float) AS int)` to work around this but if I can do that, why can I not just cast to int directly? 

Is this the intended behavior?

**To Reproduce**

```bash
echo "1.2" > foo.csv
```

CLI:

```
> CREATE EXTERNAL TABLE foo (bar VARCHAR) STORED AS CSV LOCATION 'foo.csv';
0 rows in set. Query took 0.001 seconds.

> SELECT bar FROM foo;
+-----+
| bar |
+-----+
| 1.2 |
+-----+
1 row in set. Query took 0.018 seconds.

> SELECT CAST(bar AS int) FROM foo;
ArrowError(ExternalError(ArrowError(CastError("Cannot cast string '1.2' to value of arrow::datatypes::types::Int32Type type"))))

> SELECT CAST(CAST(bar as float) as int) FROM foo;
+-------------------------------------+
| CAST(CAST(bar AS Float64) AS Int32) |
+-------------------------------------+
| 1                                   |
+-------------------------------------+
1 row in set. Query took 0.017 seconds.
```

**Expected behavior**
I would expect the cast to work but if this is working as intended then it would be good to document the behavior in the user guide.

**Additional context**
None

**Comment by alamb** [comment]
I think this would involve writing some tests and updating the coercion rules in https://github.com/apache/arrow-datafusion/blob/master/datafusion/src/physical_plan/expressions/coercion.rs

**Comment by j-a-m-l** [comment]
@alamb That code delares which type coercions are available, but, maybe I'm missing something, I don't see any rule that states which numeric type should be chosen to coerce strings or the actual code to convert them from utf8 to numeric.

**Comment by alamb** [comment]
> That code declares which type coercions are available, but, maybe I'm missing something, I don't see any rule that states which numeric type should be chosen to coerce strings or the actual code to convert them from utf8 to numeric.

The arrow cast kernel https://docs.rs/arrow/6.0.0/arrow/compute/kernels/cast/index.html contains the code to covert `utf8` to many differnet types -- see https://github.com/apache/arrow-rs/blob/master/arrow/src/compute/kernels/cast.rs 

I think the issue that is described on this bug is that by desigh DF won't auto cast (coerce) in a way that loses data (so it won't coerce  `1.2` to an int because it loses precision (aka loses the .2)).

However, if the user explicitly says `CAST(col as INT)` the idea is that they are specifying the behavior and thus DataFusion should truncate them correctly

**Comment by mrob95** [comment]
Did a little digging on this. Postgres gives a similar error:
```
postgres=# select * from test;
    abc
-----------
 1.2
 1.2 hello
 1
(3 rows)

postgres=# select abc, cast(abc as int) from test;
ERROR:  invalid input syntax for type integer: "1.2"
```

The code which actually does the cast and produce is the error message in the OP is in the [arrow cast kernel here] (https://github.com/apache/arrow-rs/blob/master/arrow/src/compute/kernels/cast.rs#L1477). It calls the `parse` function from the `lexical_core` library to do the actual parsing.

`lexical_core` has an alternative function - `parse_partial`, which ["parses until an invalid digit is found (or the end of the string), returning the number of processed digits and the parsed value until that point."](https://docs.rs/lexical-core/latest/lexical_core/fn.parse_partial.html).

Options I can see for closing this issue are:
1. Accept the current behaviour, which seems to match what postgres does.
2. Update the arrow kernel to use `parse_partial`, which is more lenient about the input format, for all casts.
3. Add a `strict` flag to the arrow `CastOptions` struct, and then expose cast options to datafusion in some way.

**Comment by andygrove** [comment]
Looks like this can be closed.
