### ISSUE TITLE
Support `AtTimeZone` node in `SqlToRel`

### ISSUE THREAD

**Issue by rebasedming** [apache/arrow-datafusion#9580]
### Is your feature request related to a problem or challenge?

I would like `SqlToRel` to be able to construct a `LogicalPlan` from the a query string containing the `AT TIME ZONE` clause. Right now it's unsupported:

```sql
create table t (a timestamptz);
insert into t values('2000-12-01 04:04:12');
select a AT TIME ZONE 'UTC' from t;
This feature is not implemented: Unsupported ast node in sqltorel: AtTimeZone { timestamp: Identifier(Ident { value: "a", quote_style: None }), time_zone: "UTC" }
```

### Describe the solution you'd like

`AT TIME ZONE` clauses can be parsed and converted into logical plans.

**Comment by tinfoil-knight** [comment]
take

**Comment by tinfoil-knight** [comment]
This error (`Unsupported ast node in sqltorel`) comes from this line:
https://github.com/apache/arrow-datafusion/blob/0302d6530a5a7fffe7da40e0f3b13794a9c693ff/datafusion/sql/src/expr/mod.rs#L579

`AtTimeZone` SQL Expr is already provided by `sqlparser`. 

---

**Intended Change**:

Add a condition to handle `SQLExpr::AtTimeZone` in the match case in `sql_expr_to_logical_expr_internal` here:

https://github.com/apache/arrow-datafusion/blob/0302d6530a5a7fffe7da40e0f3b13794a9c693ff/datafusion/sql/src/expr/mod.rs#L162-L172

And add a scalar function to convert a date to a specific time zone as per the HowTo here: https://arrow.apache.org/datafusion/contributor-guide/index.html#how-to-add-a-new-scalar-function

**Comment by alamb** [comment]
> And, add a scalar function to convert a date to a specific time zone as per the HowTo [here](https://arrow.apache.org/datafusion/contributor-guide/index.html#how-to-add-a-new-scalar-function) so that it can be used by `sql_named_function_to_expr` to get the Result.

Since the Timezone is encoded in the DataType I think you could call `Expr::Cast` with a DataType that had the appropriate timezone -- e.g. set the timezone correctly https://docs.rs/arrow/latest/arrow/datatypes/enum.DataType.html#variant.Timestamp and then cast the expression to that type

**Comment by tinfoil-knight** [comment]
> Since the Timezone is encoded in the DataType I think you could call `Expr::Cast` with a DataType that had the appropriate timezone -- e.g. set the timezone correctly [docs.rs/arrow/latest/arrow/datatypes/enum.DataType.html#variant.Timestamp](https://docs.rs/arrow/latest/arrow/datatypes/enum.DataType.html#variant.Timestamp) and then cast the expression to that type
> 
> Thus you may not need to make a new scalar function

Yeah. This worked. Thank you for the suggestion.
