### ISSUE TITLE
to_timestamp benchmark doesn't actually run the test

### ISSUE THREAD

**Issue by Omega359** [apache/arrow-datafusion#9607]
### Describe the bug

the benchmark just calls the to_timestamp function but doesn't actually execute it. It needs to call the correct to_timestamp function with .invoke(...) calls.

### To Reproduce

Run to_timestamp benchmark. The results are far too good

**Comment by Omega359** [comment]
take

**Comment by alamb** [comment]
Related conversation: https://github.com/apache/arrow-datafusion/pull/9601#discussion_r1523677491
