### ISSUE TITLE
Rename `common_runtime` directory to `common-runtime` for consistency with other crate directory names

### ISSUE THREAD

**Issue by andygrove** [apache/arrow-datafusion#9696]
### Is your feature request related to a problem or challenge?

The new `common_runtime` directory uses an underscore as a separator, but other crates, such as `physical-expr` and `functions-array` use a hyphen. I think it would be better to stick to one format.

### Describe the solution you'd like

Rename `common_runtime` directory to `common-runtime` for consistency with other crate directory names

**Comment by alamb** [comment]
I will make a PR for this shortly
