### ISSUE TITLE
COPY TO fails on passing options for format through cli

### ISSUE THREAD

**Issue by tinfoil-knight** [apache/arrow-datafusion#9707]
### Describe the bug

COPY TO fails with `Error: Invalid or Unsupported Configuration: Specify a format for TableOptions` even when valid configuration options are provided for the format.

### To Reproduce

Clone the `main` branch. In the `datafusion-cli` directory, run this command:

`cargo run -- --command "COPY (VALUES (1, 'Foo'), (2, 'Bar')) TO 'test_files/scratch/copy/tab.parquet' STORED AS parquet OPTIONS ('format.compression' 'zstd(10)');"`

### Expected behavior

The command should run without error & the values should be copied to the provided destination.

### Additional context

Running the same query in a SQL Logic Test (`.slt`) doesn't throw any error. See `copy.slt` which has tests with similar commands to the one described above.

The error originates here:
https://github.com/apache/arrow-datafusion/blob/ad8d552b9f150c3c066b0764e84f72b667a649ff/datafusion/common/src/config.rs#L1175-L1180

**Comment by tinfoil-knight** [comment]
take

**Comment by alamb** [comment]
Thank you @tinfoil-knight
