### ISSUE TITLE
`DatafusionError` variant for parameter substitution during logical planning

### ISSUE THREAD

**Issue by hiltontj** [apache/arrow-datafusion#9738]
### Is your feature request related to a problem or challenge?

Currently, when replacing `ParamValue`s during logical planning, if there are missing parameters in what was provided, a `DatafusionError::Internal` will be returned.

For example, in our service, we are passing query parameters via an HTTP request along with a query string. Consider this query:
```
SELECT * FROM foo WHERE bar = $bar
```
We would expect that the user passes something like:
```json
{
  "params": {
    "bar": "baz"
  }
}
```
in the request, along with the query string. But, if they do not, then we would like to return a `4xx` error code, instead of a `5xx`.

### Describe the solution you'd like

It would be nice if a specific variant was returned, e.g., `DatafusionError::MissingParameters`, as this would allow us to handle this error differently than other `Internal` errors.

### Describe alternatives you've considered

We could parse the `Internal` error message, but that is not very convenient.

### Additional context

This is the specific error that we have run into: https://github.com/apache/arrow-datafusion/blob/47f4b5a67ac3b327764cbd4c0f42da7ac44854e5/datafusion/common/src/param_value.rs#L96-L98

We are using a map of named parameters, and not a list, but the `Internal` errors returned from the same function for indexed list parameters there could potentially get similar treatment.

**Comment by alamb** [comment]
I agree an error like `DataFusionError::Execution` or `DataFusionError::Plan` would be better in this case. 

@hiltontj  do you have the exact error message that is being hit (to make it easier to find what part of the code needs to be changed)?

**Comment by hiltontj** [comment]
@alamb - this is the specific error that we have run into: https://github.com/apache/arrow-datafusion/blob/47f4b5a67ac3b327764cbd4c0f42da7ac44854e5/datafusion/common/src/param_value.rs#L96-L98

We are using a map of named parameters, and not a list, but the `Internal` errors returned from the same function for indexed list parameters there could potentially get similar treatment.

**Comment by erratic-pattern** [comment]
I'll put together a PR for this today
