### ISSUE TITLE
[Python] Unable to install requirements.txt

### ISSUE THREAD

**Issue by mmuru** [apache/arrow-datafusion#975]
**Describe the bug**
Try to do local build using the steps in README.md file. The checked in arrow-datafusion/python/requirements.txt is locked in python 3.8 version. 

the step pip install -r requirements.txt throws the below exception and failed to install dependencies.

````
Collecting typed-ast>=1.4.2
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    typed-ast>=1.4.2 from https://files.pythonhosted.org/packages/01/08/0d92feed38a4cafe45bcbd42a2507c1900e9ec1e2e9b5e5a472f8ebfa9bb/typed_ast-1.4.3-cp37-cp37m-macosx_10_9_x86_64.whl#sha256=0fb71b8c643187d7492c1f8352f2c15b4c4af3f6338f21681d3681b3dc31a266 (from black==21.7b0->-r requirements.txt (line 15))
````

**To Reproduce**
Python 3.7.11 version (venv)
pip install -r requirements.txt

**Expected behavior**

It should install all the dependencies without any errors.

**Additional context**

To workaround is to generate requirements.txt using 
````
pip-compile --generate-hashes requirements.in
````
Then pip install -r requirements.txt works in python 3.7

**Comment by houqp** [comment]
@Jimexist do we need to generate the lock files for different versions of python? It looks like typed-ast is not required for python 3.8 anymore, which resulted in pip-compile to not include that in the lock file.

**Comment by Jimexist** [comment]
> @Jimexist do we need to generate the lock files for different versions of python? It looks like typed-ast is not required for python 3.8 anymore, which resulted in pip-compile to not include that in the lock file.

I'm using 3.8.12 and it works. Which version of 3.8 are you using?

**Comment by houqp** [comment]
It works for python 3.8, but not 3.7. I am guessing it's because when we generate the lock file using python 3.8, it didn't include typed-ast, which is needed by 3.7, because typed-ast is not required for 3.8 anymore.
