### ISSUE TITLE
Apply minor refactorings to `functions-array` crate

### ISSUE THREAD

**Issue by erenavsarogullari** [apache/arrow-datafusion#9787]
### Is your feature request related to a problem or challenge?

`functions-array` create is introduced in terms of Epic: #9285. This issue aims to apply following minor refactorings to `functions-array` create:
1- Being added make_scalar_function support to missed invoke functions,
2- Aligning rust-doc across array functions,
3- Removing redundant imports,
4- Fixing typo problems,
5- Rename `core.rs` -> `make_array.rs`.

### Describe the solution you'd like

Apply minor refactorings (listed above section) to `functions-array` create

### Questions:
1- Currently, all array functions are under `src` directory of  `functions-array` crate. Does it make sense to package them by separating from `infra source files` as follows?
```
/functions-array
	/src
		/functions
			array_has.rs
			...
			string.rs
		lib.rs
		macros.rs
		rewrite.rs
		utils.rs
```
2- `array_empty` function is named as `empty`. Should we rename it as `array_empty` to be consistent with other array functions naming convention?

**Comment by erenavsarogullari** [comment]
take

**Comment by jayzhan211** [comment]
1. It makes sense if they are getting more complex, but I think it is not that complex yet. I prefer flat structure
2. I prefer not name them the same as function name. Actually, I prefer core then `make_array`, but it is not a big problem too.

**Comment by erenavsarogullari** [comment]
@jayzhan211 Thanks for reply.
1- Sure, we can revisit this in terms of our new requirements.
2- I was wondering if we need consistency between https://github.com/apache/arrow-datafusion/blob/main/datafusion/functions-array/src/empty.rs#L33 and https://github.com/apache/arrow-datafusion/blob/main/datafusion/functions-array/src/empty.rs#L58. In general, we use `array_*` prefix for array functions naming convention so should we rename `empty` with `array_empty` by aligning with other array functions? It is not big deal, just would double check.
```
select empty(arrow_cast(make_array(1), 'LargeList(Int64)'));
----
false
```

**Comment by jayzhan211** [comment]
> @jayzhan211 Thanks for reply. 1- Sure, we can revisit this in terms of our new requirements. 2- I was wondering if we need consistency between https://github.com/apache/arrow-datafusion/blob/main/datafusion/functions-array/src/empty.rs#L33 and https://github.com/apache/arrow-datafusion/blob/main/datafusion/functions-array/src/empty.rs#L58. In general, we use `array_*` prefix for array functions naming convention so should we rename `empty` with `array_empty` by aligning with other array functions? It is not big deal, just would double check.
> 
> ```
> select empty(arrow_cast(make_array(1), 'LargeList(Int64)'));
> ----
> false
> ```

https://github.com/apache/arrow-datafusion/issues/7290
The name comes from clickhouse, so I think it is fine to name it without  prefix`array`, but I think we can have an alias as `array_empty`.

**Comment by erenavsarogullari** [comment]
Yes, makes sense to follow industry standard. I can create an issue to be defined `array_empty` as alias and follow-up test coverage and documentation.

**Comment by jayzhan211** [comment]
We can update the status about array and list some TODOs
https://github.com/apache/arrow-datafusion/issues/6980

**Comment by erenavsarogullari** [comment]
@jayzhan211 please find `array_empty` and `list_empty` functions support as alias to `empty` function: https://github.com/erenavsarogullari/arrow-datafusion/commit/a9b670ce59c7643dd7808caddba4e323c6d3a2bc. I can submit PR if the direction makes sense. Thanks for early feedback.

**Comment by jayzhan211** [comment]
> @jayzhan211 please find `array_empty` and `list_empty` functions support as alias to `empty` function: [erenavsarogullari@1402a48](https://github.com/erenavsarogullari/arrow-datafusion/commit/1402a48175470d0e996dcec460eb89b4c9d1e313). I can submit PR if the direction makes sense. Thanks for early feedback.

It makes sense.
