### ISSUE TITLE
Is it able to pushdown selections into TableProvider?

### ISSUE THREAD

**Issue by ethe** [apache/arrow-datafusion#979]
`TableProvider` always return all columns in scanning, is it able to pushdown selections into `TableProvider` and return the schema after selections? I think it may be useful to reduce the memory usage in querying. Sorry I am not good at database querying, hope for your reply, thanks.

**Comment by houqp** [comment]
This is already supported in datafusion today. We have a projection push down optimization rule (https://github.com/apache/arrow-datafusion/blob/master/datafusion/src/optimizer/projection_push_down.rs) that generates projected column indexes based on selection plans. Then the vector gets passed in to the scan method at https://github.com/apache/arrow-datafusion/blob/bb616bf94bd952da8cc0c18b20cf33c55c30459e/datafusion/src/datasource/parquet.rs#L135.

**Comment by ethe** [comment]
Thank you, it is not clear about arguments of `scan`, so I missed it.
