### ISSUE TITLE
Ensure DataFusion "works" with the "zip bomb" parquet file

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#9814]
### Is your feature request related to a problem or challenge?

DuckDB wrote a description of how to compress 4PM of data into a small number of bytes:

https://duckdb.org/2024/03/26/42-parquet-a-zip-bomb-for-the-big-data-age

We should make sure DataFusion / arrow-rs does not explode on this file

**Comment by brayanjuls** [comment]
@alamb  What should be the desired outcome? To be able to read it or to throw an error once we identify the parquet may be a "zip bomb". Can I work on this issue?

**Comment by alamb** [comment]
> @alamb What should be the desired outcome? To be able to read it or to throw an error once we identify the parquet may be a "zip bomb". Can I work on this issue?

My desired behavior would be:
1. Running a query that actually reads the file (for example `SELECT SUM(colum) FROM bomb` does not result in an OOM / out of memory
2. The query can be cancelled (e.g. Ctrl-C / dropping the stream) correctly cleans up and stops decoding

**Comment by brayanjuls** [comment]
@alamb  I did three test, the results:

1. The program I did for testing was running forever for this query in my computer, I did not experience OOM contrary the memory consumption was really small 15mb and the cpu consumption was high. I will attach a flame graph for this query. 
Code:
```rust
fn main(){
    bomb_table();
}

#[tokio::main]
async fn bomb_table(){
    let ctx = SessionContext::new();
    ctx.register_parquet("bomb", "path/to/fortytwodotparquet/42.parquet", ParquetReadOptions::default().skip_metadata(false)).await.unwrap();
    let df = ctx.sql("select sum(b) from bomb").await.unwrap();
    df.show().await.unwrap();
}
```
Flame Graph of sum query:
![flamegraph_sum_query](https://github.com/apache/arrow-datafusion/assets/7233005/cf9249ed-d601-4190-80ba-91a184b70556)

2. I was able to successfully cancel the query and the resources in use where clean.
3. I run the following query `SELECT * FROM bomb` to bring everything into memory and the program was killed by OS when it reached the limits of my computer memory. 

Flame Graph of * query:
![flamegraph_fech_all_query](https://github.com/apache/arrow-datafusion/assets/7233005/f854914c-52a0-46df-8cc7-a27b794c1630)

**Comment by alamb** [comment]
Awesome -- thank you @brayanjuls  -- that is both great news and a great analysis. I think with that I would say this issue is complete. 🎩 👌
