### ISSUE TITLE
Wanting to contribute to project where to start?

### ISSUE THREAD

**Issue by fabianmurariu** [apache/arrow-datafusion#983]
The project looks very interesting and I'd like to contribute but don't know where to start. After watching CMU Database Group course on Intro to Database Systems arrow-datafusion looks perfectly to get my hands dirty on writing SQL engines.

On other projects the easier issues have a tag like `low_hanging_fruit` so newcomers can have a peak.

I see some date functions are missing but I'm unsure which ones. I'd eventually like to work on the query optimizer on join ordering and unnesting but now I'm looking for something to start with.

**Comment by nevi-me** [comment]
Welcome Fabian

There's a "good first issue" label. Have a look at these issues https://github.com/apache/arrow-datafusion/labels/good%20first%20issue
