### ISSUE TITLE
CI test failing on master due to clippy

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#985]
**Describe the bug**
The `clippy` linting CI check is failing on master. For example:
https://github.com/apache/arrow-datafusion/runs/3559103073

```
error: constructor `nth_value` has the same name as the type
  --> datafusion/src/physical_plan/expressions/nth_value.rs:81:5
   |
81 | /     pub fn nth_value(
82 | |         name: impl Into<String>,
83 | |         expr: Arc<dyn PhysicalExpr>,
84 | |         data_type: DataType,
...  |
97 | |         }
98 | |     }
   | |_____^
   |
   = note: `-D clippy::self-named-constructors` implied by `-D warnings`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#self_named_constructors
```

This is likely caused by the 1.55 rust release: https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1550-2021-09-09

**Comment by alamb** [comment]
I believe https://github.com/apache/arrow-datafusion/pull/910 from @Igosuki has a fix for this issue. I will try and break that change out and get a separate PR up for it

**Comment by Igosuki** [comment]
@alamb Rebased the #910  on top of this
