### ISSUE TITLE
move Cbrt, Cos, Cosh, Degrees to datafusion-functions

### ISSUE THREAD

**Issue by Omega359** [apache/arrow-datafusion#9862]
### Is your feature request related to a problem or challenge?

As part of https://github.com/apache/arrow-datafusion/issues/9285 move the Cbrt,  Cos, Cosh, Degrees functions to the new datafusion-functions crate in the new structure.

### Describe the solution you'd like

Functions are migrated to the new crate and use the new patterns as described in https://github.com/apache/arrow-datafusion/issues/9286 & https://github.com/apache/arrow-datafusion/pull/9216

**Comment by erenavsarogullari** [comment]
take

**Comment by erenavsarogullari** [comment]
@Omega359 I need to address this issue partially. We can update the title for `cbrt`, `cos`, `cosh`, `degrees` functions. Thanks
