### ISSUE TITLE
Make `ExecutionPlan` implementations immutable

### ISSUE THREAD

**Issue by rdettai** [apache/arrow-datafusion#987]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
This is a follow up to #962.

Currently we cannot compute all the statistics at instantiation because some implementations of the `ExecutionPlan` trait are mutable. 

**Describe the solution you'd like**
The proposition is to make all ExecutionPlan implementations immutable and then transform the statistics method signature to:
```fn statistics(&self) -> &Statistics;```

**Describe alternatives you've considered**
Instead of trying to compute the statistics at instantiation, a solution could be to have `statistics(&mut self)` and cache the result from there. But if the plan is mutable this is error prone because the cached statistics needs to be correctly invalidated when updates occur.

**Additional context**
https://github.com/apache/arrow-datafusion/pull/965#discussion_r705963059

**Comment by mingmwang** [comment]
Is it still valid. I think today's ExecutionPlan is already immutable except for the run time plan metrics.

**Comment by rdettai** [comment]
I think a lot of things have changed since I opened this. Closing it.
