### ISSUE TITLE
expr.slt test failing in main

### ISSUE THREAD

**Issue by Omega359** [apache/arrow-datafusion#9891]
### Describe the bug

```
Running "expr.slt"
External error: query failed: DataFusion error: Schema error: No field named t2."struct(t1.time,t1.load1,t1.load2,t1.host)". Valid fields are t2."named_struct(Utf8(""c0""),t1.time,Utf8(""c1""),t1.load1,Utf8(""c2""),t1.load2,Utf8(""c3""),t1.host)".
[SQL] select t2."struct(t1.time,t1.load1,t1.load2,t1.host)"['c3'] as host, sum(coalesce(t2."struct(t1.time,t1.load1,t1.load2,t1.host)")['c1']) from (select struct(time,load1,load2,host) from t1) t2 where t2."struct(t1.time,t1.load1,t1.load2,t1.host)"['c3'] IS NOT NULL group by t2."struct(t1.time,t1.load1,t1.load2,t1.host)"['c3'] order by host;
at test_files/expr.slt:2290
```

Seems to be related possibly to an interaction between #9743 and #9871. Seen in CI run on #9878 and locally.

### To Reproduce

```
cargo test --test sqllogictests -- expr
```

### Expected behavior

test passes

**Comment by Lordworms** [comment]
I can try to fix it, (no guarantees since not familiar with the struct compare code)

**Comment by Lordworms** [comment]
Seems like when encountering the selection(where) part of Select, the parser would not parse the struct into SQLExpr::Struct, instead, they parse it into a CompoundIdentifier. I may file a PR in SQLparser and retry

**Comment by jayzhan211** [comment]
Why is the error not failed in CI previously 😕 It seems like a non-trivial fix, should we revert the commit in this case?

**Comment by alamb** [comment]
Looks like a logical conflict with https://github.com/apache/arrow-datafusion/pull/9743

**Comment by alamb** [comment]
Specifically since #9743 changed the name of the columns, this test would have had to use the new names.

**Comment by alamb** [comment]
Thank you very much @Omega359 and @jayzhan211  -- sorry for the disruption
