### ISSUE TITLE
Disable parquet bloom filters for `UInt8`, `Int8`, `UInt16` and `Int16` columns

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#9914]
### Describe the bug

As @progval discovered, bloom filters on these types return no results (incorrect answers): https://github.com/apache/arrow-datafusion/issues/9779

Technically I think this is a regression as previously bloom filters on these column types would be ignored

### To Reproduce

Not sure (see unit tests for parquet filters, eg. that were added in https://github.com/apache/arrow-datafusion/pull/9770)

### Expected behavior

I think we should disable bloom filters for these types on parquet for now (and maybe update the tests) until we have fixed https://github.com/apache/arrow-datafusion/issues/9779

**Comment by progval** [comment]
> Technically I think this is a regression

I agree

> as previously bloom filters on these column types would be ignored

only on unsigned columns. they were already not ignored on signed columns.

**Comment by alamb** [comment]
Sounds good -- I think we should still disable bloom filters by default for all types that provide a wrong answer

**Comment by edmondop** [comment]
This seems intermediate and maybe I can try it @alamb what do you think?

**Comment by alamb** [comment]
Thanks @edmondop  that would be great
