### ISSUE TITLE
Intermittent failure in test_files/cte.slt:751

### ISSUE THREAD

**Issue by alamb** [apache/arrow-datafusion#9930]
There is a non deterministic test failure on cte.slt it seems, unrelated to this PR and looks like a non-deterministic test...

Failure: https://github.com/apache/arrow-datafusion/actions/runs/8543135777/job/23406267036?pr=9876

```
External error: query result mismatch:
[SQL] WITH RECURSIVE my_cte AS(
    SELECT 1::int AS a
    UNION ALL
    SELECT a::bigint+2 FROM my_cte WHERE a<3
) SELECT *, arrow_typeof(a) FROM my_cte;
[Diff] (-expected|+actual)
-   1 Int32
-   3 Int32
+   3 Int32
+   1 Int32
at test_files/cte.slt:751
```

_Originally posted by @alamb in https://github.com/apache/arrow-datafusion/issues/9876#issuecomment-2035412270_

I believe this was added in https://github.com/apache/arrow-datafusion/pull/9836 from @jonahgao

**Comment by alamb** [comment]
The same PR tests passed when the same job was rerun:  https://github.com/apache/arrow-datafusion/actions/runs/8543135777/job/23410293407?pr=9876

**Comment by jonahgao** [comment]
take
