### ISSUE TITLE
unnest doesn't take into account null values

### ISSUE THREAD

**Issue by rescrv** [apache/arrow-datafusion#9932]
### Describe the bug

The code [here](https://github.com/apache/arrow-datafusion/blob/main/datafusion/physical-plan/src/unnest.rs#L372) assumes that null lists will be represented as a zero-length offset.  The structure described [in the documentation](https://docs.rs/datafusion/latest/datafusion/common/arrow/array/struct.GenericListArray.html) would break this code if it was used to encode NULL values.

### To Reproduce

Unnesting the example linked in the description should be sufficient.

### Expected behavior

It's expected that the offset will be adjusted for NULL values.

**Comment by alamb** [comment]
Thank you for the report @rescrv  -- is there any chance you can provide a self contained reproducer? I suspect this issue would get fixed quickly if that were available

**Comment by jonahgao** [comment]
take
