### ISSUE TITLE
Move `ceil`, `exp`, `factorial` to `datafusion-functions` crate

### ISSUE THREAD

**Issue by erenavsarogullari** [apache/arrow-datafusion#9939]
### Is your feature request related to a problem or challenge?

As part of #9285 move the `ceil`, `exp`, `factorial` functions to the new `datafusion-functions` crate in the new structure. Follow-up to #9862.

### Describe the solution you'd like

Functions are migrated to the new crate and use the new patterns as described in #9286 & #9216

**Comment by erenavsarogullari** [comment]
take

**Comment by alamb** [comment]
Any update on this ticket @erenavsarogullari

**Comment by erenavsarogullari** [comment]
@alamb Thanks for follow-up, will be submitting PR shortly.

**Comment by alamb** [comment]
> @alamb Thanks for follow-up, will be submitting PR shortly.

Awesome -- thank you @erenavsarogullari 🙏  (I was following up here as I saw @Omega359 's comment https://github.com/apache/arrow-datafusion/issues/9540#issuecomment-2050695033 which got me inspired to help push the functon porting project over the finish line with some cheerleading)

Thanks again
