### ISSUE TITLE
Consolidate push_down_projection tests under optimize_projections

### ISSUE THREAD

**Issue by Jefffrey** [apache/arrow-datafusion#9978]
### Is your feature request related to a problem or challenge?

#8340 removed push_down_projection rules in favour of optimize_projections

### Describe the solution you'd like

Move tests in [push_down_projection.rs](https://github.com/apache/arrow-datafusion/blob/d201ec742b08fa2a0549fc27f0b39622d67391ab/datafusion/optimizer/src/push_down_projection.rs) to [optimize_projections.rs](https://github.com/apache/arrow-datafusion/blob/d201ec742b08fa2a0549fc27f0b39622d67391ab/datafusion/optimizer/src/optimize_projections.rs) and remove the `push_down_projection.rs` file

**Comment by kavirajk** [comment]
take
