### ISSUE TITLE
implement Set Operations UNION

### ISSUE THREAD

**Issue by xudong963** [apache/arrow-datafusion#998]
**Is your feature request related to a problem or challenge? Please describe what you are trying to do.**
From README, I found Set Operations UNION isn't implemented. So I want to implement it.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by xudong963** [comment]
I am blocked at dedup `Vec<RecordBatch>`. Do you have some good ideas? @houqp @alamb

**Comment by Dandandan** [comment]
`Union distinct` effectively means building a structure to deduplicate the same rows. This means:

* Sort and deduplicate based on equivalent consecutive rows (might be fast if data is already sorted)
* Hash all column keys, store in hash table.

My proposal to implement `Union` is to translate `[a] union [b]` into the equivalent `select distinct * from ([a] union all [b])`. This currently uses the hash aggregate based implementation for deduplication. Later it could switch to whatever implementation is more efficient for the particular query.

**Comment by xudong963** [comment]
@Dandandan Thanks for your idea. I have implemented a version. I will consider your idea later.

**Comment by xudong963** [comment]
> I am blocked at dedup `Vec<RecordBatch>`. Do you have some good ideas? @houqp @alamb

@houqp @alamb  The obstacle solved, but may not be the best.

**Comment by alamb** [comment]
Another potential way to implement `UNION` might be to rewrite the logical plan to the equivalent of:

`SELECT x from foo UNION select x from bar` as `SELECT distinct (select x from foo UNION ALL select x from bar)`



`
